loaded_h_0(function(_){var window=this;
_.xhh=_.y("ygEV2c",[_.$dh]);
_.v("ygEV2c");
var yhh=class extends _.m{constructor(a){super(a)}Ba(){return _.t(this,1)}Ma(){return _.t(this,2)}oP(){return _.t(this,3)}eG(){return _.t(this,4)}getAttribute(){return _.t(this,5)}setAttribute(a){return _.Yg(this,5,a)}hasAttribute(){return _.jh(this,5)}getDescription(){return _.t(this,6)}Nh(){return _.tj(this,6)}Da(){return _.B(this,8)}Qa(){return _.Fe(this,9)}Ca(){return _.Aj(this,15,_.ih())}Sa(){return _.Cj(this,16,_.ih())}Pa(){return _.t(this,20)}La(){return _.Cj(this,21,_.ih())}hqa(){return _.Fe(this,
23)}Kx(){return _.n(this,_.HI,27)}Aa(){return _.n(this,_.bfh,31)}Ha(){return _.t(this,30)}N2(){return _.wj(this,32)}};var zhh=class extends _.Wr{static Ta(){return{jsdata:{WD:_.eK},service:{Mna:_.agh}}}constructor(a){super();this.WD=a.jsdata.WD;this.Mna=a.service.Mna;if(_.ide){a=this.WD;let b;const c=(b=_.Fch(this.getRoot()))==null?void 0:b.el();c&&_.Ug(c,"blQGUc",a.serialize())}}Aa(a){var b=a.data,c=_.$eh(new _.bfh,_.Sh(b,12));_.jh(b,13)&&_.Zg(b,13)&&_.afh(c,_.Zg(b,13));_.jh(b,19)&&_.Zg(b,19)&&(a=_.Zg(b,19),_.Yg(c,3,a));a=new yhh;var d=this.WD.La();d=_.mk(a,15,d);var e=this.WD.Ma();d=_.Rh(d,8,e);e=this.WD.Ha();
d=_.Yg(d,1,e);e=this.WD.Pa();d=_.Yg(d,2,e);e=_.Cg("q");d=_.Yg(d,25,e);e=b.zD()||this.WD.Sa();d=_.Yg(d,4,e);e=b.oP()||_.tj(this.WD,3);d=_.Yg(d,3,e);e=this.WD.Za();d=_.ok(d,16,e).setAttribute(_.tj(b,15));e=_.Cj(b,16,_.ih());d=_.ok(d,21,e);d=_.Yg(d,13,google.kEI);e=b.Kx();d=_.Kb(d,_.HI,27,e);c=_.Kb(d,_.bfh,31,c);d=_.Uh(b,20);c=_.Ph(c,32,d);d=_.tj(this.WD,14);_.Yg(c,20,d);_.Ee(b,18)&&(b=_.Sj(b,18),_.si(a,9,b));this.WD.rb()&&(b=_.Zg(this.WD,16),_.Yg(a,30,b));var f;b={productId:(f=a.Aa())==null?void 0:
f.Vq(),allowNonLoggedInFeedback:!0,enableAnonymousFeedback:!1};var g;if((g=a.Aa())==null?0:_.jh(g,2)){let l;b.bucket=(l=a.Aa())==null?void 0:_.t(l,2)}let h;if((h=a.Aa())==null?0:_.jh(h,3)){let l;b.triggerId=(l=a.Aa())==null?void 0:_.t(l,3)}f={expi:a.Ca().join(","),gl:a.Ba(),hl:a.Ma(),internal:a.Da(),vertical_id:a.Sa().join(" "),time:Date.now(),ei:google.kEI,query:_.Cg("q"),entity_id:a.eG(),entity_name:a.oP(),attribute:a.getAttribute(),secondary_entity_id:a.La().join(" "),osrp_ui_vertical:a.Ha(),ve_id:a.Qa(),
fb_ingest:a==null?void 0:a.serialize(),feature_tag:a.N2(),user_interface:a.Pa(),is_dark_theme:!!document.body.dataset.dt};let k;(g=(k=a.Kx())==null?void 0:_.NTd(k))&&Object.assign(f,Object.fromEntries(g));_.tS(b,f)}oa(a){_.Zfh(this.Mna,a.data,this.WD,[],!1,void 0,void 0,this.getData("eau").Ob())}};zhh.prototype.$wa$UhDUnd=function(){return this.oa};zhh.prototype.$wa$y64mt=function(){return this.Aa};_.as(_.xhh,zhh);
_.x();
});
// Google Inc.
