loaded_h_0(function(_){var window=this;
_.TVb=_.y("rtH1bd",[_.K7a]);
var OVb,PVb;_.NVb=function(a){return JSON.stringify(a,(b,c)=>c instanceof Map?Object.fromEntries(c):c)};OVb=function(a,b,c,d){const e=()=>d?a.pop(d,!0):_.xh(),f=()=>c!==d;return b?{Olc:e,dRc:f,nzc:2}:{Olc:e,dRc:f,o5a:()=>c?a.pop(c,!0):_.xh(),nzc:6}};PVb=function(a,b){return{Olc:()=>a.Aa(b.eD())||_.xh(),dRc:()=>!0,nzc:2}};_.QVb=a=>new _.Xt(a);_.QVb=a=>new _.Yt(a);_.RVb=class{constructor(){this.oa=new Map}and(a,...b){return a.call(null,...b,this)}};_.SVb=class{constructor(a,b,c){this.Aa=c;this.converters=a;this.oa=b}mSa(a,{y_a:b={},xfa:c}={}){const d=this.oa.getState()||{id:"",pushId:""};var e=this.Aa||d;e={url:_.QVb(e.url||""),state:e.userData||null};const f=e.url.toString(),g=_.NVb(e.state);for(const k of this.converters.keys())if(a.has(k)){const l=a.get(k);this.converters.get(k).Ap(l,e)}const {replace:h=!1}=b;if(f===e.url.toString()&&g===_.NVb(e.state))return _.Ag(OVb(this.oa,h,d.id,d.id));this.Aa&&(this.Aa.url=e.url.toString(),this.Aa.userData=
e.state);if(!b.Aif)return c?(a=this.oa.navigateToView(e.url.toString(),e.state||void 0,c.Bpa,h,c.event))?a.then(k=>PVb(this.oa,k)):_.xh(Error("Af`"+e.url)):this.oa.pushAsync(e.url.toString(),e.state||void 0,void 0,h,this.oa).then(k=>OVb(this.oa,h,d.id,k))}static compose(...a){const b=new Map;let c,d;for(const e of a){for(const f of e.converters.keys())b.delete(f),b.set(f,e.converters.get(f));c=e.oa;d=e.Aa}return new _.SVb(b,c,d)}};
_.v("rtH1bd");
var UVb,WVb,YVb,$Vb,aWb,bWb,cWb,dWb,eWb;UVb=function(a,b=[]){b.push(a);return b};_.VVb=function(a,b){const c=new Map;for(const e of a)for(const f of e.keys()){a=f;var d=e.get(f);d=b?b(d,c.get(a)):d;c.set(a,d)}return c};WVb=function(a,b){const c=new Map;for(const d of a.keys())c.set(d,b(a.get(d),d));return c};_.XVb=function(a){return _.ng(a)?a:{}};YVb=function(a,b){const c=b.reduce((d,e)=>d|(e&&e.nzc||0),1);return Object.assign({state(d){return(a.get(d)||new d).clone()},CBb(d){return(c&d)===d}},...b)};
$Vb=function(a,b=ZVb){return{getCurrent:a.getCurrent||b.getCurrent,Rza:new Set([...b.Rza,...a.Rza]),T$a:a.T$a||b.T$a}};aWb=function(a){a=_.VVb(a,UVb);return WVb(a,(b,c)=>c.compose(...b))};bWb=function(a){const b=[];for(const c of a)(a=c())&&b.push(a);return b.length?_.yh(b):null};cWb=function(a,b){const c=new Set,d=new Set([...a.keys(),...b.keys()]);for(const e of d)_.Ja(a.getAll(e),b.getAll(e))||c.add(e);return c};
dWb=function(a,b){var c;if(c=!!a&&!!b)a:{a.size>b.size&&([a,b]=[b,a]);for(const d of a)if(b.has(d)){c=!0;break a}c=!1}return c};eWb=function(a=new _.RVb){a.oa.set(_.SVb,null);return a};var ZVb;ZVb={Rza:new Set};_.gWb=function(...a){const b=[];var c=[],d=[];let e;for(const f of a)b.push(f.Rn),c.push(f.CT),d.push(f.cvc),e=f.Jub||e;a=_.VVb(b,$Vb);c=aWb(c);d=aWb(d);return new _.fWb(a,c,d,e)};
_.fWb=class{constructor(a=new Map,b=new Map,c=new Map,d){this.Rn=a;this.CT=b;this.cvc=c;this.Jub=d}run({Aa:a,eventType:b,metadata:c,oa:d}=new _.RVb){const e=new Map;for(const h of this.Rn.keys()){const k=this.Rn.get(h);let l,p,q,r=(q=(p=(l=k).getCurrent)==null?void 0:p.call(l))!=null?q:new h;var f=null;for(const u of k.Rza){const A=u;if(A.ged){if(!A.ged(r.clone(),a))continue;f=A.Uie}else f=u;f=r=f(r,a)}if(f){e.set(h,f);let u,A;(A=(u=k).T$a)==null||A.call(u,f)}}a=[];for(var g of this.CT.keys()){const h=
this.CT.get(g),k=d.get(g);k!==null&&a.push(()=>h.mSa(e,k))}d=h=>{b=b||this.Jub;const k=[],l=YVb(e,h);for(const p of this.cvc.values())k.push(()=>p.notify(e,b,c,l));return(h=bWb(k))?h.then(()=>l):_.Ag(l)};return(g=bWb(a))?g.then(d):d([])}compose(...a){return _.gWb(this,...a)}};_.hWb=class extends _.ho{static Ta(){return{service:{yHc:_.sIb}}}constructor(a){super();this.Ba=[];this.Aa=a.service.yHc;a=this.Aa.getState()||{};this.oa={url:a.url,userData:a.userData,id:"",pushId:""};this.Aa.addListener((b,c,d)=>{if(!(d.source instanceof _.sIb)){if(b.url!==this.oa.url){var e=new _.Xt(b.url||"");c=new _.Xt(this.oa.url||"");var f=cWb(e.searchParams,c.searchParams);e=cWb(e.oa,c.oa)}c=_.XVb(b.userData);var g=_.XVb(this.oa.userData);if(c===g)var h=new Set;else{var k=new Set,l=new Set([...Object.keys(c),
...Object.keys(g)]);for(h of l)_.NVb(c[h])!==_.NVb(g[h])&&k.add(h);h=k}this.oa.url=b.url;this.oa.userData=b.userData;c={url:_.QVb(b.url||""),state:b.userData};b=[];for(const {ZId:p,xRd:q}of this.Ba)g=new Set,k=new Set,l=new Set,q.oa&&(q.oa.D6&&(g=new Set(q.oa.D6())),q.oa.vC&&(k=new Set(q.oa.vC()))),q.Aa&&(l=new Set(q.Aa.keys())),(dWb(g,f)||dWb(k,e)||dWb(l,h))&&b.push(p(c));b.length&&(f=d.y6&&d.y6.length?1:0,d=d.source instanceof _.Dgb,e=_.gWb(...b),b=e.run,h=new _.RVb,h.metadata={reason:f,userInitiated:d},
b.call(e,h.and(eWb)))}})}};_.Zf(_.TVb,_.hWb);
_.x();
_.$kr=null;
var Ikd,Mkd;_.Jkd=function(){Ikd.set(_.Zt().toString(!0),_.wm())};_.Kkd=function(){return Ikd.get(_.Zt().toString(!0))};_.Lkd=function(){const a=_.Kkd();a&&_.SD.fixedUiScrollTo(a.x,a.y)};_.Nkd=function(){Mkd||(Mkd=_.me(document.documentElement,"touchmove",_.SJa));document.body.style.overflow="hidden"};_.Okd=function(){Mkd&&(_.qn(Mkd),Mkd=null);document.body.style.overflow=""};_.Pkd=function(a){a&&_.SD.Ca(0,a)};Ikd=_.tg("s",_.UNa);_.Qkd=null;Mkd=null;_.me(window,"popstate",function(){_.Qkd=_.wm()});
var Ykd,eld,mld,Xkd,sld,uld,nld,yld,Ald,lld,wld,Cld,Vkd,Wkd,tld,vld,bld,fld,xld,gld,Ukd,kld,qld,zld,cld;_.Rkd=function(a,b,c){_.Jkd();b=b||{};b.fpstate=a;_.yg(b,c)};_.Tkd=function(a){_.Skd(!0,a)};_.Skd=function(a,b){const c={};_.Ka(b||[],d=>{c[d]=""});c.fpstate="";_.yg(c,a)};
_.ald=function(a,b){Ukd++;if(window.getSelection){const f=window.getSelection();f&&f.removeAllRanges()}let c=!1,d=!1;_.Ka(a,f=>{if(f===1)_.Cg("trex")?d=!0:c=!0;else{var g=_.Gg(f);if(g!==document.body){var h=f["fp-s"];h||(h=_.Am("DIV"),f["fp-s"]=h);g?_.Fm(h,f):(g=_.Gg(h))&&g.removeChild(h);_.pJc(f,f);document.body.appendChild(f)}_.Qm(f,{"margin-top":-_.SD.getHeaderPaddingHeight()+"px","margin-bottom":-_.SD.getFooterPaddingHeight()+"px"});f["fp-i"]=Ukd;_.lm.remove(f,"fCjVlb");_.gJc(f,"t3L5Dd")}});_.Ka(document.body.children,
f=>{if(!(Vkd.has(f.tagName)||Wkd.test(f.id)||f.id==="lb"||f["fp-i"]===Ukd||f.hasAttribute("data-imig")))if(_.lm.remove(f,"r3xA2d"),f&&f["fp-i"]>0){Xkd(f);const g=f["fp-s"];g&&f&&f["fp-i"]>0&&(g.parentNode?(_.Fm(f,g),_.Hm(g)):_.Hm(f));f.parentNode!==document.body||_.lm.add(f,"fCjVlb")}else _.lm.enable(f,"fCjVlb",!c),f&&f.id.startsWith("trex_")&&_.lm.enable(f,"fCjVlb",!d)});let e;((e=google)==null?0:e.uh)?google.uh("fpstate"):_.gn(document.body,"");b!==!1&&(c&&!Ykd()?_.Zkd():_.$kd())};
Ykd=function(){const a=_.lm.contains(document.body,"qs-i"),b=!!_.Cg("istate"),c=!!_.Cg("trex"),d=_.Cg("oshop")==="apv";return a||c||b||d};eld=function(a){if(a===bld)return cld;let b=_.dld[bld+"\n"+a];return b?b:bld==="&"?cld:(b=_.dld["*\n"+a])?b:(b=_.dld[bld+"\n*"])?b:cld};
mld=function(a){var b=fld;b=b===1?b:b;if(gld!==1){var c=gld;c.style.top="";_.lm.remove(c,"ca1MEe")}_.ald([b],!1);(c=_.hld.get(bld))&&c.Jra&&c.Jra.call(null);if(c=b===1?null:b)_.lm.add(document.body,"QjZ1Sd"),_.lm.add(c,"ca1MEe"),_.lm.remove(c,"r3xA2d"),c.focus();if(_.ild){const f=_.ild;var d=f.x,e=f.y+_.SD.getScrollTop();_.SD.fixedUiScrollTo(d,e);c&&(f.x&&(c.style.left=""),f.y&&(c.style.top=""))}else _.jld!==1&&(c=_.SD.getScrollTop(),_.SD.fixedUiScrollTo(0,c));_.ild=null;b!==1||Ykd()?_.Gkd||_.wla||
_.vla||_.$kd():_.Zkd();bld=a;gld=b;fld=null;kld&&(_.qn(kld),kld=null);_.Okd();lld();(a=_.hld.get(a))&&a.Smb&&a.Smb.call(null)};_.Zkd=function(){if(_.ula)_.SD.oa(1);else{const a=_.eg(document);_.Yf(_.Pu,a.Yp()).then(b=>{b&&b.isAvailable()&&b.exitBasicMode(12)})}};_.$kd=function(){if(_.ula)_.SD.oa(3);else{const a=_.eg(document);_.Yf(_.Pu,a.Yp()).then(b=>{b&&b.isAvailable()&&b.enterBasicMode(12)})}};Xkd=function(a){_.Qm(a,{"margin-top":"","margin-bottom":""})};
sld=function(a){if(a===""){_.Cg("istate")&&_.zg("istate",_.Cg("istate"),!0);var b=_.Zt().pathname();b!=="/search"&&(b=nld(b))&&(b=_.old.get(b))&&(a=b.state)}a!==_.pld&&(_.pld=a,a===""||_.hld.has(a))&&(qld?(b=()=>void _.rld(a),qld.promise.then(b,b)):_.rld(a))};uld=function(a){return a&&(a=tld.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};nld=function(a){return(a=vld.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};
yld=function(a){a=a.Qh;const b=uld(a.newURL);if(b===_.pld){const c=uld(a.oldURL);/#(.*&)?trex=/.test(a.oldURL)||c===b||wld()||!xld||(a=xld,_.SD.fixedUiScrollTo(a.x,a.y))}};_.rld=function(a){if(bld==="&"&&a==="")bld=a;else if((0,_.Wn)(new zld),a==="")Ald(a,1),_.gJc(document.body,"ABuafc");else{bld===""&&_.gJc(document.body,"hcY69");var b=_.hld.get(a);if(b&&(b=b.eea.call(null,bld))){_.Kg(b)?Ald(a,b):b.then(c=>{Ald(a,c)},()=>{lld()});return}lld()}};
Ald=function(a,b){const c=eld(a),d=typeof c.s5b==="function"?c.s5b(bld,a,c.cFc):c.s5b;var e=b===1;const f=d!==1||gld===1?null:gld,g=d!==0||b===1?null:b;fld=b;_.jld=d;xld=_.wm();if(f){const k=xld;Bld(f,b);f.style.top=_.SD.getScrollTop()-k.y+"px"}g&&Bld(g,gld);e&&_.lm.remove(document.body,"QjZ1Sd");!e&&(_.Gkd||_.wla||_.vla)&&_.$kd();kld||(kld=_.me(document.documentElement,"touchstart",_.SJa));_.Nkd();if((e=_.hld.get(a))&&e.onReady)try{e.onReady.call(null)}catch(k){Cld(k);return}d===1?_.Lkd():d===0&&
a!==""&&bld!==""&&(_.ild=_.Kkd(),xld=null);let h;try{h=c.cFc.call(null,gld,b)}catch(k){}h?(h.then(()=>{mld(a)},k=>{mld(a);throw k;}),g&&_.ild&&(b=_.ild,b.x&&(g.style.left=-b.x+"px"),b.y&&(g.style.top=-b.y+"px"))):mld(a)};lld=function(){qld&&(qld.resolve(),qld=null)};wld=function(){if(_.jld!=null){var a=_.jld===1;if(_.ild){if(a||fld===1){var b=_.ild;a=b.x;b=b.y+_.SD.getScrollTop();_.SD.fixedUiScrollTo(a,b);return!0}}else if(a)return!0}return!1};
Cld=function(a){_.jld=fld=null;_.ald([gld]);kld&&(_.qn(kld),kld=null);_.Okd();lld();throw a;};Vkd=new Set(["SCRIPT","STYLE"]);Wkd=RegExp("^(abbl|abblt|gbbl-\\d+|gbblt-\\d+|snbc|duf3c)$");tld=/#(?:.*&)?fpstate=([^&]*)/;vld=/^\/?([^\/]*)/;_.hld=new Map;_.old=new Map;bld="&";_.pld="&";fld=null;xld=null;_.ild=null;_.dld={};_.jld=null;gld=1;Ukd=0;kld=null;qld=null;zld=class{constructor(){this.p6a=void 0;qld=_.Bf()}play(){return qld?qld.promise:Promise.resolve()}finish(){lld()}Pm(){return 2E3}};
cld={cFc:function(){return _.Ag()},s5b:0};_.Koa(()=>{_.vg("fpstate",sld);_.me(window,"hashchange",yld)});var Bld=function(a,b){_.ald([a,b],!1);Xkd(a);_.lm.add(a,"r3xA2d")};
_.zw=function(a,b=new _.RVb){const c=b.oa.get(_.SVb)||{};c.y_a=a;b.oa.set(_.SVb,c);return b};
var kWb,oWb,qWb,rWb,sWb;kWb=function(a,b=new Set){for(const c of a)b.add(c);return b};_.lWb=function(a,b){return b};_.mWb=function(a,b=new _.RVb){b.Aa=a;return b};_.hw=function(){return _.Yf(_.hWb)};_.nWb=function(a,b,c,d){return new _.SVb(new Map([[a,b]]),c,d)};
oWb=class{constructor(a=new Map){this.oa=a}notify(a,b,c,d){for(const e of a.keys())if(this.oa.has(e))for(const f of this.oa.get(e))try{f(a.get(e).clone(),b,c,d)}catch(g){_.fa(g)}}static compose(...a){const b=[];for(const c of a)b.push(c.oa);a=_.VVb(b,kWb);return new oWb(a)}};
_.pWb=function(a,{getCurrent:b,Rza:c=[],T$a:d,CT:e=[],listeners:f=[],cvc:g=[],Jub:h}={}){const k=new Map;for(const l of e)k.set(l.constructor,l);e=new Map;f&&e.set(oWb,new oWb(new Map([[a,new Set([...f])]])));for(const l of g)e.set(l.constructor,l);return new _.fWb(new Map([[a,{getCurrent:b,Rza:new Set(c),T$a:d}]]),k,e,h)};
_.iw=class{constructor(a,b,c={}){this.oa=a;this.Aa=b;this.Ba=c.iUb||(d=>_.ng(d)?d:{});this.Ca=c.H2b||((d,e)=>e)}Bo(a,b){this.oa&&this.oa.Bo&&this.oa.Bo(a.url,b);this.Aa&&this.Aa.Bo(this.Ba(a.state),b)}Ap(a,b){this.oa&&this.oa.Ap&&this.oa.Ap(a,b.url);if(this.Aa){const c=Object.assign({},this.Ba(b.state));this.Aa.Ap(a,c);a=Object.assign({},_.ng(b.state)?b.state:{});b.state=this.Ca(a,c)}}};qWb=function(a){const b=a.Aa.getState()||{};return{url:_.QVb(a.Aa.getCurrentUrl()),state:b.userData}};
rWb=function(a,b){a.Ba.push(b)};
_.jw=function(a,b,c){const d=b.Fr();b.Da(_.nWb(d,c,a.Aa,a.oa));b.Pa(h=>{const k=qWb(a);c.Bo(k,h)});let e=!1;const f=new d,g=_.pWb(d,{Rza:[h=>{const k=qWb(a);c.Bo(k,f);c.Bo(k,h);return h}],listeners:[()=>{e||(e=!0,rWb(a,{ZId:h=>b.transition(k=>{c.Bo(h,k);return k},"IaLTGb"),jke:h=>{const k=new d;return b.Ma(l=>{if(!c.oa)return!1;const p=_.QVb("");let q,r;(r=(q=c.oa).Ap)==null||r.call(q,l,p);h(p);let u,A;(A=(u=c.oa).Bo)==null||A.call(u,p,k);return!_.Kk(k,l)},()=>k,"IaLTGb")},xRd:c}))}]});b.Ha(g)};
sWb=function(a,b,c){a.listeners.set(b,c);return a};_.kw=function(a,b,c){sWb(a,c,(d,e,f,g)=>{b===e&&c(d,f,g)})};
_.lw=class{constructor(a){this.Aa=a;this.state=new this.Aa;this.CT=new Set;this.listeners=new Map;this.Ia=new Set;this.Ba=()=>{const b=this.state.clone();for(const c of this.Ia)c(b);return b};this.Ca=b=>{this.state=b};this.La=(b,c,d,e)=>{for(const f of this.listeners.values())try{f(b.clone(),c,d,e)}catch(g){_.fa(g)}};this.oa=_.pWb(this.Aa,{getCurrent:this.Ba,listeners:[this.Ca]})}Fr(){return this.Aa}listen(a){return sWb(this,a,a)}unlisten(a){this.listeners.delete(a)}get(){return this.Ba()}transition(a,
b="E8jfse"){return _.pWb(this.Aa,{getCurrent:this.Ba,Rza:[a],T$a:this.Ca,CT:this.CT,listeners:[this.La],Jub:b})}Ma(a,b,c="E8jfse"){return _.pWb(this.Aa,{getCurrent:this.Ba,Rza:[{ged:a,Uie:b}],T$a:this.Ca,CT:this.CT,listeners:[this.La],Jub:c})}initialize(a=new Map){if(!this.oa)return Promise.resolve();var b=this.oa,c=b.run,d=new _.RVb;d.eventType="sKlcvd";a=c.call(b,d.and(_.mWb,a));this.oa=null;return a}Ha(a){this.oa&&(this.oa=this.oa.compose(a))}Da(a){this.CT.add(a)}Pa(a){this.Ia.add(a)}};_.mw=class{constructor(a){const b=_.pWb(a.Fr(),{Rza:[(c,d)=>(d=d.get("R84DPe")||null)?d.clone():c]});a.Ha(b)}};
var alr=class{constructor(){this.oa=[]}async run(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{if(a.length){var e=a[0];for(let g=1;g<a.length;g++)e=e.compose(a[g]);var f=c(await d(e.run(_.zw({replace:!!b}))));f.CBb(4)&&this.oa.push(f)}}finally{d()}}goBack(){return this.oa.length>0?this.oa.pop().o5a():_.Ag()}};var elr,flr,clr,blr;_.dlr=function(a,b){blr==null&&(blr=new clr(a,b));return blr};elr=function(a){if(a=="")return{G6a:!0};var b=a.split(",");if(b.length<2)return{G6a:!1,ivb:null};a=b[0];const c=b[1];let d="";b.length>=2&&(d=b[2]);let e="";b.length>=3&&(e=b[3]);b=_.om(c);let f=null;b&&(d||e)&&(f=b.querySelector(e?`[data-local-attribute=${e}]`:`[data-dtype=${d}]`));return{G6a:!1,entryPoint:a,Yja:c,widget:d,ivb:b,Hld:f,HMa:e}};
flr=function(a,b){return a.G6a!=b.G6a||a.entryPoint!=b.entryPoint||a.Yja!=b.Yja||a.widget!=b.widget||a.HMa!=b.HMa};
_.glr=function(a,b){var c=elr(a.oa),d=elr(b);if((flr(c,d)||a.Aa)&&!(b.indexOf("d3sbx")>=0))if(d.G6a){if(a.oa=b,a.Ca=!1,d=_.$kr)a.Aa?(a.Aa=!1,d.closeDialog(),d.kZa()):d.uLa()}else if(d.ivb){a.oa=b;a.Ca=!1;if(c.ivb){if((b=!c.G6a&&!d.G6a&&c.entryPoint==d.entryPoint&&c.Yja==d.Yja&&(c.widget!=d.widget||c.HMa!=d.HMa))&&d.widget)d.Hld&&(c=_.$kr)&&c.Vnb(d.Hld);else{c=a.Aa;a.Aa=!1;const e=_.$kr;e&&e.closeDialog();if(c){e&&e.kZa();return}}if(b)return}a.Ha=d.widget||"";a.Da=d.HMa||"";a=_.dJc(d.ivb);a.set("entry_point",
d.entryPoint);_.lz(d.ivb,{context:a})}else a.yh(""),a.Ca=!0};_.hlr=function(a,b){return a.Bca.transition(c=>c.setValue(b))};_.ilr=function(a,b){return a.nE.transition(c=>c.Ca(b))};
clr=class{constructor(a,b){this.nE=a;this.Bca=b;this.Da=this.Ha=this.oa="";this.Ca=this.Ia=this.Aa=!1;this.Ba=new alr;this.Bca.get().getValue().trim()&&(this.Ia=!0);this.Bca.listen(c=>{this.mM(c)});this.mM(this.Bca.get())}mM(a){(0,_.Df)(()=>_.glr(this,a.getValue()))}async yh(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{if(this.Ha){const h=document.querySelector(this.Da?"[data-local-attribute="+this.Da+"]":"[data-dtype="+this.Ha+"]");h&&(0,_.Df)(()=>{const k=_.$kr;k&&k.Vnb(h)});this.Da=this.Ha=""}else{var e=
elr(this.oa),f=elr(a);if(flr(e,f)){this.oa=a;var g=this.nE.get().Aa();if(_.qw()||!(f.widget!=""&&f.widget!=void 0||g!=""&&g.startsWith("d3")))c(await d(this.Ba.run([_.hlr(this,a)],!!b)));else{let h=f.widget||"";const k=f.Yja+"-"+h;_.hld.has(k)&&(h=k);_.Jkd();c(await d(this.Ba.run([_.hlr(this,a),_.ilr(this,h)],!!b)))}}}}finally{d()}}La(){this.Aa=!0;this.Ba.goBack()}goBack(){return this.Ba.goBack()}};blr=null;var jlr=class extends _.m{constructor(a){super(a)}getValue(){return _.t(this,1)}setValue(a){return _.Yg(this,1,a)}clearValue(){return _.Oe(this,1)}hasValue(){return _.jh(this,1)}};jlr.prototype.kb="bgmrdf";var klr={vC(){return["duf3"]},Bo(a,b){_.Rv(new _.Yv(a.oa,b),"duf3",b.setValue,b.clearValue)},Ap(a,b){_.Vv(new _.Yv(b.oa,a),a.hasValue,a.getValue,"duf3")}};var llr;llr=null;_.mlr=class extends _.lw{constructor(a,b){super(a);new _.mw(this);_.jw(b,this,new _.iw(klr))}static Fr(){return jlr}static Yr(a){return llr?llr:llr=_.hw().then(b=>{b=new _.mlr(jlr,b);b.initialize(a);return b})}};_.So.bgmrdf=_.Ro;
_.eyq=_.y("EkevXb",[]);
var sXb=class extends _.m{constructor(a){super(a)}Aa(){return _.t(this,1)}Ca(a){return _.Yg(this,1,a)}Da(){return _.Oe(this,1)}Ba(){return _.jh(this,1)}};sXb.prototype.kb="OLea4d";var tXb={vC(){return["fpstate"]},Bo(a,b){_.Rv(new _.Yv(a.oa,b),"fpstate",b.Ca,b.Da)},Ap(a,b){_.Vv(new _.Yv(b.oa,a),a.Ba,a.Aa,"fpstate")}};var uXb;uXb=null;_.vXb=class extends _.lw{constructor(a,b){super(a);new _.mw(this);_.jw(b,this,new _.iw(tXb))}static Fr(){return sXb}static Yr(a){return uXb?uXb:uXb=_.hw().then(b=>{b=new _.vXb(sXb,b);b.initialize(a);return b})}};_.So.OLea4d=_.Ro;
_.v("EkevXb");
_.as(_.eyq,class extends _.Wr{static Ta(){return{Xe:{nE:_.vXb,Bca:_.mlr}}}constructor(a){super();a=this.oa=_.dlr(a.Xe.nE,a.Xe.Bca);a.Ca&&_.glr(a,a.Bca.get().getValue())}});

_.x();
_.bgh=_.y("fCxEDd",[]);
_.v("fCxEDd");
_.cgh=class extends _.ho{constructor(){super();this.Ixa=null}};_.Zf(_.bgh,_.cgh);
_.x();
_.end=_.y("WlNQGd",[]);
_.dnd=function(a){const b=a.event.detail;return b&&b.type?b.type==="menu_item_selected":String(a.type)==="mMf61e"};
_.v("WlNQGd");
var fnd,hnd,gnd,ind,jnd,lnd,knd,mnd,ond,nnd;fnd=class{constructor(a,b,c){this.trigger=a;this.eza=b;this.iK=c}};hnd=function(a){var b=a.oa();_.Ka(b,c=>{const d=_.ZD(a,c);if(d.isSelected()&&d.isEnabled())switch(d.getType()){case 2:gnd(a);d.Pk(!0);a.Da=c;break;case 3:d.Pk(!0);a.Ia.push(c);break;default:d.Pk(!1)}else d.Pk(!1)},a);b=b[0];_.ZD(a,b).oa()&&b.setAttribute("tabindex","0")};_.ZD=function(a,b){return a.bXa.find(c=>c.getRoot().el()===b)};gnd=function(a){a.Da&&(_.ZD(a,a.Da).Pk(!1),a.Da=null)};
ind=function(a,b,c=!1){if(b){const d=_.ZD(a,b);if(!d.isEnabled()&&c)return;d.Aa(!0);d.oa()&&b.setAttribute("tabindex","0")}else a.menu.setAttribute("tabindex","0"),a.menu.focus();a.Aa!==b&&a.Aa&&(c=_.ZD(a,a.Aa),c.oa()&&a.Aa.setAttribute("tabindex","-1"),c.Aa(!1));a.Aa=b};jnd=function(a,b){return!!a.oa().find(c=>c===b)};
lnd=function(a,b,c){const d=_.ZD(a,b);if(d.isEnabled()){ind(a,b);switch(d.getType()){case 2:var e=a.Da!==b;e&&(gnd(a),a.Da=b,d.Pk(!0));knd(a,d,e,c);break;case 3:e=!d.isSelected();d.Pk(e);e?a.Ia.push(b):_.Ca(a.Ia,b);knd(a,d,!0,c);break;case 5:a=a.getRoot().el();_.Sg(a,"LyWNEf");break;case 11:c=a.getRoot().el();a={trigger:b,Twd:a.oa()};_.Sg(c,"pjqKnd",a);break;default:knd(a,d,!1,c)}d.isSelected()}};knd=function(a,b,c,d){a=a.getRoot().el();_.Sg(a,"mMf61e",new fnd(b,c,d))};
mnd=function(a){a=a.targetElement;let b,c;for(;a.el()!=null&&((b=a.el())==null?void 0:b.tagName)!=="G-MENU-ITEM"&&((c=a.el())==null?void 0:c.tagName)!=="G-MENU";)a=a.parent();let d;return((d=a.el())==null?void 0:d.tagName)==="G-MENU-ITEM"?a.el():null};ond=function(a,b){return(b?nnd(a,!0):a.oa()).find(c=>_.ZD(a,c).isEnabled()?(c=_.ZD(a,c).getContent(),_.raa(c,a.prefix)):!1)};
nnd=function(a,b){let c=a.Aa,d=a.oa().filter(e=>_.kn(e));c===null&&(a.menu.getAttribute("tabindex")==="0"||d.length>0&&d[0].getAttribute("tabindex")==="0")&&(c=b?_.va(d):d[0]);c&&(a=d.findIndex(e=>c===e),d=_.lpb(d,b?-a-1:-a),a=d.findIndex(e=>c===e));return d};
_.$D=class extends _.Wr{static Ta(){return{controllers:{bXa:{jsname:"NNJLud",ctor:_.ph},fbe:{jsname:"hgDUwe",ctor:_.ph},qBd:{jsname:"tqp7ud",ctor:_.ph}}}}constructor(a){super();this.Da=null;this.Ia=[];this.Aa=null;this.prefix="";this.bXa=[...a.controllers.bXa,...a.controllers.fbe,...a.controllers.qBd];this.menu=this.getRoot().el();this.Qa=_.Wla(this.menu)==="listbox";this.Ma=new _.zr(this.ub,1E3,this);_.pi(this,this.Ma);hnd(this)}Jb(){return this.Aa}oa(){const a=[...this.Ib("NNJLud").toArray()].filter(c=>
!_.ZD(this,c).KBb()),b=this.qb("tqp7ud").el();b&&a.push(b);return a}Lb(){return this.bXa}ub(){this.prefix=""}clearSelection(){for(const a of this.oa()){const b=_.ZD(this,a);if(b.isSelected()&&b.isEnabled())switch(b.getType()){case 2:gnd(this);break;case 3:this.Ia.pop();break;case 1:case 7:case 6:case 4:case 5:case 10:break;default:b.getType()}b.Pk(!1)}ind(this,null)}Ba(a,b=!1){jnd(this,a)&&lnd(this,a,b)}yp(){return this.Da}Qb(){return this.Ia}Cb(){return this.Aa}Ca(){const a=this.yp();return a?_.ZD(this,
a).getContent():""}Pa(){const a=this.oa()[0];return a?this.getElementToFocus(a):null}Kb(a=!1){const b=this.yp();b&&this.Qa?a=b:a?a=(a=_.va(this.oa()))?this.getElementToFocus(a):null:a=this.Pa();return a}getElementToFocus(a){var b=_.ZD(this,a);if(b.getType()!==6&&b.getType()!==10)return a;b=(new _.oo([a])).find("*").toArray();return(a=[a].concat(b).find(c=>_.Kg(c)&&_.kn(c)&&(c.getAttribute("role")==="menuitem"&&c.hasAttribute("tabindex")||_.Lm(c))))?a:null}Ha(a){a&&!jnd(this,a)||ind(this,a)}Ub(a){const b=
mnd(a);if(b){var c=a.event;(c=c?c.which||c.keyCode:null)&&c===32?this.Sk(a):lnd(this,b,!0)}}Wa(){this.Aa===null&&ind(this,this.oa()[0])}Xa(){var a=this.getRoot().el();_.Sg(a,"OVY1kd")}Za(){var a=this.getRoot().el();_.Sg(a,"nunXZ");ind(this,null)}rb(a){(a=mnd(a))&&ind(this,a,!0)}Sk(a){const b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode;let d=!1;if(c===27)return!0;if(c===40||c===38){var e=this.Aa;const g=this.oa();e=c===38?e===g[0]:e===g.pop();if(!this.Qa||
!e){c=40===c;e=nnd(this,c);var f;c=(f=c?e.shift():e.pop())!=null?f:null;ind(this,c);this.La(this.Aa)}}else if(c===13||c===32&&!this.prefix)this.Aa&&(d=_.ZD(this,this.Aa).getType()===6||_.ZD(this,this.Aa).getType()===10,lnd(this,this.Aa,!0));else if(_.nKa(c))this.Ma.start(),f=String.fromCharCode(c),this.prefix===f?f=ond(this,!0):(this.prefix+=f,f=ond(this,!1)),f&&(ind(this,f),this.La(this.Aa));else return!1;if(a.wb.el().contains(b.target)){let g;(g=b.stopPropagation)==null||g.call(b);if(!d){let h;
(h=b.preventDefault)==null||h.call(b)}}return!1}La(a){a&&(this.Sa(a),(a=this.getElementToFocus(a))&&a.focus())}Sa(a,b){if(a){var c=_.en(this.menu);if(c.height<this.menu.scrollHeight){var d=this.menu.getBoundingClientRect().top;const e=_.en(a);d=a.getBoundingClientRect().top-d;const f=e.height/2;d<f?this.menu.scrollTop+=d-f:d+e.height>c.height-f&&(this.menu.scrollTop+=d+e.height-c.height+f);b&&(this.menu.scrollTop+=a.getBoundingClientRect().top-this.menu.getBoundingClientRect().top-Math.floor((c.height-
e.height)/2))}}}};_.$D.prototype.$wa$uYT2Vb=function(){return this.Sk};_.$D.prototype.$wa$IgJl9c=function(){return this.rb};_.$D.prototype.$wa$Tx5Rb=function(){return this.Za};_.$D.prototype.$wa$WOQqYb=function(){return this.Xa};_.$D.prototype.$wa$h06R8=function(){return this.Wa};_.$D.prototype.$wa$PSl28c=function(){return this.Ub};_.$D.prototype.$wa$xpRsNe=function(){return this.Pa};_.$D.prototype.$wa$OG2qqc=function(){return this.Ca};_.$D.prototype.$wa$kvm28d=function(){return this.Cb};
_.$D.prototype.$wa$mFs2Sc=function(){return this.Qb};_.$D.prototype.$wa$Urwwkf=function(){return this.yp};_.$D.prototype.$wa$J2hPTe=function(){return this.clearSelection};_.$D.prototype.$wa$gSmKPc=function(){return this.Lb};_.$D.prototype.$wa$lSpRlb=function(){return this.oa};_.$D.prototype.$wa$mJ60jb=function(){return this.Jb};_.as(_.end,_.$D);
_.x();
_.fQi=_.y("UHgVpe",[_.Kq,_.Vq,_.Sq,_.bgh,_.end]);
_.dQi=function(a,b){return _.ti(a,1,_.rTc,b)};_.eQi=_.Sb(_.BTc);
_.cQi=class extends _.m{constructor(a){super(a)}Pib(){return _.t(this,1)}G5(){return _.t(this,3)}getData(){return _.$i(this,4)}setData(a){return _.ik(this,4,a)}hasData(){return _.Ck(this,4)}getFileName(){return _.t(this,5)}dD(){return _.t(this,6)}cda(){return _.tj(this,6)}HQ(){return _.t(this,7)}};
_.XPi=class extends _.m{constructor(a){super(a)}getWidth(){return _.vj(this,3)}Bi(){return _.yk(this,3)}Dj(){return _.Zi(this,3)}getHeight(){return _.vj(this,4)}Ig(){return _.yk(this,4)}};_.YPi=class extends _.m{constructor(a){super(a)}getZoom(){return _.vj(this,4,1)}setZoom(a){return _.Qh(this,4,a)}};_.ZPi=class extends _.m{constructor(a){super(a)}Ox(){return _.t(this,1)}zp(){return _.t(this,2)}};_.$Pi=class extends _.m{constructor(a){super(a)}};
_.aQi=class extends _.m{constructor(a){super(a)}getType(){return _.wj(this,1)}setType(a){return _.jk(this,1,a)}EQ(){return _.n(this,_.$Pi,5)}JZ(a){return _.Kb(this,_.$Pi,5,a)}};_.aQi.prototype.Aa=_.Ub(_.mOi);_.bQi=_.Rb(_.aQi,_.mOi);
_.xPi=!!(_.Bi[49]>>17&1);_.yPi=!!(_.Bi[49]>>18&1);_.zPi=!!(_.Bi[49]>>19&1);_.APi=!!(_.Bi[49]>>21&1);_.BPi=!!(_.Bi[49]>>22&1);_.CPi=!!(_.Bi[49]>>23&1);_.DPi=!!(_.Bi[49]>>24&1);_.EPi=!!(_.Bi[49]>>25&1);_.FPi=!!(_.Bi[49]>>26&1);_.GPi=!!(_.Bi[49]>>27&1);_.HPi=!!(_.Bi[49]>>28&1);_.IPi=!!(_.Bi[49]>>29&1);_.JPi=!!(_.Bi[50]&1);_.KPi=!!(_.Bi[50]&2);
_.uPi=!!(_.Bi[15]>>23&1);_.vPi=!!(_.Bi[15]>>24&1);_.wPi=!!(_.Bi[15]>>25&1);
_.ePi=!!(_.Bi[16]>>27&1);_.fPi=!!(_.Bi[16]>>28&1);_.gPi=!!(_.Bi[17]&4);_.hPi=!!(_.Bi[17]&16);_.iPi=!!(_.Bi[17]&128);_.jPi=!!(_.Bi[17]&1024);_.kPi=!!(_.Bi[17]&2048);_.mV=!!(_.Bi[17]&4096);_.lPi=!!(_.Bi[17]>>14&1);_.mPi=!!(_.Bi[17]>>15&1);_.nPi=!!(_.Bi[17]>>16&1);_.oPi=!!(_.Bi[17]>>17&1);_.pPi=!!(_.Bi[17]>>20&1);_.qPi=!!(_.Bi[17]>>23&1);_.rPi=!!(_.Bi[17]>>24&1);_.sPi=!!(_.Bi[17]>>26&1);_.tPi=!!(_.Bi[17]>>27&1);
_.v("UHgVpe");
var hQi,kQi,lQi,mQi,iQi,gQi,pQi;hQi=function(a,b,c,d){c&&(_.Si(c,_.aQi,7)?a.searchParams.set("vsint",_.Ma(gQi(_.n(c,_.aQi,7)),4)):d&&_.Fe(b,3)>1&&(b=(0,_.bQi)(_.Oa(d)),b=_.Oe(b,7),a.searchParams.set("vsint",_.Ma(gQi(b),4))))};
_.jQi=function(a,b,c,d,e){let f=2;const g=async()=>{var h=(0,_.Rf)(),k=h();h=h(1);try{if(a!=null&&a.isAvailable()){var l=new _.Yt(b.Jf()),p=l.searchParams.get("udm"),q=l.searchParams.get("nem");if(p!=="50"&&q!=="143"){try{h(await k(a.rb(r=>{const u=new _.Yt(e);var A=r.Jta(),E;const I=(E=_.hh(r,_.xOi,2,_.ih())[0])==null?void 0:_.n(E,_.mTd,2);E=I?_.Ma((0,_.WPi)(I),4):null;const N=u.searchParams.get("q");var P=u.searchParams.get("vsrid");P=E&&E!==P;const T=new _.ATc;_.Ik(r,9).forEach((la,da)=>{u.searchParams.set(da,
la)});([4,6,7].includes(_.wj(r,15))||_.B(r,12))&&u.searchParams.set("imgn","1");u.searchParams.set("aep","63");_.FPi&&u.searchParams.set("lns_oq",N);const X=_.DPi?d.Ixa:null;let ca;(ca=r.mJc())==null||_.hh(ca,_.rTc,1,_.ih()).filter(la=>_.xPi||!_.Ui(la,_.cQi,1,_.Uz)).forEach(la=>{_.dQi(T,la)});X?(u.searchParams.set("mstk",X),u.searchParams.set("csuir","1"),u.searchParams.set("aioh","1"),u.searchParams.set("mq",A),!P&&_.gPi||u.searchParams.set("mqvsrid",E)):(l.searchParams.has("vsrid")?u.searchParams.set("q",
A):_.yPi?(_.dQi(T,(new _.rTc).kc(iQi(N).setIcon((new _.Tz).setType(79).setSize(22)))),u.searchParams.set("q",A)):u.searchParams.set("q",N?`${N} ${A}`:A),_.hh(T,_.rTc,1,_.ih()).length>0&&u.searchParams.set("aai",_.Ma((0,_.eQi)(T),4)),u.searchParams.delete("csuir"),u.searchParams.delete("mstk"),u.searchParams.delete("aioh"));_.wj(r,13)===2&&(u.searchParams.delete("udm"),u.searchParams.set("nem","143"));I&&(u.searchParams.set("vsrid",E),(A=Number(l.searchParams.get("lns_surface")))&&A===42&&hQi(u,I,
_.hh(r,_.xOi,2,_.ih())[0],l.searchParams.get("vsint")));c.navigateTo(_.oc(u.toString()))}))),f=0}catch(r){h(),_.bf(Error("op`"+r)),f=1}if(_.wPi)try{h(await k(a.Lc(()=>{c.navigateTo(_.oc(b.location.origin+"/search?udm=50&atvm=1"))})))}catch(r){h(),_.bf(Error("pp`"+r))}}}}finally{k()}};g();window.addEventListener("visibilitychange",()=>{window.document.visibilityState==="visible"&&f===1&&g()})};
kQi=function(a){a.searchParams.delete("udm");a.searchParams.delete("tbm");a.searchParams.delete("nem");a.searchParams.delete("nep");a.searchParams.delete("start");a.searchParams.delete("num");a.searchParams.delete("oq");a.searchParams.delete("gs_lp");a.searchParams.delete("ism");a.searchParams.delete("inm");a.searchParams.delete("source");a.searchParams.delete("si")};lQi=function(a){switch(a){case 0:return"-1";case 1:case 3:return"0";case 4:return"1";case 2:return"2"}};
_.nQi=function(a,b,c,d,e,f){return mQi(a,"0",b,"",c,d,e,f)};
mQi=function(a,b,c,d,e,f,g,h){a.searchParams.has("vsrid")&&!a.searchParams.has("q")&&a.searchParams.set("q","");d!==""&&(a.hostname=d);e&&a.searchParams.has("q")&&!f&&a.searchParams.set("q",e);kQi(a);for(const k of oQi.split(","))a.searchParams.delete(k);d=Number(b);d>=0&&(d===0?(a.searchParams.set("udm","50"),a.searchParams.delete("arv")):a.searchParams.set("nem",b));c!==""&&a.searchParams.set("fbs",c);g!==""&&a.searchParams.set("ved",g);h&&a.searchParams.set("aep",h.toString());a.searchParams.set("ntc",
"1");return a};iQi=function(a){var b=new _.oTc;return _.Yg(b,1,a)};gQi=_.Sb(_.mOi);pQi=!!(_.Bi[15]>>26&1);var oQi=_.Bi[55]&512?"arv,csuir,mstk,mtid,smstk,smstidx,shndl,shmd,shmds,source,kgs":"";var qQi=function(a,b){return a.getData("hostname").Ob()?_.fm(a.getData("hostname")):b!=null?_.gm(b.getData("host"),""):""},rQi=function(a,b,c,d,e,f){d=qQi(a,d);e=e?_.gm(e.getData("ved"),""):"";b=mQi(new _.Yt(a.wc.Jf()),b,c,d,_.gm(a.getData("dq"),""),_.KPi,e,f);a.Yb.navigateTo(_.oc(b.toString()))},sQi=function(a,b){const c=document.querySelector('[jsname="y2FPdf"]');if(c){var d,e,f=(e=(d=c.textContent)==null?void 0:d.split(" > "))!=null?e:[];if(f.length!==0){var g,h;if(a=((h=(g=a.bp)==null?void 0:
_.ZD(g,b))==null?void 0:h.getValue())||"")if(a==="0")c.textContent=f[0];else if(a==="1"||a==="2")c.textContent=`${f[0]} > Pro`}}},tQi=class extends _.Wr{static Ta(){return{service:{wc:_.Nv,Yb:_.wz,msb:_.iOi,NEa:_.cgh},Cd:{menu:{jsname:"S6sggc",ctor:_.$D}}}}constructor(a){super();this.bp=null;this.wc=a.service.wc;this.Yb=a.service.Yb;this.bp=a.Cd.menu;if(_.zPi&&this.getData("mgtv").Ob()){var b=mQi(new _.Yt(this.wc.Jf()),_.fm(this.getData("mgtv")),_.gm(this.getData("fbs"),""),"",_.gm(this.getData("dq"),
""),_.KPi,"1t:244952",63);_.jQi(a.service.msb,a.service.wc,a.service.Yb,a.service.NEa,b.toString())}}Ba(a){if(this.getData("mgtv").Ob()){const b=_.fm(this.getData("mgtv")),c=_.gm(this.getData("fbs"),"");rQi(this,b,c,a.targetElement,a.wb,1)}}Da(a){const b=_.fm(a.wb.getData("mgtv"));rQi(this,b,"",a.targetElement,a.wb)}Aa(a){var b=a.data.trigger,c=a.data.eza;if(b!=null&&c)if((c=b.wm())&&(c=c.dataset.ved?c:c.querySelector("a[data-ved]"))&&_.$v(c),b.getData("optionDropdown").Ob())this.oa(a);else if(a=
_.gm(b.getData("nrp"),""),a===""&&(a=_.gm(b.getData("redirectPath"),"")),a===""){var d=_.gm(this.getData("fbs"),"");rQi(this,b.getValue(),d,b.getRoot(),b)}else{c=b.getRoot();b=a;var e=_.gm(c.getData("ncp"),"");e===""&&(e=_.gm(c.getData("redirectParams"),""));a=this.wc.Jf();c=qQi(this,c);a=new _.Yt(a);var f=c;f===""&&(f=a.hostname);b=b.split("?");var g=b[0];c=b.length>1?b[1]:"";b=a.clone();g.startsWith("/")?(b.hostname=f,b.pathname=g):b=new _.Yt(g);e=e.split(",");f=new Map;g=!1;for(var h=0;h<e.length;++h)e[h]===
"*"?g=!0:e[h].startsWith("-")&&f.set(e[h].substring(1),!0);if(g){kQi(b);for(d of f.keys())b.searchParams.delete(d)}else for(b.searchParams.setValue(""),d=0;d<e.length;++d)if(f=e[d],a.searchParams.has(f))for(g=a.searchParams.getAll(f),h=0;h<g.length;++h)b.searchParams.append(f,g[h]);d=new Map;if(c!==""){a=new URLSearchParams(c);for(const [k,l]of a)a=k,c=l,d.has(a)?b.searchParams.append(a,c):(b.searchParams.set(a,c),d.set(a,!0))}d=b;(b=_.gm(this.getData("dq"),""))&&d.searchParams.has("q")&&!_.KPi&&
d.searchParams.set("q",b);d=_.oc(d.toString());this.Yb.navigateTo(d)}}oa(){const a=document.body.querySelector('[jsname="dheN8e"]');a&&this.Tc(a,_.Do,b=>{b.oa(a)})}Ca(a){const b=a.data.trigger;a=a.data.Twd;b.classList.contains("V8KfWe")?b==null||b.classList.remove("V8KfWe"):(a.forEach(c=>{c.classList.remove("V8KfWe")}),b==null||b.classList.add("V8KfWe"))}Ha(a){if(pQi){a=a.data;var b=document.querySelector('[jsname="H1cYZb"]');if(a!==0&&b){var c=lQi(a),d=this.bp;(a=d==null?void 0:d.oa().find(e=>{let f;
return((f=d==null?void 0:_.ZD(d,e))==null?void 0:f.getValue())===c}))&&a!==(d==null?void 0:d.yp())&&(d==null||d.clearSelection(),d==null||_.ZD(d,a).Pk(!0),sQi(this,a))}}}};tQi.prototype.$wa$fqmbjc=function(){return this.Ha};tQi.prototype.$wa$C70bfd=function(){return this.Ca};tQi.prototype.$wa$JxAq2e=function(){return this.oa};tQi.prototype.$wa$zlgt8b=function(){return this.Aa};tQi.prototype.$wa$I9Eaue=function(){return this.Da};tQi.prototype.$wa$vr907=function(){return this.Ba};_.as(_.fQi,tQi);
_.x();
_.v("PGyklf");
_.FOc=class extends _.Wr{constructor(){super();this.root=this.getRoot().el()}isEnabled(){return!this.root.hasAttribute("disabled")&&!this.root.hasAttribute("aria-disabled")}focus(){_.ua()&&this.root.blur();this.root.focus()}setEnabled(a){a?this.root.removeAttribute("disabled"):this.root.setAttribute("disabled","true");_.Vd(this.root,"disabled",!a)}getContent(){const a=this.qb("ibnC6b").el();return a?_.Mm(a):""}getValue(){return this.value}oa(){return this.root}};_.FOc.prototype.$wa$L4rKVc=function(){return this.oa};
_.FOc.prototype.$wa$HvnK2b=function(){return this.getValue};_.FOc.prototype.$wa$aDGs4d=function(){return this.getContent};_.FOc.prototype.$wa$AHmuwe=function(){return this.focus};_.FOc.prototype.$wa$yXgmRe=function(){return this.isEnabled};
_.x();
_.LOc=_.gr("PGyklf",[]);
_.MOc=_.y("pzkXnb",[_.LOc]);
_.v("pzkXnb");
_.NOc=class extends _.FOc{constructor(a){super(a.hc);this.value=_.gm(this.getData("v"),"");this.wrc=this.getData("o").Ob();this.isLink=this.getData("l").Ob();this.tM=this.getData("s").Ob();this.root.getAttribute("disabled")&&this.setEnabled(!1);this.root.addEventListener("click",()=>{})}Ca(){return this.tM}focus(){if(this.isLink){let a;(a=this.oa().querySelector("a"))==null||a.focus()}else super.focus()}Rc(){this.tM&&this.isEnabled()?this.Pk(!this.isSelected()):!this.isLink&&this.isEnabled()&&this.trigger("UszG1b",
{wrc:this.wrc});this.notify("aZcdhc");return!0}Ba(){this.trigger("L8zncc")}Aa(a){(a=a.event.relatedTarget)&&this.trigger("M9oBfd",{relatedTarget:a})}isSelected(){return this.tM&&(_.Xd(this.root,"checked")==="true"||_.Xd(this.root,"selected")==="true")}Pk(a){this.tM&&(a&&this.isEnabled()?(_.Vd(this.root,"checked","true"),this.trigger("UBsZj")):a||(_.Vd(this.root,"checked","false"),this.trigger("JkcjMe")))}};_.NOc.prototype.$wa$KKjvXb=function(){return this.isSelected};_.NOc.prototype.$wa$MDJmo=function(){return this.Aa};
_.NOc.prototype.$wa$rESl3=function(){return this.Ba};_.NOc.prototype.$wa$h5M12e=function(){return this.Rc};_.NOc.prototype.$wa$AHmuwe=function(){return this.focus};_.NOc.prototype.$wa$pxaUTb=function(){return this.Ca};_.as(_.MOc,_.NOc);
_.x();
_.rOc=_.y("Mbif2",[_.Tq,_.bm,_.co]);
_.v("Mbif2");
var sOc,vOc,wOc;sOc=[1,2,3];
_.uOc=function(a,b=!1){var c=_.tOc(a,a.controller),d=a.controller.oa(),e=_.KJa(d),f=_.KJa(c)-c.scrollLeft;e-=f;var g=_.he(d),h=e+_.en(d).width/2;e=h-9.5;f=a.oa.get(_.tOc(a,a.controller));var k=f.container;var l=k.style.display,p=k.style.position,q=k.style.visibility;if(a.isVisible(a.controller))k=new _.Kd(k.offsetWidth,k.offsetHeight);else{k.style.visibility="hidden";k.style.position="absolute";k.style.display="block";var r=new _.Kd(k.offsetWidth,k.offsetHeight);k.style.display=l;k.style.position=
p;k.style.visibility=q;k=r}p=k.width;r=k.height;l=a.controller.Cb();q=a.controller.ub();k=0;if(!_.lm.contains(f.container,"SiOjJb")){switch(l){case 5:case 2:k=h-p/2;break;case 4:case 1:k=h-(g?p-9.5-q:9.5+q);break;case 6:case 3:k=h-(g?9.5+q:p-9.5-q)}k=Math.max(c.scrollLeft+8,k);g=c===a.window.getDocument().body?_.Vh(a.window.get()).width:c.offsetWidth;k=Math.min(k,g+c.scrollLeft-8-p);g=parseInt(_.Sm(f.container,"border-radius"),10)||0;k=Math.min(k,e+g);k=Math.max(k,e+19+g-p)}b&&(k=Math.max(k,0));g=
parseInt(_.Sm(d,"padding-top"),10)||0;b=!1;h=sOc.indexOf(l)!==-1;q=g+9.5+r-1;l=_.Vm(d);c=c!==a.window.getDocument().body?c.scrollTop-_.Vm(c):0;p=_.en(d).height;const u=d.getBoundingClientRect().top;d=u-q>=0;q=u+p+q<=_.Vh(a.window.get()).height;a=a.controller.Wa();h&&(q||!a)||!h&&!d&&a?(a=c+l+p+g,d=a+9.5-1):(a=c+l-g-9.5,d=a-r+1,b=!0);_.Qm(f.container,"left",`${k}px`);_.Qm(f.container,"top",`${d}px`);_.Qm(f.ita,"left",`${e}px`);_.Qm(f.ita,"top",`${a}px`);b?_.lm.add(f.ita,"IBPZu"):_.lm.remove(f.ita,
"IBPZu")};_.tOc=function(a,b){return b.Sa()&&_.om(b.Sa())||b.Jb()&&b.getRoot().el().offsetParent||a.window.getDocument().body};_.xOc=function(a){if(a.controller){_.hg(a.controller.oa(),"sendDismissEvent")&&a.controller.trigger("pD7Wob");var b=a.oa.get(_.tOc(a,a.controller));a.Aa&&(a.Da=+_.gg(a.controller.getRoot().el(),"du"));a.controller=null;b&&(b.container.__owner=void 0,a.dismiss.unlisten(b.container),a.Aa?(vOc(b,!1),a.Ha=(0,_.Yn)(()=>{wOc(b)},a.Da)):wOc(b))}};
vOc=function(a,b){const c=a.container;a=a.ita;b?(_.lm.p_(c,"bE3Kif","nFdFHf"),_.lm.p_(a,"bE3Kif","nFdFHf")):(_.lm.p_(c,"nFdFHf","bE3Kif"),_.lm.p_(a,"nFdFHf","bE3Kif"))};wOc=function(a){_.Qm(a.container,{display:"none",width:"","z-index":""});_.Qm(a.ita,{display:"none","z-index":""});_.uVb(a.pZ);_.lm.set(a.container,"QyJI3d");_.lm.set(a.ita,"tYmfxe");_.lm.set(a.Cid,"oQcPt")};
_.yOc=class extends _.ho{static Ta(){return{service:{dismiss:_.rv,Cc:_.Ku,window:_.fo}}}constructor(a){super();this.Ba=this.controller=null;this.Ia=0;this.Aa=!1;this.Ha=null;this.Da=0;this.oa=new Map;this.Pb=a.service.Cc;this.dismiss=a.service.dismiss;this.window=a.service.window;_.me(this.window.get(),"resize",()=>{this.controller&&_.uOc(this)})}Vb(){super.Vb();this.oa.forEach(a=>{_.Hm(_.om(a.containerId));_.Hm(_.om(a.Did))})}Ca(a,b){this.isVisible(this.controller)&&(this.log(!1,a,b),_.xOc(this))}log(a,
b,c){const d=this.controller.Ma();b=b&&_.Ge(b)?b:void 0;d&&_.Ge(d)&&(c=b?new _.Jh(_.Ge(b),c||2):void 0,a?this.Pb.Aa(d,c):this.Pb.Ba(d,c))}onDismiss(a,b){const c=this.controller?this.controller.rb():!1;let d;if(b&&((d=this.controller)==null?0:d.Wb(b)))return!1;this.Ca(b);a===2&&this.Ba&&this.Ba.focus();return c}G9(a){const b=a.container;_.Qm(b,{display:"block"});_.Jg(b,this.controller.getRoot().el());_.hg(this.controller.oa(),"sendShowEvent")&&this.controller.trigger("tA6Kcd");this.controller.Za()||
(a.content.focus(),_.tVb(a.pZ),this.dismiss.listen(a.container,(c,d)=>this.onDismiss(c,d)));_.Qm(a.ita,{display:"block"});this.Aa&&((0,_.Zn)(this.Ha),vOc(a,!0))}isVisible(a){if(!a)return!1;a=this.oa.get(_.tOc(this,a));return!!a&&_.Sm(a.container,"display")==="block"}Cga(a){this.controller&&(a=this.oa.get(_.tOc(this,this.controller)).content.querySelector(`[jsname=${a}]`))&&_.Kg(a)&&_.Lm(a)&&a.focus()}};_.Zf(_.rOc,_.yOc);
_.x();
_.v("ipWLfe");

_.x();
var zOc=_.gr("ipWLfe",[]);_.AOc=_.y("QVaUhf",[_.rOc,zOc]);
_.v("QVaUhf");
var BOc,COc,DOc,EOc;
BOc=function(a,b){b=_.tOc(a,b);var c=a.oa.get(b);if(c)return c;c=_.ym("DIV","QyJI3d");const d="gbbl-"+String(a.Ia++);c.id=d;_.hn(c,!1);var e=_.ym("DIV");_.$m(e,0);_.gn(e,0);_.Vd(e,"hidden",!0);_.Sd(e,"button");_.iJa(e,!0);c.appendChild(e);const f=_.ym("DIV");f.tabIndex=-1;const g=new _.vVb(f);_.Qm(f,"outline","none");c.appendChild(f);_.me(e,"focus",()=>{((new _.oo([f])).find("*").toArray().reverse().find(l=>_.Kg(l)?_.Lm(l):!1)||f).focus()});e=e.cloneNode(!0);_.iJa(e,!0);_.me(e,"focus",()=>{((new _.oo([f])).find("*").toArray().find(l=>
_.Kg(l)?_.Lm(l):!1)||f).focus()});c.appendChild(e);e=_.ym("DIV",["oQcPt"]);const h=_.ym("DIV",["tYmfxe"],e),k="gbblt-"+String(a.Ia++);h.id=k;_.hn(h,!1);c={container:c,containerId:d,content:f,pZ:g,ita:h,Did:k,Cid:e};a.oa.set(b,c);return c};
COc=function(a,b,c,d,e=!1,f=!1,g=0,h="",k="",l,p=!1,q=!1){a.Aa=q;_.xOc(a);if(q=b.Ma()){q=q.parentNode?q.parentNode:q;a.controller=b;var r=BOc(a,b);var u=_.tOc(a,b);_.om(r.containerId)||u.appendChild(r.container);_.om(r.Did)||u.appendChild(r.ita);_.Vd(r.container,"hidden",!1);u=a.controller.oa();g===1?(_.lm.add(r.container,"PnQMie"),_.lm.add(r.ita,"PnQMie")):g===2&&(_.lm.add(r.container,"LWen5c"),_.lm.add(r.ita,"LWen5c"));h&&_.lm.addAll(r.container,h.split(" "));k&&_.lm.addAll(r.Cid,k.split(" "));
d!==null&&(_.Qm(r.container,"z-index",d),_.Qm(r.ita,"z-index",d+1));p&&_.Qm(r.container,"max-width","100%");_.lm.enable(r.container,"SiOjJb",f);_.lm.enable(r.container,"QJnoze",e);c>0&&!f&&_.Qm(r.container,{width:`${c}px`});b.Pa()?r.container.setAttribute("aria-label",b.Pa()):r.container.removeAttribute("aria-label");_.Sd(r.container,b.Xa()?"dialog":"alertdialog");b=r.content;_.Dm(b);for(const A of q.childNodes)b.appendChild(A.cloneNode(!0));a.Ba=a.window.getDocument().activeElement;_.uOc(a,p);a.G9(r);
a.log(!0,u,l)}};DOc=class extends _.Wr{};EOc=function(a,b,c){a=_.gg(a,b)||"";a=_.Zl(a);return isNaN(a)?c:a};
_.pz=class extends DOc{static Ta(){return{service:{ktb:_.yOc}}}constructor(a){super(a.hc);this.Ia=this.Ca=this.Da=null;this.Ha=a.service.ktb;this.Ub=_.un(()=>this.Ka("bN97Pc").el());this.Rb=_.un(()=>this.Ka("d6wfac").el());this.Qa=!_.hg(this.oa(),"lzyAct")}Kb(a){const b=a.event;b&&this.Da&&this.isVisible()&&b.clientX===this.Da.clientX&&b.clientY===this.Da.clientY&&b.timeStamp-this.Da.timeStamp<200||this.Ba(void 0,3);this.Da=null;a.event.preventDefault&&a.event.preventDefault();return _.hg(this.oa(),
"sendOpenEvent")}Ba(a,b){var c=this.oa();if(a===!1||!a&&this.isVisible())this.Qa?this.La(c,b):this.Ia=null;else if(this.Qa){a=EOc(c,"theme",0);var d=EOc(c,"zidx",0);d=d>=1?d:null;var e=EOc(c,"width",200),f=_.hg(c,"fullWidth"),g=_.hg(c,"roundedCorners"),h=_.gg(c,"extraContainerClasses"),k=_.gg(c,"extraTriangleClasses"),l=this.getData("ctv").Ob();c=_.hg(c,"enableToggleAnimation");COc(this.Ha,this,e,d,g,f,a,h,k,b,l,c);b=this.getData("f");b.Ob()&&this.Ha.Cga(b.string())}else this.Ia=b}Lb(){this.Qa=!0;
this.Ia!==null&&(this.Ba(!0,this.Ia),this.Ia=null)}G9(a){this.Ba(!0,a)}Aa(a){this.Ba(!1,a?3:void 0)}Qb(a){const b=this.oa();(new _.so(b)).focus();this.Aa(a)}rc(){return!1}onMouseEnter(a){_.hg(this.oa(),"sendOpenEvent")&&this.trigger("aKmQDb",a.targetElement);this.G9(9);this.Da=a.event;return!1}onMouseLeave(){this.Da&&(this.Ba(!1,9),this.Da=null)}Ac(a){this.Ca!==null&&((0,_.Zn)(this.Ca),this.Ca=null);if(!this.isVisible())if(_.hg(this.oa(),"delayOpenOnHover"))this.Ca=(0,_.Yn)(()=>this.onMouseEnter(a),
EOc(this.oa(),"hoverOpenDelay",500));else this.onMouseEnter(a);return!1}Fc(){this.Ca!==null&&((0,_.Zn)(this.Ca),this.Ca=null);this.isVisible()&&(this.Ca=(0,_.Yn)(()=>this.Aa(),EOc(this.oa(),"hoverHideDelay",1E3)))}Ma(){return this.Ub()}oa(){return this.Rb()}Vb(){this.isVisible()&&_.xOc(this.Ha);super.Vb()}Wb(a){return _.Vg(this.oa(),a)}La(a,b){this.isVisible()&&this.Ha.Ca(a,b)}isVisible(){var a=this.Ha;return a.controller===this&&a.isVisible(this)}Wa(){return this.getData("ci").Ob()}Cb(){return EOc(this.getRoot().el(),
"tp",2)}ub(){return EOc(this.getRoot().el(),"to",10)}Za(){return this.getData("df").Ob()}rb(){return _.hg(this.oa(),"disableDismissEventBubbling")}Sa(){return this.getData("sc").Ob()?_.fm(this.getData("sc")):null}Jb(){return this.getData("oc").Ob()}Pa(){return _.gm(this.getData("al"),"")}Xa(){return this.getData("da").Ob()}};_.pz.prototype.$wa$x2QzWe=function(){return this.Xa};_.pz.prototype.$wa$jZ0cf=function(){return this.Pa};_.pz.prototype.$wa$wu4W6e=function(){return this.Jb};
_.pz.prototype.$wa$A4M6Rd=function(){return this.Sa};_.pz.prototype.$wa$YWMfPe=function(){return this.rb};_.pz.prototype.$wa$plyROe=function(){return this.Za};_.pz.prototype.$wa$zxO7z=function(){return this.ub};_.pz.prototype.$wa$qIUUyb=function(){return this.Cb};_.pz.prototype.$wa$Dntuwf=function(){return this.Wa};_.pz.prototype.$wa$eO2Zfd=function(){return this.isVisible};_.pz.prototype.$wa$k4Iseb=function(){return this.Vb};_.pz.prototype.$wa$lI3Pp=function(){return this.oa};
_.pz.prototype.$wa$noyIOe=function(){return this.Ma};_.pz.prototype.$wa$JDTRYd=function(){return this.Fc};_.pz.prototype.$wa$jTlRtf=function(){return this.Ac};_.pz.prototype.$wa$iFHZnf=function(){return this.onMouseLeave};_.pz.prototype.$wa$MJEKMe=function(){return this.onMouseEnter};_.pz.prototype.$wa$NLMyWb=function(){return this.rc};_.pz.prototype.$wa$DLNOs=function(){return this.Qb};_.pz.prototype.$wa$VqIRre=function(){return this.Aa};_.pz.prototype.$wa$dou8Ld=function(){return this.Lb};
_.pz.prototype.$wa$vQLyHf=function(){return this.Kb};_.as(_.AOc,_.pz);
_.x();
_.Cns=class{constructor(a){this.oa=a}};var Dns=class extends _.Cns{constructor(a,b){super(a);this.Ba=b;this.Aa=null}zI(){if(this.Aa)return this.Aa;const a=[];for(var b=this.oa.xb;b instanceof gbar.I&&b!=this.Ba.oa;)a.push(b.ic()),b=b.zb();for(b=this.Ba;a.length>0;)b=b.TJa(a.pop());return this.Aa=b}getType(){return this.oa.xa}};var Ens=class extends _.Cns{listen(a,b,c,d){const e=this;return this.oa.za(a,function(f){return b.call(d||_.ea,new Dns(f,e))},c)}listenOnce(){throw Error("Wn");}unlisten(){throw Error("Wn");}ev(){throw Error("Wn");}dispatchEvent(){throw Error("Wn");}removeAllListeners(){throw Error("Wn");}Y4a(){throw Error("Wn");}fireListeners(){throw Error("Wn");}L4a(){throw Error("Wn");}K4a(){throw Error("Wn");}hasListener(){throw Error("Wn");}};Ens.prototype[_.XJa]=!0;var Fns=class extends Ens{getHeight(){return this.oa.pa()}setDarkMode(a){this.oa.pp(a);return this}};var Gns=class extends Ens{constructor(a){super(a);this.Aa=null}getId(){return this.oa.ia()}Ka(){return this.oa.ib()}getModel(){return this.Aa}setModel(a){this.Aa=a;return this}};var Hns=class extends Gns{constructor(a){super(a);this.Ba={}}TJa(a){var b=this.Ba[a];if(b)return b;if(b=this.oa.ja(a)){const c=b.__wc;if(!c)throw Error("mx");b=new c(b);return this.Ba[a]=b}return null}};var Ins=class extends Hns{getContent(){return this.oa.ca()}open(a){this.oa.cf(a)}close(a){this.oa.cg(a)}getStyle(){return this.oa.ch()}isOpen(){return this.oa.ck()}};var Jns;Jns=function(a,b){const c=a.Aa;return c?function(d){b.call(this,new c(d))}:b};_.Kns=class extends _.Cns{constructor(a,b){super(a);this.Aa=b||null}then(a,b,c){let d;a&&(d=Jns(this,a));this.oa.aa(d,b,c)}};var Lns;_.Mns=function(){return new Promise(a=>{window.gbar||(window.gbar={});if(window.gbar.a)return a(Lns.getInstance());(new Promise(b=>{window.gbar.ap=b})).then(()=>a(Lns.getInstance()))})};Lns=class extends _.Cns{constructor(a){super(a||gbar.a);this.Ba=this.Aa=null}s5(){this.Aa||(this.Aa=new _.Kns(this.oa.bf(),Fns));return this.Aa}um(){this.Ba||(this.Ba=new _.Kns(this.oa.ba(),Ins));return this.Ba}static getInstance(){return _.Ch(Lns)}};
var yns;_.zns=function(){var a=new yns;a=_.Ph(a,1,1);return _.Ph(a,2,4)};yns=class extends _.m{constructor(a){super(a)}jS(){return _.Yj(this,1)}};yns.prototype.kb="SMSkB";var Ans=class extends _.m{constructor(a){super(a)}};Ans.prototype.kb="s5PeBc";new _.mi(yns);new _.mi(Ans,1E3);_.So.s5PeBc=_.Ro;_.Bns=new _.ai("VbSMl",Ans,yns,[_.$h,!1,_.Zh,"/MyactivityService.ExternalDelete"]);new _.mi(yns);new _.mi(Ans,1E3);_.So.s5PeBc=_.Ro;
_.Ufq=_.y("SJpD2c",[_.Jo,_.bm,_.AOc]);
var Fyg,Hyg,Lyg;Fyg=function(){var a={};const b=_.CIa(_.EIa("/blank.html"));if(!Dyg.test(b))throw Error("Ll`"+b);const c=b.replace(Eyg,function(d,e){if(!Object.prototype.hasOwnProperty.call(a,e))throw Error("Ml`"+e+"`"+b+"`"+JSON.stringify(a));d=a[e];return d instanceof _.AIa?_.CIa(d):encodeURIComponent(String(d))});return _.fc(c)};_.Iyg=function(a){var b=Fyg();b=_.ic(b);b=Gyg.exec(b);const c=b[3]||"";return _.Gka(b[1]+Hyg("?",b[2]||"")+Hyg("#",c,a),{justification:"Deprecated, but safe closure/html builder"})};
Hyg=function(a,b,c){if(c==null)return b;if(typeof c==="string")return c?a+encodeURIComponent(c):"";for(const e in c)if(Object.prototype.hasOwnProperty.call(c,e)){var d=c[e];d=Array.isArray(d)?d:[d];for(let f=0;f<d.length;f++){const g=d[f];g!=null&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(e)+"="+encodeURIComponent(String(g)))}}return b};
_.Myg=function(a,b){a&&_.ic(a);var c={};c.src=a||null;c.srcdoc=void 0;var d={sandbox:""};a={};for(var e in c)Object.prototype.hasOwnProperty.call(c,e)&&(a[e]=c[e]);for(const h in d)Object.prototype.hasOwnProperty.call(d,h)&&(a[h]=d[h]);if(b)for(var f in b)if(Object.prototype.hasOwnProperty.call(b,f)){e=f.toLowerCase();if(e in c)throw Error("U");e in d&&delete a[e];a[f]=b[f]}b=void 0;c="";if(a)for(g in a)if(Object.prototype.hasOwnProperty.call(a,g)){if(!Jyg.test(g))throw Error("U");d=a[g];if(d!=null){f=
g;if(f.toLowerCase()=="style")d=String(d);else{if(/^on/i.test(f))throw Error("U");if(f.toLowerCase()in Kyg)if(d instanceof _.ec)d=_.ic(d).toString();else if(_.Via(d))d=_.kc(d);else if(typeof d==="string")d=_.oc(d).toString();else throw Error("U");}f=`${f}="`+_.Aaa(String(d))+'"';c+=" "+f}}var g="<iframe"+c;b==null?b=[]:Array.isArray(b)||(b=[b]);Lyg.iframe===!0?g+=">":(a=_.jja(b),g+=">"+_.dc(a)+"</iframe>");return _.z(g)};
Lyg={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var Eyg=/%{(\w+)}/g,Dyg=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),Gyg=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Jyg=/^[a-zA-Z0-9-]+$/,Kyg={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};
_.v("SJpD2c");
var Nns=function(a){let b=a,c;return function(){if(b){const d=b;b=void 0;c=d.apply(this,arguments)}return c}},Ons=function(a,b=!1){a.oa.sh(b)},Pns=class extends _.Cns{},Qns=function(a){a.Ca||(a.Ca=new _.Kns(a.oa.bk(),Pns));return a.Ca},Rns=async function(a,b,c){var d=(0,_.Rf)(),e=d();d=d(1);try{const f=d(await e(a.oa)),g=f[b];if(!g)throw Error("nx`"+b);return g.apply(f,c)}finally{e()}},Sns=class{constructor(a){this.oa=a;this.xm=null;a.then((0,_.ne)(function(){},this),()=>{},this)}},Vns=function(a,
b,c){const d=Array(arguments.length-2);for(var e=2;e<arguments.length;e++)d[e-2]=arguments[e];e=Tns(a,b).then(f=>f.apply(null,d),f=>{f=Error("ox`"+b+"`"+a+"`"+f,{cause:f});delete Uns[b];return _.xh(f)});return new Sns(e)},Uns={},Tns=function(a,b){var c=Uns[b];if(c)return c;c=(c=_.Ai(b))?_.Ag(c):(new _.Lg(function(d,e){const f=(new _.FIa(document)).createElement("SCRIPT");f.async=!0;_.Pc(f,_.fc(_.CIa(a)));f.onload=f.onreadystatechange=function(){f.readyState&&f.readyState!="loaded"&&f.readyState!=
"complete"||d()};f.onerror=g=>{e(Error("px`"+b+"`"+a,{cause:g}))};(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){const d=_.Ai(b);if(!d)throw Error("qx`"+b+"`"+a);return d});return Uns[b]=c};var Wns={GOOGLE:"https://www.google.com",rZe:"https://support.google.com",aRe:"https://play.google.com"},Xns=async function(a){var b=(0,_.Rf)(),c=b();b=b(1);try{for(const d of Object.values(Wns))try{b(await c(navigator.permissions.query({name:"top-level-storage-access",requestedOrigin:d}))).state!=="granted"&&a.oa.push(d)}catch(e){b();break}}finally{c()}};var Yns=_.EIa("https://www.google.com/tools/feedback/help_api.js"),$ns=function(){const a=Vns(Yns,"help.api.Lazy.create","196");return new Zns(a)},Zns=class{constructor(a){this.EEa=a}async oa(a){var b=(0,_.Rf)(),c=b();b=b(1);try{var d=this.EEa,e=arguments;try{e[0].commonConfig.frdProductData&&(e[0].commonConfig.frdProductDataSerializedJspb=e[0].commonConfig.frdProductData.serialize(),e[0].commonConfig.frdProductData=void 0)}catch(f){}try{let f;if((f=e[0].commonGseConfig)==null?0:f.gseSessionOptions)e[0].commonGseConfig.gseSessionOptionsSerializedJspb=
e[0].commonGseConfig.gseSessionOptions.serialize(),e[0].commonGseConfig.gseSessionOptions=void 0}catch(f){}try{e[0].startingFlow&&(e[0].startingFlowSerializedJspb=e[0].startingFlow.serialize(),e[0].startingFlow=void 0)}catch(f){}b(await c(Rns(d,"openHelp",e)))}finally{c()}}async close(){var a=(0,_.Rf)(),b=a();a=a(1);try{a(await b(Rns(this.EEa,"close",arguments)))}finally{b()}}};
(new class{constructor(){this.oa=[];this.Aa=[];this.initialize=Nns(async()=>{var a=(0,_.Rf)(),b=a();a=a(1);try{if(typeof document==="undefined"||document.requestStorageAccessFor===void 0||navigator.permissions===void 0||navigator.permissions.query===void 0||location.hostname.match(".+\\.google\\.com$"))return Promise.resolve();a(await b(Xns(this)));this.oa.length>0&&document.addEventListener("click",this.Ba)}finally{b()}});this.Ba=()=>{if(!(this.Aa.length>0)){for(const a of this.oa)try{this.Aa.push(document.requestStorageAccessFor(a))}catch(b){}Promise.all(this.Aa).then(()=>
{}).catch(()=>{}).finally(()=>{this.reset()})}}}reset(){document.removeEventListener("click",this.Ba)}}).initialize();var aos=function(a,b,c){return{id:b,callable:()=>{a.logClick(c)},url:null}},bos=function(a){return(b,c)=>{var d;const e=(d=a.getRoot())==null?void 0:d.el();b=a.isSignedIn?e:b;d=a.Pb.oa();e&&_.Hp(d,e,c?1:2);b&&_.Fp(d,b,3);d.log(!0)}},cos=function(a){const b=$ns(),c=_.td(_.sd("QrtxK"),0).toString(),d=!!document.body.dataset.dt,e=document.body.querySelector("[jsname='AYtejb']"),f={commonConfig:{helpCenterPath:"websearch",authuser:c,locale:_.gm(_.sd("GWsdKe"),"en")},helpPanelConfig:{helpPanelTheme:d?
1:0,helpPanelMode:1,fixedHelpPanelContainer:e?e:void 0},k9e:!0,oTa:{bucket:"Default"}};return{id:"og-am-hf",callable:()=>{a.logClick(a.Ka("uO6mde").el());b.oa(f)},url:null}},dos=function(a,b){_.Mns().then(c=>{Qns(c).then(d=>{const e=[aos(a,"og-am-ss",a.Ka("NG1V7d").el()),aos(a,"og-am-lg",a.Ka("IZKNDc").el()),aos(a,"og-am-ms",a.Ka("tP7ayb").el())];b?e.push(cos(a)):e.push(aos(a,"og-am-hf",a.Ka("uO6mde").el()));a.isSignedIn?e.push(aos(a,"og-am-qdc-qd",a.Ka("hJoEPd").el()),aos(a,"og-am-qdc-sh",a.Ka("micRse").el()),
{id:"og-am-qdc-dt",callable:()=>a.oa(),url:null},{id:"og-am-qdc-fsb",callable:()=>{a.Aa()},url:null},aos(a,"og-am-cp-int",a.qb("t5CbBf").el()),aos(a,"og-am-ps",a.qb("Du1Fsb").el()),aos(a,"og-am-sop",a.qb("bicHfd").el())):e.push(aos(a,"og-am-pc",a.qb("nSxrjf").el()));a.Ba&&e.push(aos(a,"og-am-dm",a.qb("pxGDvf").el()));d.oa.sf(e);d.oa.sj(bos(a))})})},eos=class extends _.Wr{static Ta(){return{service:{Ke:_.wr,Pb:_.Ku},controllers:{ggc:{jsname:"ovbFm",ctor:_.pz}}}}logClick(a){a!=null&&_.Fp(this.Pb.oa(),
a,3).log(!0)}constructor(a){super();this.L_=null;this.isSignedIn=!this.getData("so").Ob();const b=this.getData("iph").Ob();this.Ba=this.getData("dmt").Ob();this.Td=a.service.Ke;this.ggc=a.controllers.ggc[0];this.Pb=a.service.Pb;this.logger=null;dos(this,b);this.isSignedIn&&_.sh(this,{controllers:{L_:"PWj1Zb"}}).then(c=>{this.L_=c.controllers.L_[0]})}async oa(){var a=(0,_.Rf)(),b=a();a=a(1);try{try{const c=_.zns();a(await b(this.Td.Jc(_.Bns.getInstance(c))));return!0}catch(c){return a(),!1}}finally{b()}}Aa(){let a;
(a=this.L_)==null||a.show()}Da(){let a;(a=this.ggc)==null||a.G9()}async Ca(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const d=a.data.bVd,e=b(await c(_.Mns()));Ons(b(await c(Qns(e))),d)}finally{c()}}};eos.prototype.$wa$FPeyVe=function(){return this.Ca};eos.prototype.$wa$MMAZpe=function(){return this.Da};eos.prototype.$wa$BjElId=function(){return this.Aa};eos.prototype.$wa$BlH6Ne=function(){return this.oa};_.as(_.Ufq,eos);
_.x();
_.EVb=_.y("eX5ure",[_.bm]);
_.v("eX5ure");
var FVb=class extends _.Wr{static Ta(){return{service:{Pb:_.Ku}}}constructor(a){super();this.parentElement=null;this.root=this.getRoot().el();this.id=this.getRoot().el().getAttribute("data-id");this.Ca=this.getRoot().el().hasAttribute("data-dc");this.Da=this.getRoot().el().hasAttribute("data-dw");this.oa=_.bi(this.getRoot().getData("backDisabled"),!1);this.Pb=a.service.Pb;this.registerContent()}Ba(){return this.root}Vb(){}registerContent(){this.trigger("jxvro",{controller:this})}Ha(a){a=a.wb.el();
this.trigger("dBhwS",{Hc:a})}udd(a){this.parentElement=a}getId(){return this.id}isDefault(){return this.Ca}hide(){_.hn(this.root,!1)}vnc(a){this.hide();_.Ge(this.root)&&_.Fp(_.Hp(this.Pb.oa(),this.root,2),a).log()}show(a){_.Qm(this.root,{display:"block"});var b=this.qb("LBJcic").el();const c=this.qb("X0x7he").el();(b||this.oa)&&c&&(!this.oa&&b&&(a?_.Qm(b,{display:"inline-block"}):_.hn(b,!1)),b=this.qb("vDg59d").el(),this.Da?(a=a?220:248,b&&(a-=48),_.Qm(c,"width",`${a}px`)):b&&_.Qm(c,"width",`calc(100% - ${48+
(a?28:0)}px)`))}sIb(a,b){this.show(a);_.Ge(this.root)&&_.Fp(_.Hp(this.Pb.oa(),this.root,1),b).log()}yfc(a){const b=a.event.target;let c,d;const e=(d=(c=a.data)==null?void 0:c.contentId)!=null?d:b.getAttribute("data-id");this.parentElement&&this.Dd(this.parentElement).then(f=>f.Ia(e,b))}Aa(a){const b=a.wb.el();this.parentElement&&this.Dd(this.parentElement).then(c=>{if(c.Ca.length>0){c.Aa.vnc(b);const d=c.Ca.pop(),e=c.Ca.length>0;c.Aa=d;d.sIb(e,b)}})}};FVb.prototype.$wa$iO11jf=function(){return this.Aa};
FVb.prototype.$wa$uOhSee=function(){return this.yfc};FVb.prototype.$wa$ZYIfFd=function(){return this.hide};FVb.prototype.$wa$paynGb=function(){return this.isDefault};FVb.prototype.$wa$pTuYge=function(){return this.getId};FVb.prototype.$wa$QQtcRd=function(){return this.Ha};FVb.prototype.$wa$CHHOAf=function(){return this.registerContent};FVb.prototype.$wa$k4Iseb=function(){return this.Vb};FVb.prototype.$wa$xdy80=function(){return this.Ba};_.as(_.EVb,FVb);
_.x();
_.PFC=function(){return window.matchMedia?window.matchMedia("(forced-colors: active)").matches?2:window.matchMedia("(forced-colors: none)").matches?1:0:0};
_.mvq=_.y("zGLm3b",[]);
_.v("zGLm3b");
var UFC=!!(_.Bi[0]&2);var VFC=!!(_.Bi[24]&8192);var WFC=!!(_.Bi[60]>>15&1);var XFC=!!(_.Bi[25]>>20&1);var YFC=new _.Rn,ZFC=class extends _.Wr{constructor(){super();this.oa=_.On(YFC,a=>new a(this.getRoot()));this.Aa();this.Ba()}Aa(){const a=_.Wg();for(const b of this.oa){const c=b.KYb();c&&a.Mc(c[0],c[1])}a.log()}Ba(){var a="";for(var b of this.oa){const c=b.V_b();c&&(a.length>0&&(a+="&"),a+=c.join("="))}a.length>0&&(a=_.kna(`/client_204?${a}`,new Map,!1,!1),b=new _.mr,b.setWithCredentials(!0),b.send(a))}};ZFC.prototype.$wa$ZhdDvf=function(){return this.Ba};ZFC.prototype.$wa$fgCVyc=function(){return this.Aa};
_.as(_.mvq,ZFC);var $FC=class{constructor(a){this.Aa=this.oa=0;this.oa=_.PFC();this.Aa=_.td(a.getData("fc"),0)}KYb(){return["fc",String(this.oa)]}V_b(){return this.oa!==this.Aa?["fc",String(this.oa)]:null}};UFC&&_.Pn(YFC,$FC);var aGC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-contrast: less)").matches?"1":window.matchMedia("(prefers-contrast: more)").matches?"2":window.matchMedia("(prefers-contrast: custom)").matches?"3":"0":"0";this.Aa=_.gm(a.getData("pcon"),"-1")}KYb(){return["pcon",this.oa]}V_b(){return this.oa!==this.Aa?["pcon",this.oa]:null}};WFC&&_.Pn(YFC,aGC);var bGC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?"1":window.matchMedia("(prefers-color-scheme: dark)").matches?"2":"0":"0";this.Aa=_.gm(a.getData("pcs"),"0")}KYb(){let a="4";this.oa==="1"?a="2":this.oa==="2"&&(a="3");return["dt19",`${a}`]}V_b(){return this.oa!==this.Aa?["cs",this.oa]:null}};XFC&&_.Pn(YFC,bGC);var cGC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia&&(window.matchMedia("(prefers-reduced-motion)").matches||window.matchMedia("(prefers-reduced-motion: reduce)").matches)?"1":"0";this.Aa=a.getData("prm").Ob()?"1":"0"}KYb(){return["prm23",this.oa]}V_b(){return this.oa!==this.Aa?["prm",this.oa]:null}};VFC&&_.Pn(YFC,cGC);
_.x();
_.v("L8KGxe");
_.Zf(_.H0a,class extends _.ho{static Ta(){return{service:{window:_.fo}}}constructor(a){super();this.window=a.service.window}get(){return this.window.get()}getDocument(){return this.window.getDocument()}find(a){return(new _.so(this.getDocument().documentElement)).find(a)}});
_.x();
_.ozr=!!(_.Bi[25]&1);_.pzr=!!(_.Bi[25]&2);
_.v("PQ2Aoe");
var KHA=function(a,b){a=`data-${_.vqa(a)}`;return b?`[${a}="${b}"]`:`[${a}]`},LHA=function(a,b,c,d){const e=[];return{xme:document.createTreeWalker(a.commonAncestorContainer,NodeFilter.SHOW_ELEMENT,{acceptNode:f=>{if(!a.intersectsNode(f))return NodeFilter.FILTER_REJECT;if(f instanceof Element&&((c==null?0:c.has(f))||(d==null?0:d.has(f)))){const g=String(e.length);e.push({qNa:f,kSc:c==null?void 0:c.get(f),d6d:d==null?void 0:d.get(f)});f.dataset.copyServiceCallbackId=g;b.push(f)}return f instanceof
Element&&(c==null?0:c.has(f))?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),mgc:e}},NHA=function(a,b,c){const d=[],{xme:e,mgc:f}=LHA(a,d,b,c);for(b=e.currentNode;b;){if(!(b instanceof HTMLElement)){b=e.nextNode();continue}const g=window.getComputedStyle(b);c=g.display==="none"||g.visibility==="hidden"||g.opacity==="0"||g.height==="0px"&&g.width==="0px";d.push(b);if(c)b.dataset.copyServicePrune="";else{g.display!=="contents"&&g.display!=="inline"||b.tagName!=="DIV"||(b.dataset.copyServiceReplaceDivWithSpan=
"");const h=document.createElement("div");MHA.forEach(k=>{const l=g.getPropertyValue(k);l&&h.style.setProperty(k,l)});b.tagName==="IMG"&&(c=g.getPropertyValue("object-fit"))&&(h.style.setProperty("object-fit",c),h.style.setProperty("width",g.getPropertyValue("width")),h.style.setProperty("height",g.getPropertyValue("height")));h.style.cssText&&(b.dataset.copyServiceComputedStyle=h.style.cssText)}b=e.nextNode()}a=a.cloneContents();a.querySelectorAll(KHA("copyServicePrune")).forEach(g=>{g.remove()});
a.querySelectorAll(KHA("copyServiceReplaceDivWithSpan")).forEach(g=>{const h=document.createElement("span");for(;g.firstChild;)h.appendChild(g.firstChild);for(const k of["copyServiceComputedStyle","copyServiceCallbackId"])g instanceof HTMLElement&&k in g.dataset&&(h.dataset[k]=g.dataset[k]);g.replaceWith(h)});d.forEach(g=>{for(const h of["copyServiceComputedStyle","copyServicePrune","copyServiceCallbackId","copyServiceReplaceDivWithSpan"])delete g.dataset[h]});return{fragment:a,mgc:f}},OHA=function(a,
b,c){for(let f=0;f<b.length;f++){var d=String(f);const {qNa:g,kSc:h,d6d:k}=b[f];if(d=a.querySelector(KHA("copyServiceCallbackId",d)))if(c&&k){var e=k(g);e?d.replaceWith(document.createTextNode(e)):d.remove()}else h&&((e=h(g))?d.replaceWith(e):d.remove())}},MHA="font-family font-size font-weight margin text-decoration border-bottom".split(" ");_.Zf(_.r3a,class extends _.ho{static Ta(){return{service:{logging:_.Ku,location:_.Nv}}}constructor(a){super();this.Aa=new Map;this.Ca=new Map;this.oa=new Set;this.Ba=b=>{_.ozr&&this.JEa&&_.Ep(this.Qe.oa(),_.Kh(this.JEa,2)).log();if(_.pzr&&b.clipboardData){var c=window.getSelection();if(c&&c.rangeCount!==0){var d=this.wc.location.origin;const {fragment:A,mgc:E}=NHA(c.getRangeAt(0),this.Aa,this.Ca);var e=A,f=E;c=document.createElement("div");c.appendChild(e.cloneNode(!0));OHA(c,f,!1);e=document.createTreeWalker(c,
NodeFilter.SHOW_ELEMENT);for(var g=e.currentNode;g;){if(!(g instanceof HTMLElement)){g=e.nextNode();continue}if("copyServiceCallbackId"in g.dataset){let I;if((I=f[Number(g.dataset.copyServiceCallbackId)])==null?0:I.kSc){g=e.nextNode();continue}}var h=g.dataset.copyServiceComputedStyle;h&&(g.style.cssText=h);if(g.tagName==="A"&&g.getAttribute("href")){h=g;var k=h.getAttribute("href");_.Jc(h,(new URL(k,d)).href)}if(g.tagName==="IMG"){k=d;var l=Number(g.style.width.replace("px","")),p=Number(g.style.height.replace("px",
""));if(g instanceof HTMLImageElement&&g.complete&&l&&isFinite(l)&&g.naturalWidth&&p&&isFinite(p)&&g.naturalHeight&&(h=g.src.startsWith("data:"),!h||g.naturalWidth!==l||g.naturalHeight!==p)&&(k=(new URL(g.src)).origin!==(new URL(k)).origin,h||!k||g.crossOrigin==="anonymous")&&(h=document.createElement("canvas"),k=h.getContext("2d"))){h.width=l;h.height=p;l=h.width/g.naturalWidth;p=h.height/g.naturalHeight;p=g.style.objectFit==="contain"?Math.min(l,p):Math.max(l,p);l=g.naturalWidth*p;p*=g.naturalHeight;
k.drawImage(g,Math.floor((h.width-l)/2),Math.floor((h.height-p)/2),l,p);try{const I=h.toDataURL("image/png");g.src=I}catch(I){}}}g=e.nextNode()}for(d=document.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);c=document.createElement("div");c.appendChild(A.cloneNode(!0));OHA(c,E,!0);var q;c=(q=c.textContent)!=null?q:"";var {q$d:r,CE:u}={q$d:d,CE:c};q=!1;r.hasChildNodes()&&(q=document.createElement("div"),q.appendChild(r),b.clipboardData.setData("text/html",q.innerHTML),q=!0);u&&(b.clipboardData.setData("text/plain",
u),q=!0);q&&b.preventDefault()}}};this.Qe=a.service.logging;this.wc=a.service.location}registerCopyRoot(a){for(const b of this.oa){if(b.contains(a))return;a.contains(b)&&(b.removeEventListener("copy",this.Ba),this.oa.delete(b))}this.oa.has(a)||(a.addEventListener("copy",this.Ba),this.oa.add(a))}setLoggingElement(a){this.JEa=a}addElementCallback(a,b){this.Aa.set(a,b)}addPlainTextCallback(a,b){this.Ca.set(a,b)}});
_.x();
});
// Google Inc.
