loaded_h_0(function(_){var window=this;
var UTc;UTc=function(a,b){if(!a)return[];const c=String(b);return a.split(";").map(d=>d.trim()).filter(d=>d).map(d=>d.split(":").map(e=>e.trim())).filter(d=>d.length===2).filter(d=>{d=d[1].split(",").map(e=>e.trim());return d.includes(c)||d.includes("62")}).map(d=>d[0])};_.VTc=class{hUa(a,b,c){a=UTc(a,b);a=a.concat(c);return[...(new Set(a))].sort()}};
_.RTc=function(a){if(!a.Da())return null;if(!a.Ca()||!a.La())return a.Aa();const b=a.Aa();try{const c=new RegExp(a.Ba(),"g");return b.replace(c,a.Ha())}catch(c){return b}};
var STc;STc=function(a){return a.La()?a.Ha()?a.Aa()+"-"+a.Da():a.Aa():"en-US"};_.TTc=class{tge(a){a.Ha();const b=_.Ae(a.Ba()),c=a.Ca();return a.Da()?c.substring(b,b+_.Ae(a.Aa())):c.substring(b)}trim(a){return a.trim()}toLowerCase(a){return a.Ca()?a.Ba().toLocaleLowerCase(STc(a)):""}toUpperCase(a){return a.Ca()?a.Ba().toLocaleUpperCase(STc(a)):""}replace(a){return _.RTc(a)}startsWith(a,b){return a.startsWith(b)}endsWith(a,b){return a.endsWith(b)}toInt(a){return(a=a.match(/^\d+/))?Number(a[0]):0}};
var JTc=[0,_.Yk,-1,_.$k,_.Yk];_.KTc=[0,_.C,_.F,_.ITc,_.G,1,_.D,_.F,[0,_.G,_.D,_.G,_.F,_.ITc,[0,_.D,_.C,-1],_.el,[0,_.Yk,-2,_.C,_.Yk,_.G,_.C],_.G,_.C,_.G],_.C,_.gl,[0,3,_.F,[0,_.ol]],_.il,-1,_.G,_.F,JTc,_.C,_.G,_.C,_.G,JTc,[0,_.C,-1],_.F,[0,[5,6,7],_.G,_.D,1,_.D,_.zl,_.sSc,_.wl,-1,_.il,_.G,[0,_.D,-1,_.G]],_.C,_.il,_.G,[0,_.C,_.gl,_.F,[0,_.el,_.D]]];
_.kTc={};
_.LTc=class extends _.m{constructor(a){super(a)}getQuery(){return _.t(this,1)}setQuery(a){return _.Yg(this,1,a)}Ai(){return _.jh(this,1)}};_.MTc=class extends _.m{constructor(a){super(a,11)}getType(){return _.wj(this,1,1)}setType(a){return _.Ph(this,1,a)}Ve(){return _.Dk(this,1)}Se(){return _.Uh(this,1)}getUrl(){return _.t(this,2)}Sc(){return _.jh(this,2)}Ed(){return _.tj(this,2)}fGa(a){return _.Yg(this,8,a)}vP(){return _.n(this,_.LTc,3)}Cqa(){return _.Si(this,_.LTc,3)}};_.MTc.prototype.kb="N1YWaf";
_.NTc={};_.OTc=[0,_.D,1,_.C,-1,1,[0,[0,_.C]],_.ms,_.C,[0,_.D,_.ul,_.D],_.D,1,_.C,_.D,-4,1,_.D,-3,1,_.C,_.KTc,1,_.D,-1,2,_.D,1,_.C,_.G,_.il,_.G,-1,_.il,_.D,_.BTc];_.PTc=[-11,_.kTc,_.G,_.D,_.OTc,[-26,_.NTc,_.G,_.D,-4,_.G,_.D,-2,_.G,_.il,_.F,[0,_.D,-3,_.il],_.D,_.Yk,_.C,_.D,_.G,_.C,[0,_.Yk,_.Qk,_.Yk,-1,_.C,_.ul,-1,[0,_.il,-1,_.ul,-1],_.C,_.Fl,_.G,_.jl,_.C],1,_.C,_.il,_.C,[0,_.C,_.il,-1,_.ul,_.C,_.il,_.Yk,_.G]],_.C,1,_.C,_.D,-2];
_.In[50052456]=_.PTc;
_.qy=function(a){return _.dq(a)};_.udc=function(a){if(a!==""&&!(a instanceof _.WVa))throw Error("bg`"+_.gGa(a));a=_.Gka(a?a.getContent():"",{justification:"from Soy SanitizedTrustedResourceUri object"});return _.dh(a)};_.ry=function(a){if(!(a===""||a instanceof _.VVa||a instanceof _.Pe))throw Error("cg`"+_.gGa(a));if(a instanceof _.Pe)return _.ah(_.jc(a?a.toString():""));a=a?a.getContent():"";return _.ah(_.jc(a))};
_.sy=function(a){return a instanceof _.Xg?(a=(a=_.kta(a))?_.dc(a).toString():"",(0,_.Tp)(a)):a==null?a:null};_.ty=function(a){return a instanceof _.$g?(a=(a=_.bh(a))?_.kc(a):"",(0,_.Wp)(a)):a==null?a:null};_.uy=function(a){return a instanceof _.ch?(a=(a=_.eh(a))?_.ic(a).toString():"",(0,_.Xp)(a)):a==null?a:null};_.vdc=function(a){if(a==null)return a;if(a instanceof _.Qa)return _.kb(a);throw Error("dg`"+a);};_.wdc=function(a){return _.yca(a)};
_.Pz=function(a){let b;var c=a.getUrl();a=_.Gj(a,2,_.ih());var d;c=(d=c)!=null?d:"";if(a.length==0){{d=c;const f=d.search(":");f<0||_.Ul.i9b.isValid(d)?d=!0:(d=d.substring(0,f).toLowerCase(),d=/^[a-z][a-z\d+.-]*$/.test(d)&&d!=="javascript")}d||(c="about:invalid#zSoyz")}a:{d=c.toLowerCase();for(e of fTc)if(e.isValid(d)){var e=!0;break a}for(const f of a)if(d.startsWith(hTc[f].replace("_","-")+":")){e=!0;break a}e=!1}e||(c="about:invalid#zSoyz");c=_.ah(_.oc(c));return(b=_.ty(c))!=null?b:null};
_.Qz=function(a,b){return _.Yg(a,1,b)};_.iTc=function(a,b){return _.qk(a,2,b)};_.Rz=function(a,b){return _.rk(a,2,b)};_.Sz=class extends _.m{constructor(a){super(a)}getUrl(){return _.Zg(this,1)}Sc(){return _.jh(this,1)}Ed(){return _.tj(this,1)}};var fTc=[_.Ul.dIc,_.Ul.iMb,_.Ul.jMb,_.Ul.pJc,_.Ul.nIc,_.Ul.i9b],hTc=Object.keys({TEL:0,r9b:1,mnd:2,y4e:3,wsd:4,Vqd:5,NEe:6,TXe:7,Jud:8,Epd:20,WIe:9,XIe:27,QEe:10,VIe:11,Fpd:19,Gpd:22,jFe:12,Oqe:13,htd:14,V7b:15,Xsd:16,apd:17,Rte:18,Kue:35,YPe:21,iFe:23,Bue:24,Y3e:25,YOUTUBE:26,FILE:28,CONTENT:29,hGe:30,lFe:31,kFe:32,mFe:33,oFe:34});
_.dTc=function(a){const b=new _.Nx(1);_.Px(b,1);_.Ox(b,1);a=b.format(a);a==0&&/^\-/.test(a)&&(a=a.substr(1));return a};_.eTc=class{};
_.cTc=class{get(){return 0}};
_.rSc=function(a){return _.Fe(a,3)};
var hUc=class{merge(a,b){return _.Wz(a,b)}};var iUc=class{};var jUc=class{};var kUc=class{getUrl(a){if(a.getType()===2&&a.vP()){let b;a=(b=a.vP())==null?void 0:b.getQuery();if(a!=="")return _.Jn(new _.Pe("/search"),"q",a).toString()}throw Error("eh");}};var lUc=class{};_.cA=_.un(()=>{const a=new _.cUc;a.add("gws.common.api.jslayout.services.UniqueIdService",new _.Vz);a.add("gws.common.api.jslayout.services.DebugLevelService",new _.cTc);a.add("gws.common.api.jslayout.services.DoubleFormatterService",new _.eTc);a.add("gws.common.api.jslayout.services.StringService",new _.TTc);a.add("gws.common.api.knowledge.sharing.ShareExperimentMarksService",new _.VTc);a.add("com.google.template.jslayout.library.SafeTypeService",new jUc);a.add("com.google.gws.common.api.knowledge.link.SearchUrlGeneratorService",
new kUc);a.add("com.google.gws.common.api.sds.services.SdsDateTimeFormatterService",new lUc);a.add("com.google.gws.common.api.sds.services.SdsLogService",new hUc);a.add("gws.common.api.jslayout.services.MoneyFormatterService",new iUc);return a});_.mUc=_.un(()=>new _.eUc(document,!0));
_.wRe=function(a){return a.closest("[data-ved]")};_.KL=function(a){return _.Ge(_.wRe(a))};_.LL=function(a,b,c){const d=new _.KUa;b!==void 0||c?(b=_.mp(new _.vp,b?0:1),c&&_.tp(b,c),_.EUa(d,a,b)):_.EUa(d,a);a=_.HUa(d);_.FUa(d);return{hC:d,ved:a}};_.xRe=function(){return new _.bA(document,(0,_.cA)(),(0,_.mUc)())};
var S$d;_.T$d=function(a){var b=new S$d;return _.Ph(b,1,a)};S$d=class extends _.m{constructor(a){super(a)}};var U$d=[0,_.G];_.V$d=_.Lb(923,_.dp,S$d);_.ep[923]=U$d;_.bp[923]=U$d;
_.nv=function(a,b,c){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0;this.z=c!==void 0?c:0};_.nv.prototype.clone=function(){return new _.nv(this.x,this.y,this.z)};_.nv.prototype.toArray=function(){return[this.x,this.y,this.z]};
var sOb;_.tOb=function(a){a=_.AJa(a);const b=sOb();return a&&b?(a=new b(a),new _.Hd(a.m41,a.m42)):new _.Hd(0,0)};_.uOb=function(a,b,c){_.Qm(a,"transform","translate3d("+b+"px,"+c+"px,0px)")};sOb=_.un(function(){return _.ea.WebKitCSSMatrix!==void 0?_.ea.WebKitCSSMatrix:_.ea.MSCSSMatrix!==void 0?_.ea.MSCSSMatrix:_.ea.CSSMatrix!==void 0?_.ea.CSSMatrix:null});
var Z3h,$3h,a4h;_.X3h=function(a){if(_.xCe)a.style.paddingTop="46px",a.style.paddingBottom="72px",a.style.boxSizing="border-box";else if(_.dDe||_.eDe){let b;try{const c=_.lDe==null?void 0:_.lDe.Jf();if(!c||c==="")return;b=new _.Pe(c);const d=_.kDe(_.Ln(b,"padb")||""),e=_.kDe(_.Ln(b,"padt")||"");_.dDe&&d>0&&(a.style.paddingBottom=`${d}px`);_.eDe&&e>0&&(a.style.paddingTop=`${e}px`)}catch(c){}a.style.boxSizing="border-box"}else _.yCe&&(a.style.paddingBottom="108px",a.style.boxSizing="border-box")};
_.Y3h=function(a,b,c){const {ved:d,hC:e}=_.LL(b);_.Gp(_.Cp(a.oa(),e),new _.Mh(c,3)).log();return d};Z3h=function(a){if(_.e3h.has(a))return _.e3h.get(a);const b={Xdc:0,Pj:null,q1b:!1,rwb:null,NTc:null};_.e3h.set(a,b);return b};$3h=function(a,b,c){return b>a.WIa||c<_.e3h.get(a).Xdc};a4h=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const e=b.Xdc;c(await d(b.rwb));const f=a.client,g=a.Dwb;if($3h(f,7,e))return!1;if(f.Nf<7){const h=g.render(f);f.Nf=7;c(await d(h))}return!0}finally{d()}};
_.b4h=async function(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const f=a.client,g=a.Dwb,h=a.oG,k=Z3h(f),l=++k.Xdc;h==null||h.MFa();if(!$3h(f,1,l)&&(f.Nf<1&&g.RNc(f)&&(k.Pj=g.SPc(f),f.Nf=1,g.isActive(f)&&(g.Uxc(f),g.Yvc(f,()=>void(h==null?void 0:h.YNa())))),!$3h(f,2,l))){if(f.Nf<2){const p=g.z4c(f);k.NTc=p;f.Nf=2}if(!$3h(f,3,l)){if(f.Nf<3){const p=b(await c(k.NTc));if($3h(f,3,l))return;f.Nf<3&&(b(await c(g.Joc(f,p))),f.Nf=3)}if(!$3h(f,4,l)&&(f.Nf<4&&(k.Pj!=null||(k.Pj=g.UPc(f)),f.Nf=4),!$3h(f,5,l))){if(f.Nf<
5)try{k.q1b=g.rz(f),f.Nf=5}catch(p){}k.q1b&&(h==null||h.Q9a());if(!$3h(f,6,l)){h==null||h.aOa();f.Nf<6&&(k.rwb=g.gUc(f),f.Nf=6);var d=k.rwb,e=a4h(a,k);b(await c(_.f3h));b(await c(_.f3h));b(await c(_.f3h));g.isActive(f)&&(g.Uxc(f),b(await c(g.Yvc(f,()=>void(h==null?void 0:h.YNa())))),(0,_.lh.dirty)());try{b(await c(d)),h==null||h.ZNa()}catch(p){b()}try{b(await c(e))&&((0,_.lh.dirty)(),k.q1b||(h==null||h.Q9a(),k.q1b=!0),h==null||h.Dsa(k.Pj),h==null||h.LFa(),h==null||h.DWa(k.Pj))}catch(p){b()}}}}}}finally{c()}};var e4h=function(a){c4h(a);return d4h()},f4h=function(a){c4h(a);a="<g"+_.Y("DQYJue ")+_.Z("")+_.W("")+">";const b=d4h();return _.z(a+(b+"</g>"))},d4h=function(){return"<circle"+_.Y("BwkTpd ")+_.Z("")+_.W("")+"></circle><rect"+_.Y("BrqvYc ")+_.Z("")+_.W("")+"></rect><circle"+_.Y("BwkTpd ")+_.Z("")+_.W("")+"></circle>"},c4h=function(a){a.oa(g4h)||a.Aa(g4h,{},e4h,f4h)},g4h="t-ctlhNWCKvSA";var j4h=function(a){h4h(a);return i4h(a)},k4h=function(a){h4h(a);var b="<style"+_.Y("")+_.Z("")+_.W("")+">";a=i4h(a);return _.z(b+(a+"</style>"))},i4h=function(a){var b=_.hA(_.hi().Ua);a.Ba(".hjLOAe.zE1rf{background-color:"+_.V(b,"",c=>c.Wc())+"}");a.Ba(".hjLOAe .BwkTpd,.hjLOAe .BrqvYc{fill:"+_.V(b,"",c=>_.Lo(c))+"}");return""},h4h=function(a){a.oa(l4h)||a.Aa(l4h,{},j4h,k4h)},l4h="t-knD9z4X3SUg";var o4h=function(a){m4h(a);return n4h(a)},p4h=function(a){m4h(a);var b="<style"+_.Y("")+_.Z("")+_.W("")+">";a=n4h(a);return _.z(b+(a+"</style>"))},n4h=function(a){var b=_.hA(_.hi().Ua);a.Ba(".pZuFRb .lywBc{background-color:"+_.V(b,"",c=>c.kW())+";border-radius:12px}");a.Ba(".pZuFRb .BwkTpd,.pZuFRb .BrqvYc{fill:"+_.V(b,"",c=>c.d0())+"}");return""},m4h=function(a){a.oa(q4h)||a.Aa(q4h,{},o4h,p4h)},q4h="t-tt-mQ-0ZWBk";var t4h=function(a){r4h(a);return s4h(a)},u4h=function(a){r4h(a);var b="<style"+_.Y("")+_.Z("")+_.W("")+">";a=s4h(a);return _.z(b+(a+"</style>"))},s4h=function(a){var b=_.hA(_.hi().Dc),c=_.hA(_.hi().Vp);a.Ba(".zE1rf{width:100%;display:flex;flex-direction:row;justify-content:center;align-items:center;transition:opacity "+_.V(c,"",d=>_.t(d,50))+" "+_.V(c,"",d=>_.t(d,56))+";pointer-events:none}");a.Ba(".lywBc{display:flex;flex-direction:row;align-items:center;justify-content:center;padding:"+_.V(b,"",
d=>_.FA(d))+";"+(_.ZCe?"margin:"+_.V(b,"",d=>_.Uy(d))+";":"")+(_.ZCe?"":"margin:"+_.V(b,"",d=>_.EA(d)))+"}");a.Ba(".qn3Gnf.zE1rf{opacity:0}");a.Ba(".ofHTLc{width:70px;height:6px;margin:0 -6px}");a.Ba(".DQYJue{opacity:0}");a.Ba(".BwkTpd{cx:3px;cy:3px;r:3px;transform-box:fill-box;transform-origin:50% 50%}");a.Ba(".BrqvYc{x:3px;y:0px;width:1px;height:6px;transform-box:fill-box;transform-origin:0 50%;transform:scaleX(0)}");a.Ba(".lt9SHd{clip:rect(1px,1px,1px,1px);height:1px;overflow:hidden;position:absolute;white-space:nowrap;width:1px;user-select:none;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;z-index:-1000}");
return""},r4h=function(a){a.oa(v4h)||a.Aa(v4h,{},t4h,u4h)},v4h="t-dJvRb7h7eeI";var w4h=function(a,b){var c="";_.V(b,0,d=>_.RL(d))==0||_.V(b,0,d=>_.RL(d));_.V(b,0,d=>_.RL(d));return c+=' jscontroller="'+_.S("tlZhkd")+'" jsdata="'+_.S(_.xB("CI1deb",b))+'" jsaction="'+_.S("KF9ZEf:TQY5Y;kr34C:rMTFzd;X5vnkc:Figvhe;CZRWp:WO6jrc")+'"'+_.zB(a,{Fb:275360,track:[3]}).attributes},x4h=function(a,b){a=_.V(b,0,c=>_.RL(c))==0||_.V(b,0,c=>_.RL(c))==1;b=_.V(b,0,c=>_.RL(c))==2;return(a?"pZuFRb ":"")+(b?"hjLOAe ":"")},y4h=function(a,b){_.V(b,0,c=>_.RL(c))==0||_.V(b,0,c=>_.RL(c));_.V(b,0,c=>_.RL(c));
return""},z4h=function(a,b){_.V(b,0,c=>_.RL(c))==0||_.V(b,0,c=>_.RL(c));_.V(b,0,c=>_.RL(c));return!0},A4h=function(a,b){_.V(b,0,c=>_.RL(c))==0||_.V(b,0,c=>_.RL(c));_.V(b,0,c=>_.RL(c));return!1},D4h=function(a,b){B4h(a);return C4h(a,b.options)},E4h=function(a,b){B4h(a);var c=b.options;b="";_.V(c,0,d=>_.RL(d))==0||_.V(c,0,d=>_.RL(d));_.V(c,0,d=>_.RL(d));b+="<div"+_.Y(x4h(a,c)+"zE1rf ")+_.Z(y4h(a,c)+"")+_.W(w4h(a,c)+"")+">";c=C4h(a,c);b+=c+_.AB(a)+"</div>";return _.z(b)},C4h=function(a,b){var c=_.V(b,
0,d=>_.RL(d))==0||_.V(b,0,d=>_.RL(d))==1;b=_.V(b,0,d=>_.RL(d))==2;return s4h(a)+(c?n4h(a):"")+(b?i4h(a):"")+"<div"+_.Y("lywBc ")+_.Z("")+_.W("")+"><div"+_.Y("lt9SHd ")+_.Z("")+_.W(' aria-live="polite" role="status"')+"></div><svg"+_.Y("ofHTLc ")+_.Z("scale:"+_.S(_.Xz()=="rtl"?"-1 1":"1")+";")+_.W(' aria-hidden="true" viewBox="0 0 70 6" xmlns="http://www.w3.org/2000/svg"')+">"+_.tB(0,6).reduce(function(d){var e="<g"+_.Y("DQYJue ")+_.Z("")+_.W("")+">"+d4h()+"</g>";return d+e},"")+"</svg></div>"+_.AB(a)},
B4h=function(a){a.oa(F4h)||(a.Aa(F4h,{options:0},D4h,E4h,z4h,A4h,"",w4h,"zE1rf ",x4h,"",y4h),c4h(a),h4h(a),m4h(a),r4h(a))},F4h="t-E8dzlKj0hyg";var J4h,K4h,N4h,O4h,P4h;_.G4h=function(a,b,c){a="";_.hA(_.hi().Dc);return a+=' jsname="'+_.S("Qzjw6d")+'"'+(b?"":' aria-hidden="'+_.S("true")+'"')+(c!=""?' data-ved="'+_.S(c)+'"':"")};_.H4h=function(){_.hA(_.hi().Dc);return""};_.I4h=function(){_.hA(_.hi().Dc);return""};J4h=function(){_.hA(_.hi().Dc);return!0};K4h=function(){_.hA(_.hi().Dc);return!1};N4h=function(a){_.L4h(a);return _.M4h()};
O4h=function(a,b){_.L4h(a);var c=b.cOc,d=b.qua;b="";_.hA(_.hi().Dc);b+="<div"+_.Y(_.H4h(a,c,d)+"Fp3I9 ")+_.Z(_.I4h(a,c,d)+"")+_.W(_.G4h(a,c,d)+"")+">";a=_.M4h();return _.z(b+(a+"</div>"))};_.M4h=function(){_.hA(_.hi().Dc);return"<div"+_.Y("hwRvZe ")+_.Z("")+_.W("")+"></div>"};_.L4h=function(a){a.oa(P4h)||a.Aa(P4h,{cOc:0,qua:1},N4h,O4h,J4h,K4h,"",_.G4h,"Fp3I9 ",_.H4h,"",_.I4h)};P4h="t-eMRMwSHMfWM";var S4h=function(a){Q4h(a);return R4h(a)},T4h=function(a){Q4h(a);var b="<style"+_.Y("")+_.Z("")+_.W("")+">";a=R4h(a);return _.z(b+(a+"</style>"))},R4h=function(a){a.Ba(".Fp3I9{width:100%;height:100%;flex-shrink:0;transform:translate3d(0,0,0);"+(_.hL?"":"position:absolute;top:0;scroll-snap-align:center;scroll-snap-stop:always")+"}");a.Ba(".hwRvZe{width:100%;height:100%}");a.Ba(_.hL?".Fp3I9{position:absolute}":"");return""},Q4h=function(a){a.oa(U4h)||a.Aa(U4h,{},S4h,T4h)},U4h="t-dF5rznWAUns";var V4h=function(a){return _.zB(a,{Fb:237020,track:[3],href:_.iC(a,_.U("t-eMRMwSHMfWM",{cOc:!0,qua:""}))}).attributes+_.G4h(a,!0,"")},Y4h=function(a){W4h(a);return X4h(a)},Z4h=function(a){W4h(a);var b="";if(J4h(a,!0,"")){var c="<div"+_.Y(""+_.H4h(a,!0,"")+"Fp3I9 ")+_.Z(""+_.I4h(a,!0,""))+_.W(V4h(a)+"")+">";const d=X4h(a);c+=d+_.AB(a)+"</div>";b+=K4h(a,!0,"")?"":c}return _.z(b)},X4h=function(a){var b=_.M4h()+_.AB(a);return K4h(a,!0,"")?"":b},W4h=function(a){a.oa($4h)||(a.Aa($4h,{},Y4h,Z4h),_.L4h(a))},
$4h="t-GKxe-poKnxo";var c5h=function(a){a5h(a);return b5h(a)},d5h=function(a){a5h(a);var b="<style"+_.Y("")+_.Z("")+_.W("")+">";a=b5h(a);return _.z(b+(a+"</style>"))},b5h=function(a){var b=_.hA(_.hi().Ua);a.Ba(".HV5Yde{width:100%;height:100%;position:absolute;top:0;left:0;background-color:"+(_.V(b,"",c=>c.Wc())+";scrollbar-width:none;"+(_.hL?"":"overflow:hidden;overflow-x:scroll;scroll-snap-type:x mandatory;overscroll-behavior:none")+"}"));a.Ba(".cnmMUc .HV5Yde{position:relative}");a.Ba(".HV5Yde::-webkit-scrollbar{display:none}");
a.Ba(".pbZ4je{width:100%;height:100%;position:absolute;top:0;visibility:hidden}");a.Ba(".MPaS6{position:fixed;bottom:0;left:0;z-index:1}");return""},a5h=function(a){a.oa(e5h)||a.Aa(e5h,{},c5h,d5h)},e5h="t-Vs2sBFvBIdA";var m5h,n5h,o5h;_.f5h=function(a,b){var c="",d=_.hA(_.hi().Dc);b==null&&new _.fTe;return c+=' jsname="'+_.S("lHGsle")+'" data-gap="'+_.S(_.V(d,"",e=>_.FA(e)))+'"'+_.zB(a,{Fb:237019,track:[3]}).attributes};_.g5h=function(a,b){_.hA(_.hi().Dc);b==null&&new _.fTe;return""};_.h5h=function(a,b){_.hA(_.hi().Dc);b==null&&new _.fTe;return""};_.i5h=function(a,b){_.hA(_.hi().Dc);b==null&&new _.fTe;return!0};_.j5h=function(a,b){_.hA(_.hi().Dc);b==null&&new _.fTe;return!1};
m5h=function(a,b){_.k5h(a);return _.l5h(a,b.wNa)};n5h=function(a,b){_.k5h(a);var c=b.wNa;b="";_.hA(_.hi().Dc);c==null&&new _.fTe;b+="<div"+_.Y(_.g5h(a,c)+"HV5Yde ")+_.Z(_.h5h(a,c)+"")+_.W(_.f5h(a,c)+"")+">";c=_.l5h(a,c);b+=c+_.AB(a)+"</div>";return _.z(b)};
_.l5h=function(a,b){_.hA(_.hi().Dc);b=b==null?new _.fTe:b;var c=b5h(a)+R4h(a);if(_.aDe&&J4h(a,!0,"")){var d="<div"+_.Y(""+_.H4h(a,!0,"")+"Fp3I9 ")+_.Z(""+_.I4h(a,!0,""))+_.W(V4h(a)+"")+">"+X4h(a)+"</div>";c+=K4h(a,!0,"")?"":d}_.V(b,!1,e=>_.B(e,1))&&z4h(a,b)&&(d="<div"+_.Y("MPaS6 "+x4h(a,b)+"zE1rf ")+_.Z(y4h(a,b)+"")+_.W(w4h(a,b)+"")+">"+C4h(a,b)+"</div>",c+=A4h(a,b)?"":d);return c+=_.AB(a)};
_.k5h=function(a){a.oa(o5h)||(a.Aa(o5h,{wNa:0},m5h,n5h,_.i5h,_.j5h,"",_.f5h,"HV5Yde ",_.g5h,"",_.h5h),Q4h(a),W4h(a),a5h(a),B4h(a))};o5h="t-prAKbxAZKMw";
var j3h=function(a){return a?a.height:0},k3h=function(a){return a?(a.left?a.left.height:0)-(a.right?a.right.height:0):0},l3h=function(a){return a?a.count:0};var m3h,q3h,r3h,u3h,o3h,p3h;_.n3h=function(a){this.Ca=a||m3h;this.Aa=this.Ba=this.oa=null};m3h=function(a,b){return String(a)<String(b)?-1:String(a)>String(b)?1:0};q3h=function(a,b){const c=k3h(b);return c>1?(k3h(b.left)<0&&o3h(a,b.left),p3h(a,b)):c<-1?(k3h(b.right)>0&&p3h(a,b.right),o3h(a,b)):b};
r3h=function(a,b,c){const d=a.Ca(b,c.value);let e=!1;d>0?c.right?e=r3h(a,b,c.right):(c.right=new s3h(b,c),e=!0,c==a.Aa&&(a.Aa=c.right)):d<0&&(c.left?e=r3h(a,b,c.left):(c.left=new s3h(b,c),e=!0,c==a.Ba&&(a.Ba=c.left)));e&&(c.count++,c.height=Math.max(j3h(c.left),j3h(c.right))+1,q3h(a,c));return e};_.n3h.prototype.add=function(a){return this.oa?r3h(this,a,this.oa):(this.Aa=this.Ba=this.oa=new s3h(a),!0)};
var t3h=function(a,b,c){if(!c)return{value:null,root:null};var d=a.Ca(c.value,b);if(d>0)b=t3h(a,b,c.left),c.left=b.root,b=b.value;else if(d<0)b=t3h(a,b,c.right),c.right=b.root,b=b.value;else if(b=c.value,c.left&&c.right){b=c.value;let e=c.right;u3h(a,function(f){return f.left?e=f.left:null},c.right);c.value=e.value;d=t3h(a,e.value,c.right);c.right=d.root}else{d=c.left?c.left:c.right;if(!d)return a.Aa==c&&(a.Aa=c.parent),a.Ba==c&&(a.Ba=c.parent),{value:b,root:null};a.Aa==c&&(a.Aa=d);a.Ba==c&&(a.Ba=
d);d.parent=c.parent;c=d}c.count=l3h(c.left)+l3h(c.right)+1;c.height=Math.max(j3h(c.left),j3h(c.right))+1;return{root:q3h(a,c),value:b}};_.aa=_.n3h.prototype;_.aa.remove=function(a){a=t3h(this,a,this.oa);this.oa=a.root;return a.value};_.aa.clear=function(){this.Aa=this.Ba=this.oa=null};_.aa.contains=function(a){let b=!1;u3h(this,function(c){let d=null;const e=this.Ca(c.value,a);e>0?d=c.left:e<0?d=c.right:b=!0;return d});return b};
_.aa.indexOf=function(a){let b=-1,c=0;u3h(this,function(d){const e=this.Ca(d.value,a);if(e>0)return d.left;d.left&&(c+=d.left.count);if(e<0)return c++,d.right;b=c;return null});return b};_.aa.yj=function(){return this.oa?this.oa.count:0};_.aa.getHeight=function(){return this.oa?this.oa.height:0};_.aa.qF=function(){const a=[];_.v3h(this,function(b){a.push(b)});return a};
_.v3h=function(a,b){if(a.oa){a=a.Ba;for(var c=a.left?a.left:a;a!=null;)if(a.left!=null&&a.left!=c&&a.right!=c)a=a.left;else{if(a.right!=c&&b(a.value))break;const d=a;a=a.right!=null&&a.right!=c?a.right:a.parent;c=d}}};u3h=function(a,b,c){for(c=c?c:a.oa;c&&c!=null;)c=b.call(a,c)};
o3h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.right,b.right.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.right,b.right.parent=b.parent):(a.oa=b.right,a.oa.parent=null);a=b.right;b.right=b.right.left;b.right!=null&&(b.right.parent=b);a.left=b;b.parent=a;a.count=b.count;b.count-=(a.right?a.right.count:0)+1;w3h(b);w3h(a);return a};
p3h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.left,b.left.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.left,b.left.parent=b.parent):(a.oa=b.left,a.oa.parent=null);a=b.left;b.left=b.left.right;b.left!=null&&(b.left.parent=b);a.right=b;b.parent=a;a.count=b.count;b.count-=(a.left?a.left.count:0)+1;w3h(b);w3h(a);return a};_.n3h.prototype.copy=function(a){const b=new _.n3h(this.Ca);if(!this.oa)return b;a=this.oa.copy(null,this.Ca,a);b.oa=a.root;b.Ba=a.Y3c;b.Aa=a.Hbd;return b};
var s3h=function(a,b){this.value=a;this.parent=b?b:null;this.count=1;this.right=this.left=null;this.height=1},w3h=function(a){a.height=Math.max(a.left?a.left.height:0,a.right?a.right.height:0)+1};s3h.prototype.copy=function(a,b,c){var d=c?c(this.value):this.value;a=new s3h(d,a);a.count=this.count;a.height=this.height;let e=d=a;this.left&&(d=this.left.copy(a,b,c),a.left=d.root,d=d.Y3c);this.right&&(b=this.right.copy(a,b,c),a.right=b.root,e=b.Hbd);return{root:a,Y3c:d,Hbd:e}};
var y3h,C3h,D3h;_.x3h=function(a){if(a=a.id)return a};y3h=function(a,b){for(const c of a)if(c.nodeType===Node.ELEMENT_NODE){c.matches('[data-sve]:not([data-nv="1"])')&&b(c);for(const d of c.querySelectorAll('[data-sve]:not([data-nv="1"])'))b(d)}};_.z3h=function(a){return a.closest("[data-viewer-group]")};_.B3h=function(a){var b=a.getAttribute("data-ssid");return b&&b.length>0?new _.A3h(void 0,_.x3h(a)||"",b):(b=_.z3h(a))?new _.A3h(b,_.x3h(a)||""):null};
C3h=function(a,b,c){c=c||a.oa;const d=c.left?c.left.count:0;return b<d?C3h(a,b,c.left):b==d?c:C3h(a,b-d-1,c.right)};D3h=function(a,b){return b<0||b>=a.yj()?null:C3h(a,b).value};_.E3h=class extends _.m{constructor(a){super(a)}yUa(){return _.t(this,1)}};_.F3h=[0,_.D,-1,_.C];var G3h=_.Sb(_.F3h);var H3h;H3h=function(a,b){for(const c of b)y3h(c.removedNodes,d=>{a.oa.remove(d)}),y3h(c.addedNodes,d=>{a.group&&_.z3h(d)!==a.group||a.oa.add(d)})};_.I3h=function(a,b){return a.oa.indexOf(b)};
_.A3h=class{constructor(a,b,c){this.group=a;this.Ca=b;this.Ba=new MutationObserver(g=>{H3h(this,g)});this.oa=new _.n3h(_.bJa);let d,e;this.streamId=(e=(d=a==null?void 0:a.getAttribute("data-id"))!=null?d:c)!=null?e:"";let f;this.Aa=(f=a==null?void 0:a.getAttribute("data-cid"))!=null?f:this.streamId;if(a)this.Ba.observe(a,{subtree:!0,childList:!0,attributes:!1}),y3h(a.childNodes,g=>{_.z3h(g)===this.group&&this.oa.add(g)});else if(!this.scan(b))throw Error("eo`"+this.streamId);}scan(a){if(this.group)return 0;
this.oa.clear();let b=!1;const c=document.documentElement.querySelectorAll(`[data-ssid="${this.streamId}"]`);y3h(c,d=>{d.getAttribute("data-ssid")===this.streamId&&(this.oa.add(d),a&&_.x3h(d)===a&&(b=!0))});if(a&&!b)throw Error("fo`"+a);return this.oa.yj()}getType(){return 1}QLd(a){const b=this.yhb(a),c={};let d;c.k=(d=b.getAttribute("data-k"))!=null?d:a;this.Aa&&(c.id=this.Aa);this.streamId&&(c.vid=this.streamId);(a=_.x3h(b))&&(c.vhid=a);return c}serialize(a){var b=new _.E3h;b=_.Yg(b,1,this.streamId);
a=_.x3h(this.yhb(a));a=_.Yg(b,2,a);a=_.Rh(a,3,this.group===void 0);return G3h(a)}async mxb(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const e=D3h(this.oa,a);if(!e)throw Error("go`"+a);try{let f;const g=_.vsa((f=this.group)!=null?f:e),h=c(await d(g.getController(e)));return c(await d(h.Pca({source:b,count:this.u5(),index:a})))}catch(f){throw c(),Error("ho`"+a+"`"+this.streamId+"`"+(e==null?void 0:e.id)+"`"+(e==null?void 0:e.isConnected)+"`"+f);}}finally{d()}}yhb(a){return D3h(this.oa,a)}pTb(){let a=0;
_.v3h(this.oa,b=>{if(_.x3h(b)===this.Ca)return!0;a++;return!1});this.u5();return a}u5(){return this.oa.yj()}j9c(){return this.oa.Ba.value}dispose(){this.Ba.disconnect()}};
var Tth,Uth,Vth,Wth,Xth,Yth,auh,cuh,duh,euh,$th,iuh,huh,muh,luh,nuh,ouh,guh;Tth=function(a){let b;a=Number((b=a.trim().match(/^(\d+|\d+\.\d+)px$/))==null?void 0:b[1]);return isNaN(a)?null:a};Uth=function(a){return`linear(${a.map(([b,c])=>`${b} ${100*c}%`).join(",")})`};Vth=function(a,b){return b.map(([c,d])=>[(1/(c*(1-a)+a)-1/a)/(1-1/a),d])};Wth=function(a,b,c){return(1-a)*(1-a)*(1-a)*0+3*(1-a)*(1-a)*a*b+3*(1-a)*a*a*c+a*a*a};
Xth=function(a){const b=Number(a.split("%")[0])/100;if(isNaN(b))throw Error("On`"+a);return b};
Yth=function(a,b){a=a.match(/linear\((.*)\)/i);const c=(a?a[1].split(",").map(e=>e.trim()):["0","1"]).map(e=>{e=e.split(" ");const f=Number(e[0]),g=[[f]];e.length>=2&&g[0].push(Xth(e[1]));e.length>=3&&g.push([f,Xth(e[2])]);return g}).flatMap(e=>e);c[0][1]=0;c[c.length-1][1]=1;for(let e=0;e<c.length;e++)if(c[e].length===1){var d=e-1;a=c.findIndex((g,h)=>h>e&&g[1]!==void 0);const f=(c[a][1]-c[d][1])/(a-d);d=c[d][1];for(let g=e;g<a;g++)d+=f,c[g][1]=d}return c.map(([e,f],g)=>{const h=[[e,f]];var k=c[g+
1];if(!k)return h;var l=k[1]-f;g=Math.ceil(l*b/8.3333333);l/=g;k=(k[0]-e)/g;for(let p=0;p<g-1;p++)f+=l,e+=k,h.push([e,f]);return h}).flatMap(e=>e)};
auh=function(a="root",b=1,c=!1){const d=[];if(b===0)return d;var e=_.Zth(a,c);if(!e)return d;c=e.V7c;const f=e.Y7c,g=e.Z7c,h=e.T7c,k=e.R6c,l=e.U6c,p=e.V6c,q=e.Sma;var r=e.YP;const u=e.animation,A=e.keyframes,E=e.duration,I=e.effect;e=e.fN*(b===4?1:b===5?h/q:g/p);r=b===3||b===2?r*h/q:e;a!=="sb"&&(f+h<0||l+q<0)&&u.cancel();const N=[{transform:`translate(${c}px, ${f}px) scale(${e}, ${r})`,easing:A[0].easing,transformOrigin:"top left"},{transform:`translate(${k}px, ${l}px) scale(1, 1)`,easing:A[1].easing,
transformOrigin:"top left"}];d.push(()=>{I.setKeyframes(N)});b===2&&d.push(...$th({name:a,easing:A[0].easing,duration:E,W7c:e,X7c:r}));return d};
_.Zth=function(a,b=!1){if(!navigator.userAgent.includes(" Chrome/137.")){var c=`::view-transition-group(${a})`;if(a=document.getAnimations().find(r=>{let u;return((u=r.effect)==null?void 0:u.pseudoElement)===c})){var d=a.effect,e=d.getKeyframes(),f=a.effect.getTiming().duration;if(e[1].transform==="none"){a.currentTime=f;var g=window.getComputedStyle(document.documentElement,c);var h=new DOMMatrix(g.transform);var k=Tth(g.width);g=Tth(g.height);a.currentTime=0}else h=new DOMMatrix(e[1].transform),
k=Tth(e[1].width),g=Tth(e[1].height);if(k!==null&&g!==null){var l=Tth(e[0].width),p=Tth(e[0].height);if(l!==null&&p!==null){var q=new DOMMatrix(e[0].transform);q=_.buh(q);b&&(q=cuh(q,l,p,c));return{V7c:q.left,Y7c:q.top,Z7c:l,T7c:p,R6c:h.e,U6c:h.f,V6c:k,Sma:g,fN:q.fN,YP:q.YP,animation:a,keyframes:e,duration:f,effect:d}}}}}};_.buh=function(a){return{left:a.e,top:a.f,fN:a.a,YP:a.d}};
cuh=function(a,b,c,d){try{const e=window.getComputedStyle(document.documentElement,d).transformOrigin,{Z3c:f,Yhd:g}=duh(Object.assign({},{transformOrigin:e,width:b,height:c},a));if(isNaN(g)||isNaN(f))return a;a.left+=f;a.top+=g}catch(e){}return a};duh=function({transformOrigin:a,width:b,height:c,fN:d,YP:e}){a=euh({transformOrigin:a,height:c,width:b});return a===null?{Z3c:0,Yhd:0}:{Z3c:a.a4c*(1-d),Yhd:a.Zhd*(1-e)}};
euh=function({transformOrigin:a,height:b,width:c}){const d=a.match(/(-?\d+\.?\d*)px (-?\d+\.?\d*)px/);if(d){const [,e,f]=d;return{a4c:Number(e),Zhd:Number(f)}}if(a=a.match(/(-?\d+\.?\d*)% (-?\d+\.?\d*)%/)){const [,e,f]=a;return{a4c:c*Number(e)/100,Zhd:b*Number(f)/100}}return null};$th=function(a){return _.fuh(a).map(({keyframes:b,options:c})=>()=>{try{document.documentElement.animate(b,c)}catch(d){d.details={src:"spa-vt-csa",kf:JSON.stringify(b),o:JSON.stringify(c)},d.e5e=2}})};
_.fuh=function({name:a,easing:b,duration:c,W7c:d,X7c:e,transformOrigin:f="top left"}){const g=[];if(e===1)return[];const h=`::view-transition-image-pair(${a})`;var k=b;if(e===1)var l=k;else{b=Number(c);isNaN(b)&&(b=500);k=k.replace(/\n/g,"").replace(/\s*,\s*/g,",").replace(/\(\s*/g,"(").replace(/\s*\)/g,")").trim();if(k.startsWith("linear("))l=Yth(k,b);else{b:{var p=guh[k.trim().toLowerCase()];if(p)l=p;else{try{var q=k.match(/cubic-bezier\s*\(\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*\)/i);
if(q){l=q.slice(1).map(Number);break b}}catch(r){}l=guh.linear}}q=2*Math.round(b/8.3333333);b=[];for(k=0;k<=q;k++)p=k/q,b.push([Wth(p,l[1],l[3]),Wth(p,l[0],l[2])]);l=b}l=Vth(e,l);l=Uth(l)}c={duration:c,easing:l};g.push({keyframes:[{transformOrigin:f,transform:`scale(1, ${d/e})`},{transformOrigin:f,transform:"scale(1, 1)"}],options:Object.assign({},c,{pseudoElement:h})});a=`::view-transition-group(${a})`;f=window.getComputedStyle(document.documentElement,a).borderRadius;(f=Tth(f))&&g.push({keyframes:[{borderRadius:`${f/
d}px / ${f/e}px`},{borderRadius:`${f}px`}],options:Object.assign({},c,{pseudoElement:a})});return g};iuh=function(a){return document.startViewTransition?document.startViewTransition(a):huh(a)};huh=function(a){a=Promise.resolve(a()).then(()=>{});return{ready:Promise.resolve(),updateCallbackDone:a,finished:a,skipTransition:()=>{}}};
muh=function(a,b={}){for(var c of _.juh())c.cancel();const d=document.createElement("style");document.head.prepend(d);const e=[];var f;b.groups=(f=b.groups)!=null?f:[];const g=()=>b.root?[b.root,...b.groups]:b.groups;b.root&&(b.root.viewTransitionName="root");var h;((h=b.root)==null?0:h.disable)&&_.kuh(d,":root",{viewTransitionName:"none"});b.lHd&&_.kuh(d,"::view-transition",{pointerEvents:"none"});for(f=0;f<b.groups.length;f++)h=b.groups[f],c=`spa-vt-${f}`,h.viewTransitionName=c,h.element&&(h.element.style.viewTransitionName=
c);f=iuh(async()=>{var k=(0,_.Rf)(),l=k();k=k(1);try{const p=g().map(q=>{let r;return(r=q.fI)==null?void 0:r.call(q)}).filter(q=>q);k(await l(Promise.all([a(),...p])));for(const q of b.groups)q.Zda===void 0&&(q.Zda=q.T4a?q.T4a():q.element),q.element&&(q.element.style.viewTransitionName=""),q.Zda&&(q.Zda.style.viewTransitionName=q.viewTransitionName)}finally{l()}});f.updateCallbackDone.then(()=>{let k,l,p;b=(p=(l=(k=b).updateCallbackDone)==null?void 0:l.call(k,b))!=null?p:b;for(const q of b.groups){let r,
u;(u=(r=q).updateCallbackDone)==null||u.call(r,q)}});f.updateCallbackDone.catch(()=>{});f.ready.then(()=>{var k,l;(l=(k=b).ready)==null||l.call(k,b);for(var p of b.groups){let q,r;(r=(q=p).ready)==null||r.call(q,p)}for(const q of b.groups)q.Zda&&(q.Zda.style.viewTransitionName="");if(k=b.keyframes)for(const q of k){k=d.sheet.insertRule(`@keyframes ${q.name} {}`);k=d.sheet.cssRules[k];for(const [r,u]of Object.entries(q.keyframes)){l=u;k.appendRule(`${r} {}`);p=k.cssRules[k.cssRules.length-1];for(const A in l)l.hasOwnProperty(A)&&
(p.style[A]=l[A])}}for(const q of g())e.push(...luh(d,q));for(const q of g()){let r;((r=q)==null?0:r.hSa)&&e.push(...auh(q.viewTransitionName,q.hSa,q.P$b))}for(const q of e)q()},()=>{});f.finished.catch(()=>{});f.finished.finally(()=>{let k,l;(l=(k=b).finished)==null||l.call(k,b);for(const p of b.groups){let q,r;(r=(q=p).finished)==null||r.call(q,p)}for(const p of b.groups)p.element&&(p.element.style.viewTransitionName=""),p.Zda&&(p.Zda.style.viewTransitionName="");d.remove()});return f};
luh=function(a,b){if(!b)return[];const c=b.viewTransitionName;return[nuh(a,c,"old",b.Hra),nuh(a,c,"new",b.new),nuh(a,c,"group",b.group),nuh(a,c,"image-pair",b.AAb)].flatMap(d=>d)};nuh=function(a,b,c,d){const e=[];if(!d)return e;d.animation&&(e.push(ouh(b,c,d.animation)),d.styles=d.styles||{},d.styles.animation="none");let f;(f=d.HNb)==null||f.forEach(g=>{e.push(ouh(b,c,g))});d.styles&&_.kuh(a,`::view-transition-${c}(${b})`,d.styles);return e};
ouh=function(a,b,c){const d=`::view-transition-${b}(${a})`;return()=>document.documentElement.animate(c.keyframes,Object.assign({},c.options,{pseudoElement:d}))};_.kuh=function(a,b,c){b=a.sheet.insertRule(`${b} {}`);a=a.sheet.cssRules[b];for(const d in c)c.hasOwnProperty(d)&&(a.style[d]=c[d]);return a};_.juh=function(){return document.getAnimations().filter(a=>{a=a.effect;let b;return(a==null?void 0:a.target)===document.documentElement&&((b=a.pseudoElement)==null?void 0:b.startsWith("::view-transition"))})};
_.quh=function(a,b){return _.puh||(b==null||!b.URd)&&window.matchMedia("(prefers-reduced-motion: reduce)").matches?huh(a):muh(a,b)};guh={linear:[0,0,1,1],ease:[.25,.1,.25,1],"ease-in":[.42,0,1,1],"ease-out":[0,0,.58,1],"ease-in-out":[.42,0,.58,1]};_.puh=!!(_.Bi[68]>>14&1);_.ruh=!!(_.Bi[68]>>15&1);_.suh=!!document.startViewTransition;
_.f8e={mNe:0,iNe:1,kNe:2,hNe:3,jNe:4,lNe:5};
var yQe,zQe,AQe,BQe,CQe,FQe,GQe,HQe;yQe=function(){return""};zQe=function(){return""};AQe=function(){return""};BQe=function(){return!0};CQe=function(){return!1};FQe=function(a){_.DQe(a);return _.EQe()};GQe=function(a){_.DQe(a);return _.z(_.EQe())};_.EQe=function(){return"\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430..."};_.DQe=function(a){a.oa(HQe)||a.Aa(HQe,{},FQe,GQe,BQe,CQe,"",yQe,"",zQe,"",AQe)};HQe="t-YP5RR70-9Qs";var KQe,LQe,MQe;KQe=function(a){_.IQe(a);return _.JQe()};LQe=function(a){_.IQe(a);a="<div"+_.Y("RoKmhb ")+_.Z("")+_.W("")+">";const b=_.JQe();return _.z(a+(b+"</div>"))};_.JQe=function(){return"<div"+_.Y("beDQP ")+_.Z("")+_.W("")+"><div"+_.Y("DU0NJ SPKFmc x3SdXd J7uuUe ")+_.Z("")+_.W("")+"></div></div><div"+_.Y("FcXfi ")+_.Z("")+_.W("")+"><div"+_.Y("DU0NJ SPKFmc tS3P5 ")+_.Z("")+_.W("")+"></div></div><div"+_.Y("beDQP ")+_.Z("")+_.W("")+"><div"+_.Y("DU0NJ SPKFmc x3SdXd sDPIC ")+_.Z("")+_.W("")+"></div></div>"};
_.IQe=function(a){a.oa(MQe)||a.Aa(MQe,{},KQe,LQe)};MQe="t-nBXuT1jwnnY";
_.Che=!!(_.Bi[68]&8192);
var NQe=function(a){a=' height="'+_.S(String(a))+'" src="'+_.kB(_.S(_.$A("//www.gstatic.com/ui/v1/activityindicator/loading"+(_.Che?".svg":"_"+String(a)+".gif"))))+'" width="'+_.S(String(a))+'" aria-label="';a+=_.cB(_.EQe());return a+'"'},PQe=function(a){OQe(a);return""},QQe=function(a,b){OQe(a);a=b.size;a="<img"+_.Y("")+_.Z("")+_.W(NQe(a)+' role="progressbar"')+">";return _.z(a)},OQe=function(a){a.oa(RQe)||(a.Aa(RQe,{size:0},PQe,QQe),_.DQe(a))},RQe="t-XVClaBF4XUE";var UQe=function(a,b){SQe(a);return TQe(a,b.size)},VQe=function(a,b){SQe(a);a=TQe(a,b.size);return _.z(a)},TQe=function(a,b){a="<div"+_.Y("lP3Jof nNMuOd ")+_.Z("height:"+_.S(_.bB(a.isRtl()?_.YA("height",String(b)+"px"):String(b)+"px"))+";width:"+_.S(_.bB(a.isRtl()?_.YA("width",String(b)+"px"):String(b)+"px"))+";")+_.W(' aria-label="'+_.cB(_.EQe())+'" role="progressbar"')+">";b="<div"+_.Y("VQdeab RoKmhb ")+_.Z("")+_.W("")+">"+_.JQe()+"</div>";a+=b;b="<div"+_.Y("IEqiAf RoKmhb ")+_.Z("")+_.W("")+">"+
_.JQe()+"</div>";a+=b;b="<div"+_.Y("smocse RoKmhb ")+_.Z("")+_.W("")+">"+_.JQe()+"</div>";a+=b;b="<div"+_.Y("FlKbCe RoKmhb ")+_.Z("")+_.W("")+">"+_.JQe()+"</div>";return a+b+"</div>"},SQe=function(a){a.oa(WQe)||(a.Aa(WQe,{size:0},UQe,VQe),_.DQe(a),_.IQe(a))},WQe="t-3W4tVYHH3r4";var XQe,YQe,ZQe,$Qe,aRe,bRe;XQe=function(){return""};_.GL=function(a,b){a=_.HB||b;return(a?"jbBItf ":"")+(a?"GgTJWe ":"")+(a?"VDgVie ":"")};
_.HL=function(a,b,c,d){c=c==null?3:c;d=d==null?0:d;b=_.HB||b;c=c==3?24:c==2?19:16;d=d==3?36:d==2?24:d==1?20:d==4?16:30;return"height:"+_.S(_.bB(a.isRtl()?_.YA("height",b?String(d)+"px":String(c)+"px"):b?String(d)+"px":String(c)+"px"))+";"+(b?"":"width:"+_.S(_.bB(a.isRtl()?_.YA("width",String(c)+"px"):String(c)+"px"))+";")+(b?"min-width:"+_.S(_.bB(a.isRtl()?_.YA("min-width",String(d)+"px"):String(d)+"px"))+";":"")};YQe=function(){return!0};ZQe=function(){return!1};
$Qe=function(a,b){_.IL(a);return _.JL(a,b.ATa,b.nlb,b.UNa)};aRe=function(a,b){_.IL(a);var c=b.ATa,d=b.nlb,e=b.UNa;b="<g-loading-icon"+_.Y(_.GL(a,c,d,e)+"")+_.Z(_.HL(a,c,d,e)+"")+_.W("")+">";a=_.JL(a,c,d,e);return _.z(b+(a+"</g-loading-icon>"))};
_.JL=function(a,b,c,d){c=c==null?3:c;d=d==null?0:d;b=_.HB||b;d=d==3?36:d==2?24:d==1?20:d==4?16:30;var e=c==3?24:c==2?19:16;c=_.zB(a,{Fb:103896,Al:!0}).attributes+_.AB(a);b&&(a=TQe(a,d),c+=a);b||(a="<img"+_.Y("")+_.Z("")+_.W(NQe(e)+' role="progressbar"')+">",c+=a);return c};_.IL=function(a){a.oa(bRe)||(a.Aa(bRe,{ATa:0,nlb:1,UNa:2},$Qe,aRe,YQe,ZQe,"",XQe,"",_.GL,"",_.HL),OQe(a),SQe(a))};bRe="t-aEtoEkf3B4A";
var u0e,v0e,w0e,x0e,y0e,z0e,A0e,B0e;_.t0e=function(a){_.r0e(a);let b;b="<div"+_.Y("rVGT ")+_.Z("")+_.W("")+">";const c=_.s0e(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+"</div>";a.Ha();return _.z(b)};u0e=function(){return""};v0e=function(){return""};w0e=function(){return""};x0e=function(){return!0};y0e=function(){return!1};z0e=function(a){_.r0e(a);return _.s0e(a)};A0e=function(a){_.r0e(a);var b="<div"+_.Y("rVGT ")+_.Z("")+_.W("")+">";a=_.s0e(a);return _.z(b+(a+"</div>"))};
_.s0e=function(a){a.Ba(".rVGT{display:flex;justify-content:center;left:50%;position:absolute;top:18%;transform:translateX(-50%);z-index:1}");return"<g-loading-icon"+_.Y(_.GL(a,!0,null,null)+"")+_.Z(_.HL(a,!0,null,null)+"")+_.W("")+">"+_.JL(a,!0,null,null)+"</g-loading-icon>"};_.r0e=function(a){a.oa(B0e)||(a.Aa(B0e,{},z0e,A0e,x0e,y0e,"",u0e,"rVGT ",v0e,"",w0e),_.IL(a))};B0e="t-Zg8vSMWW_Oc";
var PYe,QYe,RYe;PYe=function(a){_.NYe(a);return _.OYe()};QYe=function(a){_.NYe(a);return _.z(_.OYe())};_.OYe=function(){return"\u0417\u0430\u043a\u0440\u044b\u0442\u044c"};_.NYe=function(a){a.oa(RYe)||a.Aa(RYe,{},PYe,QYe)};RYe="t-h4_qT3LgTLQ";
_.jC=function(a){return _.t(a,23)};_.kC=function(a){return _.Fe(a,1,-1)};_.lC=function(a){var b=new _.fp;return _.si(b,1,a)};_.mC=function(a,b){return _.Rh(a,3,b)};_.nC=function(a,b){return _.Rh(a,4,b)};_.pC=function(a,b){return _.Kb(a,_.fp,13,b)};_.qC=function(a){return _.Si(a,_.fp,13)};_.rC=function(a,b){return _.Rh(a,18,b)};
var aZe,bZe,cZe;_.SYe=function(){return' role="button" tabindex="0"'};_.TYe=function(a,b){var c="";b=b==null?_.lC(242837):b;c=c+' aria-label="'+_.cB(_.OYe());return c+='" jsaction="'+_.S("trigger.gZgazf")+'"'+_.zB(a,{Fb:_.V(b,-1,d=>_.kC(d)),track:[3]}).attributes};_.UYe=function(){return"VB2c0b "};_.VYe=function(a,b){b==null&&_.lC(242837);return""};
_.WYe=function(a,b,c,d){var e="";b==null&&_.lC(242837);return e+=(c?"background-color:"+_.S(_.bB(a.isRtl()?_.YA("background-color",c):c))+";":"")+(d?"color:"+_.S(_.bB(a.isRtl()?_.YA("color",d):d))+";":"")};_.XYe=function(a,b){b==null&&_.lC(242837);return!0};_.YYe=function(a,b){b==null&&_.lC(242837);return!1};aZe=function(a,b){_.ZYe(a);return _.$Ye(a,b.Oe)};
bZe=function(a,b){_.ZYe(a);var c=b.Oe,d=b.tDd,e=b.Lua;b="";c==null&&_.lC(242837);b+="<div"+_.Y(_.VYe(a,c,d,e)+_.UYe())+_.Z(_.WYe(a,c,d,e)+"")+_.W(_.TYe(a,c,d,e)+_.SYe())+">";c=_.$Ye(a,c);b+=c+_.AB(a)+"</div>";return _.z(b)};
_.$Ye=function(a,b){b==null&&_.lC(242837);b=_.hA(_.hi().Ua);a.Ba(".VB2c0b{color:"+(_.V(b,"",d=>_.uA(d))+";position:absolute;top:6px;right:16px;width:40px;height:40px;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:1}"));a.Ba(".VB2c0b:hover{background-color:"+_.V(b,"",d=>_.yA(d))+"}");b="";var c="<span"+_.Y(""+_.UB())+_.Z(_.VB(a,24)+"")+_.W("")+">"+_.TB()+"</span>";return b=b+c+_.AB(a)};
_.ZYe=function(a){a.oa(cZe)||(a.Aa(cZe,{Oe:0,tDd:1,Lua:2},aZe,bZe,_.XYe,_.YYe,_.SYe(),_.TYe,_.UYe(),_.VYe,"",_.WYe),_.NYe(a),_.WB(a))};cZe="t-UPSXq0uirLs";
var AZe,BZe,CZe,DZe,EZe,FZe,GZe;_.zZe=function(a){_.wZe(a);let b;b="<div"+_.Y("ZCPy9b ")+_.Z("")+_.W(_.xZe(a)+"")+">";const c=_.yZe(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+_.AB(a)+"</div>";a.Ha();return _.z(b)};_.xZe=function(a){return _.zB(a,{Fb:164355}).attributes};AZe=function(){return""};BZe=function(){return""};CZe=function(){return!0};DZe=function(){return!1};EZe=function(a){_.wZe(a);return _.yZe(a)};
FZe=function(a){_.wZe(a);var b="<div"+_.Y("ZCPy9b ")+_.Z("")+_.W(_.xZe(a)+"")+">";const c=_.yZe(a);b+=c+_.AB(a)+"</div>";return _.z(b)};_.yZe=function(a){a.Ba(".ZCPy9b{height:52px}");var b="";if(_.XYe(a,null,"","")){var c="<div"+_.Y(_.VYe(a,null,"","")+_.UYe())+_.Z(_.WYe(a,null,"","")+"")+_.W(_.TYe(a,null,"","")+_.SYe())+">"+_.$Ye(a,null)+"</div>";b+=_.YYe(a,null,"","")?"":c}return b+=_.AB(a)};_.wZe=function(a){a.oa(GZe)||(a.Aa(GZe,{},EZe,FZe,CZe,DZe,"",_.xZe,"ZCPy9b ",AZe,"",BZe),_.ZYe(a))};
GZe="t-75SV09ER6Uw";
_.ML=function(a){const b=document.createElement("div"),c=_.xRe(),{tMa:d,bG:e}=_.wUc();c.Pa=d;_.Qc(b,a(c));if(!b.firstElementChild)throw Error("Di");return{node:b.firstElementChild,bG:e}};_.yRe=class{constructor(a,b){this.oa=a;this.jya=b}dispatch(){var a=this.oa,b=this.jya;const c=_.Wg();c.Mc("sqi","21").Mc("ei",a);b&&c.Mc("pepp",b);c.log()}};
_.rWd=!!(_.Bi[71]&1);_.sWd=!!(_.Bi[71]&2);_.tWd=!!(_.Bi[71]&4);_.uWd=!!(_.Bi[71]&8);_.vWd=!!(_.Bi[71]&16);
_.MD=function(a){return _.t(a,1)};_.ND=function(a){return _.t(a,4)};_.OD=function(a){return _.t(a,3)};_.fdd=function(a){return _.t(a,34)};_.PD=function(a){return _.t(a,37)};_.QD=function(a){return _.t(a,6)};_.RD=!!(_.Bi[25]>>19&1);
_.v("Sp69O");
var kqB,lqB,mqB,nqB,oqB,qqB,pqB,sqB,rqB,vqB,tqB,xqB,CqB,DqB,EqB,OqB,MqB,PqB,QqB,TqB,UqB,SqB,VqB,RqB,XqB,WqB,YqB,IqB,NqB,ZqB,$qB,arB,FqB,brB,HqB,crB,drB,LqB,jqB,erB,frB,grB,hrB;kqB=function(a){if(jqB)return jqB;const b=_.Ge(_.um("iGkMSe"));return jqB=_.Y3h(a,251333,b)};lqB=function(){const a=new _.Xt(_.lDe.Jf());return _.Fsr.test(a.pathname)||_.Osr.test(a.pathname)||_.Psr.test(a.pathname)};
mqB=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const e={};a.forEach(g=>{e[String(g)]=_.$pB[g]});const f=c(await d(_.Xf(b,{service:e})));return Object.values(f.service)}finally{d()}};
nqB=function(a,b){var c={duration:250,easing:"cubic-bezier(.75,1,.75,1)"};const d=b.width/a.width,e=b.left-a.left*d;a=b.top-a.top*d;return{U2d:{keyframes:[{opacity:1,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:0,transform:`translate(${e}px, ${a}px) scale(${d})`,transformOrigin:"top left",mixBlendMode:"normal"}],options:c},T1d:{keyframes:[{opacity:0,transform:`translate(${-e/d}px, ${-a/d}px) scale(${1/d})`,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:1,
transformOrigin:"top left",mixBlendMode:"normal"}],options:c}}};
oqB=function({element:a,Zda:b,T4a:c,hSa:d=2,containment:e=!0,l4c:f,ucf:g,RWc:h,R$e:k,I7e:l=.5,backgroundColor:p,P$b:q=!1,options:r={}}){if(!a)return{};let u;r.duration=(u=r.duration)!=null?u:250;let A;r.easing=(A=r.easing)!=null?A:_.mQb;let E;r.fill=(E=r.fill)!=null?E:"both";const I=r.duration,N=r.easing;b={element:a,Zda:b,T4a:c,group:{},AAb:{},Hra:{},new:{}};e&&(b.group.styles={overflow:"hidden",borderRadius:"20px",backgroundColor:p||window.getComputedStyle(document.body).backgroundColor});const P=
a.getBoundingClientRect(),T=g!=null?g:f==null?void 0:f.getBoundingClientRect();b.ready=X=>{if(X.Zda){var ca;X.group=(ca=X.group)!=null?ca:{};if(ca=_.Zth(X.viewTransitionName,q)){var la=ca.V7c,da=ca.Y7c,ma=ca.Z7c,sa=ca.T7c,Aa=ca.R6c,Ga=ca.U6c,eb=ca.V6c,Va=ca.Sma,qb=ca.fN,sb=ca.YP;ca=X.Zda.getBoundingClientRect();var Nb,Ob=k?k():(Nb=h?h():f)==null?void 0:Nb.getBoundingClientRect();Nb=sb*sa/Va;ma=d===4?1:d===5?Nb:qb*ma/eb;eb=d===3||d===2?Nb:ma;X.group.animation={keyframes:[{transform:`translate(${la}px, ${da}px) scale(${ma}, ${eb})`,
transformOrigin:"top left"},{transform:`translate(${Aa}px, ${Ga}px) scale(1, 1)`,transformOrigin:"top left"}],options:r};d===2&&(X.AAb!=null||(X.AAb={}),la=_.fuh({name:X.viewTransitionName,easing:N,duration:I,W7c:ma,X7c:eb}),X.AAb.animation=la[0],X.AAb.HNb=la.slice(1));T&&Ob&&X.Hra&&X.new&&(la=Ob.left-ca.left-(T.left-P.left),ca=Ob.top-ca.top-(T.top-P.top),Ob={keyframes:[{offset:0,opacity:"0",transform:`translate(${-la}px, ${-ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-
.1,opacity:"0"},{offset:l+.1,opacity:"1"},{offset:1,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},X.Hra.animation={keyframes:[{offset:0,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-.1,opacity:"1"},{offset:l+.1,opacity:"0"},{offset:1,opacity:"0",transform:`translate(${la}px, ${ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},X.new.animation=Ob);
return X}}};return b};qqB=function(a,b){b=pqB(a,b);return b!=null&&b!==0?b:pqB(a,_.Bef)};pqB=function(a,b){switch(a){case 0:case 1:return b==null?void 0:_.wj(b,2);case 2:return b==null?void 0:_.wj(b,3);case 3:return b==null?void 0:_.wj(b,4);case 4:return b==null?void 0:_.wj(b,5);default:_.$a(a,void 0)}};sqB=async function(a,b,c){var d=(0,_.Rf)(),e=d();d=d(1);try{const f=b.map(rqB);d(await e(a.update(f,c)))}finally{e()}};
rqB=function(a){return{contentPluginType:a.contentPluginType,content:a.content,viewerType:a.viewerType,serializedModalityOverride:a.serializedModalityOverride,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,entrypointId:a.entrypointId,replacedEntrypointId:a.replacedEntrypointId,interactionVed:a.interactionVed,contentId:a.contentId,uuid:a.uuid}};
vqB=function(a){return{viewerType:a.viewerType,e9:tqB(a.serializedModalityOverride?(0,_.i8e)(a.serializedModalityOverride):void 0),serializedModalityOverride:a.serializedModalityOverride,cY:a.serializedCloseConfig?(0,_.xef)(a.serializedCloseConfig):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,Oq:null,plugin:null,M4:new AbortController,contentPluginType:a.contentPluginType,content:a.content,entrypointId:a.entrypointId,contentId:a.contentId,replacedEntrypointId:a.replacedEntrypointId,
C6a:0,wja:new uqB,interactionVed:a.interactionVed,Nf:0,WIa:0,tNa:new _.Hq,nFb:!1,Iqa:Promise.resolve(),UX:new _.Hq,entrypoint:null,Vw:null,header:null,Hk:[],sza:!1,uuid:a.uuid,yca:!1}};tqB=function(a){if(lqB())return 1;var b=a!=null?a:wqB,c;a=(c=_.wj(b,1))!=null?c:1;b=_.hh(b,_.hqB,2,_.ih());if(_.HB)return a;c=Math.min(window.innerWidth,window.innerHeight);let d=-1;for(const e of b)b=_.Fe(e,1),c>=b&&b>=d&&(d=b,a=e.getModality());return a};xqB=function(a,b,c){for(;c<a.length;c++)a[c].sza=b};
CqB=function({client:a,MYa:b,Yme:c,ane:d}){const e=a.shellStyleClass,f=a.wja,g=a.plugin,h=document,k=h.body&&_.he(h.body),{node:l,bG:p}=_.ojr?_.ML(yqB):_.ML(q=>{var r=_.aDe&&(g==null?void 0:g.getType())===3;zqB(q);let u;u="<div"+_.Y("PG8i1e ")+_.Z("")+_.W(AqB(q,r)+' role="dialog"')+">";r=BqB(q,r);const A=q.Da();A!==""&&(u+=" <style>"+A+"</style>");u+=r+_.AB(q)+"</div>";q.Ha();return _.z(u)});f.c1b({dispatch:p});l.setAttribute("data-svs","true");if(e)for(const q of e.split(" "))l.classList.add(q);
switch(a.e9){case 2:if(_.ojr){l.classList.add("cnmMUc");l.id="flE2Jf";break}b=b.get();l.style.position="fixed";l.style.top=`${b.oa()}px`;l.style.bottom=`${b.Pa()}px`;l.style[k?"right":"left"]=`${b.Ha()}px`;l.style[k?"left":"right"]="unset";l.style.width=`${b.Aa()}px`;l.classList.add("Ooz8t");_.yWr(b)!==null&&l.classList.add("F6z1Rc");break;case 3:l.style.position="fixed";l.style.display="none";l.style.bottom="0";l.style.left="0";l.style.width="100%";l.style.height="70%";break;case 4:l.style.display=
"none";_.HB?l.classList.add("Yktdff"):l.classList.add("MiFXAd");break;default:l.style.position="fixed",l.style.display="none",l.style.top="0",l.style.left="0",l.style.width="100%",l.style.height="100%"}lqB()&&_.fw&&(l.style[k?"right":"left"]="calc(calc(100% - min(100%, 768px)) / 2)",l.style.width="min(100%, 768px)");if(c){const {node:q,bG:r}=_.ML(_.zZe);f.RA({dispatch:()=>void r({Gg:_.KL(l)})});l.appendChild(q);a.header=q}if(d){const {node:q,bG:r}=_.ML(_.t0e);f.RA({dispatch:()=>void r({Gg:_.KL(l)})});
l.appendChild(q);a.Vw=q}h.body.appendChild(l);if(_.ojr){let q;(q=document.getElementById("uBYdKc"))==null||q.insertAdjacentElement("beforebegin",l);_.Ug(document.body,"flrfCd")}return l};DqB=function(){let a,b=(a=document.body.clientHeight)!=null?a:0;try{const c=window.getComputedStyle(document.body),d=_.kDe(c.paddingTop),e=_.kDe(c.paddingBottom);b-=d+e}catch(c){}return b};
EqB=function(a,b){b=b||a.clientHeight||0;if(a.style.display==="none"||b<=100)b=DqB();a.style.setProperty("--Z9tEad",b>100?`${b}px`:"100dvh")};
OqB=async function(a,b,c,d,e,f,g){var h=(0,_.Rf)(),k=h();h=h(1);try{const N=a.plugin,P=a.Oq,T=a.tNa,X=a.nFb,ca=a.e9;let la=P.clientHeight||0;if(ca===2&&la<=100){const da=e.get();la=Math.max(0,DqB()-da.oa()-da.Pa())}EqB(P,la);if(X)h(await k(T.promise));else{var l=a.viewerType===74;if(ca===2){var p=_.LRb(_.WRb(_.SRb(new _.Bv,127),1),1,{replace:[6,...(l?[]:[7]),10]});a.entrypoint&&a.entrypoint instanceof HTMLElement&&_.XRb(p,a.entrypoint)}else{const da=[2];_.MCe&&da.push(1);_.KCe&&da.push(3);_.LCe&&
da.push(4);p=FqB(_.ORb(_.VRb(_.URb(_.zv(_.SRb(new _.Av,1E3),ca===3?1:2))),a.contentPluginType!==5&&a.contentPluginType!==19&&a.viewerType!==47&&a.viewerType!==73),{getScrollTopRequirement:()=>1,getShouldDisableScrolling:()=>!0,getSwipeToDismissDirections:()=>da})}var q,r;_.KRb(_.wv(_.uv(_.vv(p,[2]),f),(r=N==null?void 0:(q=N.nce)==null?void 0:q.call(N))!=null?r:!0),5);var u=GqB?window.google.zl:void 0,A;ca===2?A=new HqB([{element:P,Ix:"PyLEff",tL:!0}],[{element:P,Ix:"PyLEff",tL:!1}],IqB(a,b)):_.ICe&&
_.suh?A=new JqB(P,IqB(a,b)):_.JCe&&_.suh?A=new KqB(P,IqB(a,b)):A=new LqB(P,IqB(a,b));_.PRb(p,A);!MqB(a)&&d.isAvailable()&&ca===1&&d.enterBasicMode(58);var E=c.open(P,p);T.resolve(E);a.nFb=!0;h(await k(T.promise));var I;u==null||(I=u.cqsv)==null||I.call(u);g();a.Nf>=5&&NqB(P)}}finally{k()}};MqB=function(a){const b=GqB?window.google.zl:void 0;return!(a.C6a===2||a.C6a===4)||!(b==null||!b.qsvo)};PqB=function(a){const b=a.plugin;(a=a.Oq)&&((b==null?0:b.Jad)?b.Jad():a.remove())};
QqB=async function(a,b,c){var d=(0,_.Rf)(),e=d();d=d(1);try{b.at(-1),a.Iqa||(a.Iqa=sqB(c,b,{replace:!1})),d(await e(a.Iqa))}finally{e()}};TqB=function(a,b){const c=a.entrypoint;a=a.contentId;const d=b.at(-1);return d?RqB(d,SqB(d,b))===c?d.contentId&&a&&d.contentId!==a?!1:!0:!1:!1};
UqB=function(a,b){for(let d=b.length-1;d>=0;d--){const {Oq:e}=b[d];let f;var c;if(!(c=(f=e)==null?0:f.contains(a))&&(c=d===0&&b[d].viewerType===74&&e))a:{c=a.closest("[jsowner]");if(!c){c=!1;break a}c=(c=document.getElementById(c.getAttribute("jsowner")))?e.contains(c):!1}if(c)return d}return-1};SqB=function(a,b){a=b.indexOf(a);return a>0?b[a-1]:null};VqB=function(a,b){if(a==null||b==null)return a===b;if(a.length!==b.length)return!1;for(let c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};
RqB=function(a,b){if(a.entrypoint)return a.entrypoint;b=WqB(a.entrypointId,b);a.entrypoint=b;XqB(a);return b};XqB=function(a){let b;!a.entrypoint||(b=a.entrypoint)!=null&&b.querySelector("img, svg")||(a.yca=!0)};WqB=function(a,b){return a?(b=b?b.Oq:document.body)?b.querySelector(`[id="${a}"]`):null:null};YqB=function(a,b){const c=a.entrypoint,d=a.replacedEntrypointId;return c&&c.isConnected?c:d?WqB(d,b):RqB(a,b)};
IqB=function(a,b){const c=b[0],d=SqB(a,b),e=!!d;return{JTb:function(){let f,g;const h=(f=a.plugin)==null?void 0:(g=f.V4a)==null?void 0:g.call(f,e);let k;return{Yxa:(k=h==null?void 0:h.Yxa)!=null?k:YqB(a,d),a6a:h==null?void 0:h.a6a,wba:(h==null?void 0:h.wba)||a.sza||MqB(a),aFa:h==null?void 0:h.aFa,Dic:a.yca}},PSb:function(){var f;let g;const h=(f=a.plugin)==null?void 0:(g=f.s4a)==null?void 0:g.call(f,e);f=h==null?void 0:h.Yxa;f===void 0&&(f=b.length===0?YqB(c,null):YqB(a,d));return{Yxa:f,a6a:h==null?
void 0:h.a6a,wba:(h==null?void 0:h.wba)||a.sza,aFa:h==null?void 0:h.aFa,Dic:a.yca}}}};NqB=function(a){(0,_.vNa)().then(()=>{const b=_.Dma(a);_.aAe(b)})};ZqB=function(){let a;((a=google)==null?0:a.uh)?google.uh("sv"):document.body.style.opacity=""};$qB=function(a){a.ksa!=null||(a.ksa=!1);a.yca!=null||(a.yca=!1);a.viewerType!=null||(a.viewerType=void 0);a.source!=null||(a.source=void 0)};
arB=function(a,b){const c=a.plugin,d=a.Oq;if(c){let e;c==null||(e=c.wdd)==null||e.call(c,a===b);let f;c==null||(f=c.setActive)==null||f.call(c,a===b)}d&&_.Vd(d,"hidden",a!==b)};FqB=function(a,b){a.Ha=b;return a};_.qna=class extends Error{};brB={duration:250,easing:_.mQb};
HqB=class extends _.lQb{constructor(a,b,c){super();this.Aa=a;this.oa=b;this.config=c}async open(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {wba:c}=this.config.JTb();_.GRb(this.Aa,c);c||a(await b(_.HRb(250)))}finally{b()}}async close(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {wba:c}=this.config.PSb();_.GRb(this.oa,c);c||a(await b(_.HRb(250)))}finally{b()}}};crB=function(a){let b;(b=a.Aa)==null||b.remove();a.Aa=void 0};
drB=function(a,b,c=!1){if(!b||c)return a.Aa?a=a.Aa:(a.Aa=document.createElement("div"),a.Aa.style.opacity="0.0000001",a.Aa.style.height="100px",a.Aa.style.width="100px",a.Aa.style.position="fixed",a.Aa.style.top="50%",a.Aa.style.left="50%",a.Aa.style.marginTop="-100px",a.Aa.style.marginLeft="-100px",a.Aa.style.pointerEvents="none",document.body.appendChild(a.Aa),a=a.Aa),a;crB(a);return b};
LqB=class extends _.lQb{constructor(a,b){super();this.overlay=a;this.config=b}async open(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {Yxa:c,wba:d,aFa:e,Dic:f}=this.config.JTb(),g=drB(this,c,f);this.overlay.style.display="block";d||(this.overlay.style.opacity="0",a(await b(_.qRb({token:e!=null?e:_.pQb,before:g,after:this.overlay}).play())));this.overlay.style.opacity="1"}finally{b()}}async close(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {Yxa:c,wba:d,aFa:e,Dic:f}=this.config.PSb(),g=drB(this,c,f);d||
(g.style.opacity="0",a(await b(_.rRb({token:e!=null?e:brB,before:this.overlay,after:g}).play())));(()=>{this.overlay.style.display="none";g.style.opacity="";crB(this)})()}finally{b()}}};frB=_.Sb(_.h8e);grB=_.Sb(_.wef);hrB=[5,19];var KqB=class extends LqB{constructor(a,b){super(a,b);this.overlay=a;this.config=b}async open(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {Yxa:p,wba:q}=this.config.JTb(),r=()=>{this.overlay.style.display="block"};if(q)r();else{var c=drB(this,p).getBoundingClientRect(),d={},e=_.quh(r,{root:d});a(await b(e.updateCallbackDone));var f=document.body.getBoundingClientRect(),g,h=((g=this.overlay.querySelector('[jsname="figiqf"]'))==null?void 0:g.getBoundingClientRect())||f,{U2d:k,T1d:l}=nqB(c,Object.assign({},
h.toJSON(),{left:0}));d.Hra={animation:k};d.new={animation:l}}}finally{b()}}async close(){var a=(0,_.Rf)(),b=a();a=a(1);try{const {Yxa:e,wba:f}=this.config.PSb(),g=drB(this,e),h=()=>{this.overlay.style.display="none";g.style.opacity=""};if(f)h();else{var c=window.getComputedStyle(document.body).backgroundColor,d=_.quh(h,{groups:[{element:this.overlay,T4a:()=>g,group:{styles:{overflow:"hidden",backgroundColor:c,borderRadius:"16px"}},hSa:2,P$b:!0}]});a(await b(d.finished))}}finally{b()}}},jrB=async function(a){const {Yxa:b,
a6a:c,wba:d}=a.config.PSb(),e=drB(a,b);if(d)a.overlay.style.display="none",e.style.opacity="";else{var f={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",fill:"both"},g=(c||a.overlay).getBoundingClientRect(),h={new:{animation:{keyframes:[{offset:0,transform:"scale(1.2)",opacity:"0"},{offset:1,transform:"scale(1)",opacity:"1"}],options:f}}},k=oqB({element:c||a.overlay,Zda:e,l4c:c,RWc:()=>e,containment:!1,hSa:1,P$b:!0,options:f});return new Promise(l=>{a.Ba=_.quh(()=>{a.overlay.style.display="none";
e.style.opacity=""},{URd:!0,root:h,groups:[k],updateCallbackDone:p=>{const q=drB(a,b).getBoundingClientRect(),r=q.width/g.width;p.root.Hra={animation:{keyframes:[{transform:"translate(0px, 0px) scale(1)",transformOrigin:"top left"},{transform:`translate(${q.left-0*r}px, ${q.top-g.top*r}px) scale(${r})`,transformOrigin:"top left"}],options:Object.assign({},f,{id:"close-root-old"})},styles:{zIndex:"1"},HNb:[{keyframes:[{opacity:1},{opacity:0}],options:f}]};a.oa={cHc:a.Ba,FZc:k,VHa:[],vEb:[],xDa:{},
Pj:{}};l()},finished:()=>{irB(a);let p,q;(p=a.oa)==null||(q=p.Mb)==null||q.remove();a.oa=void 0}})})}},lrB=function(a){let b;(b=a.oa)==null||b.cHc.skipTransition();irB(a);let c,d;(c=a.oa)==null||(d=c.Mb)==null||d.remove();a.oa=void 0;krB(a)},mrB=function(a,b){a.oa&&(b(a.oa.xDa),b(a.oa.Pj))},krB=function(a){a.overlay.style.display="block"},irB=function(a){let b;(b=a.oa)==null||b.VHa.forEach(c=>{c.cancel()})},JqB=class extends LqB{constructor(a,b){super(a,b);this.overlay=a;this.config=b;this.swipeToDismiss=
{onStart:async()=>{var c=(0,_.Rf)(),d=c();c=c(1);try{if(c(await d(jrB(this))),this.oa){c(await d(this.oa.cHc.ready));this.oa.VHa=_.juh();var e=`::view-transition-group(${this.oa.FZc.viewTransitionName})`;this.oa.xDa.animation=this.oa.VHa.find(g=>g.effect.pseudoElement===e);this.oa.Pj.animation=this.oa.VHa.find(g=>g.id==="close-root-old");if(!this.oa.xDa.animation)throw lrB(this),Error("fB");if(!this.oa.Pj.animation)throw lrB(this),Error("gB");this.oa.vEb=this.oa.VHa.filter(g=>g!==this.oa.xDa.animation&&
g!==this.oa.Pj.animation);for(const g of this.oa.VHa)g.pause();var f=document.createElement("style");this.oa.Mb=f;document.head.appendChild(f);this.oa.xDa.Uya=_.kuh(f,`html::view-transition-group(${this.oa.FZc.viewTransitionName})`,{});this.oa.Pj.Uya=_.kuh(f,"html::view-transition-old(root)",{});mrB(this,g=>{const h=new DOMMatrix(window.getComputedStyle(document.documentElement,g.animation.effect.pseudoElement).transform);g.Gn=_.buh(h)})}}finally{d()}},onMove:async c=>{if(this.oa&&this.oa.VHa.length){var d=
this.oa.VHa[0].effect.getTiming().duration;d=Math.min(Math.max(d*c.yWithTension/4E3,0),d/3);for(const e of this.oa.vEb)e.currentTime=d;mrB(this,({Uya:e,Gn:f})=>{e.style.setProperty("transform",`${`translate(${c.xWithTension+f.left}px, ${c.yWithTension+f.top}px)`} scale(${f.fN*c.scale}, ${f.YP*c.scale})`,"important")})}},onDismiss:()=>{if(this.oa){mrB(this,({animation:e,Uya:f})=>{var g=e.effect;const h=g.getKeyframes();h[0].transform=f.style.transform;g.setKeyframes(h);g=e.effect.getTiming().duration;
const k=Math.max(this.oa.vEb[0].currentTime,100);e.cancel();document.documentElement.animate([{transform:f.style.transform},{transform:h[1].transform}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:g-k,pseudoElement:e.effect.pseudoElement})});var c,d;(c=this.oa)==null||(d=c.Mb)==null||d.remove();for(const e of this.oa.VHa)e.play()}},onCancel:()=>{if(this.oa){var c=Math.max(this.oa.vEb[0].currentTime,100),d;mrB(this,({animation:g,Uya:h})=>{d=document.documentElement.animate([{transform:h.style.transform},
{transform:""}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:c,pseudoElement:g.effect.pseudoElement})});var e,f;(e=this.oa)==null||(f=e.Mb)==null||f.remove();for(const g of this.oa.vEb)g.currentTime=Math.max(g.currentTime,1),g.reverse();d.finished.then(()=>{lrB(this)})}}}}async open(){var a=(0,_.Rf)(),b=a();a=a(1);try{let c;a(await b((c=this.Ca)==null?void 0:c.finished))}finally{b()}}async beforeOpen(){const {Yxa:a,a6a:b,wba:c}=this.config.JTb();if(c)krB(this);else{var d={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",
fill:"both"},e=drB(this,a).getBoundingClientRect(),f={Hra:{animation:{keyframes:[{offset:0,transform:"scale(1)",opacity:"1"},{offset:1,transform:"scale(1.2)",opacity:"0"}],options:d}}},g=oqB({element:a,Zda:b||this.overlay,l4c:a,RWc:()=>b,containment:!1,hSa:1,options:d});return new Promise(h=>{this.Ca=_.quh(()=>{h();krB(this)},{root:f,groups:[g],updateCallbackDone:k=>{const l=(b||this.overlay).getBoundingClientRect(),p=e.width/l.width;k.root.new={animation:{keyframes:[{transform:`translate(${e.left-
0*p}px, ${e.top-l.top*p}px) scale(${p})`,transformOrigin:"top left"},{transformOrigin:"top left"}],options:d},HNb:[{keyframes:[{opacity:0},{opacity:1}],options:{delay:200,duration:300,fill:"both",easing:"cubic-bezier(.34,.69,.34,1)"}}]}}})})}}async close(){var a=(0,_.Rf)(),b=a();a=a(1);try{this.oa||a(await b(jrB(this))),this.oa&&a(await b(this.oa.cHc.finished))}finally{b()}}};var yqB=function(a){nrB(a);let b;b="<div"+_.Y("")+_.Z("")+_.W(orB(a)+prB())+">";const c=_.AB(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+_.AB(a)+"</div>";a.Ha();return _.z(b)},prB=function(){return' data-st-cnt="ssp"'},orB=function(a){return' jsname="'+_.S("ujKaBc")+'" decode-data-ved="'+_.S("1")+'"'+_.zB(a,{Fb:233502,track:[4,3]}).attributes},qrB=function(){return""},rrB=function(){return""},srB=function(){return!0},trB=function(){return!1},urB=function(a){nrB(a);return _.AB(a)},vrB=function(a){nrB(a);
var b="<div"+_.Y("")+_.Z("")+_.W(orB(a)+prB())+">";const c=_.AB(a);b+=c+_.AB(a)+"</div>";return _.z(b)},nrB=function(a){a.oa(wrB)||a.Aa(wrB,{},urB,vrB,srB,trB,prB(),orB,"",qrB,"",rrB)},wrB="t-ARc0ABBjbSc";var AqB=function(a){return' jsname="'+_.S("ujKaBc")+'" decode-data-ved="'+_.S("1")+'"'+_.zB(a,{Fb:233502,track:[4,3]}).attributes},xrB=function(){return""},yrB=function(){return""},zrB=function(){return!0},ArB=function(){return!1},BrB=function(a,b){zqB(a);return BqB(a,b.Z_c)},CrB=function(a,b){zqB(a);var c=b.Z_c;b="<div"+_.Y("PG8i1e ")+_.Z("")+_.W(AqB(a,c)+' role="dialog"')+">";c=BqB(a,c);b+=c+_.AB(a)+"</div>";return _.z(b)},BqB=function(a,b){var c=_.hA(_.hi().Ua),d=_.hA(_.hi().rL),e=_.hA(_.hi().Yi),
f=_.hA(_.hi().Vp),g=_.hA(_.hi().Dc);a.Ba(".PG8i1e{background:"+_.V(c,"",h=>h.Wc())+";overflow:hidden;position:fixed;transform:translateX(0)}");a.Ba(".PG8i1e.Ooz8t{"+((_.vWd?"border:1px solid "+_.V(c,"",h=>h.Tr())+";border-radius:24px;box-shadow:none;opacity:0.001;transition:transform "+_.V(f,"",h=>_.t(h,49))+" "+_.V(f,"",h=>_.t(h,56))+",opacity "+_.V(f,"",h=>_.t(h,49))+";":"")+(_.lPi&&!_.vWd?"border:1px solid "+_.V(c,"",h=>h.Tr())+";border-radius:"+_.V(e,"",h=>_.NB(h))+";box-shadow:none;":"")+(_.lPi||
_.vWd?"":"border-radius:"+_.V(e,"",h=>_.NB(h))+";box-shadow:"+_.V(d,"",h=>_.t(h,8))+";opacity:0.001;transform:translateX(200px);transition:transform 250ms cubic-bezier(0.05,0.07,0.1,1),opacity 250ms")+"}"));a.Ba(".Ooz8t.F6z1Rc{box-shadow:"+_.V(d,"",h=>_.t(h,6))+"}");a.Ba(".PG8i1e.Ooz8t.PyLEff{opacity:0.999;"+(_.lPi?"":"transform:translateX(0)")+"}");a.Ba(".MiFXAd{"+((_.RD?"background:"+_.V(c,"",h=>h.kW())+";":"")+(_.RD?"":"background:rgba(255,255,255,0.6);")+"display:flex;justify-content:center;align-items:center;backdrop-filter:blur(8px);position:fixed;top:0;left:0;width:100%;height:100%}"));
a.Ba(".QtrPTd{width:80%;height:calc(100% - 150px);top:75px;bottom:75px;left:10%}");a.Ba(".fLi1af{background:"+_.V(c,"",h=>h.Wc())+";border-radius:12px}");a.Ba(".Yktdff{"+((!_.tWd||_.RD?"background:#101218;color:"+_.V(c,"",h=>_.pA(h))+";":"")+(_.tWd&&!_.RD?"background:"+_.V(c,"",h=>h.Wc())+";color:"+_.V(c,"",h=>_.Lo(h))+";":"")+"position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(!_.tWd||_.RD?".Yktdff .VB2c0b{color:"+_.V(c,"",h=>h.d0())+"}":"");a.Ba(".eQVlOe{padding-left:"+(_.V(g,"",h=>_.DA(h))+
";padding-right:"+_.V(g,"",h=>_.DA(h))+"}"));a.Ba(_.gqB?".PG8i1e.Ooz8t.X3bDbe{border:1px solid "+_.V(c,"",h=>h.Tr())+";box-shadow:none;border-radius:24px;margin-top:20px;margin-bottom:20px}":"");c="";b&&_.i5h(a,null)&&(b="<div"+_.Y(_.g5h(a,null)+"HV5Yde ")+_.Z(_.h5h(a,null)+"")+_.W(_.f5h(a,null)+"")+">"+_.l5h(a,null)+"</div>",c+=_.j5h(a,null)?"":b);return c+=_.AB(a)},zqB=function(a){a.oa(DrB)||(a.Aa(DrB,{Z_c:0},BrB,CrB,zrB,ArB,' role="dialog"',AqB,"PG8i1e ",xrB,"",yrB),_.k5h(a))},DrB="t-_7Z7QKitJBk";var FrB=function(a,b,c){const d=new uqB;ErB(d,a,b,c);return d},ErB=function(a,b,c,d){a.mode=0;a.wja.dispatch(b,c,d);a.wja=new GrB(b,c,d)},uqB=class{constructor(){this.mode=1;this.wja=new HrB}c1b(a){this.wja.c1b(a)}RA(a){this.wja.RA(a)}},GrB=class{constructor(a,b,c){this.interactionVed=a;this.Gg=b;this.kE=c}c1b(a){a.dispatch({interactionVed:this.interactionVed,Gg:this.Gg,vTa:!0,kE:this.kE})}RA(a){a.dispatch()}dispatch(){}},HrB=class{constructor(){this.oa=[]}c1b(a){this.Aa=a}RA(a){this.oa.push(a)}dispatch(a,
b,c){let d;(d=this.Aa)==null||d.dispatch({interactionVed:a,Gg:b,vTa:!0,kE:c});this.oa.forEach(e=>void e.dispatch())}};var GqB,wqB,IrB,MrB,LrB,OrB,TrB,QrB,UrB,WrB,ZrB,XrB,YrB,KrB,VrB,NrB,asB,SrB,JrB,RrB,$rB,bsB,PrB;GqB=_.GCe||_.HCe;wqB=_.fDe?_.iqB(_.AM(1)):_.fw?_.AM(2):_.AM(1);IrB=function(a){return a.oa.at(-1)};
MrB=function(a,b,c){const d=SqB(b,a.oa),e=b.e9;_.Ng(c,"KpPeYd",f=>{a.yh(b,f.data)});_.Ng(c,"YS2dOd",f=>{JrB(a,b,2,f);KrB(a,b,2)});_.Ng(c,"gZgazf",f=>{JrB(a,b,1,f);KrB(a,b,1)});if(e===2&&!_.ojr){const f=a.MYa.get(),g=_.es(a).measure(k=>{k.X_a=f.oa();k.MGc=f.Pa()}).Jc(k=>{a.yk(c,k.X_a,k.MGc)}).Gr().build();b.Hk.push(_.me(window,"scroll",g));const h=f.Ec(()=>{g()});b.UX.promise.then(()=>{h()})}if(e===2&&!_.ojr){const f=a.MYa.get(),g=_.es(a).measure(h=>{h.Jqb=f.Ha();h.Kqb=f.Aa();h.MGc=f.Pa();h.W_a=c.clientHeight}).Jc(h=>
{a.handleResize(c,h.Jqb,h.Kqb,h.MGc,h.W_a)}).Gr().build();b.Hk.push(_.me(window,"resize",g))}b.UX.promise.then(()=>{b.WIa=0;b.M4.abort();try{var f;let g;(f=b.plugin)==null||(g=f.k_b)==null||g.call(f)}catch(g){}PqB(b);for(const g of b.Hk)_.qn(g);if(e===1||_.HB&&e===4)f=RqB(b,d),!f||b.Oq&&!b.Oq.contains(document.activeElement)||LrB(f);(0,_.vNa)().then(()=>{_.bAe();(0,_.lh.dirty)()})});_.Ng(c,"ucVTnf",()=>{const f=b.plugin,g=b.cY,h=a.oa,k=RqB(b,d),l=qqB(4,g)===1;let p;const q=(p=SqB(b,h))==null?void 0:
p.Oq;l&&q&&(q.style.display="");let r;(f==null?0:(r=f.UEb)==null?0:r.call(f,k))||!k||b.yca||(k.style.opacity="0");let u;if(f==null?0:f.Pmb)u=_.Pg(c,"pU3PWb",()=>{let A;return void(f==null?void 0:(A=f.Pmb)==null?void 0:A.call(f,k))});_.Pg(c,"s2IYHc",()=>{u&&_.Og(u);let A;(f==null?0:(A=f.v_b)==null?0:A.call(f,k))||!k||b.yca||(k.style.opacity="");l&&q&&(q.style.display="none")})})};
LrB=function(a,b,c=!1){if(c){c=b.ZC;c||(b.ZC=new _.LWb(a),_.JWb(b.ZC),c=b.ZC);let d;(d=_.IWb(c,0))==null||d.focus({preventScroll:!0})}else b=document.activeElement,a.contains(b)&&a!==b||(a.tabIndex===0?a.focus({preventScroll:!0}):(b=_.yWb(a).find(d=>!d.hasAttribute("data-os-fs")))?b.focus({preventScroll:!0}):(a.tabIndex=-1,a.focus({preventScroll:!0})))};
OrB=async function(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const e=IrB(a);if(e){e.C6a=3;var d=kqB(a.Qe);ErB(e.wja,d,d);document.dispatchEvent(new CustomEvent("viewerOpened"));b(await c(NrB(a,e)))}}finally{c()}};
TrB=async function(a,b,c=!1){var d=(0,_.Rf)(),e=d();d=d(1);try{_.$Ce||(c=!1);const g=a.oa;let h=b.length<g.length,k=b.length>g.length;const l=Math.min(b.length,g.length);let p=l;for(let q=0;q<l;q++)if(g[q].uuid!==b[q].uuid){h=k=!0;p=q;break}xqB(g,c,p);if(h&&!k){var f=g[p];let q,r,u;const A=(u=(q=f.plugin)==null?void 0:(r=q.t4a)==null?void 0:r.call(q))!=null?u:PrB(a,f);a.Qe.logEvent({hf:new _.Jh(A,26)})}h&&QrB(a,p);if(k){const q=b.slice(p).map(vqB);for(let r=q.length-1;r>=0;r--)if(q[r].uuid===a.Aa){d(await e(RrB(a,
1)));return}g.push(...q);xqB(g,c,p)}a.Aa=-1;(k||h)&&d(await e(SrB(a,k)));a.Ba&&(a.Ba.resolve(),a.Ba=null)}finally{e()}};
QrB=function(a,b,c=!1){b=a.oa.splice(b,Infinity);var d;const e=(d=IrB(a))==null?void 0:d.Oq;e&&(e.style.display="");if(b.length!==0){a.Aa=b[0].uuid;if(a.oa.length!==0||c)c&&document.dispatchEvent(new CustomEvent("viewerReplaced"));else if(document.dispatchEvent(new CustomEvent("viewerClosed")),_.ojr){var f;(f=document.getElementById("flE2Jf"))==null||f.remove();_.Ug(document.body,"MCtCI")}for(const g of b)c=g.Oq,d=g.nFb,f=g.UX,arB(g,null),c&&d?((d=g.ZC)&&_.KWb(d),g.Oq&&!g.Oq.contains(document.activeElement)||
document.activeElement.blur(),a.If.close(c)):f.resolve()}};UrB=function(a,b){return sqB(a.wi,a.oa,b)};WrB=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const e=VrB(a,b);xqB(a.oa,!0,b);QrB(a,b,!0);c(await d(a.wi.go(-e)))}finally{d()}};
ZrB=async function(a,b,c){var d=(0,_.Rf)(),e=d();d=d(1);try{const f=b.Ay,g=b.entrypoint,h=b.interactionVed,k=b.kE,l=b.oG,p=b.cY,q=a.oa;for(const I of q)I.WIa=I.Nf;const r=_.x3h(g),u=_.KL(g);let A;const E={viewerType:b.viewerType,e9:tqB(b.M3),serializedModalityOverride:b.M3?frB(b.M3):void 0,cY:p,serializedCloseConfig:p?grB(p):void 0,shellStyleClass:b.shellStyleClass,Oq:null,plugin:f,M4:new AbortController,contentPluginType:f.getType(),content:((A=f.serialize)==null?void 0:A.call(f))||new Uint8Array(0),
entrypointId:r,contentId:b.contentId,replacedEntrypointId:void 0,wja:FrB(h!=null?h:u,u,k),interactionVed:h!=null?h:u,C6a:2,Nf:3,WIa:7,tNa:new _.Hq,nFb:!1,Iqa:null,UX:new _.Hq,entrypoint:g,Vw:null,header:null,Hk:[],sza:c,uuid:Math.random(),yca:b.yca};XqB(E);q.push(E);q.length===1&&document.dispatchEvent(new CustomEvent("viewerOpened"));try{g&&!_.ICe&&(g.animate({transform:["scale(1)","scale(.98)","scale(1)"]},{duration:65}),c||d(await e((0,_.vNa)()))),d(await e(XrB(a,{client:E,oG:l}))),(0,_.wNa)(()=>
void YrB(a))}catch(I){d()}return E.Oq}finally{e()}};XrB=function(a,{client:b,oG:c}){let d;c==null||c.Gs((d=b.viewerType)!=null?d:0);return _.b4h({client:b,oG:c,Dwb:a.Dwb})};YrB=async function(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const f=a.oa;if(!(f.length<2||f.at(-1).Nf<7)){var d=f.at(-2);if(!d.M4.signal.aborted&&d.Nf<7)try{d.C6a=1;var e=d.wja;e.mode!==1&&(e.mode=1,e.wja=new HrB);d.WIa=7;b(await c(XrB(a,{client:d})))}catch(g){b()}}}finally{c()}};
KrB=async function(a,b,c,{Ptb:d=!1,rPc:e}={}){var f=(0,_.Rf)(),g=f();f=f(1);try{if(d||b===IrB(a)){var h=d?0:$rB(a,b,c),k=VrB(a,h);d?xqB(a.oa,!0,h):b.sza=!1;e&&(a.Ba=e);var l=a.oa.slice(h);QrB(a,h);var p=RrB(a,k);f(await g(OrB(a)));f(await g(p));if(e){const q=l.map(r=>r.UX.promise);f(await g(Promise.all([e.promise,...q])))}if(!IrB(a)){const q=document.head.querySelector('link[rel="canonical"]');q&&document.head.removeChild(q)}}}finally{g()}};
VrB=function(a,b){let c=0;for(;b<a.oa.length;b++)a.oa[b].Iqa&&c++;return c};NrB=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const e=b.Oq;e&&(e.style.display="");b.WIa=7;c(await d(XrB(a,{client:b,oG:new _.s5p})));(0,_.wNa)(()=>void YrB(a))}finally{d()}};asB=function(a,b){return(b=RqB(b,SqB(b,a.oa)))?_.KL(b):kqB(a.Qe)};
SrB=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{const k=IrB(a);if(k){_.VCe&&k.interactionVed&&_.Ep(a.Qe.oa(),new _.Jh(k.interactionVed)).log();if(b){k.C6a=4;var e=k.wja;var f=a.Qe;if(erB)var g=erB;else{var h=_.Ge(_.um("iGkMSe"));g=erB=_.Y3h(f,251479,h)}ErB(e,g,asB(a,k));document.dispatchEvent(new CustomEvent("viewerOpened"))}else k.C6a=5,ErB(k.wja,kqB(a.Qe),asB(a,k));c(await d(NrB(a,k)))}}finally{d()}};
JrB=function(a,b,c,d){let e=null;if(c===1){let f,g;e=((f=b.plugin)==null?void 0:(g=f.ZV)==null?void 0:g.call(f))||null}else if(c===2){let f,g;e=((f=b.plugin)==null?void 0:(g=f.LTa)==null?void 0:g.call(f))||null}e||(e=d.targetElement.hb());_.Fp(a.Qe.oa(),e,3).log()};RrB=async function(a,b){var c=(0,_.Rf)(),d=c();c=c(1);try{b>0&&(c(await d(a.wi.go(-b))),_.Ug(document.body,"nOJPYb"))}finally{d()}};$rB=function(a,b,c){b=qqB(c,b.cY);switch(b){case 1:return a.oa.length-1;case 2:return 0;default:return _.$a(b)}};
bsB=function(a,b){let c,d,e;const f=(e=(c=b.plugin)==null?void 0:(d=c.t4a)==null?void 0:d.call(c))!=null?e:PrB(a,b);(0,_.Df)(()=>{a.Qe.logEvent({hf:new _.Jh(f,21)})})};PrB=function(a,b){if(b.Yeb)return b.Yeb;const c=_.NHb(b.Oq);return b.Yeb=_.Y3h(a.Qe,3593,c)};
_.csB=class extends _.ho{static Ta(){return{service:{overlay:_.qv,history:_.Qsr,Vf:_.Pu,logging:_.Ku,qL:_.GWr}}}constructor(a){super();this.Aa=-1;this.Ba=null;this.Dwb={isActive:c=>c===IrB(this),RNc:c=>!hrB.includes(c.contentPluginType),SPc:c=>{const d=CqB({client:c,MYa:this.MYa,Yme:!0,ane:!0,root:SqB(c,this.oa)});MrB(this,c,d);SqB(c,this.oa)&&d.classList.add("L3JeZd");_.X3h(d);return c.Oq=d},UPc:c=>{var d=c.plugin;d=hrB.includes(c.contentPluginType)?d.H8d():CqB({client:c,MYa:this.MYa,root:SqB(c,
this.oa)});MrB(this,c,d);SqB(c,this.oa)&&d.classList.add("L3JeZd");_.X3h(d);return c.Oq=d},z4c:c=>_.aqB(c.contentPluginType,this.Yp()),Joc:async(c,d)=>{var e=(0,_.Rf)(),f=e();e=e(1);try{c.plugin=e(await f(d.ix(c.content,_.aqB)))}finally{f()}},gUc:async c=>{var d=(0,_.Rf)(),e=d();d=d(1);try{const f=c.plugin,g=c.M4;let h;d(await e((h=f.fetch)==null?void 0:h.call(f,{signal:g.signal})))}finally{e()}},rz:c=>{const d=c.plugin,e=c.Oq,f=c.M4,g=c.Vw,h=c.header,k=c.wja;let l={gC:!1,iA:!1};if(d.yPc){let p,q;
const r=(q=(p=d.C$e)==null?void 0:p.call(d))!=null?q:new Map;d.yPc(this.Yp(),_.aqB,r)}d.rz!=null&&(l=d.rz({Pj:e,signal:f.signal,RA:p=>void k.RA(p)}),l.gC&&(g==null||g.remove(),h==null||h.remove()));l.iA&&c.nFb&&NqB(e);return l.iA},render:async c=>{var d=(0,_.Rf)(),e=d();d=d(1);try{const f=c.plugin,g=c.Oq,h=c.M4,k=c.Vw,l=c.header,p=c.wja;k==null||k.remove();l==null||l.remove();f.render!=null&&d(await e(f.render({Pj:g,signal:h.signal,RA:q=>void p.RA(q)})));if(_.DCe&&!g.querySelector('[jsname="OXxrqc"]')){const q=
document.body.querySelector('[jsname="yloBKd"]');(q==null?0:q.firstElementChild)&&g.appendChild(q.firstElementChild.cloneNode(!0))}(0,_.vNa)().then(()=>{_.Gq()})}finally{e()}},Yvc:async(c,d)=>{var e=(0,_.Rf)(),f=e();e=e(1);try{e(await f(OqB(c,this.oa,this.If,this.Fm,this.MYa,this.onDismiss(c),d)));const l=this.oa,p=l.indexOf(c);if(p!==-1){var g=IrB(this);for(d=0;d<p;d++){const q=l[d],r=q.Oq;r&&(r.style.display="none");arB(q,g)}var h=c.plugin,k=c.Oq;arB(c,g);LrB(k,c,!("function"==typeof _.E6h&&h instanceof
_.E6h)&&_.HB)}}finally{f()}},Uxc:c=>{QqB(c,this.oa,this.wi)}};this.If=a.service.overlay;this.wi=a.service.history;this.Fm=a.service.Vf;this.Qe=a.service.logging;this.MYa=a.service.qL;if(GqB){var b;let c,d;(b=window.google)==null||(c=b.zl)==null||(d=c.qsvd)==null||d.call(c)}this.isRtl=document.body&&_.he(document.body);a=this.wi.get();b=a.Iqa||a.url||[];this.oa=b.map(vqB);OrB(this).catch(()=>{});a.url&&(this.wi.update([],{replace:!0}),a.url.length>0&&this.wi.update(b,{replace:!1}));(a.Iqa||a.url)&&
ZqB();this.wi.addListener((c,d)=>{TrB(this,c,d).catch(()=>{})});document.addEventListener("viewerGuestClose",()=>{QrB(this,0);UrB(this,{replace:!1}).catch(()=>{})});_.Ng(document.body,"gZgazf",this.RKa,this)}Nl(){var a=this.wi;if(_.Gsr())var b=_.lDe.Jf();else{var {Iqa:c,url:d}=a.get();a=(b=c==null?void 0:c.at(-1))!=null?b:d==null?void 0:d.at(-1);b=new _.Xt(_.lDe.Jf());a?(b.pathname=`/searchviewer/${a.viewerType}`,b.searchParams.set("svid",_.Jsr(a,void 0,!0)),b.searchParams.delete("q"),b.searchParams.delete("udm"),
b.oa.delete("sv"),b=b.toString()):b=null}return b}Ilc(){var a;{const {Iqa:d,url:e}=this.wi.get(),f=(a=d==null?void 0:d.at(-1))!=null?a:e==null?void 0:e.at(-1);f?a=_.Isr(f,void 0,_.Gsr()):(_.Gsr(),a=null)}let b,c;return{content:(b=a==null?void 0:_.Pb(a.getContent()))!=null?b:new Uint8Array(0),contentPluginType:(c=a==null?void 0:a.getContentPluginType())!=null?c:null}}async prefetch(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const d=b(await c(mqB(a,this)));b(await c(Promise.all(d.map(async e=>{let f;return await ((f=
e.prefetch)==null?void 0:f.call(e))}))))}finally{c()}}async showViewerLite(a){var b=(0,_.Rf)(),c=b();b=b(1);try{const d=_.aqB(a.contentPluginType,this.Yp());let e;const f=b(await c(d));if(a.cLb){const g=_.B3h(a.entrypoint);if(!g)throw Error("eB`"+a.entrypoint);const h=b(await c(f.ix(a.Csa,_.aqB,{index:_.I3h(g,a.entrypoint),count:g.u5()}))),k=b(await c(_.aqB(3,this.Yp())));e=b(await c(k.getInstance({index:_.I3h(g,a.entrypoint),s6a:h,jN:g})))}else e=b(await c(f.ix(a.Csa,_.aqB)));b(await c(this.showViewer({Ay:e,
bY:a.bY,entrypoint:a.entrypoint,interactionVed:a.interactionVed,oG:void 0,kE:a.kE,ksa:a.ksa,viewerType:a.viewerType,M3:a.M3,shellStyleClass:a.shellStyleClass,cY:a.cY,source:a.source,contentId:a.contentId,yca:a.yca})))}finally{c()}}async showViewer(a){var b=(0,_.Rf)(),c=b();b=b(1);try{let d,e;if(GqB&&((d=window.google)==null?0:(e=d.zl)==null?0:e.qsvoc))return window.google.zl.qsvoc--,Promise.reject(new _.qna("search-viewer: quick viewer was closed"));a.bY!=null&&_.N6h(a.bY);let f;a.oG||(a.oG=_.t5p((f=
a.entrypoint.getAttribute("data-ep-type"))!=null?f:"",a.bY));$qB(a);const g=a.entrypoint,h=a.ksa,k=this.oa;this.Aa=-1;if(TqB(a,k)){let q,r;return Promise.resolve((r=(q=IrB(this))==null?void 0:q.Oq)!=null?r:null)}const l=UqB(g,k),p=h?Math.max(0,l):l+1;if(p<k.length){let q;const r=_.quh(async()=>{var u=(0,_.Rf)(),A=u();u=u(1);try{const E=h?k[p].entrypointId:void 0;u(await A(WrB(this,p)));q=ZrB(this,a,!0);const I=IrB(this);I.replacedEntrypointId=E;u(await A(I.tNa.promise))}finally{A()}},{root:{group:{styles:{animationDuration:"150ms"}}}});
b(await c(r.updateCallbackDone));return q}return ZrB(this,a,!1)}finally{c()}}RKa(a){a=a.data;if(typeof a!=="boolean"){var b=a.rPc;if(a.Ptb)this.oa.length===0?b==null||b.resolve():KrB(this,this.oa[0],0,a).catch(c=>{b&&b.reject(c)});else if(b){const c=IrB(this);c?KrB(this,c,0,a).catch(d=>{b.reject(d)}):b.resolve()}}}HTa(){const a=IrB(this);let b="";try{if(a==null?0:a.Oq)for(const f of a.Oq.querySelectorAll("[data-sv-ctx]"))b+=" "+(f.textContent||"");let c,d;const e=(a==null?void 0:(c=a.plugin)==null?
void 0:(d=c.HTa)==null?void 0:d.call(c))||new Map;e.has("prompt_text")||(b=b+" "+(e.get("prompt_text")||""));e.set("prompt_text",b);return e}catch(c){}return null}yh(a,{content:b,entrypoint:c}){if(!a.M4.signal.aborted&&a===IrB(this)){var d=!1;c&&c!==a.entrypoint&&(d=!0,a.entrypoint=c,a.entrypointId=_.x3h(c),XqB(a));VqB(a.content,b)||(d=!0,a.content=b);d&&a.Iqa&&UrB(this,{replace:!0})}}yk(a,b,c){a.style.top=`${b}px`;a.style.bottom=`${c}px`}handleResize(a,b,c,d,e){a.style[this.isRtl?"right":"left"]=
`${b}px`;a.style.width=`${c}px`;a.style.bottom=`${d}px`;_.uWd&&EqB(a,e)}onDismiss(a){return({UX:b,eventType:c})=>{if(!this.oa.includes(a))return a.UX.resolve(b),!0;if(a!==IrB(this))return!1;a.UX.resolve(b);a:switch(c){case 2:b=3;break a;case 0:b=4;break a;default:b=0}KrB(this,a,b).catch(()=>{});bsB(this,a);return!0}}};_.Zf(_.t1a,_.csB);

_.x();
_.jwq=_.y("qCgt4c",[_.t1a]);
_.v("qCgt4c");
_.as(_.jwq,class extends _.Wr{static Ta(){return{service:{y9:_.csB}}}constructor(a){super();this.Zg=a.service.y9}});
_.x();
_.v("QFOGlf");
_.nzr=new _.Uf(_.q3a);
_.x();
_.Vfq=_.y("YlQIHe",[_.q3a]);
_.v("YlQIHe");
_.as(_.Vfq,class extends _.Wr{static Ta(){return{service:{copy:_.nzr}}}constructor(a){super();let b;a.service.copy.setLoggingElement(((b=this.qb("W2GRoe"))==null?void 0:b.el())||void 0)}});
_.x();
_.XWo=_.y("I9y8sd",[]);
_.v("I9y8sd");
var YWo=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},ZWo=function(){return google.lfm&&google.lfm.some(a=>a.ie())},$Wo=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},aXo=function(a,b,c,d,{logError:e}){d=_.Ze(d);b=`${b}-${c}-${_.ona(d)}`;const f=a.get(b),g=_.af(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.ona(d)}`;(d=_.af(d,"ck"))&&
(h=`${h}.ck=${d}`);e(Error("Xq`"+JSON.stringify({type:c,Qgf:h,gef:f,Ldf:g})))}a.set(b,g)}},cXo=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;bXo.push(a)}},dXo={name:"umods"},eXo=!!(_.Bi[19]>>20&1),fXo=!!(_.Bi[19]>>21&1),gXo=!!(_.Bi[19]>>22&1),hXo=!!(_.Bi[19]>>23&1),iXo=!!(_.Bi[19]>>24&1),jXo=!!(_.Bi[19]>>25&1),kXo=!!(_.Bi[19]>>26&1);var lXo=["google.com","youtube.com","ampproject.org","adtrafficquality.google",(new URL(location.href)).host];var bXo=[],mXo=[],nXo=class extends _.Wr{static Ta(){return{}}constructor(){super();this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Yn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of bXo)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of mXo)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.bf(b,{level:0,Bf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});fXo&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.km.uA)()}`,"")}sample(a,b){((a.Vgf?Math.random():this.Ca)<(a.sampleRate||0)||eXo)&&b()}};nXo.prototype.$wa$rT3LBf=function(){return this.Ba};
cXo({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of lXo)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("Yq"),b)}},toggle:hXo});
cXo({name:"hp",run:function({logError:a}){if(!YWo()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=$Wo(d);if(e){const f=d;(0,_.Yn)(()=>{e===$Wo(f)&&a(Error("Zq"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:gXo});
cXo({name:"sp",run:function({logError:a}){var b;if(b=!YWo())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none")&&!ZWo();if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("$q"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:gXo});
cXo({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("ar"))},toggle:iXo});
cXo({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.tg("s",dXo);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&aXo(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&aXo(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&aXo(d,c,"comburl",g,{logError:a})}}}},toggle:kXo});
var oXo={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:jXo};if(oXo.toggle){var pXo;oXo.sampleRate=(pXo=oXo.sampleRate)!=null?pXo:1;mXo.push(oXo)}_.as(_.XWo,nXo);
_.x();
});
// Google Inc.
