loaded_h_0(function(_){var window=this;
var l9h=class{constructor(a,b=_.nAd()){this.TX=a;this.oa=b;this.oa.Lc("uvpet","src".toString());this.oa.Lc("uvpvoct",Math.round(a).toString());this.oa.Lc("uvpbtod","0")}zsa(a){_.oAd(this.oa,a)}Ws(a){this.oa.Lc("vtyp",a.toString())}BFa(){this.oa.start();const a=this.oa.oa.getStartTime()+_.uh;this.oa.qy("uvpovct",Math.round(this.TX-a));_.qAd(this.oa)}WNa(){var a=this.oa;_.pAd(a);_.Ko(a,"uvpcot")}R9a(){_.rAd(this.oa)}YNa(){_.sAd(this.oa)}XNa(){_.tAd(this.oa)}AFa(){_.uAd(this.oa)}EWa(){this.oa.log();
return Promise.resolve()}};_.m9h=class extends _.wAd{constructor(a){const b=_.nAd();super(new l9h(a,b),b)}};
var s6h=class{constructor(a=_.nAd()){this.oa=a;this.oa.Lc("uvpet","sa".toString());this.oa.qy("uvpcot",0);this.oa.qy("uvpovct",0);this.oa.Lc("uvpbtod","0")}zsa(a){_.oAd(this.oa,a)}Ws(a){this.oa.Lc("vtyp",a.toString())}BFa(){this.oa.start();_.qAd(this.oa)}WNa(){}R9a(){_.rAd(this.oa)}YNa(){_.sAd(this.oa)}XNa(){_.tAd(this.oa)}AFa(){_.uAd(this.oa)}EWa(){this.oa.log();return Promise.resolve()}};_.t6h=class extends _.wAd{constructor(){const a=_.nAd();super(new s6h(a),a)}};
var J$p;_.I$p=function(a,b){switch(a){case "sa":return new _.t6h;case "o":return new _.H$p;default:return b?new _.m9h(b):new _.H$p}};
J$p=class{constructor(a=_.nAd()){this.oa=a;this.oa.Lc("uvpet","o".toString());this.oa.qy("uvpovct",0);this.oa.Lc("uvpbtod","0")}zsa(a){_.oAd(this.oa,a)}Ws(a){this.oa.Lc("vtyp",a.toString())}BFa(){this.oa.start();_.qAd(this.oa)}WNa(){var a=this.oa;_.pAd(a);_.Ko(a,"uvpcot")}R9a(){_.rAd(this.oa)}YNa(){_.sAd(this.oa)}XNa(){_.tAd(this.oa)}AFa(){_.uAd(this.oa)}EWa(){this.oa.log();return Promise.resolve()}};_.H$p=class extends _.wAd{constructor(){const a=_.nAd();super(new J$p(a),a)}};
_.wUa[257]=[0,_.G,-1];
_.PL=class extends _.m{constructor(a){super(a)}};_.PL.prototype.ob="N8ijL";_.SL=function(a){return _.zj(a,2)};_.eUe=_.YDe?"26px":"46px";
_.kSc=_.Mb(273,_.gp,_.LTa);_.ip[273]=_.NTa;
_.Tz=function(a,b){a=a.Xwa()?a.clone():a;return(0,_.hUa)(a,new _.kDa((0,_.iUa)(b)))};
var iSc;iSc=function(a,b){if(!a)return[];const c=String(b);return a.split(";").map(d=>d.trim()).filter(d=>d).map(d=>d.split(":").map(e=>e.trim())).filter(d=>d.length===2).filter(d=>{d=d[1].split(",").map(e=>e.trim());return d.includes(c)||d.includes("62")}).map(d=>d[0])};_.jSc=class{jUa(a,b,c){a=iSc(a,b);a=a.concat(c);return[...(new Set(a))].sort()}};
_.fSc=function(a){if(!a.Da())return null;if(!a.Ca()||!a.La())return a.Aa();const b=a.Aa();try{const c=new RegExp(a.Ba(),"g");return b.replace(c,a.Ha())}catch(c){return b}};
var gSc;gSc=function(a){return a.La()?a.Ha()?a.Aa()+"-"+a.Da():a.Aa():"en-US"};_.hSc=class{Xge(a){a.Ha();const b=_.De(a.Ba()),c=a.Ca();return a.Da()?c.substring(b,b+_.De(a.Aa())):c.substring(b)}trim(a){return a.trim()}toLowerCase(a){return a.Ca()?a.Ba().toLocaleLowerCase(gSc(a)):""}toUpperCase(a){return a.Ca()?a.Ba().toLocaleUpperCase(gSc(a)):""}replace(a){return _.fSc(a)}startsWith(a,b){return a.startsWith(b)}endsWith(a,b){return a.endsWith(b)}toInt(a){return(a=a.match(/^\d+/))?Number(a[0]):0}};
var YRc=[0,_.$k,-1,_.cl,_.$k];_.ZRc=[0,_.C,_.F,_.XRc,_.G,1,_.D,_.F,[0,_.G,_.D,_.G,_.F,_.XRc,[0,_.D,_.C,-1],_.hl,[0,_.$k,-2,_.C,_.$k,_.G,_.C],_.G,_.C,_.G],_.C,_.kl,[0,3,_.F,[0,_.tl]],_.ml,-1,_.G,_.F,YRc,_.C,_.G,_.C,_.G,YRc,[0,_.C,-1],_.F,[0,[5,6,7],_.G,_.D,1,_.D,_.El,_.IQc,_.Bl,-1,_.ml,_.G,[0,_.D,-1,_.G]],_.C,_.ml,_.G,[0,_.C,_.kl,_.F,[0,_.hl,_.D]]];
_.zRc={};
_.$Rc=class extends _.m{constructor(a){super(a)}getQuery(){return _.t(this,1)}setQuery(a){return _.Zg(this,1,a)}wi(){return _.mh(this,1)}};_.aSc=class extends _.m{constructor(a){super(a,11)}getType(){return _.zj(this,1,1)}setType(a){return _.Sh(this,1,a)}Ue(){return _.Gk(this,1)}Se(){return _.Xh(this,1)}getUrl(){return _.t(this,2)}Qc(){return _.mh(this,2)}Cd(){return _.wj(this,2)}UFa(a){return _.Zg(this,8,a)}tP(){return _.n(this,_.$Rc,3)}Bqa(){return _.Wi(this,_.$Rc,3)}};_.aSc.prototype.ob="N1YWaf";
_.bSc={};_.cSc=[0,_.D,1,_.C,-1,1,[0,[0,_.C]],_.ms,_.C,[0,_.D,_.zl,_.D],_.D,1,_.C,_.D,-4,1,_.D,-3,1,_.C,_.ZRc,1,_.D,-1,2,_.D,1,_.C,_.G,_.ml,_.G,-1,_.ml,_.D,_.QRc];_.dSc=[-11,_.zRc,_.G,_.D,_.cSc,[-26,_.bSc,_.G,_.D,-4,_.G,_.D,-2,_.G,_.ml,_.F,[0,_.D,-3,_.ml],_.D,_.$k,_.C,_.D,_.G,_.C,[0,_.$k,_.Rk,_.$k,-1,_.C,_.zl,-1,[0,_.ml,-1,_.zl,-1],_.C,_.Jl,_.G,_.nl,_.C],1,_.C,_.ml,_.C,[0,_.C,_.ml,-1,_.zl,_.C,_.ml,_.$k,_.G]],_.C,1,_.C,_.D,-2];
_.In[50052456]=_.dSc;
_.vy=function(a){return _.bq(a)};_.Hdc=function(a){if(a!==""&&!(a instanceof _.EVa))throw Error("dg`"+_.RFa(a));a=_.xka(a?a.getContent():"",{justification:"from Soy SanitizedTrustedResourceUri object"});return _.eh(a)};_.wy=function(a){if(!(a===""||a instanceof _.DVa||a instanceof _.Re))throw Error("eg`"+_.RFa(a));if(a instanceof _.Re)return _.bh(_.kc(a?a.toString():""));a=a?a.getContent():"";return _.bh(_.kc(a))};
_.xy=function(a){return a instanceof _.Yg?(a=(a=_.eta(a))?_.ec(a).toString():"",(0,_.Sp)(a)):a==null?a:null};_.yy=function(a){return a instanceof _.ah?(a=(a=_.ch(a))?_.mc(a):"",(0,_.Vp)(a)):a==null?a:null};_.zy=function(a){return a instanceof _.dh?(a=(a=_.fh(a))?_.jc(a).toString():"",(0,_.Wp)(a)):a==null?a:null};_.Idc=function(a){if(a==null)return a;if(a instanceof _.Qa)return _.lb(a);throw Error("fg`"+a);};_.Jdc=function(a){return _.xca(a)};
_.Mz=function(a){let b;var c=a.getUrl();a=_.Jj(a,2,_.lh());var d;c=(d=c)!=null?d:"";if(a.length==0){{d=c;const f=d.search(":");f<0||_.Xl.v9b.isValid(d)?d=!0:(d=d.substring(0,f).toLowerCase(),d=/^[a-z][a-z\d+.-]*$/.test(d)&&d!=="javascript")}d||(c="about:invalid#zSoyz")}a:{d=c.toLowerCase();for(e of vRc)if(e.isValid(d)){var e=!0;break a}for(const f of a)if(d.startsWith(wRc[f].replace("_","-")+":")){e=!0;break a}e=!1}e||(c="about:invalid#zSoyz");c=_.bh(_.pc(c));return(b=_.yy(c))!=null?b:null};
_.Nz=function(a,b){return _.Zg(a,1,b)};_.xRc=function(a,b){return _.sk(a,2,b)};_.Oz=function(a,b){return _.tk(a,2,b)};_.Pz=class extends _.m{constructor(a){super(a)}getUrl(){return _.$g(this,1)}Qc(){return _.mh(this,1)}Cd(){return _.wj(this,1)}};var vRc=[_.Xl.wIc,_.Xl.sMb,_.Xl.tMb,_.Xl.GJc,_.Xl.FIc,_.Xl.v9b],wRc=Object.keys({TEL:0,E9b:1,Ind:2,i5e:3,Psd:4,prd:5,wFe:6,EYe:7,evd:8,Ypd:20,FJe:9,GJe:27,zFe:10,EJe:11,Zpd:19,aqd:22,SFe:12,xre:13,Atd:14,i8b:15,rtd:16,ypd:17,Due:18,tve:35,JQe:21,RFe:23,lve:24,I4e:25,YOUTUBE:26,FILE:28,CONTENT:29,QGe:30,UFe:31,TFe:32,VFe:33,XFe:34});
_.tRc=function(a){const b=new _.Sx(1);_.Ux(b,1);_.Tx(b,1);a=b.format(a);a==0&&/^\-/.test(a)&&(a=a.substr(1));return a};_.uRc=class{};
_.sRc=class{get(){return 0}};
_.HQc=function(a){return _.He(a,3)};
var wSc=class{merge(a,b){return _.Tz(a,b)}},xSc=class{format(a,b){const c=new _.Sx(4,a.zs());!_.HQc(a)&&b&&(_.Tx(c,0),_.Ux(c,0));return c.format(_.ze(_.$s(a))+_.HQc(a)/1E9)}};var ySc=class{constructor(){this.oa=new xSc}};var zSc=class{};var ASc=class{getUrl(a){if(a.getType()===2&&a.tP()){let b;a=(b=a.tP())==null?void 0:b.getQuery();if(a!=="")return _.Jn(new _.Re("/search"),"q",a).toString()}throw Error("fh");}};var BSc=class{};_.Zz=_.un(()=>{const a=new _.rSc;a.add("gws.common.api.jslayout.services.UniqueIdService",new _.Sz);a.add("gws.common.api.jslayout.services.DebugLevelService",new _.sRc);a.add("gws.common.api.jslayout.services.DoubleFormatterService",new _.uRc);a.add("gws.common.api.jslayout.services.StringService",new _.hSc);a.add("gws.common.api.knowledge.sharing.ShareExperimentMarksService",new _.jSc);a.add("com.google.template.jslayout.library.SafeTypeService",new zSc);a.add("com.google.gws.common.api.knowledge.link.SearchUrlGeneratorService",
new ASc);a.add("com.google.gws.common.api.sds.services.SdsDateTimeFormatterService",new BSc);a.add("com.google.gws.common.api.sds.services.SdsLogService",new wSc);a.add("gws.common.api.jslayout.services.MoneyFormatterService",new ySc);return a});_.CSc=_.un(()=>new _.tSc(document,!0));
_.vSe=function(a){return a.closest("[data-ved]")};_.IL=function(a){return _.Ie(_.vSe(a))};_.JL=function(a,b,c){const d=new _.sUa;b!==void 0||c?(b=_.qp(new _.xp,b?0:1),c&&_.vp(b,c),_.mUa(d,a,b)):_.mUa(d,a);a=_.pUa(d);_.nUa(d);return{hC:d,ved:a}};_.wSe=function(){return new _.Yz(document,(0,_.Zz)(),(0,_.CSc)())};
var lae;_.mae=function(a){var b=new lae;return _.Sh(b,1,a)};lae=class extends _.m{constructor(a){super(a)}};var nae=[0,_.G];_.oae=_.Mb(923,_.gp,lae);_.ip[923]=nae;_.ep[923]=nae;
_.pv=function(a,b,c){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0;this.z=c!==void 0?c:0};_.pv.prototype.clone=function(){return new _.pv(this.x,this.y,this.z)};_.pv.prototype.toArray=function(){return[this.x,this.y,this.z]};
var AOb;_.BOb=function(a){a=_.kJa(a);const b=AOb();return a&&b?(a=new b(a),new _.Nd(a.m41,a.m42)):new _.Nd(0,0)};_.COb=function(a,b,c){_.Um(a,"transform","translate3d("+b+"px,"+c+"px,0px)")};AOb=_.un(function(){return _.ea.WebKitCSSMatrix!==void 0?_.ea.WebKitCSSMatrix:_.ea.MSCSSMatrix!==void 0?_.ea.MSCSSMatrix:_.ea.CSSMatrix!==void 0?_.ea.CSSMatrix:null});
var w6h,x6h,y6h;_.u6h=function(a){if(_.wDe)a.style.paddingTop="46px",a.style.paddingBottom="72px",a.style.boxSizing="border-box";else if(_.cEe||_.dEe){let b;try{const c=_.kEe==null?void 0:_.kEe.If();if(!c||c==="")return;b=new _.Re(c);const d=_.jEe(_.Ln(b,"padb")||""),e=_.jEe(_.Ln(b,"padt")||"");_.cEe&&d>0&&(a.style.paddingBottom=`${d}px`);_.dEe&&e>0&&(a.style.paddingTop=`${e}px`)}catch(c){}a.style.boxSizing="border-box"}else _.xDe&&(a.style.paddingBottom="108px",a.style.boxSizing="border-box")};
_.v6h=function(a,b,c){const {ved:d,hC:e}=_.JL(b);_.Gp(_.Cp(a.oa(),e),new _.Ph(c,3)).log();return d};w6h=function(a){if(_.C5h.has(a))return _.C5h.get(a);const b={jec:0,Oj:null,z1b:!1,ywb:null,eUc:null};_.C5h.set(a,b);return b};x6h=function(a,b,c){return b>a.NIa||c<_.C5h.get(a).jec};y6h=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{const e=b.jec;c(await d(b.ywb));const f=a.client,g=a.Jwb;if(x6h(f,7,e))return!1;if(f.Mf<7){const h=g.render(f);f.Mf=7;c(await d(h))}return!0}finally{d()}};
_.z6h=async function(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const f=a.client,g=a.Jwb,h=a.rG,k=w6h(f),l=++k.jec;h==null||h.BFa();if(!x6h(f,1,l)&&(f.Mf<1&&g.iOc(f)&&(k.Oj=g.jQc(f),f.Mf=1,g.isActive(f)&&(g.lyc(f),g.pwc(f,()=>void(h==null?void 0:h.WNa())))),!x6h(f,2,l))){if(f.Mf<2){const p=g.S4c(f);k.eUc=p;f.Mf=2}if(!x6h(f,3,l)){if(f.Mf<3){const p=b(await c(k.eUc));if(x6h(f,3,l))return;f.Mf<3&&(b(await c(g.Woc(f,p))),f.Mf=3)}if(!x6h(f,4,l)&&(f.Mf<4&&(k.Oj!=null||(k.Oj=g.lQc(f)),f.Mf=4),!x6h(f,5,l))){if(f.Mf<
5)try{k.z1b=g.qz(f),f.Mf=5}catch(p){}k.z1b&&(h==null||h.R9a());if(!x6h(f,6,l)){h==null||h.YNa();f.Mf<6&&(k.ywb=g.xUc(f),f.Mf=6);var d=k.ywb,e=y6h(a,k);b(await c(_.D5h));b(await c(_.D5h));b(await c(_.D5h));g.isActive(f)&&(g.lyc(f),b(await c(g.pwc(f,()=>void(h==null?void 0:h.WNa())))),(0,_.ph.dirty)());try{b(await c(d)),h==null||h.XNa()}catch(p){b()}try{b(await c(e))&&((0,_.ph.dirty)(),k.z1b||(h==null||h.R9a(),k.z1b=!0),h==null||h.zsa(k.Oj),h==null||h.AFa(),h==null||h.EWa(k.Oj))}catch(p){b()}}}}}}finally{c()}};var C6h=function(a){A6h(a);return B6h()},D6h=function(a){A6h(a);a="<g"+_.X("DQYJue ")+_.Y("")+_.W("")+">";const b=B6h();return _.z(a+(b+"</g>"))},B6h=function(){return"<circle"+_.X("BwkTpd ")+_.Y("")+_.W("")+"></circle><rect"+_.X("BrqvYc ")+_.Y("")+_.W("")+"></rect><circle"+_.X("BwkTpd ")+_.Y("")+_.W("")+"></circle>"},A6h=function(a){a.oa(E6h)||a.Aa(E6h,{},C6h,D6h)},E6h="t-ctlhNWCKvSA";var H6h=function(a){F6h(a);return G6h(a)},I6h=function(a){F6h(a);var b="<style"+_.X("")+_.Y("")+_.W("")+">";a=G6h(a);return _.z(b+(a+"</style>"))},G6h=function(a){var b=_.aA(_.mi().Ua);a.Ba(".hjLOAe.zE1rf{background-color:"+_.V(b,"",c=>c.Uc())+"}");a.Ba(".hjLOAe .BwkTpd,.hjLOAe .BrqvYc{fill:"+_.V(b,"",c=>_.Oo(c))+"}");return""},F6h=function(a){a.oa(J6h)||a.Aa(J6h,{},H6h,I6h)},J6h="t-knD9z4X3SUg";var M6h=function(a){K6h(a);return L6h(a)},N6h=function(a){K6h(a);var b="<style"+_.X("")+_.Y("")+_.W("")+">";a=L6h(a);return _.z(b+(a+"</style>"))},L6h=function(a){var b=_.aA(_.mi().Ua);a.Ba(".pZuFRb .lywBc{background-color:"+_.V(b,"",c=>c.gW())+";border-radius:12px}");a.Ba(".pZuFRb .BwkTpd,.pZuFRb .BrqvYc{fill:"+_.V(b,"",c=>c.b0())+"}");return""},K6h=function(a){a.oa(O6h)||a.Aa(O6h,{},M6h,N6h)},O6h="t-tt-mQ-0ZWBk";var R6h=function(a){P6h(a);return Q6h(a)},S6h=function(a){P6h(a);var b="<style"+_.X("")+_.Y("")+_.W("")+">";a=Q6h(a);return _.z(b+(a+"</style>"))},Q6h=function(a){var b=_.aA(_.mi().Dc),c=_.aA(_.mi().Sp);a.Ba(".zE1rf{width:100%;display:flex;flex-direction:row;justify-content:center;align-items:center;transition:opacity "+_.V(c,"",d=>_.t(d,50))+" "+_.V(c,"",d=>_.t(d,56))+";pointer-events:none}");a.Ba(".lywBc{display:flex;flex-direction:row;align-items:center;justify-content:center;padding:"+_.V(b,"",
d=>_.AA(d))+";"+(_.YDe?"margin:"+_.V(b,"",d=>_.Yy(d))+";":"")+(_.YDe?"":"margin:"+_.V(b,"",d=>_.zA(d)))+"}");a.Ba(".qn3Gnf.zE1rf{opacity:0}");a.Ba(".ofHTLc{width:70px;height:6px;margin:0 -6px}");a.Ba(".DQYJue{opacity:0}");a.Ba(".BwkTpd{cx:3px;cy:3px;r:3px;transform-box:fill-box;transform-origin:50% 50%}");a.Ba(".BrqvYc{x:3px;y:0px;width:1px;height:6px;transform-box:fill-box;transform-origin:0 50%;transform:scaleX(0)}");a.Ba(".lt9SHd{clip:rect(1px,1px,1px,1px);height:1px;overflow:hidden;position:absolute;white-space:nowrap;width:1px;user-select:none;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;z-index:-1000}");
return""},P6h=function(a){a.oa(T6h)||a.Aa(T6h,{},R6h,S6h)},T6h="t-dJvRb7h7eeI";var U6h=function(a,b){var c="";_.V(b,0,d=>_.SL(d))==0||_.V(b,0,d=>_.SL(d));_.V(b,0,d=>_.SL(d));return c+=' jscontroller="'+_.S("tlZhkd")+'" jsdata="'+_.S(_.wB("N8ijL",b))+'" jsaction="'+_.S("KF9ZEf:TQY5Y;kr34C:rMTFzd;X5vnkc:Figvhe;CZRWp:WO6jrc")+'"'+_.yB(a,{Fb:275360,track:[3]}).attributes},V6h=function(a,b){a=_.V(b,0,c=>_.SL(c))==0||_.V(b,0,c=>_.SL(c))==1;b=_.V(b,0,c=>_.SL(c))==2;return(a?"pZuFRb ":"")+(b?"hjLOAe ":"")},W6h=function(a,b){_.V(b,0,c=>_.SL(c))==0||_.V(b,0,c=>_.SL(c));_.V(b,0,c=>_.SL(c));
return""},X6h=function(a,b){_.V(b,0,c=>_.SL(c))==0||_.V(b,0,c=>_.SL(c));_.V(b,0,c=>_.SL(c));return!0},Y6h=function(a,b){_.V(b,0,c=>_.SL(c))==0||_.V(b,0,c=>_.SL(c));_.V(b,0,c=>_.SL(c));return!1},a7h=function(a,b){Z6h(a);return $6h(a,b.options)},b7h=function(a,b){Z6h(a);var c=b.options;b="";_.V(c,0,d=>_.SL(d))==0||_.V(c,0,d=>_.SL(d));_.V(c,0,d=>_.SL(d));b+="<div"+_.X(V6h(a,c)+"zE1rf ")+_.Y(W6h(a,c)+"")+_.W(U6h(a,c)+"")+">";c=$6h(a,c);b+=c+_.zB(a)+"</div>";return _.z(b)},$6h=function(a,b){var c=_.V(b,
0,d=>_.SL(d))==0||_.V(b,0,d=>_.SL(d))==1;b=_.V(b,0,d=>_.SL(d))==2;return Q6h(a)+(c?L6h(a):"")+(b?G6h(a):"")+"<div"+_.X("lywBc ")+_.Y("")+_.W("")+"><div"+_.X("lt9SHd ")+_.Y("")+_.W(' aria-live="polite" role="status"')+"></div><svg"+_.X("ofHTLc ")+_.Y("scale:"+_.S(_.Uz()=="rtl"?"-1 1":"1")+";")+_.W(' aria-hidden="true" viewBox="0 0 70 6" xmlns="http://www.w3.org/2000/svg"')+">"+_.uB(0,6).reduce(function(d){var e="<g"+_.X("DQYJue ")+_.Y("")+_.W("")+">"+B6h()+"</g>";return d+e},"")+"</svg></div>"+_.zB(a)},
Z6h=function(a){a.oa(c7h)||(a.Aa(c7h,{options:0},a7h,b7h,X6h,Y6h,"",U6h,"zE1rf ",V6h,"",W6h),A6h(a),F6h(a),K6h(a),P6h(a))},c7h="t-E8dzlKj0hyg";var g7h,h7h,k7h,l7h,m7h;_.d7h=function(a,b,c){a="";_.aA(_.mi().Dc);return a+=' jsname="'+_.S("Qzjw6d")+'"'+(b?"":' aria-hidden="'+_.S("true")+'"')+(c!=""?' data-ved="'+_.S(c)+'"':"")};_.e7h=function(){_.aA(_.mi().Dc);return""};_.f7h=function(){_.aA(_.mi().Dc);return""};g7h=function(){_.aA(_.mi().Dc);return!0};h7h=function(){_.aA(_.mi().Dc);return!1};k7h=function(a){_.i7h(a);return _.j7h()};
l7h=function(a,b){_.i7h(a);var c=b.tOc,d=b.hua;b="";_.aA(_.mi().Dc);b+="<div"+_.X(_.e7h(a,c,d)+"Fp3I9 ")+_.Y(_.f7h(a,c,d)+"")+_.W(_.d7h(a,c,d)+"")+">";a=_.j7h();return _.z(b+(a+"</div>"))};_.j7h=function(){_.aA(_.mi().Dc);return"<div"+_.X("hwRvZe ")+_.Y("")+_.W("")+"></div>"};_.i7h=function(a){a.oa(m7h)||a.Aa(m7h,{tOc:0,hua:1},k7h,l7h,g7h,h7h,"",_.d7h,"Fp3I9 ",_.e7h,"",_.f7h)};m7h="t-eMRMwSHMfWM";var p7h=function(a){n7h(a);return o7h(a)},q7h=function(a){n7h(a);var b="<style"+_.X("")+_.Y("")+_.W("")+">";a=o7h(a);return _.z(b+(a+"</style>"))},o7h=function(a){a.Ba(".Fp3I9{width:100%;height:100%;flex-shrink:0;transform:translate3d(0,0,0);"+(_.eL?"":"position:absolute;top:0;scroll-snap-align:center;scroll-snap-stop:always")+"}");a.Ba(".hwRvZe{width:100%;height:100%}");a.Ba(_.eL?".Fp3I9{position:absolute}":"");return""},n7h=function(a){a.oa(r7h)||a.Aa(r7h,{},p7h,q7h)},r7h="t-dF5rznWAUns";var s7h=function(a){return _.yB(a,{Fb:237020,track:[3],href:_.iC(a,_.U("t-eMRMwSHMfWM",{tOc:!0,hua:""}))}).attributes+_.d7h(a,!0,"")},v7h=function(a){t7h(a);return u7h(a)},w7h=function(a){t7h(a);var b="";if(g7h(a,!0,"")){var c="<div"+_.X(""+_.e7h(a,!0,"")+"Fp3I9 ")+_.Y(""+_.f7h(a,!0,""))+_.W(s7h(a)+"")+">";const d=u7h(a);c+=d+_.zB(a)+"</div>";b+=h7h(a,!0,"")?"":c}return _.z(b)},u7h=function(a){var b=_.j7h()+_.zB(a);return h7h(a,!0,"")?"":b},t7h=function(a){a.oa(x7h)||(a.Aa(x7h,{},v7h,w7h),_.i7h(a))},
x7h="t-GKxe-poKnxo";var A7h=function(a){y7h(a);return z7h(a)},B7h=function(a){y7h(a);var b="<style"+_.X("")+_.Y("")+_.W("")+">";a=z7h(a);return _.z(b+(a+"</style>"))},z7h=function(a){var b=_.aA(_.mi().Ua);a.Ba(".HV5Yde{width:100%;height:100%;position:absolute;top:0;left:0;background-color:"+(_.V(b,"",c=>c.Uc())+";scrollbar-width:none;"+(_.eL?"":"overflow:hidden;overflow-x:scroll;scroll-snap-type:x mandatory;overscroll-behavior:none")+"}"));a.Ba(".cnmMUc .HV5Yde{position:relative}");a.Ba(".HV5Yde::-webkit-scrollbar{display:none}");
a.Ba(".pbZ4je{width:100%;height:100%;position:absolute;top:0;visibility:hidden}");a.Ba(".MPaS6{position:fixed;bottom:0;left:0;z-index:1}");return""},y7h=function(a){a.oa(C7h)||a.Aa(C7h,{},A7h,B7h)},C7h="t-Vs2sBFvBIdA";var K7h,L7h,M7h;_.D7h=function(a,b){var c="",d=_.aA(_.mi().Dc);b==null&&new _.PL;return c+=' jsname="'+_.S("lHGsle")+'" data-gap="'+_.S(_.V(d,"",e=>_.AA(e)))+'"'+_.yB(a,{Fb:237019,track:[3]}).attributes};_.E7h=function(a,b){_.aA(_.mi().Dc);b==null&&new _.PL;return""};_.F7h=function(a,b){_.aA(_.mi().Dc);b==null&&new _.PL;return""};_.G7h=function(a,b){_.aA(_.mi().Dc);b==null&&new _.PL;return!0};_.H7h=function(a,b){_.aA(_.mi().Dc);b==null&&new _.PL;return!1};
K7h=function(a,b){_.I7h(a);return _.J7h(a,b.Hra)};L7h=function(a,b){_.I7h(a);var c=b.Hra;b="";_.aA(_.mi().Dc);c==null&&new _.PL;b+="<div"+_.X(_.E7h(a,c)+"HV5Yde ")+_.Y(_.F7h(a,c)+"")+_.W(_.D7h(a,c)+"")+">";c=_.J7h(a,c);b+=c+_.zB(a)+"</div>";return _.z(b)};
_.J7h=function(a,b){_.aA(_.mi().Dc);b=b==null?new _.PL:b;var c=z7h(a)+o7h(a);if(_.$De&&g7h(a,!0,"")){var d="<div"+_.X(""+_.e7h(a,!0,"")+"Fp3I9 ")+_.Y(""+_.f7h(a,!0,""))+_.W(s7h(a)+"")+">"+u7h(a)+"</div>";c+=h7h(a,!0,"")?"":d}_.V(b,!1,e=>_.B(e,1))&&X6h(a,b)&&(d="<div"+_.X("MPaS6 "+V6h(a,b)+"zE1rf ")+_.Y(W6h(a,b)+"")+_.W(U6h(a,b)+"")+">"+$6h(a,b)+"</div>",c+=Y6h(a,b)?"":d);return c+=_.zB(a)};
_.I7h=function(a){a.oa(M7h)||(a.Aa(M7h,{Hra:0},K7h,L7h,_.G7h,_.H7h,"",_.D7h,"HV5Yde ",_.E7h,"",_.F7h),n7h(a),t7h(a),y7h(a),Z6h(a))};M7h="t-prAKbxAZKMw";
var H5h=function(a){return a?a.height:0},I5h=function(a){return a?(a.left?a.left.height:0)-(a.right?a.right.height:0):0},J5h=function(a){return a?a.count:0};var K5h,O5h,P5h,S5h,M5h,N5h;_.L5h=function(a){this.Ca=a||K5h;this.Aa=this.Ba=this.oa=null};K5h=function(a,b){return String(a)<String(b)?-1:String(a)>String(b)?1:0};O5h=function(a,b){const c=I5h(b);return c>1?(I5h(b.left)<0&&M5h(a,b.left),N5h(a,b)):c<-1?(I5h(b.right)>0&&N5h(a,b.right),M5h(a,b)):b};
P5h=function(a,b,c){const d=a.Ca(b,c.value);let e=!1;d>0?c.right?e=P5h(a,b,c.right):(c.right=new Q5h(b,c),e=!0,c==a.Aa&&(a.Aa=c.right)):d<0&&(c.left?e=P5h(a,b,c.left):(c.left=new Q5h(b,c),e=!0,c==a.Ba&&(a.Ba=c.left)));e&&(c.count++,c.height=Math.max(H5h(c.left),H5h(c.right))+1,O5h(a,c));return e};_.L5h.prototype.add=function(a){return this.oa?P5h(this,a,this.oa):(this.Aa=this.Ba=this.oa=new Q5h(a),!0)};
var R5h=function(a,b,c){if(!c)return{value:null,root:null};var d=a.Ca(c.value,b);if(d>0)b=R5h(a,b,c.left),c.left=b.root,b=b.value;else if(d<0)b=R5h(a,b,c.right),c.right=b.root,b=b.value;else if(b=c.value,c.left&&c.right){b=c.value;let e=c.right;S5h(a,function(f){return f.left?e=f.left:null},c.right);c.value=e.value;d=R5h(a,e.value,c.right);c.right=d.root}else{d=c.left?c.left:c.right;if(!d)return a.Aa==c&&(a.Aa=c.parent),a.Ba==c&&(a.Ba=c.parent),{value:b,root:null};a.Aa==c&&(a.Aa=d);a.Ba==c&&(a.Ba=
d);d.parent=c.parent;c=d}c.count=J5h(c.left)+J5h(c.right)+1;c.height=Math.max(H5h(c.left),H5h(c.right))+1;return{root:O5h(a,c),value:b}};_.aa=_.L5h.prototype;_.aa.remove=function(a){a=R5h(this,a,this.oa);this.oa=a.root;return a.value};_.aa.clear=function(){this.Aa=this.Ba=this.oa=null};_.aa.contains=function(a){let b=!1;S5h(this,function(c){let d=null;const e=this.Ca(c.value,a);e>0?d=c.left:e<0?d=c.right:b=!0;return d});return b};
_.aa.indexOf=function(a){let b=-1,c=0;S5h(this,function(d){const e=this.Ca(d.value,a);if(e>0)return d.left;d.left&&(c+=d.left.count);if(e<0)return c++,d.right;b=c;return null});return b};_.aa.wj=function(){return this.oa?this.oa.count:0};_.aa.getHeight=function(){return this.oa?this.oa.height:0};_.aa.sF=function(){const a=[];_.T5h(this,function(b){a.push(b)});return a};
_.T5h=function(a,b){if(a.oa){a=a.Ba;for(var c=a.left?a.left:a;a!=null;)if(a.left!=null&&a.left!=c&&a.right!=c)a=a.left;else{if(a.right!=c&&b(a.value))break;const d=a;a=a.right!=null&&a.right!=c?a.right:a.parent;c=d}}};S5h=function(a,b,c){for(c=c?c:a.oa;c&&c!=null;)c=b.call(a,c)};
M5h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.right,b.right.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.right,b.right.parent=b.parent):(a.oa=b.right,a.oa.parent=null);a=b.right;b.right=b.right.left;b.right!=null&&(b.right.parent=b);a.left=b;b.parent=a;a.count=b.count;b.count-=(a.right?a.right.count:0)+1;U5h(b);U5h(a);return a};
N5h=function(a,b){b.parent&&b.parent.left==b?(b.parent.left=b.left,b.left.parent=b.parent):b.parent&&b.parent.right==b?(b.parent.right=b.left,b.left.parent=b.parent):(a.oa=b.left,a.oa.parent=null);a=b.left;b.left=b.left.right;b.left!=null&&(b.left.parent=b);a.right=b;b.parent=a;a.count=b.count;b.count-=(a.left?a.left.count:0)+1;U5h(b);U5h(a);return a};_.L5h.prototype.copy=function(a){const b=new _.L5h(this.Ca);if(!this.oa)return b;a=this.oa.copy(null,this.Ca,a);b.oa=a.root;b.Ba=a.q4c;b.Aa=a.bcd;return b};
var Q5h=function(a,b){this.value=a;this.parent=b?b:null;this.count=1;this.right=this.left=null;this.height=1},U5h=function(a){a.height=Math.max(a.left?a.left.height:0,a.right?a.right.height:0)+1};Q5h.prototype.copy=function(a,b,c){var d=c?c(this.value):this.value;a=new Q5h(d,a);a.count=this.count;a.height=this.height;let e=d=a;this.left&&(d=this.left.copy(a,b,c),a.left=d.root,d=d.q4c);this.right&&(b=this.right.copy(a,b,c),a.right=b.root,e=b.bcd);return{root:a,q4c:d,bcd:e}};
var W5h,$5h,a6h;_.V5h=function(a){if(a=a.id)return a};W5h=function(a,b){for(const c of a)if(c.nodeType===Node.ELEMENT_NODE){c.matches('[data-sve]:not([data-nv="1"])')&&b(c);for(const d of c.querySelectorAll('[data-sve]:not([data-nv="1"])'))b(d)}};_.X5h=function(a){return a.closest("[data-viewer-group]")};_.Z5h=function(a){var b=a.getAttribute("data-ssid");return b&&b.length>0?new _.Y5h(void 0,_.V5h(a)||"",b):(b=_.X5h(a))?new _.Y5h(b,_.V5h(a)||""):null};
$5h=function(a,b,c){c=c||a.oa;const d=c.left?c.left.count:0;return b<d?$5h(a,b,c.left):b==d?c:$5h(a,b-d-1,c.right)};a6h=function(a,b){return b<0||b>=a.wj()?null:$5h(a,b).value};_.b6h=class extends _.m{constructor(a){super(a)}zUa(){return _.t(this,1)}};_.c6h=[0,_.D,-1,_.C];var d6h=_.Tb(_.c6h);var e6h;e6h=function(a,b){for(const c of b)W5h(c.removedNodes,d=>{a.oa.remove(d)}),W5h(c.addedNodes,d=>{a.group&&_.X5h(d)!==a.group||a.oa.add(d)})};_.f6h=function(a,b){return a.oa.indexOf(b)};
_.Y5h=class{constructor(a,b,c){this.group=a;this.Ca=b;this.Ba=new MutationObserver(g=>{e6h(this,g)});this.oa=new _.L5h(_.MIa);let d,e;this.streamId=(e=(d=a==null?void 0:a.getAttribute("data-id"))!=null?d:c)!=null?e:"";let f;this.Aa=(f=a==null?void 0:a.getAttribute("data-cid"))!=null?f:this.streamId;if(a)this.Ba.observe(a,{subtree:!0,childList:!0,attributes:!1}),W5h(a.childNodes,g=>{_.X5h(g)===this.group&&this.oa.add(g)});else if(!this.scan(b))throw Error("io`"+this.streamId);}scan(a){if(this.group)return 0;
this.oa.clear();let b=!1;const c=document.documentElement.querySelectorAll(`[data-ssid="${this.streamId}"]`);W5h(c,d=>{d.getAttribute("data-ssid")===this.streamId&&(this.oa.add(d),a&&_.V5h(d)===a&&(b=!0))});if(a&&!b)throw Error("jo`"+a);return this.oa.wj()}getType(){return 1}pMd(a){const b=this.Hhb(a),c={};let d;c.k=(d=b.getAttribute("data-k"))!=null?d:a;this.Aa&&(c.id=this.Aa);this.streamId&&(c.vid=this.streamId);(a=_.V5h(b))&&(c.vhid=a);return c}serialize(a){var b=new _.b6h;b=_.Zg(b,1,this.streamId);
a=_.V5h(this.Hhb(a));a=_.Zg(b,2,a);a=_.Uh(a,3,this.group===void 0);return d6h(a)}async sxb(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{const e=a6h(this.oa,a);if(!e)throw Error("ko`"+a);try{let f;const g=_.osa((f=this.group)!=null?f:e),h=c(await d(g.getController(e)));return c(await d(h.Nca({source:b,count:this.u5(),index:a})))}catch(f){throw c(),Error("lo`"+a+"`"+this.streamId+"`"+(e==null?void 0:e.id)+"`"+(e==null?void 0:e.isConnected)+"`"+f);}}finally{d()}}Hhb(a){return a6h(this.oa,a)}BTb(){let a=0;
_.T5h(this.oa,b=>{if(_.V5h(b)===this.Ca)return!0;a++;return!1});this.u5();return a}u5(){return this.oa.wj()}D9c(){return this.oa.Ba.value}dispose(){this.Ba.disconnect()}};
var pvh,qvh,rvh,svh,tvh,uvh,xvh,zvh,Avh,Bvh,wvh,Fvh,Evh,Jvh,Ivh,Kvh,Lvh,Dvh;pvh=function(a){let b;a=Number((b=a.trim().match(/^(\d+|\d+\.\d+)px$/))==null?void 0:b[1]);return isNaN(a)?null:a};qvh=function(a){return`linear(${a.map(([b,c])=>`${b} ${100*c}%`).join(",")})`};rvh=function(a,b){return b.map(([c,d])=>[(1/(c*(1-a)+a)-1/a)/(1-1/a),d])};svh=function(a,b,c){return(1-a)*(1-a)*(1-a)*0+3*(1-a)*(1-a)*a*b+3*(1-a)*a*a*c+a*a*a};
tvh=function(a){const b=Number(a.split("%")[0])/100;if(isNaN(b))throw Error("Sn`"+a);return b};
uvh=function(a,b){a=a.match(/linear\((.*)\)/i);const c=(a?a[1].split(",").map(e=>e.trim()):["0","1"]).map(e=>{e=e.split(" ");const f=Number(e[0]),g=[[f]];e.length>=2&&g[0].push(tvh(e[1]));e.length>=3&&g.push([f,tvh(e[2])]);return g}).flatMap(e=>e);c[0][1]=0;c[c.length-1][1]=1;for(let e=0;e<c.length;e++)if(c[e].length===1){var d=e-1;a=c.findIndex((g,h)=>h>e&&g[1]!==void 0);const f=(c[a][1]-c[d][1])/(a-d);d=c[d][1];for(let g=e;g<a;g++)d+=f,c[g][1]=d}return c.map(([e,f],g)=>{const h=[[e,f]];var k=c[g+
1];if(!k)return h;var l=k[1]-f;g=Math.ceil(l*b/8.3333333);l/=g;k=(k[0]-e)/g;for(let p=0;p<g-1;p++)f+=l,e+=k,h.push([e,f]);return h}).flatMap(e=>e)};
xvh=function(a="root",b=1,c=!1){const d=[];if(b===0)return d;var e=_.vvh(a,c);if(!e)return d;c=e.p8c;const f=e.s8c,g=e.t8c,h=e.n8c,k=e.m7c,l=e.p7c,p=e.q7c,q=e.Pma;var r=e.XP;const u=e.animation,A=e.keyframes,E=e.duration,I=e.effect;e=e.hN*(b===4?1:b===5?h/q:g/p);r=b===3||b===2?r*h/q:e;a!=="sb"&&(f+h<0||l+q<0)&&u.cancel();const N=[{transform:`translate(${c}px, ${f}px) scale(${e}, ${r})`,easing:A[0].easing,transformOrigin:"top left"},{transform:`translate(${k}px, ${l}px) scale(1, 1)`,easing:A[1].easing,
transformOrigin:"top left"}];d.push(()=>{I.setKeyframes(N)});b===2&&d.push(...wvh({name:a,easing:A[0].easing,duration:E,q8c:e,r8c:r}));return d};
_.vvh=function(a,b=!1){if(!navigator.userAgent.includes(" Chrome/137.")){var c=`::view-transition-group(${a})`;if(a=document.getAnimations().find(r=>{let u;return((u=r.effect)==null?void 0:u.pseudoElement)===c})){var d=a.effect,e=d.getKeyframes(),f=a.effect.getTiming().duration;if(e[1].transform==="none"){a.currentTime=f;var g=window.getComputedStyle(document.documentElement,c);var h=new DOMMatrix(g.transform);var k=pvh(g.width);g=pvh(g.height);a.currentTime=0}else h=new DOMMatrix(e[1].transform),
k=pvh(e[1].width),g=pvh(e[1].height);if(k!==null&&g!==null){var l=pvh(e[0].width),p=pvh(e[0].height);if(l!==null&&p!==null){var q=new DOMMatrix(e[0].transform);q=_.yvh(q);b&&(q=zvh(q,l,p,c));return{p8c:q.left,s8c:q.top,t8c:l,n8c:p,m7c:h.e,p7c:h.f,q7c:k,Pma:g,hN:q.hN,XP:q.XP,animation:a,keyframes:e,duration:f,effect:d}}}}}};_.yvh=function(a){return{left:a.e,top:a.f,hN:a.a,XP:a.d}};
zvh=function(a,b,c,d){try{const e=window.getComputedStyle(document.documentElement,d).transformOrigin,{r4c:f,Cid:g}=Avh(Object.assign({},{transformOrigin:e,width:b,height:c},a));if(isNaN(g)||isNaN(f))return a;a.left+=f;a.top+=g}catch(e){}return a};Avh=function({transformOrigin:a,width:b,height:c,hN:d,XP:e}){a=Bvh({transformOrigin:a,height:c,width:b});return a===null?{r4c:0,Cid:0}:{r4c:a.s4c*(1-d),Cid:a.Did*(1-e)}};
Bvh=function({transformOrigin:a,height:b,width:c}){const d=a.match(/(-?\d+\.?\d*)px (-?\d+\.?\d*)px/);if(d){const [,e,f]=d;return{s4c:Number(e),Did:Number(f)}}if(a=a.match(/(-?\d+\.?\d*)% (-?\d+\.?\d*)%/)){const [,e,f]=a;return{s4c:c*Number(e)/100,Did:b*Number(f)/100}}return null};wvh=function(a){return _.Cvh(a).map(({keyframes:b,options:c})=>()=>{try{document.documentElement.animate(b,c)}catch(d){d.details={src:"spa-vt-csa",kf:JSON.stringify(b),o:JSON.stringify(c)},d.O5e=2}})};
_.Cvh=function({name:a,easing:b,duration:c,q8c:d,r8c:e,transformOrigin:f="top left"}){const g=[];if(e===1)return[];const h=`::view-transition-image-pair(${a})`;var k=b;if(e===1)var l=k;else{b=Number(c);isNaN(b)&&(b=500);k=k.replace(/\n/g,"").replace(/\s*,\s*/g,",").replace(/\(\s*/g,"(").replace(/\s*\)/g,")").trim();if(k.startsWith("linear("))l=uvh(k,b);else{b:{var p=Dvh[k.trim().toLowerCase()];if(p)l=p;else{try{var q=k.match(/cubic-bezier\s*\(\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)\s*\)/i);
if(q){l=q.slice(1).map(Number);break b}}catch(r){}l=Dvh.linear}}q=2*Math.round(b/8.3333333);b=[];for(k=0;k<=q;k++)p=k/q,b.push([svh(p,l[1],l[3]),svh(p,l[0],l[2])]);l=b}l=rvh(e,l);l=qvh(l)}c={duration:c,easing:l};g.push({keyframes:[{transformOrigin:f,transform:`scale(1, ${d/e})`},{transformOrigin:f,transform:"scale(1, 1)"}],options:Object.assign({},c,{pseudoElement:h})});a=`::view-transition-group(${a})`;f=window.getComputedStyle(document.documentElement,a).borderRadius;(f=pvh(f))&&g.push({keyframes:[{borderRadius:`${f/
d}px / ${f/e}px`},{borderRadius:`${f}px`}],options:Object.assign({},c,{pseudoElement:a})});return g};Fvh=function(a){return document.startViewTransition?document.startViewTransition(a):Evh(a)};Evh=function(a){a=Promise.resolve(a()).then(()=>{});return{ready:Promise.resolve(),updateCallbackDone:a,finished:a,skipTransition:()=>{}}};
Jvh=function(a,b={}){for(var c of _.Gvh())c.cancel();const d=document.createElement("style");document.head.prepend(d);const e=[];var f;b.groups=(f=b.groups)!=null?f:[];const g=()=>b.root?[b.root,...b.groups]:b.groups;b.root&&(b.root.viewTransitionName="root");var h;((h=b.root)==null?0:h.disable)&&_.Hvh(d,":root",{viewTransitionName:"none"});b.IHd&&_.Hvh(d,"::view-transition",{pointerEvents:"none"});for(f=0;f<b.groups.length;f++)h=b.groups[f],c=`spa-vt-${f}`,h.viewTransitionName=c,h.element&&(h.element.style.viewTransitionName=
c);f=Fvh(async()=>{var k=(0,_.Qf)(),l=k();k=k(1);try{const p=g().map(q=>{let r;return(r=q.jI)==null?void 0:r.call(q)}).filter(q=>q);k(await l(Promise.all([a(),...p])));for(const q of b.groups)q.bea===void 0&&(q.bea=q.W4a?q.W4a():q.element),q.element&&(q.element.style.viewTransitionName=""),q.bea&&(q.bea.style.viewTransitionName=q.viewTransitionName)}finally{l()}});f.updateCallbackDone.then(()=>{let k,l,p;b=(p=(l=(k=b).updateCallbackDone)==null?void 0:l.call(k,b))!=null?p:b;for(const q of b.groups){let r,
u;(u=(r=q).updateCallbackDone)==null||u.call(r,q)}});f.updateCallbackDone.catch(()=>{});f.ready.then(()=>{var k,l;(l=(k=b).ready)==null||l.call(k,b);for(var p of b.groups){let q,r;(r=(q=p).ready)==null||r.call(q,p)}for(const q of b.groups)q.bea&&(q.bea.style.viewTransitionName="");if(k=b.keyframes)for(const q of k){k=d.sheet.insertRule(`@keyframes ${q.name} {}`);k=d.sheet.cssRules[k];for(const [r,u]of Object.entries(q.keyframes)){l=u;k.appendRule(`${r} {}`);p=k.cssRules[k.cssRules.length-1];for(const A in l)l.hasOwnProperty(A)&&
(p.style[A]=l[A])}}for(const q of g())e.push(...Ivh(d,q));for(const q of g()){let r;((r=q)==null?0:r.iSa)&&e.push(...xvh(q.viewTransitionName,q.iSa,q.bac))}for(const q of e)q()},()=>{});f.finished.catch(()=>{});f.finished.finally(()=>{let k,l;(l=(k=b).finished)==null||l.call(k,b);for(const p of b.groups){let q,r;(r=(q=p).finished)==null||r.call(q,p)}for(const p of b.groups)p.element&&(p.element.style.viewTransitionName=""),p.bea&&(p.bea.style.viewTransitionName="");d.remove()});return f};
Ivh=function(a,b){if(!b)return[];const c=b.viewTransitionName;return[Kvh(a,c,"old",b.Cra),Kvh(a,c,"new",b.new),Kvh(a,c,"group",b.group),Kvh(a,c,"image-pair",b.KAb)].flatMap(d=>d)};Kvh=function(a,b,c,d){const e=[];if(!d)return e;d.animation&&(e.push(Lvh(b,c,d.animation)),d.styles=d.styles||{},d.styles.animation="none");let f;(f=d.RNb)==null||f.forEach(g=>{e.push(Lvh(b,c,g))});d.styles&&_.Hvh(a,`::view-transition-${c}(${b})`,d.styles);return e};
Lvh=function(a,b,c){const d=`::view-transition-${b}(${a})`;return()=>document.documentElement.animate(c.keyframes,Object.assign({},c.options,{pseudoElement:d}))};_.Hvh=function(a,b,c){b=a.sheet.insertRule(`${b} {}`);a=a.sheet.cssRules[b];for(const d in c)c.hasOwnProperty(d)&&(a.style[d]=c[d]);return a};_.Gvh=function(){return document.getAnimations().filter(a=>{a=a.effect;let b;return(a==null?void 0:a.target)===document.documentElement&&((b=a.pseudoElement)==null?void 0:b.startsWith("::view-transition"))})};
_.Nvh=function(a,b){return _.Mvh||(b==null||!b.vSd)&&window.matchMedia("(prefers-reduced-motion: reduce)").matches?Evh(a):Jvh(a,b)};Dvh={linear:[0,0,1,1],ease:[.25,.1,.25,1],"ease-in":[.42,0,1,1],"ease-out":[0,0,.58,1],"ease-in-out":[.42,0,.58,1]};_.Mvh=!!(_.Gi[68]&64);_.Ovh=!!(_.Gi[68]&128);_.Pvh=!!document.startViewTransition;
var xRe,yRe,zRe,ARe,BRe,ERe,FRe,GRe;xRe=function(){return""};yRe=function(){return""};zRe=function(){return""};ARe=function(){return!0};BRe=function(){return!1};ERe=function(a){_.CRe(a);return _.DRe()};FRe=function(a){_.CRe(a);return _.z(_.DRe())};_.DRe=function(){return"\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430..."};_.CRe=function(a){a.oa(GRe)||a.Aa(GRe,{},ERe,FRe,ARe,BRe,"",xRe,"",yRe,"",zRe)};GRe="t-YP5RR70-9Qs";var JRe,KRe,LRe;JRe=function(a){_.HRe(a);return _.IRe()};KRe=function(a){_.HRe(a);a="<div"+_.X("RoKmhb ")+_.Y("")+_.W("")+">";const b=_.IRe();return _.z(a+(b+"</div>"))};_.IRe=function(){return"<div"+_.X("beDQP ")+_.Y("")+_.W("")+"><div"+_.X("DU0NJ SPKFmc x3SdXd J7uuUe ")+_.Y("")+_.W("")+"></div></div><div"+_.X("FcXfi ")+_.Y("")+_.W("")+"><div"+_.X("DU0NJ SPKFmc tS3P5 ")+_.Y("")+_.W("")+"></div></div><div"+_.X("beDQP ")+_.Y("")+_.W("")+"><div"+_.X("DU0NJ SPKFmc x3SdXd sDPIC ")+_.Y("")+_.W("")+"></div></div>"};
_.HRe=function(a){a.oa(LRe)||a.Aa(LRe,{},JRe,KRe)};LRe="t-nBXuT1jwnnY";
_.Xhe=!!(_.Gi[68]&32);
var MRe=function(a){a=' height="'+_.S(String(a))+'" src="'+_.kB(_.S(_.TA("//www.gstatic.com/ui/v1/activityindicator/loading"+(_.Xhe?".svg":"_"+String(a)+".gif"))))+'" width="'+_.S(String(a))+'" aria-label="';a+=_.cB(_.DRe());return a+'"'},ORe=function(a){NRe(a);return""},PRe=function(a,b){NRe(a);a=b.size;a="<img"+_.X("")+_.Y("")+_.W(MRe(a)+' role="progressbar"')+">";return _.z(a)},NRe=function(a){a.oa(QRe)||(a.Aa(QRe,{size:0},ORe,PRe),_.CRe(a))},QRe="t-XVClaBF4XUE";var TRe=function(a,b){RRe(a);return SRe(a,b.size)},URe=function(a,b){RRe(a);a=SRe(a,b.size);return _.z(a)},SRe=function(a,b){a="<div"+_.X("lP3Jof nNMuOd ")+_.Y("height:"+_.S(_.VA(a.isRtl()?_.RA("height",String(b)+"px"):String(b)+"px"))+";width:"+_.S(_.VA(a.isRtl()?_.RA("width",String(b)+"px"):String(b)+"px"))+";")+_.W(' aria-label="'+_.cB(_.DRe())+'" role="progressbar"')+">";b="<div"+_.X("VQdeab RoKmhb ")+_.Y("")+_.W("")+">"+_.IRe()+"</div>";a+=b;b="<div"+_.X("IEqiAf RoKmhb ")+_.Y("")+_.W("")+">"+
_.IRe()+"</div>";a+=b;b="<div"+_.X("smocse RoKmhb ")+_.Y("")+_.W("")+">"+_.IRe()+"</div>";a+=b;b="<div"+_.X("FlKbCe RoKmhb ")+_.Y("")+_.W("")+">"+_.IRe()+"</div>";return a+b+"</div>"},RRe=function(a){a.oa(VRe)||(a.Aa(VRe,{size:0},TRe,URe),_.CRe(a),_.HRe(a))},VRe="t-3W4tVYHH3r4";var WRe,XRe,YRe,ZRe,$Re,aSe;WRe=function(){return""};_.EL=function(a,b){a=_.DB||b;return(a?"jbBItf ":"")+(a?"GgTJWe ":"")+(a?"VDgVie ":"")};
_.FL=function(a,b,c,d){c=c==null?3:c;d=d==null?0:d;b=_.DB||b;c=c==3?24:c==2?19:16;d=d==3?36:d==2?24:d==1?20:d==4?16:30;return"height:"+_.S(_.VA(a.isRtl()?_.RA("height",b?String(d)+"px":String(c)+"px"):b?String(d)+"px":String(c)+"px"))+";"+(b?"":"width:"+_.S(_.VA(a.isRtl()?_.RA("width",String(c)+"px"):String(c)+"px"))+";")+(b?"min-width:"+_.S(_.VA(a.isRtl()?_.RA("min-width",String(d)+"px"):String(d)+"px"))+";":"")};XRe=function(){return!0};YRe=function(){return!1};
ZRe=function(a,b){_.GL(a);return _.HL(a,b.ATa,b.vlb,b.SNa)};$Re=function(a,b){_.GL(a);var c=b.ATa,d=b.vlb,e=b.SNa;b="<g-loading-icon"+_.X(_.EL(a,c,d,e)+"")+_.Y(_.FL(a,c,d,e)+"")+_.W("")+">";a=_.HL(a,c,d,e);return _.z(b+(a+"</g-loading-icon>"))};
_.HL=function(a,b,c,d){c=c==null?3:c;d=d==null?0:d;b=_.DB||b;d=d==3?36:d==2?24:d==1?20:d==4?16:30;var e=c==3?24:c==2?19:16;c=_.yB(a,{Fb:103896,rl:!0}).attributes+_.zB(a);b&&(a=SRe(a,d),c+=a);b||(a="<img"+_.X("")+_.Y("")+_.W(MRe(e)+' role="progressbar"')+">",c+=a);return c};_.GL=function(a){a.oa(aSe)||(a.Aa(aSe,{ATa:0,vlb:1,SNa:2},ZRe,$Re,XRe,YRe,"",WRe,"",_.EL,"",_.FL),NRe(a),RRe(a))};aSe="t-aEtoEkf3B4A";
var t1e,u1e,v1e,w1e,x1e,y1e,z1e,A1e;_.s1e=function(a){_.q1e(a);let b;b="<div"+_.X("rVGT ")+_.Y("")+_.W("")+">";const c=_.r1e(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+"</div>";a.Ha();return _.z(b)};t1e=function(){return""};u1e=function(){return""};v1e=function(){return""};w1e=function(){return!0};x1e=function(){return!1};y1e=function(a){_.q1e(a);return _.r1e(a)};z1e=function(a){_.q1e(a);var b="<div"+_.X("rVGT ")+_.Y("")+_.W("")+">";a=_.r1e(a);return _.z(b+(a+"</div>"))};
_.r1e=function(a){a.Ba(".rVGT{display:flex;justify-content:center;left:50%;position:absolute;top:18%;transform:translateX(-50%);z-index:1}");return"<g-loading-icon"+_.X(_.EL(a,!0,null,null)+"")+_.Y(_.FL(a,!0,null,null)+"")+_.W("")+">"+_.HL(a,!0,null,null)+"</g-loading-icon>"};_.q1e=function(a){a.oa(A1e)||(a.Aa(A1e,{},y1e,z1e,w1e,x1e,"",t1e,"rVGT ",u1e,"",v1e),_.GL(a))};A1e="t-Zg8vSMWW_Oc";
var OZe,PZe,QZe;OZe=function(a){_.MZe(a);return _.NZe()};PZe=function(a){_.MZe(a);return _.z(_.NZe())};_.NZe=function(){return"\u0417\u0430\u043a\u0440\u044b\u0442\u044c"};_.MZe=function(a){a.oa(QZe)||a.Aa(QZe,{},OZe,PZe)};QZe="t-h4_qT3LgTLQ";
_.jC=function(a){return _.t(a,23)};_.kC=function(a){return _.He(a,1,-1)};_.lC=function(a){var b=new _.jp;return _.wi(b,1,a)};_.mC=function(a,b){return _.Uh(a,3,b)};_.nC=function(a,b){return _.Uh(a,4,b)};_.oC=function(a,b){return _.Lb(a,_.jp,13,b)};_.pC=function(a){return _.Wi(a,_.jp,13)};_.qC=function(a,b){return _.Uh(a,18,b)};
var $Ze,a_e,b_e;_.RZe=function(){return' role="button" tabindex="0"'};_.SZe=function(a,b){var c="";b=b==null?_.lC(242837):b;c=c+' aria-label="'+_.cB(_.NZe());return c+='" jsaction="'+_.S("trigger.gZgazf")+'"'+_.yB(a,{Fb:_.V(b,-1,d=>_.kC(d)),track:[3]}).attributes};_.TZe=function(){return"VB2c0b "};_.UZe=function(a,b){b==null&&_.lC(242837);return""};
_.VZe=function(a,b,c,d){var e="";b==null&&_.lC(242837);return e+=(c?"background-color:"+_.S(_.VA(a.isRtl()?_.RA("background-color",c):c))+";":"")+(d?"color:"+_.S(_.VA(a.isRtl()?_.RA("color",d):d))+";":"")};_.WZe=function(a,b){b==null&&_.lC(242837);return!0};_.XZe=function(a,b){b==null&&_.lC(242837);return!1};$Ze=function(a,b){_.YZe(a);return _.ZZe(a,b.Ne)};
a_e=function(a,b){_.YZe(a);var c=b.Ne,d=b.ODd,e=b.Eua;b="";c==null&&_.lC(242837);b+="<div"+_.X(_.UZe(a,c,d,e)+_.TZe())+_.Y(_.VZe(a,c,d,e)+"")+_.W(_.SZe(a,c,d,e)+_.RZe())+">";c=_.ZZe(a,c);b+=c+_.zB(a)+"</div>";return _.z(b)};
_.ZZe=function(a,b){b==null&&_.lC(242837);b=_.aA(_.mi().Ua);a.Ba(".VB2c0b{color:"+(_.V(b,"",d=>_.oA(d))+";position:absolute;top:6px;right:16px;width:40px;height:40px;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:1}"));a.Ba(".VB2c0b:hover{background-color:"+_.V(b,"",d=>_.sA(d))+"}");b="";var c="<span"+_.X(""+_.VB())+_.Y(_.WB(a,24)+"")+_.W("")+">"+_.UB()+"</span>";return b=b+c+_.zB(a)};
_.YZe=function(a){a.oa(b_e)||(a.Aa(b_e,{Ne:0,ODd:1,Eua:2},$Ze,a_e,_.WZe,_.XZe,_.RZe(),_.SZe,_.TZe(),_.UZe,"",_.VZe),_.MZe(a),_.XB(a))};b_e="t-UPSXq0uirLs";
var A_e,B_e,C_e,D_e,E_e,F_e,G_e;_.v_e=function(a){return a};_.z_e=function(a){_.w_e(a);let b;b="<div"+_.X("ZCPy9b ")+_.Y("")+_.W(_.x_e(a)+"")+">";const c=_.y_e(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c+_.zB(a)+"</div>";a.Ha();return _.z(b)};_.x_e=function(a){return _.yB(a,{Fb:164355}).attributes};A_e=function(){return""};B_e=function(){return""};C_e=function(){return!0};D_e=function(){return!1};E_e=function(a){_.w_e(a);return _.y_e(a)};
F_e=function(a){_.w_e(a);var b="<div"+_.X("ZCPy9b ")+_.Y("")+_.W(_.x_e(a)+"")+">";const c=_.y_e(a);b+=c+_.zB(a)+"</div>";return _.z(b)};_.y_e=function(a){a.Ba(".ZCPy9b{height:52px}");var b="";if(_.WZe(a,null,"","")){var c="<div"+_.X(_.UZe(a,null,"","")+_.TZe())+_.Y(_.VZe(a,null,"","")+"")+_.W(_.SZe(a,null,"","")+_.RZe())+">"+_.ZZe(a,null)+"</div>";b+=_.XZe(a,null,"","")?"":c}return b+=_.zB(a)};_.w_e=function(a){a.oa(G_e)||(a.Aa(G_e,{},E_e,F_e,C_e,D_e,"",_.x_e,"ZCPy9b ",A_e,"",B_e),_.YZe(a))};
G_e="t-75SV09ER6Uw";
_.KL=function(a){const b=document.createElement("div"),c=_.wSe(),{qMa:d,dG:e}=_.NSc();c.Pa=d;_.Sc(b,a(c));if(!b.firstElementChild)throw Error("Fi");return{node:b.firstElementChild,dG:e}};_.xSe=class{constructor(a,b){this.oa=a;this.gya=b}dispatch(){var a=this.oa,b=this.gya;const c=_.Xg();c.Lc("sqi","21").Lc("ei",a);b&&c.Lc("pepp",b);c.log()}};
_.MD=function(a){return _.t(a,1)};_.ND=function(a){return _.t(a,4)};_.OD=function(a){return _.t(a,3)};_.Gbd=function(a){return _.t(a,34)};_.PD=function(a){return _.t(a,37)};_.QD=!!(_.Gi[25]&4);
_.v("Sp69O");
var syB,tyB,uyB,wyB,vyB,yyB,xyB,ByB,CyB,IyB,JyB,KyB,UyB,SyB,VyB,WyB,ZyB,$yB,YyB,azB,XyB,czB,bzB,dzB,OyB,TyB,ezB,fzB,gzB,LyB,hzB,izB,jzB,NyB,kzB,lzB,RyB,ryB,mzB,zyB,nzB;syB=function(a){if(ryB)return ryB;const b=_.Ie(_.ym("iGkMSe"));return ryB=_.v6h(a,251333,b)};
tyB=function(a,b){var c={duration:250,easing:"cubic-bezier(.75,1,.75,1)"};const d=b.width/a.width,e=b.left-a.left*d;a=b.top-a.top*d;return{y3d:{keyframes:[{opacity:1,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:0,transform:`translate(${e}px, ${a}px) scale(${d})`,transformOrigin:"top left",mixBlendMode:"normal"}],options:c},v2d:{keyframes:[{opacity:0,transform:`translate(${-e/d}px, ${-a/d}px) scale(${1/d})`,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:1,
transformOrigin:"top left",mixBlendMode:"normal"}],options:c}}};
uyB=function({element:a,bea:b,W4a:c,iSa:d=2,containment:e=!0,D4c:f,idf:g,jXc:h,Haf:k,v8e:l=.5,backgroundColor:p,bac:q=!1,options:r={}}){let u;r.duration=(u=r.duration)!=null?u:250;let A;r.easing=(A=r.easing)!=null?A:_.wQb;let E;r.fill=(E=r.fill)!=null?E:"both";const I=r.duration,N=r.easing;b={element:a,bea:b,W4a:c,group:{},KAb:{},Cra:{},new:{}};e&&(b.group.styles={overflow:"hidden",borderRadius:"20px",backgroundColor:p||window.getComputedStyle(document.body).backgroundColor});const P=a.getBoundingClientRect(),
T=g!=null?g:f==null?void 0:f.getBoundingClientRect();b.ready=Z=>{if(Z.bea){var ca;Z.group=(ca=Z.group)!=null?ca:{};if(ca=_.vvh(Z.viewTransitionName,q)){var ja=ca.p8c,da=ca.s8c,ma=ca.t8c,sa=ca.n8c,za=ca.m7c,Ga=ca.p7c,fb=ca.q7c,Wa=ca.Pma,qb=ca.hN,sb=ca.XP;ca=Z.bea.getBoundingClientRect();var Nb,Ob=k?k():(Nb=h?h():f)==null?void 0:Nb.getBoundingClientRect();Nb=sb*sa/Wa;ma=d===4?1:d===5?Nb:qb*ma/fb;fb=d===3||d===2?Nb:ma;Z.group.animation={keyframes:[{transform:`translate(${ja}px, ${da}px) scale(${ma}, ${fb})`,
transformOrigin:"top left"},{transform:`translate(${za}px, ${Ga}px) scale(1, 1)`,transformOrigin:"top left"}],options:r};d===2&&(Z.KAb!=null||(Z.KAb={}),ja=_.Cvh({name:Z.viewTransitionName,easing:N,duration:I,q8c:ma,r8c:fb}),Z.KAb.animation=ja[0],Z.KAb.RNb=ja.slice(1));T&&Ob&&Z.Cra&&Z.new&&(ja=Ob.left-ca.left-(T.left-P.left),ca=Ob.top-ca.top-(T.top-P.top),Ob={keyframes:[{offset:0,opacity:"0",transform:`translate(${-ja}px, ${-ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-
.1,opacity:"0"},{offset:l+.1,opacity:"1"},{offset:1,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.Cra.animation={keyframes:[{offset:0,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-.1,opacity:"1"},{offset:l+.1,opacity:"0"},{offset:1,opacity:"0",transform:`translate(${ja}px, ${ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.new.animation=Ob);
return Z}}};return b};wyB=function(a,b){b=vyB(a,b);return b!=null&&b!==0?b:vyB(a,_.Aff)};vyB=function(a,b){switch(a){case 0:case 1:return b==null?void 0:_.zj(b,2);case 2:return b==null?void 0:_.zj(b,3);case 3:return b==null?void 0:_.zj(b,4);case 4:return b==null?void 0:_.zj(b,5);default:_.$a(a,void 0)}};yyB=async function(a,b,c){var d=(0,_.Qf)(),e=d();d=d(1);try{const f=b.map(xyB);d(await e(a.update(f,c)))}finally{e()}};
xyB=function(a){return{contentPluginType:a.contentPluginType,content:a.content,viewerType:a.viewerType,serializedModalityOverride:a.nZ?zyB(a.nZ):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,entrypointId:a.entrypointId,replacedEntrypointId:a.replacedEntrypointId,interactionVed:a.interactionVed,contentId:a.contentId,uuid:a.uuid}};
ByB=function(a){return{viewerType:a.viewerType,nZ:a.serializedModalityOverride?(0,_.i9e)(a.serializedModalityOverride):void 0,serializedModalityOverride:void 0,UX:a.serializedCloseConfig?(0,_.wff)(a.serializedCloseConfig):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,qq:null,plugin:null,L4:new AbortController,contentPluginType:a.contentPluginType,content:a.content,entrypointId:a.entrypointId,contentId:a.contentId,replacedEntrypointId:a.replacedEntrypointId,
F6a:0,xja:new AyB,interactionVed:a.interactionVed,Mf:0,NIa:0,rNa:new _.Hq,uFb:!1,Hqa:Promise.resolve(),JX:new _.Hq,entrypoint:null,Rw:null,header:null,Qk:[],oza:!1,uuid:a.uuid,uca:!1,RZa:void 0}};CyB=function(a,b,c){for(;c<a.length;c++)a[c].oza=b};
IyB=function({client:a,SMa:b,Hne:c,Jne:d}){const e=a.shellStyleClass,f=a.xja,g=a.plugin,{node:h,dG:k}=_.KL(l=>{var p;let q;var r=_.$De&&(g==null?void 0:g.getType())===3,u=(q=(p=a.RZa)==null?void 0:p.Aa())!=null?q:null;DyB(l);p="";u==null&&new _.PL;p+="<div"+_.X(EyB(l,r,u)+"PG8i1e ")+_.Y(FyB(l,r,u)+"")+_.W(GyB(l,r,u)+' role="dialog"')+">";r=HyB(l,r,u);u=l.Da();u!==""&&(p+=" <style>"+u+"</style>");p+=r+_.zB(l)+"</div>";l.Ha();return _.z(p)});f.m1b({dispatch:k});h.setAttribute("data-svs","true");if(e)for(const l of e.split(" "))h.classList.add(l);
a.qq=h;if(c){const {node:l,dG:p}=_.KL(_.z_e);f.bB({dispatch:()=>void p({Fg:_.IL(h)})});h.appendChild(l);a.header=l}if(d){const {node:l,dG:p}=_.KL(_.s1e);f.bB({dispatch:()=>void p({Fg:_.IL(h)})});h.appendChild(l);a.Rw=l}document.body.appendChild(h);a.mZ=b.apply(a);return h};JyB=function(){let a,b=(a=document.body.clientHeight)!=null?a:0;try{const c=window.getComputedStyle(document.body),d=_.jEe(c.paddingTop),e=_.jEe(c.paddingBottom);b-=d+e}catch(c){}return b};
KyB=function(a,b){b=b||a.clientHeight||0;if(a.style.display==="none"||b<=100)b=JyB();a.style.setProperty("--Z9tEad",b>100?`${b}px`:"100dvh")};
UyB=async function(a,b,c,d,e,f,g){var h=(0,_.Qf)(),k=h();h=h(1);try{const P=a.plugin,T=a.qq,Z=a.rNa,ca=a.uFb,ja=a.mZ;if(ja!==5){var l=T.clientHeight||0;if(ja===2&&l<=100){const da=e.get();l=Math.max(0,JyB()-da.oa()-da.Pa())}KyB(T,l);if(ca)h(await k(Z.promise));else{var p=a.viewerType===74;if(ja===2){var q=_.VRb(_.eSb(_.aSb(new _.Cv,127),1),1,{replace:[6,...(p?[]:[7]),10]});a.entrypoint&&a.entrypoint instanceof HTMLElement&&_.fSb(q,a.entrypoint)}else{const da=[2];_.LDe&&da.push(1);_.JDe&&da.push(3);
_.KDe&&da.push(4);q=LyB(_.YRb(_.dSb(_.cSb(_.Av(_.aSb(new _.Bv,1E3),ja===3?1:2))),a.contentPluginType!==5&&a.contentPluginType!==19&&a.viewerType!==47&&a.viewerType!==73),{getScrollTopRequirement:()=>1,getShouldDisableScrolling:()=>!0,getSwipeToDismissDirections:()=>da})}var r,u;_.URb(_.zv(_.wv(_.xv(q,[2]),f),(u=P==null?void 0:(r=P.Rce)==null?void 0:r.call(P))!=null?u:!0),5);var A=MyB?window.google.zl:void 0,E;ja===2?E=new NyB([{element:T,Gx:"PyLEff",vL:!0}],[{element:T,Gx:"PyLEff",vL:!1}],OyB(a,b)):
_.HDe&&_.Pvh?E=new PyB(T,OyB(a,b)):_.IDe&&_.Pvh?E=new QyB(T,OyB(a,b)):E=new RyB(T,OyB(a,b));_.yv(q,E);!SyB(a)&&d.isAvailable()&&ja===1&&d.enterBasicMode(58);var I=c.open(T,q);Z.resolve(I);a.uFb=!0;h(await k(Z.promise));var N;A==null||(N=A.cqsv)==null||N.call(A);g();a.Mf>=5&&TyB(T)}}}finally{k()}};SyB=function(a){const b=MyB?window.google.zl:void 0;return!(a.F6a===2||a.F6a===4)||!(b==null||!b.qsvo)};VyB=function(a){const b=a.plugin;(a=a.qq)&&((b==null?0:b.ebd)?b.ebd():a.remove())};
WyB=async function(a,b,c){var d=(0,_.Qf)(),e=d();d=d(1);try{b.at(-1),a.Hqa||(a.Hqa=yyB(c,b,{replace:!1})),d(await e(a.Hqa))}finally{e()}};ZyB=function(a,b){const c=a.entrypoint;a=a.contentId;const d=b.at(-1);return d?XyB(d,YyB(d,b))===c?d.contentId&&a&&d.contentId!==a?!1:!0:!1:!1};
$yB=function(a,b){for(let d=b.length-1;d>=0;d--){const {qq:e}=b[d];let f;var c;if(!(c=(f=e)==null?0:f.contains(a))&&(c=d===0&&b[d].viewerType===74&&e))a:{c=a.closest("[jsowner]");if(!c){c=!1;break a}c=(c=document.getElementById(c.getAttribute("jsowner")))?e.contains(c):!1}if(c)return d}return-1};YyB=function(a,b){a=b.indexOf(a);return a>0?b[a-1]:null};azB=function(a,b){if(a==null||b==null)return a===b;if(a.length!==b.length)return!1;for(let c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};
XyB=function(a,b){if(a.entrypoint)return a.entrypoint;b=bzB(a.entrypointId,b);a.entrypoint=b;czB(a);return b};czB=function(a){let b;!a.entrypoint||(b=a.entrypoint)!=null&&b.querySelector("img, svg")||(a.uca=!0)};bzB=function(a,b){return a?(b=b?b.qq:document.body)?b.querySelector(`[id="${a}"]`):null:null};dzB=function(a,b){const c=a.entrypoint,d=a.replacedEntrypointId;return c&&c.isConnected?c:d?bzB(d,b):XyB(a,b)};
OyB=function(a,b){const c=b[0],d=YyB(a,b),e=!!d;return{UTb:function(){let f,g;const h=(f=a.plugin)==null?void 0:(g=f.X4a)==null?void 0:g.call(f,e);let k;return{Vxa:(k=h==null?void 0:h.Vxa)!=null?k:dzB(a,d),c6a:h==null?void 0:h.c6a,tba:(h==null?void 0:h.tba)||a.oza||SyB(a),PEa:h==null?void 0:h.PEa,Oic:a.uca}},bTb:function(){var f;let g;const h=(f=a.plugin)==null?void 0:(g=f.v4a)==null?void 0:g.call(f,e);f=h==null?void 0:h.Vxa;f===void 0&&(f=b.length===0?dzB(c,null):dzB(a,d));return{Vxa:f,c6a:h==null?
void 0:h.c6a,tba:(h==null?void 0:h.tba)||a.oza,PEa:h==null?void 0:h.PEa,Oic:a.uca}}}};TyB=function(a){(0,_.cNa)().then(()=>{const b=_.vma(a);_.$Ae(b)})};ezB=function(){let a;((a=google)==null?0:a.uh)?google.uh("sv"):document.body.style.opacity=""};fzB=function(a){a.fsa!=null||(a.fsa=!1);a.uca!=null||(a.uca=!1);a.viewerType!=null||(a.viewerType=void 0);a.source!=null||(a.source=void 0)};
gzB=function(a,b){const c=a.plugin,d=a.qq;if(c){let e;c==null||(e=c.Rdd)==null||e.call(c,a===b);let f;c==null||(f=c.setActive)==null||f.call(c,a===b)}d&&_.Yd(d,"hidden",a!==b)};LyB=function(a,b){a.Ha=b;return a};
hzB={[28]:_.sIq,[1]:_.x5h,[3]:_.N7h,[4]:_.l1a,[5]:_.aaf,[19]:_.baf,[17]:_.wBq,[14]:_.FFq,[6]:_.J0a,[9]:_.RIj,[11]:_.yUi,[13]:_.I0a,[15]:_.lUi,[22]:_.SJj,[27]:_.KUq,[29]:_.yAq,[7]:_.Mwq,[8]:_.bPq,[10]:_.TPq,[12]:_.uBq,[16]:_.V0a,[18]:_.DRq,[20]:_.oAq,[33]:_.qAq,[21]:_.zAq,[41]:_.dSe,[23]:_.Dwq,[25]:_.p1e,[26]:_.hBq,[30]:_.Qwq,[31]:_.vBq,[32]:_.XQq,[34]:_.Ezq,[35]:_.oQq,[36]:_.cFq,[37]:_.KBq,[38]:_.Fxq,[39]:_.cOq,[40]:_.mQq,[42]:_.BAq,[43]:_.hrq};izB=[5,19];_.ina=class extends Error{};
jzB={duration:250,easing:_.wQb};NyB=class extends _.vQb{constructor(a,b,c){super();this.Aa=a;this.oa=b;this.config=c}async open(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {tba:c}=this.config.UTb();_.QRb(this.Aa,c);c||a(await b(_.RRb(250)))}finally{b()}}async close(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {tba:c}=this.config.bTb();_.QRb(this.oa,c);c||a(await b(_.RRb(250)))}finally{b()}}};kzB=function(a){let b;(b=a.Aa)==null||b.remove();a.Aa=void 0};
lzB=function(a,b,c=!1){if(!b||c)return a.Aa?a=a.Aa:(a.Aa=document.createElement("div"),a.Aa.style.opacity="0.0000001",a.Aa.style.height="100px",a.Aa.style.width="100px",a.Aa.style.position="fixed",a.Aa.style.top="50%",a.Aa.style.left="50%",a.Aa.style.marginTop="-100px",a.Aa.style.marginLeft="-100px",a.Aa.style.pointerEvents="none",document.body.appendChild(a.Aa),a=a.Aa),a;kzB(a);return b};
RyB=class extends _.vQb{constructor(a,b){super();this.overlay=a;this.config=b}async open(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {Vxa:c,tba:d,PEa:e,Oic:f}=this.config.UTb(),g=lzB(this,c,f);this.overlay.style.display="block";d||(this.overlay.style.opacity="0",a(await b(_.ARb({token:e!=null?e:_.zQb,before:g,after:this.overlay}).play())));this.overlay.style.opacity="1"}finally{b()}}async close(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {Vxa:c,tba:d,PEa:e,Oic:f}=this.config.bTb(),g=lzB(this,c,f);d||
(g.style.opacity="0",a(await b(_.BRb({token:e!=null?e:jzB,before:this.overlay,after:g}).play())));(()=>{this.overlay.style.display="none";g.style.opacity="";kzB(this)})()}finally{b()}}};zyB=_.Tb(_.h9e);nzB=_.Tb(_.vff);var QyB=class extends RyB{constructor(a,b){super(a,b);this.overlay=a;this.config=b}async open(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {Vxa:p,tba:q}=this.config.UTb(),r=()=>{this.overlay.style.display="block"};if(q)r();else{var c=lzB(this,p).getBoundingClientRect(),d={},e=_.Nvh(r,{root:d});a(await b(e.updateCallbackDone));var f=document.body.getBoundingClientRect(),g,h=((g=this.overlay.querySelector('[jsname="figiqf"]'))==null?void 0:g.getBoundingClientRect())||f,{y3d:k,v2d:l}=tyB(c,Object.assign({},
h.toJSON(),{left:0}));d.Cra={animation:k};d.new={animation:l}}}finally{b()}}async close(){var a=(0,_.Qf)(),b=a();a=a(1);try{const {Vxa:e,tba:f}=this.config.bTb(),g=lzB(this,e),h=()=>{this.overlay.style.display="none";g.style.opacity=""};if(f)h();else{var c=window.getComputedStyle(document.body).backgroundColor,d=_.Nvh(h,{groups:[{element:this.overlay,W4a:()=>g,group:{styles:{overflow:"hidden",backgroundColor:c,borderRadius:"16px"}},iSa:2,bac:!0}]});a(await b(d.finished))}}finally{b()}}},pzB=async function(a){const {Vxa:b,
c6a:c,tba:d}=a.config.bTb(),e=lzB(a,b);if(d)a.overlay.style.display="none",e.style.opacity="";else{var f={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",fill:"both"},g=(c||a.overlay).getBoundingClientRect(),h={new:{animation:{keyframes:[{offset:0,transform:"scale(1.2)",opacity:"0"},{offset:1,transform:"scale(1)",opacity:"1"}],options:f}}},k=uyB({element:c||a.overlay,bea:e,D4c:c,jXc:()=>e,containment:!1,iSa:1,bac:!0,options:f});return new Promise(l=>{a.Ba=_.Nvh(()=>{a.overlay.style.display="none";
e.style.opacity=""},{vSd:!0,root:h,groups:[k],updateCallbackDone:p=>{const q=lzB(a,b).getBoundingClientRect(),r=q.width/g.width;p.root.Cra={animation:{keyframes:[{transform:"translate(0px, 0px) scale(1)",transformOrigin:"top left"},{transform:`translate(${q.left-0*r}px, ${q.top-g.top*r}px) scale(${r})`,transformOrigin:"top left"}],options:Object.assign({},f,{id:"close-root-old"})},styles:{zIndex:"1"},RNb:[{keyframes:[{opacity:1},{opacity:0}],options:f}]};a.oa={vHc:a.Ba,YZc:k,MHa:[],CEb:[],oDa:{},
Oj:{}};l()},finished:()=>{ozB(a);let p,q;(p=a.oa)==null||(q=p.Mb)==null||q.remove();a.oa=void 0}})})}},rzB=function(a){let b;(b=a.oa)==null||b.vHc.skipTransition();ozB(a);let c,d;(c=a.oa)==null||(d=c.Mb)==null||d.remove();a.oa=void 0;qzB(a)},szB=function(a,b){a.oa&&(b(a.oa.oDa),b(a.oa.Oj))},qzB=function(a){a.overlay.style.display="block"},ozB=function(a){let b;(b=a.oa)==null||b.MHa.forEach(c=>{c.cancel()})},PyB=class extends RyB{constructor(a,b){super(a,b);this.overlay=a;this.config=b;this.swipeToDismiss=
{onStart:async()=>{var c=(0,_.Qf)(),d=c();c=c(1);try{if(c(await d(pzB(this))),this.oa){c(await d(this.oa.vHc.ready));this.oa.MHa=_.Gvh();var e=`::view-transition-group(${this.oa.YZc.viewTransitionName})`;this.oa.oDa.animation=this.oa.MHa.find(g=>g.effect.pseudoElement===e);this.oa.Oj.animation=this.oa.MHa.find(g=>g.id==="close-root-old");if(!this.oa.oDa.animation)throw rzB(this),Error("jB");if(!this.oa.Oj.animation)throw rzB(this),Error("kB");this.oa.CEb=this.oa.MHa.filter(g=>g!==this.oa.oDa.animation&&
g!==this.oa.Oj.animation);for(const g of this.oa.MHa)g.pause();var f=document.createElement("style");this.oa.Mb=f;document.head.appendChild(f);this.oa.oDa.rule=_.Hvh(f,`html::view-transition-group(${this.oa.YZc.viewTransitionName})`,{});this.oa.Oj.rule=_.Hvh(f,"html::view-transition-old(root)",{});szB(this,g=>{const h=new DOMMatrix(window.getComputedStyle(document.documentElement,g.animation.effect.pseudoElement).transform);g.Hn=_.yvh(h)})}}finally{d()}},onMove:async c=>{if(this.oa&&this.oa.MHa.length){var d=
this.oa.MHa[0].effect.getTiming().duration;d=Math.min(Math.max(d*c.yWithTension/4E3,0),d/3);for(const e of this.oa.CEb)e.currentTime=d;szB(this,({rule:e,Hn:f})=>{e.style.setProperty("transform",`${`translate(${c.xWithTension+f.left}px, ${c.yWithTension+f.top}px)`} scale(${f.hN*c.scale}, ${f.XP*c.scale})`,"important")})}},onDismiss:()=>{if(this.oa){szB(this,({animation:e,rule:f})=>{var g=e.effect;const h=g.getKeyframes();h[0].transform=f.style.transform;g.setKeyframes(h);g=e.effect.getTiming().duration;
const k=Math.max(this.oa.CEb[0].currentTime,100);e.cancel();document.documentElement.animate([{transform:f.style.transform},{transform:h[1].transform}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:g-k,pseudoElement:e.effect.pseudoElement})});var c,d;(c=this.oa)==null||(d=c.Mb)==null||d.remove();for(const e of this.oa.MHa)e.play()}},onCancel:()=>{if(this.oa){var c=Math.max(this.oa.CEb[0].currentTime,100),d;szB(this,({animation:g,rule:h})=>{d=document.documentElement.animate([{transform:h.style.transform},
{transform:""}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:c,pseudoElement:g.effect.pseudoElement})});var e,f;(e=this.oa)==null||(f=e.Mb)==null||f.remove();for(const g of this.oa.CEb)g.currentTime=Math.max(g.currentTime,1),g.reverse();d.finished.then(()=>{rzB(this)})}}}}async open(){var a=(0,_.Qf)(),b=a();a=a(1);try{let c;a(await b((c=this.Ca)==null?void 0:c.finished))}finally{b()}}async beforeOpen(){const {Vxa:a,c6a:b,tba:c}=this.config.UTb();if(c)qzB(this);else{var d={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",
fill:"both"},e=lzB(this,a),f=e.getBoundingClientRect(),g={Cra:{animation:{keyframes:[{offset:0,transform:"scale(1)",opacity:"1"},{offset:1,transform:"scale(1.2)",opacity:"0"}],options:d}}},h=uyB({element:e,bea:b||this.overlay,D4c:e,jXc:()=>b,containment:!1,iSa:1,options:d});return new Promise(k=>{this.Ca=_.Nvh(()=>{k();qzB(this)},{root:g,groups:[h],updateCallbackDone:l=>{const p=(b||this.overlay).getBoundingClientRect(),q=f.width/p.width;l.root.new={animation:{keyframes:[{transform:`translate(${f.left-
0*q}px, ${f.top-p.top*q}px) scale(${q})`,transformOrigin:"top left"},{transformOrigin:"top left"}],options:d},RNb:[{keyframes:[{opacity:0},{opacity:1}],options:{delay:200,duration:300,fill:"both",easing:"cubic-bezier(.34,.69,.34,1)"}}]}}})})}}async close(){var a=(0,_.Qf)(),b=a();a=a(1);try{this.oa||a(await b(pzB(this))),this.oa&&a(await b(this.oa.vHc.finished))}finally{b()}}};var GyB=function(a,b,c){b="";c==null&&new _.PL;return b+=' jsname="'+_.S("ujKaBc")+'" decode-data-ved="'+_.S("1")+'"'+_.yB(a,{Fb:233502,track:[4,3]}).attributes},EyB=function(a,b,c){c==null&&new _.PL;return""},FyB=function(a,b,c){c==null&&new _.PL;return""},tzB=function(a,b,c){c==null&&new _.PL;return!0},uzB=function(a,b,c){c==null&&new _.PL;return!1},vzB=function(a,b){DyB(a);return HyB(a,b.s0c,b.Hra)},wzB=function(a,b){DyB(a);var c=b.s0c,d=b.Hra;b="";d==null&&new _.PL;b+="<div"+_.X(EyB(a,c,d)+"PG8i1e ")+
_.Y(FyB(a,c,d)+"")+_.W(GyB(a,c,d)+' role="dialog"')+">";c=HyB(a,c,d);b+=c+_.zB(a)+"</div>";return _.z(b)},HyB=function(a,b,c){c=c==null?new _.PL:c;var d=_.aA(_.mi().Ua),e=_.aA(_.mi().qH),f=_.aA(_.mi().Yi),g=_.aA(_.mi().Sp),h=_.aA(_.mi().Dc);a.Ba(".PG8i1e{background:"+_.V(d,"",k=>k.Uc())+";overflow:hidden;position:fixed;transform:translateX(0)}");a.Ba(".PG8i1e.Ooz8t{"+((_.MWd?"border:1px solid "+_.V(d,"",k=>k.Wr())+";border-radius:24px;box-shadow:none;opacity:0.001;transition:transform "+_.V(g,"",
k=>_.t(k,49))+" "+_.V(g,"",k=>_.t(k,56))+",opacity "+_.V(g,"",k=>_.t(k,49))+";":"")+(_.XRi&&!_.MWd?"border:1px solid "+_.V(d,"",k=>k.Wr())+";border-radius:"+_.V(f,"",k=>_.KB(k))+";box-shadow:none;":"")+(_.XRi||_.MWd?"":"border-radius:"+_.V(f,"",k=>_.KB(k))+";box-shadow:"+_.V(e,"",k=>_.t(k,8))+";opacity:0.001;transform:translateX(200px);transition:transform 250ms cubic-bezier(0.05,0.07,0.1,1),opacity 250ms")+"}"));a.Ba(".Ooz8t.F6z1Rc{box-shadow:"+_.V(e,"",k=>_.t(k,6))+"}");a.Ba(".PG8i1e.Ooz8t.PyLEff{opacity:0.999;"+
(_.XRi?"":"transform:translateX(0)")+"}");a.Ba(".MiFXAd{"+((_.QD?"background:"+_.V(d,"",k=>k.gW())+";":"")+(_.QD?"":"background:rgba(255,255,255,0.6);")+"display:flex;justify-content:center;align-items:center;backdrop-filter:blur(8px);position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(".QtrPTd{width:80%;height:calc(100% - 150px);top:75px;bottom:75px;left:10%}");a.Ba(".fLi1af{background:"+_.V(d,"",k=>k.Uc())+";border-radius:12px}");a.Ba(".Yktdff{"+((!_.KWd||_.QD?"background:#101218;color:"+
_.V(d,"",k=>_.hA(k))+";":"")+(_.KWd&&!_.QD?"background:"+_.V(d,"",k=>k.Uc())+";color:"+_.V(d,"",k=>_.Oo(k))+";":"")+"position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(!_.KWd||_.QD?".Yktdff .VB2c0b{color:"+_.V(d,"",k=>k.b0())+"}":"");a.Ba(".eQVlOe{padding-left:"+(_.V(h,"",k=>_.yA(k))+";padding-right:"+_.V(h,"",k=>_.yA(k))+"}"));a.Ba(_.qyB?".PG8i1e.Ooz8t.X3bDbe{border:1px solid "+_.V(d,"",k=>k.Wr())+";box-shadow:none;border-radius:24px;margin-top:20px;margin-bottom:20px}":"");d="";b&&_.G7h(a,
c)&&(b="<div"+_.X(_.E7h(a,c)+"HV5Yde ")+_.Y(_.F7h(a,c)+"")+_.W(_.D7h(a,c)+"")+">"+_.J7h(a,c)+"</div>",d+=_.H7h(a,c)?"":b);return d+=_.zB(a)},DyB=function(a){a.oa(xzB)||(a.Aa(xzB,{s0c:0,Hra:1},vzB,wzB,tzB,uzB,' role="dialog"',GyB,"PG8i1e ",EyB,"",FyB),_.I7h(a))},xzB="t-_7Z7QKitJBk";var zzB=function(a,b,c){const d=new AyB;yzB(d,a,b,c);return d},yzB=function(a,b,c,d){a.mode=0;a.xja.dispatch(b,c,d);a.xja=new AzB(b,c,d)},AyB=class{constructor(){this.mode=1;this.xja=new BzB}m1b(a){this.xja.m1b(a)}bB(a){this.xja.bB(a)}},AzB=class{constructor(a,b,c){this.interactionVed=a;this.Fg=b;this.lE=c}m1b(a){a.dispatch({interactionVed:this.interactionVed,Fg:this.Fg,vTa:!0,lE:this.lE})}bB(a){a.dispatch()}dispatch(){}},BzB=class{constructor(){this.oa=[]}m1b(a){this.Aa=a}bB(a){this.oa.push(a)}dispatch(a,
b,c){let d;(d=this.Aa)==null||d.dispatch({interactionVed:a,Fg:b,vTa:!0,lE:c});this.oa.forEach(e=>void e.dispatch())}};var MyB,CzB,GzB,FzB,IzB,NzB,KzB,OzB,QzB,TzB,RzB,SzB,EzB,PzB,HzB,VzB,MzB,DzB,LzB,UzB,WzB,JzB;MyB=_.FDe||_.GDe;CzB=function(a){return a.oa.at(-1)};
GzB=function(a,b,c){const d=YyB(b,a.oa),e=b.mZ;_.Pg(c,"KpPeYd",f=>{a.Ch(b,f.data)});_.Pg(c,"YS2dOd",f=>{DzB(a,b,2,f);EzB(a,b,2)});_.Pg(c,"gZgazf",f=>{DzB(a,b,1,f);EzB(a,b,1)});b.JX.promise.then(()=>{b.NIa=0;b.L4.abort();try{var f;let g;(f=b.plugin)==null||(g=f.v_b)==null||g.call(f)}catch(g){}VyB(b);for(const g of b.Qk)_.rn(g);if(e===1||_.DB&&e===4)f=XyB(b,d),!f||b.qq&&!b.qq.contains(document.activeElement)||FzB(f);(0,_.cNa)().then(()=>{_.aBe();(0,_.ph.dirty)()})});_.Pg(c,"ucVTnf",()=>{const f=b.plugin,
g=b.UX,h=a.oa,k=XyB(b,d),l=wyB(4,g)===1;let p;const q=(p=YyB(b,h))==null?void 0:p.qq;l&&q&&(q.style.display="");let r;(f==null?0:(r=f.bFb)==null?0:r.call(f,k))||!k||b.uca||(k.style.opacity="0");let u;if(f==null?0:f.Xmb)u=_.Rg(c,"pU3PWb",()=>{let A;return void(f==null?void 0:(A=f.Xmb)==null?void 0:A.call(f,k))});_.Rg(c,"s2IYHc",()=>{u&&_.Qg(u);let A;(f==null?0:(A=f.F_b)==null?0:A.call(f,k))||!k||b.uca||(k.style.opacity="");l&&q&&(q.style.display="none")})})};
FzB=function(a,b,c=!1){if(c){c=b.cD;c||(b.cD=new _.UWb(a),_.SWb(b.cD),c=b.cD);let d;(d=_.RWb(c,0))==null||d.focus({preventScroll:!0})}else b=document.activeElement,a.contains(b)&&a!==b||(a.tabIndex===0?a.focus({preventScroll:!0}):(b=_.HWb(a).find(d=>!d.hasAttribute("data-os-fs")))?b.focus({preventScroll:!0}):(a.tabIndex=-1,a.focus({preventScroll:!0})))};
IzB=async function(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const e=CzB(a);if(e){e.F6a=3;var d=syB(a.Pe);yzB(e.xja,d,d);document.dispatchEvent(new CustomEvent("viewerOpened"));b(await c(HzB(a,e)))}}finally{c()}};
NzB=async function(a,b,c=!1){var d=(0,_.Qf)(),e=d();d=d(1);try{_.ZDe||(c=!1);const g=a.oa;let h=b.length<g.length,k=b.length>g.length;const l=Math.min(b.length,g.length);let p=l;for(let q=0;q<l;q++)if(g[q].uuid!==b[q].uuid){h=k=!0;p=q;break}CyB(g,c,p);if(h&&!k){var f=g[p];let q,r,u;const A=(u=(q=f.plugin)==null?void 0:(r=q.w4a)==null?void 0:r.call(q))!=null?u:JzB(a,f);a.Pe.logEvent({ef:new _.Nh(A,26)})}h&&KzB(a,p);if(k){const q=b.slice(p).map(ByB);for(let r=q.length-1;r>=0;r--)if(q[r].uuid===a.Aa){d(await e(LzB(a,
1)));return}g.push(...q);CyB(g,c,p)}a.Aa=-1;(k||h)&&d(await e(MzB(a,k)));a.Ba&&(a.Ba.resolve(),a.Ba=null)}finally{e()}};
KzB=function(a,b,c=!1){b=a.oa.splice(b,Infinity);var d;const e=(d=CzB(a))==null?void 0:d.qq;e&&(e.style.display="");if(b.length!==0){a.Aa=b[0].uuid;a.oa.length!==0||c?c&&document.dispatchEvent(new CustomEvent("viewerReplaced")):document.dispatchEvent(new CustomEvent("viewerClosed"));for(const f of b)c=f.qq,d=f.uFb,b=f.JX,gzB(f,null),c&&d?((d=f.cD)&&_.TWb(d),f.qq&&!f.qq.contains(document.activeElement)||document.activeElement.blur(),a.Ef.close(c)):b.resolve()}};
OzB=function(a,b){return yyB(a.xi,a.oa,b)};QzB=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{const e=PzB(a,b);CyB(a.oa,!0,b);KzB(a,b,!0);c(await d(a.xi.go(-e)))}finally{d()}};
TzB=async function(a,b,c){var d=(0,_.Qf)(),e=d();d=d(1);try{const f=b.yy,g=b.entrypoint,h=b.interactionVed,k=b.lE,l=b.rG,p=b.UX,q=a.oa;for(const I of q)I.NIa=I.Mf;const r=_.V5h(g),u=_.IL(g);let A;const E={viewerType:b.viewerType,nZ:b.nZ,serializedModalityOverride:void 0,UX:p,serializedCloseConfig:p?nzB(p):void 0,shellStyleClass:b.shellStyleClass,qq:null,plugin:f,L4:new AbortController,contentPluginType:f.getType(),content:((A=f.serialize)==null?void 0:A.call(f))||new Uint8Array(0),entrypointId:r,
contentId:b.contentId,replacedEntrypointId:void 0,xja:zzB(h!=null?h:u,u,k),interactionVed:h!=null?h:u,F6a:2,Mf:3,NIa:7,rNa:new _.Hq,uFb:!1,Hqa:null,JX:new _.Hq,entrypoint:g,Rw:null,header:null,Qk:[],oza:c,uuid:Math.random(),uca:b.uca,RZa:b.RZa};czB(E);q.push(E);q.length===1&&document.dispatchEvent(new CustomEvent("viewerOpened"));try{g&&!_.HDe&&(g.animate({transform:["scale(1)","scale(.98)","scale(1)"]},{duration:65}),c||d(await e((0,_.cNa)()))),d(await e(RzB(a,{client:E,rG:l}))),(0,_.dNa)(()=>void SzB(a))}catch(I){d()}return E.qq}finally{e()}};
RzB=function(a,{client:b,rG:c}){let d;c==null||c.Ws((d=b.viewerType)!=null?d:0);return _.z6h({client:b,rG:c,Jwb:a.Jwb})};SzB=async function(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const f=a.oa;if(!(f.length<2||f.at(-1).Mf<7)){var d=f.at(-2);if(!d.L4.signal.aborted&&d.Mf<7)try{d.F6a=1;var e=d.xja;e.mode!==1&&(e.mode=1,e.xja=new BzB);d.NIa=7;b(await c(RzB(a,{client:d})))}catch(g){b()}}}finally{c()}};
EzB=async function(a,b,c,{Xtb:d=!1,IPc:e}={}){var f=(0,_.Qf)(),g=f();f=f(1);try{if(d||b===CzB(a)){var h=d?0:UzB(a,b,c),k=PzB(a,h);d?CyB(a.oa,!0,h):b.oza=!1;e&&(a.Ba=e);var l=a.oa.slice(h);KzB(a,h);var p=LzB(a,k);f(await g(IzB(a)));f(await g(p));if(e){const q=l.map(r=>r.JX.promise);f(await g(Promise.all([e.promise,...q])))}if(!CzB(a)){const q=document.head.querySelector('link[rel="canonical"]');q&&document.head.removeChild(q)}}}finally{g()}};
PzB=function(a,b){let c=0;for(;b<a.oa.length;b++)a.oa[b].Hqa&&c++;return c};HzB=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{const e=b.qq;e&&(e.style.display="");b.NIa=7;c(await d(RzB(a,{client:b,rG:new _.H$p})));(0,_.dNa)(()=>void SzB(a))}finally{d()}};VzB=function(a,b){return(b=XyB(b,YyB(b,a.oa)))?_.IL(b):syB(a.Pe)};
MzB=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{const k=CzB(a);if(k){_.UDe&&k.interactionVed&&_.Ep(a.Pe.oa(),new _.Nh(k.interactionVed)).log();if(b){k.F6a=4;var e=k.xja;var f=a.Pe;if(mzB)var g=mzB;else{var h=_.Ie(_.ym("iGkMSe"));g=mzB=_.v6h(f,251479,h)}yzB(e,g,VzB(a,k));document.dispatchEvent(new CustomEvent("viewerOpened"))}else k.F6a=5,yzB(k.xja,syB(a.Pe),VzB(a,k));c(await d(HzB(a,k)))}}finally{d()}};
DzB=function(a,b,c,d){let e=null;if(c===1){let f,g;e=((f=b.plugin)==null?void 0:(g=f.VV)==null?void 0:g.call(f))||null}else if(c===2){let f,g;e=((f=b.plugin)==null?void 0:(g=f.LTa)==null?void 0:g.call(f))||null}e||(e=d.targetElement.hb());_.Fp(a.Pe.oa(),e,3).log()};LzB=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{b>0&&(c(await d(a.xi.go(-b))),_.Vg(document.body,"nOJPYb"))}finally{d()}};UzB=function(a,b,c){b=wyB(c,b.UX);switch(b){case 1:return a.oa.length-1;case 2:return 0;default:return _.$a(b)}};
WzB=function(a,b){let c,d,e;const f=(e=(c=b.plugin)==null?void 0:(d=c.w4a)==null?void 0:d.call(c))!=null?e:JzB(a,b);(0,_.Ef)(()=>{a.Pe.logEvent({ef:new _.Nh(f,21)})})};JzB=function(a,b){if(b.ffb)return b.ffb;const c=_.UHb(b.qq);return b.ffb=_.v6h(a.Pe,3593,c)};
_.XzB=class extends _.ko{static Ta(){return{service:{overlay:_.sv,history:_.iyr,Vf:_.Pu,logging:_.Hu,mZ:_.ZZA,jJ:_.k1r,kna:_.jyB}}}constructor(a){super();this.Aa=-1;this.Ba=null;this.Jwb={isActive:c=>c===CzB(this),iOc:c=>!izB.includes(c.contentPluginType),jQc:c=>{const d=IyB({client:c,SMa:this.SMa,Hne:!0,Jne:!0,root:YyB(c,this.oa)});GzB(this,c,d);YyB(c,this.oa)&&d.classList.add("L3JeZd");_.u6h(d);return d},lQc:c=>{var d=c.plugin;d=izB.includes(c.contentPluginType)?d.m9d():IyB({client:c,SMa:this.SMa,
root:YyB(c,this.oa)});GzB(this,c,d);YyB(c,this.oa)&&d.classList.add("L3JeZd");_.u6h(d);return c.qq=d},S4c:c=>this.Qda(c.contentPluginType),Woc:async(c,d)=>{var e=(0,_.Qf)(),f=e();e=e(1);try{c.plugin=e(await f(d.Zw(c.content,g=>this.Qda(g))))}finally{f()}},xUc:async c=>{var d=(0,_.Qf)(),e=d();d=d(1);try{const f=c.plugin,g=c.L4;let h;d(await e((h=f.fetch)==null?void 0:h.call(f,{signal:g.signal})))}finally{e()}},qz:c=>{const d=c.plugin,e=c.qq,f=c.L4,g=c.Rw,h=c.header,k=c.xja;let l={gC:!1,kA:!1};if(d.PPc){let p,
q;const r=(q=(p=d.qaf)==null?void 0:p.call(d))!=null?q:new Map;d.PPc(this.yr(),u=>this.Qda(u),r)}d.qz!=null&&(l=d.qz({Oj:e,signal:f.signal,bB:p=>void k.bB(p)}),l.gC&&(g==null||g.remove(),h==null||h.remove()));l.kA&&c.uFb&&TyB(e);return l.kA},render:async c=>{var d=(0,_.Qf)(),e=d();d=d(1);try{const f=c.plugin,g=c.qq,h=c.L4,k=c.Rw,l=c.header,p=c.xja;k==null||k.remove();l==null||l.remove();f.render!=null&&d(await e(f.render({Oj:g,signal:h.signal,bB:q=>void p.bB(q)})));if(_.CDe&&!g.querySelector('[jsname="OXxrqc"]')){const q=
document.body.querySelector('[jsname="yloBKd"]');(q==null?0:q.firstElementChild)&&g.appendChild(q.firstElementChild.cloneNode(!0))}(0,_.cNa)().then(()=>{_.Gq()})}finally{e()}},pwc:async(c,d)=>{var e=(0,_.Qf)(),f=e();e=e(1);try{e(await f(UyB(c,this.oa,this.Ef,this.Hm,this.Ca,this.onDismiss(c),d)));const l=this.oa,p=l.indexOf(c);if(p!==-1){var g=CzB(this);for(d=0;d<p;d++){const q=l[d],r=q.qq;r&&(r.style.display="none");gzB(q,g)}var h=c.plugin,k=c.qq;gzB(c,g);FzB(k,c,!("function"==typeof _.b9h&&h instanceof
_.b9h)&&_.DB)}}finally{f()}},lyc:c=>{WyB(c,this.oa,this.xi)}};this.Ef=a.service.overlay;this.xi=a.service.history;this.Hm=a.service.Vf;this.Pe=a.service.logging;this.SMa=a.service.mZ;this.Ca=a.service.jJ;if(MyB){var b;let c,d;(b=window.google)==null||(c=b.zl)==null||(d=c.qsvd)==null||d.call(c)}this.isRtl=document.body&&_.je(document.body);a=this.xi.get();b=a.Hqa||a.url||[];this.oa=b.map(ByB);IzB(this).catch(()=>{});a.url&&(this.xi.update([],{replace:!0}),a.url.length>0&&this.xi.update(b,{replace:!1}));
(a.Hqa||a.url)&&ezB();this.xi.addListener((c,d)=>{NzB(this,c,d).catch(()=>{})});document.addEventListener("viewerGuestClose",()=>{KzB(this,0);OzB(this,{replace:!1}).catch(()=>{})});_.Pg(document.body,"gZgazf",this.KKa,this)}Ml(){var a=this.xi;if(_.Zxr())var b=_.kEe.If();else{var {Hqa:c,url:d}=a.get();a=(b=c==null?void 0:c.at(-1))!=null?b:d==null?void 0:d.at(-1);b=new _.Wt(_.kEe.If());a?(b.pathname=`/searchviewer/${a.viewerType}`,b.searchParams.set("svid",_.byr(a,void 0,!0)),b.searchParams.delete("q"),
b.searchParams.delete("udm"),b.oa.delete("sv"),b=b.toString()):b=null}return b}Vlc(){var a;{const {Hqa:d,url:e}=this.xi.get(),f=(a=d==null?void 0:d.at(-1))!=null?a:e==null?void 0:e.at(-1);f?a=_.ayr(f,void 0,_.Zxr()):(_.Zxr(),a=null)}let b,c;return{content:(b=a==null?void 0:_.Qb(a.getContent()))!=null?b:new Uint8Array(0),contentPluginType:(c=a==null?void 0:a.getContentPluginType())!=null?c:null}}async prefetch(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const d=b(await c(this.IYb(a)));b(await c(Promise.all(d.map(async e=>
{let f;return await ((f=e.prefetch)==null?void 0:f.call(e))}))))}finally{c()}}async IYb(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const d={};a.forEach(f=>{d[String(f)]=hzB[f]});const e=b(await c(_.Yf(this,{service:d})));return Object.values(e.service)}finally{c()}}async Qda(a){return await _.Zf(hzB[a],this.yr())}async showViewerLite(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const d=this.Qda(a.contentPluginType);let e;const f=b(await c(d));if(a.mLb){const g=_.Z5h(a.entrypoint);if(!g)throw Error("IA`"+a.entrypoint);
const h=b(await c(f.Zw(a.ysa,l=>this.Qda(l),{index:_.f6h(g,a.entrypoint),count:g.u5()}))),k=b(await c(this.Qda(3)));e=b(await c(k.getInstance({index:_.f6h(g,a.entrypoint),v6a:h,lN:g})))}else e=b(await c(f.Zw(a.ysa,g=>this.Qda(g))));b(await c(this.showViewer({yy:e,TX:a.TX,entrypoint:a.entrypoint,interactionVed:a.interactionVed,rG:void 0,lE:a.lE,fsa:a.fsa,viewerType:a.viewerType,nZ:a.nZ,shellStyleClass:a.shellStyleClass,UX:a.UX,source:a.source,contentId:a.contentId,uca:a.uca,RZa:a.RZa})))}finally{c()}}async showViewer(a){var b=
(0,_.Qf)(),c=b();b=b(1);try{let d,e;if(MyB&&((d=window.google)==null?0:(e=d.zl)==null?0:e.qsvoc))return window.google.zl.qsvoc--,Promise.reject(new _.ina("search-viewer: quick viewer was closed"));a.TX!=null&&_.k9h(a.TX);let f;a.rG||(a.rG=_.I$p((f=a.entrypoint.getAttribute("data-ep-type"))!=null?f:"",a.TX));fzB(a);const g=a.entrypoint,h=a.fsa,k=this.oa;this.Aa=-1;if(ZyB(a,k)){let q,r;return Promise.resolve((r=(q=CzB(this))==null?void 0:q.qq)!=null?r:null)}const l=$yB(g,k),p=h?Math.max(0,l):l+1;if(p<
k.length){let q;const r=_.Nvh(async()=>{var u=(0,_.Qf)(),A=u();u=u(1);try{const E=h?k[p].entrypointId:void 0;u(await A(QzB(this,p)));q=TzB(this,a,!0);const I=CzB(this);I.replacedEntrypointId=E;u(await A(I.rNa.promise))}finally{A()}},{root:{group:{styles:{animationDuration:"150ms"}}}});b(await c(r.updateCallbackDone));return q}return TzB(this,a,!1)}finally{c()}}KKa(a){a=a.data;if(typeof a!=="boolean"){var b=a.IPc;if(a.Xtb)this.oa.length===0?b==null||b.resolve():EzB(this,this.oa[0],0,a).catch(c=>{b&&
b.reject(c)});else if(b){const c=CzB(this);c?EzB(this,c,0,a).catch(d=>{b.reject(d)}):b.resolve()}}}HTa(){const a=CzB(this);let b="";try{if(a==null?0:a.qq)for(const f of a.qq.querySelectorAll("[data-sv-ctx]"))b+=" "+(f.textContent||"");let c,d;const e=(a==null?void 0:(c=a.plugin)==null?void 0:(d=c.HTa)==null?void 0:d.call(c))||new Map;e.has("prompt_text")||(b=b+" "+(e.get("prompt_text")||""));e.set("prompt_text",b);return e}catch(c){}return null}Ch(a,{content:b,entrypoint:c}){if(!a.L4.signal.aborted&&
a===CzB(this)){var d=!1;c&&c!==a.entrypoint&&(d=!0,a.entrypoint=c,a.entrypointId=_.V5h(c),czB(a));azB(a.content,b)||(d=!0,a.content=b);d&&a.Hqa&&OzB(this,{replace:!0})}}onDismiss(a){return({JX:b,eventType:c})=>{if(!this.oa.includes(a))return a.JX.resolve(b),!0;if(a!==CzB(this))return!1;a.JX.resolve(b);a:switch(c){case 2:b=3;break a;case 0:b=4;break a;default:b=0}EzB(this,a,b).catch(()=>{});WzB(this,a);return!0}}};_.$f(_.g1a,_.XzB);

_.x();
_.zBq=_.y("qCgt4c",[_.g1a]);
_.v("qCgt4c");
_.Yr(_.zBq,class extends _.Wr{static Ta(){return{service:{w9:_.XzB}}}constructor(a){super();this.Sg=a.service.w9}});
_.x();
_.v("QFOGlf");
_.LEr=new _.Vf(_.d3a);
_.x();
_.llq=_.y("YlQIHe",[_.d3a]);
_.v("YlQIHe");
_.Yr(_.llq,class extends _.Wr{static Ta(){return{service:{copy:_.LEr}}}constructor(a){super();let b;a.service.copy.setLoggingElement(((b=this.qb("W2GRoe"))==null?void 0:b.el())||void 0)}});
_.x();
_.X0o=_.y("I9y8sd",[]);
_.v("I9y8sd");
var Y0o=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},Z0o=function(){return google.lfm&&google.lfm.some(a=>a.ie())},$0o=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},a1o=function(a,b,c,d,{logError:e}){d=_.bf(d);b=`${b}-${c}-${_.gna(d)}`;const f=a.get(b),g=_.cf(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.gna(d)}`;(d=_.cf(d,"ck"))&&
(h=`${h}.ck=${d}`);e(Error("br`"+JSON.stringify({type:c,Fhf:h,Wef:f,Aef:g})))}a.set(b,g)}},c1o=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;b1o.push(a)}},d1o={name:"umods"},e1o=!!(_.Gi[18]>>22&1),f1o=!!(_.Gi[18]>>23&1),g1o=!!(_.Gi[18]>>24&1),h1o=!!(_.Gi[18]>>25&1),i1o=!!(_.Gi[18]>>26&1),j1o=!!(_.Gi[18]>>27&1),k1o=!!(_.Gi[18]>>28&1);var l1o=["google.com","youtube.com","ampproject.org","adtrafficquality.google",(new URL(location.href)).host];var b1o=[],m1o=[],n1o=class extends _.Wr{static Ta(){return{}}constructor(){super();this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Yn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of b1o)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of m1o)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.df(b,{level:0,zf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});f1o&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.nm.HA)()}`,"")}sample(a,b){((a.Khf?Math.random():this.Ca)<(a.sampleRate||0)||e1o)&&b()}};n1o.prototype.$wa$rT3LBf=function(){return this.Ba};
c1o({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of l1o)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("cr"),b)}},toggle:h1o});
c1o({name:"hp",run:function({logError:a}){if(!Y0o()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=$0o(d);if(e){const f=d;(0,_.Yn)(()=>{e===$0o(f)&&a(Error("dr"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:g1o});
c1o({name:"sp",run:function({logError:a}){var b;if(b=!Y0o())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none")&&!Z0o();if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("er"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:g1o});
c1o({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("fr"))},toggle:i1o});
c1o({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.wg("s",d1o);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&a1o(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&a1o(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&a1o(d,c,"comburl",g,{logError:a})}}}},toggle:k1o});
var o1o={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:j1o};if(o1o.toggle){var p1o;o1o.sampleRate=(p1o=o1o.sampleRate)!=null?p1o:1;m1o.push(o1o)}_.Yr(_.X0o,n1o);
_.x();
});
// Google Inc.
