loaded_h_0(function(_){var window=this;
_.bWb=_.y("rtH1bd",[_.y7a]);
var XVb,YVb;_.WVb=function(a){return JSON.stringify(a,(b,c)=>c instanceof Map?Object.fromEntries(c):c)};XVb=function(a,b,c,d){const e=()=>d?a.pop(d,!0):_.zh(),f=()=>c!==d;return b?{bmc:e,uRc:f,Ezc:2}:{bmc:e,uRc:f,q5a:()=>c?a.pop(c,!0):_.zh(),Ezc:6}};YVb=function(a,b){return{bmc:()=>a.Aa(b.iD())||_.zh(),uRc:()=>!0,Ezc:2}};_.ZVb=a=>new _.Wt(a);_.ZVb=a=>new _.Xt(a);_.$Vb=class{constructor(){this.oa=new Map}and(a,...b){return a.call(null,...b,this)}};_.aWb=class{constructor(a,b,c){this.Aa=c;this.converters=a;this.oa=b}nSa(a,{A_a:b={},yfa:c}={}){const d=this.oa.getState()||{id:"",pushId:""};var e=this.Aa||d;e={url:_.ZVb(e.url||""),state:e.userData||null};const f=e.url.toString(),g=_.WVb(e.state);for(const k of this.converters.keys())if(a.has(k)){const l=a.get(k);this.converters.get(k).zp(l,e)}const {replace:h=!1}=b;if(f===e.url.toString()&&g===_.WVb(e.state))return _.Dg(XVb(this.oa,h,d.id,d.id));this.Aa&&(this.Aa.url=e.url.toString(),this.Aa.userData=
e.state);if(!b.ojf)return c?(a=this.oa.navigateToView(e.url.toString(),e.state||void 0,c.Bpa,h,c.event))?a.then(k=>YVb(this.oa,k)):_.zh(Error("Cf`"+e.url)):this.oa.pushAsync(e.url.toString(),e.state||void 0,void 0,h,this.oa).then(k=>XVb(this.oa,h,d.id,k))}static compose(...a){const b=new Map;let c,d;for(const e of a){for(const f of e.converters.keys())b.delete(f),b.set(f,e.converters.get(f));c=e.oa;d=e.Aa}return new _.aWb(b,c,d)}};
_.v("rtH1bd");
var cWb,eWb,gWb,iWb,jWb,kWb,lWb,mWb,nWb;cWb=function(a,b=[]){b.push(a);return b};_.dWb=function(a,b){const c=new Map;for(const e of a)for(const f of e.keys()){a=f;var d=e.get(f);d=b?b(d,c.get(a)):d;c.set(a,d)}return c};eWb=function(a,b){const c=new Map;for(const d of a.keys())c.set(d,b(a.get(d),d));return c};_.fWb=function(a){return _.qg(a)?a:{}};gWb=function(a,b){const c=b.reduce((d,e)=>d|(e&&e.Ezc||0),1);return Object.assign({state(d){return(a.get(d)||new d).clone()},JBb(d){return(c&d)===d}},...b)};
iWb=function(a,b=hWb){return{getCurrent:a.getCurrent||b.getCurrent,Nza:new Set([...b.Nza,...a.Nza]),W$a:a.W$a||b.W$a}};jWb=function(a){a=_.dWb(a,cWb);return eWb(a,(b,c)=>c.compose(...b))};kWb=function(a){const b=[];for(const c of a)(a=c())&&b.push(a);return b.length?_.Ch(b):null};lWb=function(a,b){const c=new Set,d=new Set([...a.keys(),...b.keys()]);for(const e of d)_.Ja(a.getAll(e),b.getAll(e))||c.add(e);return c};
mWb=function(a,b){var c;if(c=!!a&&!!b)a:{a.size>b.size&&([a,b]=[b,a]);for(const d of a)if(b.has(d)){c=!0;break a}c=!1}return c};nWb=function(a=new _.$Vb){a.oa.set(_.aWb,null);return a};var hWb;hWb={Nza:new Set};_.pWb=function(...a){const b=[];var c=[],d=[];let e;for(const f of a)b.push(f.Sn),c.push(f.wT),d.push(f.pvc),e=f.Qub||e;a=_.dWb(b,iWb);c=jWb(c);d=jWb(d);return new _.oWb(a,c,d,e)};
_.oWb=class{constructor(a=new Map,b=new Map,c=new Map,d){this.Sn=a;this.wT=b;this.pvc=c;this.Qub=d}run({Aa:a,eventType:b,metadata:c,oa:d}=new _.$Vb){const e=new Map;for(const h of this.Sn.keys()){const k=this.Sn.get(h);let l,p,q,r=(q=(p=(l=k).getCurrent)==null?void 0:p.call(l))!=null?q:new h;var f=null;for(const u of k.Nza){const A=u;if(A.Ced){if(!A.Ced(r.clone(),a))continue;f=A.Bje}else f=u;f=r=f(r,a)}if(f){e.set(h,f);let u,A;(A=(u=k).W$a)==null||A.call(u,f)}}a=[];for(var g of this.wT.keys()){const h=
this.wT.get(g),k=d.get(g);k!==null&&a.push(()=>h.nSa(e,k))}d=h=>{b=b||this.Qub;const k=[],l=gWb(e,h);for(const p of this.pvc.values())k.push(()=>p.notify(e,b,c,l));return(h=kWb(k))?h.then(()=>l):_.Dg(l)};return(g=kWb(a))?g.then(d):d([])}compose(...a){return _.pWb(this,...a)}};_.qWb=class extends _.ko{static Ta(){return{service:{RHc:_.zIb}}}constructor(a){super();this.Ba=[];this.Aa=a.service.RHc;a=this.Aa.getState()||{};this.oa={url:a.url,userData:a.userData,id:"",pushId:""};this.Aa.addListener((b,c,d)=>{if(!(d.source instanceof _.zIb)){if(b.url!==this.oa.url){var e=new _.Wt(b.url||"");c=new _.Wt(this.oa.url||"");var f=lWb(e.searchParams,c.searchParams);e=lWb(e.oa,c.oa)}c=_.fWb(b.userData);var g=_.fWb(this.oa.userData);if(c===g)var h=new Set;else{var k=new Set,l=new Set([...Object.keys(c),
...Object.keys(g)]);for(h of l)_.WVb(c[h])!==_.WVb(g[h])&&k.add(h);h=k}this.oa.url=b.url;this.oa.userData=b.userData;c={url:_.ZVb(b.url||""),state:b.userData};b=[];for(const {xJd:p,YRd:q}of this.Ba)g=new Set,k=new Set,l=new Set,q.oa&&(q.oa.C6&&(g=new Set(q.oa.C6())),q.oa.vC&&(k=new Set(q.oa.vC()))),q.Aa&&(l=new Set(q.Aa.keys())),(mWb(g,f)||mWb(k,e)||mWb(l,h))&&b.push(p(c));b.length&&(f=d.x6&&d.x6.length?1:0,d=d.source instanceof _.Kgb,e=_.pWb(...b),b=e.run,h=new _.$Vb,h.metadata={reason:f,userInitiated:d},
b.call(e,h.and(nWb)))}})}};_.$f(_.bWb,_.qWb);
_.x();
_.wqr=null;
var hjd,ljd;_.ijd=function(){hjd.set(_.Yt().toString(!0),_.Am())};_.jjd=function(){return hjd.get(_.Yt().toString(!0))};_.kjd=function(){const a=_.jjd();a&&_.RD.fixedUiScrollTo(a.x,a.y)};_.mjd=function(){ljd||(ljd=_.ne(document.documentElement,"touchmove",_.CJa));document.body.style.overflow="hidden"};_.njd=function(){ljd&&(_.rn(ljd),ljd=null);document.body.style.overflow=""};_.ojd=function(a){a&&_.RD.Ca(0,a)};hjd=_.wg("s",_.BNa);_.pjd=null;ljd=null;_.ne(window,"popstate",function(){_.pjd=_.Am()});
var xjd,Ejd,Mjd,wjd,Tjd,Vjd,Njd,Zjd,akd,Ljd,Xjd,ckd,ujd,vjd,Ujd,Wjd,Bjd,Fjd,Yjd,Gjd,tjd,Kjd,Qjd,$jd,Cjd;_.qjd=function(a,b,c){_.ijd();b=b||{};b.fpstate=a;_.Ag(b,c)};_.sjd=function(a){_.rjd(!0,a)};_.rjd=function(a,b){const c={};_.Ka(b||[],d=>{c[d]=""});c.fpstate="";_.Ag(c,a)};
_.Ajd=function(a,b){tjd++;if(window.getSelection){const f=window.getSelection();f&&f.removeAllRanges()}let c=!1,d=!1;_.Ka(a,f=>{if(f===1)_.Fg("trex")?d=!0:c=!0;else{var g=_.Jg(f);if(g!==document.body){var h=f["fp-s"];h||(h=_.Em("DIV"),f["fp-s"]=h);g?_.Jm(h,f):(g=_.Jg(h))&&g.removeChild(h);_.CJc(f,f);document.body.appendChild(f)}_.Um(f,{"margin-top":-_.RD.getHeaderPaddingHeight()+"px","margin-bottom":-_.RD.getFooterPaddingHeight()+"px"});f["fp-i"]=tjd;_.om.remove(f,"fCjVlb");_.tJc(f,"t3L5Dd")}});_.Ka(document.body.children,
f=>{if(!(ujd.has(f.tagName)||vjd.test(f.id)||f.id==="lb"||f["fp-i"]===tjd||f.hasAttribute("data-imig")))if(_.om.remove(f,"r3xA2d"),f&&f["fp-i"]>0){wjd(f);const g=f["fp-s"];g&&f&&f["fp-i"]>0&&(g.parentNode?(_.Jm(f,g),_.Lm(g)):_.Lm(f));f.parentNode!==document.body||_.om.add(f,"fCjVlb")}else _.om.enable(f,"fCjVlb",!c),f&&f.id.startsWith("trex_")&&_.om.enable(f,"fCjVlb",!d)});let e;((e=google)==null?0:e.uh)?google.uh("fpstate"):_.hn(document.body,"");b!==!1&&(c&&!xjd()?_.yjd():_.zjd())};
xjd=function(){const a=_.om.contains(document.body,"qs-i"),b=!!_.Fg("istate"),c=!!_.Fg("trex"),d=_.Fg("oshop")==="apv";return a||c||b||d};Ejd=function(a){if(a===Bjd)return Cjd;let b=_.Djd[Bjd+"\n"+a];return b?b:Bjd==="&"?Cjd:(b=_.Djd["*\n"+a])?b:(b=_.Djd[Bjd+"\n*"])?b:Cjd};
Mjd=function(a){var b=Fjd;b=b===1?b:b;if(Gjd!==1){var c=Gjd;c.style.top="";_.om.remove(c,"ca1MEe")}_.Ajd([b],!1);(c=_.Hjd.get(Bjd))&&c.Era&&c.Era.call(null);if(c=b===1?null:b)_.om.add(document.body,"QjZ1Sd"),_.om.add(c,"ca1MEe"),_.om.remove(c,"r3xA2d"),c.focus();if(_.Ijd){const f=_.Ijd;var d=f.x,e=f.y+_.RD.getScrollTop();_.RD.fixedUiScrollTo(d,e);c&&(f.x&&(c.style.left=""),f.y&&(c.style.top=""))}else _.Jjd!==1&&(c=_.RD.getScrollTop(),_.RD.fixedUiScrollTo(0,c));_.Ijd=null;b!==1||xjd()?_.fjd||_.ola||
_.nla||_.zjd():_.yjd();Bjd=a;Gjd=b;Fjd=null;Kjd&&(_.rn(Kjd),Kjd=null);_.njd();Ljd();(a=_.Hjd.get(a))&&a.anb&&a.anb.call(null)};_.yjd=function(){if(_.mla)_.RD.oa(1);else{const a=_.eg(document);_.Zf(_.Pu,a.yr()).then(b=>{b&&b.isAvailable()&&b.exitBasicMode(12)})}};_.zjd=function(){if(_.mla)_.RD.oa(3);else{const a=_.eg(document);_.Zf(_.Pu,a.yr()).then(b=>{b&&b.isAvailable()&&b.enterBasicMode(12)})}};wjd=function(a){_.Um(a,{"margin-top":"","margin-bottom":""})};
Tjd=function(a){if(a===""){_.Fg("istate")&&_.Bg("istate",_.Fg("istate"),!0);var b=_.Yt().pathname();b!=="/search"&&(b=Njd(b))&&(b=_.Ojd.get(b))&&(a=b.state)}a!==_.Pjd&&(_.Pjd=a,a===""||_.Hjd.has(a))&&(Qjd?(b=()=>void _.Sjd(a),Qjd.promise.then(b,b)):_.Sjd(a))};Vjd=function(a){return a&&(a=Ujd.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};Njd=function(a){return(a=Wjd.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};
Zjd=function(a){a=a.Ph;const b=Vjd(a.newURL);if(b===_.Pjd){const c=Vjd(a.oldURL);/#(.*&)?trex=/.test(a.oldURL)||c===b||Xjd()||!Yjd||(a=Yjd,_.RD.fixedUiScrollTo(a.x,a.y))}};_.Sjd=function(a){if(Bjd==="&"&&a==="")Bjd=a;else if((0,_.Wn)(new $jd),a==="")akd(a,1),_.tJc(document.body,"ABuafc");else{Bjd===""&&_.tJc(document.body,"hcY69");var b=_.Hjd.get(a);if(b&&(b=b.gea.call(null,Bjd))){_.Ng(b)?akd(a,b):b.then(c=>{akd(a,c)},()=>{Ljd()});return}Ljd()}};
akd=function(a,b){const c=Ejd(a),d=typeof c.transitionType==="function"?c.transitionType(Bjd,a,c.tFc):c.transitionType;var e=b===1;const f=d!==1||Gjd===1?null:Gjd,g=d!==0||b===1?null:b;Fjd=b;_.Jjd=d;Yjd=_.Am();if(f){const k=Yjd;bkd(f,b);f.style.top=_.RD.getScrollTop()-k.y+"px"}g&&bkd(g,Gjd);e&&_.om.remove(document.body,"QjZ1Sd");!e&&(_.fjd||_.ola||_.nla)&&_.zjd();Kjd||(Kjd=_.ne(document.documentElement,"touchstart",_.CJa));_.mjd();if((e=_.Hjd.get(a))&&e.onReady)try{e.onReady.call(null)}catch(k){ckd(k);
return}d===1?_.kjd():d===0&&a!==""&&Bjd!==""&&(_.Ijd=_.jjd(),Yjd=null);let h;try{h=c.tFc.call(null,Gjd,b)}catch(k){}h?(h.then(()=>{Mjd(a)},k=>{Mjd(a);throw k;}),g&&_.Ijd&&(b=_.Ijd,b.x&&(g.style.left=-b.x+"px"),b.y&&(g.style.top=-b.y+"px"))):Mjd(a)};Ljd=function(){Qjd&&(Qjd.resolve(),Qjd=null)};Xjd=function(){if(_.Jjd!=null){var a=_.Jjd===1;if(_.Ijd){if(a||Fjd===1){var b=_.Ijd;a=b.x;b=b.y+_.RD.getScrollTop();_.RD.fixedUiScrollTo(a,b);return!0}}else if(a)return!0}return!1};
ckd=function(a){_.Jjd=Fjd=null;_.Ajd([Gjd]);Kjd&&(_.rn(Kjd),Kjd=null);_.njd();Ljd();throw a;};ujd=new Set(["SCRIPT","STYLE"]);vjd=RegExp("^(abbl|abblt|gbbl-\\d+|gbblt-\\d+|snbc|duf3c)$");Ujd=/#(?:.*&)?fpstate=([^&]*)/;Wjd=/^\/?([^\/]*)/;_.Hjd=new Map;_.Ojd=new Map;Bjd="&";_.Pjd="&";Fjd=null;Yjd=null;_.Ijd=null;_.Djd={};_.Jjd=null;Gjd=1;tjd=0;Kjd=null;Qjd=null;$jd=class{constructor(){this.s6a=void 0;Qjd=_.Df()}play(){return Qjd?Qjd.promise:Promise.resolve()}finish(){Ljd()}Rm(){return 2E3}};
Cjd={tFc:function(){return _.Dg()},transitionType:0};_.Coa(()=>{_.yg("fpstate",Tjd);_.ne(window,"hashchange",Zjd)});var bkd=function(a,b){_.Ajd([a,b],!1);wjd(a);_.om.add(a,"r3xA2d")};
_.Hw=function(a,b=new _.$Vb){const c=b.oa.get(_.aWb)||{};c.A_a=a;b.oa.set(_.aWb,c);return b};
var tWb,xWb,zWb,AWb,BWb;tWb=function(a,b=new Set){for(const c of a)b.add(c);return b};_.uWb=function(a,b){return b};_.vWb=function(a,b=new _.$Vb){b.Aa=a;return b};_.qw=function(){return _.Zf(_.qWb)};_.wWb=function(a,b,c,d){return new _.aWb(new Map([[a,b]]),c,d)};
xWb=class{constructor(a=new Map){this.oa=a}notify(a,b,c,d){for(const e of a.keys())if(this.oa.has(e))for(const f of this.oa.get(e))try{f(a.get(e).clone(),b,c,d)}catch(g){_.fa(g)}}static compose(...a){const b=[];for(const c of a)b.push(c.oa);a=_.dWb(b,tWb);return new xWb(a)}};
_.yWb=function(a,{getCurrent:b,Nza:c=[],W$a:d,wT:e=[],listeners:f=[],pvc:g=[],Qub:h}={}){const k=new Map;for(const l of e)k.set(l.constructor,l);e=new Map;f&&e.set(xWb,new xWb(new Map([[a,new Set([...f])]])));for(const l of g)e.set(l.constructor,l);return new _.oWb(new Map([[a,{getCurrent:b,Nza:new Set(c),W$a:d}]]),k,e,h)};
_.rw=class{constructor(a,b,c={}){this.oa=a;this.Aa=b;this.Ba=c.tUb||(d=>_.qg(d)?d:{});this.Ca=c.R2b||((d,e)=>e)}Bo(a,b){this.oa&&this.oa.Bo&&this.oa.Bo(a.url,b);this.Aa&&this.Aa.Bo(this.Ba(a.state),b)}zp(a,b){this.oa&&this.oa.zp&&this.oa.zp(a,b.url);if(this.Aa){const c=Object.assign({},this.Ba(b.state));this.Aa.zp(a,c);a=Object.assign({},_.qg(b.state)?b.state:{});b.state=this.Ca(a,c)}}};zWb=function(a){const b=a.Aa.getState()||{};return{url:_.ZVb(a.Aa.getCurrentUrl()),state:b.userData}};
AWb=function(a,b){a.Ba.push(b)};
_.sw=function(a,b,c){const d=b.Er();b.Da(_.wWb(d,c,a.Aa,a.oa));b.Pa(h=>{const k=zWb(a);c.Bo(k,h)});let e=!1;const f=new d,g=_.yWb(d,{Nza:[h=>{const k=zWb(a);c.Bo(k,f);c.Bo(k,h);return h}],listeners:[()=>{e||(e=!0,AWb(a,{xJd:h=>b.transition(k=>{c.Bo(h,k);return k},"IaLTGb"),Qke:h=>{const k=new d;return b.Ma(l=>{if(!c.oa)return!1;const p=_.ZVb("");let q,r;(r=(q=c.oa).zp)==null||r.call(q,l,p);h(p);let u,A;(A=(u=c.oa).Bo)==null||A.call(u,p,k);return!_.Lk(k,l)},()=>k,"IaLTGb")},YRd:c}))}]});b.Ha(g)};
BWb=function(a,b,c){a.listeners.set(b,c);return a};_.tw=function(a,b,c){BWb(a,c,(d,e,f,g)=>{b===e&&c(d,f,g)})};
_.uw=class{constructor(a){this.Aa=a;this.state=new this.Aa;this.wT=new Set;this.listeners=new Map;this.Ia=new Set;this.Ba=()=>{const b=this.state.clone();for(const c of this.Ia)c(b);return b};this.Ca=b=>{this.state=b};this.La=(b,c,d,e)=>{for(const f of this.listeners.values())try{f(b.clone(),c,d,e)}catch(g){_.fa(g)}};this.oa=_.yWb(this.Aa,{getCurrent:this.Ba,listeners:[this.Ca]})}Er(){return this.Aa}listen(a){return BWb(this,a,a)}unlisten(a){this.listeners.delete(a)}get(){return this.Ba()}transition(a,
b="E8jfse"){return _.yWb(this.Aa,{getCurrent:this.Ba,Nza:[a],W$a:this.Ca,wT:this.wT,listeners:[this.La],Qub:b})}Ma(a,b,c="E8jfse"){return _.yWb(this.Aa,{getCurrent:this.Ba,Nza:[{Ced:a,Bje:b}],W$a:this.Ca,wT:this.wT,listeners:[this.La],Qub:c})}initialize(a=new Map){if(!this.oa)return Promise.resolve();var b=this.oa,c=b.run,d=new _.$Vb;d.eventType="sKlcvd";a=c.call(b,d.and(_.vWb,a));this.oa=null;return a}Ha(a){this.oa&&(this.oa=this.oa.compose(a))}Da(a){this.wT.add(a)}Pa(a){this.Ia.add(a)}};_.vw=class{constructor(a){const b=_.yWb(a.Er(),{Nza:[(c,d)=>(d=d.get("R84DPe")||null)?d.clone():c]});a.Ha(b)}};
var xqr=class{constructor(){this.oa=[]}async run(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{if(a.length){var e=a[0];for(let g=1;g<a.length;g++)e=e.compose(a[g]);var f=c(await d(e.run(_.Hw({replace:!!b}))));f.JBb(4)&&this.oa.push(f)}}finally{d()}}goBack(){return this.oa.length>0?this.oa.pop().q5a():_.Dg()}};var Bqr,Cqr,zqr,yqr;_.Aqr=function(a,b){yqr==null&&(yqr=new zqr(a,b));return yqr};Bqr=function(a){if(a=="")return{J6a:!0};var b=a.split(",");if(b.length<2)return{J6a:!1,pvb:null};a=b[0];const c=b[1];let d="";b.length>=2&&(d=b[2]);let e="";b.length>=3&&(e=b[3]);b=_.sm(c);let f=null;b&&(d||e)&&(f=b.querySelector(e?`[data-local-attribute=${e}]`:`[data-dtype=${d}]`));return{J6a:!1,entryPoint:a,Wja:c,widget:d,pvb:b,bmd:f,EMa:e}};
Cqr=function(a,b){return a.J6a!=b.J6a||a.entryPoint!=b.entryPoint||a.Wja!=b.Wja||a.widget!=b.widget||a.EMa!=b.EMa};
_.Dqr=function(a,b){var c=Bqr(a.oa),d=Bqr(b);if((Cqr(c,d)||a.Aa)&&!(b.indexOf("d3sbx")>=0))if(d.J6a){if(a.oa=b,a.Ca=!1,d=_.wqr)a.Aa?(a.Aa=!1,d.closeDialog(),d.mZa()):d.oLa()}else if(d.pvb){a.oa=b;a.Ca=!1;if(c.pvb){if((b=!c.J6a&&!d.J6a&&c.entryPoint==d.entryPoint&&c.Wja==d.Wja&&(c.widget!=d.widget||c.EMa!=d.EMa))&&d.widget)d.bmd&&(c=_.wqr)&&c.dob(d.bmd);else{c=a.Aa;a.Aa=!1;const e=_.wqr;e&&e.closeDialog();if(c){e&&e.mZa();return}}if(b)return}a.Ha=d.widget||"";a.Da=d.EMa||"";a=_.qJc(d.pvb);a.set("entry_point",
d.entryPoint);_.qz(d.pvb,{context:a})}else a.Ch(""),a.Ca=!0};_.Eqr=function(a,b){return a.yca.transition(c=>c.setValue(b))};_.Fqr=function(a,b){return a.pE.transition(c=>c.setPage(b))};
zqr=class{constructor(a,b){this.pE=a;this.yca=b;this.Da=this.Ha=this.oa="";this.Ca=this.Ia=this.Aa=!1;this.Ba=new xqr;this.yca.get().getValue().trim()&&(this.Ia=!0);this.yca.listen(c=>{this.pM(c)});this.pM(this.yca.get())}pM(a){(0,_.Ef)(()=>_.Dqr(this,a.getValue()))}async Ch(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{if(this.Ha){const h=document.querySelector(this.Da?"[data-local-attribute="+this.Da+"]":"[data-dtype="+this.Ha+"]");h&&(0,_.Ef)(()=>{const k=_.wqr;k&&k.dob(h)});this.Da=this.Ha=""}else{var e=
Bqr(this.oa),f=Bqr(a);if(Cqr(e,f)){this.oa=a;var g=this.pE.get().Aa();if(_.zw()||!(f.widget!=""&&f.widget!=void 0||g!=""&&g.startsWith("d3")))c(await d(this.Ba.run([_.Eqr(this,a)],!!b)));else{let h=f.widget||"";const k=f.Wja+"-"+h;_.Hjd.has(k)&&(h=k);_.ijd();c(await d(this.Ba.run([_.Eqr(this,a),_.Fqr(this,h)],!!b)))}}}}finally{d()}}La(){this.Aa=!0;this.Ba.goBack()}goBack(){return this.Ba.goBack()}};yqr=null;var Gqr=class extends _.m{constructor(a){super(a)}getValue(){return _.t(this,1)}setValue(a){return _.Zg(this,1,a)}clearValue(){return _.Qe(this,1)}hasValue(){return _.mh(this,1)}};Gqr.prototype.ob="bgmrdf";var Hqr={vC(){return["duf3"]},Bo(a,b){_.Yv(new _.gw(a.oa,b),"duf3",b.setValue,b.clearValue)},zp(a,b){_.aw(new _.gw(b.oa,a),a.hasValue,a.getValue,"duf3")}};var Iqr;Iqr=null;_.Jqr=class extends _.uw{constructor(a,b){super(a);new _.vw(this);_.sw(b,this,new _.rw(Hqr))}static Er(){return Gqr}static xs(a){return Iqr?Iqr:Iqr=_.qw().then(b=>{b=new _.Jqr(Gqr,b);b.initialize(a);return b})}};_.Wo.bgmrdf=_.Vo;
_.vDq=_.y("EkevXb",[]);
var BXb=class extends _.m{constructor(a){super(a)}Aa(){return _.t(this,1)}setPage(a){return _.Zg(this,1,a)}Ca(){return _.Qe(this,1)}Ba(){return _.mh(this,1)}};BXb.prototype.ob="OLea4d";var CXb={vC(){return["fpstate"]},Bo(a,b){_.Yv(new _.gw(a.oa,b),"fpstate",b.setPage,b.Ca)},zp(a,b){_.aw(new _.gw(b.oa,a),a.Ba,a.Aa,"fpstate")}};var DXb;DXb=null;_.EXb=class extends _.uw{constructor(a,b){super(a);new _.vw(this);_.sw(b,this,new _.rw(CXb))}static Er(){return BXb}static xs(a){return DXb?DXb:DXb=_.qw().then(b=>{b=new _.EXb(BXb,b);b.initialize(a);return b})}};_.Wo.OLea4d=_.Vo;
_.v("EkevXb");
_.Yr(_.vDq,class extends _.Wr{static Ta(){return{We:{pE:_.EXb,yca:_.Jqr}}}constructor(a){super();a=this.oa=_.Aqr(a.We.pE,a.We.yca);a.Ca&&_.Dqr(a,a.yca.get().getValue())}});

_.x();
_.whh=_.y("fCxEDd",[]);
_.v("fCxEDd");
_.xhh=class extends _.ko{constructor(){super();this.Fxa=null}};_.$f(_.whh,_.xhh);
_.x();
_.Gld=_.y("WlNQGd",[]);
_.Fld=function(a){const b=a.event.detail;return b&&b.type?b.type==="menu_item_selected":String(a.type)==="mMf61e"};
_.v("WlNQGd");
var Hld,Jld,Ild,Kld,Lld,Nld,Mld,Old,Qld,Pld;Hld=class{constructor(a,b,c){this.trigger=a;this.aza=b;this.nK=c}};Jld=function(a){var b=a.oa();_.Ka(b,c=>{const d=_.YD(a,c);if(d.isSelected()&&d.isEnabled())switch(d.getType()){case 2:Ild(a);d.Lk(!0);a.Da=c;break;case 3:d.Lk(!0);a.Ia.push(c);break;default:d.Lk(!1)}else d.Lk(!1)},a);b=b[0];_.YD(a,b).oa()&&b.setAttribute("tabindex","0")};_.YD=function(a,b){return a.cXa.find(c=>c.getRoot().el()===b)};Ild=function(a){a.Da&&(_.YD(a,a.Da).Lk(!1),a.Da=null)};
Kld=function(a,b,c=!1){if(b){const d=_.YD(a,b);if(!d.isEnabled()&&c)return;d.Aa(!0);d.oa()&&b.setAttribute("tabindex","0")}else a.menu.setAttribute("tabindex","0"),a.menu.focus();a.Aa!==b&&a.Aa&&(c=_.YD(a,a.Aa),c.oa()&&a.Aa.setAttribute("tabindex","-1"),c.Aa(!1));a.Aa=b};Lld=function(a,b){return!!a.oa().find(c=>c===b)};
Nld=function(a,b,c){const d=_.YD(a,b);if(d.isEnabled()){Kld(a,b);switch(d.getType()){case 2:var e=a.Da!==b;e&&(Ild(a),a.Da=b,d.Lk(!0));Mld(a,d,e,c);break;case 3:e=!d.isSelected();d.Lk(e);e?a.Ia.push(b):_.Ca(a.Ia,b);Mld(a,d,!0,c);break;case 5:a=a.getRoot().el();_.Tg(a,"LyWNEf");break;case 11:c=a.getRoot().el();a={trigger:b,oxd:a.oa()};_.Tg(c,"pjqKnd",a);break;default:Mld(a,d,!1,c)}d.isSelected()}};Mld=function(a,b,c,d){a=a.getRoot().el();_.Tg(a,"mMf61e",new Hld(b,c,d))};
Old=function(a){a=a.targetElement;let b,c;for(;a.el()!=null&&((b=a.el())==null?void 0:b.tagName)!=="G-MENU-ITEM"&&((c=a.el())==null?void 0:c.tagName)!=="G-MENU";)a=a.parent();let d;return((d=a.el())==null?void 0:d.tagName)==="G-MENU-ITEM"?a.el():null};Qld=function(a,b){return(b?Pld(a,!0):a.oa()).find(c=>_.YD(a,c).isEnabled()?(c=_.YD(a,c).getContent(),_.qaa(c,a.prefix)):!1)};
Pld=function(a,b){let c=a.Aa,d=a.oa().filter(e=>_.kn(e));c===null&&(a.menu.getAttribute("tabindex")==="0"||d.length>0&&d[0].getAttribute("tabindex")==="0")&&(c=b?_.va(d):d[0]);c&&(a=d.findIndex(e=>c===e),d=_.spb(d,b?-a-1:-a),a=d.findIndex(e=>c===e));return d};
_.ZD=class extends _.Wr{static Ta(){return{controllers:{cXa:{jsname:"NNJLud",ctor:_.sh},Ibe:{jsname:"hgDUwe",ctor:_.sh},LBd:{jsname:"tqp7ud",ctor:_.sh}}}}constructor(a){super();this.Da=null;this.Ia=[];this.Aa=null;this.prefix="";this.cXa=[...a.controllers.cXa,...a.controllers.Ibe,...a.controllers.LBd];this.menu=this.getRoot().el();this.Qa=_.Ola(this.menu)==="listbox";this.Ma=new _.zr(this.ub,1E3,this);_.ui(this,this.Ma);Jld(this)}Jb(){return this.Aa}oa(){const a=[...this.Ib("NNJLud").toArray()].filter(c=>
!_.YD(this,c).RBb()),b=this.qb("tqp7ud").el();b&&a.push(b);return a}Lb(){return this.cXa}ub(){this.prefix=""}clearSelection(){for(const a of this.oa()){const b=_.YD(this,a);if(b.isSelected()&&b.isEnabled())switch(b.getType()){case 2:Ild(this);break;case 3:this.Ia.pop();break;case 1:case 7:case 6:case 4:case 5:case 10:break;default:b.getType()}b.Lk(!1)}Kld(this,null)}Ba(a,b=!1){Lld(this,a)&&Nld(this,a,b)}wp(){return this.Da}Qb(){return this.Ia}Cb(){return this.Aa}Ca(){const a=this.wp();return a?_.YD(this,
a).getContent():""}Pa(){const a=this.oa()[0];return a?this.getElementToFocus(a):null}Kb(a=!1){const b=this.wp();b&&this.Qa?a=b:a?a=(a=_.va(this.oa()))?this.getElementToFocus(a):null:a=this.Pa();return a}getElementToFocus(a){var b=_.YD(this,a);if(b.getType()!==6&&b.getType()!==10)return a;b=(new _.oo([a])).find("*").toArray();return(a=[a].concat(b).find(c=>_.Ng(c)&&_.kn(c)&&(c.getAttribute("role")==="menuitem"&&c.hasAttribute("tabindex")||_.Pm(c))))?a:null}Ha(a){a&&!Lld(this,a)||Kld(this,a)}Tb(a){const b=
Old(a);if(b){var c=a.event;(c=c?c.which||c.keyCode:null)&&c===32?this.Pk(a):Nld(this,b,!0)}}Wa(){this.Aa===null&&Kld(this,this.oa()[0])}Xa(){var a=this.getRoot().el();_.Tg(a,"OVY1kd")}Za(){var a=this.getRoot().el();_.Tg(a,"nunXZ");Kld(this,null)}rb(a){(a=Old(a))&&Kld(this,a,!0)}Pk(a){const b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode;let d=!1;if(c===27)return!0;if(c===40||c===38){var e=this.Aa;const g=this.oa();e=c===38?e===g[0]:e===g.pop();if(!this.Qa||
!e){c=40===c;e=Pld(this,c);var f;c=(f=c?e.shift():e.pop())!=null?f:null;Kld(this,c);this.La(this.Aa)}}else if(c===13||c===32&&!this.prefix)this.Aa&&(d=_.YD(this,this.Aa).getType()===6||_.YD(this,this.Aa).getType()===10,Nld(this,this.Aa,!0));else if(_.YJa(c))this.Ma.start(),f=String.fromCharCode(c),this.prefix===f?f=Qld(this,!0):(this.prefix+=f,f=Qld(this,!1)),f&&(Kld(this,f),this.La(this.Aa));else return!1;if(a.wb.el().contains(b.target)){let g;(g=b.stopPropagation)==null||g.call(b);if(!d){let h;
(h=b.preventDefault)==null||h.call(b)}}return!1}La(a){a&&(this.Sa(a),(a=this.getElementToFocus(a))&&a.focus())}Sa(a,b){if(a){var c=_.fn(this.menu);if(c.height<this.menu.scrollHeight){var d=this.menu.getBoundingClientRect().top;const e=_.fn(a);d=a.getBoundingClientRect().top-d;const f=e.height/2;d<f?this.menu.scrollTop+=d-f:d+e.height>c.height-f&&(this.menu.scrollTop+=d+e.height-c.height+f);b&&(this.menu.scrollTop+=a.getBoundingClientRect().top-this.menu.getBoundingClientRect().top-Math.floor((c.height-
e.height)/2))}}}};_.ZD.prototype.$wa$uYT2Vb=function(){return this.Pk};_.ZD.prototype.$wa$IgJl9c=function(){return this.rb};_.ZD.prototype.$wa$Tx5Rb=function(){return this.Za};_.ZD.prototype.$wa$WOQqYb=function(){return this.Xa};_.ZD.prototype.$wa$h06R8=function(){return this.Wa};_.ZD.prototype.$wa$PSl28c=function(){return this.Tb};_.ZD.prototype.$wa$xpRsNe=function(){return this.Pa};_.ZD.prototype.$wa$OG2qqc=function(){return this.Ca};_.ZD.prototype.$wa$kvm28d=function(){return this.Cb};
_.ZD.prototype.$wa$mFs2Sc=function(){return this.Qb};_.ZD.prototype.$wa$Urwwkf=function(){return this.wp};_.ZD.prototype.$wa$J2hPTe=function(){return this.clearSelection};_.ZD.prototype.$wa$gSmKPc=function(){return this.Lb};_.ZD.prototype.$wa$lSpRlb=function(){return this.oa};_.ZD.prototype.$wa$mJ60jb=function(){return this.Jb};_.Yr(_.Gld,_.ZD);
_.x();
_.TSi=_.y("UHgVpe",[_.Kq,_.Vq,_.Sq,_.whh,_.Gld]);
_.QSi=function(a){var b=new _.PRc;return _.oj(b,1,a)};_.RSi=function(a,b){return _.xi(a,1,_.GRc,b)};_.SSi=_.Tb(_.QRc);
_.PSi=class extends _.m{constructor(a){super(a)}p5a(){return _.t(this,1)}G5(){return _.t(this,3)}getData(){return _.ej(this,4)}setData(a){return _.lk(this,4,a)}hasData(){return _.Ek(this,4)}getFileName(){return _.t(this,5)}hD(){return _.t(this,6)}Zca(){return _.wj(this,6)}FQ(){return _.t(this,7)}};
_.JSi=class extends _.m{constructor(a){super(a)}getWidth(){return _.yj(this,3)}Bi(){return _.Bk(this,3)}Ej(){return _.dj(this,3)}getHeight(){return _.yj(this,4)}setHeight(a){return _.Th(this,4,a)}Hg(){return _.Bk(this,4)}};_.KSi=class extends _.m{constructor(a){super(a)}getZoom(){return _.yj(this,4,1)}setZoom(a){return _.Th(this,4,a)}};_.LSi=class extends _.m{constructor(a){super(a)}Lx(){return _.t(this,1)}yp(){return _.t(this,2)}};_.MSi=class extends _.m{constructor(a){super(a)}};
_.NSi=class extends _.m{constructor(a){super(a)}getType(){return _.zj(this,1)}setType(a){return _.mk(this,1,a)}DQ(){return _.n(this,_.MSi,5)}HZ(a){return _.Lb(this,_.MSi,5,a)}};_.NSi.prototype.Aa=_.Vb(_.YQi);_.OSi=_.Sb(_.NSi,_.YQi);
_.jSi=!!(_.Gi[49]&16);_.kSi=!!(_.Gi[49]&32);_.lSi=!!(_.Gi[49]&64);_.mSi=!!(_.Gi[49]&256);_.nSi=!!(_.Gi[49]&512);_.oSi=!!(_.Gi[49]&1024);_.pSi=!!(_.Gi[49]&2048);_.qSi=!!(_.Gi[49]&4096);_.rSi=!!(_.Gi[49]&8192);_.sSi=!!(_.Gi[49]>>14&1);_.tSi=!!(_.Gi[49]>>15&1);_.uSi=!!(_.Gi[49]>>16&1);_.vSi=!!(_.Gi[49]>>17&1);_.wSi=!!(_.Gi[49]>>18&1);
_.gSi=!!(_.Gi[14]>>22&1);_.hSi=!!(_.Gi[14]>>23&1);_.iSi=!!(_.Gi[14]>>24&1);
_.QRi=!!(_.Gi[15]>>27&1);_.RRi=!!(_.Gi[15]>>28&1);_.SRi=!!(_.Gi[16]&4);_.TRi=!!(_.Gi[16]&16);_.URi=!!(_.Gi[16]&128);_.VRi=!!(_.Gi[16]&1024);_.WRi=!!(_.Gi[16]&2048);_.lV=!!(_.Gi[16]&4096);_.XRi=!!(_.Gi[16]>>14&1);_.YRi=!!(_.Gi[16]>>15&1);_.ZRi=!!(_.Gi[16]>>16&1);_.$Ri=!!(_.Gi[16]>>17&1);_.aSi=!!(_.Gi[16]>>20&1);_.bSi=!!(_.Gi[16]>>21&1);_.cSi=!!(_.Gi[16]>>25&1);_.dSi=!!(_.Gi[16]>>26&1);_.eSi=!!(_.Gi[16]>>28&1);_.fSi=!!(_.Gi[16]>>29&1);
_.v("UHgVpe");
var VSi,YSi,ZSi,$Si,WSi,USi,cTi;VSi=function(a,b,c,d){c&&(_.Wi(c,_.NSi,7)?a.searchParams.set("vsint",_.Ma(USi(_.n(c,_.NSi,7)),4)):d&&_.He(b,3)>1&&(b=(0,_.OSi)(_.Oa(d)),b=_.Qe(b,7),a.searchParams.set("vsint",_.Ma(USi(b),4))))};
_.XSi=function(a,b,c,d,e){let f=2;const g=async()=>{var h=(0,_.Qf)(),k=h();h=h(1);try{if(a!=null&&a.isAvailable()){var l=new _.Xt(b.If()),p=l.searchParams.get("udm"),q=l.searchParams.get("nem");if(p!=="50"&&q!=="143"){try{h(await k(a.Kb(r=>{const u=new _.Xt(e);var A=r.Dta(),E;const I=(E=_.kh(r,_.iRi,2,_.lh())[0])==null?void 0:_.n(E,_.DTd,2);E=I?_.Ma((0,_.ISi)(I),4):null;const N=u.searchParams.get("q");var P=u.searchParams.get("vsrid");P=E&&E!==P;const T=new _.PRc;_.Jk(r,9).forEach((ja,da)=>{u.searchParams.set(da,
ja)});([4,6,7].includes(_.zj(r,15))||_.B(r,12))&&u.searchParams.set("imgn","1");u.searchParams.set("aep","63");_.rSi&&u.searchParams.set("lns_oq",N);const Z=_.pSi?d.Fxa:null;let ca;(ca=_.n(r,_.PRc,8))==null||_.kh(ca,_.GRc,1,_.lh()).filter(ja=>_.jSi||!_.Yi(ja,_.PSi,1,_.Rz)).forEach(ja=>{_.RSi(T,ja)});Z?(u.searchParams.set("mstk",Z),u.searchParams.set("csuir","1"),u.searchParams.set("aioh","1"),u.searchParams.set("mq",A),!P&&_.SRi||u.searchParams.set("mqvsrid",E)):(l.searchParams.has("vsrid")?u.searchParams.set("q",
A):_.kSi?(_.RSi(T,(new _.GRc).hc(WSi(N).setIcon((new _.Qz).setType(79).setSize(22)))),u.searchParams.set("q",A)):u.searchParams.set("q",N?`${N} ${A}`:A),_.kh(T,_.GRc,1,_.lh()).length>0&&u.searchParams.set("aai",_.Ma((0,_.SSi)(T),4)),u.searchParams.delete("csuir"),u.searchParams.delete("mstk"),u.searchParams.delete("aioh"));_.zj(r,13)===2&&(u.searchParams.delete("udm"),u.searchParams.set("nem","143"));I&&(u.searchParams.set("vsrid",E),(A=Number(l.searchParams.get("lns_surface")))&&A===42&&VSi(u,I,
_.kh(r,_.iRi,2,_.lh())[0],l.searchParams.get("vsint")));c.navigateTo(_.pc(u.toString()))}))),f=0}catch(r){h(),_.df(Error("tp`"+r)),f=1}if(_.iSi)try{h(await k(a.Ec(()=>{c.navigateTo(_.pc(b.location.origin+"/search?udm=50&atvm=1"))})))}catch(r){h(),_.df(Error("up`"+r))}}}}finally{k()}};g();window.addEventListener("visibilitychange",()=>{window.document.visibilityState==="visible"&&f===1&&g()})};
YSi=function(a){a.searchParams.delete("udm");a.searchParams.delete("tbm");a.searchParams.delete("nem");a.searchParams.delete("nep");a.searchParams.delete("start");a.searchParams.delete("num");a.searchParams.delete("oq");a.searchParams.delete("gs_lp");a.searchParams.delete("ism");a.searchParams.delete("inm");a.searchParams.delete("source");a.searchParams.delete("si")};ZSi=function(a){switch(a){case 0:return"-1";case 1:case 3:return"0";case 4:return"1";case 2:return"2"}};
_.aTi=function(a,b,c,d,e,f){return $Si(a,"0",b,"",c,d,e,f)};
$Si=function(a,b,c,d,e,f,g,h){a.searchParams.has("vsrid")&&!a.searchParams.has("q")&&a.searchParams.set("q","");d!==""&&(a.hostname=d);e&&a.searchParams.has("q")&&!f&&a.searchParams.set("q",e);YSi(a);for(const k of bTi.split(","))a.searchParams.delete(k);d=Number(b);d>=0&&(d===0?(a.searchParams.set("udm","50"),a.searchParams.delete("arv")):a.searchParams.set("nem",b));c!==""&&a.searchParams.set("fbs",c);g!==""&&a.searchParams.set("ved",g);h&&a.searchParams.set("aep",h.toString());a.searchParams.set("ntc",
"1");return a};WSi=function(a){var b=new _.DRc;return _.Zg(b,1,a)};USi=_.Tb(_.YQi);cTi=!!(_.Gi[14]>>25&1);var bTi=_.Gi[55]&1?"arv,csuir,mstk,mtid,smstk,smstidx,shndl,shmd,shmds,source,kgs":"";var dTi=function(a,b){return a.getData("hostname").Ob()?_.im(a.getData("hostname")):b!=null?_.jm(b.getData("host"),""):""},eTi=function(a,b,c,d,e,f){d=dTi(a,d);e=e?_.jm(e.getData("ved"),""):"";b=$Si(new _.Xt(a.rc.If()),b,c,d,_.jm(a.getData("dq"),""),_.wSi,e,f);a.Yb.navigateTo(_.pc(b.toString()))},fTi=function(a,b){const c=document.querySelector('[jsname="y2FPdf"]');if(c){var d,e,f=(e=(d=c.textContent)==null?void 0:d.split(" > "))!=null?e:[];if(f.length!==0){var g,h;if(a=((h=(g=a.Wo)==null?void 0:
_.YD(g,b))==null?void 0:h.getValue())||"")if(a==="0")c.textContent=f[0];else if(a==="1"||a==="2")c.textContent=`${f[0]} > Pro`}}},gTi=class extends _.Wr{static Ta(){return{service:{rc:_.Uv,Yb:_.Bz,vsb:_.UQi,BEa:_.xhh},Bd:{menu:{jsname:"S6sggc",ctor:_.ZD}}}}constructor(a){super();this.Wo=null;this.rc=a.service.rc;this.Yb=a.service.Yb;this.Wo=a.Bd.menu;if(_.lSi&&this.getData("mgtv").Ob()){var b=$Si(new _.Xt(this.rc.If()),_.im(this.getData("mgtv")),_.jm(this.getData("fbs"),""),"",_.jm(this.getData("dq"),
""),_.wSi,"1t:244952",63);_.XSi(a.service.vsb,a.service.rc,a.service.Yb,a.service.BEa,b.toString())}}Ba(a){if(this.getData("mgtv").Ob()){const b=_.im(this.getData("mgtv")),c=_.jm(this.getData("fbs"),"");eTi(this,b,c,a.targetElement,a.wb,1)}}Da(a){const b=_.im(a.wb.getData("mgtv"));eTi(this,b,"",a.targetElement,a.wb)}Aa(a){var b=a.data.trigger,c=a.data.aza;if(b!=null&&c)if((c=b.wm())&&(c=c.dataset.ved?c:c.querySelector("a[data-ved]"))&&_.iw(c),b.getData("optionDropdown").Ob())this.oa(a);else if(a=
_.jm(b.getData("nrp"),""),a===""&&(a=_.jm(b.getData("redirectPath"),"")),a===""){var d=_.jm(this.getData("fbs"),"");eTi(this,b.getValue(),d,b.getRoot(),b)}else{c=b.getRoot();b=a;var e=_.jm(c.getData("ncp"),"");e===""&&(e=_.jm(c.getData("redirectParams"),""));a=this.rc.If();c=dTi(this,c);a=new _.Xt(a);var f=c;f===""&&(f=a.hostname);b=b.split("?");var g=b[0];c=b.length>1?b[1]:"";b=a.clone();g.startsWith("/")?(b.hostname=f,b.pathname=g):b=new _.Xt(g);e=e.split(",");f=new Map;g=!1;for(var h=0;h<e.length;++h)e[h]===
"*"?g=!0:e[h].startsWith("-")&&f.set(e[h].substring(1),!0);if(g){YSi(b);for(d of f.keys())b.searchParams.delete(d)}else for(b.searchParams.setValue(""),d=0;d<e.length;++d)if(f=e[d],a.searchParams.has(f))for(g=a.searchParams.getAll(f),h=0;h<g.length;++h)b.searchParams.append(f,g[h]);d=new Map;if(c!==""){a=new URLSearchParams(c);for(const [k,l]of a)a=k,c=l,d.has(a)?b.searchParams.append(a,c):(b.searchParams.set(a,c),d.set(a,!0))}d=b;(b=_.jm(this.getData("dq"),""))&&d.searchParams.has("q")&&!_.wSi&&
d.searchParams.set("q",b);d=_.pc(d.toString());this.Yb.navigateTo(d)}}oa(){const a=document.body.querySelector('[jsname="dheN8e"]');a&&this.Vc(a,_.Do,b=>{b.oa(a)})}Ca(a){const b=a.data.trigger;a=a.data.oxd;b.classList.contains("V8KfWe")?b==null||b.classList.remove("V8KfWe"):(a.forEach(c=>{c.classList.remove("V8KfWe")}),b==null||b.classList.add("V8KfWe"))}Ha(a){if(cTi){a=a.data;var b=document.querySelector('[jsname="H1cYZb"]');if(a!==0&&b){var c=ZSi(a),d=this.Wo;(a=d==null?void 0:d.oa().find(e=>{let f;
return((f=d==null?void 0:_.YD(d,e))==null?void 0:f.getValue())===c}))&&a!==(d==null?void 0:d.wp())&&(d==null||d.clearSelection(),d==null||_.YD(d,a).Lk(!0),fTi(this,a))}}}};gTi.prototype.$wa$fqmbjc=function(){return this.Ha};gTi.prototype.$wa$C70bfd=function(){return this.Ca};gTi.prototype.$wa$JxAq2e=function(){return this.oa};gTi.prototype.$wa$zlgt8b=function(){return this.Aa};gTi.prototype.$wa$I9Eaue=function(){return this.Da};gTi.prototype.$wa$vr907=function(){return this.Ba};_.Yr(_.TSi,gTi);
_.x();
_.v("PGyklf");
_.TOc=class extends _.Wr{constructor(){super();this.root=this.getRoot().el()}isEnabled(){return!this.root.hasAttribute("disabled")&&!this.root.hasAttribute("aria-disabled")}focus(){_.ua()&&this.root.blur();this.root.focus()}setEnabled(a){a?this.root.removeAttribute("disabled"):this.root.setAttribute("disabled","true");_.Yd(this.root,"disabled",!a)}getContent(){const a=this.qb("ibnC6b").el();return a?_.Qm(a):""}getValue(){return this.value}oa(){return this.root}};_.TOc.prototype.$wa$L4rKVc=function(){return this.oa};
_.TOc.prototype.$wa$HvnK2b=function(){return this.getValue};_.TOc.prototype.$wa$aDGs4d=function(){return this.getContent};_.TOc.prototype.$wa$AHmuwe=function(){return this.focus};_.TOc.prototype.$wa$yXgmRe=function(){return this.isEnabled};
_.x();
_.ZOc=_.er("PGyklf",[]);
_.$Oc=_.y("pzkXnb",[_.ZOc]);
_.v("pzkXnb");
_.aPc=class extends _.TOc{constructor(){super();this.value=_.jm(this.getData("v"),"");this.Krc=this.getData("o").Ob();this.isLink=this.getData("l").Ob();this.vM=this.getData("s").Ob();this.root.getAttribute("disabled")&&this.setEnabled(!1);this.root.addEventListener("click",()=>{})}Ca(){return this.vM}focus(){if(this.isLink){let a;(a=this.oa().querySelector("a"))==null||a.focus()}else super.focus()}Pc(){this.vM&&this.isEnabled()?this.Lk(!this.isSelected()):!this.isLink&&this.isEnabled()&&this.trigger("UszG1b",
{Krc:this.Krc});this.notify("aZcdhc");return!0}Ba(){this.trigger("L8zncc")}Aa(a){(a=a.event.relatedTarget)&&this.trigger("M9oBfd",{relatedTarget:a})}isSelected(){return this.vM&&(_.$d(this.root,"checked")==="true"||_.$d(this.root,"selected")==="true")}Lk(a){this.vM&&(a&&this.isEnabled()?(_.Yd(this.root,"checked","true"),this.trigger("UBsZj")):a||(_.Yd(this.root,"checked","false"),this.trigger("JkcjMe")))}};_.aPc.prototype.$wa$KKjvXb=function(){return this.isSelected};_.aPc.prototype.$wa$MDJmo=function(){return this.Aa};
_.aPc.prototype.$wa$rESl3=function(){return this.Ba};_.aPc.prototype.$wa$h5M12e=function(){return this.Pc};_.aPc.prototype.$wa$AHmuwe=function(){return this.focus};_.aPc.prototype.$wa$pxaUTb=function(){return this.Ca};_.Yr(_.$Oc,_.aPc);
_.x();
_.FOc=_.y("Mbif2",[_.Tq,_.em,_.co]);
_.v("Mbif2");
var GOc,JOc,KOc;GOc=[1,2,3];
_.IOc=function(a,b=!1){var c=_.HOc(a,a.controller),d=a.controller.oa(),e=_.uJa(d),f=_.uJa(c)-c.scrollLeft;e-=f;var g=_.je(d),h=e+_.fn(d).width/2;e=h-9.5;f=a.oa.get(_.HOc(a,a.controller));var k=f.container;var l=k.style.display,p=k.style.position,q=k.style.visibility;if(a.isVisible(a.controller))k=new _.Od(k.offsetWidth,k.offsetHeight);else{k.style.visibility="hidden";k.style.position="absolute";k.style.display="block";var r=new _.Od(k.offsetWidth,k.offsetHeight);k.style.display=l;k.style.position=
p;k.style.visibility=q;k=r}p=k.width;r=k.height;l=a.controller.Cb();q=a.controller.ub();k=0;if(!_.om.contains(f.container,"SiOjJb")){switch(l){case 5:case 2:k=h-p/2;break;case 4:case 1:k=h-(g?p-9.5-q:9.5+q);break;case 6:case 3:k=h-(g?9.5+q:p-9.5-q)}k=Math.max(c.scrollLeft+8,k);g=c===a.window.getDocument().body?_.Yh(a.window.get()).width:c.offsetWidth;k=Math.min(k,g+c.scrollLeft-8-p);g=parseInt(_.Wm(f.container,"border-radius"),10)||0;k=Math.min(k,e+g);k=Math.max(k,e+19+g-p)}b&&(k=Math.max(k,0));g=
parseInt(_.Wm(d,"padding-top"),10)||0;b=!1;h=GOc.indexOf(l)!==-1;q=g+9.5+r-1;l=_.Zm(d);c=c!==a.window.getDocument().body?c.scrollTop-_.Zm(c):0;p=_.fn(d).height;const u=d.getBoundingClientRect().top;d=u-q>=0;q=u+p+q<=_.Yh(a.window.get()).height;a=a.controller.Wa();h&&(q||!a)||!h&&!d&&a?(a=c+l+p+g,d=a+9.5-1):(a=c+l-g-9.5,d=a-r+1,b=!0);_.Um(f.container,"left",`${k}px`);_.Um(f.container,"top",`${d}px`);_.Um(f.dta,"left",`${e}px`);_.Um(f.dta,"top",`${a}px`);b?_.om.add(f.dta,"IBPZu"):_.om.remove(f.dta,
"IBPZu")};_.HOc=function(a,b){return b.Sa()&&_.sm(b.Sa())||b.Jb()&&b.getRoot().el().offsetParent||a.window.getDocument().body};_.LOc=function(a){if(a.controller){_.hg(a.controller.oa(),"sendDismissEvent")&&a.controller.trigger("pD7Wob");var b=a.oa.get(_.HOc(a,a.controller));a.Aa&&(a.Da=+_.gg(a.controller.getRoot().el(),"du"));a.controller=null;b&&(b.container.__owner=void 0,a.dismiss.unlisten(b.container),a.Aa?(JOc(b,!1),a.Ha=(0,_.Yn)(()=>{KOc(b)},a.Da)):KOc(b))}};
JOc=function(a,b){const c=a.container;a=a.dta;b?(_.om.n_(c,"bE3Kif","nFdFHf"),_.om.n_(a,"bE3Kif","nFdFHf")):(_.om.n_(c,"nFdFHf","bE3Kif"),_.om.n_(a,"nFdFHf","bE3Kif"))};KOc=function(a){_.Um(a.container,{display:"none",width:"","z-index":""});_.Um(a.dta,{display:"none","z-index":""});_.DVb(a.lZ);_.om.set(a.container,"QyJI3d");_.om.set(a.dta,"tYmfxe");_.om.set(a.Wid,"oQcPt")};
_.MOc=class extends _.ko{static Ta(){return{service:{dismiss:_.tv,Bc:_.Hu,window:_.go}}}constructor(a){super();this.Ba=this.controller=null;this.Ia=0;this.Aa=!1;this.Ha=null;this.Da=0;this.oa=new Map;this.Pb=a.service.Bc;this.dismiss=a.service.dismiss;this.window=a.service.window;_.ne(this.window.get(),"resize",()=>{this.controller&&_.IOc(this)})}Vb(){super.Vb();this.oa.forEach(a=>{_.Lm(_.sm(a.containerId));_.Lm(_.sm(a.Xid))})}Ca(a,b){this.isVisible(this.controller)&&(this.log(!1,a,b),_.LOc(this))}log(a,
b,c){const d=this.controller.Ma();b=b&&_.Ie(b)?b:void 0;d&&_.Ie(d)&&(c=b?new _.Nh(_.Ie(b),c||2):void 0,a?this.Pb.Aa(d,c):this.Pb.Ba(d,c))}onDismiss(a,b){const c=this.controller?this.controller.rb():!1;let d;if(b&&((d=this.controller)==null?0:d.Wb(b)))return!1;this.Ca(b);a===2&&this.Ba&&this.Ba.focus();return c}D9(a){const b=a.container;_.Um(b,{display:"block"});_.Mg(b,this.controller.getRoot().el());_.hg(this.controller.oa(),"sendShowEvent")&&this.controller.trigger("tA6Kcd");this.controller.Za()||
(a.content.focus(),_.CVb(a.lZ),this.dismiss.listen(a.container,(c,d)=>this.onDismiss(c,d)));_.Um(a.dta,{display:"block"});this.Aa&&((0,_.Zn)(this.Ha),JOc(a,!0))}isVisible(a){if(!a)return!1;a=this.oa.get(_.HOc(this,a));return!!a&&_.Wm(a.container,"display")==="block"}Cga(a){this.controller&&(a=this.oa.get(_.HOc(this,this.controller)).content.querySelector(`[jsname=${a}]`))&&_.Ng(a)&&_.Pm(a)&&a.focus()}};_.$f(_.FOc,_.MOc);
_.x();
_.v("ipWLfe");

_.x();
var NOc=_.er("ipWLfe",[]);_.OOc=_.y("QVaUhf",[_.FOc,NOc]);
_.v("QVaUhf");
var POc,QOc,ROc,SOc;
POc=function(a,b){b=_.HOc(a,b);var c=a.oa.get(b);if(c)return c;c=_.Dm("DIV","QyJI3d");const d="gbbl-"+String(a.Ia++);c.id=d;_.jn(c,!1);var e=_.Dm("DIV");_.dn(e,0);_.hn(e,0);_.Yd(e,"hidden",!0);_.Xd(e,"button");_.TIa(e,!0);c.appendChild(e);const f=_.Dm("DIV");f.tabIndex=-1;const g=new _.EVb(f);_.Um(f,"outline","none");c.appendChild(f);_.ne(e,"focus",()=>{((new _.oo([f])).find("*").toArray().reverse().find(l=>_.Ng(l)?_.Pm(l):!1)||f).focus()});e=e.cloneNode(!0);_.TIa(e,!0);_.ne(e,"focus",()=>{((new _.oo([f])).find("*").toArray().find(l=>
_.Ng(l)?_.Pm(l):!1)||f).focus()});c.appendChild(e);e=_.Dm("DIV",["oQcPt"]);const h=_.Dm("DIV",["tYmfxe"],e),k="gbblt-"+String(a.Ia++);h.id=k;_.jn(h,!1);c={container:c,containerId:d,content:f,lZ:g,dta:h,Xid:k,Wid:e};a.oa.set(b,c);return c};
QOc=function(a,b,c,d,e=!1,f=!1,g=0,h="",k="",l,p=!1,q=!1){a.Aa=q;_.LOc(a);if(q=b.Ma()){q=q.parentNode?q.parentNode:q;a.controller=b;var r=POc(a,b);var u=_.HOc(a,b);_.sm(r.containerId)||u.appendChild(r.container);_.sm(r.Xid)||u.appendChild(r.dta);_.Yd(r.container,"hidden",!1);u=a.controller.oa();g===1?(_.om.add(r.container,"PnQMie"),_.om.add(r.dta,"PnQMie")):g===2&&(_.om.add(r.container,"LWen5c"),_.om.add(r.dta,"LWen5c"));h&&_.om.addAll(r.container,h.split(" "));k&&_.om.addAll(r.Wid,k.split(" "));
d!==null&&(_.Um(r.container,"z-index",d),_.Um(r.dta,"z-index",d+1));p&&_.Um(r.container,"max-width","100%");_.om.enable(r.container,"SiOjJb",f);_.om.enable(r.container,"QJnoze",e);c>0&&!f&&_.Um(r.container,{width:`${c}px`});b.Pa()?r.container.setAttribute("aria-label",b.Pa()):r.container.removeAttribute("aria-label");_.Xd(r.container,b.Xa()?"dialog":"alertdialog");b=r.content;_.Hm(b);for(const A of q.childNodes)b.appendChild(A.cloneNode(!0));a.Ba=a.window.getDocument().activeElement;_.IOc(a,p);a.D9(r);
a.log(!0,u,l)}};ROc=class extends _.Wr{};SOc=function(a,b,c){a=_.gg(a,b)||"";a=_.bm(a);return isNaN(a)?c:a};
_.uz=class extends ROc{static Ta(){return{service:{ttb:_.MOc}}}constructor(a){super();this.Ia=this.Ca=this.Da=null;this.Ha=a.service.ttb;this.Tb=_.un(()=>this.Ka("bN97Pc").el());this.Rb=_.un(()=>this.Ka("d6wfac").el());this.Qa=!_.hg(this.oa(),"lzyAct")}Kb(a){const b=a.event;b&&this.Da&&this.isVisible()&&b.clientX===this.Da.clientX&&b.clientY===this.Da.clientY&&b.timeStamp-this.Da.timeStamp<200||this.Ba(void 0,3);this.Da=null;a.event.preventDefault&&a.event.preventDefault();return _.hg(this.oa(),"sendOpenEvent")}Ba(a,
b){var c=this.oa();if(a===!1||!a&&this.isVisible())this.Qa?this.La(c,b):this.Ia=null;else if(this.Qa){a=SOc(c,"theme",0);var d=SOc(c,"zidx",0);d=d>=1?d:null;var e=SOc(c,"width",200),f=_.hg(c,"fullWidth"),g=_.hg(c,"roundedCorners"),h=_.gg(c,"extraContainerClasses"),k=_.gg(c,"extraTriangleClasses"),l=this.getData("ctv").Ob();c=_.hg(c,"enableToggleAnimation");QOc(this.Ha,this,e,d,g,f,a,h,k,b,l,c);b=this.getData("f");b.Ob()&&this.Ha.Cga(b.string())}else this.Ia=b}Lb(){this.Qa=!0;this.Ia!==null&&(this.Ba(!0,
this.Ia),this.Ia=null)}D9(a){this.Ba(!0,a)}Aa(a){this.Ba(!1,a?3:void 0)}Qb(a){const b=this.oa();(new _.so(b)).focus();this.Aa(a)}qc(){return!1}onMouseEnter(a){_.hg(this.oa(),"sendOpenEvent")&&this.trigger("aKmQDb",a.targetElement);this.D9(9);this.Da=a.event;return!1}onMouseLeave(){this.Da&&(this.Ba(!1,9),this.Da=null)}zc(a){this.Ca!==null&&((0,_.Zn)(this.Ca),this.Ca=null);if(!this.isVisible())if(_.hg(this.oa(),"delayOpenOnHover"))this.Ca=(0,_.Yn)(()=>this.onMouseEnter(a),SOc(this.oa(),"hoverOpenDelay",
500));else this.onMouseEnter(a);return!1}Fc(){this.Ca!==null&&((0,_.Zn)(this.Ca),this.Ca=null);this.isVisible()&&(this.Ca=(0,_.Yn)(()=>this.Aa(),SOc(this.oa(),"hoverHideDelay",1E3)))}Ma(){return this.Tb()}oa(){return this.Rb()}Vb(){this.isVisible()&&_.LOc(this.Ha);super.Vb()}Wb(a){return _.Wg(this.oa(),a)}La(a,b){this.isVisible()&&this.Ha.Ca(a,b)}isVisible(){var a=this.Ha;return a.controller===this&&a.isVisible(this)}Wa(){return this.getData("ci").Ob()}Cb(){return SOc(this.getRoot().el(),"tp",2)}ub(){return SOc(this.getRoot().el(),
"to",10)}Za(){return this.getData("df").Ob()}rb(){return _.hg(this.oa(),"disableDismissEventBubbling")}Sa(){return this.getData("sc").Ob()?_.im(this.getData("sc")):null}Jb(){return this.getData("oc").Ob()}Pa(){return _.jm(this.getData("al"),"")}Xa(){return this.getData("da").Ob()}};_.uz.prototype.$wa$x2QzWe=function(){return this.Xa};_.uz.prototype.$wa$jZ0cf=function(){return this.Pa};_.uz.prototype.$wa$wu4W6e=function(){return this.Jb};_.uz.prototype.$wa$A4M6Rd=function(){return this.Sa};
_.uz.prototype.$wa$YWMfPe=function(){return this.rb};_.uz.prototype.$wa$plyROe=function(){return this.Za};_.uz.prototype.$wa$zxO7z=function(){return this.ub};_.uz.prototype.$wa$qIUUyb=function(){return this.Cb};_.uz.prototype.$wa$Dntuwf=function(){return this.Wa};_.uz.prototype.$wa$eO2Zfd=function(){return this.isVisible};_.uz.prototype.$wa$k4Iseb=function(){return this.Vb};_.uz.prototype.$wa$lI3Pp=function(){return this.oa};_.uz.prototype.$wa$noyIOe=function(){return this.Ma};
_.uz.prototype.$wa$JDTRYd=function(){return this.Fc};_.uz.prototype.$wa$jTlRtf=function(){return this.zc};_.uz.prototype.$wa$iFHZnf=function(){return this.onMouseLeave};_.uz.prototype.$wa$MJEKMe=function(){return this.onMouseEnter};_.uz.prototype.$wa$NLMyWb=function(){return this.qc};_.uz.prototype.$wa$DLNOs=function(){return this.Qb};_.uz.prototype.$wa$VqIRre=function(){return this.Aa};_.uz.prototype.$wa$dou8Ld=function(){return this.Lb};_.uz.prototype.$wa$vQLyHf=function(){return this.Kb};
_.Yr(_.OOc,_.uz);
_.x();
_.Ots=class{constructor(a){this.oa=a}};var Pts=class extends _.Ots{constructor(a,b){super(a);this.Ba=b;this.Aa=null}JI(){if(this.Aa)return this.Aa;const a=[];for(var b=this.oa.xb;b instanceof gbar.I&&b!=this.Ba.oa;)a.push(b.ic()),b=b.zb();for(b=this.Ba;a.length>0;)b=b.LJa(a.pop());return this.Aa=b}getType(){return this.oa.xa}};var Qts=class extends _.Ots{listen(a,b,c,d){const e=this;return this.oa.za(a,function(f){return b.call(d||_.ea,new Pts(f,e))},c)}listenOnce(){throw Error("$n");}unlisten(){throw Error("$n");}ev(){throw Error("$n");}dispatchEvent(){throw Error("$n");}removeAllListeners(){throw Error("$n");}a5a(){throw Error("$n");}fireListeners(){throw Error("$n");}O4a(){throw Error("$n");}N4a(){throw Error("$n");}hasListener(){throw Error("$n");}};Qts.prototype[_.HJa]=!0;var Rts=class extends Qts{getHeight(){return this.oa.pa()}setDarkMode(a){this.oa.pp(a);return this}};var Sts=class extends Qts{constructor(a){super(a);this.Aa=null}getId(){return this.oa.ia()}Ka(){return this.oa.ib()}getModel(){return this.Aa}setModel(a){this.Aa=a;return this}};var Tts=class extends Sts{constructor(a){super(a);this.Ba={}}LJa(a){var b=this.Ba[a];if(b)return b;if(b=this.oa.ja(a)){const c=b.__wc;if(!c)throw Error("vx");b=new c(b);return this.Ba[a]=b}return null}};var Uts=class extends Tts{getContent(){return this.oa.ca()}open(a){this.oa.cf(a)}close(a){this.oa.cg(a)}getStyle(){return this.oa.ch()}isOpen(){return this.oa.ck()}};var Vts;Vts=function(a,b){const c=a.Aa;return c?function(d){b.call(this,new c(d))}:b};_.Wts=class extends _.Ots{constructor(a,b){super(a);this.Aa=b||null}then(a,b,c){let d;a&&(d=Vts(this,a));this.oa.aa(d,b,c)}};var Xts;_.Yts=function(){return new Promise(a=>{window.gbar||(window.gbar={});if(window.gbar.a)return a(Xts.getInstance());(new Promise(b=>{window.gbar.ap=b})).then(()=>a(Xts.getInstance()))})};Xts=class extends _.Ots{constructor(a){super(a||gbar.a);this.Ba=this.Aa=null}s5(){this.Aa||(this.Aa=new _.Wts(this.oa.bf(),Rts));return this.Aa}um(){this.Ba||(this.Ba=new _.Wts(this.oa.ba(),Uts));return this.Ba}static getInstance(){return _.Gh(Xts)}};
var Kts;_.Lts=function(){var a=new Kts;a=_.Sh(a,1,1);return _.Sh(a,2,4)};Kts=class extends _.m{constructor(a){super(a)}fS(){return _.bk(this,1)}};Kts.prototype.ob="SMSkB";var Mts=class extends _.m{constructor(a){super(a)}};Mts.prototype.ob="s5PeBc";new _.ri(Kts);new _.ri(Mts,1E3);_.Wo.s5PeBc=_.Vo;_.Nts=new _.fi("VbSMl",Mts,Kts,[_.ei,!1,_.di,"/MyactivityService.ExternalDelete"]);new _.ri(Kts);new _.ri(Mts,1E3);_.Wo.s5PeBc=_.Vo;
var Yzg,$zg,dAg;Yzg=function(){var a={};const b=_.mIa(_.oIa("/blank.html"));if(!Wzg.test(b))throw Error("Nl`"+b);const c=b.replace(Xzg,function(d,e){if(!Object.prototype.hasOwnProperty.call(a,e))throw Error("Ol`"+e+"`"+b+"`"+JSON.stringify(a));d=a[e];return d instanceof _.kIa?_.mIa(d):encodeURIComponent(String(d))});return _.ic(c)};_.aAg=function(a){var b=Yzg();b=_.jc(b);b=Zzg.exec(b);const c=b[3]||"";return _.xka(b[1]+$zg("?",b[2]||"")+$zg("#",c,a),{justification:"Deprecated, but safe closure/html builder"})};
$zg=function(a,b,c){if(c==null)return b;if(typeof c==="string")return c?a+encodeURIComponent(c):"";for(const e in c)if(Object.prototype.hasOwnProperty.call(c,e)){var d=c[e];d=Array.isArray(d)?d:[d];for(let f=0;f<d.length;f++){const g=d[f];g!=null&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(e)+"="+encodeURIComponent(String(g)))}}return b};
_.eAg=function(a,b){a&&_.jc(a);var c={};c.src=a||null;c.srcdoc=void 0;var d={sandbox:""};a={};for(var e in c)Object.prototype.hasOwnProperty.call(c,e)&&(a[e]=c[e]);for(const h in d)Object.prototype.hasOwnProperty.call(d,h)&&(a[h]=d[h]);if(b)for(var f in b)if(Object.prototype.hasOwnProperty.call(b,f)){e=f.toLowerCase();if(e in c)throw Error("U");e in d&&delete a[e];a[f]=b[f]}b=void 0;c="";if(a)for(g in a)if(Object.prototype.hasOwnProperty.call(a,g)){if(!bAg.test(g))throw Error("U");d=a[g];if(d!=null){f=
g;if(f.toLowerCase()=="style")d=String(d);else{if(/^on/i.test(f))throw Error("U");if(f.toLowerCase()in cAg)if(d instanceof _.fc)d=_.jc(d).toString();else if(_.Nia(d))d=_.mc(d);else if(typeof d==="string")d=_.pc(d).toString();else throw Error("U");}f=`${f}="`+_.zaa(String(d))+'"';c+=" "+f}}var g="<iframe"+c;b==null?b=[]:Array.isArray(b)||(b=[b]);dAg.iframe===!0?g+=">":(a=_.bja(b),g+=">"+_.ec(a)+"</iframe>");return _.z(g)};
dAg={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var Xzg=/%{(\w+)}/g,Wzg=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),Zzg=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,bAg=/^[a-zA-Z0-9-]+$/,cAg={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};
var xts=function(a){let b=a,c;return function(){if(b){const d=b;b=void 0;c=d.apply(this,arguments)}return c}},yts=function(a){try{a[0].commonConfig.frdProductData&&(a[0].commonConfig.frdProductDataSerializedJspb=a[0].commonConfig.frdProductData.serialize(),a[0].commonConfig.frdProductData=void 0)}catch(b){}try{let b;if((b=a[0].commonGseConfig)==null?0:b.gseSessionOptions)a[0].commonGseConfig.gseSessionOptionsSerializedJspb=a[0].commonGseConfig.gseSessionOptions.serialize(),a[0].commonGseConfig.gseSessionOptions=
void 0}catch(b){}try{a[0].startingFlow&&(a[0].startingFlowSerializedJspb=a[0].startingFlow.serialize(),a[0].startingFlow=void 0)}catch(b){}return a},zts=async function(a,b,c){var d=(0,_.Qf)(),e=d();d=d(1);try{const f=d(await e(a.oa)),g=f[b];if(!g)throw Error("rx`"+b);return g.apply(f,c)}finally{e()}},Ats=class{constructor(a){this.oa=a;this.ym=null;a.then((0,_.oe)(function(){},this),()=>{},this)}},Dts=function(a,b,c){const d=Array(arguments.length-2);for(var e=2;e<arguments.length;e++)d[e-2]=arguments[e];
e=Bts(a,b).then(f=>f.apply(null,d),f=>{f=Error("sx`"+b+"`"+a+"`"+f,{cause:f});delete Cts[b];return _.zh(f)});return new Ats(e)},Cts={},Bts=function(a,b){var c=Cts[b];if(c)return c;c=(c=_.Fi(b))?_.Dg(c):(new _.Og(function(d,e){const f=(new _.pIa(document)).createElement("SCRIPT");f.async=!0;_.Rc(f,_.ic(_.mIa(a)));f.onload=f.onreadystatechange=function(){f.readyState&&f.readyState!="loaded"&&f.readyState!="complete"||d()};f.onerror=g=>{e(Error("tx`"+b+"`"+a,{cause:g}))};(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){const d=
_.Fi(b);if(!d)throw Error("ux`"+b+"`"+a);return d});return Cts[b]=c};var Ets={GOOGLE:"https://www.google.com",c_e:"https://support.google.com",LRe:"https://play.google.com"},Fts=async function(a){var b=(0,_.Qf)(),c=b();b=b(1);try{for(const d of Object.values(Ets))try{b(await c(navigator.permissions.query({name:"top-level-storage-access",requestedOrigin:d}))).state!=="granted"&&a.oa.push(d)}catch(e){b();break}}finally{c()}};var Gts,Hts,Its;Gts=_.oIa("https://www.google.com/tools/feedback/open_to_help_guide_lazy.js");Hts=_.oIa("https://www.google.com/tools/feedback/help_api.js");_.Jts=function(a,b){let c=Hts,d="help.api.Lazy.create";(b==null?void 0:b.yRd)===1&&(c=Gts,d="help.api.HelpGuideLazy.create");a=Dts(c,d,a);return new Its(a)};
Its=class{constructor(a){this.zxa=a}async oa(a){var b=(0,_.Qf)(),c=b();b=b(1);try{b(await c(zts(this.zxa,"openHelp",yts(arguments))))}finally{c()}}async Aa(a){await zts(this.zxa,"openToGse",yts(arguments))}async close(){var a=(0,_.Qf)(),b=a();a=a(1);try{a(await b(zts(this.zxa,"close",arguments)))}finally{b()}}};
(new class{constructor(){this.oa=[];this.Aa=[];this.initialize=xts(async()=>{var a=(0,_.Qf)(),b=a();a=a(1);try{if(typeof document==="undefined"||document.requestStorageAccessFor===void 0||navigator.permissions===void 0||navigator.permissions.query===void 0||location.hostname.match(".+\\.google\\.com$"))return Promise.resolve();a(await b(Fts(this)));this.oa.length>0&&document.addEventListener("click",this.Ba)}finally{b()}});this.Ba=()=>{if(!(this.Aa.length>0)){for(const a of this.oa)try{this.Aa.push(document.requestStorageAccessFor(a))}catch(b){}Promise.all(this.Aa).then(()=>
{}).catch(()=>{}).finally(()=>{this.reset()})}}}reset(){document.removeEventListener("click",this.Ba)}}).initialize();
_.klq=_.y("SJpD2c",[_.Mo,_.em,_.OOc]);
_.v("SJpD2c");
var Zts=function(a,b=!1){a.oa.sh(b)},$ts=class extends _.Ots{},aus=function(a){a.Ca||(a.Ca=new _.Wts(a.oa.bk(),$ts));return a.Ca},bus=function(a,b,c){return{id:b,callable:()=>{a.logClick(c)},url:null}},cus=function(a){return(b,c)=>{var d;const e=(d=a.getRoot())==null?void 0:d.el();b=a.isSignedIn?e:b;d=a.Pb.oa();e&&_.Hp(d,e,c?1:2);b&&_.Fp(d,b,3);d.log(!0)}},dus=function(a){const b=_.Jts("196"),c=_.wd(_.vd("QrtxK"),0).toString(),d=!!document.body.dataset.dt,e=document.body.querySelector("[jsname='AYtejb']"),
f={commonConfig:{helpCenterPath:"websearch",authuser:c,locale:_.jm(_.vd("GWsdKe"),"en")},helpPanelConfig:{helpPanelTheme:d?1:0,helpPanelMode:1,fixedHelpPanelContainer:e?e:void 0},X9e:!0,oTa:{bucket:"Default"}};return{id:"og-am-hf",callable:()=>{a.logClick(a.Ka("uO6mde").el());b.oa(f)},url:null}},eus=function(a,b){_.Yts().then(c=>{aus(c).then(d=>{const e=[bus(a,"og-am-ss",a.Ka("NG1V7d").el()),bus(a,"og-am-lg",a.Ka("IZKNDc").el()),bus(a,"og-am-ms",a.Ka("tP7ayb").el())];b?e.push(dus(a)):e.push(bus(a,
"og-am-hf",a.Ka("uO6mde").el()));a.isSignedIn?e.push(bus(a,"og-am-qdc-qd",a.Ka("hJoEPd").el()),bus(a,"og-am-qdc-sh",a.Ka("micRse").el()),{id:"og-am-qdc-dt",callable:()=>a.oa(),url:null},{id:"og-am-qdc-fsb",callable:()=>{a.Aa()},url:null},bus(a,"og-am-cp-int",a.qb("t5CbBf").el()),bus(a,"og-am-ps",a.qb("Du1Fsb").el()),bus(a,"og-am-sop",a.qb("bicHfd").el())):e.push(bus(a,"og-am-pc",a.qb("nSxrjf").el()));a.Ba&&e.push(bus(a,"og-am-dm",a.qb("pxGDvf").el()));d.oa.sf(e);d.oa.sj(cus(a))})})},fus=class extends _.Wr{static Ta(){return{service:{Ke:_.wr,
Pb:_.Hu},controllers:{sgc:{jsname:"ovbFm",ctor:_.uz}}}}logClick(a){a!=null&&_.Fp(this.Pb.oa(),a,3).log(!0)}constructor(a){super();this.I_=null;this.isSignedIn=!this.getData("so").Ob();const b=this.getData("iph").Ob();this.Ba=this.getData("dmt").Ob();this.Rd=a.service.Ke;this.sgc=a.controllers.sgc[0];this.Pb=a.service.Pb;this.logger=null;eus(this,b);this.isSignedIn&&_.vh(this,{controllers:{I_:"PWj1Zb"}}).then(c=>{this.I_=c.controllers.I_[0]})}async oa(){var a=(0,_.Qf)(),b=a();a=a(1);try{try{const c=
_.Lts();a(await b(this.Rd.Ic(_.Nts.getInstance(c))));return!0}catch(c){return a(),!1}}finally{b()}}Aa(){let a;(a=this.I_)==null||a.show()}Da(){let a;(a=this.sgc)==null||a.D9()}async Ca(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const d=a.data.CVd,e=b(await c(_.Yts()));Zts(b(await c(aus(e))),d)}finally{c()}}};fus.prototype.$wa$FPeyVe=function(){return this.Ca};fus.prototype.$wa$MMAZpe=function(){return this.Da};fus.prototype.$wa$BjElId=function(){return this.Aa};fus.prototype.$wa$BlH6Ne=function(){return this.oa};
_.Yr(_.klq,fus);
_.x();
_.NVb=_.y("eX5ure",[_.em]);
_.v("eX5ure");
var OVb=class extends _.Wr{static Ta(){return{service:{Pb:_.Hu}}}constructor(a){super();this.parentElement=null;this.root=this.getRoot().el();this.id=this.getRoot().el().getAttribute("data-id");this.Ca=this.getRoot().el().hasAttribute("data-dc");this.Da=this.getRoot().el().hasAttribute("data-dw");this.oa=_.gi(this.getRoot().getData("backDisabled"),!1);this.Pb=a.service.Pb;this.registerContent()}Ba(){return this.root}Vb(){}registerContent(){this.trigger("jxvro",{controller:this})}Ha(a){a=a.wb.el();
this.trigger("dBhwS",{triggerElement:a})}Pdd(a){this.parentElement=a}getId(){return this.id}isDefault(){return this.Ca}hide(){_.jn(this.root,!1)}Inc(a){this.hide();_.Ie(this.root)&&_.Fp(_.Hp(this.Pb.oa(),this.root,2),a).log()}show(a){_.Um(this.root,{display:"block"});var b=this.qb("LBJcic").el();const c=this.qb("X0x7he").el();(b||this.oa)&&c&&(!this.oa&&b&&(a?_.Um(b,{display:"inline-block"}):_.jn(b,!1)),b=this.qb("vDg59d").el(),this.Da?(a=a?220:248,b&&(a-=48),_.Um(c,"width",`${a}px`)):b&&_.Um(c,"width",
`calc(100% - ${48+(a?28:0)}px)`))}AIb(a,b){this.show(a);_.Ie(this.root)&&_.Fp(_.Hp(this.Pb.oa(),this.root,1),b).log()}Lfc(a){const b=a.event.target;let c,d;const e=(d=(c=a.data)==null?void 0:c.contentId)!=null?d:b.getAttribute("data-id");this.parentElement&&this.Sd(this.parentElement).then(f=>f.Ia(e,b))}Aa(a){const b=a.wb.el();this.parentElement&&this.Sd(this.parentElement).then(c=>{if(c.Ca.length>0){c.Aa.Inc(b);const d=c.Ca.pop(),e=c.Ca.length>0;c.Aa=d;d.AIb(e,b)}})}};OVb.prototype.$wa$iO11jf=function(){return this.Aa};
OVb.prototype.$wa$uOhSee=function(){return this.Lfc};OVb.prototype.$wa$ZYIfFd=function(){return this.hide};OVb.prototype.$wa$paynGb=function(){return this.isDefault};OVb.prototype.$wa$pTuYge=function(){return this.getId};OVb.prototype.$wa$QQtcRd=function(){return this.Ha};OVb.prototype.$wa$CHHOAf=function(){return this.registerContent};OVb.prototype.$wa$k4Iseb=function(){return this.Vb};OVb.prototype.$wa$xdy80=function(){return this.Ba};_.Yr(_.NVb,OVb);
_.x();
_.SNC=function(){return window.matchMedia?window.matchMedia("(forced-colors: active)").matches?2:window.matchMedia("(forced-colors: none)").matches?1:0:0};
_.CAq=_.y("zGLm3b",[]);
_.v("zGLm3b");
var XNC=!!(_.Gi[0]&2);var YNC=!!(_.Gi[24]&1);var ZNC=!!(_.Gi[60]&256);var $NC=!!(_.Gi[25]&8);var aOC=new _.Rn,bOC=class extends _.Wr{constructor(){super();this.oa=_.On(aOC,a=>new a(this.getRoot()));this.Aa();this.Ba()}Aa(){const a=_.Xg();for(const b of this.oa){const c=b.VYb();c&&a.Lc(c[0],c[1])}a.log()}Ba(){var a="";for(var b of this.oa){const c=b.f0b();c&&(a.length>0&&(a+="&"),a+=c.join("="))}a.length>0&&(a=_.cna(`/client_204?${a}`,new Map,!1,!1),b=new _.lr,b.setWithCredentials(!0),b.send(a))}};bOC.prototype.$wa$ZhdDvf=function(){return this.Ba};bOC.prototype.$wa$fgCVyc=function(){return this.Aa};
_.Yr(_.CAq,bOC);var cOC=class{constructor(a){this.Aa=this.oa=0;this.oa=_.SNC();this.Aa=_.wd(a.getData("fc"),0)}VYb(){return["fc",String(this.oa)]}f0b(){return this.oa!==this.Aa?["fc",String(this.oa)]:null}};XNC&&_.Pn(aOC,cOC);var dOC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-contrast: less)").matches?"1":window.matchMedia("(prefers-contrast: more)").matches?"2":window.matchMedia("(prefers-contrast: custom)").matches?"3":"0":"0";this.Aa=_.jm(a.getData("pcon"),"-1")}VYb(){return["pcon",this.oa]}f0b(){return this.oa!==this.Aa?["pcon",this.oa]:null}};ZNC&&_.Pn(aOC,dOC);var eOC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?"1":window.matchMedia("(prefers-color-scheme: dark)").matches?"2":"0":"0";this.Aa=_.jm(a.getData("pcs"),"0")}VYb(){let a="4";this.oa==="1"?a="2":this.oa==="2"&&(a="3");return["dt19",`${a}`]}f0b(){return this.oa!==this.Aa?["cs",this.oa]:null}};$NC&&_.Pn(aOC,eOC);var fOC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia&&(window.matchMedia("(prefers-reduced-motion)").matches||window.matchMedia("(prefers-reduced-motion: reduce)").matches)?"1":"0";this.Aa=a.getData("prm").Ob()?"1":"0"}VYb(){return["prm23",this.oa]}f0b(){return this.oa!==this.Aa?["prm",this.oa]:null}};YNC&&_.Pn(aOC,fOC);
_.x();
_.v("L8KGxe");
_.$f(_.s0a,class extends _.ko{static Ta(){return{service:{window:_.go}}}constructor(a){super();this.window=a.service.window}get(){return this.window.get()}getDocument(){return this.window.getDocument()}find(a){return(new _.so(this.getDocument().documentElement)).find(a)}});
_.x();
_.MEr=!!(_.Gi[24]>>15&1);_.NEr=!!(_.Gi[24]>>16&1);
_.v("PQ2Aoe");
var JPA=function(a,b){a=`data-${_.oqa(a)}`;return b?`[${a}="${b}"]`:`[${a}]`},KPA=function(a,b,c,d){const e=[];return{ene:document.createTreeWalker(a.commonAncestorContainer,NodeFilter.SHOW_ELEMENT,{acceptNode:f=>{if(!a.intersectsNode(f))return NodeFilter.FILTER_REJECT;if(f instanceof Element&&((c==null?0:c.has(f))||(d==null?0:d.has(f)))){const g=String(e.length);e.push({oNa:f,BSc:c==null?void 0:c.get(f),I6d:d==null?void 0:d.get(f)});f.dataset.copyServiceCallbackId=g;b.push(f)}return f instanceof
Element&&(c==null?0:c.has(f))?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),ygc:e}},MPA=function(a,b,c){const d=[],{ene:e,ygc:f}=KPA(a,d,b,c);for(b=e.currentNode;b;){if(!(b instanceof HTMLElement)){b=e.nextNode();continue}const g=window.getComputedStyle(b);c=g.display==="none"||g.visibility==="hidden"||g.opacity==="0"||g.height==="0px"&&g.width==="0px";d.push(b);if(c)b.dataset.copyServicePrune="";else{g.display!=="contents"&&g.display!=="inline"||b.tagName!=="DIV"||(b.dataset.copyServiceReplaceDivWithSpan=
"");const h=document.createElement("div");LPA.forEach(k=>{const l=g.getPropertyValue(k);l&&h.style.setProperty(k,l)});b.tagName==="IMG"&&(c=g.getPropertyValue("object-fit"))&&(h.style.setProperty("object-fit",c),h.style.setProperty("width",g.getPropertyValue("width")),h.style.setProperty("height",g.getPropertyValue("height")));h.style.cssText&&(b.dataset.copyServiceComputedStyle=h.style.cssText)}b=e.nextNode()}a=a.cloneContents();a.querySelectorAll(JPA("copyServicePrune")).forEach(g=>{g.remove()});
a.querySelectorAll(JPA("copyServiceReplaceDivWithSpan")).forEach(g=>{const h=document.createElement("span");for(;g.firstChild;)h.appendChild(g.firstChild);for(const k of["copyServiceComputedStyle","copyServiceCallbackId"])g instanceof HTMLElement&&k in g.dataset&&(h.dataset[k]=g.dataset[k]);g.replaceWith(h)});d.forEach(g=>{for(const h of["copyServiceComputedStyle","copyServicePrune","copyServiceCallbackId","copyServiceReplaceDivWithSpan"])delete g.dataset[h]});return{fragment:a,ygc:f}},NPA=function(a,
b,c){for(let f=0;f<b.length;f++){var d=String(f);const {oNa:g,BSc:h,I6d:k}=b[f];if(d=a.querySelector(JPA("copyServiceCallbackId",d)))if(c&&k){var e=k(g);e?d.replaceWith(document.createTextNode(e)):d.remove()}else h&&((e=h(g))?d.replaceWith(e):d.remove())}},LPA="font-family font-size font-weight margin text-decoration border-bottom".split(" ");_.$f(_.e3a,class extends _.ko{static Ta(){return{service:{logging:_.Hu,location:_.Uv}}}constructor(a){super();this.Aa=new Map;this.Ca=new Map;this.oa=new Set;this.Ba=b=>{_.MEr&&this.xEa&&_.Ep(this.Pe.oa(),_.Oh(this.xEa,2)).log();if(_.NEr&&b.clipboardData){var c=window.getSelection();if(c&&c.rangeCount!==0){var d=this.rc.location.origin;const {fragment:A,ygc:E}=MPA(c.getRangeAt(0),this.Aa,this.Ca);var e=A,f=E;c=document.createElement("div");c.appendChild(e.cloneNode(!0));NPA(c,f,!1);e=document.createTreeWalker(c,
NodeFilter.SHOW_ELEMENT);for(var g=e.currentNode;g;){if(!(g instanceof HTMLElement)){g=e.nextNode();continue}if("copyServiceCallbackId"in g.dataset){let I;if((I=f[Number(g.dataset.copyServiceCallbackId)])==null?0:I.BSc){g=e.nextNode();continue}}var h=g.dataset.copyServiceComputedStyle;h&&(g.style.cssText=h);if(g.tagName==="A"&&g.getAttribute("href")){h=g;var k=h.getAttribute("href");_.Kc(h,(new URL(k,d)).href)}if(g.tagName==="IMG"){k=d;var l=Number(g.style.width.replace("px","")),p=Number(g.style.height.replace("px",
""));if(g instanceof HTMLImageElement&&g.complete&&l&&isFinite(l)&&g.naturalWidth&&p&&isFinite(p)&&g.naturalHeight&&(h=g.src.startsWith("data:"),!h||g.naturalWidth!==l||g.naturalHeight!==p)&&(k=(new URL(g.src)).origin!==(new URL(k)).origin,h||!k||g.crossOrigin==="anonymous")&&(h=document.createElement("canvas"),k=h.getContext("2d"))){h.width=l;h.height=p;l=h.width/g.naturalWidth;p=h.height/g.naturalHeight;p=g.style.objectFit==="contain"?Math.min(l,p):Math.max(l,p);l=g.naturalWidth*p;p*=g.naturalHeight;
k.drawImage(g,Math.floor((h.width-l)/2),Math.floor((h.height-p)/2),l,p);try{const I=h.toDataURL("image/png");g.src=I}catch(I){}}}g=e.nextNode()}for(d=document.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);c=document.createElement("div");c.appendChild(A.cloneNode(!0));NPA(c,E,!0);var q;c=(q=c.textContent)!=null?q:"";var {T$d:r,HE:u}={T$d:d,HE:c};q=!1;r.hasChildNodes()&&(q=document.createElement("div"),q.appendChild(r),b.clipboardData.setData("text/html",q.innerHTML),q=!0);u&&(b.clipboardData.setData("text/plain",
u),q=!0);q&&b.preventDefault()}}};this.Pe=a.service.logging;this.rc=a.service.location}registerCopyRoot(a){for(const b of this.oa){if(b.contains(a))return;a.contains(b)&&(b.removeEventListener("copy",this.Ba),this.oa.delete(b))}this.oa.has(a)||(a.addEventListener("copy",this.Ba),this.oa.add(a))}setLoggingElement(a){this.xEa=a}addElementCallback(a,b){this.Aa.set(a,b)}addPlainTextCallback(a,b){this.Ca.set(a,b)}});
_.x();
});
// Google Inc.
