loaded_h_0(function(_){var window=this;
_.Uih=_.y("ygEV2c",[_.vfh]);
_.v("ygEV2c");
var Vih=class extends _.m{constructor(a){super(a)}Ba(){return _.t(this,1)}Ma(){return _.t(this,2)}cO(){return _.t(this,3)}gG(){return _.t(this,4)}getAttribute(){return _.t(this,5)}setAttribute(a){return _.Zg(this,5,a)}hasAttribute(){return _.mh(this,5)}getDescription(){return _.t(this,6)}Mh(){return _.wj(this,6)}Da(){return _.B(this,8)}Qa(){return _.He(this,9)}Ca(){return _.Ej(this,15,_.lh())}Sa(){return _.Gj(this,16,_.lh())}Pa(){return _.t(this,20)}La(){return _.Gj(this,21,_.lh())}mla(){return _.He(this,
23)}ix(){return _.n(this,_.AI,27)}Aa(){return _.n(this,_.xgh,31)}Ha(){return _.t(this,30)}T_(){return _.zj(this,32)}};var Wih=class extends _.Wr{static Ta(){return{jsdata:{WD:_.bK},service:{Kna:_.vhh}}}constructor(a){super();this.WD=a.jsdata.WD;this.Kna=a.service.Kna;if(_.Cde){a=this.WD;let b;const c=(b=_.aeh(this.getRoot()))==null?void 0:b.el();c&&_.Vg(c,"blQGUc",a.serialize())}}Aa(a){var b=a.data,c=_.vgh(new _.xgh,_.Vh(b,12));_.mh(b,13)&&_.$g(b,13)&&_.wgh(c,_.$g(b,13));_.mh(b,19)&&_.$g(b,19)&&(a=_.$g(b,19),_.Zg(c,3,a));a=new Vih;var d=this.WD.La();d=_.ok(a,15,d);var e=this.WD.Ma();d=_.Uh(d,8,e);e=this.WD.Ha();
d=_.Zg(d,1,e);e=this.WD.Pa();d=_.Zg(d,2,e);e=_.Fg("q");d=_.Zg(d,25,e);e=b.eD()||this.WD.Sa();d=_.Zg(d,4,e);e=b.cO()||_.wj(this.WD,3);d=_.Zg(d,3,e);e=this.WD.Za();d=_.qk(d,16,e).setAttribute(_.wj(b,15));e=_.Gj(b,16,_.lh());d=_.qk(d,21,e);d=_.Zg(d,13,google.kEI);e=b.ix();d=_.Lb(d,_.AI,27,e);c=_.Lb(d,_.xgh,31,c);d=_.Xh(b,20);c=_.Sh(c,32,d);d=_.wj(this.WD,14);_.Zg(c,20,d);_.Ge(b,18)&&(b=_.Uj(b,18),_.wi(a,9,b));this.WD.rb()&&(b=_.$g(this.WD,16),_.Zg(a,30,b));var f;b={productId:(f=a.Aa())==null?void 0:
f.Nq(),allowNonLoggedInFeedback:!0,enableAnonymousFeedback:!1};var g;if((g=a.Aa())==null?0:_.mh(g,2)){let l;b.bucket=(l=a.Aa())==null?void 0:_.t(l,2)}let h;if((h=a.Aa())==null?0:_.mh(h,3)){let l;b.triggerId=(l=a.Aa())==null?void 0:_.t(l,3)}f={expi:a.Ca().join(","),gl:a.Ba(),hl:a.Ma(),internal:a.Da(),vertical_id:a.Sa().join(" "),time:Date.now(),ei:google.kEI,query:_.Fg("q"),entity_id:a.gG(),entity_name:a.cO(),attribute:a.getAttribute(),secondary_entity_id:a.La().join(" "),osrp_ui_vertical:a.Ha(),ve_id:a.Qa(),
fb_ingest:a==null?void 0:a.serialize(),feature_tag:a.T_(),user_interface:a.Pa(),is_dark_theme:!!document.body.dataset.dt};let k;(g=(k=a.ix())==null?void 0:_.dUd(k))&&Object.assign(f,Object.fromEntries(g));_.oS(b,f)}oa(a){_.thh(this.Kna,a.data,this.WD,[],!1,void 0,void 0,this.getData("eau").Ob())}};Wih.prototype.$wa$UhDUnd=function(){return this.oa};Wih.prototype.$wa$y64mt=function(){return this.Aa};_.Yr(_.Uih,Wih);
_.x();
});
// Google Inc.
