loaded_h_0(function(_){var window=this;
_.SVb=_.y("YjTCDb",[_.cr]);
_.v("YjTCDb");
var TVb,UVb;TVb=function(a,b){let c=b.el();for(b=c.parentElement;c!==document.body;b=b.parentElement)Array.from(b.children).forEach(d=>{d!==c&&d.getAttribute("aria-hidden")!=="true"&&(_.wo(new _.so(d),"aria-hidden",!0),a.Da.push(d))},a),c=b};UVb=function(a){a.Da.forEach(b=>{b.removeAttribute("aria-hidden")});a.Da=[]};
_.VVb=class extends _.Rv{constructor(a){super(a.Ac);this.Ba=!1;this.container=new _.oo([]);this.Ha=!1;this.Da=[];this.Ca=[];this.Ia=new _.ESb(null)}isOpen(){return this.Ba}open(a,b,c=!1){this.Ba||(this.Ia=new _.ESb(document.activeElement),this.VGa=_.Pg(a.el(),"MH4mvf",this.La,this),this.container=a,TVb(this,a),c?_.GSb(this,a):_.Pv(this,a,b),this.Ba=this.Ha=!0)}close(a=!0){this.Ba&&(this.Ba=!1,this.Ca.forEach(b=>{b.remove();document.body.appendChild(b)}),this.Ca=[],UVb(this),_.Qv(this.container),this.VGa&&
_.Qg(this.VGa),this.Ha=!1,a&&this.Ia.restore(),this.container=new _.oo([]))}La(a){a=_.Ig(a).container;if(!this.Ca.includes(a)){a.remove();a.removeAttribute("aria-hidden");var b=this.container.el();this.Ha?b.insertBefore(a,b.lastElementChild):b.appendChild(a);this.Ca.push(a)}}};_.$f(_.SVb,_.VVb);
_.x();
_.PVb=_.y("q00IXe",[_.em]);
_.v("q00IXe");
var QVb;QVb=function(a,b){return[{element:a.getRoot().hb(),Gx:"vLITie",vL:a.oa},{element:a.getRoot().hb(),Gx:"ho8p1c",vL:b===1},{element:a.getRoot().hb(),Gx:"vnmqGf",vL:b===2},{element:a.Ka("DUjDrd").hb(),Gx:"HEeD1c",vL:b===3},{element:a.Ka("DUjDrd").hb(),Gx:"uT5fcc",vL:b===4}]};
_.RVb=class extends _.Wr{static Ta(){return{service:{Bc:_.Hu}}}constructor(a){super();this.oa=!1;this.position=0;this.Pb=a.service.Bc;this.setPosition(2);this.id=_.im(this.getData("cid"));this.trigger("w3NMIc",{controller:this});this.getRoot().Tc("aria-labelledby")!==null&&_.wo(this.Ka("okoQgd").parent(),"id",this.getRoot().Tc("aria-labelledby"))}Pa(a){a=a.wb.el();this.trigger("qPDdOb",{triggerElement:a})}Ma(a){a=a.wb.el();this.trigger("uLpOF",{triggerElement:a})}getId(){return this.id}setPosition(a,
b=!0){this.position=a;b&&(a=QVb(this,a),(new _.TRb(a,[],0,0)).open())}Ha(){this.position===1&&this.setPosition(3)}Ia(){this.position===1&&this.setPosition(4)}La(){this.position!==3&&this.position!==4||this.setPosition(1)}Da(){return QVb(this,this.oa?1:4)}Ba(){return QVb(this,2)}Aa(){return this.Ka("okoQgd")}Ca(){return this.Ka("okoQgd").el()}};_.RVb.prototype.$wa$Hv3npb=function(){return this.Ca};_.RVb.prototype.$wa$l8ZHOd=function(){return this.Aa};_.RVb.prototype.$wa$fSVRId=function(){return this.Ba};
_.RVb.prototype.$wa$y8p6Dd=function(){return this.Da};_.RVb.prototype.$wa$jji5be=function(){return this.La};_.RVb.prototype.$wa$Na055d=function(){return this.Ia};_.RVb.prototype.$wa$F3V9ae=function(){return this.Ha};_.RVb.prototype.$wa$pTuYge=function(){return this.getId};_.RVb.prototype.$wa$AuQwcb=function(){return this.Ma};_.RVb.prototype.$wa$jJaprb=function(){return this.Pa};_.Yr(_.PVb,_.RVb);
_.x();
_.ww=_.y("Fh0l0",[_.Tq,_.SVb,_.Rq,_.em,_.Nq]);
var CWb=class extends _.m{constructor(a){super(a)}Ba(){return _.He(this,1)}Ha(a){return _.wi(this,1,a)}Ca(){return _.Qe(this,1)}Da(){return _.Ge(this,1)}Aa(){return _.He(this,2)}Pa(a){return _.wi(this,2,a)}La(){return _.Qe(this,2)}Ma(){return _.Ge(this,2)}};CWb.prototype.ob="cV628";var DWb={C6(){return["padt","padb"]},Bo(a,b){a=new _.gw(a.searchParams,b);_.Zv(a,"padt",b.Ha,b.Ca);_.Zv(a,"padb",b.Pa,b.La)},zp(a,b){b=new _.gw(b.searchParams,a);_.bw(b,a.Da,a.Ba,"padt");_.bw(b,a.Ma,a.Aa,"padb")}};var EWb;EWb=null;_.FWb=class extends _.uw{constructor(a,b){super(a);new _.vw(this);_.sw(b,this,new _.rw(DWb))}static Er(){return CWb}static xs(a){return EWb?EWb:EWb=_.qw().then(b=>{b=new _.FWb(CWb,b);b.initialize(a);return b})}};_.Wo.cV628=_.Vo;
_.sWb=class extends _.vQb{constructor(a,b){super();this.open=a;this.close=b}};
_.rWb=class extends _.m{constructor(a){super(a)}Ca(){return _.Gk(this,1)}La(){return _.Xh(this,1)}Pa(){return _.Jj(this,2,_.lh())}Ba(){return _.Jj(this,2,3,void 0,!0).length}Ma(){return _.Jj(this,3,_.lh())}Aa(){return _.Jj(this,3,3,void 0,!0).length}Ha(){return _.Jj(this,4,_.lh())}mva(a){return _.Kj(this,4,a)}Da(){return _.Jj(this,4,3,void 0,!0).length}};_.rWb.prototype.ob="ol26e";
_.v("Fh0l0");
var VWb,WWb,XWb,aXb,hXb,gXb,eXb,fXb,iXb,jXb,bXb,cXb,YWb,ZWb,$Wb,dXb,kXb,lXb,mXb,nXb;VWb=function(a,b){const c=a.oa?1:4;a.position!==c&&a.setPosition(c,b)};WWb=[1,2];XWb=function(a){a=a!=null?a:new _.rWb;if(!a.Ca()){const b=a.Aa()>0;a.Ba()>0&&!b?_.Sh(a,1,2):_.Sh(a,1,1)}return a.qe()};
aXb=function(a,b,c){if(a.oa){var d=a.Aa;if(d!==void 0){var e=a.Ca,f=d.Ca(),g=YWb(a),h=ZWb(a,{tUd:g,bpa:c});h=_.yv(_.Av(_.zv(_.WRb(_.wv(new _.Bv,q=>$Wb(a,q)),a.zJb),!0),1),h);var k,l=(k=a.Ia.Jfc)!=null?k:a.Jfc;if(l){_.xv(h,[...WWb,4]);let q;k=(q=a.Ia.czd)!=null?q:()=>{aXb(a,b,c)};_.XRb(h,l,k)}a.Ia.XFc&&_.aSb(h,a.Ia.XFc);a.Ia.ajb&&_.xv(h,a.Ia.ajb);var p=()=>{bXb(a,d);cXb(a,[[a,1],[d,1]],b)};e.style.position="fixed";c===void 0?(_.ZRb(h,f),a.Ef.open(e,h),p()):(_.cSb(h),a.Ef.open(e,h).then(async()=>{var q=
(0,_.Qf)(),r=q();q=q(1);try{if(q(await r(dXb(a,c)))){q(await r(g.open()));a.Xa=new _.UWb(e);_.SWb(a.Xa);var u;(u=_.IWb(f,-1)?f:_.RWb(a.Xa,0))==null||u.focus();p()}}finally{r()}}))}}};hXb=function(a,b,c){const d=a.Aa;d!==void 0&&(eXb(a),c===void 0?fXb(a,d,b):c.then(()=>{a.isOpen&&c===a.bpa&&(gXb(a,c),fXb(a,d,b))},()=>{a.close()}))};gXb=function(a,b){a.bpa===b&&(a.bpa=void 0)};
eXb=function(a){if(a.rb&&a.Ha){const b=_.EUb("stUuGf");b&&!b.contains(a.Ha)&&(b.appendChild(a.Ha),_.jn(b,!0),a.Sa=b.style.visibility,b.style.visibility="visible",b.offsetHeight)}a.Cb||!a.Vf.isAvailable()||(a.Qb=a.Vf.isInBasicMode())||a.Vf.enterBasicMode(15);a.container.hasClass("ho8p1c")||a.container.addClass("ho8p1c");iXb(a);jXb(a)};fXb=function(a,b,c){bXb(a,b);const d=b.Aa();a.yJa.open(a.Jb,d);cXb(a,[[a,1],[b,1]],c)};
iXb=function(a){a.Qa&&_.rn(a.Qa);a.Qa=_.ne(window,"scroll",c=>{const d=c.target;d&&!_.qi(a.container).contains(d)&&_.Pr(c)},!0);const b=a.ssb.get().Ba();window.scrollY<b&&window.scrollTo(0,b);a.Wa=window.scrollY;a.Pa.style.top=`-${a.Wa}px`;_.om.add(a.Pa,"aKl9bd")};jXb=function(a){a.wq.listen(a.Ca,b=>a.onDismiss(b),WWb,!1,!0)};bXb=function(a,b){a.La=b;for(const c of a.Ba.values())VWb(c,!a.oa)};
cXb=function(a,b,c){a=_.Ep(a.Pb.oa(),c&&new _.Nh(_.Ie(c),3));for(const [d,e]of b)b=e,_.Hp(a,d.getRoot().el(),b);a.log(!0)};YWb=function(a){const b=[],c=[];for(const d of a.Ba.values())b.push(...d.Da()),c.push(...d.Ba());return new _.TRb(b,c,a.ub,a.ub)};ZWb=function(a,{tUd:b,bpa:c}){return new _.sWb(async()=>{var d=(0,_.Qf)(),e=d();d=d(1);try{c===void 0&&d(await e(b.open()))}finally{e()}},async()=>{var d=(0,_.Qf)(),e=d();d=d(1);try{a.bpa!==void 0?gXb(a,a.bpa):d(await e(b.close()))}finally{e()}})};
$Wb=function(a,{eventType:b}){if(!a.oa)return!1;if(!a.isOpen)return!0;if(a.bpa===void 0){kXb(a);cXb(a,[[a,2],[a.La,2]]);let c;(c=a.Xa)==null||_.TWb(c);a.Xa=void 0}lXb(a);a.trigger("Yaup7b",{NRc:b});a.isOpen=!1;return!0};dXb=async function(a,b){var c=(0,_.Qf)(),d=c();c=c(1);try{let e=!1;try{c(await d(b))}catch(f){c(),e=!0}if(!a.isOpen||b!==a.bpa)return!1;if(e)return a.close(),!1;gXb(a,b);return!0}finally{d()}};
kXb=function(a){for(const b of a.Ba.values())b.setPosition(2,!a.oa);a.oa||a.wq.unlisten(a.Ca);a.Za=[]};lXb=function(a){if(a.rb){const b=window.matchMedia("(prefers-reduced-motion: reduce)").matches?0:a.ub;(0,_.Yn)(()=>{a.Ha&&!a.getRoot().el().contains(a.Ha)&&a.getRoot().el().appendChild(a.Ha);const c=_.EUb("stUuGf");c&&a.Sa&&(c.style.visibility=a.Sa,a.Sa=null)},b)}};
mXb=function(a,b,c){if(a.isOpen&&a.bpa===void 0){var d=a.La,e=!1;if(c===void 0){c=a.Za.pop();if(!c)return;d.Ia();e=!0}else a.Za.push(d),d.Ha();a.trigger("wO8kFd",{plf:e});a.La=c;c.La();c.Aa().focus();cXb(a,[[d,2],[c,1]],b)}};nXb=function(a,b){if(a.Aa!==b){var c=a.Aa;c&&(c.oa=!1);b.oa=!0;a.Aa=b;if(a.isOpen){a.Za=[];for(const d of a.Ba.values())VWb(d,!0);b.Aa().focus();a.La=b;b=[[b,1]];c&&b.push([c,2]);cXb(a,b)}}};
_.xw=class extends _.Wr{static Ta(){return{Iua:{container:"haAclf"},Xe:{zJb:_.rWb},We:{ssb:_.FWb},service:{wq:_.tv,yJa:_.VVb,overlay:_.sv,Bc:_.Hu,Vf:_.Pu}}}constructor(a){super();this.Za=[];this.La=null;this.Ba=new Map;this.Wa=0;this.Qa=null;this.isOpen=!1;this.Sa=null;this.Qb=!1;this.Ia={};this.ssb=a.We.ssb;this.wq=a.service.wq;this.yJa=a.service.yJa;this.Ef=a.service.overlay;this.Ha=this.Ka("eQ1It").el();this.container=new _.so(a.Iua.container);this.Jb=this.Ka("ryFRZc");this.Ca=this.Jb.hb();this.Pb=
a.service.Bc;this.Pa=document.body;this.Vf=a.service.Vf;const b=this.getRoot().el(),c=["click"];this.getData("ct").Ob()&&c.push("touchstart","touchmove","touchend","touchcancel");for(const d of c)_.Pg(b,d,()=>{});this.oa=this.getData("os").Ob();this.Cb=this.getData("dh").Ob();this.oa&&(this.zJb=XWb(a.Xe.zJb));this.rb=this.getData("dd").Ob();this.ub=Number(_.jm(this.getData("dd"),"").replace(/ms$/,""))||0;this.Jfc=_.si(this.getData("db"));(this.oa||this.rb)&&_.Io(this,this.oa?this.Ca:this.Ha)}Ma(a){if(!this.Da)if(this.Aa===
void 0)this.Da=()=>{this.Da=void 0;this.Ma(a)};else{var b=Promise.resolve(a);this.isOpen||(this.isOpen=!0,this.bpa=b,this.oa?aXb(this,void 0,b):hXb(this,void 0,b))}}oL(a){this.open(a.targetElement.el())}open(a){this.Da||(this.Aa===void 0?this.Da=()=>{this.Da=void 0;this.open(a)}:this.isOpen||(this.isOpen=!0,this.oa?aXb(this,a):hXb(this,a),this.notify("BUYwVb")))}stopPropagation(){}onClose(){this.close()}close(){this.isOpen&&(this.oa?this.Ef.close(this.Ca):this.wq.dismiss(this.Ca))}onDismiss(a){if(!this.isOpen)return!0;
this.bpa!==void 0?gXb(this,this.bpa):(kXb(this),cXb(this,[[this,2],[this.La,2]]));this.yJa.close();this.CT();this.container.removeClass("ho8p1c");lXb(this);this.Cb||!this.Vf.isAvailable()||this.Qb||this.Vf.exitBasicMode(15);this.trigger("Yaup7b",{NRc:a});this.isOpen=!1;return!0}CT(){_.om.remove(this.Pa,"aKl9bd");this.Pa.style.top="";window.scrollY!==this.Wa&&window.scrollTo(0,this.Wa-_.gVb());const a=this.Qa;a&&_.pe(()=>{_.rn(a)});this.Qa=null;_.rVb(this.Pa)}Wb(a){a=a.data.controller;const b=a.getId();
if(b===null||b===""||b==="OWXEXe")throw Error("Ff`"+(b!=null?b:"<null>"));if(this.Ba.has(b))throw Error("Gf`"+b);this.Ba.set(b,a);this.Aa===void 0&&(this.Aa=a,a.oa=!0,this.Da&&(0,_.Yn)(this.Da,0));this.isOpen&&VWb(a,!0);let c;(c=this.Kb)==null||c.call(this,b,a)}Tb(a){const b=this.Ba.get(a.data.HWb);b&&mXb(this,a.targetElement.el(),b)}Rb(a){mXb(this,a.targetElement.el())}Lb(a){this.Ia=a}qc(a){const b=a.data.HWb;(a=this.Ba.get(b))?nXb(this,a):this.Kb=(c,d)=>{c===b&&(nXb(this,d),this.Kb=void 0)}}Vb(){this.wq.unlisten(this.Ca);
super.Vb()}};_.xw.prototype.$wa$k4Iseb=function(){return this.Vb};_.xw.prototype.$wa$mYaVb=function(){return this.qc};_.xw.prototype.$wa$acPBse=function(){return this.Rb};_.xw.prototype.$wa$Ib7Hzd=function(){return this.Tb};_.xw.prototype.$wa$yhG2Rd=function(){return this.Wb};_.xw.prototype.$wa$TvD9Pc=function(){return this.close};_.xw.prototype.$wa$tTT8Tc=function(){return this.onClose};_.xw.prototype.$wa$mLt3mc=function(){return this.stopPropagation};_.xw.prototype.$wa$kvzNsb=function(){return this.oL};
_.Yr(_.ww,_.xw);
_.x();
_.vz=function(a){return _.t(a,49)};_.wz=function(a){return _.t(a,48)};_.xz=!!(_.Gi[53]>>27&1);
_.v("FRLJrd");
var WOc,YOc,XOc;_.UOc=function(a,b,c,d=!1){a=a.getWindow().innerHeight;a=(d?b.top:b.bottom)+c-a;b=-((d?b.bottom:b.top)-c);c=b>0?b>window.scrollY:!1;return a>0&&b<a&&!c};_.VOc=function(a,b){let c;return!!(a.um().el().contains(b)||a.getRoot().el().contains(b)||((c=a.oa())==null?0:c.contains(b)))};
WOc=function(a,b){if(b){var c=b.oa();if(c){a=a.um().el();var d=_.fn(a);if(d.height<a.scrollHeight){var e=a.getBoundingClientRect().top;const f=_.fn(c);c=c.getBoundingClientRect().top-e;e=f.height/2;c<e?a.scrollTop+=c-e:c+f.height>d.height-e&&(a.scrollTop+=c+f.height-d.height+e)}}b.focus()}};YOc=function(a,b,c){return(b?XOc(a,!0,c):a.Ba()).find(d=>{d=d.getContent();return _.qaa(d,a.prefix)})||null};
XOc=function(a,b,c){a=a.Ba();c===null&&(c=b?_.va(a):a[0]);if(c){const d=a.findIndex(e=>e===c);a=_.spb(a,b?-d-1:-d)}return a};
_.yz=class extends _.Wr{static Ta(){return{service:{Bc:_.Hu,overlay:_.sv},Bd:{Df:{jsname:"eQ1It",ctor:_.xw}}}}constructor(a){super();this.Gc=this.getData("mb").Ob();this.Xc=!this.getData("dr").Ob();this.yf=!this.getData("dz").Ob();this.Oe=this.getData("bsis").Ob();this.prefix="";this.Jb=!this.Gc;this.dH=!1;this.Ca=new Set;this.Pb=a.service.Bc;this.Ef=a.service.overlay;this.Df=a.Bd.Df;this.um=_.un(()=>this.Ka("xl07Ob"));this.Kc=_.un(()=>this.qb("H9P06b"));this.Lb=()=>this.um().hb();this.Tb=new _.zr(this.Wc,
1E3,this);_.ui(this,this.Tb);this.Df||_.ui(this,(new _.he(this)).listen(window,"resize",_.wn(()=>{this.dH&&this.Xa()},250)))}qc(){const a=this.Ba().filter(b=>b.isSelected());this.Ca=new Set(a);this.Ca.size>1&&this.clearSelection(a[0])}clearSelection(a){for(const b of this.Ca)b!==a&&b.Lk(!1);this.Ca=a?new Set([a]):new Set}ji(a){if(a){let b;(b=this.oa())==null||b.setAttribute("disabled","");let c;(c=this.oa())==null||c.classList.add("disabled")}else{let b;(b=this.oa())==null||b.removeAttribute("disabled");
let c;(c=this.oa())==null||c.classList.remove("disabled")}}Rb(){let a;((a=this.oa())==null?0:a.hasAttribute("disabled"))||(this.dH?this.close():this.open())}Pa(a){a=_.wv(_.xv(_.fSb(_.gSb(_.yv(_.URb(new _.Cv,2),this.getAnimation()),a),a),[1,2,3]),b=>this.Ma(b));this.Xc&&(_.zv(a,!0),this.yf&&_.aSb(a,127),_.Io(this,this.um().hb()));return a}open(){this.Aa()}async Aa(){var a=(0,_.Qf)(),b=a();a=a(1);try{this.qc();const d=this.oa();if(!this.dH&&d){if(this.Df)this.Df.open(this.oa()||void 0);else if(this.Oe)this.trigger("zh0nQd",
{HWb:this.um().hb().id}),this.Qb();else{const e=this.Pa(d);a(await b(this.Ef.open(this.Lb(),e)));this.rb(!0);this.Wa(!0)}this.dH=!0;var c=this.Ca.size>0;this.getRoot().getData("e").Ob()&&(this.getRoot().toggleClass("x1SoId",c),this.getRoot().toggleClass("wYGjQ",!c));this.trigger("Yi86H")}}finally{b()}}close(){this.dH&&(this.Df?(this.Df.close(),this.Kb()):this.Ef.close(this.Lb()))}Kb(){this.dH=!1;this.trigger("L7T4N")}ub(a,b,c,d=!1){a=_.UOc(this,a,b);return d?a?[12,13]:[13,12]:a?[8,9]:[9,8]}Wb(a,b){const c=
this.getWindow().innerWidth;return{JLc:!1,h7c:Math.max(b-(c-(_.xz?c-a.right:a.left)-8),0)}}Xa(){const a=this.oa();if(a){var b=a.getBoundingClientRect(),c=this.um().hb();this.um().setStyle("width","");this.um().setStyle("max-width","");var d=this.Gc?b.width||0:Math.ceil(c.getBoundingClientRect().width),{JLc:e,h7c:f}=this.Wb(b,d);f>0&&this.Jb&&(d-=f);this.um().setStyle("width",`${d}px`);this.um().setStyle("max-width",`${d}px`);c=c.offsetHeight;var [g,h,k]=this.ub(b,c,d,e);_.kw(a,g,this.um().el(),h,
k,void 0,void 0,new _.Od(d,c))}}getAnimation(){const a=[{element:this.um().hb(),Gx:"vpR9sb",vL:!0}],b=[{element:this.um().hb(),Gx:"vpR9sb",vL:!1}],c=new _.TRb(a,b,0,0);return new _.sWb(async()=>{var d=(0,_.Qf)(),e=d();d=d(1);try{let f;(f=this.Kc())==null||f.addClass("vpR9sb");this.Xa();d(await e(c.open()))}finally{e()}},async()=>{var d=(0,_.Qf)(),e=d();d=d(1);try{d(await e(c.close()));let f;(f=this.Kc())==null||f.removeClass("vpR9sb")}finally{e()}})}Ma(){this.um().setStyle({top:"",right:"",bottom:"",
left:""});this.dH=!1;this.rb(!1);this.trigger("L7T4N");this.Wa(!1);return!0}Qb(){var a=_.Gma(this.oa());a=_.Oh(a,3,0);_.Ep(this.Pb.oa(),a).log(!0)}Wa(a){var b=a?_.Gma(this.oa()):null;b=_.Oh(b,3,a?0:1);const c=this.Pb.oa();_.Ep(c,b);_.Hp(c,this.um().el(),a?1:2);c.log(!0)}Wc(){this.prefix=""}NK(a){return this.Ba().find(b=>b.oa()===a)}selected(a){this.close();this.clearSelection();a.source instanceof _.TOc&&this.Ca.add(a.source);this.trigger("oJ9QV");return!0}wQb(a){a.source instanceof _.TOc&&this.Ca.delete(a.source);
this.trigger("oJ9QV");this.close();return!0}Pk(a){const b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode;if(c===27||c===9)return!0;let d;if(((d=this.oa())==null?0:d.contains(a.targetElement.el()))&&c===40){WOc(this,this.Sa());let h;(h=b.stopPropagation)==null||h.call(b);let k;(k=b.preventDefault)==null||k.call(b);return!1}a=a.targetElement.el();if(!this.um().el().contains(a))return!1;a=this.zc();if(c===40||c===38){if(!(c===40&&a===this.Fc()||c===38&&a===
this.Sa())){c=c===40;a=XOc(this,c,a);var e;c=(e=c?a.shift():a.pop())!=null?e:null;WOc(this,c)}}else{if(c===13||c===32&&!this.prefix)return!0;_.YJa(c)&&(this.Tb.start(),e=String.fromCharCode(c),this.prefix===e?e=YOc(this,!0,a):(this.prefix+=e,e=YOc(this,!1,a)),e&&WOc(this,e))}let f;(f=b.stopPropagation)==null||f.call(b);let g;(g=b.preventDefault)==null||g.call(b);return!1}Sa(){return this.Ba()[0]||null}Fc(){const a=this.Ba();return a.length>0?a[a.length-1]:null}zc(){return this.Ba().find(a=>a.oa().contains(document.activeElement))||
null}};_.yz.prototype.$wa$rdwPFf=function(){return this.zc};_.yz.prototype.$wa$vpeaX=function(){return this.Fc};_.yz.prototype.$wa$VZgx0c=function(){return this.Sa};_.yz.prototype.$wa$uYT2Vb=function(){return this.Pk};_.yz.prototype.$wa$AOJsKd=function(){return this.wQb};_.yz.prototype.$wa$gk6SMd=function(){return this.selected};_.yz.prototype.$wa$hmHDoe=function(){return this.Qb};_.yz.prototype.$wa$fnBGHd=function(){return this.getAnimation};_.yz.prototype.$wa$s54zIe=function(){return this.Xa};
_.yz.prototype.$wa$b7PJRd=function(){return this.Kb};_.yz.prototype.$wa$TvD9Pc=function(){return this.close};_.yz.prototype.$wa$rpDY5c=function(){return this.Aa};_.yz.prototype.$wa$FNFY6c=function(){return this.open};_.yz.prototype.$wa$gq6u4d=function(){return this.Rb};_.yz.prototype.$wa$JHxHSe=function(){return this.qc};
_.x();
_.bPc=_.er("FRLJrd",[_.em,_.Rq,_.ww]);
_.cPc=_.y("eBYPP",[_.$Oc,_.bPc]);
_.v("eBYPP");
_.dPc=class extends _.yz{static Ta(){return{controllers:{items:{jsname:"qRxief",ctor:_.aPc}}}}constructor(a){super(a.Ac);this.Da=this.getData("sm").Ob();this.Jb=!this.Da;this.Ax=a.controllers.items;this.Ha=_.un(()=>{const b=this.Ka("oYxtQd");return b.el()?b:null})}Ba(){return[...this.Ax]}oa(){let a;return((a=this.Ha())==null?void 0:a.hb())||null}Pa(a){a=super.Pa(a);this.Da?_.eSb(a,1):_.eSb(a,3);this.Da||_.VRb(a,2,{stack:[2]});return a}open(){this.Aa()}async Aa(){var a=(0,_.Qf)(),b=a();a=a(1);try{a(await b(super.Aa()));
const d=this.oa();if(this.Da){var c;(c=this.Sa())==null||c.focus();this.Df||d&&!d.classList.contains("Esm33e")&&d.classList.add("Esm33e")}}finally{b()}}Ma(a){if(a=super.Ma(a)){let b;(b=this.oa())==null||b.classList.remove("Esm33e")}return a}rb(a){let b,c;(c=this.Da?(b=this.oa())==null?void 0:b.querySelector('[role="button"]'):this.oa())==null||c.setAttribute("aria-expanded",a.toString())}Cb(){this.Da&&this.Aa();return!0}Za(a){let b;this.Da&&!_.VOc(this,(b=a.data)==null?void 0:b.relatedTarget)&&this.close();
return!0}Pk(a){if(!this.Da)return super.Pk(a);var b=a.event;b=b.which||b.keyCode;var c=this.oa();const d=!_.xz;c=c==null?void 0:c.contains(a.targetElement.el());const e=d&&b===39||_.xz&&b===37;if(c&&!e)return!0;c&&e?this.dH||this.Aa():(d&&b===37||_.xz&&b===39)&&this.close();return super.Pk(a)}Qa(a){let b;((b=a.data)==null?0:b.Krc)||this.close();return!0}close(){super.close()}ub(a,b,c,d){if(this.Da){d=getComputedStyle(this.um().hb()).paddingTop.replace("px","");d=new _.Nd(0,-1*(Number(d)||0));b=_.UOc(this,
a,b,!0);const e=(a.left-c)*-1;a=a.right+c-this.getWindow().innerWidth;a=(_.xz?e>0&&a<e:a>0&&e<a)?b?[9,13,d]:[8,12,d]:b?[13,9,d]:[12,8,d]}else a=super.ub(a,b,c,d);return a}Wb(a,b){var c=this.getWindow().innerWidth;const d=this.Jb?8:0;c=a.left+b+d-c;a=(a.right-b-d)*-1;return{JLc:_.xz?a>0&&c<a:c>0&&a<c,h7c:Math.max(Math.min(c,a),0)}}Wa(a){this.Da||super.Wa(a)}Vb(){this.La&&_.Qg(this.La);this.Ia&&_.Qg(this.Ia);super.Vb()}};_.dPc.prototype.$wa$k4Iseb=function(){return this.Vb};
_.dPc.prototype.$wa$TvD9Pc=function(){return this.close};_.dPc.prototype.$wa$Seb4Qb=function(){return this.Qa};_.dPc.prototype.$wa$uYT2Vb=function(){return this.Pk};_.dPc.prototype.$wa$veZYT=function(){return this.Za};_.dPc.prototype.$wa$fRYjtf=function(){return this.Cb};_.dPc.prototype.$wa$rpDY5c=function(){return this.Aa};_.dPc.prototype.$wa$FNFY6c=function(){return this.open};_.dPc.prototype.$wa$Wn4E8e=function(){return this.oa};_.dPc.prototype.$wa$kKeMjf=function(){return this.Ba};
_.Yr(_.cPc,_.dPc);
_.x();
_.N0=function(a){return`[jsname="${a}"]`};_.Sir=_.N0("ZLxsqf");_.Tir=_.N0("E6JrNd");
_.wus=function(a){return`\n\n##########################################################################
### ${a}
##########################################################################`};_.xus=function(a){const b=document.body.querySelector(_.N0("UCHPqc"));if(!b)return null;const c=document.createElement("div");c.id=a;c.classList.add("ktvLwd");b.appendChild(c);return c};_.zus=function(){let a;const b=((a=_.yus("OYkqOb"))==null?void 0:a.getAttribute("href"))||"";if(b)return{name:"/search",link:b}};
_.Bus=function(){let a=_.Aus("D2tCC");a=a.length>0?a:_.Aus("lro_sherlog_link_");return[...a.map(b=>{b=b.getAttribute("href")||"";return{link:b,name:b.includes("Darksteel+Widget")?"MagiLRO - Widget":"MagiLRO"}}),..._.Aus("KXEGMc").map(b=>({link:b.getAttribute("href")||"",name:"/async/folftch"})),..._.Aus("pJjOnd").map(b=>{let c,d;return{link:b.getAttribute("href")||"",name:((c=b.innerText)==null?void 0:(d=c.replace("Sherlog",""))==null?void 0:d.trim())||"Async"}})].filter(b=>b.link)};
_.yus=function(a,b=document.body){return[...b.querySelectorAll(_.N0(a))].at(-1)};_.Aus=function(a,b=document.body){return[...b.querySelectorAll(_.N0(a))]};_.Cus=function(a){const b=new URL("https://searchdebugger.corp.google.com/past/debug/overview");b.searchParams.set("testsherlogurl",a);return b};_.Dus=_.wus("Previous Turn");
_.YOq=_.y("zouQy",[_.Kq,_.Vq]);
_.UOq=_.y("DOjgn",[]);
_.$$e=function(a,b){b=_.npa({Cc:b},!1);b=_.If(b);try{return _.Of(a instanceof _.bc?_.xpa(a):a)}finally{_.If(b)}};
_.v("zouQy");
var oxs=function(a){a.style.display=a.style.display!=="block"?"block":"none"},pxs=class extends _.Wr{static Ta(){return{service:{rc:_.Uv,Yb:_.Bz}}}constructor(a){super();this.Aa=document.body.querySelector(_.N0("j4auif"));this.oa=document.body.querySelector(_.N0("dGolQe"));this.Ca=document.body.querySelector(_.N0("EljlOd"));this.Ba=document.body.querySelector(_.N0("M3wrwe"));this.rc=a.service.rc;this.Yb=a.service.Yb}Pa(){const a=document.body.querySelector("#memory-drawer");oxs(a)}async Ma(){var a=
(0,_.Qf)(),b=a();a=a(1);try{const c=a(await b(_.$$e(_.Nq,this.yr()))),d=document.body.querySelector("#feedback-drawer");oxs(d);d.style.display==="block"?(window.scrollTo({top:0,behavior:"instant"}),_.iSi&&c.isAvailable()&&a(await b(c.enterBasicMode(65)))):_.iSi&&c.isAvailable()&&c.isInBasicMode()&&a(await b(c.restoreToPreviousState(65)))}finally{b()}}async Da(){this.notify("MCziPc");if(!document.body.querySelector("#debug-drawer")&&this.Ba){var a=_.xus("debug-drawer");a&&(a.replaceChildren(this.Ba),
this.Ba.style.display="block")}a=document.body.querySelector("#debug-drawer");oxs(a)}async La(){if(this.Aa&&this.oa&&(this.Aa.toggleAttribute("hidden"),!this.Aa.hasAttribute("hidden"))){this.oa.remove();var a=_.Yt().get("q");a=(0,_.vc)`https://www.google.com/search?q=${a}&igu=1&gsc=1`;_.Lc(this.oa,a);this.Aa.appendChild(this.oa)}}async Ha(){var a=(0,_.Qf)(),b=a();a=a(1);try{this.Ca&&a(await b(_.Go(this,this.Ca))).oa()}finally{b()}}async Ia(){const a=new _.Xt(this.rc.If());a.searchParams.delete("csuir");
a.searchParams.delete("mstk");this.Yb.navigateTo(_.pc(a.toString()))}};pxs.prototype.$wa$m8mq3=function(){return this.Ia};pxs.prototype.$wa$jmJuMb=function(){return this.Ha};pxs.prototype.$wa$BgSDEb=function(){return this.La};pxs.prototype.$wa$vPcAUd=function(){return this.Da};pxs.prototype.$wa$FLqQwf=function(){return this.Ma};pxs.prototype.$wa$aVVNTe=function(){return this.Pa};_.Yr(_.YOq,pxs);
_.x();
_.yzq=_.y("zLjACb",[]);
var D1e,E1e,F1e;D1e=function(){var a=document;_.jAa(a);return a.__gwbp};_.G1e=function(){E1e||(E1e=D1e().then(a=>F1e=a));return E1e};_.G1e();var H1e=Event;_.I1e=class extends H1e{constructor(a){super(a,{bubbles:!0});F1e.addEvent(a)}};
_.v("zLjACb");
var cDr=class extends _.I1e{constructor(){super("aimNavigateToZeroState")}};var dDr=class extends _.I1e{constructor(){super("aimOpenThreadsView")}};var eDr=class extends _.Wr{static Ta(){return{}}oa(a){_.iw(a.wb.el());let b;(b=document.querySelector('[data-xid="Lr04i"]'))==null||b.dispatchEvent(new dDr);let c;(c=document.querySelector('[data-xid="m3fCN"]'))==null||c.dispatchEvent(new dDr)}Aa(a){_.iw(a.wb.el());let b;(b=document.querySelector('[data-xid="Lr04i"]'))==null||b.dispatchEvent(new cDr)}};eDr.prototype.$wa$JqmUue=function(){return this.Aa};eDr.prototype.$wa$ez1Xib=function(){return this.oa};_.Yr(_.yzq,eDr);
_.x();
_.Hr=class extends _.m{constructor(a){super(a)}};
_.Fr=new _.Cq("componentConnected");_.Gr=new _.Cq("componentDisconnected");
_.v("YNjGDd");

_.x();
_.cob=function(a,b){return b(`[${a.substring(4)}`)};_.eob=class extends _.m{constructor(a){super(a)}clearValue(){return _.fj(this,_.dob)}};_.dob=[1,2];var fob;fob=class extends _.m{constructor(a){super(a)}clearValue(){return _.fj(this,_.Er)}};_.Er=[2,3,4,5,6,8];var gob=class extends _.m{constructor(a){super(a)}};var hob=class extends _.m{constructor(a){super(a)}getIdentifier(){return _.n(this,gob,1)}XTa(){return _.kh(this,fob,2,_.lh())}qTb(){return _.ej(this,3)}};_.iob=function(a){return _.kh(a,hob,1,_.lh())};_.job=_.Yb(class extends _.m{constructor(a){super(a)}});
_.v("IZT63");
var oob=function(){const a=_.Ela("nQyAE",window);var b=_.Ela("TSDtV",window);if(b&&typeof b==="string"){var c=_.iob(_.cob(b,_.job))[0];if(c){b={};for(d of c.XTa())switch(c=_.t(d,7),_.hj(d,_.Er)){case 3:b[c]=_.Lj(d,3,_.Er);break;case 2:b[c]=_.ze(_.iEa(d,2,_.Er));break;case 4:b[c]=_.kEa(d,4,_.Er);break;case 5:b[c]=_.Nj(d,5,_.Er);break;case 8:const e=_.mj(d,_.eob,8,_.Er);switch(_.hj(e,_.dob)){case 1:b[c]="%.@."+_.Nj(e,1,_.dob).substring(1)}}var d=b}else d={}}else d={};if(d&&Object.keys(d).length>0)for(let e of Object.keys(d))e in
a||(a[e]=d[e]);return a};_.pob=class{get(a){const b=oob()[a];return b!==void 0?new _.Fla("nQyAE."+a,b):null}getAll(){return(new _.Fla("nQyAE",oob())).object()}};_.ag(_.pob,_.bya);
_.x();
_.v("YYmHzb");
var kob=class{constructor(){let a=null;this.Ba=!0;var b=_.Ela("TSDtV",window);(b=typeof b!=="string"?null:b)&&(a=_.iob(_.cob(b,_.job))[0]);if(a)for(var c of a.XTa())if(_.Yi(c,_.ii,6,_.Er))throw Error();if(b=a){c={};for(d of b.XTa())switch(b=_.Me(d,1).toString(),_.hj(d,_.Er)){case 3:c[b]=_.Lj(d,3,_.Er);break;case 2:c[b]=_.ze(_.iEa(d,2,_.Er));break;case 4:c[b]=_.kEa(d,4,_.Er);break;case 5:c[b]=_.Nj(d,5,_.Er);break;case 6:c[b]=_.Kh(d,_.ii,6,_.Er);break;case 8:const e=_.mj(d,_.eob,8,_.Er);switch(_.hj(e,
_.dob)){case 1:c[b]=_.Nj(e,1,_.dob);break;default:throw Error("$e`"+_.hj(e,_.dob));}break;default:throw Error("$e`"+_.hj(d,_.Er));}var d=c}else d={};this.Aa=d;this.token=a?a.qTb():null}oa(a){return a.phase===1||this.Ba&&!(a.key in this.Aa)?a.defaultValue:a.ctor(this.Aa[a.key])}qTb(){return this.token}};_.lob=class extends _.ko{constructor(){super();this.delegate=new kob}oa(a){this.delegate=this.delegate;return this.delegate.oa(a)}qTb(){this.delegate=this.delegate;return this.delegate.qTb()}};_.$f(_.pFa,_.lob);
_.x();
_.v("PrPYRd");
var rob,sob,tob,vob,xob,yob,zob,Dob,Eob,wob,Hob,Aob,Lob,Job,Bob,Kob;rob=function(a){const b={};for(let c in a){const d=a[c].vk!=null?a[c].vk:"data";d in b||(b[d]={});b[d][c]=a[c]}a={};for(let c in b)a[c]=b[c];return a};sob=function(a){return _.rCa(a,(b,c)=>(b[c.BEb]=c,b),{})};tob=function(a,b){let c;for(const d of((c=a.metadata)==null?void 0:c.pu)||[])if(d.key===b){d.value.notify(0);break}};vob=function(a){const b=a.Ka();return b?(_.uob(b,null),b.XyHi9=null,a.Jd=null,!0):!1};
xob=function(){const a=_.vd("w2btAe");return a&&a.Ob&&a.Ob()?_.cob(a.string(),wob):new _.bxa};yob=function(a,b){return _.yc(b,c=>{c=_.Kja(c,(e,f)=>f.indexOf(`${a}|`)==0);const d={};_.xc(c,(e,f)=>{d[f.substring(f.indexOf("|")+1)]=e});return d})};zob=function(a){return Object.keys(a).reduce((b,c)=>b||!!a[c],!1)};
Dob=function(a,b,c,d,e,f){const g={rua:b},h=new _.Cva({FVxLkf:g},c,void 0,d);return()=>{function k(l){const p={},q=_.yc(Aob(b),(r,u)=>r.then(A=>A.length!=1||Bob(A[0])?_.Ch(A.map(E=>_.Cob(E))).then(E=>{p[l.get(u)]=E}):_.Cob(A[0]).then(E=>{p[l.get(u)]=E})));return _.Ch(_.zc(q)).then(()=>p)}g.cPc=e instanceof _.Og?e.then(k):k(e);return _.Ch([f,g.cPc]).then(()=>_.Bva(a.Cq,h,d))}};Eob=function(a){var b=_.Uf.getInstance();a=_.vpa(b,a);return _.MOa?_.Ooa(_.Lf(a,!0).then()):_.Zpa(a)};
_.uob=function(a,b){a.__component=b};wob=_.Yb(_.bxa);_.Gob=function(a,b){var c=_.qPa(a);if(c)return _.Dg(c);if(c=a.XyHi9)return c;c=_.Kg(a,d=>!!d.attributes&&!!d.attributes.getNamedItem("c-wiz"));if(!c||a.getAttribute("data-node-index")==="0;0")return Fob(b,a);b=_.Gob(c,b);if(!a.hasAttribute("c-wiz"))return b;b=b.then(d=>Hob(d).then(e=>{const f=a.getAttribute("data-node-index");e=e[f];if(!e)throw Error("af`"+d.id+"`"+a.getAttribute("jsrenderer")+"`"+f);_.Iob(e,a);return e}));return a.XyHi9=b};
Hob=function(a){a.La||(a.La=_.Ch(_.zc(a.Aa)).then(_.sba).then(b=>_.Ch(b.map(c=>c.id&&c.id.Kkb()?Job(c):c))).then(b=>sob(b)));return a.La};_.Iob=function(a,b){a.id.Kkb()?Job(a).then(c=>{_.uob(b,c)}):_.uob(b,a);a.Jd=b;for(const c in a.CSa)tob(a.CSa[c],_.Fr)};Aob=function(a){return _.yc(a.Aa,b=>b instanceof Kob?_.Dg([b]):b)};Lob=function(a,b){return b(a)?_.Ch(Object.values(Aob(a)).map(c=>c.then(d=>_.Ch(d.map(e=>Lob(e,b)))))):_.Dg(!0)};_.Cob=function(a){a.Pa||(a.Pa=a.Qa());return a.Pa};
Job=async function(a){var b=(0,_.Qf)(),c=b();b=b(1);try{const d=b(await c(a.Ma)),e=Object.values(d),f=a.id.getName();if(!e.length)throw Error("bf`"+f);const g=b(await c(e[0]));if(!g.length)throw Error("cf`"+Object.keys(d)[0]);return g[0]}finally{c()}};Bob=function(a){return a.Ca&&a.Ca.repeated};
Kob=class{constructor(a,b,c,d,e,f,g,h,k,l){this.id=a;this.Ha=b;this.Ba=c;this.BEb=d;this.CSa=e;e===null&&a.getName();this.Ia=f;this.oa=g||{};this.Aa=h;this.Ma=k;this.Ca=l;this.La=null;this.Da=!1;this.Qa=this.Pa=this.Jd=null}getParams(){return this.Ha}update(a,b,c,d,e,f,g,h,k,l){this.Ha=b||this.Ha;this.BEb=d||this.BEb;this.Ia=f||this.Ia;this.oa=g||this.oa;this.CSa=e||this.CSa;this.Aa=h||this.Aa;this.Ma=k||this.Ma;this.Ca=l||this.Ca;this.Ba=c||this.Ba}Ka(){return this.Jd}dispose(){if(!this.Da){this.Da=
!0;for(const a in this.CSa)tob(this.CSa[a],_.Gr);Lob(this,vob)}}isDisposed(){return this.Da}};var Mob,Oob,Qob;Mob=function(a){return a.Da||new (a.Cq.getParams().ctor)};_.Nob=function(a,b){a.Ba=Object.assign(a.Ba||{},b);return a};Oob=function(a,b,c){a.Ia=b;a.La=c;return a};
Qob=class{constructor(a,b,c){this.Cq=a;this.Da=c||void 0;this.Ha=b}Lca(){return this.Ma}Aa(a){this.Ca=a;return this}f4a(){const a=this.Ba&&this.Ba.pu||[];a.push({key:_.Jq,value:!0});return _.Nob(this,{pu:a})}oa(a){if(!a)return this;const b=_.yc(a,c=>()=>c);return Oob(this,()=>_.Dg(a),b)}fetch(){return _.Cob(_.Pob(this.Ha,this.Ha,[this])[0])}};_.Ir={};var Fob,Rob,Sob,Tob,Yob,Uob,Vob,Wob,Xob,Zob,$ob,apb,bpb;Fob=function(a,b){const c=b.getAttribute("jsrenderer"),d=_.xua(c);return _.Dg(Eob(d)).then(()=>{var e=_.qPa(b);if(e)return e;const f=_.Ir[c];e=b.getAttribute("data-p")?_.cob(b.getAttribute("data-p"),h=>_.Xb(f.getParams().ctor,h)):null;const g=new _.Xza(b,_.eg(_.ae(b)),_.Jr);e=_.Pob(a,g,[a.oF(f,e)])[0];_.Iob(e,b);return e})};
_.Pob=function(a,b,c){var d=_.sba(_.Mi(c,e=>Rob(a,e.Cq,!0)));_.OOa(_.Uf.getInstance(),d);c=c.map(e=>Sob(a,b,e,"0;0"));d=[].concat(...c.map(e=>e.I2a));Tob(a,d,b);return c.map(e=>e.rua)};Rob=function(a,b,c=!1){const d=[];c&&d.push(b.Cq);const e=b.oa();e&&e.length>0&&e.forEach(f=>void d.push(f));b.Kkb()||_.xc(b.getChildren(),f=>{f.recursive||_.Fa(d,Rob(a,f.id,c))});return d};
Sob=function(a,b,c,d,e){const f=c.Cq,g=xob(),h=Uob(a,c,g);var k=`${f.getName()}:${a.oa++}`;const {LQc:l,sQc:p}=Vob(a,b,h,c.Ia,k);k=p?[p]:[];const q={};var r=_.Dg();let u=_.Dg();if(f.Kkb()){r=Wob(f,l,c.Da);var A=r.then(({jBd:N})=>Xob(a,b,c,g,l,N));u=r.then(({kBd:N})=>N);r=A.then(N=>{Object.assign(q,N.bPc);N=Object.values(q);return N.length===1?N[0].then(P=>{P[0].BEb=d;return q}):_.Dg(q)});var E=A.then(N=>N.aPc);A.then(N=>{N.Ucc.length>0&&Tob(a,N.Ucc,b)})}else E=Xob(a,b,c,g,l),Object.assign(q,E.bPc),
k.push(...E.Ucc),E=E.aPc;const I=Mob(c);(A=c.Lca())?A.update(0,I,l,d,h,g,c.Ca,q,r,e):A=new Kob(f,I,l,d,h,g,c.Ca,q,r,e);e=Dob(f,A,b,a.yr(),E,u);A.Qa=e;return{rua:A,I2a:k}};Tob=function(a,b,c){const d=Yob(a,b),e=_.vh(c,d);_.Ka(b,function(f){f.start.call(this,e)},a)};Yob=function(a,b){const c={};_.Ka(b,function(d){_.xc(d.aHb,(e,f)=>{c[d.xCd+"|"+f]=e},this)},a);return rob(c)};
Uob=function(a,b,c){const d={},e=b.Cq.Qa();if(_.Ec(e))return d;const f=b.La||{},g=Mob(b),h=b.Ba;_.xc(e,(k,l)=>{if(!f[l]){var p=void 0;typeof k==="function"?p=k(g,c,h):p=k;p!==void 0&&(d[l]=p)}},a);return d};
Vob=function(a,b,c,d,e){let f;f=d?_.Dg(d(b)):_.Dg({});if(Object.keys(c).length==0)return{LQc:f,sQc:null};const g={};return{LQc:new _.Og(h=>{g.aHb=c;g.xCd=e;g.start=k=>{k=k.then(l=>yob(e,l));h(_.Ch([f,k]).then(l=>{const p=l[0];l=l[1];const q={};for(let r in l)for(let u in l[r])q[u]=l[r][u];_.Vja(q,p);return q}))}},a),sQc:g}};
Wob=function(a,b,c){return b.then(d=>{var e=a.Da(d,c);const f=e.Jf;(d=a.oa())&&d.length>0&&f.concat(d.map(g=>g.oa));d=Promise.resolve();d=_.AOa(_.KOa(_.Uf.getInstance()),f);e=Object.keys(e.Lf);e=e.length===1?e[0]:"not exist";return{kBd:_.Ch(Object.values(d)),jBd:e}})};
Xob=function(a,b,c,d,e,f){const g=new Map,h={},k=[],l=c.Cq.getChildren();let p=1;for(const I in l){if(f&&I!==f)continue;var q=l[I];const N=q.name;g.set(N,I);var r=q.jr(Mob(c),d,e);if(!Zob(a,r))continue;q=a;var u=p,A=b,E=c.Ba;c.Cq.getName();q=r.repeated?$ob(q,A,r,u):r.recursive?apb(q,A,r,u):bpb(q,A,r,u,E);const {rua:P,I2a:T}=q;P&&(h[N]=P,p+=1,k.push(...T))}return{bPc:h,Ucc:k,aPc:g}};
Zob=function(a,b){const c=b.H8!=null?b.H8:!0,d=!!b.oJa&&b.oJa.length>0,e=!!b.mPb&&b.mPb.length>0;let f=!1;b.oJa&&b.oJa.length>0&&(f=_.Ni(b.oJa,function(h){return this.Ba.get(h).bool()},a));let g=!1;b.mPb&&b.mPb.length>0&&(g=_.Ni(b.mPb,function(h){return this.Ca.oa(h)},a));return d||e?c&&(f||g):c};
$ob=function(a,b,c,d){return{rua:c.Lz(a).then(function(e){let f,g;const h=_.Ac(e);e.Hya?(f=e.Hya||[],g=_.xa(h,k=>e[k]==f)):(g=h[0],f=e[g]||[]);return _.Mi(f,function(k,l){const p=_.Kja(e,q=>!Array.isArray(q));p[g]=k;k=Oob(this.oF(c.id,c.Mc),()=>p,c.Vl);({rua:l}=Sob(this,b,k,`${d};${l}`,c));return l},this)},void 0,a),I2a:[]}};apb=function(a,b,c,d){return{rua:c.Lz(a).then(e=>zob(e)?bpb(a,b,c,d).rua:_.Dg([])),I2a:[]}};
bpb=function(a,b,c,d,e){e=Oob(_.Nob(a.oF(c.id,c.Mc),e),c.Lz,c.Vl);a=Sob(a,b,e,`${d};0`,c);return{rua:_.Dg([a.rua]),I2a:a.I2a}};
_.Jr=class extends _.ko{static Ta(){return{service:{dwb:_.pob,JBd:_.lob}}}constructor(a){super();this.Ba=a.service.dwb;this.Ca=a.service.JBd;this.ym=null;this.oa=0}Lca(a){return _.Gob(a,this)}oF(a,b){return new Qob(a,this,b)}fetch(a,b,c,d,e){this.oa=0;a=_.Nob(this.oF(a,c).Aa(d),e);b=_.Pob(this,b,[a])[0];return _.Cob(b)}Gia(a){return _.OOa(_.Uf.getInstance(),Rob(this,a,!0))}Aa(a,b){return this.oF(a,b)}QDb(a,b,c,d){const e=Rob(this,a);_.OOa(_.Uf.getInstance(),e);const {rua:f,I2a:g}=Sob(this,b,this.Aa(a,
c),"0;0");_.Iob(f,d);let h=0;_.Ka(g,function(l){_.xc(l.aHb,()=>{h++},this)},this);a=Yob(this,g);const k=_.vh(b,a);_.Ka(g,l=>{l.start(k)});return f}};_.$f(_.Bq,_.Jr);
_.x();
var u1b=class extends _.m{constructor(a){super(a)}Da(){return _.B(this,2)}Aa(){return _.B(this,3)}zc(){return _.B(this,5)}Ec(){return _.B(this,6)}qc(){return _.B(this,54)}Fc(){return _.B(this,58)}Kc(){return _.B(this,59)}Ha(){return _.B(this,9)}qd(){return _.B(this,11)}ey(){return _.B(this,80)}Kb(){return _.B(this,52)}Cb(){return _.B(this,55)}getTitle(){return _.t(this,19)}setTitle(a){return _.Zg(this,19,a)}vd(){return _.mh(this,19)}xu(){return _.t(this,24)}Ba(){return _.Gj(this,71,_.lh())}Qa(){return _.B(this,
28)}Yd(){return _.B(this,30)}yf(){return _.B(this,31)}Lb(){return _.zj(this,32)}sC(){return _.t(this,33)}Gd(){return _.B(this,48)}vH(){return _.B(this,76)}ze(){return _.B(this,65)}Oe(){return _.B(this,66)}Ld(){return _.B(this,50)}Zh(){return _.B(this,51)}Xa(){return _.zj(this,38)}Za(){return _.zj(this,39)}ub(){return _.zj(this,40)}rb(){return _.zj(this,41)}Wb(){return _.zj(this,42)}Wa(){return _.zj(this,43)}Tb(){return _.B(this,44)}Qb(){return _.B(this,46)}Ca(){return _.B(this,47)}Xc(){return _.B(this,
61)}Sa(){return _.B(this,62)}La(){return _.B(this,63)}Gh(){return _.B(this,64)}Wc(){return _.B(this,70)}Pa(){return _.B(this,72)}bu(){return _.B(this,73)}Ma(){return _.B(this,74)}sK(){return _.B(this,78)}Jb(){return _.t(this,77)}Nd(){return _.B(this,81)}Kg(){return _.B(this,82)}Rf(){return _.B(this,83)}Jg(){return _.zj(this,84)}},v1b=[0,[29,36],1,_.C,-1,1,_.C,-1,2,_.C,1,_.C,7,_.D,4,_.D,3,_.C,_.Bl,_.C,-1,_.G,_.D,2,_.El,[0,_.Yk,_.D],1,_.G,-5,_.C,1,_.C,-2,1,_.C,-2,1,_.C,-1,2,_.C,-1,1,_.C,-5,3,_.C,_.zl,
_.C,-2,[0,_.D,-4,_.G,_.D,-1],_.C,_.D,_.C,[0,[2,3],[0,_.D,-1,_.G,_.$k,_.G],_.fl,-1,_.D],_.C,-3,_.G];_.Uw=class extends _.m{constructor(a){super(a)}Aa(){return _.kh(this,u1b,1,_.lh())}Ba(){return _.B(this,9)}};_.Uw.prototype.ob="yxsBx";_.w1b=[0,_.F,v1b,4,_.Dn,_.D,_.G,_.C,[0,_.D,1,_.D,_.C,_.zo,-1,_.D,_.G]];
_.QHc=class extends _.m{constructor(a){super(a)}x8(){return _.zj(this,8)}};
_.PHc=_.y("M8IzD",[_.Bq,_.em]);
_.Mr=_.y("q0xTif",[_.gXa,_.Bq,_.B2a]);
_.EHc=_.y("H44aUc",[_.Mr]);
_.Gsc=_.y("XqvtHd",[_.Mr]);
_.Fsc=class extends _.m{constructor(a){super(a)}};_.Fsc.prototype.ob="lPgjzd";new _.ri(_.Fsc);_.Wo.lPgjzd=_.Vo;
var u7b=class extends _.m{constructor(a){super(a)}};_.v7b=class extends _.m{constructor(a){super(a)}};_.x7b=class extends _.m{constructor(a){super(a)}yr(){return _.Kh(this,u7b,1,_.w7b)}Aa(){return _.Yi(this,u7b,1,_.w7b)}Ba(){return _.Yi(this,_.v7b,2,_.w7b)}};_.w7b=[1,2,4];
var y7b;_.Ix=function(a){return _.wj(a,3)};y7b=class extends _.m{constructor(a){super(a)}};_.z7b=function(a){return _.t(a,2)};_.A7b=class extends _.m{constructor(a){super(a)}};_.B7b=function(a){return _.n(a,_.A7b,2)};_.C7b=function(a){return _.wj(a,4)};_.D7b=function(a){return _.wj(a,5)};_.E7b=class extends _.m{constructor(a){super(a)}};_.F7b=function(a){return _.Wh(a,1)};_.Jx=function(a){return _.Wh(a,2)};_.Kx=function(a){return _.n(a,_.E7b,3)};_.G7b=function(a){return _.n(a,_.ah,4)};_.H7b=class extends _.m{constructor(a){super(a)}};_.Lx=function(a){return _.Xh(a,6)};_.I7b=class extends _.m{constructor(a){super(a)}getTitle(){return _.n(this,_.Yg,1)}setTitle(a){return _.Lb(this,_.Yg,1,a)}vd(){return _.Wi(this,_.Yg,1)}getImageUrl(){return _.n(this,_.ah,12)}Aa(){return _.kj(this,_.ah,12)}};_.J7b=function(a){return _.Wh(a,5)};_.Mx=function(a){return _.n(a,_.I7b,1)};_.Nx=function(a){return _.n(a,_.H7b,2)};_.Ox=function(a){return _.n(a,y7b,4)};_.K7b=class extends _.m{constructor(a){super(a)}};var L7b=class extends _.m{constructor(a){super(a)}xUa(){return _.Tj(this,1)}ix(){return _.n(this,_.x7b,6)}Nq(){return _.Uj(this,11)}};_.M7b=class extends _.m{constructor(a){super(a)}AA(){return _.$g(this,3)}};_.N7b=class extends _.m{constructor(a){super(a)}};_.O7b=class extends _.m{constructor(a){super(a)}};_.Px=function(a){return _.kh(a,_.K7b,1,_.lh())};_.Qx=function(a){return _.n(a,L7b,2)};_.P7b=class extends _.m{constructor(a){super(a)}};_.P7b.prototype.ob="pJTLoe";new _.ri(_.P7b);_.Wo.pJTLoe=_.Vo;
var uBb;_.cu=function(a){return(b,c,d)=>{b=a(b,c,d);if(!b)return b;b.metadata.b$d=!0;return b}};uBb=function(a){a.oa||(a.oa=new _.Hq);return a.oa};_.du=class{constructor(){this.oa=null}monitor(a){uBb(this).promise.then(a)}notify(){uBb(this).resolve()}};
var nBb;_.Zt=function(a){return new nBb(a)};
nBb=class{constructor(a){this.Ma=a.Tf||!1;this.Aa=a.name;this.Cq=a.Qf;this.Ia=a.data;this.Ha=a.children;this.Ca=a.hg;a.params?typeof a.params==="function"&&(a.params={ctor:a.params}):a.params={ctor:_.Hr};this.La=a.params;this.Sa=a.dg||(()=>({variant:null,Jf:[],Lf:[]}));this.Ba=a.Kkb||!1;this.Pa=a.Xf||{}}getName(){return this.Aa}Da(a,b){if(!this.Ba)return{variant:null,Jf:[],Lf:[]};b=this.Sa(a,b);for(const d of Object.keys(b.Lf)){const e=b.Lf[d];var c=this.Pa[d]||{};const f={};let g=!1;for(const h of Object.keys(c))f[h]=
c[h](a),Array.isArray(f[h])&&(g=!0);if(g){const h=Object.keys(f).find(k=>Array.isArray(f[k]));c=f[h].map(k=>{const l=Object.assign({},f);l[h]=k;return e(l,void 0).Jf});b.Jf.push(...c)}else b.Jf.push(...e(f,void 0).Jf)}return b}Kkb(){return this.Ba}Qa(){return this.Ia||{}}getChildren(){return this.Ha||{}}getParams(){return this.La}oa(){return this.Ca?this.Ca:null}toString(){return"ComponentId<"+this.Aa+">"}};_.$t=_.vDa;
var Hsc=class extends _.m{constructor(a){super(a)}Hh(){return _.$g(this,3)}Do(){return _.wj(this,3)}};Hsc.prototype.ob="HIbR3";new _.ri(Hsc);new _.ri(_.P7b);_.Wo.pJTLoe=_.Vo;var Isc=new _.fi("TD9dLc",_.P7b,Hsc,[_.ei,!0,_.di,"/WhyThisAdDataService.WhyThisAdContext"]);var Jsc=class extends _.m{constructor(a){super(a)}};Jsc.prototype.ob="NWEFRc";new _.ri(Jsc);new _.ri(_.Fsc);_.Wo.lPgjzd=_.Vo;var Ksc=new _.fi("BONMwf",_.Fsc,Jsc,[_.ei,!0,_.di,"/AdsSettingsUserInfoDataService.AdsSettingsRelatedProducts"]);_.Lsc=()=>({variant:null,Jf:[],Lf:{}});_.Msc=class extends _.m{constructor(a){super(a)}Hh(){return _.t(this,3)}Do(){return _.wj(this,3)}x8(){return _.zj(this,10)}};_.Nsc=_.Zt({Tf:!1,name:"b2zFDf",Qf:_.Gsc,params:{ctor:_.Msc},hg:[],data:{context:function(a,b,c){b=c||{};c=b.vk||"rpc";var d=new Hsc;if(_.mh(a,6)){var e=_.t(a,6);_.Zg(d,5,e)}_.mh(a,5)&&(e=_.t(a,5),_.Zg(d,4,e));_.mh(a,15)&&(e=_.t(a,15),_.Zg(d,8,e));_.mh(a,2)&&(e=_.t(a,2),_.Zg(d,2,e));_.mh(a,12)&&(e=_.t(a,12),_.Zg(d,6,e));_.mh(a,3)&&(e=a.Hh(),_.Zg(d,3,e));_.mh(a,1)&&(a=_.t(a,1),_.Zg(d,1,a));a={fatal:!0,pu:[{key:_.Fr,value:new _.du},{key:_.Gr,value:new _.du}]};let f;for(f in b)a[f]=b[f];return{Po:Isc,
vk:c,Us:d,metadata:a}},HF:function(a,b,c){if(a.x8()==1){a=c||{};b=a.vk||"rpc";c=new Jsc;var d={fatal:!0,pu:[{key:_.Fr,value:new _.du},{key:_.Gr,value:new _.du}]};let e;for(e in a)d[e]=a[e];return{Po:Ksc,vk:b,Us:c,metadata:d}}}},dg:_.Lsc,Xf:{},children:{}});
_.FHc=function(a,b){return _.Zg(a,2,b)};_.GHc=function(a,b){return _.Zg(a,3,b)};_.HHc=function(a,b){return _.Sh(a,10,b)};_.IHc=function(a,b){return _.Lb(a,_.ah,4,b)};_.JHc=function(a,b){return _.Lb(a,_.ah,9,b)};_.KHc=function(a,b){_.Zg(a,12,b)};_.LHc=_.Zt({Tf:!1,name:"o3ebOd",Qf:_.EHc,params:{ctor:_.Msc},hg:[],data:{},dg:()=>({variant:null,Jf:[],Lf:{JHc:_.Lsc}}),Xf:{JHc:{}},children:{JHc:{id:_.Nsc,name:"SagRuf",jr:function(a){var b=new _.Msc;_.Wi(a,_.ah,9)&&_.JHc(b,a.Nf()?_.ij(a,_.ah,9,_.$t):_.kj(a,_.ah,9));_.Wi(a,_.ah,4)&&_.IHc(b,a.Nf()?_.ij(a,_.ah,4,_.$t):_.kj(a,_.ah,4));if(_.mh(a,8)){var c=_.t(a,8);_.Zg(b,8,c)}_.mh(a,6)&&(c=_.t(a,6),_.Zg(b,6,c));_.mh(a,5)&&(c=_.t(a,5),_.Zg(b,5,c));_.mh(a,2)&&_.FHc(b,_.t(a,2));_.mh(a,12)&&_.KHc(b,_.t(a,
12));_.mh(a,3)&&_.GHc(b,a.Hh());_.Gk(a,10)&&_.HHc(b,a.x8());_.mh(a,1)&&(a=_.t(a,1),_.Zg(b,1,a));return{Mc:b,id:_.Nsc,name:"SagRuf"}}}}});
_.p7b=_.y("OlGQO",[_.Mr]);
_.q7b=_.Zt({Tf:!1,name:"HXzY2c",Qf:_.p7b,params:{ctor:_.Hr},hg:[],data:{},dg:()=>({variant:null,Jf:[],Lf:{}}),Xf:{},children:{}});
_.v("M8IzD");
var RHc=function(a){return _.Je(a,_.QHc,10)},SHc=_.Yb(_.Uw),THc=class extends _.m{constructor(a){super(a)}};THc.prototype.ob="svcCQe";var VHc=function(a,b,c){const d=c?RHc(SHc(b.data)):a.Da;b.event&&!c&&(b.event.preventDefault(),b.event.stopPropagation());b.wb.el()&&_.Ie(b.wb.el())&&_.Fp(a.Pb.oa(),b.wb.el()).log(!0);if(!a.oa&&!a.Ba){a.oa=!0;var e=a.yd?a.Ka("I3OyF").el():a.Ka("oDTRPe").el();if(a.Aa||c){for(;e.firstChild;)e.removeChild(e.firstChild);a.Aa=!1}if(a.Ca&&!c)UHc(a),a.oa=!1;else{var f=new _.Msc;_.KHc(_.JHc(_.IHc(_.HHc(_.GHc(_.FHc(f,_.wj(d,1)),(g=>{switch(g){case 15:return"localservices";case 7:return"pla";case 10:return"css";
case 12:return"searchpla";default:return"searchad"}})(_.bk(d,8))),_.Xh(d,8)),_.Wi(d,_.ah,5)?_.n(d,_.ah,5):_.bh(_.pc("https://adssettings.google.com"))),_.Wi(d,_.ah,6)?_.n(d,_.ah,6):_.bh(_.pc("https://adssettings.google.com/authenticated"))),_.mh(d,7)?_.t(d,7):"https://www.google.com");_.ug(a.Kf.oF(_.LHc,f).fetch().then(g=>{e.appendChild(g.render());UHc(a);a.Ca=!0}).catch(g=>{a.Ba=!0;_.ug(a.Kf.oF(_.q7b,null).fetch().then(h=>{e.appendChild(h.render());UHc(a);a.Aa=!0}),()=>{a.Ba=!1});_.df(Error("hg`"+
f.Hh()+"`"+_.t(f,2).length+"`"+g),{level:1})}),()=>{a.oa=!1})}}},UHc=function(a){a.yd?a.Vc("vf4JOc",_.Do).then(b=>{b.open()}):a.Vc("vbrkHb",_.Do).then(b=>{b.open()})},WHc=class extends _.Wr{static Ta(){return{jsdata:{swd:THc},service:{Kf:_.Jr,Pb:_.Hu}}}constructor(a){super();this.Ca=this.Aa=this.Ba=this.oa=!1;const b=a.jsdata.swd;this.Da=_.n(b,_.QHc,1);this.yd=_.B(b,2);this.Kf=a.service.Kf;this.Pb=a.service.Pb}Ia(a){VHc(this,a,!0)}Ha(a){VHc(this,a,!1)}};WHc.prototype.$wa$IwCZH=function(){return this.Ha};
WHc.prototype.$wa$AlF6be=function(){return this.Ia};_.Yr(_.PHc,WHc);
_.x();
});
// Google Inc.
