"use strict";loaded_g_0(function(_){var window=this;
_.h("wWQ0Lc");

_.q();
_.h("btdpvd");
_.nQa=function(){let a=_.En(_.zn(new _.vn,"/gen_204"),"ei",_.$xa()),b=new Map;_.fp(b,!1,!1);for(let [c,d]of b)_.En(a,c,d);return a};
_.q();
_.h("ba5WFf");
var ZHb=[["label",["so"]],["type",{E8:0,B8:1,C8:2,D8:3}],"className",["disabled",["so"]],"JI"],DI=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){const a=this.j().label,b=_.ot(this,"JIbuQc"),c=this.j().type,d=this.j().className,e=this.j().disabled,f=this.j().JI,g=_.Ie(_.As),k=_.lt(this,0,"div",!1);this.ja("nz6JVb",function(){f&&g.ra().j(k.value,3).log();return b()});const l=new Map([[1,"wZE6ue"],[2,"nvVUFd"],[3,"Ga40Nb"]]);this.fa("J0E0qd",_.O(()=>_.Ys(a),void 0,"WRONA"));this.fa("UpSNec",
_.O(()=>_.Z("xwey6c",l.get(c!==void 0?c:1),d,_.Ys(e)?"P4b4wf":""),void 0,"MVI8pf"));this.ea()}j(){return super.j()}ba(){return ZHb}da(){throw Error("Ie");}};DI.prototype.$wa$TKxcbd=function(){return this.da};DI.prototype.$wa$p2ggSe=function(){return this.ba};DI.prototype.$wa$QyQmSc=function(){return this.j};DI.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("ba5WFf",[_.X]),DI);
_.q();
_.h("t7xgIe");

_.q();
_.h("DHWBFf");
var ZPb=[["isSelected",["s"]],["Oa",["s"]],["xc",["so"]],["tm",["s"]]],nL=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){const a=this.j().Oa,b=_.ot(this,"jIYg8d");this.ta("oBcEhe",(c,d)=>_.n(function*(){c.stopPropagation();b(d)}));this.fa("kApB4c",_.O(()=>a()?"Canvas is turned on. To turn off, start a new search.":"A workspace to create, edit, and save your progress",void 0,"s0HJee"));this.ea()}j(){return super.j()}ba(){return ZPb}da(){throw Error("Ie");}};
nL.prototype.$wa$TKxcbd=function(){return this.da};nL.prototype.$wa$p2ggSe=function(){return this.ba};nL.prototype.$wa$QyQmSc=function(){return this.j};nL.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("DHWBFf",[_.X]),nL);


_.q();
_.h("znhYCe");

_.q();
_.h("TWUxld");

_.q();
_.h("GRvX4c");

_.q();
_.h("gllL8");

_.q();
_.h("OAHOkf");
var JLb=[],ZJ=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return JLb}da(){throw Error("Ie");}};ZJ.prototype.$wa$TKxcbd=function(){return this.da};ZJ.prototype.$wa$p2ggSe=function(){return this.ba};ZJ.prototype.$wa$QyQmSc=function(){return this.j};ZJ.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("OAHOkf",[_.X]),ZJ);
_.q();
_.h("T6CUD");
var o4b=[["isSelected",["s"]],["Oa",["s"]],["xc",["so"]]],HO=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){const a=this.j().isSelected,b=this.j().Oa,c=this.j().xc,d=_.ot(this,"oBcEhe"),e=_.lt(this,0,"button",!1);this.fa("UpSNec",_.O(()=>_.Z("PVlNde",a()?"rOvWfd":"",_.Ys(c)&&"n0nTPd"),void 0,"nuPpPd"));const f=_.Ie(_.As);this.ja("oMR5Vc",function(g){g.stopPropagation();if(_.Ix){if(b()||e.value.disabled)return;e.value.disabled=!0;setTimeout(()=>{e.value&&
(e.value.disabled=!1)},50)}d(e.value);f.ra().j(e.value,3).log(!0)});this.ja("gBoq3c",function(g){g.stopPropagation()});_.pt(this,"HugV6",a,()=>_.S(_.zx,{na:a,then:()=>_.S(_.cs,null,_.S(_.HTb,{Wq:16},_.S(_.BJ,{size:16}))),else:()=>_.S(_.cs,null,_.S("span",{class:"eJWmjb"},"Deep Search"))}));this.ea()}j(){return super.j()}ba(){return o4b}da(){throw Error("Ie");}};HO.prototype.$wa$TKxcbd=function(){return this.da};HO.prototype.$wa$p2ggSe=function(){return this.ba};HO.prototype.$wa$QyQmSc=function(){return this.j};
HO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("T6CUD",[_.X]),HO);
_.q();
_.h("Hgdwff");
var N_a=[["ha",_.ux],["cg",["so"]],["ariaHidden",["so"]]],Dx=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){function a(){const Y=new IntersectionObserver(aa=>{aa.forEach(ba=>{ba.isIntersecting&&(R(),w.value&&Y.unobserve(w.value))})});w.value&&Y.observe(w.value)}function b(Y){const aa=w.value,ba=x.value;switch(Y){case 1:ba.style.bottom="calc(100% + 11px)";aa.style.flexDirection="column";break;case 2:ba.style.top="calc(100% + 11px)";aa.style.flexDirection="column";break;case 3:ba.style.right=
"calc(100% + 11px)";break;case 4:ba.style.left="calc(100% + 11px)";break;case 5:ba.style.top="calc(100% + 11px)",ba.style.right="calc(50% - 29px)",aa.style.flexDirection="column"}}function c(Y){const aa=z.value;switch(Y){case 1:aa.style.bottom="-10px";aa.style.left="calc(50% - 7px)";break;case 2:aa.style.top="-10px";aa.style.left="calc(50% - 7px)";aa.style.transform="rotate(180deg)";break;case 3:aa.style.right="-9px";aa.style.top="calc(50% - 7px)";aa.style.transform="rotate(-90deg)";break;case 4:aa.style.left=
"-9px";aa.style.top="calc(50% - 7px)";aa.style.transform="rotate(90deg)";break;case 5:aa.style.top="-10px",aa.style.right="22px",aa.style.transform="rotate(180deg)"}}const d=this.j().cg,e=this.j().ha||new _.ux,f=_.Gl(e,1),g=e.getPosition(),k=_.y(e,3),l=_.Cl(e,4,300),r=_.Cl(e,5,600),t=_.Cl(e,6);_.Gl(e,7);const u=_.lt(this,1,"div",!1),w=_.lt(this,0,"div",!1),x=_.lt(this,2,"div",!1),z=_.lt(this,3,"div",!1),B=_.Jj(_.Sm),F=f===2||f===5||f===6||f===7,H=f===2||f===5,I=this.ta("Geh74d",()=>_.n(function*(){(yield B).close(u.value);
let Y,aa;(aa=(Y=google).domchange)==null||aa.call(Y)})),M=_.Ie(_.qn),R=this.ta("knZyec",()=>_.n(function*(){if(!_.Ys(d)){if(t!==0)if(yield M.canShowPromotion(t))M.recordPromoShown(t);else return;b(g);c(g);var Y=_.G_a(x.value,r);var aa=_.dw(_.rx({overlay:u.value,yb:!1,position:"absolute",ab:!0,Cb:!H,animation:Y}),({Zb:ka})=>{ka.then(()=>{u.value.classList.add("Aspg9c")});return!0});_.sw(aa,4);F&&_.cw(aa,1);Y||x.value.classList.add("ko8QQ");u.value.classList.remove("Aspg9c");yield new Promise(ka=>{requestAnimationFrame(ka)});
yield _.sx(u.value,yield B,aa);var ba,fa;(fa=(ba=google).domchange)==null||fa.call(ba)}}));this.ja("i0Beg",function(){return _.n(function*(){yield I()})});_.Zs(()=>_.n(function*(){_.Ys(d)&&(yield B).isOpen(u.value)&&(yield I())}),"DyGLvd");const V=()=>_.n(function*(){if(f===3||f===4)yield R()}),U=()=>_.n(function*(){if(f===3||f===4)yield R()}),W=()=>_.n(function*(){if(f===3||f===4)yield I()}),T=()=>_.n(function*(){if(f===3||f===4)yield I()});this.onInit(function(){f===2||f===6?a():f!==5&&f!==7||!k?
(w.value.addEventListener("mouseenter",V),w.value.addEventListener("focusin",U),w.value.addEventListener("mouseleave",W),w.value.addEventListener("focusout",T),l!==300&&x.value.style.setProperty("--animation-open-debounce",`${l}ms`),r!==600&&x.value.style.setProperty("--animation-close-debounce",`${r}ms`)):w.value.addEventListener(k,R,{once:!0})});this.ea()}j(){return super.j()}ba(){return N_a}da(){throw Error("Ie");}};Dx.prototype.$wa$TKxcbd=function(){return this.da};Dx.prototype.$wa$p2ggSe=function(){return this.ba};
Dx.prototype.$wa$QyQmSc=function(){return this.j};Dx.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("Hgdwff",[_.X]),Dx);


_.q();
_.h("nqTR2b");
var XKb=[["ha",_.wG],"className",["FE",["so"]],["cg",["so"]],["ariaHidden",["so"]]],KJ=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){function a(M){const R=t.value,V=u.value,U=`calc(100% + ${getComputedStyle(V).getPropertyValue("offset-distance").trim()})`;switch(M){case 1:V.style.bottom=U;R.style.flexDirection="column";break;case 2:V.style.top=U;R.style.flexDirection="column";break;case 3:V.style.right=U;break;case 4:V.style.left=U;break;case 5:V.style.bottom=U;V.style.right="0";
R.style.flexDirection="column";break;case 6:V.style.bottom=U;V.style.left="0";R.style.flexDirection="column";break;case 7:V.style.top=U;V.style.right="0";R.style.flexDirection="column";break;case 8:V.style.top=U,V.style.left="0",R.style.flexDirection="column"}}const b=this.j().className,c=this.j().FE,d=this.j().cg,e=this.j().ha||new _.wG,f=_.Gl(e,1),g=e.getPosition(),[k,l]=this.fa("tkK3Rb",_.K(!0,void 0,"HbOlW"));this.fa("URFwmf",_.O(()=>_.Z(k()&&"tHaXU","eksFZe",b),void 0,"Lowboe"));const r=_.lt(this,
1,"div",!1),t=_.lt(this,0,"div",!1),u=_.lt(this,2,"div",!1),w=_.Jj(_.Sm),x=this.ta("Geh74d",()=>_.n(function*(){if(!_.Ys(c)){(yield w).close(r.value);var M,R;(R=(M=google).domchange)==null||R.call(M)}}));_.Zs(()=>_.n(function*(){_.Ys(d)&&!_.Ys(c)&&(yield w).isOpen(r.value)&&(yield x())}),"cO6NXe");const z=this.ta("knZyec",()=>_.n(function*(){if(!_.Ys(d)||_.Ys(c)){a(g);var M=_.bw(_.dw(_.rx({overlay:r.value,yb:!1,position:"absolute",ab:!0,Cb:!0,animation:_.G_a(u.value)}),({Zb:U})=>{U.then(()=>{l(!0)});
return!0}),14);l(!1);yield new Promise(U=>{requestAnimationFrame(U)});yield _.sx(r.value,yield w,M);var R,V;(V=(R=google).domchange)==null||V.call(R)}})),B=()=>_.n(function*(){if(f===2||f===3)yield z()}),F=()=>_.n(function*(){if(f===2||f===3)yield x()}),H=()=>_.n(function*(){if(f===2||f===3)yield z()}),I=()=>_.n(function*(){if(f===2||f===3)yield x()});this.onInit(function(){t.value.addEventListener("mouseenter",B);t.value.addEventListener("focusin",H);t.value.addEventListener("mouseleave",F);t.value.addEventListener("focusout",
I)});_.Zs(()=>_.n(function*(){_.Ys(c)?yield z():yield x()}),"rf6hh");this.ea()}j(){return super.j()}ba(){return XKb}da(){throw Error("Ie");}};KJ.prototype.$wa$TKxcbd=function(){return this.da};KJ.prototype.$wa$p2ggSe=function(){return this.ba};KJ.prototype.$wa$QyQmSc=function(){return this.j};KJ.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("nqTR2b",[_.X]),KJ);


_.q();
_.h("q8cKod");
var p4b=[["isSelected",["s"]],["Oa",["s"]],["xc",["so"]],["tm",["s"]]],IO=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){const a=this.j().isSelected,b=this.j().Oa,c=this.j().xc,d=this.j().tm,e=_.ot(this,"jIYg8d"),f=_.xx(_.wx(_.vx(3).setPosition(1),50)),g=_.xG(3).setPosition(1);this.fa("h4Qywc",_.O(()=>_.Z("F0u3ce",a()?"orkI9e":""),void 0,"emy7we"));const k=_.S(_.MTb,{isSelected:a,Oa:b,xc:c,kv:e,yg:"j2yiQ"}),l=this.fa("kApB4c",_.O(()=>b()?"\u0427\u0442\u043e\u0431\u044b \u0441\u043d\u043e\u0432\u0430 \u0432\u043e\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c\u0441\u044f Deep Search, \u043d\u0430\u0447\u043d\u0438\u0442\u0435 \u043d\u043e\u0432\u044b\u0439 \u043f\u043e\u0438\u0441\u043a":
"\u0411\u043e\u043b\u0435\u0435 \u043e\u0431\u043e\u0441\u043d\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b \u0441 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0435\u0439 \u0438\u0437 \u0440\u0430\u0437\u043d\u044b\u0445 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u043e\u0432, \u043d\u043e \u043d\u0435\u043c\u043d\u043e\u0433\u043e \u043c\u0435\u0434\u043b\u0435\u043d\u043d\u0435\u0435",void 0,"rCbAqf"));_.pt(this,"HugV6",null,()=>_.S(_.CM,null,_.S(_.AM,
{when:()=>_.HF&&!d()},()=>_.S(_.yG,{ha:g,className:"i30lS",jc:k,ariaHidden:!0},_.S("div",{id:"j2yiQ"},l))),_.S(_.AM,{when:()=>_.HF&&d()},()=>k),_.S(_.BM,null,()=>_.S(_.yx,{ha:f,className:"yWES4b",jc:k,cg:d,ariaHidden:!0},_.S("div",{id:"j2yiQ",class:"DhSREd"},l)))),!0);this.ea()}j(){return super.j()}ba(){return p4b}da(){throw Error("Ie");}};IO.prototype.$wa$TKxcbd=function(){return this.da};IO.prototype.$wa$p2ggSe=function(){return this.ba};IO.prototype.$wa$QyQmSc=function(){return this.j};
IO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("q8cKod",[_.X]),IO);


_.q();
_.h("QClhuc");
var u4b=[],NO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){function a(){f=setTimeout(()=>{c()},2500)}function b(){return _.n(function*(){var g=_.UE({ab:!0});yield _.VE(d.value,yield e,g);g=d.value.getBoundingClientRect();d.value.style.left=`calc(50% - ${g.width}px / 2)`;d.value.style.top=`-${32+g.height}px`;a()})}function c(){return _.n(function*(){(yield e).close(d.value)})}const d=_.lt(this,0,"div",!1),e=_.Jj(_.Sm);let f=0;this.onInit(function(){b();_.vr(()=>{f&&(clearTimeout(f),
f=0)})});this.ea()}j(){return super.j()}ba(){return u4b}da(){throw Error("Ie");}};NO.prototype.$wa$TKxcbd=function(){return this.da};NO.prototype.$wa$p2ggSe=function(){return this.ba};NO.prototype.$wa$QyQmSc=function(){return this.j};NO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("QClhuc",[_.X]),NO);
_.q();
_.h("jkJHWd");
var w4b=[["Oa",["so"]],"className",["Qc",["so"]],"ui"],PO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){const a=_.ot(this,"Fk7gc"),b=this.j().Oa,c=this.j().className,d=this.j().ui,e=_.lt(this,1,"input",!1),f=_.lt(this,2,"button",!1),g=_.Ie(_.As);this.ja("h5M12e",function(){f.value.disabled||(f.value.disabled=!0,setTimeout(()=>{if(f==null?0:f.value)f.value.disabled=!1},1E3),e.value.click(),g.ra().j(f.value,3).log())});this.fa("ynmjY",_.O(()=>_.Z("nQpXxb",c,_.Ys(b)&&"XegSHf",d&&
"gUmKBb"),void 0,"mHOKC"));this.ja("FDSEXc",function(){const k=e.value.files;k&&k.length>0&&(a(k),e.value&&(e.value.value=""))});this.fa("ggNWmb",()=>_.Ys(b));this.ea()}j(){return super.j()}ba(){return w4b}da(){throw Error("Ie");}};PO.prototype.$wa$TKxcbd=function(){return this.da};PO.prototype.$wa$p2ggSe=function(){return this.ba};PO.prototype.$wa$QyQmSc=function(){return this.j};PO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("jkJHWd",[_.X]),PO);


_.q();
_.h("x927f");

_.q();
_.h("y4xy3");

_.q();
_.h("qVQl0c");

_.q();
_.h("uGc0Lc");
var y4b=[["ariaLabel",["so"]],["Oa",["so"]],["className",["so"]],["Lk",["so"]],["label",["so"]],["Ko",["so"]],["Qc",["so"]]],RO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){const a=_.ot(this,"KjsqPd"),b=this.j().ariaLabel,c=this.j().Oa,d=this.j().className,e=this.j().Lk,f=this.j().label,g=this.j().Ko,k=_.lt(this,1,"button",!1),l=_.Ie(_.As);this.ja("h5M12e",function(r){k.value.disabled||(k.value.disabled=!0,setTimeout(()=>{if(k==null?0:k.value)k.value.disabled=!1},1E3),l.ra().j(k.value,
3).log(!0),a(r))});this.ja("TdZlWb",function(r){r.stopPropagation()});this.fa("J0E0qd",_.O(()=>_.Ys(b),void 0,"PVM6oc"));this.fa("ynmjY",_.O(()=>_.Z("uMMzHc",_.Ys(d),_.Ys(c)?"wdK4Nc":""),void 0,"eMd5ye"));this.fa("TWRqUd",_.O(()=>_.Z("wilSz",_.Ys(e)),void 0,"zxsKZb"));this.fa("ZfkVq",_.O(()=>_.Z("TXv1xf",_.Ys(g)),void 0,"oVyD2"));this.fa("Bww8Xd",_.O(()=>_.Ys(f),void 0,"T0OZKb"));this.fa("H2n69d",_.O(()=>_.Ys(c)?-1:0,void 0,"RixZR"));this.ea()}j(){return super.j()}ba(){return y4b}da(){throw Error("Ie");
}};RO.prototype.$wa$TKxcbd=function(){return this.da};RO.prototype.$wa$p2ggSe=function(){return this.ba};RO.prototype.$wa$QyQmSc=function(){return this.j};RO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("uGc0Lc",[_.X]),RO);


_.q();
_.h("Yfil0");
var z4b=[],SO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return z4b}da(){throw Error("Ie");}};SO.prototype.$wa$TKxcbd=function(){return this.da};SO.prototype.$wa$p2ggSe=function(){return this.ba};SO.prototype.$wa$QyQmSc=function(){return this.j};SO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("Yfil0",[_.X]),SO);
_.q();
_.h("p4HiId");
var A4b=[["isSelected",["so"]],["Oa",["so"]],["ariaLabel",["so"]],"className",["label",["so"]],["Qc",["so"]],["an",["so"]]],TO=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){function a(){const w=l.value.animate([{opacity:1},{opacity:0}],{duration:100,easing:"cubic-bezier(0.3, 0, 0.8, 0.15)"}),x=l.value.animate([{transform:"translateX(0px)"},{transform:"translateX(-20px)"}],{duration:100,easing:"cubic-bezier(0.3, 0, 1, 1)"});return{finished:Promise.all([w.finished,
x.finished])}}const b=_.ot(this,"KjsqPd"),c=this.j().isSelected,d=this.j().Oa,e=this.j().ariaLabel,f=this.j().className,g=this.j().label,k=this.j().an,l=_.lt(this,1,"button",!1),r=_.Ie(_.As);this.onInit(function(){_.vH&&l.value.animate([{opacity:0,transform:"translateX(-20px)"},{offset:.4,opacity:1},{opacity:1,transform:"translateX(0px)"}],{duration:350,easing:"cubic-bezier(0.42, 1.67, 0.21, 0.9)",fill:"both"})});this.ja("h5M12e",function(w){l.value.disabled||_.Ys(d)||(l.value.disabled=!0,setTimeout(()=>
{let x;if((x=l)==null?0:x.value)l.value.disabled=!1},500),r.ra().j(l.value,3).log(!0),_.vH?a().finished.then(()=>{b(w)}):b(w))});this.ja("TdZlWb",function(w){w.stopPropagation()});this.fa("DyjnAe",_.O(()=>_.Ys(e),void 0,"seev0c"));this.fa("ynmjY",_.O(()=>_.Z("r3F7Z",f,_.Ys(c)&&"YJSrRe",_.Ys(d)&&"hiro0c"),void 0,"k5zAyb"));this.fa("Bww8Xd",_.O(()=>_.Ys(g),void 0,"J5sbjc"));this.fa("YycZN",_.O(()=>_.Ys(k)||_.Ys(e),void 0,"AQp6mf"));this.fa("ggNWmb",()=>_.Ys(d));this.fa("mCevaf",()=>_.Ys(c));const t=
this.fa("OCa4gb",()=>_.Ys(c)),u=this.fa("MMNOWd",()=>_.Ys(c));_.pt(this,"HugV6",t,()=>_.S(_.zx,{na:t,then:()=>_.S("div",{class:"Gnum6c","aria-hidden":"true"},_.S(_.EM,{size:20}))}));_.pt(this,"WyzG9e",u,()=>_.S(_.zx,{na:u,then:()=>_.S("div",{class:"Gnum6c","aria-hidden":"true"},_.S(_.BJ,{size:24}))}));this.ea()}j(){return super.j()}ba(){return A4b}da(){throw Error("Ie");}};TO.prototype.$wa$TKxcbd=function(){return this.da};TO.prototype.$wa$p2ggSe=function(){return this.ba};
TO.prototype.$wa$QyQmSc=function(){return this.j};TO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("p4HiId",[_.X]),TO);


_.q();
_.h("kFeSjd");
var B4b=[["isOpen",["s"]]],UO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){const a=_.ot(this,"tTT8Tc"),b=_.OTb?"https://support.google.com/chrome/?p=ui_voice_search":_.QTb&&_.PTb?"https://support.apple.com/guide/safari/websites-ibrwe2159f50/mac":"",c=b!=="";this.ta("V69dXb",()=>{c&&_.Bs(window,_.ni(b));a()});this.ea()}j(){return super.j()}ba(){return B4b}da(){throw Error("Ie");}};UO.prototype.$wa$TKxcbd=function(){return this.da};UO.prototype.$wa$p2ggSe=function(){return this.ba};
UO.prototype.$wa$QyQmSc=function(){return this.j};UO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("kFeSjd",[_.X]),UO);
_.q();
_.h("WlOj5b");

_.q();
_.h("qj9t6b");

_.q();
_.h("bFudd");

_.q();
_.h("xDykld");

_.q();
_.h("i4Gy7b");

_.q();
_.h("PjpS9e");
var C4b=[["copy",["s"]],["configuration",["so"]]],VO=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){const a=_.ot(this,"DgdDpd"),b=_.ot(this,"q86U3e"),c=this.j().configuration;_.pt(this,"HugV6",null,()=>_.S(_.CM,null,_.S(_.AM,{when:()=>_.Ys(c)==="confirmation"},()=>_.S(_.cs,null,_.S(_.CI,{label:"\u0414\u0430",action:a,className:"ygXQGf",type:3,icon:_.v(_.ry(new _.jv,30).setSize(20))}),_.S(_.CI,{label:"\u041d\u0435\u0442",className:"ygXQGf",action:b,type:2,
icon:_.v(_.ry(new _.jv,6).setSize(20))}))),_.S(_.AM,{when:()=>_.Ys(c)==="error"},()=>_.S(_.CI,{label:"\u0417\u0430\u043a\u0440\u044b\u0442\u044c",action:a,className:"ygXQGf",type:2,icon:_.v(_.ry(new _.jv,6).setSize(20))}))),!0);this.ea()}j(){return super.j()}ba(){return C4b}da(){throw Error("Ie");}};VO.prototype.$wa$TKxcbd=function(){return this.da};VO.prototype.$wa$p2ggSe=function(){return this.ba};VO.prototype.$wa$QyQmSc=function(){return this.j};VO.prototype.$wa$kXCA5e=function(){return this.aa};
_.P(_.m("PjpS9e",[_.X]),VO);
_.q();
_.h("tnlF0");
var D4b=[["Od",{oga:0,qfa:1,eea:2,m8:3,n8:58,o8:4,H9:5,I9:60,Faa:6,Saa:7,rba:8,xfa:9,iha:10,tha:11,Qia:12,Mha:13,Qaa:14,t7:15,G8:16,iga:17,Waa:18,xba:19,l8:20,eka:21,uga:22,aga:23,oaa:24,Xla:25,n7:26,pba:27,jV:28,s$:29,c7:30,pga:31,Oha:32,Gha:54,rla:33,Zea:34,xK:35,Gla:36,eV:37,x8:38,iC:39,Yla:40,qba:41,Sfa:42,dL:43,Sga:46,O$:47,Baa:48,Zla:49,jga:50,o7:51,Wga:52,EMPTY:53,K9:55,L9:56,J9:57,hfa:59,kea:61,jea:62,iea:63,wba:66,fha:67,gha:68,hha:69,zba:70,q7:71,r7:72,Hka:73,oea:75,w8:76,w9:84,Lha:86,Daa:87,
haa:44,uaa:45,Aea:74,fka:77,Yaa:78,e9:79,hga:81,Lfa:82,Zga:83,Nga:85,gga:88,s7:89,A7:90,u8:91,u7:92,f6:93,mla:94,Ika:95,P$:96,iV:97,lga:98,pda:99,j8:100,m9:101,kga:102,cU:103}]],WO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return D4b}da(){throw Error("Ie");}};WO.prototype.$wa$TKxcbd=function(){return this.da};WO.prototype.$wa$p2ggSe=function(){return this.ba};WO.prototype.$wa$QyQmSc=function(){return this.j};WO.prototype.$wa$kXCA5e=function(){return this.aa};
_.P(_.m("tnlF0",[_.X]),WO);
_.q();
_.h("GNrGjf");
var E4b=[],XO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return E4b}da(){throw Error("Ie");}};XO.prototype.$wa$TKxcbd=function(){return this.da};XO.prototype.$wa$p2ggSe=function(){return this.ba};XO.prototype.$wa$QyQmSc=function(){return this.j};XO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("GNrGjf",[_.X]),XO);
_.q();
_.h("GDyo6");
var F4b=[["label",["so"]],["description",["so"]],["isSelected",["so"]],["ariaLabel",["so"]],["Oa",["so"]],["className",["so"]],["Te",["so"]]],YO=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){const a=_.ot(this,"KjsqPd"),b=this.j().description,c=this.j().isSelected,d=this.j().ariaLabel,e=this.j().Oa,f=this.j().className,g=this.j().Te,k=_.lt(this,1,"button",!1),l=_.Ie(_.As);this.ja("h5M12e",function(w){k.value.disabled||(k.value.disabled=!0,setTimeout(()=>
{if(k==null?0:k.value)k.value.disabled=!1},1E3),l.ra().j(k.value,3).log(!0),a(w))});const r=this.fa("cN5qGc",_.O(()=>_.Ys(c)&&_.Ys(g),void 0,"BENQQd"));this.fa("J0E0qd",_.O(()=>_.Ys(d),void 0,"QDZhef"));this.fa("ynmjY",_.O(()=>_.Z("qP3qJc",_.Ys(f),_.Ys(e)||r()?"SbOEpe":"",_.Ys(c)&&_.RF?"Jais6b":""),void 0,"lBkdNc"));this.fa("ggNWmb",()=>_.Ys(e)||r());const t=this.fa("mCevaf",()=>!!_.Ys(b)),u=this.fa("OCa4gb",()=>_.Ys(c)&&!r());_.pt(this,"HugV6",t,()=>_.S(_.zx,{na:t,then:()=>_.S("div",{class:"RYs0Ae"},
b)}));_.pt(this,"WyzG9e",u,()=>_.S(_.zx,{na:u,then:()=>_.S("div",{class:"vHnTfd"},_.S(_.RTb,{size:_.gwb?24:20}))}));this.ea()}j(){return super.j()}ba(){return F4b}da(){throw Error("Ie");}};YO.prototype.$wa$TKxcbd=function(){return this.da};YO.prototype.$wa$p2ggSe=function(){return this.ba};YO.prototype.$wa$QyQmSc=function(){return this.j};YO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("GDyo6",[_.X]),YO);
_.q();
_.h("TYPcCd");
var G4b=[["inputs",["s",["r",[["query"],["Om"]]]]],"lz"],ZO=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){function a(){return _.n(function*(){const {query:u,Om:w}=b();if(u!==""){var x=_.WTb(u);w!==""&&x.searchParams.append("pq",w);x=yield _.lRb(x);d||(x=x?_.NL(new _.nRb(_.XTb(x))):"",x===""?(l(""),c("",0)):(f().j.j(Object.assign({},_.mRb([]),{aJ:{Kp:{ss:199,qs:[160]},VH:u.length,length:x.length}})),l(u+x),c(u+x,r.value.offsetHeight)))}})}const b=this.j().inputs,c=_.ot(this,"kMEGm"),
d=this.j().lz,e=_.lt(this,0,"div",!1),f=_.Kj(_.Ps(e,_.ML));this.fa("NvLm5b",_.O(()=>b().query,void 0,"xscXRe"));const [g,k]=this.fa("GUCSgd",_.K("",void 0,"uZsIuf")),l=k,r=_.lt(this,1,"span",!1),t=this.fa("efYfac",_.O(()=>{const u=b().query;return u===""?"":g().startsWith(u)?g().substring(u.length):""},void 0,"yEmZTe"));this.fa("dwGWT",_.O(()=>t()!=="",void 0,"BPi5ze"));_.Zs(()=>{a()},"tNeU2e");this.la();this.ea()}j(){return super.j()}ba(){return G4b}da(){throw Error("Ie");}};
ZO.prototype.$wa$TKxcbd=function(){return this.da};ZO.prototype.$wa$p2ggSe=function(){return this.ba};ZO.prototype.$wa$QyQmSc=function(){return this.j};ZO.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("TYPcCd",[_.X]),ZO);
_.q();
_.h("YpdhLe");
var H4b=[["isOpen",["s"]]],$O=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){_.ot(this,"tTT8Tc");_.ot(this,"quQ7H");const a=_.ni("https://support.google.com/websearch/answer/7368877");this.ta("ttVHBc",()=>{_.Bs(window,_.ni(a))});this.ea()}j(){return super.j()}ba(){return H4b}da(){throw Error("Ie");}};$O.prototype.$wa$TKxcbd=function(){return this.da};$O.prototype.$wa$p2ggSe=function(){return this.ba};$O.prototype.$wa$QyQmSc=function(){return this.j};$O.prototype.$wa$kXCA5e=function(){return this.aa};
_.P(_.m("YpdhLe",[_.X]),$O);
_.q();
_.h("wVP2q");
var I4b=[["ha",_.Ek(_.oRb)()],["Um",["so"]],["pa",["ve",(0,_.N)()]],"qy"],aP=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){function a(U){U.type==="contextmenu"&&(U.preventDefault(),U.stopPropagation())}function b(U,W){U.addEventListener("touchstart",T=>{V=setTimeout(()=>{T.preventDefault();T.stopPropagation();W(T)},500)});U.addEventListener("touchend",()=>{clearTimeout(V)});U.addEventListener("touchmove",()=>{clearTimeout(V)});U.addEventListener("contextmenu",
T=>{T.preventDefault();T.stopPropagation()})}const c=this.j().ha,d=_.ot(this,"Qp553b"),e=_.ot(this,"SX8t4"),f=this.j().Um,g=this.j().pa,k=this.j().qy,l=_.lt(this,0,"div",!1),r=_.lt(this,1,"button",!1),t=_.pl(c,_.JM,9).length>0?_.pl(c,_.JM,9).map(U=>_.y(U,1)).join(""):_.y(c,1);let u=!1;this.ja("KjsqPd",function(){if(!r.value.disabled){r.value.disabled=!0;setTimeout(()=>{if(r==null?0:r.value)r.value.disabled=!1},1E3);var U=_.HM(_.GM(_.ZTb((new _.Iv).j(_.y(c,1)),4),_.Gl(c,10)===1||_.Bl(c,3)),_.Gl(c,
10)===4?!0:void 0);_.Gl(c,10)!==0&&U.Kb(_.Gl(c,10));d(U,l.value,_.Ys(f))}});const w=_.nt(this,2,"div",!1),[x,z]=this.fa("QQNyac",_.K(!1,void 0,"wdXYhc")),[B,F]=this.fa("woO5Wc",_.K(!1,void 0,"SebKof"));let H;const I=this.ta("lQPRyd",()=>{u=!0}),M=this.ta("JxJRMd",()=>{z(!1);_.Ix&&document.removeEventListener("contextmenu",a);if(u){u=!1;var U=_.vxb(new _.xw,"autocomplete_user_feedback_kp_id");U=_.Ml(U,18,k||!g?_.w2a.id:g.id);U=_.fG(_.kG(_.hG(_.aUb(_.dG(_.$Tb(_.wxb(_.vw(_.gG(_.eG(U),11),11).setAttribute("AutocompletePrediction"),
5010715)),t)))),_.IM(_.IM(_.IM(_.IM(_.IM(new _.Sv,"scuti_ui_version","2"),"query",""),"choices_sc",t),"suggestion-type_sc",String(_.Cl(c,5))),"suggestion-subtypes_sc",_.wj(c,6,_.ej,_.Mk()).join(" ")));_.Xm(document.body,"qjLxRc",U.serialize());e(c)}}),R=()=>{w.value!==null&&(_.Ix&&document.addEventListener("contextmenu",a),F(!0),z(!0))};this.ja("vITW8b",R);let V;this.onInit(function(){_.Ix&&_.Bl(c,2)&&b(l.value,R)});this.Ta(function(){H&&(H(),H=void 0)});_.pt(this,"HugV6",B,()=>_.S(_.zx,{na:B,then:()=>
_.S(_.YTb,{isOpen:x,be:M,QQ:I})}));this.la();this.ea()}j(){return super.j()}ba(){return I4b}da(){throw Error("Ie");}};aP.prototype.$wa$TKxcbd=function(){return this.da};aP.prototype.$wa$p2ggSe=function(){return this.ba};aP.prototype.$wa$QyQmSc=function(){return this.j};aP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("wVP2q",[_.X]),aP);
_.q();
_.h("TgdQEf");
var J4b=[["ha",_.Ek(_.kM)()],["Tf",(0,_.ZQb)()],["config",["r",[["shouldFetchRecommendations"],["disableAnimation"],["disableSuggestVeLogging"],["shouldHandlePrefetchOnly"]]]],["bk",{kka:0,ima:1,c6:2,ufa:3}]],bP=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){const a=this.j().ha,b=_.ot(this,"Qp553b"),c=this.j().Tf,d=this.j().config,e=this.j().bk,f=a.j(),[g,k]=this.fa("cBqIic",_.K(d.disableAnimation,void 0,"L0toee")),[l,r]=this.fa("JX1Gx",_.K(d.shouldFetchRecommendations?
[]:f,void 0,"X7dG4e"));this.fa("j8w0Od",_.O(()=>_.Z("AzTUSc",g()?"z5wVW":"JZX7Zb",e===3?"y3QVGb":""),void 0,"ORqQz"));const t=_.lt(this,1,"div",!1),u=_.Kj(_.Ps(t,_.OL)),w=_.Kj(_.Ps(t,_.ML)),x=this.ta("Fckft",(T,Y,aa)=>{_.xH&&w().j.j({name:"suggestionSelected",Um:aa});b(T,Y)}),z=this.ta("Ppu6Cb",T=>{_.qUb(u(),T);_.LM(u(),!0,"",H(),R(),_.xH?w().j:void 0,_.Gl(c,10))}),[B,F]=this.fa("sUk96e",_.K(0,void 0,"mdguDf")),H=B,[I,M]=this.fa("tD51ge",_.K(void 0,void 0,"hewi0e")),R=I,V=_.Kj(_.Ps(t,_.JL)),U=_.Ie(_.CL),
W=[];_.Zs(()=>{d.shouldHandlePrefetchOnly||(u().aa=f,_.LM(u(),!!d.shouldFetchRecommendations,"",H(),R(),_.xH?w().j:void 0,_.Gl(c,10)))},"sJgKe");this.onInit(function(){W.push(V().j.bind(F));W.push(U.aa.bind(M));t.value.dataset.hydrated==="true"&&k(!0);d.shouldFetchRecommendations&&(t.value.dataset.hydrated="true");W.push(u().j.bind(r))});this.Ta(function(){for(;W.length>0;)W.pop()()});_.pt(this,"HugV6",l,()=>_.S(_.Px,{Ga:l},(T,Y)=>_.S("li",{class:"Ha884"},_.S(_.kUb,{ha:T,Em:x,uR:z,bk:e||1,pa:_.s4a,
Um:Y,qy:d.disableSuggestVeLogging}))));this.ea()}j(){return super.j()}ba(){return J4b}da(){throw Error("Ie");}};bP.prototype.$wa$TKxcbd=function(){return this.da};bP.prototype.$wa$p2ggSe=function(){return this.ba};bP.prototype.$wa$QyQmSc=function(){return this.j};bP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("TgdQEf",[_.X]),bP);
_.q();
_.h("Veb2cb");
var K4b=[],cP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return K4b}da(){throw Error("Ie");}};cP.prototype.$wa$TKxcbd=function(){return this.da};cP.prototype.$wa$p2ggSe=function(){return this.ba};cP.prototype.$wa$QyQmSc=function(){return this.j};cP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("Veb2cb",[_.X]),cP);
_.q();
_.h("IlmhKc");
var XPb=[],kL=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return XPb}da(){throw Error("Ie");}};kL.prototype.$wa$TKxcbd=function(){return this.da};kL.prototype.$wa$p2ggSe=function(){return this.ba};kL.prototype.$wa$QyQmSc=function(){return this.j};kL.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("IlmhKc",[_.X]),kL);
_.q();
_.h("cl43Hd");
var L4b=[],dP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return L4b}da(){throw Error("Ie");}};dP.prototype.$wa$TKxcbd=function(){return this.da};dP.prototype.$wa$p2ggSe=function(){return this.ba};dP.prototype.$wa$QyQmSc=function(){return this.j};dP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("cl43Hd",[_.X]),dP);
_.q();
_.h("oOHUse");
var Uqb=[],mE=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return Uqb}da(){throw Error("Ie");}};mE.prototype.$wa$TKxcbd=function(){return this.da};mE.prototype.$wa$p2ggSe=function(){return this.ba};mE.prototype.$wa$QyQmSc=function(){return this.j};mE.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("oOHUse",[_.X]),mE);
_.q();
_.h("xfXxve");
var M4b=[],eP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return M4b}da(){throw Error("Ie");}};eP.prototype.$wa$TKxcbd=function(){return this.da};eP.prototype.$wa$p2ggSe=function(){return this.ba};eP.prototype.$wa$QyQmSc=function(){return this.j};eP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("xfXxve",[_.X]),eP);
_.q();
_.h("Bpyu8c");
var N4b=[],fP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return N4b}da(){throw Error("Ie");}};fP.prototype.$wa$TKxcbd=function(){return this.da};fP.prototype.$wa$p2ggSe=function(){return this.ba};fP.prototype.$wa$QyQmSc=function(){return this.j};fP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("Bpyu8c",[_.X]),fP);
_.q();
_.h("mS46Ef");
var O4b=[],gP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return O4b}da(){throw Error("Ie");}};gP.prototype.$wa$TKxcbd=function(){return this.da};gP.prototype.$wa$p2ggSe=function(){return this.ba};gP.prototype.$wa$QyQmSc=function(){return this.j};gP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("mS46Ef",[_.X]),gP);
_.q();
_.h("qHR9mb");
var P4b=[],hP=class extends _.Q{constructor(a){super(a.ga);this.response=a}aa(){this.ea()}j(){return super.j()}ba(){return P4b}da(){throw Error("Ie");}};hP.prototype.$wa$TKxcbd=function(){return this.da};hP.prototype.$wa$p2ggSe=function(){return this.ba};hP.prototype.$wa$QyQmSc=function(){return this.j};hP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("qHR9mb",[_.X]),hP);
_.q();
_.h("P5gZDb");
var R4b,iP;_.Q4b=_.Ek(_.TN);
R4b=[["ha",(0,_.Q4b)()],["isActive",["so"]],"Zq",["nr",["so"]],"Xr",["Hq",["so"]],"cE","pM",["config",["r",[["enableEclipseAudioWave"],["enableImageUpload"],["enableFileUpload"],["enableDeepSearch"],["enableDeepBrowse"],["enableImageGenTool"],["closeCallback"],["disableCloseIfClickedOutside"],["enableFog"],["useSearchSparkIcon"],["ghostTextPlaceholder"],["enableCanvas"],["suggestConfig",["r",[["showSuggestionsBelowInputPlate"],["zeroStateConfig",["r",[["enableZeroPrefixSuggestions"],["shouldRefreshZeroPrefixSuggestions"],
["enableTypedSuggestions"]]]],["followupConfig",["r",[["enableZeroPrefixSuggestions"],["shouldRefreshZeroPrefixSuggestions"],["enableTypedSuggestions"]]]],["mWebClassicSearchboxVariant"]]]],["isFinal"]]]],"mr"];
iP=class extends _.Q{constructor(a){super(a.ga);this.response=a;a=this.ka();_.kt(this,a)}aa(){function a(Za,Xb){_.NF?(Ssa.push(Za),fPa([...Ssa]),Xb()):(ata(Za),sV=Xb,tV=void 0,bta("error"),tj(5))}function b(Za,Xb,rd){switch(Za){case 1:return _.NF?_.cXb(rd):"Cannot search with multiple files";case 2:return _.eXb(Xb);case 3:return _.fXb(Xb);case 4:return Za=[],Za.push(...Array.from(Rsa(),He=>"."+He.split("/")[1])),_.dXb(Za.sort());case 5:return _.NF?"Exceeds 100MB":"File is larger than 100 MB";case 6:return"Some of your URLs were not included in the response.";
default:return""}}function c(Za,Xb){for(const rd of Za.values())if(rd===Xb)return!0;return!1}function d(Za,Xb){Za instanceof FileList&&(Za=Array.from(Za));if(!Xb){const cg=jg();Xb=()=>{tj(cg)}}var rd=_.AL(Bi,1)+_.AL(Bi,2);const He=_.NF?_.lXb(_.nl(jb,_.kN,1))||1:1;rd={Gz:{count:_.NF?He-rd:1,cN:!_.NF||rd===He,dN:!_.NF||rd===He},maxFileSize:1E8,PB:Rsa(),yM:_.NF&&rd<He,UN:_.mXb(Bi)};rd=_.kXb(Za,rd);rd.forEach((cg,xh)=>{cg!==2&&cg!==3||a(b(cg,xh,He),Xb)});if(c(rd,1)&&(a(b(1,"",He),Xb),!_.NF))return!1;
if(_.NF){c(rd,4)&&a(b(4,"",He),Xb);for(var Zh of Za){const cg=rd.get(Zh.name);cg&&cg!==5||_.lN(Bi,Zh,cg?b(cg,Zh.name,He):void 0)}}else if(Za.length>0){if(Zh=rd.get(Za[0].name))return a(b(Zh,Za[0].name,He),Xb),!1;if(_.nXb(Bi))return ata("Replace current file?"),sV=()=>{_.FM(Bi,"filemodality");_.lN(Bi,Za[0]);Xb()},tV=Xb,bta("confirmation"),tj(5),!1;_.lN(Bi,Za[0])}return jg()!==5?(_.rc()&&_.axb||vj(),_.rc()&&_.Vwb&&T(),_.rc()&&_.Zwb&&W(),_.rc()&&_.$wb&&fa(),!0):!1}function e(){return{pw:()=>{aa()},bv:()=>
{Ut(!0);B()},Nt:()=>{B()},Sw:Za=>{l(Za);No(Za);Xi(!0)},xw:Za=>{u(Za,{nG:!0})},Lt:af,Gg:xe}}function f(){if(Im===null){Tg(!0);var Za=!1;Im=()=>{Za=!0};_.hXb(e()).then(Xb=>{Za?(Xb==null||Xb(),Im=null):Im=Xb}).catch(()=>{Za||(Im=null)})}}function g(){return _.n(function*(){Im!==null?_.wH&&Y():(Tg(!0),Im=yield _.hXb(e()))})}function k(){Fn(Cb.value.value.trim()!=="")}function l(Za){Cb.value.value=Za;k();sa();na()}function r(){Re(!1);if(nq()!==4){var Za=lc&&!_.Ys(xa)&&zb.value.style.height===window.getComputedStyle(zb.value).minHeight;
_.sH?requestAnimationFrame(()=>{Lh(!0);Za&&Oc(!0);setTimeout(()=>{Lh(!1);Oc(!1)},750)}):requestAnimationFrame(()=>{Mb.value&&(Mb.value.classList.add("sPJmO"),Za&&Mb.value.classList.add("BeJZl"),setTimeout(()=>{Mb.value!==null&&Mb.value.classList.remove("sPJmO","BeJZl")},500))})}}function t(Za,Xb){Vj(!0);Xb||r();Za.me(ZC());if(!_.qCb){var rd=_.aDb(_.Gl(Za,15));_.SCb&&rd!==0?If().Kb(rd):_.Bl(Za,4)?If().Kb(1):_.Bl(Za,6)?If().Kb(5):_.Bl(Za,11)?If().Kb(2):_.Bl(Za,12)&&If().Kb(4)}Za.Kb(Vk());az=Za.Fd();
Bi.vg(Za);if(_.xH){gw().j.j({name:"endSession",Og:performance.now()});const Zh=_.oXb(gw().j);rd=_.yj(Za,9,_.mj);var He=Cb.value.value;rd.set("gs_lp",_.Gi((0,_.pXb)(Zh),4));rd.set("oq",He);w()}B(!0);_.GTb();Xb?eb&&eb(Za,Xb):oa(Za);_.AH&&T()}function u(Za,{nG:Xb=!1}){if($C()){Za=Za.trim();document.documentElement.style.removeProperty("--sxs-input-plate-height");var rd=_.HM(_.qXb(_.rXb(_.GM(_.ZTb((new _.Iv).j(Za),Xb||Ef()?2:1),jw()),Wt()),Pr()),Hm());_.JCb?(Xb=x(Za,rd),_.uH?Xb.then(()=>{t(rd)}):t(rd)):
t(rd)}}function w(){gw().j.j({name:"startSession",Zx:"aim-web",Og:performance.now(),rB:_.LA||_.Sfb})}function x(Za,Xb){return _.n(function*(){const rd=(cg,xh)=>{cg=_.mN(new _.Hv,cg);Xb.aa(cg);var Hn;cg=(Hn=Xb.ba())!=null?Hn:new _.Fv;Hn=xh;try{Hn=(new URL(xh.includes("://")?xh:`https://${xh}`)).hostname}catch(bz){}xh=new _.SA;xh=_.Nl(xh,3,Hn);xh=_.sXb(xh);_.ul(cg,2,_.SA,xh);Xb.da(cg)};if(!(_.yA(Xb,_.Hv,2)>0)){var He=_.xWb(Za);if(_.NF||He.length===1){if(_.NF){var Zh=_.AL(Bi,1)+_.AL(Bi,2);Zh=_.lXb(_.nl(jb,
_.kN,1))-Zh;if(Zh<He.length){const cg=jg();a("Some of your URLs were not included in the response.",()=>{tj(cg)})}He=He.slice(0,Zh)}He=He.map(cg=>{const xh=_.sWb();_.Ml(xh,9,1);_.uH||(_.nN(xh,5),rd(xh,cg));return{url:cg,Uf:xh}});for(const {url:cg,Uf:xh}of He){He=_.yWb(cg,xh);try{const Hn=yield _.nWb(He);if(Hn.Ne())break;let bz;const gJ=(bz=_.Bk(Hn,_.tXb,2))==null?void 0:_.Cl(bz,8);let cD;_.nN(xh,(cD=gJ)!=null?cD:0)}catch(Hn){break}_.uH&&rd(xh,cg)}}}})}function z(){Cb.value.animate([{opacity:"1"},
{opacity:"0"}],{duration:100,delay:250,fill:"both",easing:"cubic-bezier(0.3, 0, 1, 1)"}).finished.then(()=>{l("");Cb.value.animate([{opacity:"0"},{opacity:"1"}],{duration:50,fill:"both",easing:"cubic-bezier(0.3, 0, 1, 1)"})})}function B(Za=!1){Xi(!1);nq()===4?_.EL(Bi):(_.EL(Bi),_.vH&&!_.Ix?z():l(""),T(Za),zc.value.setAttribute("data-before",""),zc.value.setAttribute("data-after",""),zc.value.removeAttribute("style"),Cb.value.removeAttribute("style"),ra(),na(),Za&&(Za||_.uXb(If())),_.Ys(Oa)&&vj())}
function F(Za){var Xb=yc.value;if(Xb&&Xb.contains(Za.target)){var rd=Xb.scrollTop,He=Xb.scrollHeight;Xb=Xb.clientHeight;if(He>Xb){var Zh,cg=(((Zh=Za.touches[0])==null?void 0:Zh.clientY)||0)-(wl||0);Zh=cg<0;cg>0&&rd<=0?Za.preventDefault():Zh&&rd+Xb>=He&&Za.preventDefault()}else Za.preventDefault()}else Za.preventDefault()}function H(){!_.Ix||_.AH&&_.Ys(xa)||(Gc.value.hidden=!1,_.zf(Gc.value.offsetWidth),Gc.value.removeEventListener("transitionend",aJ),window.removeEventListener("pageshow",I),document.body.style.overflow=
"hidden",_.rc()&&_.WF&&document.body.addEventListener("touchmove",F,{passive:!1}))}function I(Za){Za.persisted&&(Gc.value.hidden=!0)}function M(Za=!1){_.Ix&&(Za?Gc.value.hidden=!0:(Gc.value.addEventListener("transitionend",aJ,{once:!0}),window.addEventListener("pageshow",I,{once:!0})),document.body.style.removeProperty("overflow"),_.rc()&&_.WF&&document.body.removeEventListener("touchmove",F))}function R(){setTimeout(()=>{document.addEventListener("click",ba)},500)}function V(){return jg()===2||jg()===
3}function U(Za,Xb=!1){bJ.ra().j(Za,Xb?5:3).log(!0)}function W(Za=!1){V()||(Re(!1),_.zf(Mb.value.offsetWidth),Za||H(),tj(2),UC=!0,R(),sa(),aD=window.scrollY,Jf(!0),setTimeout(()=>{Jf(!1)},1E3))}function T(Za=!1,Xb=!1){Cb.value.blur();UC&&!_.Ys(Oa)&&(UC=!1,zb.value.style.removeProperty("height"),document.documentElement.style.removeProperty("--sxs-input-plate-height"));yc.value.scroll({top:0,behavior:"instant"});_.rc()&&_.oc()&&_.bxb&&window.visualViewport&&zb.value.style.removeProperty("transform");
tj(_.Ys(Oa)?2:1);document.removeEventListener("click",ba);M(Za);Y(Za,Xb);TC&&aD!==void 0&&(window.scrollTo({top:aD,behavior:"smooth"}),aD=void 0);ra();na();fm(!1)}function Y(Za=!1,Xb=!1){Im!==null&&(Im(),Im=null);No("");Wj(!1);let rd;const He=(rd=Mb.value)==null?void 0:rd.querySelector('[data-xid="h4gG8"]');!He||Za||Xb||setTimeout(()=>{He.focus()},0)}function aa(){Re(!1);Wj(!0);H();let Za;const Xb=(Za=Mb.value)==null?void 0:Za.querySelector('[data-xid="ljhwxf"]');Xb&&setTimeout(()=>{Xb.focus()},0);
tj(_.wH?2:3);R()}function ba(Za){if(!nb||!nb.disableCloseIfClickedOutside)if(!(Za.target instanceof Node)||document.body.contains(Za.target)){var Xb,rd;zb.value.contains(Za.target)||((Xb=$d)==null?0:(rd=Xb.value)==null?0:rd.contains(Za.target))||Za.target instanceof HTMLElement&&Za.target.closest("[data-turn-building]")!==null||(T(),U(Gc.value))}}function fa(){if(Cb.value!==null)if(Cb.value.selectionStart!==Cb.value.selectionEnd)zc.value.classList.add("pvW4Ge");else{var Za=Cb.value.selectionStart,
Xb=Cb.value.value.slice(0,Za),rd=Cb.value.value.slice(Za);Za=yc.value.scrollTop;Cb.value.style.height="0px";zc.value.style.height="0px";zc.value.setAttribute("data-before",Xb);zc.value.setAttribute("data-after",rd||" ");Xb=Cb.value.value.length<CV;CV=Cb.value.value.length;rd=Cb.value.scrollHeight>zc.value.scrollHeight;const He=_.oc()||_.rc();Xb&&He&&rd&&(Xb=Cb.value.style.paddingRight,Cb.value.style.paddingRight="1px",_.zf(Cb.value.offsetWidth),Cb.value.style.paddingRight=Xb||"");Xb=ka();zc.value.classList.remove("pvW4Ge");
zc.value.style.height=`${Xb}px`;Cb.value.style.height=`${Xb}px`;yc.value.scrollTop=Za;ha(Xb);da();zc.value.removeAttribute("animating-caret");_.zf(zc.value.offsetHeight);zc.value.setAttribute("animating-caret","")}}function ka(){return Math.max(Cb.value.scrollHeight,24*(_.Ix&&!_.zH?2:1),Math.ceil(jta/24)*24)}function ha(Za){UC&&(Za=Za+24+48+(_.zH?12:16)+(WI()?68:0),zb.value.style.height=`${Za}px`,document.documentElement.style.setProperty("--sxs-input-plate-height",`${Za}px`))}function da(){V()?Math.abs(yc.value.scrollHeight-
yc.value.clientHeight-yc.value.scrollTop)>1?fm(!0):fm(!1):fm(!1)}function sa(){_.LA&&Tj({query:BV?"":Cb.value.value,Om:az})}function na(){if(ud)if(jg()!==2)_.vXb(lw());else if(IV()){let Za;_.LM(lw(),!((Za=ua())==null||!Za.shouldRefreshZeroPrefixSuggestions),"",Vk(),kq(),void 0,_.Gl(jb,10))}else DPa()?_.LM(lw(),!0,Cb.value.value):_.vXb(lw())}function ra(){hw="";Tj({query:"",Om:""})}function ua(){if(Hm()||jw()||Pr()){let Za,Xb;return _.Ys(xa)?(Za=nb)==null?void 0:(Xb=Za.suggestConfig)==null?void 0:
Xb.zeroStateConfig:void 0}if(!XI()){let Za,Xb,rd,He;return _.Ys(xa)?(Za=nb)==null?void 0:(Xb=Za.suggestConfig)==null?void 0:Xb.zeroStateConfig:(rd=nb)==null?void 0:(He=rd.suggestConfig)==null?void 0:He.followupConfig}}function ta(){if(zb.value){const Za=_.Jx(zb.value),Xb=zb.value.getBoundingClientRect();Za&&window.innerWidth-Xb.right<150?St(5):!Za&&Xb.left<150?St(6):St(1)}}const Ka=this.j().ha,ya=this.j().isActive,Aa=this.j().Zq,xa=this.j().nr,oa=_.ot(this,"lc6cze"),za=this.j().Xr;_.mt(this,"TlpD4");
const Oa=this.j().Hq,Ua=this.j().cE,kb=this.j().pM,nb=this.j().config,eb=_.mt(this,"vNEa7c");let Ra,qb,ib,wb,xb,ab,hb,Sa,Va;const jb=this.j().mr?Ka.j():_.v(_.wXb(_.xXb(_.yXb(_.zXb(_.AXb(_.BXb(_.CXb(new _.DL,[...(((Ra=nb)==null?0:Ra.enableImageGenTool)&&_.zwb&&!_.PF?[_.v(_.oN(_.pN(_.qN(_.rN(_.sN(_.tN(4),"\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f"),_.Ix?"\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f":"\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f"),
"\u041e\u043f\u0438\u0448\u0438\u0442\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435"),_.v(_.uN(_.WCb?98:100))),_.v(_.DXb())))]:[]),...(((qb=nb)==null?0:qb.enableDeepSearch)&&_.Pfb&&_.kF?[_.v(_.EXb(_.oN(_.pN(_.vN(_.qN(_.rN(_.sN(_.tN(1),"Deep Search"),"Deep Search"),"\u0418\u0441\u0441\u043b\u0435\u0434\u0443\u0439\u0442\u0435 \u043b\u044e\u0431\u0443\u044e \u0442\u0435\u043c\u0443")),_.v(_.uN(94))),_.v(_.wN(1))),[_.v(_.FXb(_.GXb(),_.Ix?"\u041d\u0443\u0436\u043d\u043e \u0431\u043e\u043b\u044c\u0448\u0435 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438":
"\u0414\u043e\u0431\u0430\u0432\u044c\u0442\u0435 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e \u0438\u043b\u0438 \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u0412\u0432\u043e\u0434, \u0447\u0442\u043e\u0431\u044b \u043d\u0430\u0447\u0430\u0442\u044c \u0438\u0441\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u0435"))]))]:[]),...(((ib=nb)==null?0:ib.enableCanvas)?[_.v(_.EXb(_.oN(_.pN(_.vN(_.qN(_.rN(_.sN(_.tN(2),"Canvas"),"Canvas"),"\u0421\u043e\u0437\u0434\u0430\u0432\u0430\u0439\u0442\u0435 \u0447\u0442\u043e \u0443\u0433\u043e\u0434\u043d\u043e")),
_.v(_.uN(96))),_.v(_.HXb())),[_.v(_.FXb(_.IXb(5),"\u0417\u0430\u0434\u0430\u0439\u0442\u0435 \u0432\u043e\u043f\u0440\u043e\u0441"))]))]:[]),...(((wb=nb)==null?0:wb.enableDeepBrowse)&&_.Ofb&&_.TF?[_.v(_.oN(_.pN(_.vN(_.qN(_.rN(_.sN(_.tN(5),"Task Agent"),"Task Agent"),"\u0418\u0441\u0441\u043b\u0435\u0434\u0443\u0439\u0442\u0435 \u043b\u044e\u0431\u0443\u044e \u0442\u0435\u043c\u0443")),_.v(_.uN(95))),_.v(_.wN(5))))]:[])]),[...(((xb=nb)==null?0:xb.enableImageUpload)&&!_.PF?[_.v(_.JXb(_.KXb(_.LXb(_.MXb(1),
"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435"),_.v(_.uN(93))),_.v(_.NXb(_.OXb(1)))))]:[]),...(((ab=nb)==null?0:ab.enableFileUpload)&&_.Awb&&!_.PF?[_.v(_.JXb(_.KXb(_.LXb(_.MXb(2),"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0444\u0430\u0439\u043b"),_.v(_.uN(92))),_.v(_.NXb(_.OXb(2)))))]:[])]))),(hb=Ka.j())==null?void 0:hb.j()),(Sa=Ka.j())==null?void 0:_.nl(Sa,_.kN,1)),(Va=Ka.j())==null?void 0:_.Gl(Va,10))),Na=
Za=>_.pl(jb,_.IL,5).find(Xb=>_.Gl(Xb,1)===Za),db=Za=>_.pl(jb,_.HL,6).find(Xb=>Xb.getModel()===Za),La=Za=>_.pl(jb,_.GL,4).find(Xb=>_.Gl(Xb,1)===Za),Fb=Ka==null?void 0:Ka.aa();let lb,pb;const ac=(pb=(lb=Na(1))==null?void 0:_.y(lb,3))!=null?pb:"";let Kb,cc;const Sb=(cc=(Kb=Na(5))==null?void 0:_.y(Kb,3))!=null?cc:"";let kc,Tb;const gb=(Tb=(kc=Na(2))==null?void 0:_.y(kc,3))!=null?Tb:"";let ic,Rc;const xd=(Rc=(ic=La(1))==null?void 0:_.y(ic,2))!=null?Rc:"";let ge,vc;const Zc=(vc=(ge=La(2))==null?void 0:
_.y(ge,2))!=null?vc:"";let jc,qd;const yd=(qd=(jc=db(1))==null?void 0:_.y(jc,2))!=null?qd:"";let Be,ld;const Ed=(ld=(Be=db(3))==null?void 0:_.y(Be,2))!=null?ld:"";let qe,Td;const ef=(Td=(qe=db(2))==null?void 0:_.y(qe,2))!=null?Td:"";let le,ff;const Nc=(ff=(le=db(4))==null?void 0:_.y(le,2))!=null?ff:"";let Kd;const ve=((Kd=Na(4))==null?void 0:_.y(Kd,3))||"",Ld=_.gwb&&_.Ix,ce=Array.from(_.xL).join(","),pf=`.pdf,application/pdf,${ce}`,De=_.lt(this,0,"div",!1),$d=_.nt(this,1,"div",!0),Ad=_.nt(this,2,
"div",!1),we=_.nt(this,3,"div",!1),Mb=_.lt(this,4,"div",!1),yc=_.lt(this,5,"div",!1),zb=_.lt(this,6,"div",!1),Cb=_.lt(this,7,"textarea",!1),zc=_.lt(this,8,"div",!1),Gc=_.lt(this,9,"div",!1),sd=_.lt(this,10,"div",!1),$e=_.nt(this,11,"div",!1),af=Ka.ea(),xe=Ka.da(),Eb=typeof Oa==="boolean"?Oa:Ua,lc=!_.Ix&&Eb;let mb,Ga,ub,Ab,Wa,Db,bb,Da,fb,Rb,Qc,Wc;const ud=!!(((mb=nb)==null?0:(Ga=mb.suggestConfig)==null?0:(ub=Ga.zeroStateConfig)==null?0:ub.enableZeroPrefixSuggestions)||((Ab=nb)==null?0:(Wa=Ab.suggestConfig)==
null?0:(Db=Wa.zeroStateConfig)==null?0:Db.enableTypedSuggestions)||((bb=nb)==null?0:(Da=bb.suggestConfig)==null?0:(fb=Da.followupConfig)==null?0:fb.enableZeroPrefixSuggestions)||((Rb=nb)==null?0:(Qc=Rb.suggestConfig)==null?0:(Wc=Qc.followupConfig)==null?0:Wc.enableTypedSuggestions)),Zd=new Set(_.pl(jb,_.GL,4).map(Za=>_.Gl(Za,1))),Ze=Zd.size>0,Df=Zd.has(1),Gb=Zd.has(2),$b=new Set(_.pl(jb,_.IL,5).map(Za=>_.Gl(Za,1))),Xc=$b.size>0,gd=$b.has(1),Ee=$b.has(2),Hg=$b.has(5),Ib=$b.has(4),[nc,Ac]=this.fa("NNgNdd",
_.K(!1,void 0,"yxbjEb")),[fd,Dd]=this.fa("NT4DDf",_.K(!1,void 0,"r2ukUb")),[Md,bf]=this.fa("LUnZ5",_.K(!1,void 0,"Bx17ac")),Lh=bf,[ji,Jb]=this.fa("khJHBe",_.K(!1,void 0,"bqfoF")),Oc=Jb,[fe,Qd]=this.fa("WryyRc",_.K(za,void 0,"iBw5Kd")),Re=Qd,[vf,Wi]=this.fa("QRdRL",_.K(!1,void 0,"nfgLrd")),Vj=Wi,[mh,nh]=this.fa("XiUwde",_.K(!1,void 0,"pxHQp")),Wj=nh,[Uk,Jm]=this.fa("uh1U2",_.K(!1,void 0,"WUOhmc")),Fn=Jm,[,em]=this.fa("OgMUtf",_.K("",void 0,"DIbRZ")),No=em,[VC,Vi]=this.fa("sOsWOc",_.K(!1,void 0,"ZGhRac")),
fm=Vi,[uk,Tt]=this.fa("S3Lcgb",_.K(!1,void 0,"CuZHwb")),Ut=Tt,[Gn,vk]=this.fa("qQ11Lb",_.K(!1,void 0,"sy4uz")),[Or,Vt]=this.fa("HyHOnb",_.K(!_.PF,void 0,"DLhUAf")),[Qr,ug]=this.fa("kC3Mg",_.K({query:"",Om:""},void 0,"A2u9Ye")),Tj=ug,[iw,Yy]=this.fa("umZ0k",_.K(Eb?2:1,void 0,"mWu28")),jg=iw,tj=Yy,[xc,Yd]=this.fa("uBHkTd",_.K(!1,void 0,"K5jUj")),Jf=Yd,[lh,oh]=this.fa("rFEqZd",_.K(!1,void 0,"B444K")),[Rr,Ig]=this.fa("aUIbZ",_.K(!1,void 0,"WdXeSb")),Tg=Ig,[xl,Km]=this.fa("og0Jfb",_.K(!0,void 0,"KcgDNd")),
[uj,Sr]=this.fa("dAL57c",_.K(!1,void 0,"H0Zi7c")),[Nr,jq]=this.fa("wxR3gf",_.K(!1,void 0,"wFacnd")),[Lc,Gd]=this.fa("AmnBze",_.K(!1,void 0,"Q0a1sd")),Ef=Lc,Xi=Gd,[Zy,VI]=this.fa("YwES9e",_.K([],void 0,"EwIlmb")),WI=this.fa("Kvfo9e",_.O(()=>Zy().length>0,void 0,"axKqhb")),[$y,aPa]=this.fa("OZNjQc",_.K(!1,void 0,"A7xwrd")),[bPa,cPa]=this.fa("cjrZF",_.K(!1,void 0,"IY6tn")),[WC,Jsa]=this.fa("py0SJe",_.K({yr:0,Zz:0,oQ:0,zr:0},void 0,"WrKBre")),OI=this.fa("BVhabf",_.O(()=>jg()===5,void 0,"IFV6Jf")),[qV,
dPa]=this.fa("NjldL",_.K("",void 0,"En8gje")),ata=dPa;let sV=void 0,tV=void 0;const Ksa=this.ta("poe6lb",()=>{let Za;(Za=sV)==null||Za()}),ePa=this.ta("gHH9fc",()=>{let Za;(Za=tV)==null||Za()}),[XOa,Isa]=this.fa("IAMsed",_.K("confirmation",void 0,"QK6KXb")),bta=Isa,[,fPa]=this.fa("szlvbb",_.K([],void 0,"Ah0Pcd")),Ssa=[],[gPa,hPa]=this.fa("tD51ge",_.K(void 0,void 0,"eSmwHe")),kq=gPa,[cta,iPa]=this.fa("sUk96e",_.K(0,void 0,"IihAo")),Vk=cta,[fw,QI]=this.fa("MBxLce",_.K(0,void 0,"WpGqB")),Hm=this.fa("sGruaf",
_.O(()=>Vk()===4,void 0,"PAAH5b")),Pr=this.fa("ganhLc",_.O(()=>Vk()===2,void 0,"ZuwSff")),Wt=this.fa("z3gdrd",_.O(()=>Vk()===5,void 0,"INDr4d")),jw=this.fa("jHLdCf",_.O(()=>Vk()===1,void 0,"Ls2jie")),XI=this.fa("zF7yje",_.O(()=>Vk()!==0,void 0,"y1WFfc")),[YI,ZI]=this.fa("us7zV",_.K(new Set([]),void 0,"YdxRuf")),[dta,eta]=this.fa("f4Ytp",_.K(new Set([]),void 0,"KNIQzf")),[XC,jPa]=this.fa("nstQRc",_.K(new Set([]),void 0,"BzyOg")),uV=this.fa("Z40Mwf",_.O(()=>dta().has(2),void 0,"DhSRRe")),vV=this.fa("im5dmb",
_.O(()=>dta().has(1),void 0,"NW3p0d")),$I=this.fa("c57lwb",_.O(()=>YI().has(4),void 0,"XmWJu")),fta=this.fa("Dl8qWd",_.O(()=>YI().has(2),void 0,"xXSVGb")),wV=this.fa("KCkL2e",_.O(()=>YI().has(5),void 0,"XRahBc")),Xt=this.fa("jyDHgb",_.O(()=>YI().has(1),void 0,"V7omyb")),Tr=this.fa("zMThb",_.O(()=>Xt()?"\u0427\u0442\u043e\u0431\u044b \u0441\u043d\u043e\u0432\u0430 \u0432\u043e\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c\u0441\u044f Deep Search, \u043d\u0430\u0447\u043d\u0438\u0442\u0435 \u043d\u043e\u0432\u044b\u0439 \u043f\u043e\u0438\u0441\u043a":
"\u0411\u043e\u043b\u0435\u0435 \u043e\u0431\u043e\u0441\u043d\u043e\u0432\u0430\u043d\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b \u0441 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0435\u0439 \u0438\u0437 \u0440\u0430\u0437\u043d\u044b\u0445 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u043e\u0432, \u043d\u043e \u043d\u0435\u043c\u043d\u043e\u0433\u043e \u043c\u0435\u0434\u043b\u0435\u043d\u043d\u0435\u0435",void 0,"PI4Skc")),gta=this.fa("AB851e",_.O(()=>_.rl(jb,_.IL,5).some(Za=>
_.Gl(Za,1)===Vk()&&_.Bl(Za,2)),void 0,"LXAL8d")),YC=new Set(_.rl(jb,_.HL,6).map(Za=>Za.getModel())),Ur=YC.size>1,kPa=YC.has(1),lPa=YC.has(3),hta=YC.has(4),mPa=YC.has(2),nPa=this.fa("wZJOfb",_.O(()=>XC().has(1),void 0,"Vc9NM")),oPa=this.fa("GG3ive",_.O(()=>XC().has(3),void 0,"wVNNRb")),pPa=this.fa("YYs5re",_.O(()=>XC().has(4),void 0,"qfbhg")),RC=this.fa("C1SoI",_.O(()=>XC().has(2),void 0,"Zi5wUd")),[qPa,rPa]=this.fa("yqBAtb",_.K(1,void 0,"ds6A6c")),ZC=qPa,sPa=this.fa("rwJdLd",_.O(()=>ZC()===1,void 0,
"h1lgGc")),tPa=this.fa("AiYWV",_.O(()=>ZC()===3,void 0,"zxUn9b")),uPa=this.fa("qhYQ6b",_.O(()=>ZC()===4,void 0,"jGKW0c")),Osa=this.fa("IYmbPd",_.O(()=>ZC()===2,void 0,"vXgg9c")),[xV,vPa]=this.fa("qtUCre",_.K(!1,void 0,"yMWPGe")),aJ=()=>{Gc.value.hidden=!0},Yt=this.fa("cOLVIe",_.O(()=>fta()||!_.VF&&jb.j()===2,void 0,"bqw32")),Nsa=this.fa("tKEvre",_.O(()=>Yt()?"\u0427\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u043b\u044e\u0447\u0438\u0442\u044c Canvas, \u043d\u0430\u0447\u043d\u0438\u0442\u0435 \u043d\u043e\u0432\u044b\u0439 \u043f\u043e\u0438\u0441\u043a.":
"\u0420\u0430\u0431\u043e\u0447\u0430\u044f \u043e\u0431\u043b\u0430\u0441\u0442\u044c: \u0441\u043e\u0437\u0434\u0430\u0432\u0430\u0439\u0442\u0435 \u0438 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u0443\u0439\u0442\u0435 \u043a\u043e\u043d\u0442\u0435\u043d\u0442",void 0,"JJhrdb"));_.Zs(()=>{if(_.Ys(ya)&&nc()&&!If().ea.value){If().ea.value=!0;var Za=If(),Xb=_.Wh(jb);Za.Tf.value=Xb}},"JMexOc");_.xH&&_.Zs(()=>{_.Ys(ya)&&(w(),Yh.push(lw().j.bind(Za=>{Za=Za.map(Xb=>({ss:_.Cl(Xb,5),qs:Array.from(_.wj(Xb,
6,_.ej,_.Mk()))}));gw().j.j({name:"responseRendered",Kp:Za,Og:performance.now()})})))},"VbKLkb");const zV=this.fa("tRmPFc",_.O(()=>{let Za,Xb,rd;return!((Xb=((rd=(Za=Na(Vk()))==null?void 0:_.rl(Za,_.xN,8))!=null?rd:[]).find(He=>_.Gl(He,1)===fw()))==null||!_.Bl(Xb,3))},void 0,"bJobuc")),dm=this.fa("dBtjX",_.O(()=>Uk()||WI()||zV(),void 0,"JGCtve")),$C=this.fa("NW2FCe",_.O(()=>WC().yr>0?!1:WC().Zz===WC().zr&&WC().zr>0?Uk()||zV():Uk()||bPa()||zV(),void 0,"QHj5y"));this.fa("ibg7bb",_.O(()=>_.Ys(ya)?"input-plate-active":
"",void 0,"OCOk6d"));const nq=this.fa("JWJ2Ef",_.O(()=>{let Za;return xV()||vf()&&((Za=nb)==null?0:Za.isFinal)?4:dm()?2:1},void 0,"u5um2")),oq=this.fa("FfETAf",_.O(()=>nq()===4,void 0,"NqV3t")),ita=this.fa("tYkcE",_.O(()=>oq()||!$C(),void 0,"stgrYe")),Sg=this.fa("uRJWv",_.O(()=>_.Ix||xc()||Gn(),void 0,"AKwule")),AV=this.fa("mfb50d",_.O(()=>Sg()&&!Ka.ba(),void 0,"mjK8Mb")),Bi=_.Ie(_.CL),dg=_.Ie(_.bG),Qy=_.Jj(_.Qn),If=_.Qs(_.JL,De),gw=_.Qs(_.ML,De);let hw="",jta=0,BV=!1;const Psa=this.ta("DWWiC",(Za,
Xb)=>{hw=Za;jta=Xb;fa()});_.Zs(()=>{_.Ys(ya)&&_.PXb(dg,nq())},"IU1Q3");const Xj=this.ta("OWZUve",Za=>{d(Za)}),bJ=_.Ie(_.As),Yh=[],kw=_.ECb||_.Kwb;let wl,Ry=!1,Im=null,TC=!1,aD,UC=Eb,Py=!1,CV=0,az=(new URLSearchParams(window.location.search)).get("q")||"";_.Zs(()=>{_.Ys(ya)&&(az=(new URLSearchParams(window.location.search)).get("q")||"")},"MJynW");const [kta,cJ]=this.fa("au0HV",_.K(null,void 0,"WOEvn"));_.Zs(()=>{WC().yr===0&&kta()&&(kta()(),cJ(null))},"vy1Pt");this.fa("YU5ZI",_.O(()=>{switch(jg()){case 3:return"\u0413\u043e\u0432\u043e\u0440\u0438\u0442\u0435\u2026";
case 4:return"\u041f\u0435\u0440\u0435\u0442\u0430\u0449\u0438\u0442\u0435 \u0444\u0430\u0439\u043b \u0441\u044e\u0434\u0430";case 5:return"";default:if(Hm()&&$y())return"\u041e\u043f\u0438\u0448\u0438\u0442\u0435, \u0447\u0442\u043e \u0432\u044b \u0445\u043e\u0442\u0438\u0442\u0435 \u0438\u0437\u043c\u0435\u043d\u0438\u0442\u044c";const Za=Na(Vk());let Xb,rd,He;return((Xb=((He=Za==null?void 0:_.rl(Za,_.xN,8))!=null?He:[]).find(Zh=>_.Gl(Zh,1)===fw()))==null?void 0:Xb.Ek())||(Za==null?void 0:Za.Ek())||
((rd=nb)==null?void 0:rd.ghostTextPlaceholder)||jb.Ek()}},void 0,"yO8XCf"));_.Zs(()=>{_.Ix||Py||!_.Ys(ya)||(Py=!0,vj({vl:!1}))},"GSWZN");_.Zs(()=>{nq()!==1&&Km(!1)},"yXnxGc");const DV=()=>{vj();uj()&&_.Ix&&(oh(!1),oh(!0));If().Kb(1,!jw());vk(!1)},wPa=this.ta("QxtLBe",Za=>{DV(Za.target)}),xPa=this.ta("HQg1Gb",Za=>{DV(Za)}),yPa=this.ta("eNTyEf",Za=>{DV(Za.target)}),lta=this.ta("RVnrsf",Za=>{FV(Za)}),EV=this.ta("mUX5ab",Za=>{FV(Za.target)}),FV=()=>{const Za=!Pr();If().Kb(2,Za);vj();vk(!1)},mta=this.fa("G75ZK",
()=>{const Za=!Wt();If().Kb(5,Za);vj();vk(!1)}),zPa=this.ta("bYoX0d",()=>{mta()}),APa=this.ta("JJr5hb",()=>{mta()});this.ta("JHq4Yd",_.FCb?()=>{f()}:()=>_.n(function*(){return g()}));this.ta("TuDNec",()=>_.n(function*(){_.wH&&Y()}));const nta=this.ta("jJaprb",()=>{B();let Za;((Za=nb)==null?0:Za.closeCallback)&&nb.closeCallback()}),ota=this.ta("F0IZne",()=>{u(Cb.value.value,{})}),{layout:BPa}=this.KB(_.BRb),vj=({vl:Za=!0,Yv:Xb=!0}={})=>{Za&&W();document.activeElement!==Cb.value&&(Za=_.Ys(BPa)==="i",
Cb.value.focus({preventScroll:_.Ix||Za}));Xb&&fa()};this.ta("Krz57b",vj);this.ja("uBTO9d",function(Za){kw&&(Za.touches.length===1?wl=Za.touches[0].clientY:wl=void 0,Ry=!1)});this.ja("XC9X0",function(Za){kw&&!Ry&&wl!==void 0&&Za.touches.length===1&&Math.abs(Za.touches[0].clientY-wl)>10&&(Ry=!0)});this.ja("mEOlad",function(Za){if(_.Ix)if(kw&&Ry)wl=void 0,Ry=!1;else{var Xb,rd,He;((Xb=Ad.value)==null?0:Xb.contains(Za.target))||((rd=sd.value)==null?0:rd.contains(Za.target))||((He=we.value)==null?0:He.contains(Za.target))||
(document.activeElement!==Cb.value&&(vj({vl:!0,Yv:!1}),Za.preventDefault()),fa())}});this.ja("cJXDcd",function(Za){if(!_.Ix)switch(BV=!1,Za.key){case "Enter":Za.shiftKey||Za.isComposing||Za.keyCode===229||(Za.preventDefault(),(Za=Mb.value.querySelector('[data-xid="input-plate-send-button"]'))&&U(Za,!0),u(Cb.value.value,{}));break;case "Escape":kb?nta():T(!1,!0);U(Gc.value,!0);break;case "Tab":_.LA&&hw!==""&&(gw().j.j(Object.assign({},_.DWb(hw.length-Cb.value.value.length),{yC:Cb.value.value.length})),
Za.preventDefault(),Cb.value.value=hw,ra());break;case "Backspace":_.LA&&(BV=!0);break;case "ArrowUp":_.ICb&&Cb.value.value===""&&az!==""&&(Za.preventDefault(),Cb.value.value=az,bJ.ra().j($e.value,24).log(!0),HV(Za))}});_.DCb?_.Zs(()=>{ha(ka())},"KgYS2"):_.Zs(()=>{WI()||fa()},"Q43Lfd");this.ja("QaOr6c",function(){vj();U(yc.value)});this.ja("V64iSc",function(Za){if(jg()!==5){var Xb,rd=(Xb=Za.clipboardData)==null?void 0:Xb.files;rd&&rd.length!==0&&(Za.preventDefault(),d(rd))}});const sj=this.ta("wr1vfd",
()=>{Ut(!1)}),GV=this.ta("ayfowb",Za=>{d(Za);vk(!1)});this.ta("z0zvc",()=>{vk(!1)});const pta=this.ta("xdiJoc",Za=>{Za.stopPropagation();Gn()||vk(!0)}),HV=()=>{V()||(W(),U(yc.value,!0));fa();k();_.xH&&gw().j.j(_.CWb());sa();na()};this.ja("xlz35d",HV);this.ja("RdaUDc",function(){V()||(W(),U(yc.value,!0));fa();k();sa()});const lw=_.Kj(_.Ps(De,_.OL));_.Zs(()=>{let Za;var Xb=lw(),rd=((Za=Ka.aa())==null?void 0:Za.j())||[];Xb.aa=rd;jg()!==0&&na()},"IvHewc");const CPa=()=>{if(window.visualViewport)if(window.visualViewport.scale!==
1)zb.value.style.removeProperty("transform");else{var Za=window.innerHeight-window.visualViewport.height;Za>0?zb.value.style.transform=`translateY(-${Za}px)`:zb.value.style.removeProperty("transform")}};this.fa("X6ewwf",_.O(()=>_.Z(!Or()||_.wH&&mh()?"Z3UdVc":""),void 0,"acL0jf"));this.fa("hZY9xb",_.O(()=>_.Z("sisB6e","Mmkrwb",Or()&&_.wH&&mh()?"":"Z3UdVc"),void 0,"CNT3d"));const qta=this.fa("tNnuqe",_.O(()=>_.Z(Gn()?"Mmkrwb":"",_.wH&&mh()?"Z3UdVc":"",_.zH&&!XI()?"hhGtFb":""),void 0,"Ret02e")),rta=
this.fa("FDY4Kc",_.O(()=>dm()||Sg(),void 0,"wDX6Ic")),sta=this.fa("t4b0wc",_.O(()=>dm()||Sg(),void 0,"iNNoX")),IV=this.fa("qgRUnc",_.O(()=>{let Za;return!((Za=ua())==null||!Za.enableZeroPrefixSuggestions)&&(!dm()||Hm()&&$y()&&!Uk())},void 0,"vM4dIc")),DPa=this.fa("By8DWe",_.O(()=>{let Za;return!((Za=ua())==null||!Za.enableTypedSuggestions)&&Uk()&&!WI()&&!XI()},void 0,"ngsowb"));this.ja("uXavTc",function(Za){Za.request.aa()&&l(Za.request.Fd());V()||vj()});this.ja("h130ie",function(){Mb.value.style.display=
"none"});this.ja("zkTe5d",function(){Mb.value.removeAttribute("style")});this.ja("PCPhYc",function(Za){_.QXb(If(),Za.request)});this.ja("Enjd1b",function(){If().da.value=!0});this.ja("caE5rf",function(){If().da.value=!1});this.ja("uL02nb",function(Za){Za.stopPropagation();Za.preventDefault()});let eJ=1,dJ="";this.ja("n3ytI",function(Za){if(nq()!==4&&jg()!==5){var Xb=()=>{l(dJ);tj(eJ)};if(Za.j.ba()||Za.j.da())jg()!==4&&(Re(!1),eJ=jg(),dJ=Cb.value.value,l(""),tj(4));else if(Za.j.ea()){if(Za.j.preventDefault(),
!Za.j.aa()||d(Za.j.j(),Xb))l(dJ),tj(eJ)}else tj(eJ)}});const [tta,EPa]=this.fa("C0W1sf",_.K(1,void 0,"Ia6xac")),St=EPa,FPa=this.fa("XwhR3b",_.O(()=>_.Z(nq()===1?"iUTYAe":"",nq()===2?"usImhc":"",nq()===4?"IbS5tc":""),void 0,"ANw3Tb")),GPa=this.fa("C2kEgb",_.O(()=>_.Z(jg()===1?"M9CbTd":"",jg()===2?"UAbVe":"",jg()===3?"Bd8gxb":"",jg()===4?"rIcffd":"",jg()===5?"bGkj2b UAbVe":""),void 0,"gvnQvd")),HPa=this.fa("mCAg4",_.O(()=>fe()?_.Ys(Oa)?_.Z([_.Ys(xa)&&"H8A2Mc","f8NOwb"]):_.Z(_.Ix&&"H8A2Mc","awLKaf"):
"",void 0,"LF0emf"));_.Zs(()=>{fe()&&setTimeout(()=>{Re(!1)},1E3)},"U2Qnwc");this.fa("tyLYue",_.O(()=>{let Za,Xb,rd;return _.Z(GPa(),fd()&&"AdSAi",nc()?FPa():"iUTYAe",xl()&&"rn9GPe",HPa(),_.Ys(Oa)?"YBkage":"",lc?"sk67dc":"",((Za=nb)==null?void 0:(Xb=Za.suggestConfig)==null?void 0:(rd=Xb.zeroStateConfig)==null?void 0:rd.enableZeroPrefixSuggestions)&&_.Ys(xa)&&_.Ix&&_.AH&&"pTDPyc",_.sH&&Md()&&"sPJmO",_.sH&&ji()&&"BeJZl")},void 0,"vubJxf"));this.fa("p7ZpOd",_.O(()=>_.Z("Txyg0d",VC()?"SJXlhf":""),void 0,
"bwnnOe"));this.fa("JXhswb",_.O(()=>_.Z(!_.Ys(Oa)||kb||jg()!==2||dm()||_.wH&&mh()?"EfpX5":"Z3UdVc",_.Ys(Oa)?"":"EfpX5",uj()?"Z3UdVc":"",jg()===4||jg()===5||_.wH&&_.PCb&&mh()?"Z3UdVc":""),void 0,"JblUOd"));this.fa("ymEH9b",_.O(()=>_.Z("lUxx6",(uj()||Nr())&&"NKu3uf"),void 0,"OVG4Db"));const IPa=this.fa("O1WQv",_.O(()=>_.Z("qOAOh",!uj()&&"Z3UdVc"),void 0,"Ordwce"));this.fa("Hd6hYe",_.O(()=>_.Z(jg()===4||jg()===5?"pvW4Ge":"CEpIFc"),void 0,"nSnB4d"));const uta=this.fa("b845Ab",_.O(()=>_.Z(!lc||jg()!==
2||dm()||_.wH&&mh()?"OEueve":"Z3UdVc",ita()?"IbS5tc":""),void 0,"WIQaCe")),JV=Za=>{if(Za.kind==="remove")return _.FM(Bi,Za.id);if(Za.kind==="appendToQueryText"){var Xb=Cb.value.value;l(Xb?`${Xb}${Za.separator}${Za.text}`:Za.text);return Cb.value.value}if(Za.kind==="removeFromQueryText"){Xb=Cb.value.value;if(!Xb)return"";Xb=Xb.split(Za.separator).filter(rd=>rd!==Za.text).join(Za.separator);l(Xb);return Xb}_.Bl(Za.request,2)&&W(_.Bl(Za.request,5));_.Tl(Za.request,1)&&l(Za.request.Fd());Xb=_.Lk(Za.request,
_.uv,3)?_.RXb(Bi,Za):"";_.Ix&&!_.oCb||vj({Yv:!_.DCb});_.Bl(Za.request,4)&&cJ(()=>{u(Cb.value.value,{})});return Xb};_.Uwb&&_.Zs(()=>{if(_.Ys(ya)){const Za=_.SXb(dg,JV);this.Ta(function(){Za()})}},"zIz0xe");this.onInit(function(){Dd(!0);Cb.value.addEventListener("selectionchange",fa);yc.value.addEventListener("scroll",da);ta();window.addEventListener("resize",ta);Yh.push(()=>{window.removeEventListener("resize",ta)});_.PF||Vt(!!window.webkitSpeechRecognition);if(_.Ix){let Za,Xb;TC=!((Za=document.querySelector('meta[name="viewport"]'))==
null?0:(Xb=Za.getAttribute("content"))==null?0:Xb.includes("interactive-widget=resizes-content"));let rd;(rd=window.visualViewport)==null||rd.addEventListener("resize",CPa);_.tH&&(new URLSearchParams(window.location.search)).get("avm")==="1"&&g()}else Aa?vj({vl:!1}):(new URLSearchParams(window.location.search)).get("akm")==="1"&&_.BH?vj({vl:!0}):_.tH&&(new URLSearchParams(window.location.search)).get("avm")==="1"&&g();Ac(!0);Yh.push(Bi.Jg.bind(VI));Yh.push(Bi.da.bind(aPa));Yh.push(Bi.ka.bind(Jsa));
Yh.push(Bi.ea.bind(cPa));Yh.push(If().j.bind(iPa));Yh.push(If().Ea.bind(ZI));Yh.push(If().sf.bind(rPa));Yh.push(If().za.bind(eta));Yh.push(If().Da.bind(jPa));Yh.push(If().Ia.bind(Sr));Yh.push(If().Fa.bind(jq));Yh.push(If().La.bind(vPa));Yh.push(If().ba.bind(QI));Yh.push(Bi.aa.bind(hPa));if(!_.Uwb){const Za=_.SXb(dg,JV);_.vr(()=>{Za()})}Qy.then(Za=>{const Xb=new URL(window.location.href);Xb.searchParams.delete("aipt");Za.pushAsync(Xb.toString(),void 0,()=>{},!0)})});this.Ta(function(){for(;Yh.length>
0;)Yh.pop()();_.EL(Bi);oh(!1);_.Ix&&(document.body.style.removeProperty("overflow"),_.rc()&&_.WF&&document.body.removeEventListener("touchmove",F))});const Rsa=this.fa("hfxzke",()=>{const Za=new Set;if(_.MF)return Za;Gb&&!uV()&&Za.add("application/pdf");if(Df)for(const Xb of _.xL)Za.add(Xb);return Za}),ZOa=this.ta("oBDzpc",(Za,Xb)=>{t(Za,Xb)}),JPa=_.O(()=>_.Z("OXxICc","N4Fgg"),void 0,"lfoUvf"),KPa=this.ta("Dn9bvb",()=>{If().Kb(4,!Hm());vj();vk(!1)}),LPa=this.ta("tW9Ceb",()=>{If().Kb(4,!1);vj()}),
MPa=this.ta("dUZ0md",()=>{If().me(1);vj();vk(!1)}),NPa=this.ta("kNFfef",()=>{If().me(3);vj();vk(!1)}),OPa=this.ta("ps5lxe",()=>{If().me(4);vj();vk(!1)}),PPa=this.ta("hOozGc",()=>{If().me(2);vj();vk(!1)});this.fa("TFxjId",_.O(()=>_.Z("rJkohe",!_.Ix&&Ur&&_.Ys(xa)&&"es8f0"),void 0,"iohX2d"));const bD=({pa:Za})=>_.S(_.fN,{onClick:nta,pa:Za,icon:_.zH&&_.Ix?_.S(_.EM,{size:24}):_.S(_.BJ,null),ariaLabel:"\u0417\u0430\u043a\u0440\u044b\u0442\u044c",Qc:Sg,Lk:"xuAr6b"}),KV=this.fa("jixXVc",_.O(()=>uj()?"\u041d\u0430\u0447\u0430\u0442\u044c":
"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c",void 0,"l6fzzf")),vta=({pa:Za})=>{let Xb;return _.S(_.fN,{onClick:ota,icon:((Xb=nb)==null?0:Xb.useSearchSparkIcon)?_.S(_.spb,null):_.S(_.YWb,null),pa:Za,ariaLabel:KV,Oa:ita,className:uta,Lk:"Iq9dx",label:"\u041d\u0430\u0447\u0430\u0442\u044c",Ko:IPa,Qc:Sg,hh:"input-plate-send-button",yO:!0})},fJ=({ug:Za})=>{const Xb=this.fa("ggNWmb",_.O(()=>Sg()||!_.HF,void 0,"TROaPb"));return _.S(_.fN,{onClick:pta,pa:_.s2a,icon:_.S(_.aXb,{ha:_.v((new _.ox).setSize(5))}),
ug:Za,ariaLabel:_.HF?Ur?"\u0414\u043e\u0431\u0430\u0432\u044c\u0442\u0435 \u0444\u0430\u0439\u043b\u044b, \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b \u0438 \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043c\u043e\u0434\u0435\u043b\u044c":"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0444\u0430\u0439\u043b\u044b \u0438 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b":"\u0414\u0440\u0443\u0433\u0438\u0435 \u0441\u043f\u043e\u0441\u043e\u0431\u044b \u0432\u0432\u043e\u0434\u0430",
className:qta,Qc:Xb,Oa:Gn})},wta=this.fa("mCevaf",()=>{let Za,Xb,rd,He,Zh,cg,xh,Hn,bz,gJ,cD,Bta,Cta,Dta;return(_.Ys(xa)?((Za=nb)==null?void 0:(Xb=Za.suggestConfig)==null?void 0:(rd=Xb.zeroStateConfig)==null?void 0:rd.enableZeroPrefixSuggestions)||((He=nb)==null?void 0:(Zh=He.suggestConfig)==null?void 0:(cg=Zh.zeroStateConfig)==null?void 0:cg.enableTypedSuggestions):((xh=nb)==null?void 0:(Hn=xh.suggestConfig)==null?void 0:(bz=Hn.followupConfig)==null?void 0:bz.enableZeroPrefixSuggestions)||((gJ=nb)==
null?void 0:(cD=gJ.suggestConfig)==null?void 0:(Bta=cD.followupConfig)==null?void 0:Bta.enableTypedSuggestions))&&!((Cta=nb)==null?0:(Dta=Cta.suggestConfig)==null?0:Dta.showSuggestionsBelowInputPlate)&&jg()===2});this.fa("OCa4gb",()=>mh()&&_.wH);const SI=this.fa("MMNOWd",()=>!_.wH||!mh()),xta=this.fa("jPT3hf",()=>_.wH&&mh()),QPa=this.fa("NRhlj",()=>sPa()&&!gta()),RPa=this.fa("eQXGBd",()=>nPa()),SPa=this.fa("L89bMc",()=>tPa()&&!gta()),TPa=this.fa("IB0Eg",()=>oPa()),yta=this.fa("EJDhYe",()=>!mh()||
!_.wH),zta=this.fa("hE9xac",()=>_.wH&&mh());_.pt(this,"HugV6",Rr,()=>_.S(_.zx,{na:Rr,then:()=>_.S(_.IWb,{isOpen:uk,be:sj})}));_.pt(this,"WyzG9e",wta,()=>_.S(_.zx,{na:wta,then:()=>{let Za,Xb;return _.S("div",{el:$d,class:JPa},_.S(_.jN,{ha:Fb,Em:ZOa,Tf:jb,bk:((Za=nb)==null?0:(Xb=Za.suggestConfig)==null?0:Xb.mWebClassicSearchboxVariant)?3:2,config:{shouldFetchRecommendations:Aa,disableAnimation:!Aa,disableSuggestVeLogging:!0,shouldHandlePrefetchOnly:!0},pa:_.x2a}))}}));_.pt(this,"lC1IR",OI,()=>_.S(_.zx,
{na:OI,then:()=>_.S(_.JWb,{copy:qV,xQ:Ksa,CQ:ePa,configuration:XOa})}));_.pt(this,"Y6wv1e",SI,()=>_.S(_.zx,{na:SI,then:()=>_.S(_.XWb,{inputs:Qr,WR:Psa,VS:"FGQVEf",lz:_.Sfb})}));_.pt(this,"mkNeje",xta,()=>_.S(_.zx,{na:xta,then:()=>bD({pa:_.o4a}),else:()=>bD({pa:_.m2a})}));_.pt(this,"nkGDxf",Gn,()=>_.S(_.zx,{na:Gn,then:()=>_.S(_.cs,null,_.KC({na:Ld&&Ze,container:({children:Za})=>_.S("div",{class:"RjVCgb"},Za),children:_.S(_.cs,null,_.Ct(Df,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.eN,{Uj:GV,
ui:Ld,Oa:vV,pa:_.X1a,icon:_.S(_.hN,{Wd:(Za=La(1))==null?void 0:(Xb=_.Bk(Za,_.yN,4))==null?void 0:_.zN(Xb),Od:93,size:Ld?32:24}),className:"z0vyjc",Ll:ce,ls:xd,ariaLabel:xd,Qc:!0,Sz:_.NF}))}),_.Ct(Ld&&Df,()=>_.S("div",{class:"q3INob"},_.S(_.eN,{pa:_.x0a,Uj:GV,ui:Ld,Oa:vV,className:"z0vyjc",Ll:"image/jpeg,image/png,image/webp,image/avif",icon:_.S(_.bXb,{ha:_.v(_.lx(new _.ox,32))}),JB:!0,ls:"\u041a\u0430\u043c\u0435\u0440\u0430",ariaLabel:"\u041a\u0430\u043c\u0435\u0440\u0430",Qc:!0}))),_.Ct(Gb,()=>
{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.eN,{pa:_.B1a,ui:Ld,Uj:GV,Oa:uV,icon:_.S(_.hN,{Wd:(Za=La(2))==null?void 0:(Xb=_.Bk(Za,_.yN,4))==null?void 0:_.zN(Xb),Od:92,size:Ld?32:24}),className:"z0vyjc",Ll:_.MF?"":pf,ls:Zc,ariaLabel:Zc,Qc:!0,Sz:_.NF}))}))}),_.Ct(Ze&&Xc,()=>_.S("hr",{class:"DAbcae"})),_.Ct(Xc&&_.pwb,()=>_.S("div",{class:"z6SWBe"},_.nl(jb,_.AN,7).getHeader())),_.Ct(Ib,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:KPa,ariaLabel:ve,pa:_.q2a,className:"z0vyjc",
label:ve,icon:_.S(_.hN,{Wd:(Za=Na(4))==null?void 0:(Xb=_.BN(Za))==null?void 0:_.zN(Xb),Od:100}),isSelected:Hm,Oa:$I,Te:!_.RF}))}),_.Ct(gd,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:yPa,ariaLabel:ac,pa:_.Tx,className:"z0vyjc",label:ac,icon:_.S(_.hN,{Wd:(Za=Na(1))==null?void 0:(Xb=_.BN(Za))==null?void 0:_.zN(Xb),Od:94}),isSelected:jw,Oa:Xt,Te:!_.RF}))}),_.Ct(Hg,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{pa:_.K3a,onClick:APa,ariaLabel:Sb,className:"z0vyjc",label:Sb,
icon:_.S(_.hN,{Wd:(Za=Na(5))==null?void 0:(Xb=_.BN(Za))==null?void 0:_.zN(Xb),Od:95}),isSelected:Wt,Oa:wV,Te:!_.RF}))}),_.Ct(Ee,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:EV,ariaLabel:gb,pa:_.p2a,className:"z0vyjc",label:gb,icon:_.S(_.hN,{Wd:(Za=Na(2))==null?void 0:(Xb=_.BN(Za))==null?void 0:_.zN(Xb),Od:96}),isSelected:Pr,Oa:fta,Te:!_.RF}))}),_.Ct((Ze||Xc)&&Ur,()=>_.S("hr",{class:"DAbcae"})),_.Ct(Ur,()=>_.S("div",{class:"z6SWBe"},_.nl(jb,_.AN,8).getHeader())),_.Ct(Ur&&kPa,
()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:MPa,pa:_.v2a,label:yd,ariaLabel:yd,className:"z0vyjc",icon:_.S(_.hN,{Wd:(Za=db(1))==null?void 0:(Xb=_.CN(Za))==null?void 0:_.zN(Xb),Od:91}),isSelected:QPa,Oa:RPa,Te:!1}))}),_.Ct(Ur&&lPa,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:NPa,pa:_.o2a,label:Ed,ariaLabel:Ed,className:"z0vyjc",icon:_.S(_.hN,{Wd:(Za=db(3))==null?void 0:(Xb=_.CN(Za))==null?void 0:_.zN(Xb),Od:90}),isSelected:SPa,Oa:TPa,Te:!1}))}),_.Ct(Ur&&
mPa,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:PPa,pa:_.t2a,label:ef,ariaLabel:ef,className:"z0vyjc",icon:_.S(_.hN,{Wd:(Za=db(2))==null?void 0:(Xb=_.CN(Za))==null?void 0:_.zN(Xb),Od:hta&&!_.ZCb?89:97}),isSelected:Osa,Oa:RC,Te:!1}))}),_.Ct(Ur&&hta,()=>{let Za,Xb;return _.S("div",{class:"q3INob"},_.S(_.iN,{onClick:OPa,pa:_.u2a,label:Nc,ariaLabel:Nc,className:"z0vyjc",icon:_.S(_.hN,{Wd:(Za=db(4))==null?void 0:(Xb=_.CN(Za))==null?void 0:_.zN(Xb),Od:97}),isSelected:uPa,Oa:pPa,Te:!1}))}))}));
_.pt(this,"EZFthd",null,()=>_.S(_.CM,null,_.S(_.AM,{when:()=>tta()===5},()=>fJ({ug:5})),_.S(_.AM,{when:()=>tta()===6},()=>fJ({ug:6})),_.S(_.BM,null,()=>fJ({ug:1}))),!0);_.pt(this,"AhKDyd",lh,()=>_.S(_.zx,{na:lh,then:()=>_.S(_.FWb,null)}));_.pt(this,"PAH57d",jw,()=>_.S(_.zx,{na:jw,then:()=>_.Ct(_.zH,()=>_.S(_.gN,{onClick:wPa,ariaLabel:"Deep Search",pa:_.Tx,label:"Deep Search",isSelected:!0,icon:_.S(_.DM,{size:24}),Oa:Xt,Qc:rta,an:Tr}),()=>_.S(_.EWb,{isSelected:jw,Oa:Xt,xc:!1,tm:rta,Jw:xPa}))}));_.pt(this,
"txdxjf",Wt,()=>_.S(_.zx,{na:Wt,then:()=>_.S(_.gN,{onClick:zPa,ariaLabel:Sb,pa:_.K3a,label:Sb,isSelected:!0,icon:_.S(_.MWb,{size:24}),Oa:wV,Qc:Sg})}));_.pt(this,"mz5kCb",Hm,()=>_.S(_.zx,{na:Hm,then:()=>{let Za,Xb,rd;return _.S(_.gN,{onClick:LPa,ariaLabel:ve,pa:_.r2a,label:((Za=Na(4))==null?void 0:_.y(Za,4))||"",isSelected:!0,icon:_.S(_.hN,{Wd:(Xb=Na(4))==null?void 0:(rd=_.BN(Xb))==null?void 0:_.zN(rd),Od:_.WCb?98:100}),Oa:!1,Qc:Sg,an:"\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0438\u043b\u0438 \u0438\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f"})}}));
_.pt(this,"NLm8k",Pr,()=>_.S(_.zx,{na:Pr,then:()=>_.Ct(_.zH,()=>_.S(_.gN,{onClick:EV,ariaLabel:gb,pa:_.O0a,label:gb,isSelected:!0,icon:_.S(_.lL,{size:24}),Oa:Yt,Qc:sta,an:Nsa}),()=>_.S(_.AWb,{isSelected:Pr,Oa:Yt,xc:!1,tm:sta,Jw:lta}))}));_.pt(this,"aCYHB",yta,()=>_.S(_.zx,{na:yta,then:()=>_.S(_.eN,{pa:_.z2a,Uj:Xj,icon:_.S(_.LWb,null),Ll:"image/jpeg,image/png,image/webp,image/avif",JB:!0,ariaLabel:"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435",
className:_.Z("PlA8td"),Qc:AV,lS:Ka.ba()})}));_.pt(this,"nLCYAe",zta,()=>_.S(_.zx,{na:zta,then:()=>vta({pa:_.r4a}),else:()=>vta({pa:_.C1a})}));this.la();this.ea()}j(){return super.j()}ba(){return R4b}da(){throw Error("Ie");}};iP.prototype.$wa$TKxcbd=function(){return this.da};iP.prototype.$wa$p2ggSe=function(){return this.ba};iP.prototype.$wa$QyQmSc=function(){return this.j};iP.prototype.$wa$kXCA5e=function(){return this.aa};_.P(_.m("P5gZDb",[_.X]),iP);



_.q();
});
// Google Inc.
