loaded_h_0(function(_){var window=this;
_.eM=function(a){const b=document.createElement("div"),c=_.SWe(),{oMa:d,gF:e}=_.OSc();c.Pa=d;_.Oc(b,a(c));if(!b.firstElementChild)throw Error("Hi");return{node:b.firstElementChild,gF:e}};_.TWe=class{constructor(a,b){this.oa=a;this.eya=b}dispatch(){var a=this.oa,b=this.eya;const c=_.Yg();c.Lc("sqi","21").Lc("ei",a);b&&c.Lc("pepp",b);c.log()}};
_.VD=function(a){return _.t(a,4)};_.Bbd=function(a){return _.t(a,34)};_.WD=function(a){return _.t(a,37)};_.XD=!!(_.Ei[25]>>15&1);
_.v("Sp69O");
var eRA,fRA,gRA,iRA,hRA,kRA,jRA,nRA,oRA,uRA,vRA,wRA,GRA,ERA,HRA,IRA,LRA,MRA,KRA,NRA,JRA,PRA,ORA,QRA,ARA,FRA,RRA,SRA,TRA,xRA,URA,zRA,VRA,WRA,DRA,dRA,XRA,lRA,YRA;eRA=function(a){if(dRA)return dRA;const b=_.Ge(_.wm("iGkMSe"));return dRA=_.x$h(a,251333,b)};
fRA=function(a,b){var c={duration:250,easing:"cubic-bezier(.75,1,.75,1)"};const d=b.width/a.width,e=b.left-a.left*d;a=b.top-a.top*d;return{D2d:{keyframes:[{opacity:1,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:0,transform:`translate(${e}px, ${a}px) scale(${d})`,transformOrigin:"top left",mixBlendMode:"normal"}],options:c},y1d:{keyframes:[{opacity:0,transform:`translate(${-e/d}px, ${-a/d}px) scale(${1/d})`,transformOrigin:"top left",mixBlendMode:"normal"},{opacity:1},{opacity:1,
transformOrigin:"top left",mixBlendMode:"normal"}],options:c}}};
gRA=function({element:a,Uda:b,F4a:c,aSa:d=2,containment:e=!0,z3c:f,Ccf:g,lWc:h,X$e:k,O7e:l=.5,backgroundColor:p,n$b:q=!1,options:r={}}){let u;r.duration=(u=r.duration)!=null?u:250;let A;r.easing=(A=r.easing)!=null?A:_.xQb;let E;r.fill=(E=r.fill)!=null?E:"both";const I=r.duration,N=r.easing;b={element:a,Uda:b,F4a:c,group:{},eAb:{},S8:{},new:{}};e&&(b.group.styles={overflow:"hidden",borderRadius:"20px",backgroundColor:p||window.getComputedStyle(document.body).backgroundColor});const P=a.getBoundingClientRect(),
T=g!=null?g:f==null?void 0:f.getBoundingClientRect();b.ready=Z=>{if(Z.Uda){var ca;Z.group=(ca=Z.group)!=null?ca:{};if(ca=_.szh(Z.viewTransitionName,q)){var ka=ca.h7c,da=ca.k7c,ma=ca.l7c,ta=ca.f7c,Ea=ca.f6c,Ga=ca.i6c,eb=ca.j6c,Va=ca.Mma,qb=ca.VM,sb=ca.yP;ca=Z.Uda.getBoundingClientRect();var Lb,Gb=k?k():(Lb=h?h():f)==null?void 0:Lb.getBoundingClientRect();Lb=sb*ta/Va;ma=d===4?1:d===5?Lb:qb*ma/eb;eb=d===3||d===2?Lb:ma;Z.group.animation={keyframes:[{transform:`translate(${ka}px, ${da}px) scale(${ma}, ${eb})`,
transformOrigin:"top left"},{transform:`translate(${Ea}px, ${Ga}px) scale(1, 1)`,transformOrigin:"top left"}],options:r};d===2&&(Z.eAb!=null||(Z.eAb={}),ka=_.zzh({name:Z.viewTransitionName,easing:N,duration:I,i7c:ma,j7c:eb}),Z.eAb.animation=ka[0],Z.eAb.dNb=ka.slice(1));T&&Gb&&Z.S8&&Z.new&&(ka=Gb.left-ca.left-(T.left-P.left),ca=Gb.top-ca.top-(T.top-P.top),Gb={keyframes:[{offset:0,opacity:"0",transform:`translate(${-ka}px, ${-ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-
.1,opacity:"0"},{offset:l+.1,opacity:"1"},{offset:1,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.S8.animation={keyframes:[{offset:0,opacity:"1",transform:"translate(0px, 0px)",transformOrigin:"top left",mixBlendMode:"plus-lighter"},{offset:l-.1,opacity:"1"},{offset:l+.1,opacity:"0"},{offset:1,opacity:"0",transform:`translate(${ka}px, ${ca}px)`,transformOrigin:"top left",mixBlendMode:"plus-lighter"}],options:r},Z.new.animation=Gb);
return Z}}};return b};iRA=function(a,b){b=hRA(a,b);return b!=null&&b!==0?b:hRA(a,_.Jjf)};hRA=function(a,b){switch(a){case 0:case 1:return b==null?void 0:_.zj(b,2);case 2:return b==null?void 0:_.zj(b,3);case 3:return b==null?void 0:_.zj(b,4);case 4:return b==null?void 0:_.zj(b,5);default:_.$a(a,void 0)}};kRA=async function(a,b,c){var d=(0,_.Pf)(),e=d();d=d(1);try{const f=b.map(jRA);d(await e(a.update(f,c)))}finally{e()}};
jRA=function(a){return{contentPluginType:a.contentPluginType,content:a.content,viewerType:a.viewerType,serializedModalityOverride:a.tW?lRA(a.tW):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,entrypointId:a.entrypointId,replacedEntrypointId:a.replacedEntrypointId,interactionVed:a.interactionVed,contentId:a.contentId,uuid:a.uuid}};
nRA=function(a){return{viewerType:a.viewerType,tW:a.serializedModalityOverride?(0,_.Lcf)(a.serializedModalityOverride):void 0,serializedModalityOverride:void 0,IX:a.serializedCloseConfig?(0,_.Fjf)(a.serializedCloseConfig):void 0,serializedCloseConfig:a.serializedCloseConfig,shellStyleClass:a.shellStyleClass,hq:null,plugin:null,vX:new AbortController,contentPluginType:a.contentPluginType,content:a.content,entrypointId:a.entrypointId,contentId:a.contentId,replacedEntrypointId:a.replacedEntrypointId,
j6a:0,vja:new mRA,interactionVed:a.interactionVed,Mf:0,JIa:0,oNa:new _.Hq,NEb:!1,Fqa:Promise.resolve(),xX:new _.Hq,entrypoint:null,Kw:null,header:null,Yk:[],nza:!1,uuid:a.uuid,nca:!1,KZa:void 0}};oRA=function(a,b,c){for(;c<a.length;c++)a[c].nza=b};
uRA=function({client:a,GEa:b,Ome:c,Qme:d}){const e=a.shellStyleClass,f=a.vja,g=a.plugin,{node:h,gF:k}=_.eM(l=>{var p;let q;var r=_.HEe&&(g==null?void 0:g.getType())===3,u=(q=(p=a.KZa)==null?void 0:p.Aa())!=null?q:null;pRA(l);p="";u==null&&new _.hM;p+="<div"+_.X(qRA(l,r,u)+"PG8i1e ")+_.Y(rRA(l,r,u)+"")+_.W(sRA(l,r,u)+' role="dialog"')+">";r=tRA(l,r,u);u=l.Da();u!==""&&(p+=" <style>"+u+"</style>");p+=r+_.wB(l)+"</div>";l.Ha();return _.z(p)});f.C0b({dispatch:k});h.setAttribute("data-svs","true");if(e)for(const l of e.split(" "))h.classList.add(l);
a.hq=h;if(c){const {node:l,gF:p}=_.eM(_.Y3e);f.YA({dispatch:()=>void p({Eg:_.cM(h)})});h.appendChild(l);a.header=l}if(d){const {node:l,gF:p}=_.eM(_.R5e);f.YA({dispatch:()=>void p({Eg:_.cM(h)})});h.appendChild(l);a.Kw=l}document.body.appendChild(h);a.fZ=b.apply(a);return h};vRA=function(){let a,b=(a=document.body.clientHeight)!=null?a:0;try{const c=window.getComputedStyle(document.body),d=_.REe(c.paddingTop),e=_.REe(c.paddingBottom);b-=d+e}catch(c){}return b};
wRA=function(a,b){b=b||a.clientHeight||0;if(a.style.display==="none"||b<=100)b=vRA();a.style.setProperty("--Z9tEad",b>100?`${b}px`:"100dvh")};
GRA=async function(a,b,c,d,e,f,g){var h=(0,_.Pf)(),k=h();h=h(1);try{const P=a.plugin,T=a.hq,Z=a.oNa,ca=a.NEb,ka=a.fZ;if(ka!==5){var l=T.clientHeight||0;if(ka===2&&l<=100){const da=e.get();l=Math.max(0,vRA()-da.oa()-da.Pa())}wRA(T,l);if(ca)h(await k(Z.promise));else{var p=a.viewerType===74;if(ka===2){var q=_.WRb(_.fSb(_.bSb(new _.Gv,127),1),1,{replace:[6,...(p?[]:[7]),10]});a.entrypoint&&a.entrypoint instanceof HTMLElement&&_.gSb(q,a.entrypoint)}else{const da=[2];_.qEe&&da.push(1);_.oEe&&da.push(3);
_.pEe&&da.push(4);q=xRA(_.ZRb(_.eSb(_.dSb(_.Ev(_.bSb(new _.Fv,1E3),ka===3?1:2))),a.contentPluginType!==5&&a.contentPluginType!==19&&a.viewerType!==47&&a.viewerType!==73),{getScrollTopRequirement:()=>1,getShouldDisableScrolling:()=>!0,getSwipeToDismissDirections:()=>da})}var r,u;_.VRb(_.Dv(_.Av(_.Bv(q,[2]),f),(u=P==null?void 0:(r=P.Tbe)==null?void 0:r.call(P))!=null?u:!0),5);var A=yRA?window.google.zl:void 0,E;ka===2?E=new zRA([{element:T,Ax:"PyLEff",oL:!0}],[{element:T,Ax:"PyLEff",oL:!1}],ARA(a,b)):
_.mEe&&_.Lzh?E=new BRA(T,ARA(a,b)):_.nEe&&_.Lzh?E=new CRA(T,ARA(a,b)):E=new DRA(T,ARA(a,b));_.Cv(q,E);!ERA(a)&&d.isAvailable()&&ka===1&&d.enterBasicMode(58);var I=c.open(T,q);Z.resolve(I);a.NEb=!0;h(await k(Z.promise));var N;A==null||(N=A.cqsv)==null||N.call(A);g();a.Mf>=5&&FRA(T)}}}finally{k()}};ERA=function(a){const b=yRA?window.google.zl:void 0;return!(a.j6a===2||a.j6a===4)||!(b==null||!b.qsvo)};HRA=function(a){const b=a.plugin;(a=a.hq)&&((b==null?0:b.P$c)?b.P$c():a.remove())};
IRA=async function(a,b,c){var d=(0,_.Pf)(),e=d();d=d(1);try{b.at(-1),a.Fqa||(a.Fqa=kRA(c,b,{replace:!1})),d(await e(a.Fqa))}finally{e()}};LRA=function(a,b){const c=a.entrypoint;a=a.contentId;const d=b.at(-1);return d?JRA(d,KRA(d,b))===c?d.contentId&&a&&d.contentId!==a?!1:!0:!1:!1};
MRA=function(a,b){for(let d=b.length-1;d>=0;d--){const {hq:e}=b[d];let f;var c;if(!(c=(f=e)==null?0:f.contains(a))&&(c=d===0&&b[d].viewerType===74&&e))a:{c=a.closest("[jsowner]");if(!c){c=!1;break a}c=(c=document.getElementById(c.getAttribute("jsowner")))?e.contains(c):!1}if(c)return d}return-1};KRA=function(a,b){a=b.indexOf(a);return a>0?b[a-1]:null};NRA=function(a,b){if(a==null||b==null)return a===b;if(a.length!==b.length)return!1;for(let c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};
JRA=function(a,b){if(a.entrypoint)return a.entrypoint;b=ORA(a.entrypointId,b);a.entrypoint=b;PRA(a);return b};PRA=function(a){let b;!a.entrypoint||(b=a.entrypoint)!=null&&b.querySelector("img, svg")||(a.nca=!0)};ORA=function(a,b){return a?(b=b?b.hq:document.body)?b.querySelector(`[id="${a}"]`):null:null};QRA=function(a,b){const c=a.entrypoint,d=a.replacedEntrypointId;return c&&c.isConnected?c:d?ORA(d,b):JRA(a,b)};
ARA=function(a,b){const c=b[0],d=KRA(a,b),e=!!d;return{lTb:function(){let f,g;const h=(f=a.plugin)==null?void 0:(g=f.G4a)==null?void 0:g.call(f,e);let k;return{Txa:(k=h==null?void 0:h.Txa)!=null?k:QRA(a,d),D5a:h==null?void 0:h.D5a,fba:(h==null?void 0:h.fba)||a.nza||ERA(a),IEa:h==null?void 0:h.IEa,Whc:a.nca}},rSb:function(){var f;let g;const h=(f=a.plugin)==null?void 0:(g=f.g4a)==null?void 0:g.call(f,e);f=h==null?void 0:h.Txa;f===void 0&&(f=b.length===0?QRA(c,null):QRA(a,d));return{Txa:f,D5a:h==null?
void 0:h.D5a,fba:(h==null?void 0:h.fba)||a.nza,IEa:h==null?void 0:h.IEa,Whc:a.nca}}}};FRA=function(a){(0,_.VMa)().then(()=>{const b=_.tma(a);_.qBe(b)})};RRA=function(){let a;((a=google)==null?0:a.uh)?google.uh("sv"):document.body.style.opacity=""};SRA=function(a){a.fsa!=null||(a.fsa=!1);a.nca!=null||(a.nca=!1);a.viewerType!=null||(a.viewerType=void 0);a.source!=null||(a.source=void 0)};
TRA=function(a,b){const c=a.plugin,d=a.hq;if(c){let e;c==null||(e=c.Icd)==null||e.call(c,a===b);let f;c==null||(f=c.setActive)==null||f.call(c,a===b)}d&&_.Xd(d,"hidden",a!==b)};xRA=function(a,b){a.Ha=b;return a};_.gna=class extends Error{};URA={duration:250,easing:_.xQb};
zRA=class extends _.wQb{constructor(a,b,c){super();this.Aa=a;this.oa=b;this.config=c}async open(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {fba:c}=this.config.lTb();_.RRb(this.Aa,c);c||a(await b(_.SRb(250)))}finally{b()}}async close(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {fba:c}=this.config.rSb();_.RRb(this.oa,c);c||a(await b(_.SRb(250)))}finally{b()}}};VRA=function(a){let b;(b=a.Aa)==null||b.remove();a.Aa=void 0};
WRA=function(a,b,c=!1){if(!b||c)return a.Aa?a=a.Aa:(a.Aa=document.createElement("div"),a.Aa.style.opacity="0.0000001",a.Aa.style.height="100px",a.Aa.style.width="100px",a.Aa.style.position="fixed",a.Aa.style.top="50%",a.Aa.style.left="50%",a.Aa.style.marginTop="-100px",a.Aa.style.marginLeft="-100px",a.Aa.style.pointerEvents="none",document.body.appendChild(a.Aa),a=a.Aa),a;VRA(a);return b};
DRA=class extends _.wQb{constructor(a,b){super();this.overlay=a;this.config=b}async open(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {Txa:c,fba:d,IEa:e,Whc:f}=this.config.lTb(),g=WRA(this,c,f);this.overlay.style.display="block";d||(this.overlay.style.opacity="0",a(await b(_.BRb({token:e!=null?e:_.AQb,before:g,after:this.overlay}).play())));this.overlay.style.opacity="1"}finally{b()}}async close(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {Txa:c,fba:d,IEa:e,Whc:f}=this.config.rSb(),g=WRA(this,c,f);d||
(g.style.opacity="0",a(await b(_.CRb({token:e!=null?e:URA,before:this.overlay,after:g}).play())));(()=>{this.overlay.style.display="none";g.style.opacity="";VRA(this)})()}finally{b()}}};lRA=_.Sb(_.Kcf);YRA=_.Sb(_.Ejf);var CRA=class extends DRA{constructor(a,b){super(a,b);this.overlay=a;this.config=b}async open(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {Txa:p,fba:q}=this.config.lTb(),r=()=>{this.overlay.style.display="block"};if(q)r();else{var c=WRA(this,p).getBoundingClientRect(),d={},e=_.US(r,{root:d});a(await b(e.updateCallbackDone));var f=document.body.getBoundingClientRect(),g,h=((g=this.overlay.querySelector('[jsname="figiqf"]'))==null?void 0:g.getBoundingClientRect())||f,{D2d:k,y1d:l}=fRA(c,Object.assign({},
h.toJSON(),{left:0}));d.S8={animation:k};d.new={animation:l}}}finally{b()}}async close(){var a=(0,_.Pf)(),b=a();a=a(1);try{const {Txa:e,fba:f}=this.config.rSb(),g=WRA(this,e),h=()=>{this.overlay.style.display="none";g.style.opacity=""};if(f)h();else{var c=window.getComputedStyle(document.body).backgroundColor,d=_.US(h,{groups:[{element:this.overlay,F4a:()=>g,group:{styles:{overflow:"hidden",backgroundColor:c,borderRadius:"16px"}},aSa:2,n$b:!0}]});a(await b(d.finished))}}finally{b()}}},$RA=async function(a){const {Txa:b,
D5a:c,fba:d}=a.config.rSb(),e=WRA(a,b);if(d)a.overlay.style.display="none",e.style.opacity="";else{var f={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",fill:"both"},g=(c||a.overlay).getBoundingClientRect(),h={new:{animation:{keyframes:[{offset:0,transform:"scale(1.2)",opacity:"0"},{offset:1,transform:"scale(1)",opacity:"1"}],options:f}}},k=gRA({element:c||a.overlay,Uda:e,z3c:c,lWc:()=>e,containment:!1,aSa:1,n$b:!0,options:f});return new Promise(l=>{a.Ba=_.US(()=>{a.overlay.style.display="none";
e.style.opacity=""},{xRd:!0,root:h,groups:[k],updateCallbackDone:p=>{const q=WRA(a,b).getBoundingClientRect(),r=q.width/g.width;p.root.S8={animation:{keyframes:[{transform:"translate(0px, 0px) scale(1)",transformOrigin:"top left"},{transform:`translate(${q.left-0*r}px, ${q.top-g.top*r}px) scale(${r})`,transformOrigin:"top left"}],options:Object.assign({},f,{id:"close-root-old"})},styles:{zIndex:"1"},dNb:[{keyframes:[{opacity:1},{opacity:0}],options:f}]};a.oa={EGc:a.Ba,VYc:k,GHa:[],VDb:[],iDa:{},Pj:{}};
l()},finished:()=>{ZRA(a);let p,q;(p=a.oa)==null||(q=p.Mb)==null||q.remove();a.oa=void 0}})})}},bSA=function(a){let b;(b=a.oa)==null||b.EGc.skipTransition();ZRA(a);let c,d;(c=a.oa)==null||(d=c.Mb)==null||d.remove();a.oa=void 0;aSA(a)},cSA=function(a,b){a.oa&&(b(a.oa.iDa),b(a.oa.Pj))},aSA=function(a){a.overlay.style.display="block"},ZRA=function(a){let b;(b=a.oa)==null||b.GHa.forEach(c=>{c.cancel()})},BRA=class extends DRA{constructor(a,b){super(a,b);this.overlay=a;this.config=b;this.swipeToDismiss=
{onStart:async()=>{var c=(0,_.Pf)(),d=c();c=c(1);try{if(c(await d($RA(this))),this.oa){c(await d(this.oa.EGc.ready));this.oa.GHa=_.Dzh();var e=`::view-transition-group(${this.oa.VYc.viewTransitionName})`;this.oa.iDa.animation=this.oa.GHa.find(g=>g.effect.pseudoElement===e);this.oa.Pj.animation=this.oa.GHa.find(g=>g.id==="close-root-old");if(!this.oa.iDa.animation)throw bSA(this),Error("AA");if(!this.oa.Pj.animation)throw bSA(this),Error("BA");this.oa.VDb=this.oa.GHa.filter(g=>g!==this.oa.iDa.animation&&
g!==this.oa.Pj.animation);for(const g of this.oa.GHa)g.pause();var f=document.createElement("style");this.oa.Mb=f;document.head.appendChild(f);this.oa.iDa.rule=_.Ezh(f,`html::view-transition-group(${this.oa.VYc.viewTransitionName})`,{});this.oa.Pj.rule=_.Ezh(f,"html::view-transition-old(root)",{});cSA(this,g=>{const h=new DOMMatrix(window.getComputedStyle(document.documentElement,g.animation.effect.pseudoElement).transform);g.yn=_.vzh(h)})}}finally{d()}},onMove:async c=>{if(this.oa&&this.oa.GHa.length){var d=
this.oa.GHa[0].effect.getTiming().duration;d=Math.min(Math.max(d*c.yWithTension/4E3,0),d/3);for(const e of this.oa.VDb)e.currentTime=d;cSA(this,({rule:e,yn:f})=>{e.style.setProperty("transform",`${`translate(${c.xWithTension+f.left}px, ${c.yWithTension+f.top}px)`} scale(${f.VM*c.scale}, ${f.yP*c.scale})`,"important")})}},onDismiss:()=>{if(this.oa){cSA(this,({animation:e,rule:f})=>{var g=e.effect;const h=g.getKeyframes();h[0].transform=f.style.transform;g.setKeyframes(h);g=e.effect.getTiming().duration;
const k=Math.max(this.oa.VDb[0].currentTime,100);e.cancel();document.documentElement.animate([{transform:f.style.transform},{transform:h[1].transform}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:g-k,pseudoElement:e.effect.pseudoElement})});var c,d;(c=this.oa)==null||(d=c.Mb)==null||d.remove();for(const e of this.oa.GHa)e.play()}},onCancel:()=>{if(this.oa){var c=Math.max(this.oa.VDb[0].currentTime,100),d;cSA(this,({animation:g,rule:h})=>{d=document.documentElement.animate([{transform:h.style.transform},
{transform:""}],{easing:"cubic-bezier(.27,1.06,.18,1)",duration:c,pseudoElement:g.effect.pseudoElement})});var e,f;(e=this.oa)==null||(f=e.Mb)==null||f.remove();for(const g of this.oa.VDb)g.currentTime=Math.max(g.currentTime,1),g.reverse();d.finished.then(()=>{bSA(this)})}}}}async open(){var a=(0,_.Pf)(),b=a();a=a(1);try{let c;a(await b((c=this.Ca)==null?void 0:c.finished))}finally{b()}}async beforeOpen(){const {Txa:a,D5a:b,fba:c}=this.config.lTb();if(c)aSA(this);else{var d={duration:500,easing:"cubic-bezier(.27,1.06,.18,1)",
fill:"both"},e=WRA(this,a),f=e.getBoundingClientRect(),g={S8:{animation:{keyframes:[{offset:0,transform:"scale(1)",opacity:"1"},{offset:1,transform:"scale(1.2)",opacity:"0"}],options:d}}},h=gRA({element:e,Uda:b||this.overlay,z3c:e,lWc:()=>b,containment:!1,aSa:1,options:d});return new Promise(k=>{this.Ca=_.US(()=>{k();aSA(this)},{root:g,groups:[h],updateCallbackDone:l=>{const p=(b||this.overlay).getBoundingClientRect(),q=f.width/p.width;l.root.new={animation:{keyframes:[{transform:`translate(${f.left-
0*q}px, ${f.top-p.top*q}px) scale(${q})`,transformOrigin:"top left"},{transformOrigin:"top left"}],options:d},dNb:[{keyframes:[{opacity:0},{opacity:1}],options:{delay:200,duration:300,fill:"both",easing:"cubic-bezier(.34,.69,.34,1)"}}]}}})})}}async close(){var a=(0,_.Pf)(),b=a();a=a(1);try{this.oa||a(await b($RA(this))),this.oa&&a(await b(this.oa.EGc.finished))}finally{b()}}};var sRA=function(a,b,c){b="";c==null&&new _.hM;return b+=' jsname="'+_.S("ujKaBc")+'" decode-data-ved="'+_.S("1")+'"'+_.vB(a,{Fb:233502,track:[4,3]}).attributes},qRA=function(a,b,c){c==null&&new _.hM;return""},rRA=function(a,b,c){c==null&&new _.hM;return""},dSA=function(a,b,c){c==null&&new _.hM;return!0},eSA=function(a,b,c){c==null&&new _.hM;return!1},fSA=function(a,b){pRA(a);return tRA(a,b.q_c,b.Gra)},gSA=function(a,b){pRA(a);var c=b.q_c,d=b.Gra;b="";d==null&&new _.hM;b+="<div"+_.X(qRA(a,c,d)+"PG8i1e ")+
_.Y(rRA(a,c,d)+"")+_.W(sRA(a,c,d)+' role="dialog"')+">";c=tRA(a,c,d);b+=c+_.wB(a)+"</div>";return _.z(b)},tRA=function(a,b,c){c=c==null?new _.hM:c;var d=_.$z(_.ki().Ua),e=_.$z(_.ki().jH),f=_.$z(_.ki().cj),g=_.$z(_.ki().Qp),h=_.$z(_.ki().Dc);a.Ba(".Ksi7Wb{background-color:"+_.V(d,"",k=>_.t(k,27))+"}");a.Ba(".PG8i1e{background:"+_.V(d,"",k=>k.Tc())+";overflow:hidden;position:fixed;transform:translateX(0)}");a.Ba(".PG8i1e.Ooz8t{"+((_.ZWd?"border:1px solid "+_.V(d,"",k=>k.Jr())+";border-radius:24px;box-shadow:none;opacity:0.001;transition:transform "+
_.V(g,"",k=>_.t(k,49))+" "+_.V(g,"",k=>_.t(k,56))+",opacity "+_.V(g,"",k=>_.t(k,49))+";":"")+(_.lWi&&!_.ZWd?"border:1px solid "+_.V(d,"",k=>k.Jr())+";border-radius:"+_.V(f,"",k=>_.IB(k))+";box-shadow:none;":"")+(_.lWi||_.ZWd?"":"border-radius:"+_.V(f,"",k=>_.IB(k))+";box-shadow:"+_.V(e,"",k=>_.t(k,8))+";opacity:0.001;transform:translateX(200px);transition:transform 250ms cubic-bezier(0.05,0.07,0.1,1),opacity 250ms")+"}"));a.Ba(".Ooz8t.F6z1Rc{box-shadow:"+_.V(e,"",k=>_.t(k,6))+"}");a.Ba(".PG8i1e.Ooz8t.PyLEff{opacity:0.999;"+
(_.lWi?"":"transform:translateX(0);")+"overflow-y:auto}");a.Ba(".MiFXAd{"+((_.XD?"background:"+_.V(d,"",k=>k.UV())+";":"")+(_.XD?"":"background:rgba(255,255,255,0.6);")+"display:flex;justify-content:center;align-items:center;backdrop-filter:blur(8px);position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(".QtrPTd{width:80%;height:calc(100% - 150px);top:75px;bottom:75px;left:10%}");a.Ba(".fLi1af{background:"+_.V(d,"",k=>k.Tc())+";border-radius:12px}");a.Ba(".Yktdff{"+((!_.XWd||_.XD?"background:#101218;color:"+
_.V(d,"",k=>_.gA(k))+";":"")+(_.XWd&&!_.XD?"background:"+_.V(d,"",k=>k.Tc())+";color:"+_.V(d,"",k=>_.Ko(k))+";":"")+"position:fixed;top:0;left:0;width:100%;height:100%}"));a.Ba(!_.XWd||_.XD?".Yktdff .VB2c0b{color:"+_.V(d,"",k=>k.Q_())+"}":"");a.Ba(".eQVlOe{padding-left:"+(_.V(h,"",k=>_.yA(k))+";padding-right:"+_.V(h,"",k=>_.yA(k))+"}"));a.Ba(_.cRA?".PG8i1e.Ooz8t.X3bDbe{border:1px solid "+_.V(d,"",k=>k.Jr())+";box-shadow:none;border-radius:24px;margin-top:20px;margin-bottom:20px}":"");d="";b&&_.Iai(a,
c)&&(b="<div"+_.X(_.Gai(a,c)+"HV5Yde ")+_.Y(_.Hai(a,c)+"")+_.W(_.Fai(a,c)+"")+">"+_.Lai(a,c)+"</div>",d+=_.Jai(a,c)?"":b);return d+=_.wB(a)},pRA=function(a){a.oa(hSA)||(a.Aa(hSA,{q_c:0,Gra:1},fSA,gSA,dSA,eSA,' role="dialog"',sRA,"PG8i1e ",qRA,"",rRA),_.Kai(a))},hSA="t-_7Z7QKitJBk";var jSA=function(a,b,c){const d=new mRA;iSA(d,a,b,c);return d},iSA=function(a,b,c,d){a.mode=0;a.vja.dispatch(b,c,d);a.vja=new kSA(b,c,d)},mRA=class{constructor(){this.mode=1;this.vja=new lSA}C0b(a){this.vja.C0b(a)}YA(a){this.vja.YA(a)}},kSA=class{constructor(a,b,c){this.interactionVed=a;this.Eg=b;this.eE=c}C0b(a){a.dispatch({interactionVed:this.interactionVed,Eg:this.Eg,qTa:!0,eE:this.eE})}YA(a){a.dispatch()}dispatch(){}},lSA=class{constructor(){this.oa=[]}C0b(a){this.Aa=a}YA(a){this.oa.push(a)}dispatch(a,
b,c){let d;(d=this.Aa)==null||d.dispatch({interactionVed:a,Eg:b,qTa:!0,eE:c});this.oa.forEach(e=>void e.dispatch())}};var yRA,mSA,qSA,pSA,sSA,xSA,uSA,ySA,ASA,DSA,BSA,CSA,oSA,zSA,rSA,FSA,wSA,nSA,vSA,ESA,GSA,tSA;yRA=_.kEe||_.lEe;mSA=function(a){return a.oa.at(-1)};
qSA=function(a,b,c){const d=KRA(b,a.oa),e=b.fZ;_.Mg(c,"KpPeYd",f=>{a.Bh(b,f.data)});_.Mg(c,"YS2dOd",f=>{nSA(a,b,2,f);oSA(a,b,2)});_.Mg(c,"gZgazf",f=>{nSA(a,b,1,f);oSA(a,b,1)});b.xX.promise.then(()=>{b.JIa=0;b.vX.abort();try{var f;let g;(f=b.plugin)==null||(g=f.KZb)==null||g.call(f)}catch(g){}HRA(b);for(const g of b.Yk)_.nn(g);if(e===1||_.BB&&e===4)f=JRA(b,d),!f||b.hq&&!b.hq.contains(document.activeElement)||pSA(f);(0,_.VMa)().then(()=>{_.rBe();(0,_.oh.dirty)()})});_.Mg(c,"ucVTnf",()=>{const f=b.plugin,
g=b.IX,h=a.oa,k=JRA(b,d),l=iRA(4,g)===1;let p;const q=(p=KRA(b,h))==null?void 0:p.hq;l&&q&&(q.style.display="");let r;(f==null?0:(r=f.uEb)==null?0:r.call(f,k))||!k||b.nca||(k.style.opacity="0");let u;if(f==null?0:f.ymb)u=_.Pg(c,"pU3PWb",()=>{let A;return void(f==null?void 0:(A=f.ymb)==null?void 0:A.call(f,k))});_.Pg(c,"s2IYHc",()=>{u&&_.Og(u);let A;(f==null?0:(A=f.UZb)==null?0:A.call(f,k))||!k||b.nca||(k.style.opacity="");l&&q&&(q.style.display="none")})})};
pSA=function(a,b,c=!1){if(c){c=b.UC;c||(b.UC=new _.VWb(a),_.TWb(b.UC),c=b.UC);let d;(d=_.SWb(c,0))==null||d.focus({preventScroll:!0})}else b=document.activeElement,a.contains(b)&&a!==b||(a.tabIndex===0?a.focus({preventScroll:!0}):(b=_.IWb(a).find(d=>!d.hasAttribute("data-os-fs")))?b.focus({preventScroll:!0}):(a.tabIndex=-1,a.focus({preventScroll:!0})))};
sSA=async function(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const e=mSA(a);if(e){e.j6a=3;var d=eRA(a.Oe);iSA(e.vja,d,d);document.dispatchEvent(new CustomEvent("viewerOpened"));b(await c(rSA(a,e)))}}finally{c()}};
xSA=async function(a,b,c=!1){var d=(0,_.Pf)(),e=d();d=d(1);try{_.GEe||(c=!1);const g=a.oa;let h=b.length<g.length,k=b.length>g.length;const l=Math.min(b.length,g.length);let p=l;for(let q=0;q<l;q++)if(g[q].uuid!==b[q].uuid){h=k=!0;p=q;break}oRA(g,c,p);if(h&&!k){var f=g[p];let q,r,u;const A=(u=(q=f.plugin)==null?void 0:(r=q.h4a)==null?void 0:r.call(q))!=null?u:tSA(a,f);a.Oe.logEvent({ef:new _.Kh(A,26)})}h&&uSA(a,p);if(k){const q=b.slice(p).map(nRA);for(let r=q.length-1;r>=0;r--)if(q[r].uuid===a.Aa){d(await e(vSA(a,
1)));return}g.push(...q);oRA(g,c,p)}a.Aa=-1;(k||h)&&d(await e(wSA(a,k)));a.Ba&&(a.Ba.resolve(),a.Ba=null)}finally{e()}};
uSA=function(a,b,c=!1){b=a.oa.splice(b,Infinity);var d;const e=(d=mSA(a))==null?void 0:d.hq;e&&(e.style.display="");if(b.length!==0){a.Aa=b[0].uuid;a.oa.length!==0||c?c&&document.dispatchEvent(new CustomEvent("viewerReplaced")):document.dispatchEvent(new CustomEvent("viewerClosed"));for(const f of b)c=f.hq,d=f.NEb,b=f.xX,TRA(f,null),c&&d?(_.rEe&&a.GEa.AZa(f),(d=f.UC)&&_.UWb(d),f.hq&&!f.hq.contains(document.activeElement)||document.activeElement.blur(),a.Ff.close(c)):b.resolve()}};
ySA=function(a,b){return kRA(a.xi,a.oa,b)};ASA=async function(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{const e=zSA(a,b);oRA(a.oa,!0,b);uSA(a,b,!0);c(await d(a.xi.go(-e)))}finally{d()}};
DSA=async function(a,b,c){var d=(0,_.Pf)(),e=d();d=d(1);try{const f=b.yx,g=b.entrypoint,h=b.interactionVed,k=b.eE,l=b.kG,p=b.IX,q=a.oa;for(const I of q)I.JIa=I.Mf;const r=_.X9h(g),u=_.cM(g);let A;const E={viewerType:b.viewerType,tW:b.tW,serializedModalityOverride:void 0,IX:p,serializedCloseConfig:p?YRA(p):void 0,shellStyleClass:b.shellStyleClass,hq:null,plugin:f,vX:new AbortController,contentPluginType:f.getType(),content:((A=f.serialize)==null?void 0:A.call(f))||new Uint8Array(0),entrypointId:r,
contentId:b.contentId,replacedEntrypointId:void 0,vja:jSA(h!=null?h:u,u,k),interactionVed:h!=null?h:u,j6a:2,Mf:3,JIa:7,oNa:new _.Hq,NEb:!1,Fqa:null,xX:new _.Hq,entrypoint:g,Kw:null,header:null,Yk:[],nza:c,uuid:Math.random(),nca:b.nca,KZa:b.KZa};PRA(E);q.push(E);q.length===1&&document.dispatchEvent(new CustomEvent("viewerOpened"));try{g&&!_.mEe&&(g.animate({transform:["scale(1)","scale(.98)","scale(1)"]},{duration:65}),c||d(await e((0,_.VMa)()))),d(await e(BSA(a,{client:E,kG:l}))),(0,_.WMa)(()=>void CSA(a))}catch(I){d()}return E.hq}finally{e()}};
BSA=function(a,{client:b,kG:c}){let d;c==null||c.Ts((d=b.viewerType)!=null?d:0);return _.B$h({client:b,kG:c,pwb:a.pwb})};CSA=async function(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const f=a.oa;if(!(f.length<2||f.at(-1).Mf<7)){var d=f.at(-2);if(!d.vX.signal.aborted&&d.Mf<7)try{d.j6a=1;var e=d.vja;e.mode!==1&&(e.mode=1,e.vja=new lSA);d.JIa=7;b(await c(BSA(a,{client:d})))}catch(g){b()}}}finally{c()}};
oSA=async function(a,b,c,{Gtb:d=!1,Occ:e}={}){var f=(0,_.Pf)(),g=f();f=f(1);try{if(d||b===mSA(a)){var h=d?0:ESA(a,b,c),k=zSA(a,h);d?oRA(a.oa,!0,h):b.nza=!1;e&&(a.Ba=e);var l=a.oa.slice(h);uSA(a,h);var p=vSA(a,k);f(await g(sSA(a)));f(await g(p));if(e){const q=l.map(r=>r.xX.promise);f(await g(Promise.all([e.promise,...q])))}if(!mSA(a)){const q=document.head.querySelector('link[rel="canonical"]');q&&document.head.removeChild(q)}}}finally{g()}};
zSA=function(a,b){let c=0;for(;b<a.oa.length;b++)a.oa[b].Fqa&&c++;return c};rSA=async function(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{const e=b.hq;e&&(e.style.display="");b.JIa=7;c(await d(BSA(a,{client:b,kG:new _.v6p})));(0,_.WMa)(()=>void CSA(a))}finally{d()}};FSA=function(a,b){return(b=JRA(b,KRA(b,a.oa)))?_.cM(b):eRA(a.Oe)};
wSA=async function(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{const k=mSA(a);if(k){_.AEe&&k.interactionVed&&_.Hp(a.Oe.oa(),new _.Kh(k.interactionVed)).log();if(b){k.j6a=4;var e=k.vja;var f=a.Oe;if(XRA)var g=XRA;else{var h=_.Ge(_.wm("iGkMSe"));g=XRA=_.x$h(f,251479,h)}iSA(e,g,FSA(a,k));document.dispatchEvent(new CustomEvent("viewerOpened"))}else k.j6a=5,iSA(k.vja,eRA(a.Oe),FSA(a,k));c(await d(rSA(a,k)))}}finally{d()}};
nSA=function(a,b,c,d){let e=null;if(c===1){let f,g;e=((f=b.plugin)==null?void 0:(g=f.EV)==null?void 0:g.call(f))||null}else if(c===2){let f,g;e=((f=b.plugin)==null?void 0:(g=f.GTa)==null?void 0:g.call(f))||null}e||(e=d.targetElement.hb());_.Ip(a.Oe.oa(),e,3).log()};vSA=async function(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{b>0&&(c(await d(a.xi.go(-b))),_.Ug(document.body,"nOJPYb"))}finally{d()}};ESA=function(a,b,c){b=iRA(c,b.IX);switch(b){case 1:return a.oa.length-1;case 2:return 0;default:return _.$a(b)}};
GSA=function(a,b){let c,d,e;const f=(e=(c=b.plugin)==null?void 0:(d=c.h4a)==null?void 0:d.call(c))!=null?e:tSA(a,b);(0,_.Bf)(()=>{a.Oe.logEvent({ef:new _.Kh(f,21)})})};tSA=function(a,b){if(b.Heb)return b.Heb;const c=_.PHb(b.hq);return b.Heb=_.x$h(a.Oe,3593,c)};
_.HSA=class extends _.fo{static Ta(){return{service:{overlay:_.wv,history:_.jur,Wf:_.Tu,logging:_.Ku,fZ:_.VQA,dJ:_.sYr,Jia:_.WQA}}}constructor(a){super();this.Aa=-1;this.Ba=null;this.pwb={isActive:c=>c===mSA(this),nNc:c=>!this.Ca.ppc(c.contentPluginType),nPc:c=>{const d=uRA({client:c,GEa:this.GEa,Ome:!0,Qme:!0,root:KRA(c,this.oa)});qSA(this,c,d);KRA(c,this.oa)&&d.classList.add("L3JeZd");_.w$h(d);return d},pPc:c=>{var d=c.plugin;d=this.Ca.ppc(c.contentPluginType)?d.v8d():uRA({client:c,GEa:this.GEa,
root:KRA(c,this.oa)});qSA(this,c,d);KRA(c,this.oa)&&d.classList.add("L3JeZd");_.w$h(d);return c.hq=d},O3c:c=>this.Ida(c.contentPluginType),boc:async(c,d)=>{var e=(0,_.Pf)(),f=e();e=e(1);try{c.plugin=e(await f(d.Tw(c.content,g=>this.Ida(g))))}finally{f()}},xTc:async c=>{var d=(0,_.Pf)(),e=d();d=d(1);try{const f=c.plugin,g=c.vX;let h;d(await e((h=f.fetch)==null?void 0:h.call(f,{signal:g.signal})))}finally{e()}},iz:c=>{const d=c.plugin,e=c.hq,f=c.vX,g=c.Kw,h=c.header,k=c.vja;let l={bC:!1,jA:!1};if(d.TOc){let p,
q;const r=(q=(p=d.I$e)==null?void 0:p.call(d))!=null?q:new Map;d.TOc(this.jr(),u=>this.Ida(u),r)}d.iz!=null&&(l=d.iz({Pj:e,signal:f.signal,YA:p=>void k.YA(p)}),l.bC&&(g==null||g.remove(),h==null||h.remove()));l.jA&&c.NEb&&FRA(e);return l.jA},render:async c=>{var d=(0,_.Pf)(),e=d();d=d(1);try{const f=c.plugin,g=c.hq,h=c.vX,k=c.Kw,l=c.header,p=c.vja;k==null||k.remove();l==null||l.remove();f.render!=null&&d(await e(f.render({Pj:g,signal:h.signal,YA:q=>void p.YA(q)})));if(_.hEe&&!g.querySelector('[jsname="OXxrqc"]')){const q=
document.body.querySelector('[jsname="yloBKd"]');(q==null?0:q.firstElementChild)&&g.appendChild(q.firstElementChild.cloneNode(!0))}(0,_.VMa)().then(()=>{_.Gq()})}finally{e()}},wvc:async(c,d)=>{var e=(0,_.Pf)(),f=e();e=e(1);try{e(await f(GRA(c,this.oa,this.Ff,this.Am,this.Da,this.onDismiss(c),d)));const l=this.oa,p=l.indexOf(c);if(p!==-1){var g=mSA(this);for(d=0;d<p;d++){const q=l[d],r=q.hq;r&&(r.style.display="none");TRA(q,g)}var h=c.plugin,k=c.hq;TRA(c,g);pSA(k,c,!("function"==typeof _.dci&&h instanceof
_.dci)&&_.BB)}}finally{f()}},pxc:c=>{IRA(c,this.oa,this.xi)}};this.Ff=a.service.overlay;this.xi=a.service.history;this.Am=a.service.Wf;this.Oe=a.service.logging;this.GEa=a.service.fZ;this.Da=a.service.dJ;this.Ca=a.service.Jia;if(yRA){var b;let c,d;(b=window.google)==null||(c=b.zl)==null||(d=c.qsvd)==null||d.call(c)}this.isRtl=document.body&&_.ie(document.body);a=this.xi.get();b=a.Fqa||a.url||[];this.oa=b.map(nRA);sSA(this).catch(()=>{});a.url&&(this.xi.update([],{replace:!0}),a.url.length>0&&this.xi.update(b,
{replace:!1}));(a.Fqa||a.url)&&RRA();this.xi.addListener((c,d)=>{xSA(this,c,d).catch(()=>{})});document.addEventListener("viewerGuestClose",()=>{uSA(this,0);ySA(this,{replace:!1}).catch(()=>{})});_.Mg(document.body,"gZgazf",this.JKa,this)}Sl(){var a=this.xi;if(_.$tr())var b=_.SEe.If();else{var {Fqa:c,url:d}=a.get();a=(b=c==null?void 0:c.at(-1))!=null?b:d==null?void 0:d.at(-1);b=new _.au(_.SEe.If());a?(b.pathname=`/searchviewer/${a.viewerType}`,b.searchParams.set("svid",_.cur(a,void 0,!0)),b.searchParams.delete("q"),
b.searchParams.delete("udm"),b.oa.delete("sv"),b=b.toString()):b=null}return b}gUb(){var a;{const {Fqa:d,url:e}=this.xi.get(),f=(a=d==null?void 0:d.at(-1))!=null?a:e==null?void 0:e.at(-1);f?a=_.bur(f,void 0,_.$tr()):(_.$tr(),a=null)}let b,c;return{content:(b=a==null?void 0:_.Pb(a.getContent()))!=null?b:new Uint8Array(0),contentPluginType:(c=a==null?void 0:a.getContentPluginType())!=null?c:null}}async prefetch(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const d=b(await c(this.XXb(a)));b(await c(Promise.all(d.map(async e=>
{let f;return await ((f=e.prefetch)==null?void 0:f.call(e))}))))}finally{c()}}async XXb(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const d={};a.forEach(f=>{d[String(f)]=this.Ca.dkc(f)});const e=b(await c(_.Wf(this,{service:d})));return Object.values(e.service)}finally{c()}}async Ida(a){return await _.Xf(this.Ca.dkc(a),this.jr())}async showViewerLite(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const d=this.Ida(a.contentPluginType);let e;const f=b(await c(d));if(a.zKb){const g=_.a$h(a.entrypoint);if(!g)throw Error("zA`"+
a.entrypoint);const h=b(await c(f.Tw(a.xsa,l=>this.Ida(l),{index:_.h$h(g,a.entrypoint),count:g.P7()}))),k=b(await c(this.Ida(3)));e=b(await c(k.getInstance({index:_.h$h(g,a.entrypoint),Z5a:h,bN:g})))}else e=b(await c(f.Tw(a.xsa,g=>this.Ida(g))));b(await c(this.showViewer({yx:e,HX:a.HX,entrypoint:a.entrypoint,interactionVed:a.interactionVed,kG:void 0,eE:a.eE,fsa:a.fsa,viewerType:a.viewerType,tW:a.tW,shellStyleClass:a.shellStyleClass,IX:a.IX,source:a.source,contentId:a.contentId,nca:a.nca,KZa:a.KZa})))}finally{c()}}async showViewer(a){var b=
(0,_.Pf)(),c=b();b=b(1);try{let d,e;if(yRA&&((d=window.google)==null?0:(e=d.zl)==null?0:e.qsvoc))return window.google.zl.qsvoc--,Promise.reject(new _.gna("search-viewer: quick viewer was closed"));a.HX!=null&&_.mci(a.HX);let f;a.kG||(a.kG=_.w6p((f=a.entrypoint.getAttribute("data-ep-type"))!=null?f:"",a.HX));SRA(a);const g=a.entrypoint,h=a.fsa,k=this.oa;this.Aa=-1;if(LRA(a,k)){let q,r;return Promise.resolve((r=(q=mSA(this))==null?void 0:q.hq)!=null?r:null)}const l=MRA(g,k),p=h?Math.max(0,l):l+1;if(p<
k.length){let q;const r=_.US(async()=>{var u=(0,_.Pf)(),A=u();u=u(1);try{const E=h?k[p].entrypointId:void 0;u(await A(ASA(this,p)));q=DSA(this,a,!0);const I=mSA(this);I.replacedEntrypointId=E;u(await A(I.oNa.promise))}finally{A()}},{root:{group:{styles:{animationDuration:"150ms"}}}});b(await c(r.updateCallbackDone));return q}return DSA(this,a,!1)}finally{c()}}JKa(a){a=a.data;if(typeof a!=="boolean"){var b=a.Occ;if(a.Gtb)this.oa.length===0?b==null||b.resolve():oSA(this,this.oa[0],0,a).catch(c=>{b&&
b.reject(c)});else if(b){const c=mSA(this);c?oSA(this,c,0,a).catch(d=>{b.reject(d)}):b.resolve()}}}CTa(){const a=mSA(this);let b="";try{if(a==null?0:a.hq)for(const f of a.hq.querySelectorAll("[data-sv-ctx]"))b+=" "+(f.textContent||"");let c,d;const e=(a==null?void 0:(c=a.plugin)==null?void 0:(d=c.CTa)==null?void 0:d.call(c))||new Map;e.has("prompt_text")||(b=b+" "+(e.get("prompt_text")||""));e.set("prompt_text",b);return e}catch(c){}return null}Bh(a,{content:b,entrypoint:c}){if(!a.vX.signal.aborted&&
a===mSA(this)){var d=!1;c&&c!==a.entrypoint&&(d=!0,a.entrypoint=c,a.entrypointId=_.X9h(c),PRA(a));NRA(a.content,b)||(d=!0,a.content=b);d&&a.Fqa&&ySA(this,{replace:!0})}}onDismiss(a){return({xX:b,eventType:c})=>{if(!this.oa.includes(a))return a.xX.resolve(b),!0;if(a!==mSA(this))return!1;a.xX.resolve(b);a:switch(c){case 2:b=3;break a;case 0:b=4;break a;default:b=0}oSA(this,a,b).catch(()=>{});GSA(this,a);return!0}}};_.Yf(_.W0a,_.HSA);

_.x();
_.kxq=_.y("qCgt4c",[_.W0a]);
_.v("qCgt4c");
_.cs(_.kxq,class extends _.as{static Ta(){return{service:{i9:_.HSA}}}constructor(a){super();this.Ag=a.service.i9}});
_.x();
_.v("QFOGlf");
_.KAr=new _.Tf(_.V2a);
_.x();
_.$gq=_.y("YlQIHe",[_.V2a]);
_.v("YlQIHe");
_.cs(_.$gq,class extends _.as{static Ta(){return{service:{copy:_.KAr}}}constructor(a){super();let b;a.service.copy.setLoggingElement(((b=this.qb("W2GRoe"))==null?void 0:b.el())||void 0)}});
_.x();
_.PXo=_.y("I9y8sd",[]);
_.v("I9y8sd");
var QXo=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},RXo=function(){return google.lfm&&google.lfm.some(a=>a.ie())},SXo=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},TXo=function(a,b,c,d,{logError:e}){d=_.af(d);b=`${b}-${c}-${_.ena(d)}`;const f=a.get(b),g=_.bf(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.ena(d)}`;(d=_.bf(d,"ck"))&&
(h=`${h}.ck=${d}`);e(Error("dr`"+JSON.stringify({type:c,Xgf:h,qef:f,Vdf:g})))}a.set(b,g)}},VXo=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;UXo.push(a)}},WXo={name:"umods"},XXo=!!(_.Ei[19]&256),YXo=!!(_.Ei[19]&512),ZXo=!!(_.Ei[19]&1024),$Xo=!!(_.Ei[19]&2048),aYo=!!(_.Ei[19]&4096),bYo=!!(_.Ei[19]&8192),cYo=!!(_.Ei[19]>>14&1);var dYo=["google.com","youtube.com","ampproject.org","adtrafficquality.google",(new URL(location.href)).host];var UXo=[],eYo=[],fYo=class extends _.as{static Ta(){return{}}constructor(){super();this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Wn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of UXo)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of eYo)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.df(b,{level:0,zf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});YXo&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.lm.HA)()}`,"")}sample(a,b){((a.chf?Math.random():this.Ca)<(a.sampleRate||0)||XXo)&&b()}};fYo.prototype.$wa$rT3LBf=function(){return this.Ba};
VXo({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of dYo)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("er"),b)}},toggle:$Xo});
VXo({name:"hp",run:function({logError:a}){if(!QXo()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=SXo(d);if(e){const f=d;(0,_.Wn)(()=>{e===SXo(f)&&a(Error("fr"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:ZXo});
VXo({name:"sp",run:function({logError:a}){var b;if(b=!QXo())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none")&&!RXo();if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("gr"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:ZXo});
VXo({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("hr"))},toggle:aYo});
VXo({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.tg("s",WXo);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&TXo(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&TXo(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&TXo(d,c,"comburl",g,{logError:a})}}}},toggle:cYo});
var gYo={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:bYo};if(gYo.toggle){var hYo;gYo.sampleRate=(hYo=gYo.sampleRate)!=null?hYo:1;eYo.push(gYo)}_.cs(_.PXo,fYo);
_.x();
});
// Google Inc.
