loaded_h_0(function(_){var window=this;
_.TVb=_.y("YjTCDb",[_.cr]);
_.v("YjTCDb");
var UVb,VVb;UVb=function(a,b){let c=b.el();for(b=c.parentElement;c!==document.body;b=b.parentElement)Array.from(b.children).forEach(d=>{d!==c&&d.getAttribute("aria-hidden")!=="true"&&(_.to(new _.qo(d),"aria-hidden",!0),a.Da.push(d))},a),c=b};VVb=function(a){a.Da.forEach(b=>{b.removeAttribute("aria-hidden")});a.Da=[]};
_.WVb=class extends _.Sv{constructor(a){super(a.Ac);this.Ba=!1;this.container=new _.lo([]);this.Ha=!1;this.Da=[];this.Ca=[];this.Ia=new _.FSb(null)}isOpen(){return this.Ba}open(a,b,c=!1){this.Ba||(this.Ia=new _.FSb(document.activeElement),this.PGa=_.Mg(a.el(),"MH4mvf",this.La,this),this.container=a,UVb(this,a),c?_.HSb(this,a):_.Qv(this,a,b),this.Ba=this.Ha=!0)}close(a=!0){this.Ba&&(this.Ba=!1,this.Ca.forEach(b=>{b.remove();document.body.appendChild(b)}),this.Ca=[],VVb(this),_.Rv(this.container),this.PGa&&
_.Og(this.PGa),this.Ha=!1,a&&this.Ia.restore(),this.container=new _.lo([]))}La(a){a=_.Fg(a).container;if(!this.Ca.includes(a)){a.remove();a.removeAttribute("aria-hidden");var b=this.container.el();this.Ha?b.insertBefore(a,b.lastElementChild):b.appendChild(a);this.Ca.push(a)}}};_.Yf(_.TVb,_.WVb);
_.x();
_.QVb=_.y("q00IXe",[_.Vq]);
_.v("q00IXe");
var RVb;RVb=function(a,b){return[{element:a.getRoot().hb(),Ax:"vLITie",oL:a.oa},{element:a.getRoot().hb(),Ax:"ho8p1c",oL:b===1},{element:a.getRoot().hb(),Ax:"vnmqGf",oL:b===2},{element:a.Ka("DUjDrd").hb(),Ax:"HEeD1c",oL:b===3},{element:a.Ka("DUjDrd").hb(),Ax:"uT5fcc",oL:b===4}]};
_.SVb=class extends _.as{static Ta(){return{service:{Bc:_.Ku}}}constructor(a){super();this.oa=!1;this.position=0;this.Pb=a.service.Bc;this.setPosition(2);this.id=_.gm(this.getData("cid"));this.trigger("w3NMIc",{controller:this});this.getRoot().Rc("aria-labelledby")!==null&&_.to(this.Ka("okoQgd").parent(),"id",this.getRoot().Rc("aria-labelledby"))}Pa(a){a=a.wb.el();this.trigger("qPDdOb",{triggerElement:a})}Ma(a){a=a.wb.el();this.trigger("uLpOF",{triggerElement:a})}getId(){return this.id}setPosition(a,
b=!0){this.position=a;b&&(a=RVb(this,a),(new _.URb(a,[],0,0)).open())}Ha(){this.position===1&&this.setPosition(3)}Ia(){this.position===1&&this.setPosition(4)}La(){this.position!==3&&this.position!==4||this.setPosition(1)}Da(){return RVb(this,this.oa?1:4)}Ba(){return RVb(this,2)}Aa(){return this.Ka("okoQgd")}Ca(){return this.Ka("okoQgd").el()}};_.SVb.prototype.$wa$Hv3npb=function(){return this.Ca};_.SVb.prototype.$wa$l8ZHOd=function(){return this.Aa};_.SVb.prototype.$wa$fSVRId=function(){return this.Ba};
_.SVb.prototype.$wa$y8p6Dd=function(){return this.Da};_.SVb.prototype.$wa$jji5be=function(){return this.La};_.SVb.prototype.$wa$Na055d=function(){return this.Ia};_.SVb.prototype.$wa$F3V9ae=function(){return this.Ha};_.SVb.prototype.$wa$pTuYge=function(){return this.getId};_.SVb.prototype.$wa$AuQwcb=function(){return this.Ma};_.SVb.prototype.$wa$jJaprb=function(){return this.Pa};_.cs(_.QVb,_.SVb);
_.x();
_.vw=_.y("Fh0l0",[_.Rq,_.TVb,_.Qq,_.Vq,_.Mq]);
var DWb=class extends _.m{constructor(a){super(a)}Ba(){return _.Fe(this,1)}Ha(a){return _.ui(this,1,a)}Ca(){return _.Pe(this,1)}Da(){return _.Ee(this,1)}Aa(){return _.Fe(this,2)}Pa(a){return _.ui(this,2,a)}La(){return _.Pe(this,2)}Ma(){return _.Ee(this,2)}};DWb.prototype.kb="cV628";var EWb={k6(){return["padt","padb"]},Bo(a,b){a=new _.dw(a.searchParams,b);_.Zv(a,"padt",b.Ha,b.Ca);_.Zv(a,"padb",b.Pa,b.La)},wp(a,b){b=new _.dw(b.searchParams,a);_.bw(b,a.Da,a.Ba,"padt");_.bw(b,a.Ma,a.Aa,"padb")}};var FWb;FWb=null;_.GWb=class extends _.tw{constructor(a,b){super(a);new _.uw(this);_.rw(b,this,new _.qw(EWb))}static Br(){return DWb}static Zr(a){return FWb?FWb:FWb=_.pw().then(b=>{b=new _.GWb(DWb,b);b.initialize(a);return b})}};_.Uo.cV628=_.To;
_.tWb=class extends _.wQb{constructor(a,b){super();this.open=a;this.close=b}};
_.sWb=class extends _.m{constructor(a){super(a)}Ca(){return _.Fk(this,1)}La(){return _.Vh(this,1)}Pa(){return _.Jj(this,2,_.kh())}Ba(){return _.Jj(this,2,3,void 0,!0).length}Ma(){return _.Jj(this,3,_.kh())}Aa(){return _.Jj(this,3,3,void 0,!0).length}Ha(){return _.Jj(this,4,_.kh())}mva(a){return _.Kj(this,4,a)}Da(){return _.Jj(this,4,3,void 0,!0).length}};_.sWb.prototype.kb="ol26e";
_.v("Fh0l0");
var WWb,XWb,YWb,bXb,iXb,hXb,fXb,gXb,jXb,kXb,cXb,dXb,ZWb,$Wb,aXb,eXb,lXb,mXb,nXb,oXb;WWb=function(a,b){const c=a.oa?1:4;a.position!==c&&a.setPosition(c,b)};XWb=[1,2];YWb=function(a){a=a!=null?a:new _.sWb;if(!a.Ca()){const b=a.Aa()>0;a.Ba()>0&&!b?_.Qh(a,1,2):_.Qh(a,1,1)}return a.Ud()};
bXb=function(a,b,c){if(a.oa){var d=a.Aa;if(d!==void 0){var e=a.Ca,f=d.Ca(),g=ZWb(a),h=$Wb(a,{zTd:g,bpa:c});h=_.Cv(_.Ev(_.Dv(_.XRb(_.Av(new _.Fv,q=>aXb(a,q)),a.NIb),!0),1),h);var k,l=(k=a.Ia.Qec)!=null?k:a.Qec;if(l){_.Bv(h,[...XWb,4]);let q;k=(q=a.Ia.ayd)!=null?q:()=>{bXb(a,b,c)};_.YRb(h,l,k)}a.Ia.gFc&&_.bSb(h,a.Ia.gFc);a.Ia.Aib&&_.Bv(h,a.Ia.Aib);var p=()=>{cXb(a,d);dXb(a,[[a,1],[d,1]],b)};e.style.position="fixed";c===void 0?(_.$Rb(h,f),a.Ff.open(e,h),p()):(_.dSb(h),a.Ff.open(e,h).then(async()=>{var q=
(0,_.Pf)(),r=q();q=q(1);try{if(q(await r(eXb(a,c)))){q(await r(g.open()));a.Xa=new _.VWb(e);_.TWb(a.Xa);var u;(u=_.JWb(f,-1)?f:_.SWb(a.Xa,0))==null||u.focus();p()}}finally{r()}}))}}};iXb=function(a,b,c){const d=a.Aa;d!==void 0&&(fXb(a),c===void 0?gXb(a,d,b):c.then(()=>{a.isOpen&&c===a.bpa&&(hXb(a,c),gXb(a,d,b))},()=>{a.close()}))};hXb=function(a,b){a.bpa===b&&(a.bpa=void 0)};
fXb=function(a){if(a.rb&&a.Ha){const b=_.FUb("stUuGf");b&&!b.contains(a.Ha)&&(b.appendChild(a.Ha),_.en(b,!0),a.Sa=b.style.visibility,b.style.visibility="visible",b.offsetHeight)}a.Cb||!a.Wf.isAvailable()||(a.Qb=a.Wf.isInBasicMode())||a.Wf.enterBasicMode(15);a.container.hasClass("ho8p1c")||a.container.addClass("ho8p1c");jXb(a);kXb(a)};gXb=function(a,b,c){cXb(a,b);const d=b.Aa();a.wJa.open(a.Ib,d);dXb(a,[[a,1],[b,1]],c)};
jXb=function(a){a.Qa&&_.nn(a.Qa);a.Qa=_.me(window,"scroll",c=>{const d=c.target;d&&!_.oi(a.container).contains(d)&&_.Tr(c)},!0);const b=a.Urb.get().Ba();window.scrollY<b&&window.scrollTo(0,b);a.Wa=window.scrollY;a.Pa.style.top=`-${a.Wa}px`;_.mm.add(a.Pa,"aKl9bd")};kXb=function(a){a.kq.listen(a.Ca,b=>a.onDismiss(b),XWb,!1,!0)};cXb=function(a,b){a.La=b;for(const c of a.Ba.values())WWb(c,!a.oa)};
dXb=function(a,b,c){a=_.Hp(a.Pb.oa(),c&&new _.Kh(_.Ge(c),3));for(const [d,e]of b)b=e,_.Kp(a,d.getRoot().el(),b);a.log(!0)};ZWb=function(a){const b=[],c=[];for(const d of a.Ba.values())b.push(...d.Da()),c.push(...d.Ba());return new _.URb(b,c,a.ub,a.ub)};$Wb=function(a,{zTd:b,bpa:c}){return new _.tWb(async()=>{var d=(0,_.Pf)(),e=d();d=d(1);try{c===void 0&&d(await e(b.open()))}finally{e()}},async()=>{var d=(0,_.Pf)(),e=d();d=d(1);try{a.bpa!==void 0?hXb(a,a.bpa):d(await e(b.close()))}finally{e()}})};
aXb=function(a,{eventType:b}){if(!a.oa)return!1;if(!a.isOpen)return!0;if(a.bpa===void 0){lXb(a);dXb(a,[[a,2],[a.La,2]]);let c;(c=a.Xa)==null||_.UWb(c);a.Xa=void 0}mXb(a);a.trigger("Yaup7b",{RQc:b});a.isOpen=!1;return!0};eXb=async function(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{let e=!1;try{c(await d(b))}catch(f){c(),e=!0}if(!a.isOpen||b!==a.bpa)return!1;if(e)return a.close(),!1;hXb(a,b);return!0}finally{d()}};
lXb=function(a){for(const b of a.Ba.values())b.setPosition(2,!a.oa);a.oa||a.kq.unlisten(a.Ca);a.Za=[]};mXb=function(a){if(a.rb){const b=window.matchMedia("(prefers-reduced-motion: reduce)").matches?0:a.ub;(0,_.Wn)(()=>{a.Ha&&!a.getRoot().el().contains(a.Ha)&&a.getRoot().el().appendChild(a.Ha);const c=_.FUb("stUuGf");c&&a.Sa&&(c.style.visibility=a.Sa,a.Sa=null)},b)}};
nXb=function(a,b,c){if(a.isOpen&&a.bpa===void 0){var d=a.La,e=!1;if(c===void 0){c=a.Za.pop();if(!c)return;d.Ia();e=!0}else a.Za.push(d),d.Ha();a.trigger("wO8kFd",{Kkf:e});a.La=c;c.La();c.Aa().focus();dXb(a,[[d,2],[c,1]],b)}};oXb=function(a,b){if(a.Aa!==b){var c=a.Aa;c&&(c.oa=!1);b.oa=!0;a.Aa=b;if(a.isOpen){a.Za=[];for(const d of a.Ba.values())WWb(d,!0);b.Aa().focus();a.La=b;b=[[b,1]];c&&b.push([c,2]);dXb(a,b)}}};
_.ww=class extends _.as{static Ta(){return{Hua:{container:"haAclf"},Xe:{NIb:_.sWb},We:{Urb:_.GWb},service:{kq:_.xv,wJa:_.WVb,overlay:_.wv,Bc:_.Ku,Wf:_.Tu}}}constructor(a){super();this.Za=[];this.La=null;this.Ba=new Map;this.Wa=0;this.Qa=null;this.isOpen=!1;this.Sa=null;this.Qb=!1;this.Ia={};this.Urb=a.We.Urb;this.kq=a.service.kq;this.wJa=a.service.wJa;this.Ff=a.service.overlay;this.Ha=this.Ka("eQ1It").el();this.container=new _.qo(a.Hua.container);this.Ib=this.Ka("ryFRZc");this.Ca=this.Ib.hb();this.Pb=
a.service.Bc;this.Pa=document.body;this.Wf=a.service.Wf;const b=this.getRoot().el(),c=["click"];this.getData("ct").Ob()&&c.push("touchstart","touchmove","touchend","touchcancel");for(const d of c)_.Mg(b,d,()=>{});this.oa=this.getData("os").Ob();this.Cb=this.getData("dh").Ob();this.oa&&(this.NIb=YWb(a.Xe.NIb));this.rb=this.getData("dd").Ob();this.ub=Number(_.hm(this.getData("dd"),"").replace(/ms$/,""))||0;this.Qec=_.qi(this.getData("db"));(this.oa||this.rb)&&_.Fo(this,this.oa?this.Ca:this.Ha)}Ma(a){if(!this.Da)if(this.Aa===
void 0)this.Da=()=>{this.Da=void 0;this.Ma(a)};else{var b=Promise.resolve(a);this.isOpen||(this.isOpen=!0,this.bpa=b,this.oa?bXb(this,void 0,b):iXb(this,void 0,b))}}iL(a){this.open(a.targetElement.el())}open(a){this.Da||(this.Aa===void 0?this.Da=()=>{this.Da=void 0;this.open(a)}:this.isOpen||(this.isOpen=!0,this.oa?bXb(this,a):iXb(this,a),this.notify("BUYwVb")))}stopPropagation(){}onClose(){this.close()}close(){this.isOpen&&(this.oa?this.Ff.close(this.Ca):this.kq.dismiss(this.Ca))}onDismiss(a){if(!this.isOpen)return!0;
this.bpa!==void 0?hXb(this,this.bpa):(lXb(this),dXb(this,[[this,2],[this.La,2]]));this.wJa.close();this.jT();this.container.removeClass("ho8p1c");mXb(this);this.Cb||!this.Wf.isAvailable()||this.Qb||this.Wf.exitBasicMode(15);this.trigger("Yaup7b",{RQc:a});this.isOpen=!1;return!0}jT(){_.mm.remove(this.Pa,"aKl9bd");this.Pa.style.top="";window.scrollY!==this.Wa&&window.scrollTo(0,this.Wa-_.hVb());const a=this.Qa;a&&_.pe(()=>{_.nn(a)});this.Qa=null;_.sVb(this.Pa)}Wb(a){a=a.data.controller;const b=a.getId();
if(b===null||b===""||b==="OWXEXe")throw Error("Ef`"+(b!=null?b:"<null>"));if(this.Ba.has(b))throw Error("Ff`"+b);this.Ba.set(b,a);this.Aa===void 0&&(this.Aa=a,a.oa=!0,this.Da&&(0,_.Wn)(this.Da,0));this.isOpen&&WWb(a,!0);let c;(c=this.Kb)==null||c.call(this,b,a)}Tb(a){const b=this.Ba.get(a.data.WVb);b&&nXb(this,a.targetElement.el(),b)}Rb(a){nXb(this,a.targetElement.el())}Lb(a){this.Ia=a}qc(a){const b=a.data.WVb;(a=this.Ba.get(b))?oXb(this,a):this.Kb=(c,d)=>{c===b&&(oXb(this,d),this.Kb=void 0)}}Vb(){this.kq.unlisten(this.Ca);
super.Vb()}};_.ww.prototype.$wa$k4Iseb=function(){return this.Vb};_.ww.prototype.$wa$mYaVb=function(){return this.qc};_.ww.prototype.$wa$acPBse=function(){return this.Rb};_.ww.prototype.$wa$Ib7Hzd=function(){return this.Tb};_.ww.prototype.$wa$yhG2Rd=function(){return this.Wb};_.ww.prototype.$wa$TvD9Pc=function(){return this.close};_.ww.prototype.$wa$tTT8Tc=function(){return this.onClose};_.ww.prototype.$wa$mLt3mc=function(){return this.stopPropagation};_.ww.prototype.$wa$kvzNsb=function(){return this.iL};
_.cs(_.vw,_.ww);
_.x();
_.uz=function(a){return _.t(a,49)};_.vz=function(a){return _.t(a,48)};_.wz=!!(_.Ei[54]&2048);
_.v("FRLJrd");
var YOc,$Oc,ZOc;_.WOc=function(a,b,c,d=!1){a=a.getWindow().innerHeight;a=(d?b.top:b.bottom)+c-a;b=-((d?b.bottom:b.top)-c);c=b>0?b>window.scrollY:!1;return a>0&&b<a&&!c};_.XOc=function(a,b){return!!a.um().el().contains(b)};YOc=function(a,b){if(b){var c=b.oa();if(c){a=a.um().el();var d=_.bn(a);if(d.height<a.scrollHeight){var e=a.getBoundingClientRect().top;const f=_.bn(c);c=c.getBoundingClientRect().top-e;e=f.height/2;c<e?a.scrollTop+=c-e:c+f.height>d.height-e&&(a.scrollTop+=c+f.height-d.height+e)}}b.focus()}};
$Oc=function(a,b,c){return(b?ZOc(a,!0,c):a.Ba()).find(d=>{d=d.getContent();return _.laa(d,a.prefix)})||null};ZOc=function(a,b,c){a=a.Ba();c===null&&(c=b?_.va(a):a[0]);if(c){const d=a.findIndex(e=>e===c);a=_.opb(a,b?-d-1:-d)}return a};
_.xz=class extends _.as{static Ta(){return{service:{Bc:_.Ku,overlay:_.wv},zd:{Df:{jsname:"eQ1It",ctor:_.ww}}}}constructor(a){super();this.od=this.getData("mb").Ob();this.Ld=!this.getData("dr").Ob();this.Ig=!this.getData("dz").Ob();this.Af=this.getData("bsis").Ob();this.prefix="";this.Kb=!this.od;this.WG=!1;this.Ca=new Set;this.Pb=a.service.Bc;this.Ff=a.service.overlay;this.Df=a.zd.Df;this.um=_.rn(()=>this.Ka("xl07Ob"));this.Fc=_.rn(()=>this.qb("H9P06b"));this.Qb=()=>this.um().hb();this.Rb=new _.Cr(this.Xc,
1E3,this);_.si(this,this.Rb);this.Df||_.si(this,(new _.ee(this)).listen(window,"resize",_.tn(()=>{this.WG&&this.Wa()},250)))}zc(){const a=this.Ba().filter(b=>b.isSelected());this.Ca=new Set(a);this.Ca.size>1&&this.clearSelection(a[0])}clearSelection(a){for(const b of this.Ca)b!==a&&b.Lk(!1);this.Ca=a?new Set([a]):new Set}ji(a){if(a){let b;(b=this.oa())==null||b.setAttribute("disabled","");let c;(c=this.oa())==null||c.classList.add("disabled")}else{let b;(b=this.oa())==null||b.removeAttribute("disabled");
let c;(c=this.oa())==null||c.classList.remove("disabled")}}Wb(){let a;((a=this.oa())==null?0:a.hasAttribute("disabled"))||(this.WG?this.close():this.open())}Pa(a){a=_.Av(_.Bv(_.gSb(_.hSb(_.Cv(_.VRb(new _.Gv,2),this.getAnimation()),a),a),[1,2,3]),b=>this.Ma(b));this.Ld&&(_.Dv(a,!0),this.Ig&&_.bSb(a,127),_.Fo(this,this.um().hb()));return a}open(){this.Aa()}async Aa(){var a=(0,_.Pf)(),b=a();a=a(1);try{this.zc();const d=this.oa();if(!this.WG&&d){if(this.Df)this.Df.open(this.oa()||void 0);else if(this.Af)this.trigger("zh0nQd",
{WVb:this.um().hb().id}),this.Tb();else{const e=this.Pa(d);a(await b(this.Ff.open(this.Qb(),e)));this.Za(!0);this.Sa(!0)}this.WG=!0;var c=this.Ca.size>0;this.getRoot().getData("e").Ob()&&(this.getRoot().toggleClass("x1SoId",c),this.getRoot().toggleClass("wYGjQ",!c));this.trigger("Yi86H")}}finally{b()}}close(){this.WG&&(this.Df?(this.Df.close(),this.Lb()):this.Ff.close(this.Qb()))}Lb(){this.WG=!1;this.trigger("L7T4N")}rb(a,b,c,d=!1){a=_.WOc(this,a,b);return d?a?[12,13]:[13,12]:a?[8,9]:[9,8]}qc(a,b){const c=
this.getWindow().innerWidth;return{PKc:!1,a6c:Math.max(b-(c-(_.wz?c-a.right:a.left)-8),0)}}Wa(){const a=this.oa();if(a){var b=a.getBoundingClientRect(),c=this.um().hb();this.um().setStyle("width","");this.um().setStyle("max-width","");var d=this.od?b.width||0:Math.ceil(c.getBoundingClientRect().width),{PKc:e,a6c:f}=this.qc(b,d);f>0&&this.Kb&&(d-=f);this.um().setStyle("width",`${d}px`);this.um().setStyle("max-width",`${d}px`);c=c.offsetHeight;var [g,h,k]=this.rb(b,c,d,e);_.jw(a,g,this.um().el(),h,
k,void 0,void 0,new _.Md(d,c))}}getAnimation(){const a=[{element:this.um().hb(),Ax:"vpR9sb",oL:!0}],b=[{element:this.um().hb(),Ax:"vpR9sb",oL:!1}],c=new _.URb(a,b,0,0);return new _.tWb(async()=>{var d=(0,_.Pf)(),e=d();d=d(1);try{let f;(f=this.Fc())==null||f.addClass("vpR9sb");this.Wa();d(await e(c.open()))}finally{e()}},async()=>{var d=(0,_.Pf)(),e=d();d=d(1);try{d(await e(c.close()));let f;(f=this.Fc())==null||f.removeClass("vpR9sb")}finally{e()}})}Ma(){this.um().setStyle({top:"",right:"",bottom:"",
left:""});this.WG=!1;this.Za(!1);this.trigger("L7T4N");this.Sa(!1);return!0}Tb(){var a=_.Ema(this.oa());a=_.Lh(a,3,0);_.Hp(this.Pb.oa(),a).log(!0)}Sa(a){var b=a?_.Ema(this.oa()):null;b=_.Lh(b,3,a?0:1);const c=this.Pb.oa();_.Hp(c,b);_.Kp(c,this.um().el(),a?1:2);c.log(!0)}Xc(){this.prefix=""}GK(a){return this.Ba().find(b=>b.oa()===a)}selected(a){this.close();this.clearSelection();a.source instanceof _.VOc&&this.Ca.add(a.source);this.trigger("oJ9QV");return!0}NPb(a){a.source instanceof _.VOc&&this.Ca.delete(a.source);
this.trigger("oJ9QV");this.close();return!0}rl(a){const b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode;if(c===27||c===9)return!0;let d;if(((d=this.oa())==null?0:d.contains(a.targetElement.el()))&&c===40){YOc(this,this.Qa());let h;(h=b.stopPropagation)==null||h.call(b);let k;(k=b.preventDefault)==null||k.call(b);return!1}if(!_.XOc(this,a.targetElement.el()))return!1;a=this.Ec();if(c===40||c===38){if(!(c===40&&a===this.Hc()||c===38&&a===this.Qa())){c=c===
40;a=ZOc(this,c,a);var e;c=(e=c?a.shift():a.pop())!=null?e:null;YOc(this,c)}}else{if(c===13||c===32&&!this.prefix)return!0;_.PJa(c)&&(this.Rb.start(),e=String.fromCharCode(c),this.prefix===e?e=$Oc(this,!0,a):(this.prefix+=e,e=$Oc(this,!1,a)),e&&YOc(this,e))}let f;(f=b.stopPropagation)==null||f.call(b);let g;(g=b.preventDefault)==null||g.call(b);return!1}Qa(){return this.Ba()[0]||null}Hc(){const a=this.Ba();return a.length>0?a[a.length-1]:null}Ec(){return this.Ba().find(a=>a.oa().contains(document.activeElement))||
null}};_.xz.prototype.$wa$rdwPFf=function(){return this.Ec};_.xz.prototype.$wa$vpeaX=function(){return this.Hc};_.xz.prototype.$wa$VZgx0c=function(){return this.Qa};_.xz.prototype.$wa$uYT2Vb=function(){return this.rl};_.xz.prototype.$wa$AOJsKd=function(){return this.NPb};_.xz.prototype.$wa$gk6SMd=function(){return this.selected};_.xz.prototype.$wa$hmHDoe=function(){return this.Tb};_.xz.prototype.$wa$fnBGHd=function(){return this.getAnimation};_.xz.prototype.$wa$s54zIe=function(){return this.Wa};
_.xz.prototype.$wa$b7PJRd=function(){return this.Lb};_.xz.prototype.$wa$TvD9Pc=function(){return this.close};_.xz.prototype.$wa$rpDY5c=function(){return this.Aa};_.xz.prototype.$wa$FNFY6c=function(){return this.open};_.xz.prototype.$wa$gq6u4d=function(){return this.Wb};_.xz.prototype.$wa$JHxHSe=function(){return this.zc};
_.x();
_.dPc=_.gr("FRLJrd",[_.Vq,_.Qq,_.vw]);
_.ePc=_.y("eBYPP",[_.bPc,_.dPc]);
_.v("eBYPP");
_.fPc=class extends _.xz{static Ta(){return{controllers:{items:{jsname:"qRxief",ctor:_.cPc}}}}constructor(a){super(a.Ac);this.Da=this.getData("sm").Ob();this.Kb=!this.Da;this.qx=a.controllers.items;this.Ha=_.rn(()=>{const b=this.Ka("oYxtQd");return b.el()?b:null})}Ba(){return[...this.qx]}oa(){let a;return((a=this.Ha())==null?void 0:a.hb())||null}Pa(a){a=super.Pa(a);this.Da?_.fSb(a,1):_.fSb(a,3);this.Da||_.WRb(a,2,{stack:[2]});return a}open(){this.Aa()}async Aa(){var a=(0,_.Pf)(),b=a();a=a(1);try{a(await b(super.Aa()));
const d=this.oa();if(this.Da){var c;(c=this.Qa())==null||c.focus();this.Df||d&&!d.classList.contains("Esm33e")&&d.classList.add("Esm33e")}}finally{b()}}Ma(a){if(a=super.Ma(a)){let b;(b=this.oa())==null||b.classList.remove("Esm33e")}return a}Za(a){let b,c;(c=this.Da?(b=this.oa())==null?void 0:b.querySelector('[role="button"]'):this.oa())==null||c.setAttribute("aria-expanded",a.toString())}Cb(){this.Da&&this.Aa();return!0}ub(a){let b;var c;if(c=this.Da){a=(b=a.data)==null?void 0:b.relatedTarget;let d;
c=!(this.um().el().contains(a)||this.getRoot().el().contains(a)||((d=this.oa())==null?0:d.contains(a)))}c&&this.close();return!0}rl(a){if(!this.Da)return super.rl(a);var b=a.event;b=b.which||b.keyCode;var c=this.oa();const d=!_.wz;c=c==null?void 0:c.contains(a.targetElement.el());const e=d&&b===39||_.wz&&b===37;if(c&&!e)return!0;c&&e?this.WG||this.Aa():(d&&b===37||_.wz&&b===39)&&this.close();return super.rl(a)}Xa(a){let b;((b=a.data)==null?0:b.Eqc)||this.close();return!0}close(){super.close()}rb(a,
b,c,d){if(this.Da){d=getComputedStyle(this.um().hb()).paddingTop.replace("px","");d=new _.Ld(0,-1*(Number(d)||0));b=_.WOc(this,a,b,!0);const e=(a.left-c)*-1;a=a.right+c-this.getWindow().innerWidth;a=(_.wz?e>0&&a<e:a>0&&e<a)?b?[9,13,d]:[8,12,d]:b?[13,9,d]:[12,8,d]}else a=super.rb(a,b,c,d);return a}qc(a,b){var c=this.getWindow().innerWidth;const d=this.Kb?8:0;c=a.left+b+d-c;a=(a.right-b-d)*-1;return{PKc:_.wz?a>0&&c<a:c>0&&a<c,a6c:Math.max(Math.min(c,a),0)}}Sa(a){this.Da||super.Sa(a)}Vb(){this.La&&_.Og(this.La);
this.Ia&&_.Og(this.Ia);super.Vb()}};_.fPc.prototype.$wa$k4Iseb=function(){return this.Vb};_.fPc.prototype.$wa$TvD9Pc=function(){return this.close};_.fPc.prototype.$wa$Seb4Qb=function(){return this.Xa};_.fPc.prototype.$wa$uYT2Vb=function(){return this.rl};_.fPc.prototype.$wa$veZYT=function(){return this.ub};_.fPc.prototype.$wa$fRYjtf=function(){return this.Cb};_.fPc.prototype.$wa$rpDY5c=function(){return this.Aa};_.fPc.prototype.$wa$FNFY6c=function(){return this.open};_.fPc.prototype.$wa$Wn4E8e=function(){return this.oa};
_.fPc.prototype.$wa$kKeMjf=function(){return this.Ba};_.cs(_.ePc,_.fPc);
_.x();
_.R0=function(a){return`[jsname="${a}"]`};_.Rer=_.R0("ZLxsqf");_.Ser=_.R0("E6JrNd");
_.kqs=function(a){return`\n\n##########################################################################
### ${a}
##########################################################################`};_.lqs=function(a){const b=document.body.querySelector(_.R0("UCHPqc"));if(!b)return null;let c=document.getElementById(a);c||(c=document.createElement("div"),c.id=a,c.classList.add("ktvLwd"),b.appendChild(c));return c};_.nqs=function(){let a;const b=((a=_.mqs("OYkqOb"))==null?void 0:a.getAttribute("href"))||"";if(b)return{name:"/search",link:b}};
_.pqs=function(){let a=_.oqs("D2tCC");a=a.length>0?a:_.oqs("lro_sherlog_link_");return[...a.map(b=>{b=b.getAttribute("href")||"";return{link:b,name:b.includes("Darksteel+Widget")?"MagiLRO - Widget":"MagiLRO"}}),..._.oqs("KXEGMc").map(b=>({link:b.getAttribute("href")||"",name:"/async/folftch"})),..._.oqs("pJjOnd").map(b=>{let c,d;return{link:b.getAttribute("href")||"",name:((c=b.innerText)==null?void 0:(d=c.replace("Sherlog",""))==null?void 0:d.trim())||"Async"}})].filter(b=>b.link)};
_.mqs=function(a,b=document.body){return[...b.querySelectorAll(_.R0(a))].at(-1)};_.oqs=function(a,b=document.body){return[...b.querySelectorAll(_.R0(a))]};_.qqs=function(a){const b=new URL("https://searchdebugger.corp.google.com/past/debug/overview");b.searchParams.set("testsherlogurl",a);return b};_.rqs=_.kqs("Previous Turn");
_.OKq=_.y("zouQy",[_.Kq,_.Tq]);
_.JKq=_.y("DOjgn",[]);
_.zef=function(a,b){b=_.lpa({Cc:b},!1);b=_.Ff(b);try{return _.Nf(a instanceof _.bc?_.vpa(a):a)}finally{_.Ff(b)}};
_.v("zouQy");
var dts=function(a){a.style.display=a.style.display!=="block"?"block":"none"},ets=class extends _.as{static Ta(){return{service:{rc:_.Vv,Yb:_.Az}}}constructor(a){super();this.Aa=document.body.querySelector(_.R0("j4auif"));this.oa=document.body.querySelector(_.R0("dGolQe"));this.Da=document.body.querySelector(_.R0("EljlOd"));this.Ca=document.body.querySelector(_.R0("M3wrwe"));this.Ba=document.body.querySelector(_.R0("ySwUP"));this.rc=a.service.rc;this.Yb=a.service.Yb}Sa(){const a=document.body.querySelector("#memory-drawer");
dts(a)}async Qa(){var a=(0,_.Pf)(),b=a();a=a(1);try{const c=a(await b(_.zef(_.Mq,this.jr()))),d=document.body.querySelector("#feedback-drawer");dts(d);d.style.display==="block"?(window.scrollTo({top:0,behavior:"instant"}),_.xWi&&c.isAvailable()&&a(await b(c.enterBasicMode(65)))):_.xWi&&c.isAvailable()&&c.isInBasicMode()&&a(await b(c.restoreToPreviousState(65)))}finally{b()}}async Ia(){this.notify("MCziPc");if(!document.body.querySelector("#debug-drawer")&&this.Ca){var a=_.lqs("debug-drawer");a&&(a.replaceChildren(this.Ca),
this.Ca.style.display="block")}a=document.body.querySelector("#debug-drawer");dts(a)}async Ha(){this.notify("MCziPc");if(!document.body.querySelector("#ads-debug-drawer")&&this.Ba){var a=_.lqs("ads-debug-drawer");a&&(a.replaceChildren(this.Ba),this.Ba.style.display="block")}a=document.body.querySelector("#ads-debug-drawer");dts(a)}async Pa(){if(this.Aa&&this.oa&&(this.Aa.toggleAttribute("hidden"),!this.Aa.hasAttribute("hidden"))){this.oa.remove();var a=_.cu().get("q");a=(0,_.vc)`https://www.google.com/search?q=${a}&igu=1&gsc=1`;
_.Jc(this.oa,a);this.Aa.appendChild(this.oa)}}async La(){var a=(0,_.Pf)(),b=a();a=a(1);try{this.Da&&a(await b(_.Do(this,this.Da))).oa()}finally{b()}}async Ma(){const a=new _.bu(this.rc.If());a.searchParams.delete("csuir");a.searchParams.delete("mstk");this.Yb.navigateTo(_.qc(a.toString()))}};ets.prototype.$wa$m8mq3=function(){return this.Ma};ets.prototype.$wa$jmJuMb=function(){return this.La};ets.prototype.$wa$BgSDEb=function(){return this.Pa};ets.prototype.$wa$yMCZo=function(){return this.Ha};
ets.prototype.$wa$vPcAUd=function(){return this.Ia};ets.prototype.$wa$FLqQwf=function(){return this.Qa};ets.prototype.$wa$aVVNTe=function(){return this.Sa};_.cs(_.OKq,ets);
_.x();
_.jvq=_.y("zLjACb",[]);
var b6e,c6e,d6e;b6e=function(){var a=document;_.gAa(a);return a.__gwbp};_.e6e=function(){c6e||(c6e=b6e().then(a=>d6e=a));return c6e};_.e6e();var f6e=Event;_.g6e=class extends f6e{constructor(a){super(a,{bubbles:!0});d6e.addEvent(a)}};
_.v("zLjACb");
var ezr=class extends _.g6e{constructor(){super("aimNavigateToZeroState")}};var fzr=class extends _.g6e{constructor(){super("aimOpenThreadsView")}};var gzr=class extends _.as{static Ta(){return{}}oa(a){_.hw(a.wb.el());let b;(b=document.querySelector('[data-xid="Lr04i"]'))==null||b.dispatchEvent(new fzr);let c;(c=document.querySelector('[data-xid="m3fCN"]'))==null||c.dispatchEvent(new fzr)}Aa(a){_.hw(a.wb.el());let b;(b=document.querySelector('[data-xid="Lr04i"]'))==null||b.dispatchEvent(new ezr)}};gzr.prototype.$wa$JqmUue=function(){return this.Aa};gzr.prototype.$wa$ez1Xib=function(){return this.oa};_.cs(_.jvq,gzr);
_.x();
_.Lr=class extends _.m{constructor(a){super(a)}};
_.Jr=new _.Bq("componentConnected");_.Kr=new _.Bq("componentDisconnected");
_.v("YNjGDd");

_.x();
_.Ynb=function(a,b){return b(`[${a.substring(4)}`)};_.$nb=class extends _.m{constructor(a){super(a)}clearValue(){return _.fj(this,_.Znb)}};_.Znb=[1,2];var aob;aob=class extends _.m{constructor(a){super(a)}clearValue(){return _.fj(this,_.Ir)}};_.Ir=[2,3,4,5,6,8];var cob=class extends _.m{constructor(a){super(a)}};var dob=class extends _.m{constructor(a){super(a)}getIdentifier(){return _.n(this,cob,1)}RTa(){return _.jh(this,aob,2,_.kh())}GSb(){return _.dj(this,3)}};_.eob=function(a){return _.jh(a,dob,1,_.kh())};_.fob=_.Yb(class extends _.m{constructor(a){super(a)}});
_.v("IZT63");
var kob=function(){const a=_.Cla("nQyAE",window);var b=_.Cla("TSDtV",window);if(b&&typeof b==="string"){var c=_.eob(_.Ynb(b,_.fob))[0];if(c){b={};for(d of c.RTa())switch(c=_.t(d,7),_.hj(d,_.Ir)){case 3:b[c]=_.Lj(d,3,_.Ir);break;case 2:b[c]=_.we(_.fEa(d,2,_.Ir));break;case 4:b[c]=_.hEa(d,4,_.Ir);break;case 5:b[c]=_.Nj(d,5,_.Ir);break;case 8:const e=_.mj(d,_.$nb,8,_.Ir);switch(_.hj(e,_.Znb)){case 1:b[c]="%.@."+_.Nj(e,1,_.Znb).substring(1)}}var d=b}else d={}}else d={};if(d&&Object.keys(d).length>0)for(let e of Object.keys(d))e in
a||(a[e]=d[e]);return a};_.lob=class{get(a){const b=kob()[a];return b!==void 0?new _.Dla("nQyAE."+a,b):null}getAll(){return(new _.Dla("nQyAE",kob())).object()}};_.Zf(_.lob,_.Yxa);
_.x();
_.v("YYmHzb");
var gob=class{constructor(){let a=null;this.Ba=!0;var b=_.Cla("TSDtV",window);(b=typeof b!=="string"?null:b)&&(a=_.eob(_.Ynb(b,_.fob))[0]);if(a)for(var c of a.RTa())if(_.Xi(c,_.gi,6,_.Ir))throw Error();if(b=a){c={};for(d of b.RTa())switch(b=_.Ke(d,1).toString(),_.hj(d,_.Ir)){case 3:c[b]=_.Lj(d,3,_.Ir);break;case 2:c[b]=_.we(_.fEa(d,2,_.Ir));break;case 4:c[b]=_.hEa(d,4,_.Ir);break;case 5:c[b]=_.Nj(d,5,_.Ir);break;case 6:c[b]=_.Hh(d,_.gi,6,_.Ir);break;case 8:const e=_.mj(d,_.$nb,8,_.Ir);switch(_.hj(e,
_.Znb)){case 1:c[b]=_.Nj(e,1,_.Znb);break;default:throw Error("Ze`"+_.hj(e,_.Znb));}break;default:throw Error("Ze`"+_.hj(d,_.Ir));}var d=c}else d={};this.Aa=d;this.token=a?a.GSb():null}oa(a){return a.phase===1||this.Ba&&!(a.key in this.Aa)?a.defaultValue:a.ctor(this.Aa[a.key])}GSb(){return this.token}};_.hob=class extends _.fo{constructor(){super();this.delegate=new gob}oa(a){this.delegate=this.delegate;return this.delegate.oa(a)}GSb(){this.delegate=this.delegate;return this.delegate.GSb()}};_.Yf(_.lFa,_.hob);
_.x();
_.v("PrPYRd");
var nob,oob,pob,rob,tob,uob,vob,zob,Aob,sob,Dob,wob,Hob,Fob,xob,Gob;nob=function(a){const b={};for(let c in a){const d=a[c].vk!=null?a[c].vk:"data";d in b||(b[d]={});b[d][c]=a[c]}a={};for(let c in b)a[c]=b[c];return a};oob=function(a){return _.oCa(a,(b,c)=>(b[c.UDb]=c,b),{})};pob=function(a,b){let c;for(const d of((c=a.metadata)==null?void 0:c.Wt)||[])if(d.key===b){d.value.notify(0);break}};rob=function(a){const b=a.Ka();return b?(_.qob(b,null),b.XyHi9=null,a.Id=null,!0):!1};
tob=function(){const a=_.sd("w2btAe");return a&&a.Ob&&a.Ob()?_.Ynb(a.string(),sob):new _.Ywa};uob=function(a,b){return _.yc(b,c=>{c=_.Ija(c,(e,f)=>f.indexOf(`${a}|`)==0);const d={};_.xc(c,(e,f)=>{d[f.substring(f.indexOf("|")+1)]=e});return d})};vob=function(a){return Object.keys(a).reduce((b,c)=>b||!!a[c],!1)};
zob=function(a,b,c,d,e,f){const g={qua:b},h=new _.yva({FVxLkf:g},c,void 0,d);return()=>{function k(l){const p={},q=_.yc(wob(b),(r,u)=>r.then(A=>A.length!=1||xob(A[0])?_.zh(A.map(E=>_.yob(E))).then(E=>{p[l.get(u)]=E}):_.yob(A[0]).then(E=>{p[l.get(u)]=E})));return _.zh(_.zc(q)).then(()=>p)}g.hOc=e instanceof _.Lg?e.then(k):k(e);return _.zh([f,g.hOc]).then(()=>_.xva(a.xq,h,d))}};Aob=function(a){var b=_.Rf.getInstance();a=_.tpa(b,a);return _.EOa?_.Moa(_.Kf(a,!0).then()):_.Xpa(a)};
_.qob=function(a,b){a.__component=b};sob=_.Yb(_.Ywa);_.Cob=function(a,b){var c=_.iPa(a);if(c)return _.Bg(c);if(c=a.XyHi9)return c;c=_.Hg(a,d=>!!d.attributes&&!!d.attributes.getNamedItem("c-wiz"));if(!c||a.getAttribute("data-node-index")==="0;0")return Bob(b,a);b=_.Cob(c,b);if(!a.hasAttribute("c-wiz"))return b;b=b.then(d=>Dob(d).then(e=>{const f=a.getAttribute("data-node-index");e=e[f];if(!e)throw Error("$e`"+d.id+"`"+a.getAttribute("jsrenderer")+"`"+f);_.Eob(e,a);return e}));return a.XyHi9=b};
Dob=function(a){a.La||(a.La=_.zh(_.zc(a.Aa)).then(_.nba).then(b=>_.zh(b.map(c=>c.id&&c.id.lkb()?Fob(c):c))).then(b=>oob(b)));return a.La};_.Eob=function(a,b){a.id.lkb()?Fob(a).then(c=>{_.qob(b,c)}):_.qob(b,a);a.Id=b;for(const c in a.uSa)pob(a.uSa[c],_.Jr)};wob=function(a){return _.yc(a.Aa,b=>b instanceof Gob?_.Bg([b]):b)};Hob=function(a,b){return b(a)?_.zh(Object.values(wob(a)).map(c=>c.then(d=>_.zh(d.map(e=>Hob(e,b)))))):_.Bg(!0)};_.yob=function(a){a.Pa||(a.Pa=a.Qa());return a.Pa};
Fob=async function(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const d=b(await c(a.Ma)),e=Object.values(d),f=a.id.getName();if(!e.length)throw Error("af`"+f);const g=b(await c(e[0]));if(!g.length)throw Error("bf`"+Object.keys(d)[0]);return g[0]}finally{c()}};xob=function(a){return a.Ca&&a.Ca.repeated};
Gob=class{constructor(a,b,c,d,e,f,g,h,k,l){this.id=a;this.Ha=b;this.Ba=c;this.UDb=d;this.uSa=e;e===null&&a.getName();this.Ia=f;this.oa=g||{};this.Aa=h;this.Ma=k;this.Ca=l;this.La=null;this.Da=!1;this.Qa=this.Pa=this.Id=null}getParams(){return this.Ha}update(a,b,c,d,e,f,g,h,k,l){this.Ha=b||this.Ha;this.UDb=d||this.UDb;this.Ia=f||this.Ia;this.oa=g||this.oa;this.uSa=e||this.uSa;this.Aa=h||this.Aa;this.Ma=k||this.Ma;this.Ca=l||this.Ca;this.Ba=c||this.Ba}Ka(){return this.Id}dispose(){if(!this.Da){this.Da=
!0;for(const a in this.uSa)pob(this.uSa[a],_.Kr);Hob(this,rob)}}isDisposed(){return this.Da}};var Iob,Kob,Mob;Iob=function(a){return a.Da||new (a.xq.getParams().ctor)};_.Job=function(a,b){a.Ba=Object.assign(a.Ba||{},b);return a};Kob=function(a,b,c){a.Ia=b;a.La=c;return a};
Mob=class{constructor(a,b,c){this.xq=a;this.Da=c||void 0;this.Ha=b}Eca(){return this.Ma}Aa(a){this.Ca=a;return this}R3a(){const a=this.Ba&&this.Ba.Wt||[];a.push({key:_.Jq,value:!0});return _.Job(this,{Wt:a})}oa(a){if(!a)return this;const b=_.yc(a,c=>()=>c);return Kob(this,()=>_.Bg(a),b)}fetch(){return _.yob(_.Lob(this.Ha,this.Ha,[this])[0])}};_.Mr={};var Bob,Nob,Oob,Pob,Uob,Qob,Rob,Sob,Tob,Vob,Wob,Xob,Yob;Bob=function(a,b){const c=b.getAttribute("jsrenderer"),d=_.uua(c);return _.Bg(Aob(d)).then(()=>{var e=_.iPa(b);if(e)return e;const f=_.Mr[c];e=b.getAttribute("data-p")?_.Ynb(b.getAttribute("data-p"),h=>_.Xb(f.getParams().ctor,h)):null;const g=new _.Uza(b,_.bg(_.$d(b)),_.Nr);e=_.Lob(a,g,[a.jF(f,e)])[0];_.Eob(e,b);return e})};
_.Lob=function(a,b,c){var d=_.nba(_.Li(c,e=>Nob(a,e.xq,!0)));_.GOa(_.Rf.getInstance(),d);c=c.map(e=>Oob(a,b,e,"0;0"));d=[].concat(...c.map(e=>e.z2a));Pob(a,d,b);return c.map(e=>e.qua)};Nob=function(a,b,c=!1){const d=[];c&&d.push(b.xq);const e=b.oa();e&&e.length>0&&e.forEach(f=>void d.push(f));b.lkb()||_.xc(b.getChildren(),f=>{f.recursive||_.Fa(d,Nob(a,f.id,c))});return d};
Oob=function(a,b,c,d,e){const f=c.xq,g=tob(),h=Qob(a,c,g);var k=`${f.getName()}:${a.oa++}`;const {OPc:l,vPc:p}=Rob(a,b,h,c.Ia,k);k=p?[p]:[];const q={};var r=_.Bg();let u=_.Bg();if(f.lkb()){r=Sob(f,l,c.Da);var A=r.then(({gAd:N})=>Tob(a,b,c,g,l,N));u=r.then(({hAd:N})=>N);r=A.then(N=>{Object.assign(q,N.gOc);N=Object.values(q);return N.length===1?N[0].then(P=>{P[0].UDb=d;return q}):_.Bg(q)});var E=A.then(N=>N.fOc);A.then(N=>{N.ccc.length>0&&Pob(a,N.ccc,b)})}else E=Tob(a,b,c,g,l),Object.assign(q,E.gOc),
k.push(...E.ccc),E=E.fOc;const I=Iob(c);(A=c.Eca())?A.update(0,I,l,d,h,g,c.Ca,q,r,e):A=new Gob(f,I,l,d,h,g,c.Ca,q,r,e);e=zob(f,A,b,a.jr(),E,u);A.Qa=e;return{qua:A,z2a:k}};Pob=function(a,b,c){const d=Uob(a,b),e=_.uh(c,d);_.Ka(b,function(f){f.start.call(this,e)},a)};Uob=function(a,b){const c={};_.Ka(b,function(d){_.xc(d.rGb,(e,f)=>{c[d.vBd+"|"+f]=e},this)},a);return nob(c)};
Qob=function(a,b,c){const d={},e=b.xq.Qa();if(_.Dc(e))return d;const f=b.La||{},g=Iob(b),h=b.Ba;_.xc(e,(k,l)=>{if(!f[l]){var p=void 0;typeof k==="function"?p=k(g,c,h):p=k;p!==void 0&&(d[l]=p)}},a);return d};
Rob=function(a,b,c,d,e){let f;f=d?_.Bg(d(b)):_.Bg({});if(Object.keys(c).length==0)return{OPc:f,vPc:null};const g={};return{OPc:new _.Lg(h=>{g.rGb=c;g.vBd=e;g.start=k=>{k=k.then(l=>uob(e,l));h(_.zh([f,k]).then(l=>{const p=l[0];l=l[1];const q={};for(let r in l)for(let u in l[r])q[u]=l[r][u];_.Tja(q,p);return q}))}},a),vPc:g}};
Sob=function(a,b,c){return b.then(d=>{var e=a.Da(d,c);const f=e.Lf;(d=a.oa())&&d.length>0&&f.concat(d.map(g=>g.oa));d=Promise.resolve();d=_.sOa(_.COa(_.Rf.getInstance()),f);e=Object.keys(e.Nf);e=e.length===1?e[0]:"not exist";return{hAd:_.zh(Object.values(d)),gAd:e}})};
Tob=function(a,b,c,d,e,f){const g=new Map,h={},k=[],l=c.xq.getChildren();let p=1;for(const I in l){if(f&&I!==f)continue;var q=l[I];const N=q.name;g.set(N,I);var r=q.Wq(Iob(c),d,e);if(!Vob(a,r))continue;q=a;var u=p,A=b,E=c.Ba;c.xq.getName();q=r.repeated?Wob(q,A,r,u):r.recursive?Xob(q,A,r,u):Yob(q,A,r,u,E);const {qua:P,z2a:T}=q;P&&(h[N]=P,p+=1,k.push(...T))}return{gOc:h,ccc:k,fOc:g}};
Vob=function(a,b){const c=b.p8!=null?b.p8:!0,d=!!b.mJa&&b.mJa.length>0,e=!!b.AOb&&b.AOb.length>0;let f=!1;b.mJa&&b.mJa.length>0&&(f=_.Mi(b.mJa,function(h){return this.Ba.get(h).bool()},a));let g=!1;b.AOb&&b.AOb.length>0&&(g=_.Mi(b.AOb,function(h){return this.Ca.oa(h)},a));return d||e?c&&(f||g):c};
Wob=function(a,b,c,d){return{qua:c.Jz(a).then(function(e){let f,g;const h=_.Cc(e);e.Fya?(f=e.Fya||[],g=_.xa(h,k=>e[k]==f)):(g=h[0],f=e[g]||[]);return _.Li(f,function(k,l){const p=_.Ija(e,q=>!Array.isArray(q));p[g]=k;k=Kob(this.jF(c.id,c.Mc),()=>p,c.Ul);({qua:l}=Oob(this,b,k,`${d};${l}`,c));return l},this)},void 0,a),z2a:[]}};Xob=function(a,b,c,d){return{qua:c.Jz(a).then(e=>vob(e)?Yob(a,b,c,d).qua:_.Bg([])),z2a:[]}};
Yob=function(a,b,c,d,e){e=Kob(_.Job(a.jF(c.id,c.Mc),e),c.Jz,c.Ul);a=Oob(a,b,e,`${d};0`,c);return{qua:_.Bg([a.qua]),z2a:a.z2a}};
_.Nr=class extends _.fo{static Ta(){return{service:{Jvb:_.lob,GAd:_.hob}}}constructor(a){super();this.Ba=a.service.Jvb;this.Ca=a.service.GAd;this.wm=null;this.oa=0}Eca(a){return _.Cob(a,this)}jF(a,b){return new Mob(a,this,b)}fetch(a,b,c,d,e){this.oa=0;a=_.Job(this.jF(a,c).Aa(d),e);b=_.Lob(this,b,[a])[0];return _.yob(b)}Aia(a){return _.GOa(_.Rf.getInstance(),Nob(this,a,!0))}Aa(a,b){return this.jF(a,b)}jDb(a,b,c,d){const e=Nob(this,a);_.GOa(_.Rf.getInstance(),e);const {qua:f,z2a:g}=Oob(this,b,this.Aa(a,
c),"0;0");_.Eob(f,d);let h=0;_.Ka(g,function(l){_.xc(l.rGb,()=>{h++},this)},this);a=Uob(this,g);const k=_.uh(b,a);_.Ka(g,l=>{l.start(k)});return f}};_.Yf(_.Aq,_.Nr);
_.x();
var v1b=class extends _.m{constructor(a){super(a)}Da(){return _.B(this,2)}Aa(){return _.B(this,3)}zc(){return _.B(this,5)}Fc(){return _.B(this,6)}qc(){return _.B(this,54)}Ec(){return _.B(this,58)}Hc(){return _.B(this,59)}Ha(){return _.B(this,9)}od(){return _.B(this,11)}Yx(){return _.B(this,80)}Kb(){return _.B(this,52)}Cb(){return _.B(this,55)}getTitle(){return _.t(this,19)}setTitle(a){return _.$g(this,19,a)}wd(){return _.lh(this,19)}Zt(){return _.t(this,24)}Ba(){return _.Fj(this,71,_.kh())}Qa(){return _.B(this,
28)}Xd(){return _.B(this,30)}Af(){return _.B(this,31)}Lb(){return _.zj(this,32)}nC(){return _.t(this,33)}Fd(){return _.B(this,48)}oH(){return _.B(this,76)}we(){return _.B(this,65)}Le(){return _.B(this,66)}Ld(){return _.B(this,50)}Zh(){return _.B(this,51)}Xa(){return _.zj(this,38)}Za(){return _.zj(this,39)}ub(){return _.zj(this,40)}rb(){return _.zj(this,41)}Wb(){return _.zj(this,42)}Wa(){return _.zj(this,43)}Tb(){return _.B(this,44)}Qb(){return _.B(this,46)}Ca(){return _.B(this,47)}Xc(){return _.B(this,
61)}Sa(){return _.B(this,62)}La(){return _.B(this,63)}Fh(){return _.B(this,64)}Vc(){return _.B(this,70)}Pa(){return _.B(this,72)}Tt(){return _.B(this,73)}Ma(){return _.B(this,74)}nK(){return _.B(this,78)}Ib(){return _.t(this,77)}Nd(){return _.B(this,81)}Ig(){return _.B(this,82)}Jf(){return _.B(this,83)}Ng(){return _.zj(this,84)}},w1b=[0,[29,36],1,_.C,-1,1,_.C,-1,2,_.C,1,_.C,7,_.D,4,_.D,3,_.C,_.zl,_.C,-1,_.G,_.D,2,_.Cl,[0,_.Xk,_.D],1,_.G,-5,_.C,1,_.C,-2,1,_.C,-2,1,_.C,-1,2,_.C,-1,1,_.C,-5,3,_.C,_.xl,
_.C,-2,[0,_.D,-4,_.G,_.D,-1],_.C,_.D,_.C,[0,[2,3],[0,_.D,-1,_.G,_.Zk,_.G],_.cl,-1,_.D],_.C,-3,_.G];_.Sw=class extends _.m{constructor(a){super(a)}Aa(){return _.jh(this,v1b,1,_.kh())}Ba(){return _.B(this,9)}};_.Sw.prototype.kb="yxsBx";_.x1b=[0,_.F,w1b,4,_.Bn,_.D,_.G,_.C,[0,_.D,1,_.D,_.C,_.wo,-1,_.D,_.G]];
_.SHc=class extends _.m{constructor(a){super(a)}L2(){return _.zj(this,8)}};
_.RHc=_.y("M8IzD",[_.Aq,_.Vq]);
_.Qr=_.y("q0xTif",[_.VWa,_.Aq,_.t2a]);
_.GHc=_.y("H44aUc",[_.Qr]);
_.Isc=_.y("XqvtHd",[_.Qr]);
_.Hsc=class extends _.m{constructor(a){super(a)}};_.Hsc.prototype.kb="lPgjzd";new _.pi(_.Hsc);_.Uo.lPgjzd=_.To;
var x7b=class extends _.m{constructor(a){super(a)}};_.y7b=class extends _.m{constructor(a){super(a)}};_.A7b=class extends _.m{constructor(a){super(a)}jr(){return _.Hh(this,x7b,1,_.z7b)}Aa(){return _.Xi(this,x7b,1,_.z7b)}Ba(){return _.Xi(this,_.y7b,2,_.z7b)}};_.z7b=[1,2,4];
var B7b;_.Ix=function(a){return _.wj(a,3)};B7b=class extends _.m{constructor(a){super(a)}};_.C7b=function(a){return _.t(a,2)};_.D7b=class extends _.m{constructor(a){super(a)}};_.E7b=function(a){return _.n(a,_.D7b,2)};_.F7b=function(a){return _.wj(a,4)};_.G7b=function(a){return _.wj(a,5)};_.H7b=class extends _.m{constructor(a){super(a)}};_.I7b=function(a){return _.Uh(a,1)};_.Jx=function(a){return _.Uh(a,2)};_.Kx=function(a){return _.n(a,_.H7b,3)};_.J7b=function(a){return _.n(a,_.ch,4)};_.K7b=class extends _.m{constructor(a){super(a)}};_.Lx=function(a){return _.Vh(a,6)};_.L7b=class extends _.m{constructor(a){super(a)}getTitle(){return _.n(this,_.Zg,1)}setTitle(a){return _.Kb(this,_.Zg,1,a)}wd(){return _.Vi(this,_.Zg,1)}getImageUrl(){return _.n(this,_.ch,12)}Aa(){return _.kj(this,_.ch,12)}};_.M7b=function(a){return _.Uh(a,5)};_.Mx=function(a){return _.n(a,_.L7b,1)};_.Nx=function(a){return _.n(a,_.K7b,2)};_.Ox=function(a){return _.n(a,B7b,4)};_.N7b=class extends _.m{constructor(a){super(a)}};var O7b=class extends _.m{constructor(a){super(a)}sUa(){return _.Sj(this,1)}Ww(){return _.n(this,_.A7b,6)}Jq(){return _.Tj(this,11)}};_.P7b=class extends _.m{constructor(a){super(a)}AA(){return _.ah(this,3)}};_.Q7b=class extends _.m{constructor(a){super(a)}};_.R7b=class extends _.m{constructor(a){super(a)}};_.Px=function(a){return _.jh(a,_.N7b,1,_.kh())};_.Qx=function(a){return _.n(a,O7b,2)};_.S7b=class extends _.m{constructor(a){super(a)}};_.S7b.prototype.kb="pJTLoe";new _.pi(_.S7b);_.Uo.pJTLoe=_.To;
var tBb;_.iu=function(a){return(b,c,d)=>{b=a(b,c,d);if(!b)return b;b.metadata.l9d=!0;return b}};tBb=function(a){a.oa||(a.oa=new _.Hq);return a.oa};_.ju=class{constructor(){this.oa=null}monitor(a){tBb(this).promise.then(a)}notify(){tBb(this).resolve()}};
var mBb;_.du=function(a){return new mBb(a)};
mBb=class{constructor(a){this.Ma=a.Uf||!1;this.Aa=a.name;this.xq=a.Tf;this.Ia=a.data;this.Ha=a.children;this.Ca=a.hg;a.params?typeof a.params==="function"&&(a.params={ctor:a.params}):a.params={ctor:_.Lr};this.La=a.params;this.Sa=a.dg||(()=>({variant:null,Lf:[],Nf:[]}));this.Ba=a.lkb||!1;this.Pa=a.Yf||{}}getName(){return this.Aa}Da(a,b){if(!this.Ba)return{variant:null,Lf:[],Nf:[]};b=this.Sa(a,b);for(const d of Object.keys(b.Nf)){const e=b.Nf[d];var c=this.Pa[d]||{};const f={};let g=!1;for(const h of Object.keys(c))f[h]=
c[h](a),Array.isArray(f[h])&&(g=!0);if(g){const h=Object.keys(f).find(k=>Array.isArray(f[k]));c=f[h].map(k=>{const l=Object.assign({},f);l[h]=k;return e(l,void 0).Lf});b.Lf.push(...c)}else b.Lf.push(...e(f,void 0).Lf)}return b}lkb(){return this.Ba}Qa(){return this.Ia||{}}getChildren(){return this.Ha||{}}getParams(){return this.La}oa(){return this.Ca?this.Ca:null}toString(){return"ComponentId<"+this.Aa+">"}};_.gu=_.sDa;
var Jsc=class extends _.m{constructor(a){super(a)}Jh(){return _.ah(this,3)}Ho(){return _.wj(this,3)}};Jsc.prototype.kb="HIbR3";new _.pi(Jsc);new _.pi(_.S7b);_.Uo.pJTLoe=_.To;var Ksc=new _.ci("TD9dLc",_.S7b,Jsc,[_.ai,!0,_.$h,"/WhyThisAdDataService.WhyThisAdContext"]);var Lsc=class extends _.m{constructor(a){super(a)}};Lsc.prototype.kb="NWEFRc";new _.pi(Lsc);new _.pi(_.Hsc);_.Uo.lPgjzd=_.To;var Msc=new _.ci("BONMwf",_.Hsc,Lsc,[_.ai,!0,_.$h,"/AdsSettingsUserInfoDataService.AdsSettingsRelatedProducts"]);_.Nsc=()=>({variant:null,Lf:[],Nf:{}});_.Osc=class extends _.m{constructor(a){super(a)}Jh(){return _.t(this,3)}Ho(){return _.wj(this,3)}L2(){return _.zj(this,10)}};_.Psc=_.du({Uf:!1,name:"b2zFDf",Tf:_.Isc,params:{ctor:_.Osc},hg:[],data:{context:function(a,b,c){b=c||{};c=b.vk||"rpc";var d=new Jsc;if(_.lh(a,6)){var e=_.t(a,6);_.$g(d,5,e)}_.lh(a,5)&&(e=_.t(a,5),_.$g(d,4,e));_.lh(a,15)&&(e=_.t(a,15),_.$g(d,8,e));_.lh(a,2)&&(e=_.t(a,2),_.$g(d,2,e));_.lh(a,12)&&(e=_.t(a,12),_.$g(d,6,e));_.lh(a,3)&&(e=a.Jh(),_.$g(d,3,e));_.lh(a,1)&&(a=_.t(a,1),_.$g(d,1,a));a={fatal:!0,Wt:[{key:_.Jr,value:new _.ju},{key:_.Kr,value:new _.ju}]};let f;for(f in b)a[f]=b[f];return{Oo:Ksc,
vk:c,Rs:d,metadata:a}},yF:function(a,b,c){if(a.L2()==1){a=c||{};b=a.vk||"rpc";c=new Lsc;var d={fatal:!0,Wt:[{key:_.Jr,value:new _.ju},{key:_.Kr,value:new _.ju}]};let e;for(e in a)d[e]=a[e];return{Oo:Msc,vk:b,Rs:c,metadata:d}}}},dg:_.Nsc,Yf:{},children:{}});
_.HHc=function(a,b){return _.$g(a,2,b)};_.IHc=function(a,b){return _.$g(a,3,b)};_.JHc=function(a,b){return _.Qh(a,10,b)};_.KHc=function(a,b){return _.Kb(a,_.ch,4,b)};_.LHc=function(a,b){return _.Kb(a,_.ch,9,b)};_.MHc=function(a,b){_.$g(a,12,b)};_.NHc=_.du({Uf:!1,name:"o3ebOd",Tf:_.GHc,params:{ctor:_.Osc},hg:[],data:{},dg:()=>({variant:null,Lf:[],Nf:{SGc:_.Nsc}}),Yf:{SGc:{}},children:{SGc:{id:_.Psc,name:"SagRuf",Wq:function(a){var b=new _.Osc;_.Vi(a,_.ch,9)&&_.LHc(b,a.Of()?_.ij(a,_.ch,9,_.gu):_.kj(a,_.ch,9));_.Vi(a,_.ch,4)&&_.KHc(b,a.Of()?_.ij(a,_.ch,4,_.gu):_.kj(a,_.ch,4));if(_.lh(a,8)){var c=_.t(a,8);_.$g(b,8,c)}_.lh(a,6)&&(c=_.t(a,6),_.$g(b,6,c));_.lh(a,5)&&(c=_.t(a,5),_.$g(b,5,c));_.lh(a,2)&&_.HHc(b,_.t(a,2));_.lh(a,12)&&_.MHc(b,_.t(a,
12));_.lh(a,3)&&_.IHc(b,a.Jh());_.Fk(a,10)&&_.JHc(b,a.L2());_.lh(a,1)&&(a=_.t(a,1),_.$g(b,1,a));return{Mc:b,id:_.Psc,name:"SagRuf"}}}}});
_.s7b=_.y("OlGQO",[_.Qr]);
_.t7b=_.du({Uf:!1,name:"HXzY2c",Tf:_.s7b,params:{ctor:_.Lr},hg:[],data:{},dg:()=>({variant:null,Lf:[],Nf:{}}),Yf:{},children:{}});
_.v("M8IzD");
var THc=function(a){return _.He(a,_.SHc,10)},UHc=_.Yb(_.Sw),VHc=class extends _.m{constructor(a){super(a)}};VHc.prototype.kb="svcCQe";var XHc=function(a,b,c){const d=c?THc(UHc(b.data)):a.Da;b.event&&!c&&(b.event.preventDefault(),b.event.stopPropagation());b.wb.el()&&_.Ge(b.wb.el())&&_.Ip(a.Pb.oa(),b.wb.el()).log(!0);if(!a.oa&&!a.Ba){a.oa=!0;var e=a.yd?a.Ka("I3OyF").el():a.Ka("oDTRPe").el();if(a.Aa||c){for(;e.firstChild;)e.removeChild(e.firstChild);a.Aa=!1}if(a.Ca&&!c)WHc(a),a.oa=!1;else{var f=new _.Osc;_.MHc(_.LHc(_.KHc(_.JHc(_.IHc(_.HHc(f,_.wj(d,1)),(g=>{switch(g){case 15:return"localservices";case 7:return"pla";case 10:return"css";
case 12:return"searchpla";default:return"searchad"}})(_.Xj(d,8))),_.Vh(d,8)),_.Vi(d,_.ch,5)?_.n(d,_.ch,5):_.dh(_.qc("https://adssettings.google.com"))),_.Vi(d,_.ch,6)?_.n(d,_.ch,6):_.dh(_.qc("https://adssettings.google.com/authenticated"))),_.lh(d,7)?_.t(d,7):"https://www.google.com");_.qg(a.Kf.jF(_.NHc,f).fetch().then(g=>{e.appendChild(g.render());WHc(a);a.Ca=!0}).catch(g=>{a.Ba=!0;_.qg(a.Kf.jF(_.t7b,null).fetch().then(h=>{e.appendChild(h.render());WHc(a);a.Aa=!0}),()=>{a.Ba=!1});_.df(Error("gg`"+
f.Jh()+"`"+_.t(f,2).length+"`"+g),{level:1})}),()=>{a.oa=!1})}}},WHc=function(a){a.yd?a.Uc("vf4JOc",_.Ao).then(b=>{b.open()}):a.Uc("vbrkHb",_.Ao).then(b=>{b.open()})},YHc=class extends _.as{static Ta(){return{jsdata:{rvd:VHc},service:{Kf:_.Nr,Pb:_.Ku}}}constructor(a){super();this.Ca=this.Aa=this.Ba=this.oa=!1;const b=a.jsdata.rvd;this.Da=_.n(b,_.SHc,1);this.yd=_.B(b,2);this.Kf=a.service.Kf;this.Pb=a.service.Pb}Ia(a){XHc(this,a,!0)}Ha(a){XHc(this,a,!1)}};YHc.prototype.$wa$IwCZH=function(){return this.Ha};
YHc.prototype.$wa$AlF6be=function(){return this.Ia};_.cs(_.RHc,YHc);
_.x();
});
// Google Inc.
