loaded_h_0(function(_){var window=this;
_.cWb=_.y("rtH1bd",[_.q7a]);
var YVb,ZVb;_.XVb=function(a){return JSON.stringify(a,(b,c)=>c instanceof Map?Object.fromEntries(c):c)};YVb=function(a,b,c,d){const e=()=>d?a.pop(d,!0):_.yh(),f=()=>c!==d;return b?{ilc:e,xQc:f,Hyc:2}:{ilc:e,xQc:f,V4a:()=>c?a.pop(c,!0):_.yh(),Hyc:6}};ZVb=function(a,b){return{ilc:()=>a.Aa(b.aD())||_.yh(),xQc:()=>!0,Hyc:2}};_.$Vb=a=>new _.au(a);_.$Vb=a=>new _.bu(a);_.aWb=class{constructor(){this.oa=new Map}and(a,...b){return a.call(null,...b,this)}};_.bWb=class{constructor(a,b,c){this.Aa=c;this.converters=a;this.oa=b}fSa(a,{u_a:b={},qfa:c}={}){const d=this.oa.getState()||{id:"",pushId:""};var e=this.Aa||d;e={url:_.$Vb(e.url||""),state:e.userData||null};const f=e.url.toString(),g=_.XVb(e.state);for(const k of this.converters.keys())if(a.has(k)){const l=a.get(k);this.converters.get(k).wp(l,e)}const {replace:h=!1}=b;if(f===e.url.toString()&&g===_.XVb(e.state))return _.Bg(YVb(this.oa,h,d.id,d.id));this.Aa&&(this.Aa.url=e.url.toString(),this.Aa.userData=
e.state);if(!b.Iif)return c?(a=this.oa.navigateToView(e.url.toString(),e.state||void 0,c.Bpa,h,c.event))?a.then(k=>ZVb(this.oa,k)):_.yh(Error("Bf`"+e.url)):this.oa.pushAsync(e.url.toString(),e.state||void 0,void 0,h,this.oa).then(k=>YVb(this.oa,h,d.id,k))}static compose(...a){const b=new Map;let c,d;for(const e of a){for(const f of e.converters.keys())b.delete(f),b.set(f,e.converters.get(f));c=e.oa;d=e.Aa}return new _.bWb(b,c,d)}};
_.v("rtH1bd");
var dWb,fWb,hWb,jWb,kWb,lWb,mWb,nWb,oWb;dWb=function(a,b=[]){b.push(a);return b};_.eWb=function(a,b){const c=new Map;for(const e of a)for(const f of e.keys()){a=f;var d=e.get(f);d=b?b(d,c.get(a)):d;c.set(a,d)}return c};fWb=function(a,b){const c=new Map;for(const d of a.keys())c.set(d,b(a.get(d),d));return c};_.gWb=function(a){return _.mg(a)?a:{}};hWb=function(a,b){const c=b.reduce((d,e)=>d|(e&&e.Hyc||0),1);return Object.assign({state(d){return(a.get(d)||new d).clone()},dBb(d){return(c&d)===d}},...b)};
jWb=function(a,b=iWb){return{getCurrent:a.getCurrent||b.getCurrent,Lza:new Set([...b.Lza,...a.Lza]),x$a:a.x$a||b.x$a}};kWb=function(a){a=_.eWb(a,dWb);return fWb(a,(b,c)=>c.compose(...b))};lWb=function(a){const b=[];for(const c of a)(a=c())&&b.push(a);return b.length?_.zh(b):null};mWb=function(a,b){const c=new Set,d=new Set([...a.keys(),...b.keys()]);for(const e of d)_.Ja(a.getAll(e),b.getAll(e))||c.add(e);return c};
nWb=function(a,b){var c;if(c=!!a&&!!b)a:{a.size>b.size&&([a,b]=[b,a]);for(const d of a)if(b.has(d)){c=!0;break a}c=!1}return c};oWb=function(a=new _.aWb){a.oa.set(_.bWb,null);return a};var iWb;iWb={Lza:new Set};_.qWb=function(...a){const b=[];var c=[],d=[];let e;for(const f of a)b.push(f.Tn),c.push(f.fT),d.push(f.uuc),e=f.zub||e;a=_.eWb(b,jWb);c=kWb(c);d=kWb(d);return new _.pWb(a,c,d,e)};
_.pWb=class{constructor(a=new Map,b=new Map,c=new Map,d){this.Tn=a;this.fT=b;this.uuc=c;this.zub=d}run({Aa:a,eventType:b,metadata:c,oa:d}=new _.aWb){const e=new Map;for(const h of this.Tn.keys()){const k=this.Tn.get(h);let l,p,q,r=(q=(p=(l=k).getCurrent)==null?void 0:p.call(l))!=null?q:new h;var f=null;for(const u of k.Lza){const A=u;if(A.sdd){if(!A.sdd(r.clone(),a))continue;f=A.Kie}else f=u;f=r=f(r,a)}if(f){e.set(h,f);let u,A;(A=(u=k).x$a)==null||A.call(u,f)}}a=[];for(var g of this.fT.keys()){const h=
this.fT.get(g),k=d.get(g);k!==null&&a.push(()=>h.fSa(e,k))}d=h=>{b=b||this.zub;const k=[],l=hWb(e,h);for(const p of this.uuc.values())k.push(()=>p.notify(e,b,c,l));return(h=lWb(k))?h.then(()=>l):_.Bg(l)};return(g=lWb(a))?g.then(d):d([])}compose(...a){return _.qWb(this,...a)}};_.rWb=class extends _.fo{static Ta(){return{service:{bHc:_.uIb}}}constructor(a){super();this.Ba=[];this.Aa=a.service.bHc;a=this.Aa.getState()||{};this.oa={url:a.url,userData:a.userData,id:"",pushId:""};this.Aa.addListener((b,c,d)=>{if(!(d.source instanceof _.uIb)){if(b.url!==this.oa.url){var e=new _.au(b.url||"");c=new _.au(this.oa.url||"");var f=mWb(e.searchParams,c.searchParams);e=mWb(e.oa,c.oa)}c=_.gWb(b.userData);var g=_.gWb(this.oa.userData);if(c===g)var h=new Set;else{var k=new Set,l=new Set([...Object.keys(c),
...Object.keys(g)]);for(h of l)_.XVb(c[h])!==_.XVb(g[h])&&k.add(h);h=k}this.oa.url=b.url;this.oa.userData=b.userData;c={url:_.$Vb(b.url||""),state:b.userData};b=[];for(const {vId:p,aRd:q}of this.Ba)g=new Set,k=new Set,l=new Set,q.oa&&(q.oa.k6&&(g=new Set(q.oa.k6())),q.oa.pC&&(k=new Set(q.oa.pC()))),q.Aa&&(l=new Set(q.Aa.keys())),(nWb(g,f)||nWb(k,e)||nWb(l,h))&&b.push(p(c));b.length&&(f=d.e6&&d.e6.length?1:0,d=d.source instanceof _.Fgb,e=_.qWb(...b),b=e.run,h=new _.aWb,h.metadata={reason:f,userInitiated:d},
b.call(e,h.and(oWb)))}})}};_.Yf(_.cWb,_.rWb);
_.x();
_.wmr=null;
var cjd,gjd;_.djd=function(){cjd.set(_.cu().toString(!0),_.ym())};_.ejd=function(){return cjd.get(_.cu().toString(!0))};_.fjd=function(){const a=_.ejd();a&&_.YD.fixedUiScrollTo(a.x,a.y)};_.hjd=function(){gjd||(gjd=_.me(document.documentElement,"touchmove",_.tJa));document.body.style.overflow="hidden"};_.ijd=function(){gjd&&(_.nn(gjd),gjd=null);document.body.style.overflow=""};_.jjd=function(a){a&&_.YD.Ca(0,a)};cjd=_.tg("s",_.tNa);_.kjd=null;gjd=null;_.me(window,"popstate",function(){_.kjd=_.ym()});
var sjd,zjd,Hjd,rjd,Njd,Pjd,Ijd,Tjd,Vjd,Gjd,Rjd,Xjd,pjd,qjd,Ojd,Qjd,wjd,Ajd,Sjd,Bjd,ojd,Fjd,Ljd,Ujd,xjd;_.ljd=function(a,b,c){_.djd();b=b||{};b.fpstate=a;_.zg(b,c)};_.njd=function(a){_.mjd(!0,a)};_.mjd=function(a,b){const c={};_.Ka(b||[],d=>{c[d]=""});c.fpstate="";_.zg(c,a)};
_.vjd=function(a,b){ojd++;if(window.getSelection){const f=window.getSelection();f&&f.removeAllRanges()}let c=!1,d=!1;_.Ka(a,f=>{if(f===1)_.Dg("trex")?d=!0:c=!0;else{var g=_.Gg(f);if(g!==document.body){var h=f["fp-s"];h||(h=_.Cm("DIV"),f["fp-s"]=h);g?_.Hm(h,f):(g=_.Gg(h))&&g.removeChild(h);_.DJc(f,f);document.body.appendChild(f)}_.Rm(f,{"margin-top":-_.YD.getHeaderPaddingHeight()+"px","margin-bottom":-_.YD.getFooterPaddingHeight()+"px"});f["fp-i"]=ojd;_.mm.remove(f,"fCjVlb");_.uJc(f,"t3L5Dd")}});_.Ka(document.body.children,
f=>{if(!(pjd.has(f.tagName)||qjd.test(f.id)||f.id==="lb"||f["fp-i"]===ojd||f.hasAttribute("data-imig")))if(_.mm.remove(f,"r3xA2d"),f&&f["fp-i"]>0){rjd(f);const g=f["fp-s"];g&&f&&f["fp-i"]>0&&(g.parentNode?(_.Hm(f,g),_.Jm(g)):_.Jm(f));f.parentNode!==document.body||_.mm.add(f,"fCjVlb")}else _.mm.enable(f,"fCjVlb",!c),f&&f.id.startsWith("trex_")&&_.mm.enable(f,"fCjVlb",!d)});let e;((e=google)==null?0:e.uh)?google.uh("fpstate"):_.dn(document.body,"");b!==!1&&(c&&!sjd()?_.tjd():_.ujd())};
sjd=function(){const a=_.mm.contains(document.body,"qs-i"),b=!!_.Dg("istate"),c=!!_.Dg("trex"),d=_.Dg("oshop")==="apv";return a||c||b||d};zjd=function(a){if(a===wjd)return xjd;let b=_.yjd[wjd+"\n"+a];return b?b:wjd==="&"?xjd:(b=_.yjd["*\n"+a])?b:(b=_.yjd[wjd+"\n*"])?b:xjd};
Hjd=function(a){var b=Ajd;b=b===1?b:b;if(Bjd!==1){var c=Bjd;c.style.top="";_.mm.remove(c,"ca1MEe")}_.vjd([b],!1);(c=_.Cjd.get(wjd))&&c.Dra&&c.Dra.call(null);if(c=b===1?null:b)_.mm.add(document.body,"QjZ1Sd"),_.mm.add(c,"ca1MEe"),_.mm.remove(c,"r3xA2d"),c.focus();if(_.Djd){const f=_.Djd;var d=f.x,e=f.y+_.YD.getScrollTop();_.YD.fixedUiScrollTo(d,e);c&&(f.x&&(c.style.left=""),f.y&&(c.style.top=""))}else _.Ejd!==1&&(c=_.YD.getScrollTop(),_.YD.fixedUiScrollTo(0,c));_.Djd=null;b!==1||sjd()?_.ajd||_.mla||
_.lla||_.ujd():_.tjd();wjd=a;Bjd=b;Ajd=null;Fjd&&(_.nn(Fjd),Fjd=null);_.ijd();Gjd();(a=_.Cjd.get(a))&&a.Bmb&&a.Bmb.call(null)};_.tjd=function(){if(_.kla)_.YD.oa(1);else{const a=_.bg(document);_.Xf(_.Tu,a.jr()).then(b=>{b&&b.isAvailable()&&b.exitBasicMode(12)})}};_.ujd=function(){if(_.kla)_.YD.oa(3);else{const a=_.bg(document);_.Xf(_.Tu,a.jr()).then(b=>{b&&b.isAvailable()&&b.enterBasicMode(12)})}};rjd=function(a){_.Rm(a,{"margin-top":"","margin-bottom":""})};
Njd=function(a){if(a===""){_.Dg("istate")&&_.Ag("istate",_.Dg("istate"),!0);var b=_.cu().pathname();b!=="/search"&&(b=Ijd(b))&&(b=_.Jjd.get(b))&&(a=b.state)}a!==_.Kjd&&(_.Kjd=a,a===""||_.Cjd.has(a))&&(Ljd?(b=()=>void _.Mjd(a),Ljd.promise.then(b,b)):_.Mjd(a))};Pjd=function(a){return a&&(a=Ojd.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};Ijd=function(a){return(a=Qjd.exec(a))&&a[1]?decodeURIComponent(a[1].replace(/\+/g," ")):""};
Tjd=function(a){a=a.Ph;const b=Pjd(a.newURL);if(b===_.Kjd){const c=Pjd(a.oldURL);/#(.*&)?trex=/.test(a.oldURL)||c===b||Rjd()||!Sjd||(a=Sjd,_.YD.fixedUiScrollTo(a.x,a.y))}};_.Mjd=function(a){if(wjd==="&"&&a==="")wjd=a;else if((0,_.Un)(new Ujd),a==="")Vjd(a,1),_.uJc(document.body,"ABuafc");else{wjd===""&&_.uJc(document.body,"hcY69");var b=_.Cjd.get(a);if(b&&(b=b.Xda.call(null,wjd))){_.Kg(b)?Vjd(a,b):b.then(c=>{Vjd(a,c)},()=>{Gjd()});return}Gjd()}};
Vjd=function(a,b){const c=zjd(a),d=typeof c.transitionType==="function"?c.transitionType(wjd,a,c.zEc):c.transitionType;var e=b===1;const f=d!==1||Bjd===1?null:Bjd,g=d!==0||b===1?null:b;Ajd=b;_.Ejd=d;Sjd=_.ym();if(f){const k=Sjd;Wjd(f,b);f.style.top=_.YD.getScrollTop()-k.y+"px"}g&&Wjd(g,Bjd);e&&_.mm.remove(document.body,"QjZ1Sd");!e&&(_.ajd||_.mla||_.lla)&&_.ujd();Fjd||(Fjd=_.me(document.documentElement,"touchstart",_.tJa));_.hjd();if((e=_.Cjd.get(a))&&e.onReady)try{e.onReady.call(null)}catch(k){Xjd(k);
return}d===1?_.fjd():d===0&&a!==""&&wjd!==""&&(_.Djd=_.ejd(),Sjd=null);let h;try{h=c.zEc.call(null,Bjd,b)}catch(k){}h?(h.then(()=>{Hjd(a)},k=>{Hjd(a);throw k;}),g&&_.Djd&&(b=_.Djd,b.x&&(g.style.left=-b.x+"px"),b.y&&(g.style.top=-b.y+"px"))):Hjd(a)};Gjd=function(){Ljd&&(Ljd.resolve(),Ljd=null)};Rjd=function(){if(_.Ejd!=null){var a=_.Ejd===1;if(_.Djd){if(a||Ajd===1){var b=_.Djd;a=b.x;b=b.y+_.YD.getScrollTop();_.YD.fixedUiScrollTo(a,b);return!0}}else if(a)return!0}return!1};
Xjd=function(a){_.Ejd=Ajd=null;_.vjd([Bjd]);Fjd&&(_.nn(Fjd),Fjd=null);_.ijd();Gjd();throw a;};pjd=new Set(["SCRIPT","STYLE"]);qjd=RegExp("^(abbl|abblt|gbbl-\\d+|gbblt-\\d+|snbc|duf3c)$");Ojd=/#(?:.*&)?fpstate=([^&]*)/;Qjd=/^\/?([^\/]*)/;_.Cjd=new Map;_.Jjd=new Map;wjd="&";_.Kjd="&";Ajd=null;Sjd=null;_.Djd=null;_.yjd={};_.Ejd=null;Bjd=1;ojd=0;Fjd=null;Ljd=null;Ujd=class{constructor(){this.W5a=void 0;Ljd=_.Af()}play(){return Ljd?Ljd.promise:Promise.resolve()}finish(){Gjd()}Qm(){return 2E3}};
xjd={zEc:function(){return _.Bg()},transitionType:0};_.Aoa(()=>{_.vg("fpstate",Njd);_.me(window,"hashchange",Tjd)});var Wjd=function(a,b){_.vjd([a,b],!1);rjd(a);_.mm.add(a,"r3xA2d")};
_.Fw=function(a,b=new _.aWb){const c=b.oa.get(_.bWb)||{};c.u_a=a;b.oa.set(_.bWb,c);return b};
var uWb,yWb,AWb,BWb,CWb;uWb=function(a,b=new Set){for(const c of a)b.add(c);return b};_.vWb=function(a,b){return b};_.wWb=function(a,b=new _.aWb){b.Aa=a;return b};_.pw=function(){return _.Xf(_.rWb)};_.xWb=function(a,b,c,d){return new _.bWb(new Map([[a,b]]),c,d)};
yWb=class{constructor(a=new Map){this.oa=a}notify(a,b,c,d){for(const e of a.keys())if(this.oa.has(e))for(const f of this.oa.get(e))try{f(a.get(e).clone(),b,c,d)}catch(g){_.fa(g)}}static compose(...a){const b=[];for(const c of a)b.push(c.oa);a=_.eWb(b,uWb);return new yWb(a)}};
_.zWb=function(a,{getCurrent:b,Lza:c=[],x$a:d,fT:e=[],listeners:f=[],uuc:g=[],zub:h}={}){const k=new Map;for(const l of e)k.set(l.constructor,l);e=new Map;f&&e.set(yWb,new yWb(new Map([[a,new Set([...f])]])));for(const l of g)e.set(l.constructor,l);return new _.pWb(new Map([[a,{getCurrent:b,Lza:new Set(c),x$a:d}]]),k,e,h)};
_.qw=class{constructor(a,b,c={}){this.oa=a;this.Aa=b;this.Ba=c.LTb||(d=>_.mg(d)?d:{});this.Ca=c.h2b||((d,e)=>e)}Bo(a,b){this.oa&&this.oa.Bo&&this.oa.Bo(a.url,b);this.Aa&&this.Aa.Bo(this.Ba(a.state),b)}wp(a,b){this.oa&&this.oa.wp&&this.oa.wp(a,b.url);if(this.Aa){const c=Object.assign({},this.Ba(b.state));this.Aa.wp(a,c);a=Object.assign({},_.mg(b.state)?b.state:{});b.state=this.Ca(a,c)}}};AWb=function(a){const b=a.Aa.getState()||{};return{url:_.$Vb(a.Aa.getCurrentUrl()),state:b.userData}};
BWb=function(a,b){a.Ba.push(b)};
_.rw=function(a,b,c){const d=b.Br();b.Da(_.xWb(d,c,a.Aa,a.oa));b.Pa(h=>{const k=AWb(a);c.Bo(k,h)});let e=!1;const f=new d,g=_.zWb(d,{Lza:[h=>{const k=AWb(a);c.Bo(k,f);c.Bo(k,h);return h}],listeners:[()=>{e||(e=!0,BWb(a,{vId:h=>b.transition(k=>{c.Bo(h,k);return k},"IaLTGb"),cke:h=>{const k=new d;return b.Ma(l=>{if(!c.oa)return!1;const p=_.$Vb("");let q,r;(r=(q=c.oa).wp)==null||r.call(q,l,p);h(p);let u,A;(A=(u=c.oa).Bo)==null||A.call(u,p,k);return!_.Mk(k,l)},()=>k,"IaLTGb")},aRd:c}))}]});b.Ha(g)};
CWb=function(a,b,c){a.listeners.set(b,c);return a};_.sw=function(a,b,c){CWb(a,c,(d,e,f,g)=>{b===e&&c(d,f,g)})};
_.tw=class{constructor(a){this.Aa=a;this.state=new this.Aa;this.fT=new Set;this.listeners=new Map;this.Ia=new Set;this.Ba=()=>{const b=this.state.clone();for(const c of this.Ia)c(b);return b};this.Ca=b=>{this.state=b};this.La=(b,c,d,e)=>{for(const f of this.listeners.values())try{f(b.clone(),c,d,e)}catch(g){_.fa(g)}};this.oa=_.zWb(this.Aa,{getCurrent:this.Ba,listeners:[this.Ca]})}Br(){return this.Aa}listen(a){return CWb(this,a,a)}unlisten(a){this.listeners.delete(a)}get(){return this.Ba()}transition(a,
b="E8jfse"){return _.zWb(this.Aa,{getCurrent:this.Ba,Lza:[a],x$a:this.Ca,fT:this.fT,listeners:[this.La],zub:b})}Ma(a,b,c="E8jfse"){return _.zWb(this.Aa,{getCurrent:this.Ba,Lza:[{sdd:a,Kie:b}],x$a:this.Ca,fT:this.fT,listeners:[this.La],zub:c})}initialize(a=new Map){if(!this.oa)return Promise.resolve();var b=this.oa,c=b.run,d=new _.aWb;d.eventType="sKlcvd";a=c.call(b,d.and(_.wWb,a));this.oa=null;return a}Ha(a){this.oa&&(this.oa=this.oa.compose(a))}Da(a){this.fT.add(a)}Pa(a){this.Ia.add(a)}};_.uw=class{constructor(a){const b=_.zWb(a.Br(),{Lza:[(c,d)=>(d=d.get("R84DPe")||null)?d.clone():c]});a.Ha(b)}};
var xmr=class{constructor(){this.oa=[]}async run(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{if(a.length){var e=a[0];for(let g=1;g<a.length;g++)e=e.compose(a[g]);var f=c(await d(e.run(_.Fw({replace:!!b}))));f.dBb(4)&&this.oa.push(f)}}finally{d()}}goBack(){return this.oa.length>0?this.oa.pop().V4a():_.Bg()}};var Bmr,Cmr,zmr,ymr;_.Amr=function(a,b){ymr==null&&(ymr=new zmr(a,b));return ymr};Bmr=function(a){if(a=="")return{n6a:!0};var b=a.split(",");if(b.length<2)return{n6a:!1,Wub:null};a=b[0];const c=b[1];let d="";b.length>=2&&(d=b[2]);let e="";b.length>=3&&(e=b[3]);b=_.rm(c);let f=null;b&&(d||e)&&(f=b.querySelector(e?`[data-local-attribute=${e}]`:`[data-dtype=${d}]`));return{n6a:!1,entryPoint:a,Uja:c,widget:d,Wub:b,Zkd:f,CMa:e}};
Cmr=function(a,b){return a.n6a!=b.n6a||a.entryPoint!=b.entryPoint||a.Uja!=b.Uja||a.widget!=b.widget||a.CMa!=b.CMa};
_.Dmr=function(a,b){var c=Bmr(a.oa),d=Bmr(b);if((Cmr(c,d)||a.Aa)&&!(b.indexOf("d3sbx")>=0))if(d.n6a){if(a.oa=b,a.Ca=!1,d=_.wmr)a.Aa?(a.Aa=!1,d.closeDialog(),d.eZa()):d.mLa()}else if(d.Wub){a.oa=b;a.Ca=!1;if(c.Wub){if((b=!c.n6a&&!d.n6a&&c.entryPoint==d.entryPoint&&c.Uja==d.Uja&&(c.widget!=d.widget||c.CMa!=d.CMa))&&d.widget)d.Zkd&&(c=_.wmr)&&c.Fnb(d.Zkd);else{c=a.Aa;a.Aa=!1;const e=_.wmr;e&&e.closeDialog();if(c){e&&e.eZa();return}}if(b)return}a.Ha=d.widget||"";a.Da=d.CMa||"";a=_.rJc(d.Wub);a.set("entry_point",
d.entryPoint);_.nz(d.Wub,{context:a})}else a.Bh(""),a.Ca=!0};_.Emr=function(a,b){return a.sca.transition(c=>c.setValue(b))};_.Fmr=function(a,b){return a.iE.transition(c=>c.setPage(b))};
zmr=class{constructor(a,b){this.iE=a;this.sca=b;this.Da=this.Ha=this.oa="";this.Ca=this.Ia=this.Aa=!1;this.Ba=new xmr;this.sca.get().getValue().trim()&&(this.Ia=!0);this.sca.listen(c=>{this.fM(c)});this.fM(this.sca.get())}fM(a){(0,_.Bf)(()=>_.Dmr(this,a.getValue()))}async Bh(a,b){var c=(0,_.Pf)(),d=c();c=c(1);try{if(this.Ha){const h=document.querySelector(this.Da?"[data-local-attribute="+this.Da+"]":"[data-dtype="+this.Ha+"]");h&&(0,_.Bf)(()=>{const k=_.wmr;k&&k.Fnb(h)});this.Da=this.Ha=""}else{var e=
Bmr(this.oa),f=Bmr(a);if(Cmr(e,f)){this.oa=a;var g=this.iE.get().Aa();if(_.yw()||!(f.widget!=""&&f.widget!=void 0||g!=""&&g.startsWith("d3")))c(await d(this.Ba.run([_.Emr(this,a)],!!b)));else{let h=f.widget||"";const k=f.Uja+"-"+h;_.Cjd.has(k)&&(h=k);_.djd();c(await d(this.Ba.run([_.Emr(this,a),_.Fmr(this,h)],!!b)))}}}}finally{d()}}La(){this.Aa=!0;this.Ba.goBack()}goBack(){return this.Ba.goBack()}};ymr=null;var Gmr=class extends _.m{constructor(a){super(a)}getValue(){return _.t(this,1)}setValue(a){return _.$g(this,1,a)}clearValue(){return _.Pe(this,1)}hasValue(){return _.lh(this,1)}};Gmr.prototype.kb="bgmrdf";var Hmr={pC(){return["duf3"]},Bo(a,b){_.Yv(new _.dw(a.oa,b),"duf3",b.setValue,b.clearValue)},wp(a,b){_.aw(new _.dw(b.oa,a),a.hasValue,a.getValue,"duf3")}};var Imr;Imr=null;_.Jmr=class extends _.tw{constructor(a,b){super(a);new _.uw(this);_.rw(b,this,new _.qw(Hmr))}static Br(){return Gmr}static Zr(a){return Imr?Imr:Imr=_.pw().then(b=>{b=new _.Jmr(Gmr,b);b.initialize(a);return b})}};_.Uo.bgmrdf=_.To;
_.gzq=_.y("EkevXb",[]);
var CXb=class extends _.m{constructor(a){super(a)}Aa(){return _.t(this,1)}setPage(a){return _.$g(this,1,a)}Ca(){return _.Pe(this,1)}Ba(){return _.lh(this,1)}};CXb.prototype.kb="OLea4d";var DXb={pC(){return["fpstate"]},Bo(a,b){_.Yv(new _.dw(a.oa,b),"fpstate",b.setPage,b.Ca)},wp(a,b){_.aw(new _.dw(b.oa,a),a.Ba,a.Aa,"fpstate")}};var EXb;EXb=null;_.FXb=class extends _.tw{constructor(a,b){super(a);new _.uw(this);_.rw(b,this,new _.qw(DXb))}static Br(){return CXb}static Zr(a){return EXb?EXb:EXb=_.pw().then(b=>{b=new _.FXb(CXb,b);b.initialize(a);return b})}};_.Uo.OLea4d=_.To;
_.v("EkevXb");
_.cs(_.gzq,class extends _.as{static Ta(){return{We:{iE:_.FXb,sca:_.Jmr}}}constructor(a){super();a=this.oa=_.Amr(a.We.iE,a.We.sca);a.Ca&&_.Dmr(a,a.sca.get().getValue())}});

_.x();
_.jlh=_.y("fCxEDd",[]);
_.v("fCxEDd");
_.klh=class extends _.fo{constructor(){super();this.Dxa=null}};_.Yf(_.jlh,_.klh);
_.x();
_.Bld=_.y("WlNQGd",[]);
_.Ald=function(a){const b=a.event.detail;return b&&b.type?b.type==="menu_item_selected":String(a.type)==="mMf61e"};
_.v("WlNQGd");
var Cld,Eld,Dld,Fld,Gld,Ild,Hld,Jld,Lld,Kld;Cld=class{constructor(a,b,c){this.trigger=a;this.Zya=b;this.iK=c}};Eld=function(a){var b=a.oa();_.Ka(b,c=>{const d=_.eE(a,c);if(d.isSelected()&&d.isEnabled())switch(d.getType()){case 2:Dld(a);d.Lk(!0);a.Da=c;break;case 3:d.Lk(!0);a.Ia.push(c);break;default:d.Lk(!1)}else d.Lk(!1)},a);b=b[0];_.eE(a,b).oa()&&b.setAttribute("tabindex","0")};_.eE=function(a,b){return a.TWa.find(c=>c.getRoot().el()===b)};Dld=function(a){a.Da&&(_.eE(a,a.Da).Lk(!1),a.Da=null)};
Fld=function(a,b,c=!1){if(b){const d=_.eE(a,b);if(!d.isEnabled()&&c)return;d.Aa(!0);d.oa()&&b.setAttribute("tabindex","0")}else a.menu.setAttribute("tabindex","0"),a.menu.focus();a.Aa!==b&&a.Aa&&(c=_.eE(a,a.Aa),c.oa()&&a.Aa.setAttribute("tabindex","-1"),c.Aa(!1));a.Aa=b};Gld=function(a,b){return!!a.oa().find(c=>c===b)};
Ild=function(a,b,c){const d=_.eE(a,b);if(d.isEnabled()){Fld(a,b);switch(d.getType()){case 2:var e=a.Da!==b;e&&(Dld(a),a.Da=b,d.Lk(!0));Hld(a,d,e,c);break;case 3:e=!d.isSelected();d.Lk(e);e?a.Ia.push(b):_.Ba(a.Ia,b);Hld(a,d,!0,c);break;case 5:a=a.getRoot().el();_.Rg(a,"LyWNEf");break;case 11:c=a.getRoot().el();a={trigger:b,nwd:a.oa()};_.Rg(c,"pjqKnd",a);break;default:Hld(a,d,!1,c)}d.isSelected()}};Hld=function(a,b,c,d){a=a.getRoot().el();_.Rg(a,"mMf61e",new Cld(b,c,d))};
Jld=function(a){a=a.targetElement;let b,c;for(;a.el()!=null&&((b=a.el())==null?void 0:b.tagName)!=="G-MENU-ITEM"&&((c=a.el())==null?void 0:c.tagName)!=="G-MENU";)a=a.parent();let d;return((d=a.el())==null?void 0:d.tagName)==="G-MENU-ITEM"?a.el():null};Lld=function(a,b){return(b?Kld(a,!0):a.oa()).find(c=>_.eE(a,c).isEnabled()?(c=_.eE(a,c).getContent(),_.laa(c,a.prefix)):!1)};
Kld=function(a,b){let c=a.Aa,d=a.oa().filter(e=>_.fn(e));c===null&&(a.menu.getAttribute("tabindex")==="0"||d.length>0&&d[0].getAttribute("tabindex")==="0")&&(c=b?_.va(d):d[0]);c&&(a=d.findIndex(e=>c===e),d=_.opb(d,b?-a-1:-a),a=d.findIndex(e=>c===e));return d};
_.fE=class extends _.as{static Ta(){return{controllers:{TWa:{jsname:"NNJLud",ctor:_.rh},Qae:{jsname:"hgDUwe",ctor:_.rh},JAd:{jsname:"tqp7ud",ctor:_.rh}}}}constructor(a){super();this.Da=null;this.Ia=[];this.Aa=null;this.prefix="";this.TWa=[...a.controllers.TWa,...a.controllers.Qae,...a.controllers.JAd];this.menu=this.getRoot().el();this.Qa=_.Mla(this.menu)==="listbox";this.Ma=new _.Cr(this.ub,1E3,this);_.si(this,this.Ma);Eld(this)}Ib(){return this.Aa}oa(){const a=[...this.Jb("NNJLud").toArray()].filter(c=>
!_.eE(this,c).lBb()),b=this.qb("tqp7ud").el();b&&a.push(b);return a}Lb(){return this.TWa}ub(){this.prefix=""}clearSelection(){for(const a of this.oa()){const b=_.eE(this,a);if(b.isSelected()&&b.isEnabled())switch(b.getType()){case 2:Dld(this);break;case 3:this.Ia.pop();break;case 1:case 7:case 6:case 4:case 5:case 10:break;default:b.getType()}b.Lk(!1)}Fld(this,null)}Ba(a,b=!1){Gld(this,a)&&Ild(this,a,b)}qp(){return this.Da}Qb(){return this.Ia}Cb(){return this.Aa}Ca(){const a=this.qp();return a?_.eE(this,
a).getContent():""}Pa(){const a=this.oa()[0];return a?this.getElementToFocus(a):null}Kb(a=!1){const b=this.qp();b&&this.Qa?a=b:a?a=(a=_.va(this.oa()))?this.getElementToFocus(a):null:a=this.Pa();return a}getElementToFocus(a){var b=_.eE(this,a);if(b.getType()!==6&&b.getType()!==10)return a;b=(new _.lo([a])).find("*").toArray();return(a=[a].concat(b).find(c=>_.Kg(c)&&_.fn(c)&&(c.getAttribute("role")==="menuitem"&&c.hasAttribute("tabindex")||_.Mm(c))))?a:null}Ha(a){a&&!Gld(this,a)||Fld(this,a)}Tb(a){const b=
Jld(a);if(b){var c=a.event;(c=c?c.which||c.keyCode:null)&&c===32?this.rl(a):Ild(this,b,!0)}}Wa(){this.Aa===null&&Fld(this,this.oa()[0])}Xa(){var a=this.getRoot().el();_.Rg(a,"OVY1kd")}Za(){var a=this.getRoot().el();_.Rg(a,"nunXZ");Fld(this,null)}rb(a){(a=Jld(a))&&Fld(this,a,!0)}rl(a){const b=a.event;if(!b||b.ctrlKey||b.metaKey||b.shiftKey||b.altKey)return!1;var c=b.which||b.keyCode;let d=!1;if(c===27)return!0;if(c===40||c===38){var e=this.Aa;const g=this.oa();e=c===38?e===g[0]:e===g.pop();if(!this.Qa||
!e){c=40===c;e=Kld(this,c);var f;c=(f=c?e.shift():e.pop())!=null?f:null;Fld(this,c);this.La(this.Aa)}}else if(c===13||c===32&&!this.prefix)this.Aa&&(d=_.eE(this,this.Aa).getType()===6||_.eE(this,this.Aa).getType()===10,Ild(this,this.Aa,!0));else if(_.PJa(c))this.Ma.start(),f=String.fromCharCode(c),this.prefix===f?f=Lld(this,!0):(this.prefix+=f,f=Lld(this,!1)),f&&(Fld(this,f),this.La(this.Aa));else return!1;if(a.wb.el().contains(b.target)){let g;(g=b.stopPropagation)==null||g.call(b);if(!d){let h;
(h=b.preventDefault)==null||h.call(b)}}return!1}La(a){a&&(this.Sa(a),(a=this.getElementToFocus(a))&&a.focus())}Sa(a,b){if(a){var c=_.bn(this.menu);if(c.height<this.menu.scrollHeight){var d=this.menu.getBoundingClientRect().top;const e=_.bn(a);d=a.getBoundingClientRect().top-d;const f=e.height/2;d<f?this.menu.scrollTop+=d-f:d+e.height>c.height-f&&(this.menu.scrollTop+=d+e.height-c.height+f);b&&(this.menu.scrollTop+=a.getBoundingClientRect().top-this.menu.getBoundingClientRect().top-Math.floor((c.height-
e.height)/2))}}}};_.fE.prototype.$wa$uYT2Vb=function(){return this.rl};_.fE.prototype.$wa$IgJl9c=function(){return this.rb};_.fE.prototype.$wa$Tx5Rb=function(){return this.Za};_.fE.prototype.$wa$WOQqYb=function(){return this.Xa};_.fE.prototype.$wa$h06R8=function(){return this.Wa};_.fE.prototype.$wa$PSl28c=function(){return this.Tb};_.fE.prototype.$wa$xpRsNe=function(){return this.Pa};_.fE.prototype.$wa$OG2qqc=function(){return this.Ca};_.fE.prototype.$wa$kvm28d=function(){return this.Cb};
_.fE.prototype.$wa$mFs2Sc=function(){return this.Qb};_.fE.prototype.$wa$Urwwkf=function(){return this.qp};_.fE.prototype.$wa$J2hPTe=function(){return this.clearSelection};_.fE.prototype.$wa$gSmKPc=function(){return this.Lb};_.fE.prototype.$wa$lSpRlb=function(){return this.oa};_.fE.prototype.$wa$mJ60jb=function(){return this.Ib};_.cs(_.Bld,_.fE);
_.x();
_.hXi=_.y("UHgVpe",[_.Kq,_.Tq,_.fr,_.jlh,_.Bld]);
_.eXi=function(a){var b=new _.QRc;return _.pj(b,1,a)};_.fXi=function(a,b){return _.vi(a,1,_.HRc,b)};_.gXi=_.Sb(_.RRc);
_.dXi=class extends _.m{constructor(a){super(a)}getData(){return _.dj(this,4)}setData(a){return _.jk(this,4,a)}hasData(){return _.Ek(this,4)}getFileName(){return _.t(this,5)}tD(){return _.t(this,6)}Sca(){return _.wj(this,6)}mQ(){return _.t(this,7)}};
_.YWi=class extends _.m{constructor(a){super(a)}getWidth(){return _.yj(this,3)}Bi(){return _.zk(this,3)}Gj(){return _.cj(this,3)}getHeight(){return _.yj(this,4)}setHeight(a){return _.Rh(this,4,a)}Lg(){return _.zk(this,4)}};_.ZWi=class extends _.m{constructor(a){super(a)}getZoom(){return _.yj(this,4,1)}setZoom(a){return _.Rh(this,4,a)}};_.$Wi=class extends _.m{constructor(a){super(a)}Gx(){return _.t(this,1)}vp(){return _.t(this,2)}};_.aXi=class extends _.m{constructor(a){super(a)}};
_.bXi=class extends _.m{constructor(a){super(a)}getType(){return _.zj(this,1)}setType(a){return _.kk(this,1,a)}kQ(){return _.n(this,_.aXi,5)}tZ(a){return _.Kb(this,_.aXi,5,a)}};_.bXi.prototype.Aa=_.Ub(_.mVi);_.cXi=_.Rb(_.bXi,_.mVi);
_.yWi=!!(_.Ei[49]>>17&1);_.zWi=!!(_.Ei[49]>>18&1);_.AWi=!!(_.Ei[49]>>19&1);_.BWi=!!(_.Ei[49]>>21&1);_.CWi=!!(_.Ei[49]>>22&1);_.DWi=!!(_.Ei[49]>>23&1);_.EWi=!!(_.Ei[49]>>24&1);_.FWi=!!(_.Ei[49]>>25&1);_.GWi=!!(_.Ei[49]>>26&1);_.HWi=!!(_.Ei[49]>>27&1);_.IWi=!!(_.Ei[49]>>28&1);_.JWi=!!(_.Ei[49]>>29&1);_.KWi=!!(_.Ei[50]&1);_.LWi=!!(_.Ei[50]&2);
_.vWi=!!(_.Ei[15]&1);_.wWi=!!(_.Ei[15]&2);_.xWi=!!(_.Ei[15]&4);
_.eWi=!!(_.Ei[16]&4096);_.fWi=!!(_.Ei[16]&8192);_.gWi=!!(_.Ei[16]>>17&1);_.hWi=!!(_.Ei[16]>>19&1);_.iWi=!!(_.Ei[16]>>22&1);_.jWi=!!(_.Ei[16]>>25&1);_.kWi=!!(_.Ei[16]>>26&1);_.CV=!!(_.Ei[16]>>27&1);_.lWi=!!(_.Ei[16]>>29&1);_.mWi=!!(_.Ei[17]&1);_.nWi=!!(_.Ei[17]&2);_.oWi=!!(_.Ei[17]&4);_.pWi=!!(_.Ei[17]&32);_.qWi=!!(_.Ei[17]&64);_.rWi=!!(_.Ei[17]&1024);_.sWi=!!(_.Ei[17]&2048);_.tWi=!!(_.Ei[17]&8192);_.uWi=!!(_.Ei[17]>>14&1);
_.v("UHgVpe");
var jXi,mXi,nXi,oXi,kXi,iXi,rXi;jXi=function(a,b,c,d){c&&(_.Vi(c,_.bXi,7)?a.searchParams.set("vsint",_.Ma(iXi(_.n(c,_.bXi,7)),4)):d&&_.Fe(b,3)>1&&(b=(0,_.cXi)(_.Oa(d)),b=_.Pe(b,7),a.searchParams.set("vsint",_.Ma(iXi(b),4))))};
_.lXi=function(a,b,c,d,e){let f=2;const g=async()=>{var h=(0,_.Pf)(),k=h();h=h(1);try{if(a!=null&&a.isAvailable()){var l=new _.bu(b.If()),p=l.searchParams.get("udm"),q=l.searchParams.get("nem");if(p!=="50"&&q!=="143"){try{h(await k(a.Kb(r=>{const u=new _.bu(e);var A=r.Bta(),E;const I=(E=_.jh(r,_.xVi,2,_.kh())[0])==null?void 0:_.n(E,_.BTd,2);E=I?_.Ma((0,_.XWi)(I),4):null;const N=u.searchParams.get("q");var P=u.searchParams.get("vsrid");P=E&&E!==P;const T=new _.QRc;_.Kk(r,9).forEach((ka,da)=>{u.searchParams.set(da,
ka)});([4,6,7].includes(_.zj(r,15))||_.B(r,12))&&u.searchParams.set("imgn","1");u.searchParams.set("aep","63");_.GWi&&u.searchParams.set("lns_oq",N);const Z=_.EWi?d.Dxa:null;let ca;(ca=_.n(r,_.QRc,8))==null||_.jh(ca,_.HRc,1,_.kh()).filter(ka=>_.yWi||!_.Xi(ka,_.dXi,1,_.Qz)).forEach(ka=>{_.fXi(T,ka)});Z?(u.searchParams.set("mstk",Z),u.searchParams.set("csuir","1"),u.searchParams.set("aioh","1"),u.searchParams.set("mq",A),!P&&_.gWi||u.searchParams.set("mqvsrid",E)):(l.searchParams.has("vsrid")?u.searchParams.set("q",
A):_.zWi?(_.fXi(T,(new _.HRc).hc(kXi(N).setIcon((new _.Pz).setType(79).setSize(22)))),u.searchParams.set("q",A)):u.searchParams.set("q",N?`${N} ${A}`:A),_.jh(T,_.HRc,1,_.kh()).length>0&&u.searchParams.set("aai",_.Ma((0,_.gXi)(T),4)),u.searchParams.delete("csuir"),u.searchParams.delete("mstk"),u.searchParams.delete("aioh"));_.zj(r,13)===2&&(u.searchParams.delete("udm"),u.searchParams.set("nem","143"));I&&(u.searchParams.set("vsrid",E),(A=Number(l.searchParams.get("lns_surface")))&&A===42&&jXi(u,I,
_.jh(r,_.xVi,2,_.kh())[0],l.searchParams.get("vsint")));c.navigateTo(_.qc(u.toString()))}))),f=0}catch(r){h(),_.df(Error("vp`"+r)),f=1}if(_.xWi)try{h(await k(a.Fc(()=>{c.navigateTo(_.qc(b.location.origin+"/search?udm=50&atvm=1"))})))}catch(r){h(),_.df(Error("wp`"+r))}}}}finally{k()}};g();window.addEventListener("visibilitychange",()=>{window.document.visibilityState==="visible"&&f===1&&g()})};
mXi=function(a){a.searchParams.delete("udm");a.searchParams.delete("tbm");a.searchParams.delete("nem");a.searchParams.delete("nep");a.searchParams.delete("start");a.searchParams.delete("num");a.searchParams.delete("oq");a.searchParams.delete("gs_lp");a.searchParams.delete("ism");a.searchParams.delete("inm");a.searchParams.delete("source");a.searchParams.delete("si")};nXi=function(a){switch(a){case 0:return"-1";case 1:case 3:return"0";case 4:return"1";case 2:return"2"}};
_.pXi=function(a,b,c,d,e,f){return oXi(a,"0",b,"",c,d,e,f)};
oXi=function(a,b,c,d,e,f,g,h){a.searchParams.has("vsrid")&&!a.searchParams.has("q")&&a.searchParams.set("q","");d!==""&&(a.hostname=d);e&&a.searchParams.has("q")&&!f&&a.searchParams.set("q",e);mXi(a);for(const k of qXi.split(","))a.searchParams.delete(k);d=Number(b);d>=0&&(d===0?(a.searchParams.set("udm","50"),a.searchParams.delete("arv")):a.searchParams.set("nem",b));c!==""&&a.searchParams.set("fbs",c);g!==""&&a.searchParams.set("ved",g);h&&a.searchParams.set("aep",h.toString());a.searchParams.set("ntc",
"1");return a};kXi=function(a){var b=new _.ERc;return _.$g(b,1,a)};iXi=_.Sb(_.mVi);rXi=!!(_.Ei[15]&16);var qXi=_.Ei[55]>>14&1?"arv,csuir,mstk,mtid,smstk,smstidx,shndl,shmd,shmds,source,kgs":"";var sXi=function(a,b){return a.getData("hostname").Ob()?_.gm(a.getData("hostname")):b!=null?_.hm(b.getData("host"),""):""},tXi=function(a,b,c,d,e,f){d=sXi(a,d);e=e?_.hm(e.getData("ved"),""):"";b=oXi(new _.bu(a.rc.If()),b,c,d,_.hm(a.getData("dq"),""),_.LWi,e,f);a.Yb.navigateTo(_.qc(b.toString()))},uXi=function(a,b){const c=document.querySelector('[jsname="y2FPdf"]');if(c){var d,e,f=(e=(d=c.textContent)==null?void 0:d.split(" > "))!=null?e:[];if(f.length!==0){var g,h;if(a=((h=(g=a.Wo)==null?void 0:
_.eE(g,b))==null?void 0:h.getValue())||"")if(a==="0")c.textContent=f[0];else if(a==="1"||a==="2")c.textContent=`${f[0]} > Pro`}}},vXi=class extends _.as{static Ta(){return{service:{rc:_.Vv,Yb:_.Az,Wrb:_.iVi,tEa:_.klh},zd:{menu:{jsname:"S6sggc",ctor:_.fE}}}}constructor(a){super();this.oa=this.Wo=null;this.rc=a.service.rc;this.Yb=a.service.Yb;this.Wo=a.zd.menu;if(_.AWi&&this.getData("mgtv").Ob()){var b=oXi(new _.bu(this.rc.If()),_.gm(this.getData("mgtv")),_.hm(this.getData("fbs"),""),"",_.hm(this.getData("dq"),
""),_.LWi,"1t:244952",63);_.lXi(a.service.Wrb,a.service.rc,a.service.Yb,a.service.tEa,b.toString())}}Ca(){_.nw||this.oa||(this.oa=()=>{if(!this.getRoot().el().hasAttribute("data-ilm")){var a=this.getRoot().el();_.Rg(a,"A05xBd")}},window.addEventListener("scroll",this.oa,{passive:!0}))}Ba(){this.oa&&(window.removeEventListener("scroll",this.oa),this.oa=null)}Vb(){this.oa&&(window.removeEventListener("scroll",this.oa),this.oa=null);super.Vb()}Ha(a){if(this.getData("mgtv").Ob()){const b=_.gm(this.getData("mgtv")),
c=_.hm(this.getData("fbs"),"");tXi(this,b,c,a.targetElement,a.wb,1)}}La(a){const b=_.gm(a.wb.getData("mgtv"));tXi(this,b,"",a.targetElement,a.wb)}Da(a){var b=a.data.trigger,c=a.data.Zya;if(b!=null&&c)if((c=b.Wl())&&(c=c.dataset.ved?c:c.querySelector("a[data-ved]"))&&_.hw(c),b.getData("optionDropdown").Ob())this.Aa(a);else if(a=_.hm(b.getData("nrp"),""),a===""&&(a=_.hm(b.getData("redirectPath"),"")),a===""){var d=_.hm(this.getData("fbs"),"");tXi(this,b.getValue(),d,b.getRoot(),b)}else{c=b.getRoot();
b=a;var e=_.hm(c.getData("ncp"),"");e===""&&(e=_.hm(c.getData("redirectParams"),""));a=this.rc.If();c=sXi(this,c);a=new _.bu(a);var f=c;f===""&&(f=a.hostname);b=b.split("?");var g=b[0];c=b.length>1?b[1]:"";b=a.clone();g.startsWith("/")?(b.hostname=f,b.pathname=g):b=new _.bu(g);e=e.split(",");f=new Map;g=!1;for(var h=0;h<e.length;++h)e[h]==="*"?g=!0:e[h].startsWith("-")&&f.set(e[h].substring(1),!0);if(g){mXi(b);for(d of f.keys())b.searchParams.delete(d)}else for(b.searchParams.setValue(""),d=0;d<e.length;++d)if(f=
e[d],a.searchParams.has(f))for(g=a.searchParams.getAll(f),h=0;h<g.length;++h)b.searchParams.append(f,g[h]);d=new Map;if(c!==""){a=new URLSearchParams(c);for(const [k,l]of a)a=k,c=l,d.has(a)?b.searchParams.append(a,c):(b.searchParams.set(a,c),d.set(a,!0))}d=b;(b=_.hm(this.getData("dq"),""))&&d.searchParams.has("q")&&!_.LWi&&d.searchParams.set("q",b);d=_.qc(d.toString());this.Yb.navigateTo(d)}}Aa(){const a=document.body.querySelector('[jsname="dheN8e"]');a&&this.Uc(a,_.Ao,b=>{b.oa(a)})}Ia(a){const b=
a.data.trigger;a=a.data.nwd;b.classList.contains("V8KfWe")?b==null||b.classList.remove("V8KfWe"):(a.forEach(c=>{c.classList.remove("V8KfWe")}),b==null||b.classList.add("V8KfWe"))}Ma(a){if(rXi){a=a.data;var b=document.querySelector('[jsname="H1cYZb"]');if(a!==0&&b){var c=nXi(a),d=this.Wo;(a=d==null?void 0:d.oa().find(e=>{let f;return((f=d==null?void 0:_.eE(d,e))==null?void 0:f.getValue())===c}))&&a!==(d==null?void 0:d.qp())&&(d==null||d.clearSelection(),d==null||_.eE(d,a).Lk(!0),uXi(this,a))}}}};
vXi.prototype.$wa$fqmbjc=function(){return this.Ma};vXi.prototype.$wa$C70bfd=function(){return this.Ia};vXi.prototype.$wa$JxAq2e=function(){return this.Aa};vXi.prototype.$wa$zlgt8b=function(){return this.Da};vXi.prototype.$wa$I9Eaue=function(){return this.La};vXi.prototype.$wa$vr907=function(){return this.Ha};vXi.prototype.$wa$k4Iseb=function(){return this.Vb};vXi.prototype.$wa$fduAUd=function(){return this.Ba};vXi.prototype.$wa$hBzrpf=function(){return this.Ca};_.cs(_.hXi,vXi);
_.x();
_.v("PGyklf");
_.VOc=class extends _.as{constructor(){super();this.root=this.getRoot().el()}isEnabled(){return!this.root.hasAttribute("disabled")&&!this.root.hasAttribute("aria-disabled")}focus(){_.ua()&&this.root.blur();this.root.focus()}setEnabled(a){a?this.root.removeAttribute("disabled"):this.root.setAttribute("disabled","true");_.Xd(this.root,"disabled",!a)}getContent(){const a=this.qb("ibnC6b").el();return a?_.Nm(a):""}getValue(){return this.value}oa(){return this.root}};_.VOc.prototype.$wa$L4rKVc=function(){return this.oa};
_.VOc.prototype.$wa$HvnK2b=function(){return this.getValue};_.VOc.prototype.$wa$aDGs4d=function(){return this.getContent};_.VOc.prototype.$wa$AHmuwe=function(){return this.focus};_.VOc.prototype.$wa$yXgmRe=function(){return this.isEnabled};
_.x();
_.aPc=_.gr("PGyklf",[]);
_.bPc=_.y("pzkXnb",[_.aPc]);
_.v("pzkXnb");
_.cPc=class extends _.VOc{constructor(){super();this.value=_.hm(this.getData("v"),"");this.Eqc=this.getData("o").Ob();this.isLink=this.getData("l").Ob();this.mM=this.getData("s").Ob();this.root.getAttribute("disabled")&&this.setEnabled(!1);this.root.addEventListener("click",()=>{})}Ca(){return this.mM}focus(){if(this.isLink){let a;(a=this.oa().querySelector("a"))==null||a.focus()}else super.focus()}Oc(){this.mM&&this.isEnabled()?this.Lk(!this.isSelected()):!this.isLink&&this.isEnabled()&&this.trigger("UszG1b",
{Eqc:this.Eqc});this.notify("aZcdhc");return!0}Ba(){this.trigger("L8zncc")}Aa(a){(a=a.event.relatedTarget)&&this.trigger("M9oBfd",{relatedTarget:a})}isSelected(){return this.mM&&(_.Zd(this.root,"checked")==="true"||_.Zd(this.root,"selected")==="true")}Lk(a){this.mM&&(a&&this.isEnabled()?(_.Xd(this.root,"checked","true"),this.trigger("UBsZj")):a||(_.Xd(this.root,"checked","false"),this.trigger("JkcjMe")))}};_.cPc.prototype.$wa$KKjvXb=function(){return this.isSelected};_.cPc.prototype.$wa$MDJmo=function(){return this.Aa};
_.cPc.prototype.$wa$rESl3=function(){return this.Ba};_.cPc.prototype.$wa$h5M12e=function(){return this.Oc};_.cPc.prototype.$wa$AHmuwe=function(){return this.focus};_.cPc.prototype.$wa$pxaUTb=function(){return this.Ca};_.cs(_.bPc,_.cPc);
_.x();
_.HOc=_.y("Mbif2",[_.Rq,_.Vq,_.bo]);
_.v("Mbif2");
var IOc,LOc,MOc;IOc=[1,2,3];
_.KOc=function(a,b=!1){var c=_.JOc(a,a.controller),d=a.controller.oa(),e=_.lJa(d),f=_.lJa(c)-c.scrollLeft;e-=f;var g=_.ie(d),h=e+_.bn(d).width/2;e=h-9.5;f=a.oa.get(_.JOc(a,a.controller));var k=f.container;var l=k.style.display,p=k.style.position,q=k.style.visibility;if(a.isVisible(a.controller))k=new _.Md(k.offsetWidth,k.offsetHeight);else{k.style.visibility="hidden";k.style.position="absolute";k.style.display="block";var r=new _.Md(k.offsetWidth,k.offsetHeight);k.style.display=l;k.style.position=
p;k.style.visibility=q;k=r}p=k.width;r=k.height;l=a.controller.Cb();q=a.controller.ub();k=0;if(!_.mm.contains(f.container,"SiOjJb")){switch(l){case 5:case 2:k=h-p/2;break;case 4:case 1:k=h-(g?p-9.5-q:9.5+q);break;case 6:case 3:k=h-(g?9.5+q:p-9.5-q)}k=Math.max(c.scrollLeft+8,k);g=c===a.window.getDocument().body?_.Wh(a.window.get()).width:c.offsetWidth;k=Math.min(k,g+c.scrollLeft-8-p);g=parseInt(_.Tm(f.container,"border-radius"),10)||0;k=Math.min(k,e+g);k=Math.max(k,e+19+g-p)}b&&(k=Math.max(k,0));g=
parseInt(_.Tm(d,"padding-top"),10)||0;b=!1;h=IOc.indexOf(l)!==-1;q=g+9.5+r-1;l=_.Wm(d);c=c!==a.window.getDocument().body?c.scrollTop-_.Wm(c):0;p=_.bn(d).height;const u=d.getBoundingClientRect().top;d=u-q>=0;q=u+p+q<=_.Wh(a.window.get()).height;a=a.controller.Wa();h&&(q||!a)||!h&&!d&&a?(a=c+l+p+g,d=a+9.5-1):(a=c+l-g-9.5,d=a-r+1,b=!0);_.Rm(f.container,"left",`${k}px`);_.Rm(f.container,"top",`${d}px`);_.Rm(f.cta,"left",`${e}px`);_.Rm(f.cta,"top",`${a}px`);b?_.mm.add(f.cta,"IBPZu"):_.mm.remove(f.cta,
"IBPZu")};_.JOc=function(a,b){return b.Sa()&&_.rm(b.Sa())||b.Ib()&&b.getRoot().el().offsetParent||a.window.getDocument().body};_.NOc=function(a){if(a.controller){_.fg(a.controller.oa(),"sendDismissEvent")&&a.controller.trigger("pD7Wob");var b=a.oa.get(_.JOc(a,a.controller));a.Aa&&(a.Da=+_.eg(a.controller.getRoot().el(),"du"));a.controller=null;b&&(b.container.__owner=void 0,a.dismiss.unlisten(b.container),a.Aa?(LOc(b,!1),a.Ha=(0,_.Wn)(()=>{MOc(b)},a.Da)):MOc(b))}};
LOc=function(a,b){const c=a.container;a=a.cta;b?(_.mm.g_(c,"bE3Kif","nFdFHf"),_.mm.g_(a,"bE3Kif","nFdFHf")):(_.mm.g_(c,"nFdFHf","bE3Kif"),_.mm.g_(a,"nFdFHf","bE3Kif"))};MOc=function(a){_.Rm(a.container,{display:"none",width:"","z-index":""});_.Rm(a.cta,{display:"none","z-index":""});_.EVb(a.eZ);_.mm.set(a.container,"QyJI3d");_.mm.set(a.cta,"tYmfxe");_.mm.set(a.Chd,"oQcPt")};
_.OOc=class extends _.fo{static Ta(){return{service:{dismiss:_.xv,Bc:_.Ku,window:_.co}}}constructor(a){super();this.Ba=this.controller=null;this.Ia=0;this.Aa=!1;this.Ha=null;this.Da=0;this.oa=new Map;this.Pb=a.service.Bc;this.dismiss=a.service.dismiss;this.window=a.service.window;_.me(this.window.get(),"resize",()=>{this.controller&&_.KOc(this)})}Vb(){super.Vb();this.oa.forEach(a=>{_.Jm(_.rm(a.containerId));_.Jm(_.rm(a.Dhd))})}Ca(a,b){this.isVisible(this.controller)&&(this.log(!1,a,b),_.NOc(this))}log(a,
b,c){const d=this.controller.Ma();b=b&&_.Ge(b)?b:void 0;d&&_.Ge(d)&&(c=b?new _.Kh(_.Ge(b),c||2):void 0,a?this.Pb.Aa(d,c):this.Pb.Ba(d,c))}onDismiss(a,b){const c=this.controller?this.controller.rb():!1;let d;if(b&&((d=this.controller)==null?0:d.Wb(b)))return!1;this.Ca(b);a===2&&this.Ba&&this.Ba.focus();return c}p9(a){const b=a.container;_.Rm(b,{display:"block"});_.Ig(b,this.controller.getRoot().el());_.fg(this.controller.oa(),"sendShowEvent")&&this.controller.trigger("tA6Kcd");this.controller.Za()||
(a.content.focus(),_.DVb(a.eZ),this.dismiss.listen(a.container,(c,d)=>this.onDismiss(c,d)));_.Rm(a.cta,{display:"block"});this.Aa&&((0,_.Xn)(this.Ha),LOc(a,!0))}isVisible(a){if(!a)return!1;a=this.oa.get(_.JOc(this,a));return!!a&&_.Tm(a.container,"display")==="block"}tga(a){this.controller&&(a=this.oa.get(_.JOc(this,this.controller)).content.querySelector(`[jsname=${a}]`))&&_.Kg(a)&&_.Mm(a)&&a.focus()}};_.Yf(_.HOc,_.OOc);
_.x();
_.v("ipWLfe");

_.x();
var POc=_.gr("ipWLfe",[]);_.QOc=_.y("QVaUhf",[_.HOc,POc]);
_.v("QVaUhf");
var ROc,SOc,TOc,UOc;
ROc=function(a,b){b=_.JOc(a,b);var c=a.oa.get(b);if(c)return c;c=_.Am("DIV","QyJI3d");const d="gbbl-"+String(a.Ia++);c.id=d;_.en(c,!1);var e=_.Am("DIV");_.$m(e,0);_.dn(e,0);_.Xd(e,"hidden",!0);_.Ud(e,"button");_.KIa(e,!0);c.appendChild(e);const f=_.Am("DIV");f.tabIndex=-1;const g=new _.FVb(f);_.Rm(f,"outline","none");c.appendChild(f);_.me(e,"focus",()=>{((new _.lo([f])).find("*").toArray().reverse().find(l=>_.Kg(l)?_.Mm(l):!1)||f).focus()});e=e.cloneNode(!0);_.KIa(e,!0);_.me(e,"focus",()=>{((new _.lo([f])).find("*").toArray().find(l=>
_.Kg(l)?_.Mm(l):!1)||f).focus()});c.appendChild(e);e=_.Am("DIV",["oQcPt"]);const h=_.Am("DIV",["tYmfxe"],e),k="gbblt-"+String(a.Ia++);h.id=k;_.en(h,!1);c={container:c,containerId:d,content:f,eZ:g,cta:h,Dhd:k,Chd:e};a.oa.set(b,c);return c};
SOc=function(a,b,c,d,e=!1,f=!1,g=0,h="",k="",l,p=!1,q=!1){a.Aa=q;_.NOc(a);if(q=b.Ma()){q=q.parentNode?q.parentNode:q;a.controller=b;var r=ROc(a,b);var u=_.JOc(a,b);_.rm(r.containerId)||u.appendChild(r.container);_.rm(r.Dhd)||u.appendChild(r.cta);_.Xd(r.container,"hidden",!1);u=a.controller.oa();g===1?(_.mm.add(r.container,"PnQMie"),_.mm.add(r.cta,"PnQMie")):g===2&&(_.mm.add(r.container,"LWen5c"),_.mm.add(r.cta,"LWen5c"));h&&_.mm.addAll(r.container,h.split(" "));k&&_.mm.addAll(r.Chd,k.split(" "));
d!==null&&(_.Rm(r.container,"z-index",d),_.Rm(r.cta,"z-index",d+1));p&&_.Rm(r.container,"max-width","100%");_.mm.enable(r.container,"SiOjJb",f);_.mm.enable(r.container,"QJnoze",e);c>0&&!f&&_.Rm(r.container,{width:`${c}px`});b.Pa()?r.container.setAttribute("aria-label",b.Pa()):r.container.removeAttribute("aria-label");_.Ud(r.container,b.Xa()?"dialog":"alertdialog");b=r.content;_.Fm(b);for(const A of q.childNodes)b.appendChild(A.cloneNode(!0));a.Ba=a.window.getDocument().activeElement;_.KOc(a,p);a.p9(r);
a.log(!0,u,l)}};TOc=class extends _.as{};UOc=function(a,b,c){a=_.eg(a,b)||"";a=_.Zl(a);return isNaN(a)?c:a};
_.tz=class extends TOc{static Ta(){return{service:{dtb:_.OOc}}}constructor(a){super();this.Ia=this.Ca=this.Da=null;this.Ha=a.service.dtb;this.Tb=_.rn(()=>this.Ka("bN97Pc").el());this.Rb=_.rn(()=>this.Ka("d6wfac").el());this.Qa=!_.fg(this.oa(),"lzyAct")}Kb(a){const b=a.event;b&&this.Da&&this.isVisible()&&b.clientX===this.Da.clientX&&b.clientY===this.Da.clientY&&b.timeStamp-this.Da.timeStamp<200||this.Ba(void 0,3);this.Da=null;a.event.preventDefault&&a.event.preventDefault();return _.fg(this.oa(),"sendOpenEvent")}Ba(a,
b){var c=this.oa();if(a===!1||!a&&this.isVisible())this.Qa?this.La(c,b):this.Ia=null;else if(this.Qa){a=UOc(c,"theme",0);var d=UOc(c,"zidx",0);d=d>=1?d:null;var e=UOc(c,"width",200),f=_.fg(c,"fullWidth"),g=_.fg(c,"roundedCorners"),h=_.eg(c,"extraContainerClasses"),k=_.eg(c,"extraTriangleClasses"),l=this.getData("ctv").Ob();c=_.fg(c,"enableToggleAnimation");SOc(this.Ha,this,e,d,g,f,a,h,k,b,l,c);b=this.getData("f");b.Ob()&&this.Ha.tga(b.string())}else this.Ia=b}Lb(){this.Qa=!0;this.Ia!==null&&(this.Ba(!0,
this.Ia),this.Ia=null)}p9(a){this.Ba(!0,a)}Aa(a){this.Ba(!1,a?3:void 0)}Qb(a){const b=this.oa();(new _.qo(b)).focus();this.Aa(a)}qc(){return!1}onMouseEnter(a){_.fg(this.oa(),"sendOpenEvent")&&this.trigger("aKmQDb",a.targetElement);this.p9(9);this.Da=a.event;return!1}onMouseLeave(){this.Da&&(this.Ba(!1,9),this.Da=null)}zc(a){this.Ca!==null&&((0,_.Xn)(this.Ca),this.Ca=null);if(!this.isVisible())if(_.fg(this.oa(),"delayOpenOnHover"))this.Ca=(0,_.Wn)(()=>this.onMouseEnter(a),UOc(this.oa(),"hoverOpenDelay",
500));else this.onMouseEnter(a);return!1}Ec(){this.Ca!==null&&((0,_.Xn)(this.Ca),this.Ca=null);this.isVisible()&&(this.Ca=(0,_.Wn)(()=>this.Aa(),UOc(this.oa(),"hoverHideDelay",1E3)))}Ma(){return this.Tb()}oa(){return this.Rb()}Vb(){this.isVisible()&&_.NOc(this.Ha);super.Vb()}Wb(a){return _.Wg(this.oa(),a)}La(a,b){this.isVisible()&&this.Ha.Ca(a,b)}isVisible(){var a=this.Ha;return a.controller===this&&a.isVisible(this)}Wa(){return this.getData("ci").Ob()}Cb(){return UOc(this.getRoot().el(),"tp",2)}ub(){return UOc(this.getRoot().el(),
"to",10)}Za(){return this.getData("df").Ob()}rb(){return _.fg(this.oa(),"disableDismissEventBubbling")}Sa(){return this.getData("sc").Ob()?_.gm(this.getData("sc")):null}Ib(){return this.getData("oc").Ob()}Pa(){return _.hm(this.getData("al"),"")}Xa(){return this.getData("da").Ob()}};_.tz.prototype.$wa$x2QzWe=function(){return this.Xa};_.tz.prototype.$wa$jZ0cf=function(){return this.Pa};_.tz.prototype.$wa$wu4W6e=function(){return this.Ib};_.tz.prototype.$wa$A4M6Rd=function(){return this.Sa};
_.tz.prototype.$wa$YWMfPe=function(){return this.rb};_.tz.prototype.$wa$plyROe=function(){return this.Za};_.tz.prototype.$wa$zxO7z=function(){return this.ub};_.tz.prototype.$wa$qIUUyb=function(){return this.Cb};_.tz.prototype.$wa$Dntuwf=function(){return this.Wa};_.tz.prototype.$wa$eO2Zfd=function(){return this.isVisible};_.tz.prototype.$wa$k4Iseb=function(){return this.Vb};_.tz.prototype.$wa$lI3Pp=function(){return this.oa};_.tz.prototype.$wa$noyIOe=function(){return this.Ma};
_.tz.prototype.$wa$JDTRYd=function(){return this.Ec};_.tz.prototype.$wa$jTlRtf=function(){return this.zc};_.tz.prototype.$wa$iFHZnf=function(){return this.onMouseLeave};_.tz.prototype.$wa$MJEKMe=function(){return this.onMouseEnter};_.tz.prototype.$wa$NLMyWb=function(){return this.qc};_.tz.prototype.$wa$DLNOs=function(){return this.Qb};_.tz.prototype.$wa$VqIRre=function(){return this.Aa};_.tz.prototype.$wa$dou8Ld=function(){return this.Lb};_.tz.prototype.$wa$vQLyHf=function(){return this.Kb};
_.cs(_.QOc,_.tz);
_.x();
_.Aps=class{constructor(a){this.oa=a}};var Bps=class extends _.Aps{constructor(a,b){super(a);this.Ba=b;this.Aa=null}wI(){if(this.Aa)return this.Aa;const a=[];for(var b=this.oa.xb;b instanceof gbar.I&&b!=this.Ba.oa;)a.push(b.ic()),b=b.zb();for(b=this.Ba;a.length>0;)b=b.JJa(a.pop());return this.Aa=b}getType(){return this.oa.xa}};var Cps=class extends _.Aps{listen(a,b,c,d){const e=this;return this.oa.za(a,function(f){return b.call(d||_.ea,new Bps(f,e))},c)}listenOnce(){throw Error("bo");}unlisten(){throw Error("bo");}Tu(){throw Error("bo");}dispatchEvent(){throw Error("bo");}removeAllListeners(){throw Error("bo");}H4a(){throw Error("bo");}fireListeners(){throw Error("bo");}x4a(){throw Error("bo");}w4a(){throw Error("bo");}hasListener(){throw Error("bo");}};Cps.prototype[_.yJa]=!0;var Dps=class extends Cps{getHeight(){return this.oa.pa()}setDarkMode(a){this.oa.pp(a);return this}};var Eps=class extends Cps{constructor(a){super(a);this.Aa=null}getId(){return this.oa.ia()}Ka(){return this.oa.ib()}getModel(){return this.Aa}setModel(a){this.Aa=a;return this}};var Fps=class extends Eps{constructor(a){super(a);this.Ba={}}JJa(a){var b=this.Ba[a];if(b)return b;if(b=this.oa.ja(a)){const c=b.__wc;if(!c)throw Error("lx");b=new c(b);return this.Ba[a]=b}return null}};var Gps=class extends Fps{getContent(){return this.oa.ca()}open(a){this.oa.cf(a)}close(a){this.oa.cg(a)}getStyle(){return this.oa.ch()}isOpen(){return this.oa.ck()}};var Hps;Hps=function(a,b){const c=a.Aa;return c?function(d){b.call(this,new c(d))}:b};_.Ips=class extends _.Aps{constructor(a,b){super(a);this.Aa=b||null}then(a,b,c){let d;a&&(d=Hps(this,a));this.oa.aa(d,b,c)}};var Jps;_.Kps=function(){return new Promise(a=>{window.gbar||(window.gbar={});if(window.gbar.a)return a(Jps.getInstance());(new Promise(b=>{window.gbar.ap=b})).then(()=>a(Jps.getInstance()))})};Jps=class extends _.Aps{constructor(a){super(a||gbar.a);this.Ba=this.Aa=null}c5(){this.Aa||(this.Aa=new _.Ips(this.oa.bf(),Dps));return this.Aa}um(){this.Ba||(this.Ba=new _.Ips(this.oa.ba(),Gps));return this.Ba}static getInstance(){return _.Dh(Jps)}};
var wps;_.xps=function(){var a=new wps;a=_.Qh(a,1,1);return _.Qh(a,2,4)};wps=class extends _.m{constructor(a){super(a)}yR(){return _.Xj(this,1)}};wps.prototype.kb="SMSkB";var yps=class extends _.m{constructor(a){super(a)}};yps.prototype.kb="s5PeBc";new _.pi(wps);new _.pi(yps,1E3);_.Uo.s5PeBc=_.To;_.zps=new _.ci("VbSMl",yps,wps,[_.ai,!1,_.$h,"/MyactivityService.ExternalDelete"]);new _.pi(wps);new _.pi(yps,1E3);_.Uo.s5PeBc=_.To;
var SDg,UDg,YDg;SDg=function(){var a={};const b=_.dIa(_.fIa("/blank.html"));if(!QDg.test(b))throw Error("Ql`"+b);const c=b.replace(RDg,function(d,e){if(!Object.prototype.hasOwnProperty.call(a,e))throw Error("Rl`"+e+"`"+b+"`"+JSON.stringify(a));d=a[e];return d instanceof _.bIa?_.dIa(d):encodeURIComponent(String(d))});return _.jc(c)};_.VDg=function(a){var b=SDg();b=_.kc(b);b=TDg.exec(b);const c=b[3]||"";return _.wka(b[1]+UDg("?",b[2]||"")+UDg("#",c,a),{justification:"Deprecated, but safe closure/html builder"})};
UDg=function(a,b,c){if(c==null)return b;if(typeof c==="string")return c?a+encodeURIComponent(c):"";for(const e in c)if(Object.prototype.hasOwnProperty.call(c,e)){var d=c[e];d=Array.isArray(d)?d:[d];for(let f=0;f<d.length;f++){const g=d[f];g!=null&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(e)+"="+encodeURIComponent(String(g)))}}return b};
_.ZDg=function(a,b){a&&_.kc(a);var c={};c.src=a||null;c.srcdoc=void 0;var d={sandbox:""};a={};for(var e in c)Object.prototype.hasOwnProperty.call(c,e)&&(a[e]=c[e]);for(const h in d)Object.prototype.hasOwnProperty.call(d,h)&&(a[h]=d[h]);if(b)for(var f in b)if(Object.prototype.hasOwnProperty.call(b,f)){e=f.toLowerCase();if(e in c)throw Error("U");e in d&&delete a[e];a[f]=b[f]}b=void 0;c="";if(a)for(g in a)if(Object.prototype.hasOwnProperty.call(a,g)){if(!WDg.test(g))throw Error("U");d=a[g];if(d!=null){f=
g;if(f.toLowerCase()=="style")d=String(d);else{if(/^on/i.test(f))throw Error("U");if(f.toLowerCase()in XDg)if(d instanceof _.hc)d=_.kc(d).toString();else if(_.Kia(d))d=_.nc(d);else if(typeof d==="string")d=_.qc(d).toString();else throw Error("U");}f=`${f}="`+_.uaa(String(d))+'"';c+=" "+f}}var g="<iframe"+c;b==null?b=[]:Array.isArray(b)||(b=[b]);YDg.iframe===!0?g+=">":(a=_.$ia(b),g+=">"+_.ec(a)+"</iframe>");return _.z(g)};
YDg={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var RDg=/%{(\w+)}/g,QDg=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),TDg=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,WDg=/^[a-zA-Z0-9-]+$/,XDg={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};
var jps=function(a){let b=a,c;return function(){if(b){const d=b;b=void 0;c=d.apply(this,arguments)}return c}},kps=function(a){try{a[0].commonConfig.frdProductData&&(a[0].commonConfig.frdProductDataSerializedJspb=a[0].commonConfig.frdProductData.serialize(),a[0].commonConfig.frdProductData=void 0)}catch(b){}try{let b;if((b=a[0].commonGseConfig)==null?0:b.gseSessionOptions)a[0].commonGseConfig.gseSessionOptionsSerializedJspb=a[0].commonGseConfig.gseSessionOptions.serialize(),a[0].commonGseConfig.gseSessionOptions=
void 0}catch(b){}try{a[0].startingFlow&&(a[0].startingFlowSerializedJspb=a[0].startingFlow.serialize(),a[0].startingFlow=void 0)}catch(b){}return a},lps=async function(a,b,c){var d=(0,_.Pf)(),e=d();d=d(1);try{const f=d(await e(a.oa)),g=f[b];if(!g)throw Error("hx`"+b);return g.apply(f,c)}finally{e()}},mps=class{constructor(a){this.oa=a;this.wm=null;a.then((0,_.oe)(function(){},this),()=>{},this)}},pps=function(a,b,c){const d=Array(arguments.length-2);for(var e=2;e<arguments.length;e++)d[e-2]=arguments[e];
e=nps(a,b).then(f=>f.apply(null,d),f=>{f=Error("ix`"+b+"`"+a+"`"+f,{cause:f});delete ops[b];return _.yh(f)});return new mps(e)},ops={},nps=function(a,b){var c=ops[b];if(c)return c;c=(c=_.Di(b))?_.Bg(c):(new _.Lg(function(d,e){const f=(new _.gIa(document)).createElement("SCRIPT");f.async=!0;_.Nc(f,_.jc(_.dIa(a)));f.onload=f.onreadystatechange=function(){f.readyState&&f.readyState!="loaded"&&f.readyState!="complete"||d()};f.onerror=g=>{e(Error("jx`"+b+"`"+a,{cause:g}))};(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){const d=
_.Di(b);if(!d)throw Error("kx`"+b+"`"+a);return d});return ops[b]=c};var qps={GOOGLE:"https://www.google.com",yZe:"https://support.google.com",cRe:"https://play.google.com"},rps=async function(a){var b=(0,_.Pf)(),c=b();b=b(1);try{for(const d of Object.values(qps))try{b(await c(navigator.permissions.query({name:"top-level-storage-access",requestedOrigin:d}))).state!=="granted"&&a.oa.push(d)}catch(e){b();break}}finally{c()}};var sps,tps,ups;sps=_.fIa("https://www.google.com/tools/feedback/open_to_help_guide_lazy.js");tps=_.fIa("https://www.google.com/tools/feedback/help_api.js");_.vps=function(a,b){let c=tps,d="help.api.Lazy.create";(b==null?void 0:b.AQd)===1&&(c=sps,d="help.api.HelpGuideLazy.create");a=pps(c,d,a);return new ups(a)};
ups=class{constructor(a){this.xxa=a}async oa(a){var b=(0,_.Pf)(),c=b();b=b(1);try{b(await c(lps(this.xxa,"openHelp",kps(arguments))))}finally{c()}}async Aa(a){await lps(this.xxa,"openToGse",kps(arguments))}async close(){var a=(0,_.Pf)(),b=a();a=a(1);try{a(await b(lps(this.xxa,"close",arguments)))}finally{b()}}};
(new class{constructor(){this.oa=[];this.Aa=[];this.initialize=jps(async()=>{var a=(0,_.Pf)(),b=a();a=a(1);try{if(typeof document==="undefined"||document.requestStorageAccessFor===void 0||navigator.permissions===void 0||navigator.permissions.query===void 0||location.hostname.match(".+\\.google\\.com$"))return Promise.resolve();a(await b(rps(this)));this.oa.length>0&&document.addEventListener("click",this.Ba)}finally{b()}});this.Ba=()=>{if(!(this.Aa.length>0)){for(const a of this.oa)try{this.Aa.push(document.requestStorageAccessFor(a))}catch(b){}Promise.all(this.Aa).then(()=>
{}).catch(()=>{}).finally(()=>{this.reset()})}}}reset(){document.removeEventListener("click",this.Ba)}}).initialize();
_.Zgq=_.y("SJpD2c",[_.Io,_.Vq,_.QOc]);
_.v("SJpD2c");
var Lps=function(a,b=!1){a.oa.sh(b)},Mps=class extends _.Aps{},Nps=function(a){a.Ca||(a.Ca=new _.Ips(a.oa.bk(),Mps));return a.Ca},Ops=!!(_.Ei[57]&8192);var Pps=function(a,b,c){return{id:b,callable:()=>{a.logClick(c)},url:null}},Qps=function(a){return(b,c)=>{var d;const e=(d=a.getRoot())==null?void 0:d.el();b=a.isSignedIn?e:b;d=a.Pb.oa();e&&_.Kp(d,e,c?1:2);b&&_.Ip(d,b,3);d.log(!0)}},Rps=function(a){const b=_.vps("196"),c=_.td(_.sd("QrtxK"),0).toString(),d=!!document.body.dataset.dt,e=document.body.querySelector("[jsname='AYtejb']"),f={commonConfig:{helpCenterPath:"websearch",authuser:c,locale:_.hm(_.sd("GWsdKe"),"en")},helpPanelConfig:{helpPanelTheme:d?
1:0,helpPanelMode:1,fixedHelpPanelContainer:e?e:void 0},r9e:!0,iTa:{bucket:"Default"}};return{id:"og-am-hf",callable:()=>{a.logClick(a.Ka("uO6mde").el());b.oa(f)},url:null}},Sps=function(a,b,c){const d=[Pps(a,"og-am-ss",a.Ka("NG1V7d").el()),Pps(a,"og-am-lg",a.Ka("IZKNDc").el()),Pps(a,"og-am-ms",a.Ka("tP7ayb").el())];c?d.push(Rps(a)):d.push(Pps(a,"og-am-hf",a.Ka("uO6mde").el()));a.isSignedIn?(Ops&&d.push(Pps(a,"og-am-cca",a.qb("ZOjQVc").el())),d.push(Pps(a,"og-am-qdc-qd",a.Ka("hJoEPd").el()),Pps(a,
"og-am-qdc-sh",a.Ka("micRse").el()),{id:"og-am-qdc-dt",callable:()=>a.oa(),url:null},{id:"og-am-qdc-fsb",callable:()=>{a.Aa()},url:null},Pps(a,"og-am-cp-int",a.qb("t5CbBf").el()),Pps(a,"og-am-ps",a.qb("Du1Fsb").el()),Pps(a,"og-am-sop",a.qb("bicHfd").el()))):d.push(Pps(a,"og-am-pc",a.qb("nSxrjf").el()));a.Ba&&d.push(Pps(a,"og-am-dm",a.qb("pxGDvf").el()));b.oa.sf(d)},Tps=function(a,b){_.Kps().then(c=>{Nps(c).then(d=>{Sps(a,d,b);a.isSignedIn&&Ops&&d.oa.sk([{callable:null,id:"og-am-cca",isHidden:!1,label:null,
mainIconName:null,subLabel:null,url:null}]);d.oa.sj(Qps(a))})})},Ups=class extends _.as{static Ta(){return{service:{Me:_.yr,Pb:_.Ku},controllers:{Dfc:{jsname:"ovbFm",ctor:_.tz}}}}logClick(a){a!=null&&_.Ip(this.Pb.oa(),a,3).log(!0)}constructor(a){super();this.y_=null;this.isSignedIn=!this.getData("so").Ob();const b=this.getData("iph").Ob();this.Ba=this.getData("dmt").Ob();this.Rd=a.service.Me;this.Dfc=a.controllers.Dfc[0];this.Pb=a.service.Pb;this.logger=null;Tps(this,b);this.isSignedIn&&_.uh(this,
{controllers:{y_:"PWj1Zb"}}).then(c=>{this.y_=c.controllers.y_[0]})}async oa(){var a=(0,_.Pf)(),b=a();a=a(1);try{try{const c=_.xps();a(await b(this.Rd.Kc(_.zps.getInstance(c))));return!0}catch(c){return a(),!1}}finally{b()}}Aa(){let a;(a=this.y_)==null||a.show()}Da(){let a;(a=this.Dfc)==null||a.p9()}async Ca(a){var b=(0,_.Pf)(),c=b();b=b(1);try{const d=a.data.HUd,e=b(await c(_.Kps()));Lps(b(await c(Nps(e))),d)}finally{c()}}};Ups.prototype.$wa$FPeyVe=function(){return this.Ca};
Ups.prototype.$wa$MMAZpe=function(){return this.Da};Ups.prototype.$wa$BjElId=function(){return this.Aa};Ups.prototype.$wa$BlH6Ne=function(){return this.oa};_.cs(_.Zgq,Ups);
_.x();
_.OVb=_.y("eX5ure",[_.Vq]);
_.v("eX5ure");
var PVb=class extends _.as{static Ta(){return{service:{Pb:_.Ku}}}constructor(a){super();this.parentElement=null;this.root=this.getRoot().el();this.id=this.getRoot().el().getAttribute("data-id");this.Ca=this.getRoot().el().hasAttribute("data-dc");this.Da=this.getRoot().el().hasAttribute("data-dw");this.oa=_.ei(this.getRoot().getData("backDisabled"),!1);this.Pb=a.service.Pb;this.registerContent()}Ba(){return this.root}Vb(){}registerContent(){this.trigger("jxvro",{controller:this})}Ha(a){a=a.wb.el();
this.trigger("dBhwS",{triggerElement:a})}Gcd(a){this.parentElement=a}getId(){return this.id}isDefault(){return this.Ca}hide(){_.en(this.root,!1)}Mmc(a){this.hide();_.Ge(this.root)&&_.Ip(_.Kp(this.Pb.oa(),this.root,2),a).log()}show(a){_.Rm(this.root,{display:"block"});var b=this.qb("LBJcic").el();const c=this.qb("X0x7he").el();(b||this.oa)&&c&&(!this.oa&&b&&(a?_.Rm(b,{display:"inline-block"}):_.en(b,!1)),b=this.qb("vDg59d").el(),this.Da?(a=a?220:248,b&&(a-=48),_.Rm(c,"width",`${a}px`)):b&&_.Rm(c,"width",
`calc(100% - ${48+(a?28:0)}px)`))}RHb(a,b){this.show(a);_.Ge(this.root)&&_.Ip(_.Kp(this.Pb.oa(),this.root,1),b).log()}Sec(a){const b=a.event.target;let c,d;const e=(d=(c=a.data)==null?void 0:c.contentId)!=null?d:b.getAttribute("data-id");this.parentElement&&this.He(this.parentElement).then(f=>f.Ia(e,b))}Aa(a){const b=a.wb.el();this.parentElement&&this.He(this.parentElement).then(c=>{if(c.Ca.length>0){c.Aa.Mmc(b);const d=c.Ca.pop(),e=c.Ca.length>0;c.Aa=d;d.RHb(e,b)}})}};PVb.prototype.$wa$iO11jf=function(){return this.Aa};
PVb.prototype.$wa$uOhSee=function(){return this.Sec};PVb.prototype.$wa$ZYIfFd=function(){return this.hide};PVb.prototype.$wa$paynGb=function(){return this.isDefault};PVb.prototype.$wa$pTuYge=function(){return this.getId};PVb.prototype.$wa$QQtcRd=function(){return this.Ha};PVb.prototype.$wa$CHHOAf=function(){return this.registerContent};PVb.prototype.$wa$k4Iseb=function(){return this.Vb};PVb.prototype.$wa$xdy80=function(){return this.Ba};_.cs(_.OVb,PVb);
_.x();
_.WEC=function(){return window.matchMedia?window.matchMedia("(forced-colors: active)").matches?2:window.matchMedia("(forced-colors: none)").matches?1:0:0};
_.nwq=_.y("zGLm3b",[]);
_.v("zGLm3b");
var aFC=!!(_.Ei[0]&2);var bFC=!!(_.Ei[24]>>16&1);var cFC=!!(_.Ei[60]>>23&1);var dFC=!!(_.Ei[25]>>16&1);var eFC=new _.On,fFC=class extends _.as{constructor(){super();this.oa=_.Ln(eFC,a=>new a(this.getRoot()));this.Aa();this.Ba()}Aa(){const a=_.Yg();for(const b of this.oa){const c=b.kYb();c&&a.Lc(c[0],c[1])}a.log()}Ba(){var a="";for(var b of this.oa){const c=b.u_b();c&&(a.length>0&&(a+="&"),a+=c.join("="))}a.length>0&&(a=_.ana(`/client_204?${a}`,new Map,!1,!1),b=new _.rr,b.setWithCredentials(!0),b.send(a))}};fFC.prototype.$wa$ZhdDvf=function(){return this.Ba};fFC.prototype.$wa$fgCVyc=function(){return this.Aa};
_.cs(_.nwq,fFC);var gFC=class{constructor(a){this.Aa=this.oa=0;this.oa=_.WEC();this.Aa=_.td(a.getData("fc"),0)}kYb(){return["fc",String(this.oa)]}u_b(){return this.oa!==this.Aa?["fc",String(this.oa)]:null}};aFC&&_.Mn(eFC,gFC);var hFC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-contrast: less)").matches?"1":window.matchMedia("(prefers-contrast: more)").matches?"2":window.matchMedia("(prefers-contrast: custom)").matches?"3":"0":"0";this.Aa=_.hm(a.getData("pcon"),"-1")}kYb(){return["pcon",this.oa]}u_b(){return this.oa!==this.Aa?["pcon",this.oa]:null}};cFC&&_.Mn(eFC,hFC);var iFC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?"1":window.matchMedia("(prefers-color-scheme: dark)").matches?"2":"0":"0";this.Aa=_.hm(a.getData("pcs"),"0")}kYb(){let a="4";this.oa==="1"?a="2":this.oa==="2"&&(a="3");return["dt19",`${a}`]}u_b(){return this.oa!==this.Aa?["cs",this.oa]:null}};dFC&&_.Mn(eFC,iFC);var jFC=class{constructor(a){this.Aa=this.oa="0";this.oa=window.matchMedia&&(window.matchMedia("(prefers-reduced-motion)").matches||window.matchMedia("(prefers-reduced-motion: reduce)").matches)?"1":"0";this.Aa=a.getData("prm").Ob()?"1":"0"}kYb(){return["prm23",this.oa]}u_b(){return this.oa!==this.Aa?["prm",this.oa]:null}};bFC&&_.Mn(eFC,jFC);
_.x();
_.v("L8KGxe");
_.Yf(_.f0a,class extends _.fo{static Ta(){return{service:{window:_.co}}}constructor(a){super();this.window=a.service.window}get(){return this.window.get()}getDocument(){return this.window.getDocument()}find(a){return(new _.qo(this.getDocument().documentElement)).find(a)}});
_.x();
_.DQq=_.y("NyWhAc",[_.Vq]);
_.wNq=_.y("FIzMp",[]);
_.OMq=_.y("HbcOOb",[]);
_.eMq=_.y("Cd223",[_.Aq,_.Wq,_.ni]);
_.cMq=_.y("X4lYGb",[_.Aq,_.Wq]);
_.JLq=_.y("DR4yb",[]);
_.SKq=_.y("tokonb",[]);
_.SJq=_.y("G2zoeb",[_.Vq]);
_.gEq=_.y("jRLbY",[_.Vq]);
_.qBq=_.y("pAgBU",[]);
_.OAq=_.y("p5rP6",[_.ni]);
_.vxq=_.y("xAb0Tc",[_.Aq,_.Wq]);
_.hxq=_.y("HJhqMe",[]);
_.gxq=_.y("jLqWIc",[]);
_.fxq=_.y("nVPlNd",[_.Vq]);
_.Twq=_.y("b4mtSe",[_.ni,_.Vq,_.Wq]);
_.mwq=_.y("fHChbd",[]);
_.kwq=_.y("OHB8qd",[_.Aq,_.Wq,_.uZa]);
_.jwq=_.y("xup2k",[_.u0a]);
_.bwq=_.y("zuTkjc",[_.ni,_.Vq]);
_.$vq=_.y("M5Cm4b",[]);
_.pvq=_.y("dwQcv",[_.ni]);
_.qtq=_.y("aV3GZc",[_.Aq,_.Bya,_.Vq,_.Wq]);
_.Bsq=_.y("n9Sscf",[_.Kq]);
_.xsq=_.y("MNMT3d",[]);
_.osq=_.y("NzKC9b",[]);
_.Xmq=_.y("k5amqf",[_.Aq,_.k3a]);
_.eLj=_.y("GvcUpe",[_.u0a]);
_.dKj=_.y("EDPXZb",[_.u0a]);
_.NYi=_.y("pWObQe",[_.u0a]);
_.AYi=_.y("QHMAaf",[_.u0a]);
_.oF=_.y("yb08jf",[]);_.md(_.oF);
_.Pai=_.y("wVv2xf",[_.oF,_.Vq]);
_.z9h=_.y("hBCH7c",[_.Vq]);
_.Bef=_.y("k0SRie",[]);
_.Aef=_.y("Sfc5C",[]);
_.O5e=_.y("CIT9Te",[_.Vq]);
_.zWe=_.y("sUYMvd",[_.Aq,_.Wq,_.uZa]);
_.v("mGCtob");
var XqB={[28]:_.gEq,[1]:_.z9h,[3]:_.Pai,[4]:_.b1a,[5]:_.Aef,[19]:_.Bef,[17]:_.hxq,[14]:_.qBq,[6]:_.w0a,[9]:_.dKj,[11]:_.NYi,[13]:_.v0a,[15]:_.AYi,[22]:_.eLj,[27]:_.DQq,[29]:_.jwq,[7]:_.xsq,[8]:_.SKq,[10]:_.JLq,[12]:_.fxq,[16]:_.I0a,[18]:_.wNq,[20]:_.$vq,[33]:_.bwq,[21]:_.kwq,[41]:_.zWe,[23]:_.osq,[25]:_.O5e,[26]:_.Twq,[30]:_.Bsq,[31]:_.gxq,[32]:_.OMq,[34]:_.pvq,[35]:_.eMq,[36]:_.OAq,[37]:_.vxq,[38]:_.qtq,[39]:_.SJq,[40]:_.cMq,[42]:_.mwq,[43]:_.Xmq},YqB=[5,19];_.Yf(_.O0a,class extends _.fo{dkc(a){return XqB[a]}ppc(a){return YqB.includes(a)}});
_.x();
_.LAr=!!(_.Ei[25]&2);_.MAr=!!(_.Ei[25]&4);
_.v("PQ2Aoe");
var EGA=function(a,b){a=`data-${_.mqa(a)}`;return b?`[${a}="${b}"]`:`[${a}]`},FGA=function(a,b,c,d){const e=[];return{pme:document.createTreeWalker(a.commonAncestorContainer,NodeFilter.SHOW_ELEMENT,{acceptNode:f=>{if(!a.intersectsNode(f))return NodeFilter.FILTER_REJECT;if(f instanceof Element&&((c==null?0:c.has(f))||(d==null?0:d.has(f)))){const g=String(e.length);e.push({lNa:f,ERc:c==null?void 0:c.get(f),Q5d:d==null?void 0:d.get(f)});f.dataset.copyServiceCallbackId=g;b.push(f)}return f instanceof
Element&&(c==null?0:c.has(f))?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),Jfc:e}},HGA=function(a,b,c){const d=[],{pme:e,Jfc:f}=FGA(a,d,b,c);for(b=e.currentNode;b;){if(!(b instanceof HTMLElement)){b=e.nextNode();continue}const g=window.getComputedStyle(b);c=g.display==="none"||g.visibility==="hidden"||g.opacity==="0"||g.height==="0px"&&g.width==="0px";d.push(b);if(c)b.dataset.copyServicePrune="";else{g.display!=="contents"&&g.display!=="inline"||b.tagName!=="DIV"||(b.dataset.copyServiceReplaceDivWithSpan=
"");const h=document.createElement("div");GGA.forEach(k=>{const l=g.getPropertyValue(k);l&&h.style.setProperty(k,l)});b.tagName==="IMG"&&(c=g.getPropertyValue("object-fit"))&&(h.style.setProperty("object-fit",c),h.style.setProperty("width",g.getPropertyValue("width")),h.style.setProperty("height",g.getPropertyValue("height")));h.style.cssText&&(b.dataset.copyServiceComputedStyle=h.style.cssText)}b=e.nextNode()}a=a.cloneContents();a.querySelectorAll(EGA("copyServicePrune")).forEach(g=>{g.remove()});
a.querySelectorAll(EGA("copyServiceReplaceDivWithSpan")).forEach(g=>{const h=document.createElement("span");for(;g.firstChild;)h.appendChild(g.firstChild);for(const k of["copyServiceComputedStyle","copyServiceCallbackId"])g instanceof HTMLElement&&k in g.dataset&&(h.dataset[k]=g.dataset[k]);g.replaceWith(h)});d.forEach(g=>{for(const h of["copyServiceComputedStyle","copyServicePrune","copyServiceCallbackId","copyServiceReplaceDivWithSpan"])delete g.dataset[h]});return{fragment:a,Jfc:f}},IGA=function(a,
b,c){for(let f=0;f<b.length;f++){var d=String(f);const {lNa:g,ERc:h,Q5d:k}=b[f];if(d=a.querySelector(EGA("copyServiceCallbackId",d)))if(c&&k){var e=k(g);e?d.replaceWith(document.createTextNode(e)):d.remove()}else h&&((e=h(g))?d.replaceWith(e):d.remove())}},GGA="font-family font-size font-weight margin text-decoration border-bottom".split(" ");_.Yf(_.W2a,class extends _.fo{static Ta(){return{service:{logging:_.Ku,location:_.Vv}}}constructor(a){super();this.Aa=new Map;this.Ca=new Map;this.oa=new Set;this.Ba=b=>{_.LAr&&this.pEa&&_.Hp(this.Oe.oa(),_.Lh(this.pEa,2)).log();if(_.MAr&&b.clipboardData){var c=window.getSelection();if(c&&c.rangeCount!==0){var d=this.rc.location.origin;const {fragment:A,Jfc:E}=HGA(c.getRangeAt(0),this.Aa,this.Ca);var e=A,f=E;c=document.createElement("div");c.appendChild(e.cloneNode(!0));IGA(c,f,!1);e=document.createTreeWalker(c,
NodeFilter.SHOW_ELEMENT);for(var g=e.currentNode;g;){if(!(g instanceof HTMLElement)){g=e.nextNode();continue}if("copyServiceCallbackId"in g.dataset){let I;if((I=f[Number(g.dataset.copyServiceCallbackId)])==null?0:I.ERc){g=e.nextNode();continue}}var h=g.dataset.copyServiceComputedStyle;h&&(g.style.cssText=h);if(g.tagName==="A"&&g.getAttribute("href")){h=g;var k=h.getAttribute("href");_.Ic(h,(new URL(k,d)).href)}if(g.tagName==="IMG"){k=d;var l=Number(g.style.width.replace("px","")),p=Number(g.style.height.replace("px",
""));if(g instanceof HTMLImageElement&&g.complete&&l&&isFinite(l)&&g.naturalWidth&&p&&isFinite(p)&&g.naturalHeight&&(h=g.src.startsWith("data:"),!h||g.naturalWidth!==l||g.naturalHeight!==p)&&(k=(new URL(g.src)).origin!==(new URL(k)).origin,h||!k||g.crossOrigin==="anonymous")&&(h=document.createElement("canvas"),k=h.getContext("2d"))){h.width=l;h.height=p;l=h.width/g.naturalWidth;p=h.height/g.naturalHeight;p=g.style.objectFit==="contain"?Math.min(l,p):Math.max(l,p);l=g.naturalWidth*p;p*=g.naturalHeight;
k.drawImage(g,Math.floor((h.width-l)/2),Math.floor((h.height-p)/2),l,p);try{const I=h.toDataURL("image/png");g.src=I}catch(I){}}}g=e.nextNode()}for(d=document.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);c=document.createElement("div");c.appendChild(A.cloneNode(!0));IGA(c,E,!0);var q;c=(q=c.textContent)!=null?q:"";var {d$d:r,xF:u}={d$d:d,xF:c};q=!1;r.hasChildNodes()&&(q=document.createElement("div"),q.appendChild(r),b.clipboardData.setData("text/html",q.innerHTML),q=!0);u&&(b.clipboardData.setData("text/plain",
u),q=!0);q&&b.preventDefault()}}};this.Oe=a.service.logging;this.rc=a.service.location}registerCopyRoot(a){for(const b of this.oa){if(b.contains(a))return;a.contains(b)&&(b.removeEventListener("copy",this.Ba),this.oa.delete(b))}this.oa.has(a)||(a.addEventListener("copy",this.Ba),this.oa.add(a))}setLoggingElement(a){this.pEa=a}addElementCallback(a,b){this.Aa.set(a,b)}addPlainTextCallback(a,b){this.Ca.set(a,b)}});
_.x();
});
// Google Inc.
